BBIPED Platform: UserMeshVO Class Reference
UserMeshVO Class Reference
#include <usermeshvo.h>
Public Member Functions
UserMeshVO ()
Constructor.
void addBoundary (QString _boundName, QString _val)
Add a Boundary and its value.
bool containsBoundary (QString _bndName)
Checks if a boundary name is present.
void deleteBoundary (QString _bndName)
Delete a boundary by its name.
QStringList getAssociatedMeshVariables ()
Get the list of associated mesh variables.
QStringList getBoundaryAssociatedValues ()
Get the list of the associated values.
QStringList getBoundaryNameList ()
the the list of boundary names
QString getFilename ()
Get the name of the file.
QString getParentMenu ()
Get the name of the parent menu.
QString getUserName ()
Get the user name.
bool hasAssociatedMeshVariables ()
Check if it has associated Mesh variables (by default false)
void initializeBndAssociatedValuesToDefault (QString _val, int _noElements)
Initialize the boundary associated values to a default value (_val)
void resetValues ()
Reset all lis values.
void setAssociatedMeshVariables (QStringList _list)
Set the list of associated mesh variables.
void setBoundaryAssociatedValues (QStringList _list)
Set the list of associated values.
void setBoundaryNameList (QStringList _list)
Set the list of the boundary names.
void setFilename (QString _name)
Set the file name.
void setHasAssociatedMeshVariables (bool _val)
Set true if it has associated mesh variables, false otherwise.
void setParentMenu (QString _menu)
Destructor.
void setUserName (QString _name)
set the user name
void updateBndValue (QString _boundName, QString _newVal)
Update the boundary value.
Private Attributes
QStringList _associatedMeshVariables
QStringList _boundaryAssociatedValues
QStringList _boundaryNameList
QString _filename
bool _hasAssociatedMeshVariables
QString _parentMenu
QString _userName
Detailed Description
Definition at line 7 of file usermeshvo.h.
Constructor & Destructor Documentation
UserMeshVO::UserMeshVO ()
Constructor.
Definition at line 23 of file usermeshvo.cpp.
References _filename, _hasAssociatedMeshVariables, _parentMenu, and _userName.
 {
     _filename = "";
     _userName ="";
     _parentMenu = "";
     _hasAssociatedMeshVariables = false;
 }
Member Function Documentation
void UserMeshVO::addBoundary (QString _boundName, QString _val)
Add a Boundary and its value.
Parameters
_boundName
_val
Definition at line 158 of file usermeshvo.cpp.
References _boundaryAssociatedValues, _boundaryNameList, and updateBndValue().
Referenced by MeshDialog::saveUserChanges().
 {
     // Firts check if it is already in the name list
     if ( (!_boundaryNameList.isEmpty()) && (_boundaryNameList.contains(_boundName)) )
     {
        updateBndValue(_boundName,_val);
     }else
     {
         _boundaryNameList.append(_boundName);
         _boundaryAssociatedValues.append(_val);
     }
 }
bool UserMeshVO::containsBoundary (QString _bndName)
Checks if a boundary name is present.
Parameters
_bndName
Returns
bool
Definition at line 189 of file usermeshvo.cpp.
References _boundaryNameList.
Referenced by MeshDialog::findMeshVariableToUpdateByBndValue().
 {
     return _boundaryNameList.contains(_bndName);
 }
void UserMeshVO::deleteBoundary (QString _bndName)
Delete a boundary by its name.
Parameters
_bndName
Definition at line 199 of file usermeshvo.cpp.
References _boundaryAssociatedValues, and _boundaryNameList.
Referenced by MeshDialog::saveUserChanges().
 {
     if (_boundaryNameList.isEmpty())
         return;
     int _pos = _boundaryNameList.indexOf(_bndName);
     if (_pos == -1)
         return;
     _boundaryNameList.removeAt(_pos);
     if ( (!_boundaryAssociatedValues.isEmpty()) && (_pos <= _boundaryAssociatedValues.size()))
         _boundaryAssociatedValues.removeAt(_pos);
 }
QStringList UserMeshVO::getAssociatedMeshVariables ()
Get the list of associated mesh variables.
Returns
QStringList
Definition at line 225 of file usermeshvo.cpp.
References _associatedMeshVariables.
Referenced by MeshDialog::initBndNamesInAssociatedMeshVar(), MeshDialog::removeBoundaryNamesInAssociatedVariables(), MeshDialog::saveUserChanges(), and MeshDialog::updateTableWithUserValues().
 {
     return _associatedMeshVariables;
 }
QStringList UserMeshVO::getBoundaryAssociatedValues ()
Get the list of the associated values.
Returns
QStringList
Definition at line 86 of file usermeshvo.cpp.
References _boundaryAssociatedValues.
Referenced by MeshDialog::buildUserBndValueMap(), MeshDialog::initBndNamesInAssociatedMeshVar(), MeshDialog::saveUserChanges(), and MeshDialog::updateTableWithUserValues().
 {
     return _boundaryAssociatedValues;
 }
QStringList UserMeshVO::getBoundaryNameList ()
the the list of boundary names
Returns
QStringList
Definition at line 76 of file usermeshvo.cpp.
References _boundaryNameList.
Referenced by MeshDialog::buildUserBndValueMap(), MeshDialog::initBndNamesInAssociatedMeshVar(), MeshDialog::removeBoundaryNamesInAssociatedVariables(), MeshDialog::saveUserChanges(), and MeshDialog::updateTableWithUserValues().
 {
     return _boundaryNameList;
 }
QString UserMeshVO::getFilename ()
Get the name of the file.
Returns
QString
Definition at line 56 of file usermeshvo.cpp.
References _filename.
Referenced by MeshDialog::buildUserBndValueMap(), MeshDialog::findMeshVariableToUpdateByFileNameVar(), and MeshDialog::removeBoundaryNamesInAssociatedVariables().
 {
     return _filename;
 }
QString UserMeshVO::getParentMenu ()
Get the name of the parent menu.
Returns
QString
Definition at line 46 of file usermeshvo.cpp.
References _parentMenu.
Referenced by MeshDialog::buildUserBndValueMap(), MeshDialog::findMeshVariableToUpdate(), MeshDialog::findMeshVariableToUpdateByBndValue(), MeshDialog::findMeshVariableToUpdateByFileNameVar(), and MeshDialog::updateTableWithUserValues().
 {
     return _parentMenu;
 }
QString UserMeshVO::getUserName ()
Get the user name.
Returns
QString
Definition at line 66 of file usermeshvo.cpp.
References _userName.
Referenced by MeshDialog::findMeshVariableToUpdate(), MeshDialog::saveUserChanges(), and MeshDialog::updateTableWithUserValues().
 {
     return _userName;
 }
bool UserMeshVO::hasAssociatedMeshVariables ()
Check if it has associated Mesh variables (by default false)
Returns
bool
Definition at line 235 of file usermeshvo.cpp.
References _hasAssociatedMeshVariables.
Referenced by MeshDialog::initBndNamesInAssociatedMeshVar(), MeshDialog::removeBoundaryNamesInAssociatedVariables(), MeshDialog::saveUserChanges(), and MeshDialog::updateTableWithUserValues().
 {
     return _hasAssociatedMeshVariables;
 }
void UserMeshVO::initializeBndAssociatedValuesToDefault (QString _val, int _noElements)
Initialize the boundary associated values to a default value (_val)
Parameters
_val
_noElements
Definition at line 255 of file usermeshvo.cpp.
References _boundaryAssociatedValues.
Referenced by MeshDialog::saveUserChanges().
 {
     for (int i = 0; i < _noElements;i++)
         _boundaryAssociatedValues.append(_val);
 }
void UserMeshVO::resetValues ()
Reset all lis values.
Definition at line 177 of file usermeshvo.cpp.
References _boundaryAssociatedValues, and _boundaryNameList.
 {
     _boundaryAssociatedValues.clear();
     _boundaryNameList.clear();
 }
void UserMeshVO::setAssociatedMeshVariables (QStringList _list)
Set the list of associated mesh variables.
Parameters
_list
Definition at line 215 of file usermeshvo.cpp.
References _associatedMeshVariables.
Referenced by MeshDialog::createMeshVariables().
 {
     _associatedMeshVariables = _list;
 }
void UserMeshVO::setBoundaryAssociatedValues (QStringList _list)
Set the list of associated values.
Parameters
_list
Definition at line 126 of file usermeshvo.cpp.
References _boundaryAssociatedValues.
Referenced by MeshDialog::createMeshVariables(), and MeshDialog::initBndNamesInAssociatedMeshVar().
 {
     _boundaryAssociatedValues = _list;
 }
void UserMeshVO::setBoundaryNameList (QStringList _list)
Set the list of the boundary names.
Parameters
_list
Definition at line 116 of file usermeshvo.cpp.
References _boundaryNameList.
Referenced by MeshDialog::createMeshVariables(), MeshDialog::initBndNamesInAssociatedMeshVar(), and MeshDialog::saveUserChanges().
 {
     _boundaryNameList = _list;
 }
void UserMeshVO::setFilename (QString _name)
Set the file name.
Parameters
_name
Definition at line 96 of file usermeshvo.cpp.
References _filename.
Referenced by MeshDialog::createMeshVariables().
 {
     _filename = _name;
 }
void UserMeshVO::setHasAssociatedMeshVariables (bool _val)
Set true if it has associated mesh variables, false otherwise.
Parameters
_val
Definition at line 245 of file usermeshvo.cpp.
References _hasAssociatedMeshVariables.
Referenced by MeshDialog::createMeshVariables().
 {
     _hasAssociatedMeshVariables = _val;
 }
void UserMeshVO::setParentMenu (QString _menu)
Destructor.
Parameters
_menu
Definition at line 36 of file usermeshvo.cpp.
References _parentMenu.
Referenced by MeshDialog::createMeshVariables().
 {
     _parentMenu = _menu;
 }
void UserMeshVO::setUserName (QString _name)
set the user name
Parameters
_name
Definition at line 106 of file usermeshvo.cpp.
References _userName.
Referenced by MeshDialog::createMeshVariables().
 {
     _userName = _name;
 }
void UserMeshVO::updateBndValue (QString _boundName, QString _newVal)
Update the boundary value.
Parameters
_boundName
_newVal
Definition at line 137 of file usermeshvo.cpp.
References _boundaryAssociatedValues, and _boundaryNameList.
Referenced by addBoundary().
 {
     int _pos = _boundaryNameList.indexOf(_boundName);
     if ((_pos != -1) && (_pos < _boundaryAssociatedValues.size()))
         _boundaryAssociatedValues.replace(_pos, _newVal);
     else
     {
         for (int i = _boundaryAssociatedValues.size(); i <= _pos;i++)
         {
             _boundaryAssociatedValues.append("0");
         }
         _boundaryAssociatedValues.replace(_pos, _newVal);
     }
 }
Member Data Documentation
QStringList UserMeshVO::_associatedMeshVariables private
Definition at line 46 of file usermeshvo.h.
Referenced by getAssociatedMeshVariables(), and setAssociatedMeshVariables().
QStringList UserMeshVO::_boundaryAssociatedValues private
Definition at line 43 of file usermeshvo.h.
Referenced by addBoundary(), deleteBoundary(), getBoundaryAssociatedValues(), initializeBndAssociatedValuesToDefault(), resetValues(), setBoundaryAssociatedValues(), and updateBndValue().
QStringList UserMeshVO::_boundaryNameList private
Definition at line 42 of file usermeshvo.h.
Referenced by addBoundary(), containsBoundary(), deleteBoundary(), getBoundaryNameList(), resetValues(), setBoundaryNameList(), and updateBndValue().
QString UserMeshVO::_filename private
Definition at line 40 of file usermeshvo.h.
Referenced by getFilename(), setFilename(), and UserMeshVO().
bool UserMeshVO::_hasAssociatedMeshVariables private
Definition at line 47 of file usermeshvo.h.
Referenced by hasAssociatedMeshVariables(), setHasAssociatedMeshVariables(), and UserMeshVO().
QString UserMeshVO::_parentMenu private
Definition at line 44 of file usermeshvo.h.
Referenced by getParentMenu(), setParentMenu(), and UserMeshVO().
QString UserMeshVO::_userName private
Definition at line 41 of file usermeshvo.h.
Referenced by getUserName(), setUserName(), and UserMeshVO().
The documentation for this class was generated from the following files:
Data/Solver/usermeshvo.h
Data/Solver/usermeshvo.cpp