BBIPED Platform: ProjectSettingsDialog Class Reference
ProjectSettingsDialog Class Reference
#include <projectsettingsdialog.h>
Public Member Functions
ProjectSettingsDialog (QWidget *parent=0)
Constructor.
~ProjectSettingsDialog ()
Destructor.
MultizoneProjectData getMultizoneProjectData ()
Returns the multizone data.
ProjectData getProjectData ()
Returns the project data.
ProjectDetails getProjectDetailsData ()
Returns the project Details.
void setMultizoneProjectData (MultizoneProjectData _data)
Set the multizone project data and update the correspondent views.
void setProjectData (ProjectData _data)
Set the project data and update the correspondent views.
void setProjectDetailsData (ProjectDetails _prjDetails)
Store the project Details.
bool userAcceptChanges ()
Returns true if the user accept the changes.
Private Types
enum SettingsColumnsTypes
Private Slots
void on_associatedFileTable_cellClicked (int row, int column)
This action controls the actions when the user clicks in teh cell to remove a file (removing means remove both configuration file and mesh file)
void on_buttonBox_accepted ()
Action when the user accepts the changes.
void on_buttonBox_rejected ()
Action when the user rejects the changes.
Private Member Functions
void addRowToTable (int _idRow, int _idZone, QString _fileName)
void addValuesToTable (QStringList _list1, QStringList _list2)
This function add the values to the table.
void updateFileTableInSettingsView ()
This function updates the information in teh table.
void updateProjectData ()
This function updates the project data information according user changes.
void updateProjectDetailsInProjectDetailsTabView ()
Update the values of the project details in the tab view.
void updateProjectInformationInSettingsView ()
This fucntion updates the project information in the Dialog.
Private Attributes
MultizoneProjectData _multizoneData
ProjectData _projectData
ProjectDetails _projectDetailsData
QStringList _removedConfigFiles
QStringList _removedMeshFiles
bool _userAcceptChanges
Ui::ProjectSettingsDialog * ui
Detailed Description
Definition at line 14 of file projectsettingsdialog.h.
Member Enumeration Documentation
enum ProjectSettingsDialog::SettingsColumnsTypes private
Enumerator
SettingsColZoneNo
SettingsColFileType
SettingsColDelFile
Definition at line 41 of file projectsettingsdialog.h.
{
         SettingsColZoneNo = 0,
         SettingsColFileType = 1,
         SettingsColDelFile =2
     };
Constructor & Destructor Documentation
ProjectSettingsDialog::ProjectSettingsDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 34 of file projectsettingsdialog.cpp.
References _userAcceptChanges, and ui.
                                                             :
     QDialog(parent),
     ui(new Ui::ProjectSettingsDialog)
 {
     ui->setupUi(this);
     _userAcceptChanges = false;
 }
ProjectSettingsDialog::~ProjectSettingsDialog ()
Destructor.
Definition at line 46 of file projectsettingsdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void ProjectSettingsDialog::addRowToTable (int _idRow, int _idZone, QString _fileName) private
This function add the row to the table for hte correspondent file
Parameters
_idRow
_idZone
_fileName
Definition at line 176 of file projectsettingsdialog.cpp.
References QtableUtil::addIcon(), QtableUtil::addNonEditableText(), IconDelete, SettingsColDelFile, SettingsColFileType, SettingsColZoneNo, and ui.
Referenced by addValuesToTable().
 {
     QtableUtil _tableHelper;
     ui->associatedFileTable->insertRow(_idRow);
     ui->associatedFileTable->setItem(_idRow,SettingsColZoneNo,_tableHelper.addNonEditableText(QString::number(_idZone)) );
     ui->associatedFileTable->setItem(_idRow,SettingsColFileType,_tableHelper.addNonEditableText(_fileName) );
     // Only the configuration files have the possibility to be deleted
     // The mesh files must be deleted or changed in the normal Solver Menu
     if (_idRow%2 == 0)
         ui->associatedFileTable->setCellWidget(_idRow,SettingsColDelFile,_tableHelper.addIcon(IconDelete) );
     else
     {
         ui->associatedFileTable->item(_idRow-1,SettingsColZoneNo)->setTextAlignment(Qt::AlignCenter);
         ui->associatedFileTable->setSpan(_idRow-1,SettingsColDelFile,2,1);
         ui->associatedFileTable->setSpan(_idRow-1,SettingsColZoneNo,2,1);
     }
 }
void ProjectSettingsDialog::addValuesToTable (QStringList _list1, QStringList _list2) private
This function add the values to the table.
Parameters
_list1
_list2
Definition at line 116 of file projectsettingsdialog.cpp.
References addRowToTable().
Referenced by updateFileTableInSettingsView().
 {
     bool _isDifSize = false;
     int _listSize = _list1.size();
     // Check if the lists are not equal
     if ((_list1.size() != _list2.size()))
         _isDifSize = true;
     if ( (_isDifSize) && (_list1.size()>_list2.size()) )
       _listSize = _list2.size();
     for(int i= 0; i < _listSize; i++)
     {
         QString _configFileName = _list1.at(i);
         QString _meshFileName = _list2.at(i);
         int _cRow = i*2;
         addRowToTable(_cRow,_cRow/2, _configFileName);
         _cRow++;
         addRowToTable(_cRow,_cRow/2, _meshFileName);
     }
     // Completing the
     if (_isDifSize)
     {
         bool _addToConfig =false;
         bool _addToMesh = false;
         int _difSizeVal = 0;
         int _startPoint = _listSize;
         if (_list1.size() > _list2.size() )
         {
             _difSizeVal = _list1.size() - _list2.size();
             _addToConfig = true;
         }else
         {
             _difSizeVal = _list2.size() - _list1.size();
             _addToMesh = true;
         }
         for (int j = _startPoint; j < (_difSizeVal+_startPoint);j++)
         {
             QString _configFileName("Not Defined");
             if (_addToConfig)
                 _configFileName = _list1.at(j);
             QString _meshFileName("Not Defined");
             if (_addToMesh)
                 _meshFileName = _list2.at(j);
             int _cRow = j*2;
             addRowToTable(_cRow,_cRow/2, _configFileName);
             _cRow++;
             addRowToTable(_cRow,_cRow/2, _meshFileName);
         }
     }
 }
MultizoneProjectData ProjectSettingsDialog::getMultizoneProjectData ()
Returns the multizone data.
Returns
MultizoneProjectData
Definition at line 355 of file projectsettingsdialog.cpp.
References _multizoneData.
Referenced by EditHelper::launchSettingsDialog().
 {
     return _multizoneData;
 }
ProjectData ProjectSettingsDialog::getProjectData ()
Returns the project data.
Returns
ProjectData
Definition at line 333 of file projectsettingsdialog.cpp.
References _projectData.
Referenced by EditHelper::launchSettingsDialog().
 {
     return _projectData;
 }
ProjectDetails ProjectSettingsDialog::getProjectDetailsData ()
Returns the project Details.
Returns
ProjectDetails
Definition at line 386 of file projectsettingsdialog.cpp.
References _projectDetailsData.
Referenced by EditHelper::launchSettingsDialog().
 {
     return _projectDetailsData;
 }
void ProjectSettingsDialog::on_associatedFileTable_cellClicked (int row, int column) private slot
This action controls the actions when the user clicks in teh cell to remove a file (removing means remove both configuration file and mesh file)
Parameters
row
column
Definition at line 263 of file projectsettingsdialog.cpp.
References _removedConfigFiles, _removedMeshFiles, SettingsColDelFile, SettingsColFileType, ShowMessageHelper::showWarningMessage(), and ui.
 {
     if  (column == SettingsColDelFile)
     {
         ShowMessageHelper _msgHelper;
         bool _userWantsToDelete =_msgHelper.showWarningMessage("Remove Config & Associated Mesh File from Project","You are about to remove the link of the configuration file in this project and its corresponding mesh file. You will still keep them in the folder but not for the simulation. Are you sure?");
         if (_userWantsToDelete)
         {
             QString _configFile = ui->associatedFileTable->item(row,SettingsColFileType)->text();
             QString _meshFile =  ui->associatedFileTable->item(row+1,SettingsColFileType)->text();
             _removedConfigFiles.append(_configFile);
             _removedMeshFiles.append(_meshFile);
             ui->associatedFileTable->removeRow(row+1);
             ui->associatedFileTable->removeRow(row);
         }
     }
 }
void ProjectSettingsDialog::on_buttonBox_accepted () private slot
Action when the user accepts the changes.
Definition at line 289 of file projectsettingsdialog.cpp.
References _projectDetailsData, _removedConfigFiles, _removedMeshFiles, _userAcceptChanges, ProjectDetails::setAuthor(), ProjectDetails::setOtherDetails(), ProjectDetails::setProjectTile(), ProjectDetails::setStartingDate(), ui, and updateProjectData().
 {
      _userAcceptChanges = true;
      if( (!_removedConfigFiles.isEmpty()) && (!_removedMeshFiles.isEmpty()))
         updateProjectData();
      // Update the Project details
      _projectDetailsData.setProjectTile(ui->projectTitleLineEdit->text());
      _projectDetailsData.setAuthor(ui->authorLineEdit->text());
      _projectDetailsData.setStartingDate(ui->startingDateLineEdit->text());
      _projectDetailsData.setOtherDetails(ui->otherDetailsTexEdit->toPlainText());
      close();
 }
void ProjectSettingsDialog::on_buttonBox_rejected () private slot
Action when the user rejects the changes.
Definition at line 308 of file projectsettingsdialog.cpp.
References _userAcceptChanges.
 {
     _userAcceptChanges = false;
     close();
 }
void ProjectSettingsDialog::setMultizoneProjectData (MultizoneProjectData _data)
Set the multizone project data and update the correspondent views.
Parameters
_data
Definition at line 343 of file projectsettingsdialog.cpp.
References _multizoneData, updateFileTableInSettingsView(), and updateProjectInformationInSettingsView().
Referenced by EditHelper::launchSettingsDialog().
 {
     _multizoneData = _data;
     updateProjectInformationInSettingsView();
     updateFileTableInSettingsView();
 }
void ProjectSettingsDialog::setProjectData (ProjectData _data)
Set the project data and update the correspondent views.
Parameters
_data
Definition at line 321 of file projectsettingsdialog.cpp.
References _projectData, updateFileTableInSettingsView(), and updateProjectInformationInSettingsView().
Referenced by EditHelper::launchSettingsDialog().
 {
     _projectData = _data;
     updateProjectInformationInSettingsView();
     updateFileTableInSettingsView();
 }
void ProjectSettingsDialog::setProjectDetailsData (ProjectDetails _prjDetails)
Store the project Details.
Parameters
_prjDetails
Definition at line 374 of file projectsettingsdialog.cpp.
References _projectDetailsData, and updateProjectDetailsInProjectDetailsTabView().
Referenced by EditHelper::launchSettingsDialog().
 {
     _projectDetailsData = _prjDetails;
     updateProjectDetailsInProjectDetailsTabView();
 }
void ProjectSettingsDialog::updateFileTableInSettingsView () private
This function updates the information in teh table.
Definition at line 84 of file projectsettingsdialog.cpp.
References _multizoneData, _projectData, addValuesToTable(), MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), MultizoneProjectData::isEmpty(), ProjectData::isEmpty(), and ui.
Referenced by setMultizoneProjectData(), and setProjectData().
 {
     QStringList _listConfigFiles;
     QStringList _listMeshFiles;
     if (!_projectData.isEmpty())
     {
         QString _configFile = _projectData.getSolverDataInformation().getSolverConfigFilePath();
         QString _meshFile = _projectData.getSolverDataInformation().getSolverFilePath();
         _listConfigFiles.append(QFileInfo(_configFile).fileName());
         _listMeshFiles.append(QFileInfo(_meshFile).fileName());
     }else
     {
         if (!_multizoneData.isEmpty())
         {
             _listConfigFiles = _multizoneData.getListConfigFileNames();
             _listMeshFiles = _multizoneData.getListMeshFileNames();
         }
     }
     addValuesToTable(_listConfigFiles,_listMeshFiles);
     ui->associatedFileTable->resizeColumnsToContents();
 }
void ProjectSettingsDialog::updateProjectData () private
This function updates the project data information according user changes.
Definition at line 199 of file projectsettingsdialog.cpp.
References _multizoneData, _projectData, _removedConfigFiles, _removedMeshFiles, SolverVO::clear(), MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListConfigFiles(), MultizoneProjectData::getListMeshFileNames(), MultizoneProjectData::getListMeshFiles(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), MultizoneProjectData::isEmpty(), ProjectData::isEmpty(), MultizoneProjectData::setListConfigFiles(), MultizoneProjectData::setListMeshFiles(), ProjectData::setSolverDataInformation(), and StrEqual.
Referenced by on_buttonBox_accepted().
 {
     if (!_projectData.isEmpty())
     {
         SolverVO _solverData = _projectData.getSolverDataInformation();
         QString _configFileName = QFileInfo(_solverData.getSolverConfigFilePath()).fileName();
         QString _meshFileName = QFileInfo(_solverData.getSolverFilePath()).fileName();
         if ( (QString::compare(_configFileName,_removedConfigFiles.at(0)) == StrEqual)
             && (QString::compare(_meshFileName,_removedMeshFiles.at(0)) == StrEqual) )
             _solverData.clear();
         _projectData.setSolverDataInformation(_solverData);
     }else
     {
         if (!_multizoneData.isEmpty())
         {
             QStringList _configFileList = _multizoneData.getListConfigFiles();
             QStringList _configFileListNames = _multizoneData.getListConfigFileNames();
             QStringList _meshFileList = _multizoneData.getListMeshFiles();
             QStringList _meshFileListNames = _multizoneData.getListMeshFileNames();
             for (int i = 0; i <  _removedConfigFiles.size();i++)
             {
                 int _posToRemove = _configFileListNames.indexOf(_removedConfigFiles.at(i));
                 _configFileList.removeAt(_posToRemove);
                 _configFileListNames.removeAt(_posToRemove);
             }
             for (int i = 0; i <  _removedMeshFiles.size();i++)
             {
                 int _posToRemove = _meshFileListNames.indexOf(_removedMeshFiles.at(i));
                 _meshFileList.removeAt(_posToRemove);
                 _meshFileListNames.removeAt(_posToRemove);
             }
             _multizoneData.setListConfigFiles(_configFileList);
             _multizoneData.setListMeshFiles(_meshFileList);
         }
     }
 }
void ProjectSettingsDialog::updateProjectDetailsInProjectDetailsTabView () private
Update the values of the project details in the tab view.
Definition at line 246 of file projectsettingsdialog.cpp.
References _projectDetailsData, ProjectDetails::getAuthor(), ProjectDetails::getOtherDetails(), ProjectDetails::getProjectTile(), ProjectDetails::getStartingDate(), and ui.
Referenced by setProjectDetailsData().
 {
     ui->projectTitleLineEdit->setText(_projectDetailsData.getProjectTile());
     ui->authorLineEdit->setText(_projectDetailsData.getAuthor());
     ui->startingDateLineEdit->setText(_projectDetailsData.getStartingDate());
     ui->otherDetailsTexEdit->setPlainText(_projectDetailsData.getOtherDetails());
 }
void ProjectSettingsDialog::updateProjectInformationInSettingsView () private
This fucntion updates the project information in the Dialog.
Definition at line 57 of file projectsettingsdialog.cpp.
References _multizoneData, _projectData, ProjectData::getProjectFileName(), MultizoneProjectData::getProjectName(), MultizoneProjectData::isEmpty(), ProjectData::isEmpty(), PROJECT_TYPE_MULTIZONE, PROJECT_TYPE_NORMAL, and ui.
Referenced by setMultizoneProjectData(), and setProjectData().
 {
     QString _projectName;
     QString _projectFileType;
     if (!_projectData.isEmpty())
     {
         _projectName = _projectData.getProjectFileName();
         _projectFileType = PROJECT_TYPE_NORMAL;
     }else{
         if (!_multizoneData.isEmpty())
         {
             _projectName = _multizoneData.getProjectName();
             _projectFileType = PROJECT_TYPE_MULTIZONE;
         }
     }
     if ((!_projectName.isEmpty()) && (!_projectFileType.isEmpty()))
     {
         ui->projectNameLabel->setText(_projectName);
         ui->projectTypeLabel->setText(_projectFileType);
     }
 }
bool ProjectSettingsDialog::userAcceptChanges ()
Returns true if the user accept the changes.
Returns
bool
Definition at line 364 of file projectsettingsdialog.cpp.
References _userAcceptChanges.
Referenced by EditHelper::launchSettingsDialog().
 {
     return _userAcceptChanges;
 }
Member Data Documentation
MultizoneProjectData ProjectSettingsDialog::_multizoneData private
Definition at line 51 of file projectsettingsdialog.h.
Referenced by getMultizoneProjectData(), setMultizoneProjectData(), updateFileTableInSettingsView(), updateProjectData(), and updateProjectInformationInSettingsView().
ProjectData ProjectSettingsDialog::_projectData private
Definition at line 50 of file projectsettingsdialog.h.
Referenced by getProjectData(), setProjectData(), updateFileTableInSettingsView(), updateProjectData(), and updateProjectInformationInSettingsView().
ProjectDetails ProjectSettingsDialog::_projectDetailsData private
Definition at line 52 of file projectsettingsdialog.h.
Referenced by getProjectDetailsData(), on_buttonBox_accepted(), setProjectDetailsData(), and updateProjectDetailsInProjectDetailsTabView().
QStringList ProjectSettingsDialog::_removedConfigFiles private
Definition at line 54 of file projectsettingsdialog.h.
Referenced by on_associatedFileTable_cellClicked(), on_buttonBox_accepted(), and updateProjectData().
QStringList ProjectSettingsDialog::_removedMeshFiles private
Definition at line 55 of file projectsettingsdialog.h.
Referenced by on_associatedFileTable_cellClicked(), on_buttonBox_accepted(), and updateProjectData().
bool ProjectSettingsDialog::_userAcceptChanges private
Definition at line 56 of file projectsettingsdialog.h.
Referenced by on_buttonBox_accepted(), on_buttonBox_rejected(), ProjectSettingsDialog(), and userAcceptChanges().
Ui::ProjectSettingsDialog* ProjectSettingsDialog::ui private
Definition at line 49 of file projectsettingsdialog.h.
Referenced by addRowToTable(), on_associatedFileTable_cellClicked(), on_buttonBox_accepted(), ProjectSettingsDialog(), updateFileTableInSettingsView(), updateProjectDetailsInProjectDetailsTabView(), updateProjectInformationInSettingsView(), and ~ProjectSettingsDialog().
The documentation for this class was generated from the following files:
Forms/EditMenuDialog/projectsettingsdialog.h
Forms/EditMenuDialog/projectsettingsdialog.cpp