BBIPED Platform: ClipDomainDialog Class Reference
ClipDomainDialog Class Reference
#include <clipdomaindialog.h>
Public Member Functions
ClipDomainDialog (QWidget *parent=0)
~ClipDomainDialog ()
QString getValues ()
void initializeDialog ()
void setSolverVariable (SolverVariableVO _variable)
void setUserValues (QString _value)
Private Types
enum ColumnClipDialog
Private Slots
void on_doneButton_clicked ()
Private Member Functions
void fillTable ()
void loadTableHeader ()
Private Attributes
bool _loadingTable
SolverVariableVO _solverVO
QStringList _userValues
Ui::ClipDomainDialog * ui
Detailed Description
Definition at line 14 of file clipdomaindialog.h.
Member Enumeration Documentation
enum ClipDomainDialog::ColumnClipDialog private
Enumerator
ColumnVarName
ColumnValue
Definition at line 39 of file clipdomaindialog.h.
     {
         ColumnVarName = 0,
         ColumnValue = 1
     };
Constructor & Destructor Documentation
ClipDomainDialog::ClipDomainDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 26 of file clipdomaindialog.cpp.
References _loadingTable, and ui.
                                                   :
     QDialog(parent),
     ui(new Ui::ClipDomainDialog)
 {
     ui->setupUi(this);
     _loadingTable = false;
 }
ClipDomainDialog::~ClipDomainDialog ()
Definition at line 38 of file clipdomaindialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void ClipDomainDialog::fillTable () private
Definition at line 105 of file clipdomaindialog.cpp.
References _loadingTable, _solverVO, _userValues, QtableUtil::addEditText(), QtableUtil::addNonEditableText(), ColumnValue, ColumnVarName, SolverVariableVO::getSubVariableNames(), and ui.
Referenced by initializeDialog().
 {
     QtableUtil _tableHelper;
     _loadingTable = true;
     QStringList _listValueNames = _solverVO.getSubVariableNames();
     if (!_userValues.isEmpty())
         ui->domainTypeLineEdit->setText(_userValues.at(0));
     for (int i = 0; i < _listValueNames.size(); i++)
     {
         ui->variablesTable->insertRow(i);
         ui->variablesTable->setItem(i,ColumnVarName,_tableHelper.addNonEditableText(_listValueNames.at(i)));
         if ((!_userValues.isEmpty()) && (_listValueNames.size() ==(_userValues.size()-1)))
             ui->variablesTable->setCellWidget(i,ColumnValue,_tableHelper.addEditText(_userValues.at(i+1)));
         else
              ui->variablesTable->setCellWidget(i,ColumnValue,_tableHelper.addEditText(""));
     }
     _loadingTable = false;
 }
QString ClipDomainDialog::getValues ()
Returns
QString
Definition at line 60 of file clipdomaindialog.cpp.
References _userValues.
Referenced by SolverBasicDialog::launchSpecificWindow().
 {
     return (_userValues.join(","));
 }
void ClipDomainDialog::initializeDialog ()
Definition at line 81 of file clipdomaindialog.cpp.
References _loadingTable, fillTable(), and loadTableHeader().
Referenced by SolverBasicDialog::launchSpecificWindow().
 {
     loadTableHeader();
     fillTable();
     _loadingTable = false;
 }
void ClipDomainDialog::loadTableHeader () private
Definition at line 93 of file clipdomaindialog.cpp.
References ui.
Referenced by initializeDialog().
 {
     ui->variablesTable->setColumnCount(2);
     ui->variablesTable->setHorizontalHeaderLabels( QString("Variable;Value").split(";"));
     ui->variablesTable->horizontalHeader()->setVisible(true);
 }
void ClipDomainDialog::on_doneButton_clicked () private slot
Definition at line 133 of file clipdomaindialog.cpp.
References _userValues, ColumnValue, and ui.
 {
     // Store the results of the user
     _userValues.clear();
     _userValues.append(ui->domainTypeLineEdit->text());
     int _lastRow = ui->variablesTable->rowCount();
     for (int i = 0; i < _lastRow; i++)
     {
         QLineEdit * _item = qobject_cast<QLineEdit *> (ui->variablesTable->cellWidget(i,ColumnValue));
         if (_item)
             _userValues.append(_item->text());
     }
     close();
 }
void ClipDomainDialog::setSolverVariable (SolverVariableVO _variable)
Parameters
_variable
Definition at line 70 of file clipdomaindialog.cpp.
References _solverVO.
Referenced by SolverBasicDialog::launchSpecificWindow().
 {
     _solverVO = _variable;
 }
void ClipDomainDialog::setUserValues (QString _value)
Parameters
_value
Definition at line 50 of file clipdomaindialog.cpp.
References _userValues.
Referenced by SolverBasicDialog::launchSpecificWindow().
 {
     _userValues = _value.split(",");
 }
Member Data Documentation
bool ClipDomainDialog::_loadingTable private
Definition at line 37 of file clipdomaindialog.h.
Referenced by ClipDomainDialog(), fillTable(), and initializeDialog().
SolverVariableVO ClipDomainDialog::_solverVO private
Definition at line 36 of file clipdomaindialog.h.
Referenced by fillTable(), and setSolverVariable().
QStringList ClipDomainDialog::_userValues private
Definition at line 35 of file clipdomaindialog.h.
Referenced by fillTable(), getValues(), on_doneButton_clicked(), and setUserValues().
Ui::ClipDomainDialog* ClipDomainDialog::ui private
Definition at line 34 of file clipdomaindialog.h.
Referenced by ClipDomainDialog(), fillTable(), loadTableHeader(), on_doneButton_clicked(), and ~ClipDomainDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/clipdomaindialog.h
Forms/SolverMenuDialog/clipdomaindialog.cpp