BBIPED Platform: SolverConfigWriter Class Reference
SolverConfigWriter Class Reference
#include <solverconfigwriter.h>
Public Member Functions
SolverConfigWriter ()
Constructor.
void setOptionalVariableList (QStringList _list)
void setUserValues (QHash< QString, QString > _values)
Function that set up the user value map.
void setVirtualMRFUserValues (QList< VirtualMrfVO > _values)
void writeDOMTree (QDomDocument *_configTree, QTextStream *_fileOutput)
Function that writes the DOM tree within the textStream into the config file.
void writeHeaderFile (QTextStream *_fileOutput, ProjectDetails _projectDetails)
Function that writes the Header File of the Configuration File.
void writeSectionElement (QDomElement _sectionElement, QTextStream *_fileOutput)
Function that writes out a "section" tag element into the Qtextstream.
void writeSectionList (QDomElement _sectionList, QTextStream *_fileOutput)
Function that writes out a "section" list tag element into the Qtextstream.
void writeSubsectionElement (QDomElement _subSectionElement, QTextStream *_fileOutput)
Function that writes out a "subsection" tag element into the Qtextstream.
void writeSubsectionList (QDomElement _subSectionList, QTextStream *_fileOutput)
Function that writes out a "subsection" list tag element into the Qtextstream.
void writeToConfigurationFile (QString _filePath, QDomDocument *_configTree, ProjectDetails _projectDetails)
Function to write the values of the configuration values provided by the user in the correspondent configuration file.
void writeVariableElement (QDomElement _varElement, QTextStream *_fileOutput, bool _isVirtualMRF)
Function that writes out a "variable" tag element into the Qtextstream.
void writeVariableList (QDomElement _variableList, QTextStream *_fileOutput, bool _isVirtualMRF)
Function that writes out a "variable" list tag element into the Qtextstream.
void writeVariableValue (QDomElement _valueElement, QTextStream *_fileOutput, bool _isVirtualMRF)
Function that writes out a "value" tag element into the Qtextstream.
Private Member Functions
void printVirtualMRFValues (QDomElement _variableList, QTextStream *_fileOutput)
Private Attributes
QStringList _optionalVariables
QHash< QString, QString > _userValues
QList< VirtualMrfVO > _virtualMRFUserValues
Detailed Description
Definition at line 13 of file solverconfigwriter.h.
Constructor & Destructor Documentation
SolverConfigWriter::SolverConfigWriter ()
Constructor.
Definition at line 41 of file solverconfigwriter.cpp.
 {
 }
Member Function Documentation
void SolverConfigWriter::printVirtualMRFValues (QDomElement _variableList, QTextStream * _fileOutput) private
Definition at line 357 of file solverconfigwriter.cpp.
References COMMA_SEPARATOR, VirtualMrfVO::getAxisCenter(), VirtualMrfVO::getAxisNormal(), VirtualMrfVO::getInnerCurvePoints(), VirtualMrfVO::getOmega(), VirtualMrfVO::getOuterCurvePoints(), VirtualMrfVO::getZoneName(), StrEqual, VMRF_AXIS_KEYNAME, VMRF_GRID_MOVEMENT_KEYNAME, VMRF_GRID_MOVEMENT_KIND_KEYNAME, VMRF_INNER_CURVE_KEYNAME, VMRF_OUTER_CURVE_KEYNAME, and XML_VARIABLE_VALUE_NAME_ATT.
 {
     QString _value;
     bool _printValue=true;
     if (_virtualMRFUserValues.isEmpty())
         return;
     QString _keyValue = _valueElement.attribute(XML_VARIABLE_VALUE_NAME_ATT);
     _value=_keyValue+"=(";
     for (int i = 0; i < _virtualMRFUserValues.size();i++)
     {
         _value=_keyValue+"=(";
         _printValue=true;
         VirtualMrfVO _virtualMRF_obj = _virtualMRFUserValues.at(i);
         QString _name =_virtualMRF_obj.getZoneName();
         // Create VMRF_AXIS
         if (QString::compare(_keyValue,VMRF_AXIS_KEYNAME) == StrEqual)
             _value = _value + _name + COMMA_SEPARATOR + _virtualMRF_obj.getOmega() + COMMA_SEPARATOR +
                     _virtualMRF_obj.getAxisCenter().join(COMMA_SEPARATOR) + COMMA_SEPARATOR +
                     _virtualMRF_obj.getAxisNormal().join(COMMA_SEPARATOR) +")";
         // Create INNER CURVE
         if (QString::compare(_keyValue, VMRF_INNER_CURVE_KEYNAME) == StrEqual)
             if ( (!_virtualMRF_obj.getInnerCurvePoints().isEmpty()) && (_virtualMRF_obj.getInnerCurvePoints().count() >0))
             {
                 int _noPoints = 0;
               /*  if ( _virtualMRF_obj.isCoordinatesIn3D())
                     _noPoints = _virtualMRF_obj.getInnerCurvePoints().count()/3;
                 else */
                     _noPoints = _virtualMRF_obj.getInnerCurvePoints().count();
                 _value = _value + _name + COMMA_SEPARATOR + QString::number(_noPoints) + COMMA_SEPARATOR +
                         _virtualMRF_obj.getInnerCurvePoints().join(COMMA_SEPARATOR)+")";
             }
             else
                 _value=_value +"NONE)";
         // Create Outer Curve
         if (QString::compare(_keyValue,VMRF_OUTER_CURVE_KEYNAME) == StrEqual)
             if ( (!_virtualMRF_obj.getOuterCurvePoints().isEmpty()) && (_virtualMRF_obj.getOuterCurvePoints().count() >0))
             {
                 int _noPoints = 0;
                /* if ( _virtualMRF_obj.isCoordinatesIn3D())
                     _noPoints = _virtualMRF_obj.getOuterCurvePoints().count()/3;
                 else*/
                     _noPoints = _virtualMRF_obj.getOuterCurvePoints().count();
                 _value = _value + _name + COMMA_SEPARATOR + QString::number(_noPoints) + COMMA_SEPARATOR +
                         _virtualMRF_obj.getOuterCurvePoints().join(COMMA_SEPARATOR)+")";
             }
             else
                 _value=_value +"NONE)";
         if ((QString::compare(_keyValue,VMRF_GRID_MOVEMENT_KEYNAME) == StrEqual) || (QString::compare(_keyValue,VMRF_GRID_MOVEMENT_KIND_KEYNAME) == StrEqual))
             _printValue = false;
         if (_printValue)
         {
             _value.simplified();
             _value.replace(" ","");
             *_fileOutput << _value  << endl;
         }
     }
 }
void SolverConfigWriter::setOptionalVariableList (QStringList _list)
Definition at line 442 of file solverconfigwriter.cpp.
Referenced by SolverConfigManager::saveConfigFile().
 {
     _optionalVariables = _list;
 }
void SolverConfigWriter::setUserValues (QHash< QString, QString > _values)
Function that set up the user value map.
Parameters
QHash<QString
_values
Definition at line 433 of file solverconfigwriter.cpp.
Referenced by SolverConfigManager::saveConfigFile().
 {
     _userValues = _values;
 }
void SolverConfigWriter::setVirtualMRFUserValues (QList< VirtualMrfVO > _values)
Definition at line 438 of file solverconfigwriter.cpp.
Referenced by SolverConfigManager::saveConfigFile().
 {
     _virtualMRFUserValues = _values;
 }
void SolverConfigWriter::writeDOMTree (QDomDocument * _configTree, QTextStream * _fileOutput)
Function that writes the DOM tree within the textStream into the config file.
Parameters
_configTree
_fileOutput
Definition at line 103 of file solverconfigwriter.cpp.
References StrEqual, and XML_ROOT_NODE_NAME.
 {
     // Get the root element
     QDomElement _rootElement = _configTree->documentElement();
     if (QString::compare(_rootElement.tagName(),XML_ROOT_NODE_NAME) == StrEqual)
         writeSectionList(_rootElement,_fileOutput);
 }
void SolverConfigWriter::writeHeaderFile (QTextStream * _fileOutput, ProjectDetails _projectDetails)
Function that writes the Header File of the Configuration File.
Parameters
_fileOutput
Definition at line 82 of file solverconfigwriter.cpp.
References ProjectDetails::getAuthor(), ProjectDetails::getOtherDetails(), ProjectDetails::getProjectTile(), and ProjectDetails::getStartingDate().
 {
     QDate date = QDate::currentDate();
     QString dateString = date.toString();
     *_fileOutput << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" << endl;
     *_fileOutput << "% CONFIGURATION FILE                                                                %" << endl;
     *_fileOutput << "% Project Title:   "<< _projectDetails.getProjectTile()  <<"     %" << endl;
     *_fileOutput << "% Author:      " << _projectDetails.getAuthor() <<"     %" << endl;
     *_fileOutput << "% Date of the project:" << _projectDetails.getStartingDate() << "     %" << endl;
     *_fileOutput << "% Date of the file:" << dateString << "     %" << endl;
     *_fileOutput << "% Other Details:         %" << _projectDetails.getOtherDetails() << "     %" << endl;
     *_fileOutput << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" << endl;
 }
void SolverConfigWriter::writeSectionElement (QDomElement _sectionElement, QTextStream * _fileOutput)
Function that writes out a "section" tag element into the Qtextstream.
Parameters
_sectionElement
_fileOutput
Definition at line 143 of file solverconfigwriter.cpp.
References StrEqual, XML_SUBSECTION_LIST_NAME, and XML_TITLE_SECTION_NAME.
 {
    *_fileOutput << "%**********************************************************************%%" << endl;
     QDomNode _childNode = _sectionElement.firstChild();
     while (!_childNode.isNull())
     {
         QDomElement _nodeElement = _childNode.toElement();
         if (!_nodeElement.isNull())
         {
             if (QString::compare(_nodeElement.tagName(),XML_TITLE_SECTION_NAME) == StrEqual)
             {
                 *_fileOutput << "%%####################################################################################" << endl;
                 *_fileOutput << "%%                    " <<  _nodeElement.text() << endl;
                 *_fileOutput << "%%####################################################################################" << endl;
             }
             if (QString::compare(_nodeElement.tagName(),XML_SUBSECTION_LIST_NAME) == StrEqual)
                 writeSubsectionList(_nodeElement,_fileOutput);
         }
         _childNode = _childNode.nextSibling();
     }
 }
void SolverConfigWriter::writeSectionList (QDomElement _sectionList, QTextStream * _fileOutput)
Function that writes out a "section" list tag element into the Qtextstream.
Parameters
_sectionList
_fileOutput
Definition at line 119 of file solverconfigwriter.cpp.
References StrEqual, XML_SECTION_LIST_NAME, and XML_SECTION_NODE_NAME.
 {
     QDomElement _sectionListElement = _sectionList.firstChild().toElement();
     if (!_sectionListElement.isNull())
         if (QString::compare(_sectionListElement.tagName(),XML_SECTION_LIST_NAME) == StrEqual)
         {
             QDomNodeList _childList = _sectionListElement.childNodes();
             if (!_childList.isEmpty())
                 for (int i = 0; i < _childList.count();i++)
                 {
                     QDomElement _sectionEl = _childList.at(i).toElement();
                     if ( (!_sectionEl.isNull()) && (QString::compare(_sectionEl.tagName(),XML_SECTION_NODE_NAME)== StrEqual))
                         writeSectionElement(_sectionEl,_fileOutput);
                 }
         }
 }
void SolverConfigWriter::writeSubsectionElement (QDomElement _subSectionElement, QTextStream * _fileOutput)
Function that writes out a "subsection" tag element into the Qtextstream.
Parameters
_subSectionElement
_fileOutput
Definition at line 197 of file solverconfigwriter.cpp.
References StrEqual, VIRTUAL_SUBSECTION_NAME, VMRF_GRID_MOVEMENT_KEYNAME, VMRF_GRID_MOVEMENT_KIND_KEYNAME, XML_SUBSECTION_TITLE_NAME, and XML_VARIABLE_LIST_NAME.
 {
     if (!_subSectionElement.isNull())
     {
         QDomNodeList _childList = _subSectionElement.childNodes();
         bool _isVirtualMRF = false;
         if (!_childList.isEmpty())
             for (int i = 0;i < _childList.count();i++)
             {
                 QDomElement _subsectionEl = _childList.at(i).toElement();
                 if (!_subsectionEl.isNull())
                 {
                     if (QString::compare(_subsectionEl.tagName(),XML_SUBSECTION_TITLE_NAME) == StrEqual)
                     {
                         *_fileOutput << "%%--------------------------------------------------------------------------------------" << endl;
                         *_fileOutput << "%%                    " << _subsectionEl.text() << endl;
                         *_fileOutput << "%%--------------------------------------------------------------------------------------" << endl;
                         // If is Virtual MRF section a customized output must be done
                         if (QString::compare(_subsectionEl.text(),VIRTUAL_SUBSECTION_NAME) == StrEqual)
                             _isVirtualMRF = true;
                     }
                     if (QString::compare(_subsectionEl.tagName(),XML_VARIABLE_LIST_NAME) == StrEqual)
                         writeVariableList(_subsectionEl,_fileOutput,_isVirtualMRF);
                 }
             }
         // In the case ov Virtual MRF -- Add hidden Variables
             if ((_isVirtualMRF) && (!_virtualMRFUserValues.isEmpty()))
             {
                 // Write the hidden Variables
                  QString _value;
                 _value=VMRF_GRID_MOVEMENT_KEYNAME+"=(YES)";
                 _value.simplified();
                 _value.replace(" ","");
                 *_fileOutput << _value  << endl;
                 _value=VMRF_GRID_MOVEMENT_KIND_KEYNAME+"=(ROTATING_FRAME)";
                 _value.simplified();
                 _value.replace(" ","");
                 *_fileOutput << _value  << endl;
             }
     }
 }
void SolverConfigWriter::writeSubsectionList (QDomElement _subSectionList, QTextStream * _fileOutput)
Function that writes out a "subsection" list tag element into the Qtextstream.
Parameters
_subSectionList
_fileOutput
Definition at line 173 of file solverconfigwriter.cpp.
References StrEqual, and XML_SUBSECTION_NAME.
 {
     if (!_subSectionList.isNull())
     {
         QDomNodeList _childList = _subSectionList.childNodes();
         if (!_childList.isEmpty())
         {
             for (int i = 0; i < _childList.count();i++)
             {
                 QDomElement _subsectionEl = _childList.at(i).toElement();
                 if ((!_subsectionEl.isNull()) && (QString::compare(_subsectionEl.tagName(),XML_SUBSECTION_NAME) == StrEqual) )
                     writeSubsectionElement(_subsectionEl,_fileOutput);
             }
         }
     }
 }
void SolverConfigWriter::writeToConfigurationFile (QString _filePath, QDomDocument * _configTree, ProjectDetails _projectDetails)
Function to write the values of the configuration values provided by the user in the correspondent configuration file.
Parameters
_filePath
_configTree
Definition at line 56 of file solverconfigwriter.cpp.
Referenced by MainWindow::on_newActionButton_clicked(), SolverConfigManager::saveConfigFile(), and MainWindow::updateMultizoneUserData().
 {
     QFile _file(_filePath);
     if (_file.exists())
         _file.remove();
     bool _fileCreated = _file.open(QIODevice::ReadWrite | QIODevice::Text);
     if (_fileCreated)
     {
        QTextStream * _fileWrite = new QTextStream(&_file);
        writeHeaderFile(_fileWrite, _projectDetails);
        writeDOMTree(_configTree,_fileWrite);
        delete _fileWrite;
     }
     _file.close();
 }
void SolverConfigWriter::writeVariableElement (QDomElement _varElement, QTextStream * _fileOutput, bool _isVirtualMRF)
Function that writes out a "variable" tag element into the Qtextstream.
Parameters
_varElement
_fileOutput
Definition at line 276 of file solverconfigwriter.cpp.
References StrEqual, XML_VARIABLE_NAME_NAME, and XML_VARIABLE_VALUE_NAME.
 {
     QDomNode _childNode = _varElement.firstChild();
     while (!_childNode.isNull())
     {
         QDomElement _nodeElement = _childNode.toElement();
         if (!_nodeElement.isNull())
         {
             if (QString::compare(_nodeElement.tagName(),XML_VARIABLE_NAME_NAME) == StrEqual)
                 *_fileOutput << "%%---**" << _nodeElement.text() << endl;
             if (QString::compare(_nodeElement.tagName(),XML_VARIABLE_VALUE_NAME) == StrEqual)
                 writeVariableValue(_nodeElement,_fileOutput,_isVirtualMRF);
         }
         _childNode = _childNode.nextSibling();
     }
 }
void SolverConfigWriter::writeVariableList (QDomElement _variableList, QTextStream * _fileOutput, bool _isVirtualMRF)
Function that writes out a "variable" list tag element into the Qtextstream.
Parameters
_variableList
_fileOutput
Definition at line 249 of file solverconfigwriter.cpp.
References StrEqual, and XML_VARIABLE_NAME.
 {
     if (!_variableList.isNull())
     {
         QDomNodeList _childList = _variableList.childNodes();
         if (!_childList.isEmpty())
         {
             for (int i = 0; i < _childList.count();i++)
             {
                 QDomElement _variableEl = _childList.at(i).toElement();
                 if (!_variableEl.isNull())
                     if (QString::compare(_variableEl.tagName(),XML_VARIABLE_NAME) == StrEqual)
                         writeVariableElement(_variableEl,_fileOutput,_isVirtualMRF);
             }
         }
     }
 }
void SolverConfigWriter::writeVariableValue (QDomElement _valueElement, QTextStream * _fileOutput, bool _isVirtualMRF)
Function that writes out a "value" tag element into the Qtextstream.
Parameters
_valueElement
_fileOutput
Definition at line 300 of file solverconfigwriter.cpp.
References BC_PREFIX, DOMAIN_CLIPPING_VARIABLE_FILENAME, MARKER_PREFIX, StrEqual, and XML_VARIABLE_VALUE_NAME_ATT.
 {
     QString _value;
     if (_valueElement.hasAttribute(XML_VARIABLE_VALUE_NAME_ATT))    {
         if (!_isVirtualMRF)
         {
             QString _keyValue = _valueElement.attribute(XML_VARIABLE_VALUE_NAME_ATT);
             bool _saveValue = true;
             if ((!_optionalVariables.isEmpty()) && (_optionalVariables.contains(_keyValue)))
                 _saveValue = false;
             if ((!_userValues.isEmpty()) &&  (_userValues.contains(_keyValue)))
             {
                 _value = _valueElement.attribute(XML_VARIABLE_VALUE_NAME_ATT);
                 QString _cValue = _userValues.value(_keyValue);
                 if (QString::compare(_keyValue,DOMAIN_CLIPPING_VARIABLE_FILENAME) == StrEqual)
                 {
                     if (_cValue.isEmpty())
                         _value ="";
                     else
                     {
                         // Print each value in several Domain clip variables in the file
                         QStringList _valueList = _cValue.split(";");
                         for (int i =0; i < _valueList.size();i++)
{
                             _value = DOMAIN_CLIPPING_VARIABLE_FILENAME+ "=("+_valueList.at(i)+")";
                             _value.simplified();
                             _value.replace(" ","");
                             *_fileOutput << _value  << endl;
                             _value="";
                         }
                     }
                 }else
                 {
                     if ( ((_value.contains(MARKER_PREFIX)) || (_value.contains(BC_PREFIX)))
                          && (!_cValue.contains("(")) && (!_cValue.contains(")")))
                         _value = _value  +"= ("+  _cValue+ ")";
                     else
                         _value = _value +"="+ _cValue;
                 }
             }else
                 if (_saveValue)
                     _value =  _valueElement.attribute(XML_VARIABLE_VALUE_NAME_ATT) +"="+_valueElement.text();
             _value.simplified();
             _value.replace(" ","");
             *_fileOutput << _value  << endl;
         }else
             printVirtualMRFValues(_valueElement,_fileOutput);
     }
 }
Member Data Documentation
QStringList SolverConfigWriter::_optionalVariables private
Definition at line 42 of file solverconfigwriter.h.
QHash<QString,QString> SolverConfigWriter::_userValues private
Definition at line 40 of file solverconfigwriter.h.
QList<VirtualMrfVO> SolverConfigWriter::_virtualMRFUserValues private
Definition at line 41 of file solverconfigwriter.h.
The documentation for this class was generated from the following files:
Solver/solverconfigwriter.h
Solver/solverconfigwriter.cpp