BBIPED Platform: ParserFiles Class Reference
ParserFiles Class Reference abstract
#include <parserfiles.h>
Public Member Functions
ParserFiles ()
Constructor.
QString getFilePath ()
Returns the path of the file.
QHash< QString, QString > getParsedValues ()
Returns the map of the parsed values.
virtual void parseFileProcess ()=0
QString removeSpaces (QString _value)
Function to remove spaces in the values.
void setFilePath (QString _newPath)
Establish the file path.
void setParsedValues (QHash< QString, QString > _newValues)
Sets the parsed values.
Private Attributes
QString _filePath
QHash< QString, QString > _parsedValues
Detailed Description
Definition at line 8 of file parserfiles.h.
Constructor & Destructor Documentation
ParserFiles::ParserFiles ()
Constructor.
Definition at line 23 of file parserfiles.cpp.
References _filePath, and _parsedValues.
 {
     _filePath = "";
     _parsedValues.empty();
 }
Member Function Documentation
QString ParserFiles::getFilePath ()
Returns the path of the file.
Returns
QString
Definition at line 34 of file parserfiles.cpp.
References _filePath.
Referenced by MeshFileParser::parseFileProcess(), and ConfigurationFileParser::parseFileProcess().
 {
     return _filePath;
 }
QHash< QString, QString > ParserFiles::getParsedValues ()
Returns the map of the parsed values.
Returns
QHash<QString, QString>
Definition at line 54 of file parserfiles.cpp.
References _parsedValues.
Referenced by MultizoneProjectDialog::checkConsistency(), FileComparisonDialog::loadFileValues(), and InputDataTabHelper::parseFile().
 {
     return _parsedValues;
 }
virtual void ParserFiles::parseFileProcess () pure virtual
Implemented in ConfigurationFileParser, and MeshFileParser.
QString ParserFiles::removeSpaces (QString _value)
Function to remove spaces in the values.
Parameters
_value
Returns
QString
Definition at line 76 of file parserfiles.cpp.
Referenced by MeshFileParser::saveTokenElements(), and ConfigurationFileParser::saveTokenElements().
 {
     _value = _value.simplified();
     _value.replace(" ","");
     return _value;
 }
void ParserFiles::setFilePath (QString _newPath)
Establish the file path.
Parameters
_newPath
Definition at line 44 of file parserfiles.cpp.
References _filePath.
Referenced by MultizoneProjectDialog::checkConsistency(), FileComparisonDialog::loadFileValues(), and InputDataTabHelper::parseFile().
 {
     _filePath = _newPath;
 }
void ParserFiles::setParsedValues (QHash< QString, QString > _newValues)
Sets the parsed values.
Parameters
QHash<QString
_newValues
Definition at line 65 of file parserfiles.cpp.
References _parsedValues.
Referenced by MeshFileParser::parseFileProcess(), and ConfigurationFileParser::parseFileProcess().
 {
     _parsedValues = _newValues;
 }
Member Data Documentation
QString ParserFiles::_filePath private
Definition at line 25 of file parserfiles.h.
Referenced by getFilePath(), ParserFiles(), and setFilePath().
QHash<QString,QString> ParserFiles::_parsedValues private
Definition at line 26 of file parserfiles.h.
Referenced by getParsedValues(), ParserFiles(), and setParsedValues().
The documentation for this class was generated from the following files:
Parser/parserfiles.h
Parser/parserfiles.cpp