BBIPED Platform: ShowMessageHelper Class Reference
ShowMessageHelper Class Reference
#include <showmessagehelper.h>
Public Member Functions
ShowMessageHelper ()
void showMessage (QString msg, QStatusBar *_statusBar)
Show custom message in status bar.
bool showMessageForSaving ()
Show comboBox for Saving results.
bool showMessageReset ()
Show message window to reset the boundary values to the new ones.
void showMessageWindow (QString _title, QString _message, QWidget *_window)
Show About Message window.
bool showWarningMessage (QString _title, QString _message)
Default WARNING Message.
Detailed Description
Definition at line 9 of file showmessagehelper.h.
Constructor & Destructor Documentation
ShowMessageHelper::ShowMessageHelper ()
Definition at line 24 of file showmessagehelper.cpp.
 {
 }
Member Function Documentation
void ShowMessageHelper::showMessage (QString msg, QStatusBar * _statusBar)
Show custom message in status bar.
Parameters
msg
Definition at line 34 of file showmessagehelper.cpp.
Referenced by MainWindow::enableMultizoneElements(), MainWindow::on_actionNew_Project_triggered(), MainWindow::on_actionSave_As_triggered(), and MainWindow::openProject().
 {
   // display message on main window status bar
   _statusBar->showMessage( msg );
 }
bool ShowMessageHelper::showMessageForSaving ()
Show comboBox for Saving results.
Returns
bool
Definition at line 45 of file showmessagehelper.cpp.
Referenced by MainWindow::closeProject(), and MainWindow::runSimulation().
 {
     QMessageBox msgbox;
     msgbox.setIcon(QMessageBox::Question);
     msgbox.setWindowTitle("YOUR PROJECT NEED TO BE SAVED"); //this is ignore on mac
     msgbox.setText("Your project has changes that have not been saved yet. Do you want to save them, before Closing?"); //set message box text
     msgbox.addButton(QMessageBox::Yes); //add ok button
     msgbox.addButton(QMessageBox::No); //add cancel button
     int status = msgbox.exec(); //display message box
     /* display which option was choosen */
     switch (status) {
         case QMessageBox::Yes:
             return true;
             break;
         case QMessageBox::No:
             return false;
             break;
      }
     return false;
 }
bool ShowMessageHelper::showMessageReset ()
Show message window to reset the boundary values to the new ones.
Returns
bool
Definition at line 92 of file showmessagehelper.cpp.
Referenced by SolverBasicDialog::on_resetDefaultButton_clicked().
 {
     QMessageBox msgbox;
     msgbox.setIcon(QMessageBox::Question);
     msgbox.setWindowTitle("Reset Configuration File Values"); //this is ignored on mac
     msgbox.setText("You are going to reset all the values to their default ones. Do you wan to continue?"); //set message box text
     msgbox.addButton(QMessageBox::Ok); //add ok button
     msgbox.addButton(QMessageBox::Cancel); //add cancel button
     int status = msgbox.exec(); //display message box
     /* display which option was choosen */
     switch (status) {
         case QMessageBox::Ok:
             return true;
             break;
         case QMessageBox::Cancel:
             return false;
             break;
      }
     return false;
 }
void ShowMessageHelper::showMessageWindow (QString _title, QString _message, QWidget * _window)
Show About Message window.
Parameters
_title
_message
Returns
bool
Definition at line 73 of file showmessagehelper.cpp.
Referenced by MainWindow::on_actionNew_Project_triggered(), MainWindow::on_actionSave_Temporal_triggered(), MultizoneProjectDialog::on_projectSelectionToolButton_clicked(), and MainWindow::on_solverTabwidget_tabCloseRequested().
 {
     QMessageBox _msgBox;
     _msgBox.setTextFormat(Qt::RichText);
     QPixmap projectLogo(":/logo/images/icon_31x64.png");
     _msgBox.setIconPixmap(projectLogo);
     _msgBox.setWindowTitle(_title);
     _msgBox.setText(_message);
     _msgBox.exec();
 }
bool ShowMessageHelper::showWarningMessage (QString _title, QString _message)
Default WARNING Message.
Parameters
_title
_message
Returns
bool
Definition at line 120 of file showmessagehelper.cpp.
Referenced by MultizoneProjectDialog::buildFilesInProject(), ToolsHelper::launchSalomeWarning(), MainWindow::multizoneSaveAll(), ProjectSettingsDialog::on_associatedFileTable_cellClicked(), MultizoneIndividualTabForm::on_cancelButton_clicked(), MultizoneIndividualTabForm::on_closeButton_clicked(), MultizoneSelectFilesDialog::on_importedConfigNameToolButton_clicked(), MultizoneIndividualTabForm::on_importMeshFileButton_clicked(), and MainWindow::on_newActionButton_clicked().
 {
     QMessageBox msgbox;
     msgbox.setWindowTitle(_title); //this is ignore on mac
     msgbox.setIcon(QMessageBox::Warning);
     msgbox.setText(_message); //set message box text
     msgbox.addButton(QMessageBox::Ok); //add ok button
     msgbox.addButton(QMessageBox::Cancel); //add cancel button
     int status = msgbox.exec(); //display message box
     /* display which option was choosen */
     switch (status) {
         case QMessageBox::Ok:
            return true;
            break;
         case QMessageBox::Cancel:
             return false;
             break;
      }
     return false;
 }
The documentation for this class was generated from the following files:
Utility/showmessagehelper.h
Utility/showmessagehelper.cpp