BBIPED Platform: MultizoneSummaryDialog Class Reference
MultizoneSummaryDialog Class Reference
#include <multizonesummarydialog.h>
Public Member Functions
MultizoneSummaryDialog (QWidget *parent=0)
~MultizoneSummaryDialog ()
void setConfigFileList (QStringList _list)
void setProjectPath (QString _path)
void setSolverManager (SolverConfigManager *_manager)
Private Types
enum configTableColumns
enum variablesTableColumsn
Private Slots
void on_okButton_clicked ()
void on_selectConfigFilesTable_cellClicked (int row, int column)
Private Member Functions
void addConfigData (QString _file)
void fillConfigTable ()
void fillDataTable (QHash< QString, QString > *_mapValues, QList< VirtualMrfVO > *_virtualList)
void insertRow (int _pos, QString _key, QString _value, QString _unit)
void removeDefaultValues (QHash< QString, QString > *_configVal)
void resetTable ()
Private Attributes
QStringList _configFileList
QString _projectPath
int _selectedRow
SolverConfigManager * _solverManager
Ui::MultizoneSummaryDialog * ui
Detailed Description
Definition at line 16 of file multizonesummarydialog.h.
Member Enumeration Documentation
enum MultizoneSummaryDialog::configTableColumns private
Enumerator
checkBoxColumn
configFileNameCol
Definition at line 39 of file multizonesummarydialog.h.
{
         checkBoxColumn = 0,
         configFileNameCol =1
     };
enum MultizoneSummaryDialog::variablesTableColumsn private
Enumerator
variableNameCol
variableValueCol
variableUnitCol
Definition at line 43 of file multizonesummarydialog.h.
{
         variableNameCol = 0,
         variableValueCol =1,
         variableUnitCol = 2
     };
Constructor & Destructor Documentation
MultizoneSummaryDialog::MultizoneSummaryDialog (QWidget * parent = 0) explicit
Definition at line 30 of file multizonesummarydialog.cpp.
References _selectedRow, and ui.
                                                               :
     QDialog(parent),
     ui(new Ui::MultizoneSummaryDialog)
 {
     ui->setupUi(this);
     _selectedRow = -1;
 }
MultizoneSummaryDialog::~MultizoneSummaryDialog ()
Definition at line 38 of file multizonesummarydialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void MultizoneSummaryDialog::addConfigData (QString _file) private
Definition at line 71 of file multizonesummarydialog.cpp.
References fillDataTable(), InputDataTabHelper::parseFile(), ParserSolverConfigFile, and removeDefaultValues().
Referenced by on_selectConfigFilesTable_cellClicked().
 {
     InputDataTabHelper _helper;
     QHash<QString,QString> * _configVal = new QHash<QString,QString>();
     QHash<QString,QString> * _bndMeshVal = new QHash<QString,QString>();
     QList<VirtualMrfVO> * _virtualMRFList = new  QList<VirtualMrfVO>();
     _helper.parseFile(ParserSolverConfigFile,_file,_configVal,_bndMeshVal,_virtualMRFList);
     removeDefaultValues(_configVal);
     fillDataTable(_configVal,_virtualMRFList);
 }
void MultizoneSummaryDialog::fillConfigTable () private
Definition at line 145 of file multizonesummarydialog.cpp.
References _configFileList, QtableUtil::addNonEditableText(), QtableUtil::addSelectableCheckColumn(), checkBoxColumn, configFileNameCol, and ui.
Referenced by setConfigFileList().
 {
     int _noFiles = _configFileList.size();
     QtableUtil _tableUtil;
     for (int i=0; i<_noFiles;i++)
     {
         ui->selectConfigFilesTable->insertRow(i);
         ui->selectConfigFilesTable->setItem(i,checkBoxColumn,_tableUtil.addSelectableCheckColumn());
         ui->selectConfigFilesTable->setItem(i,configFileNameCol,_tableUtil.addNonEditableText(QFileInfo(_configFileList.at(i)).fileName()));
     }
     ui->selectConfigFilesTable->resizeColumnsToContents();
     ui->selectConfigFilesTable->resizeRowsToContents();
 }
void MultizoneSummaryDialog::fillDataTable (QHash< QString, QString > * _mapValues, QList< VirtualMrfVO > * _virtualList) private
Definition at line 103 of file multizonesummarydialog.cpp.
References COMMA_SEPARATOR, VirtualMrfVO::getAxisCenter(), VirtualMrfVO::getAxisNormal(), VirtualMrfVO::getOmega(), VirtualMrfVO::getZoneName(), insertRow(), and ui.
Referenced by addConfigData().
 {
     int _indxRow = ui->summaryFile1QTable->rowCount();
     if (!_mapValues->isEmpty())
     {
         QHashIterator<QString,QString> _iter (*_mapValues);
         while(_iter.hasNext())
         {
             _iter.next();
             QString _keyName =_iter.key();
             QString _value = _iter.value();
             insertRow(_indxRow,_keyName, _value, "");
             _indxRow++;
         }
     }
     if (!_virtualList->isEmpty())
     {
         for (int i = 0; i < _virtualList->size();i++)
         {
             VirtualMrfVO _virtualData = _virtualList->at(i);
             QString _keyName =_virtualData.getZoneName();
             QString _value = "Omega ="+_virtualData.getOmega() + ";Axis center ="+_virtualData.getAxisCenter().join(COMMA_SEPARATOR)
                     +";Axis normal =" +_virtualData.getAxisNormal().join(COMMA_SEPARATOR);
             insertRow(_indxRow,_keyName, _value, "");
             _indxRow++;
         }
     }
     ui->summaryFile1QTable->resizeColumnsToContents();
     ui->summaryFile1QTable->resizeRowsToContents();
 }
void MultizoneSummaryDialog::insertRow (int _pos, QString _key, QString _value, QString _unit) private
Definition at line 136 of file multizonesummarydialog.cpp.
References QtableUtil::addNonEditableText(), ui, variableNameCol, variableUnitCol, and variableValueCol.
Referenced by fillDataTable().
 {
     QtableUtil _tableHelper;
     ui->summaryFile1QTable->insertRow(_pos);
     ui->summaryFile1QTable->setItem(_pos,variableNameCol,_tableHelper.addNonEditableText(_key));
     ui->summaryFile1QTable->setItem(_pos,variableValueCol,_tableHelper.addNonEditableText(_value));
     ui->summaryFile1QTable->setItem(_pos,variableUnitCol,_tableHelper.addNonEditableText(_unit));
 }
void MultizoneSummaryDialog::on_okButton_clicked () private slot
Definition at line 44 of file multizonesummarydialog.cpp.
 {
     close();
 }
void MultizoneSummaryDialog::on_selectConfigFilesTable_cellClicked (int row, int column) private slot
Definition at line 49 of file multizonesummarydialog.cpp.
References _projectPath, _selectedRow, addConfigData(), checkBoxColumn, configFileNameCol, resetTable(), TOOL4, and ui.
 {
     if (column == checkBoxColumn)
     {
         if (_selectedRow != -1)
             ui->selectConfigFilesTable->item(_selectedRow,checkBoxColumn)->setCheckState(Qt::Unchecked);
         QString _configFile = ui->selectConfigFilesTable->item(row,configFileNameCol)->text();
         resetTable();
         addConfigData(QDir(QDir(_projectPath).filePath(TOOL4)).filePath(_configFile));
         ui->fileName1Label->setText(_configFile);
         _selectedRow = row;
     }
 }
void MultizoneSummaryDialog::removeDefaultValues (QHash< QString, QString > * _configVal) private
Definition at line 84 of file multizonesummarydialog.cpp.
References _solverManager, SolverConfigManager::getAllSectionMenuList(), SolverSectionDAO::isDefaultValueByFileName(), and SolverConfigManager::isInitialized().
Referenced by addConfigData().
 {
     QHash<QString,QString> _cleanedConfigValues;
     QHashIterator<QString,QString> iter(* _configVal);
     SolverSectionDAO _dao;
     if (!_solverManager->isInitialized())
         _solverManager->isInitialized();
     QList<SolverSectionVO> _menuList = _solverManager->getAllSectionMenuList();
     while(iter.hasNext())
     {
         iter.next();
         if (!iter.value().contains("NONE"))
             if ( (!_dao.isDefaultValueByFileName(_menuList, iter.key(), iter.value()))
                 || (iter.key().contains("BC_")) || (iter.key().contains("MARKER")) )
                 _cleanedConfigValues.insert(iter.key(),iter.value());
     }
     (* _configVal) = _cleanedConfigValues;
 }
void MultizoneSummaryDialog::resetTable () private
Definition at line 63 of file multizonesummarydialog.cpp.
References ui.
Referenced by on_selectConfigFilesTable_cellClicked().
 {
     int _lastRow = ui->summaryFile1QTable->rowCount();
     for (int i = _lastRow-1; i >= 0; i--)
         ui->summaryFile1QTable->removeRow(i);
 }
void MultizoneSummaryDialog::setConfigFileList (QStringList _list)
Definition at line 160 of file multizonesummarydialog.cpp.
References _configFileList, and fillConfigTable().
Referenced by MainWindow::on_multizoneSummaryAllConfigButton_clicked().
 {
     _configFileList = _list;
     fillConfigTable();
 }
void MultizoneSummaryDialog::setProjectPath (QString _path)
Definition at line 166 of file multizonesummarydialog.cpp.
References _projectPath.
Referenced by MainWindow::on_multizoneSummaryAllConfigButton_clicked().
 {
     _projectPath = _path;
 }
void MultizoneSummaryDialog::setSolverManager (SolverConfigManager * _manager)
Definition at line 170 of file multizonesummarydialog.cpp.
References _solverManager.
Referenced by MainWindow::on_multizoneSummaryAllConfigButton_clicked().
 {
     _solverManager = _manager;
 }
Member Data Documentation
QStringList MultizoneSummaryDialog::_configFileList private
Definition at line 35 of file multizonesummarydialog.h.
Referenced by fillConfigTable(), and setConfigFileList().
QString MultizoneSummaryDialog::_projectPath private
Definition at line 34 of file multizonesummarydialog.h.
Referenced by on_selectConfigFilesTable_cellClicked(), and setProjectPath().
int MultizoneSummaryDialog::_selectedRow private
Definition at line 36 of file multizonesummarydialog.h.
Referenced by MultizoneSummaryDialog(), and on_selectConfigFilesTable_cellClicked().
SolverConfigManager* MultizoneSummaryDialog::_solverManager private
Definition at line 37 of file multizonesummarydialog.h.
Referenced by removeDefaultValues(), and setSolverManager().
Ui::MultizoneSummaryDialog* MultizoneSummaryDialog::ui private
Definition at line 33 of file multizonesummarydialog.h.
Referenced by fillConfigTable(), fillDataTable(), insertRow(), MultizoneSummaryDialog(), on_selectConfigFilesTable_cellClicked(), resetTable(), and ~MultizoneSummaryDialog().
The documentation for this class was generated from the following files:
Forms/SummaryDialog/multizonesummarydialog.h
Forms/SummaryDialog/multizonesummarydialog.cpp