BBIPED Platform: ProjectMenuTreeHelper Class Reference
ProjectMenuTreeHelper Class Reference
#include <projectmenutreehelper.h>
Public Member Functions
ProjectMenuTreeHelper ()
void clearProjectTreeView ()
void fillProjectTreeView (QString _projectPath)
Initialize and update the tree view.
void openFileInTabFromClickedElement (QFileInfo _file, QTextEdit *_textEditor, QTabWidget *_tabWidget)
Function that controls the opening of a text file into a new tab element from user double click.
void registerMenuTree (QTreeView *_tree)
Private Attributes
QTreeView * _registeredTree
Detailed Description
Definition at line 9 of file projectmenutreehelper.h.
Constructor & Destructor Documentation
ProjectMenuTreeHelper::ProjectMenuTreeHelper ()
Definition at line 31 of file projectmenutreehelper.cpp.
 {
 }
Member Function Documentation
void ProjectMenuTreeHelper::clearProjectTreeView ()
or reset the project tree view
Definition at line 87 of file projectmenutreehelper.cpp.
References _registeredTree.
Referenced by MainWindow::closeProject().
 {
     if (!_registeredTree)
         return;
     _registeredTree->reset();
 /*   QModelIndex _parent =  _registeredTree->rootIndex();
    for (int i = 1; i> 0; i--)
     {
         _registeredTree->model()->removeRow(i,_parent);
     }
    _registeredTree->reset();
    */
 }
void ProjectMenuTreeHelper::fillProjectTreeView (QString _projectPath)
Initialize and update the tree view.
Parameters
_projectPath
Definition at line 110 of file projectmenutreehelper.cpp.
References _registeredTree, TreeColDate, TreeColSize, and TreeColType.
Referenced by MultizoneManager::launchMultizoneDialog(), MainWindow::on_actionSave_As_triggered(), MultizoneManager::openMultizoneProject(), and MainWindow::updateMainWindowElements().
 {
     if (!_registeredTree)
         return;
     QFileSystemModel *_model = new QFileSystemModel();
     _model->setRootPath(_projectPath);
     _registeredTree->setModel(_model);
     _registeredTree->setAnimated(false);
     _registeredTree->setIndentation(20);
     _registeredTree->setSortingEnabled(true);
     _registeredTree->hideColumn(TreeColDate);
     _registeredTree->hideColumn(TreeColSize);
     _registeredTree->hideColumn(TreeColType);
     _registeredTree->setRootIndex(_model->index(_projectPath));
     _registeredTree->setWindowTitle(QObject::tr("Project View"));
     _registeredTree->show();
 }
void ProjectMenuTreeHelper::openFileInTabFromClickedElement (QFileInfo _file, QTextEdit * _textEditor, QTabWidget * _tabWidget)
Function that controls the opening of a text file into a new tab element from user double click.
Parameters
_file
_textEditor
_tabWidget
Definition at line 46 of file projectmenutreehelper.cpp.
References SOLVER_CONFIG_FILE_EXT, and StrEqual.
Referenced by MainWindow::on_projectTreeView_doubleClicked().
 {
     // If it is a file, we will open it in a new window or in the correspondent tab
     if(!_file.isDir())
     {
         if (_file.isFile())
         {
             if (QString::compare(_file.suffix(),SOLVER_CONFIG_FILE_EXT) == StrEqual)
             {
                 QFile _fileToRead(_file.absoluteFilePath());
                if(_fileToRead.open(_fileToRead.Text | _fileToRead.ReadOnly))
                {
                    QString text = _fileToRead.readAll();
                    _textEditor->setText(text);
                }
                else
                   _textEditor->setText("Error Opening File");
                _textEditor->setVisible(true);
                _textEditor->setReadOnly(true);
                _textEditor->setTextInteractionFlags(_textEditor  -> textInteractionFlags() | Qt::TextSelectableByKeyboard);
                QIcon _icon(":/new/toolbarIcons/images/page_white.png");
                _tabWidget->addTab(_textEditor, _icon,_file.fileName());
                _tabWidget->setTabsClosable(true);
             }
         }
     }
 }
void ProjectMenuTreeHelper::registerMenuTree (QTreeView * _tree)
Definition at line 34 of file projectmenutreehelper.cpp.
References _registeredTree.
Referenced by MainWindow::initializeHelper(), and MultizoneManager::registerUIElements().
 {
     _registeredTree = _tree;
 }
Member Data Documentation
QTreeView* ProjectMenuTreeHelper::_registeredTree private
Definition at line 19 of file projectmenutreehelper.h.
Referenced by clearProjectTreeView(), fillProjectTreeView(), and registerMenuTree().
The documentation for this class was generated from the following files:
WindowHelper/projectmenutreehelper.h
WindowHelper/projectmenutreehelper.cpp