BBIPED Platform: TemplateManager Class Reference
TemplateManager Class Reference
#include <templatemanager.h>
Public Member Functions
TemplateManager ()
Constructor.
void saveTemplate (QString _templatePath, QHash< QString, QString > _selVar)
Save the template values in a file.
void setSectionTreeList (QList< SolverSectionVO > _list)
Sets the tree list.
Private Member Functions
void createComboValues (SolverVariableVO _variableVO, QXmlStreamWriter *_xmlWriter)
Writes the combo values element.
void createHelpElement (SolverVariableVO _variableVO, QXmlStreamWriter *_xmlWriter)
Writes the help content element.
void createSectionElement (QString _sectionName, QXmlStreamWriter *_xmlWriter)
Writes the section element.
void createSubsectionList (QString _sectionName, QXmlStreamWriter *_xmlWriter)
Writes the subsection element.
void createTemplateFile (QStringList _sectionList, QXmlStreamWriter *_xmlWriter)
Write the template file according the list of variables.
void createValueTag (SolverVariableVO _variableVO, QXmlStreamWriter *_xmlWriter)
Writes the value tag element.
void createVariable (SolverVariableVO _variableVO, QXmlStreamWriter *_xmlWriter)
Writes the variable element.
void createVariableList (QString _sectionName, QString _subSectionName, QXmlStreamWriter *_xmlWriter)
void createVariableList (QString _subSectionName, QXmlStreamWriter *_xmlWriter)
Writes the list of variables element.
void createXmlElement (QString _tagName, QString _value, QXmlStreamWriter *_xmlWriter)
Writes a Xml node element.
QStringList getSectionNames ()
Gets the list of sections.
QStringList getSubSectionNames ()
Gets the list of subsections.
QStringList getSubSectionNamesBySectionName (QString _sectionName)
get the SubSectionames associated to a section
QStringList getVariableNames (QString _subSectionName)
Gets the list of variables of a subsection.
QList< SolverVariableVO > getVariables (QString _subSectionName)
Gets teh list of solver variables associated to a subSection.
Private Attributes
int _sectionId
QList< SolverSectionVO > _sectionTreeList
QHash< QString, QString > _selectedVariables
int _subsectionId
int _variableId
Detailed Description
Definition at line 11 of file templatemanager.h.
Constructor & Destructor Documentation
TemplateManager::TemplateManager ()
Constructor.
Definition at line 33 of file templatemanager.cpp.
References _sectionId, _subsectionId, and _variableId.
 {
     _sectionId = 0;
     _subsectionId = 0;
     _variableId = 0;
 }
Member Function Documentation
void TemplateManager::createComboValues (SolverVariableVO _variableVO, QXmlStreamWriter * _xmlWriter) private
Writes the combo values element.
Parameters
_variableVO
_xmlWriter
Definition at line 244 of file templatemanager.cpp.
References SolverVariableVO::getComboValueNamesList(), SolverVariableVO::getComboValuesList(), XML_VARIABLE_COMBOVALUE_ELEMENT_NAME, XML_VARIABLE_COMBOVALUE_NAME_ATT, and XML_VARIABLE_COMBOVALUES_LIST_NAME.
Referenced by createVariable().
 {
     _xmlWriter->writeStartElement(XML_VARIABLE_COMBOVALUES_LIST_NAME);
     QStringList _comboValList = _variableVO.getComboValuesList();
     QStringList _comboValNameList = _variableVO.getComboValueNamesList();
     if (!_comboValNameList.isEmpty())
         for (int i = 0; i < _comboValNameList.size();i++)
         {
             _xmlWriter->writeStartElement(XML_VARIABLE_COMBOVALUE_ELEMENT_NAME);
             _xmlWriter->writeAttribute(XML_VARIABLE_COMBOVALUE_NAME_ATT,_comboValNameList.at(i));
             _xmlWriter->writeCharacters(_comboValList.at(i));
             _xmlWriter->writeEndElement();
         }
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createHelpElement (SolverVariableVO _variableVO, QXmlStreamWriter * _xmlWriter) private
Writes the help content element.
Parameters
_variableVO
_xmlWriter
Definition at line 217 of file templatemanager.cpp.
References SolverVarHelpVO::getDefinitionText(), SolverVarHelpVO::getDetailsText(), SolverVariableVO::getHelperContents(), SolverVarHelpVO::getValuesText(), XML_VARIABLE_HELP_DEF_ATT, XML_VARIABLE_HELP_NAME, XML_VARIABLE_HELP_OTHERDETAILS_ATT, and XML_VARIABLE_HELP_VAL_ATT.
Referenced by createVariable().
 {
     _xmlWriter->writeStartElement(XML_VARIABLE_HELP_NAME);
     SolverVarHelpVO _help = _variableVO.getHelperContents();
     _xmlWriter->writeStartElement(XML_VARIABLE_HELP_DEF_ATT);
     _xmlWriter->writeCharacters(_help.getDefinitionText());
     _xmlWriter->writeEndElement();
     _xmlWriter->writeStartElement(XML_VARIABLE_HELP_VAL_ATT);
     _xmlWriter->writeCharacters(_help.getValuesText());
     _xmlWriter->writeEndElement();
     _xmlWriter->writeStartElement(XML_VARIABLE_HELP_OTHERDETAILS_ATT);
     _xmlWriter->writeCharacters(_help.getDetailsText());
     _xmlWriter->writeEndElement();
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createSectionElement (QString _sectionName, QXmlStreamWriter * _xmlWriter) private
Writes the section element.
Parameters
_sectionName
_xmlWriter
Definition at line 107 of file templatemanager.cpp.
References _sectionId, createSubsectionList(), createXmlElement(), XML_SECTION_ID_NAME, XML_SECTION_NODE_NAME, XML_SECTION_TITLE_IN_BASIC_VIEW_ATT, XML_SECTION_TITLE_VISIBLE_CHILDREN_ATT, and XML_TITLE_SECTION_NAME.
Referenced by createTemplateFile().
 {
      // Create Section Element
     _xmlWriter->writeStartElement(XML_SECTION_NODE_NAME);// section
     // Create the title section
     //createXmlElement(XML_TITLE_SECTION_NAME,_sectionName,_xmlWriter);
     _xmlWriter->writeStartElement(XML_TITLE_SECTION_NAME);
     _xmlWriter->writeAttribute(XML_SECTION_TITLE_IN_BASIC_VIEW_ATT,"yes");
     _xmlWriter->writeAttribute(XML_SECTION_TITLE_VISIBLE_CHILDREN_ATT,"yes");
     _xmlWriter->writeCharacters(_sectionName);
     _xmlWriter->writeEndElement();
     // Create the id
     createXmlElement(XML_SECTION_ID_NAME,QString::number(_sectionId),_xmlWriter);
     _sectionId++;
     // Create the subsectionList Element
     createSubsectionList(_sectionName,_xmlWriter);
     // End of section element
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createSubsectionList (QString _sectionName, QXmlStreamWriter * _xmlWriter) private
Writes the subsection element.
Parameters
_sectionName
_xmlWriter
Definition at line 138 of file templatemanager.cpp.
References _subsectionId, createVariableList(), createXmlElement(), getSubSectionNamesBySectionName(), XML_SUBSECTION_ID_NAME, XML_SUBSECTION_LIST_NAME, XML_SUBSECTION_NAME, XML_SUBSECTION_TITLE_NAME, and XML_SUBSECTION_VISIBLE_IN_BASIC_VIEW_ATT.
Referenced by createSectionElement().
 {
     // Create the SubsectionList Name
     _xmlWriter->writeStartElement(XML_SUBSECTION_LIST_NAME); // subsections
     QStringList _selSubSectionList = getSubSectionNamesBySectionName(_sectionName);
     if (!_selSubSectionList.isEmpty())
     {
         for (int i = 0; i < _selSubSectionList.size(); i++)
         {
             _xmlWriter->writeStartElement(XML_SUBSECTION_NAME); // subsection
             _xmlWriter->writeAttribute(XML_SUBSECTION_VISIBLE_IN_BASIC_VIEW_ATT,"yes");
             // Create the title
             createXmlElement(XML_SUBSECTION_TITLE_NAME,_selSubSectionList.at(i),_xmlWriter);
             // Create the id
             createXmlElement(XML_SUBSECTION_ID_NAME,QString::number(_subsectionId),_xmlWriter);
             _subsectionId++;
             createVariableList(_selSubSectionList.at(i), _xmlWriter);
             // End subsection name
             _xmlWriter->writeEndElement();
         }
     }
     // End SubsectionList Name
     _xmlWriter->writeEndElement();
     _subsectionId = 0; // reset the counter
 }
void TemplateManager::createTemplateFile (QStringList _sectionList, QXmlStreamWriter * _xmlWriter) private
Write the template file according the list of variables.
Parameters
_sectionList
_xmlWriter
Definition at line 86 of file templatemanager.cpp.
References createSectionElement(), XML_ROOT_NODE_NAME, and XML_SECTION_LIST_NAME.
Referenced by saveTemplate().
 {
     _xmlWriter->writeStartElement(XML_ROOT_NODE_NAME);
     _xmlWriter->writeStartElement(XML_SECTION_LIST_NAME); // sections
     for (int i = 0; i < _sectionList.size(); i++)
         createSectionElement(_sectionList.at(i),_xmlWriter);
     // End sections list
     _xmlWriter->writeEndElement();
     // End of the root element
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createValueTag (SolverVariableVO _variableVO, QXmlStreamWriter * _xmlWriter) private
Writes the value tag element.
Parameters
_variableVO
_xmlWriter
Definition at line 266 of file templatemanager.cpp.
References SolverVariableVO::getDefaultValue(), SolverVariableVO::getUnitValue(), SolverVariableVO::getVariableFileName(), XML_VARIABLE_VALUE_DEFAULT_VALUE_ATT, XML_VARIABLE_VALUE_NAME, XML_VARIABLE_VALUE_NAME_ATT, and XML_VARIABLE_VALUE_UNIT_ATT.
Referenced by createVariable().
 {
     _xmlWriter->writeStartElement(XML_VARIABLE_VALUE_NAME);
     _xmlWriter->writeAttribute(XML_VARIABLE_VALUE_NAME_ATT,_variableVO.getVariableFileName());
     _xmlWriter->writeAttribute(XML_VARIABLE_VALUE_DEFAULT_VALUE_ATT, _variableVO.getDefaultValue());
     _xmlWriter->writeAttribute(XML_VARIABLE_VALUE_UNIT_ATT,_variableVO.getUnitValue());
     _xmlWriter->writeCharacters(_variableVO.getDefaultValue());
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createVariable (SolverVariableVO _variableVO, QXmlStreamWriter * _xmlWriter) private
Writes the variable element.
Parameters
_variableVO
_xmlWriter
Definition at line 193 of file templatemanager.cpp.
References _variableId, createComboValues(), createHelpElement(), createValueTag(), createXmlElement(), SolverVariableVO::getVariableName(), XML_VARIABLE_ID_ATT, XML_VARIABLE_NAME, and XML_VARIABLE_NAME_NAME.
Referenced by createVariableList().
 {
     _xmlWriter->writeStartElement(XML_VARIABLE_NAME);
     _xmlWriter->writeAttribute(XML_VARIABLE_ID_ATT,QString::number(_variableId));
     _variableId++;
     // Write Name
     createXmlElement(XML_VARIABLE_NAME_NAME, _variableVO.getVariableName(),_xmlWriter);
     // Write Help
     createHelpElement(_variableVO, _xmlWriter);
     // Write ComboValues
     createComboValues(_variableVO,_xmlWriter);
     // Write Value
     createValueTag(_variableVO,_xmlWriter);
     _xmlWriter->writeEndElement();
 }
void TemplateManager::createVariableList (QString _sectionName, QString _subSectionName, QXmlStreamWriter * _xmlWriter) private
Referenced by createSubsectionList().
void TemplateManager::createVariableList (QString _subSectionName, QXmlStreamWriter * _xmlWriter) private
Writes the list of variables element.
Parameters
_subSectionName
_xmlWriter
Definition at line 174 of file templatemanager.cpp.
References _variableId, createVariable(), getVariables(), and XML_VARIABLE_LIST_NAME.
 {
     _xmlWriter->writeStartElement(XML_VARIABLE_LIST_NAME);
     QList<SolverVariableVO> _varList = getVariables(_subSectionName);
     for (int i = 0; i <_varList.size();i++)
         createVariable(_varList.at(i),_xmlWriter);
     // End of the variableList
     _xmlWriter->writeEndElement();
     _variableId = 0; // reset the Counter
 }
void TemplateManager::createXmlElement (QString _tagName, QString _value, QXmlStreamWriter * _xmlWriter) private
Writes a Xml node element.
Parameters
_tagName
_value
_xmlWriter
Definition at line 284 of file templatemanager.cpp.
Referenced by createSectionElement(), createSubsectionList(), and createVariable().
 {
     _xmlWriter->writeStartElement(_tagName);
     _xmlWriter->writeCharacters(_value);
     _xmlWriter->writeEndElement();
 }
QStringList TemplateManager::getSectionNames () private
Gets the list of sections.
Returns
QStringList
Definition at line 333 of file templatemanager.cpp.
References _sectionTreeList, SolverSectionDAO::findSectionNameBySubSectionName(), and getSubSectionNames().
Referenced by saveTemplate().
 {
     QStringList _result;
     QStringList _subSectionNameList = getSubSectionNames();
     SolverSectionDAO _solverDAO;
     for (int i = 0; i < _subSectionNameList.size();i++)
     {
         QString _sectionName = _solverDAO.findSectionNameBySubSectionName(_subSectionNameList.at(i),_sectionTreeList);
         if( (!_sectionName.isEmpty()) && (!_result.contains(_sectionName)) )
             _result.append(_sectionName);
     }
     return _result;
 }
QStringList TemplateManager::getSubSectionNames () private
Gets the list of subsections.
Returns
QStringList
Definition at line 354 of file templatemanager.cpp.
References _selectedVariables.
Referenced by getSectionNames(), and getSubSectionNamesBySectionName().
 {
         QStringList _result;
     QHashIterator<QString, QString> _iter(_selectedVariables);
     while (_iter.hasNext())
     {
         _iter.next();
         QString _subSectionName = _iter.value();
         if ( (!_subSectionName.isEmpty()) && (!_result.contains(_subSectionName)) )
             _result.append(_subSectionName);
     }
     return _result;
 }
QStringList TemplateManager::getSubSectionNamesBySectionName (QString _sectionName) private
get the SubSectionames associated to a section
Parameters
_sectionName
Returns
QStringList
Definition at line 376 of file templatemanager.cpp.
References _sectionTreeList, SolverSectionDAO::findSubSectionNamesBySectionName(), and getSubSectionNames().
Referenced by createSubsectionList().
 {
     QStringList _result;
     SolverSectionDAO _solverDAO;
     QStringList _subSectionList = _solverDAO.findSubSectionNamesBySectionName(_sectionName,_sectionTreeList);
     QStringList _cSelectedSubSection = getSubSectionNames();
     if ( (_subSectionList.isEmpty()) && (_cSelectedSubSection.isEmpty()) )
        return _result;
     for (int i = 0; i < _subSectionList.size();i++ )
     {
         if (_cSelectedSubSection.contains(_subSectionList.at(i)))
             _result.append(_subSectionList.at(i));
     }
     return _result;
 }
QStringList TemplateManager::getVariableNames (QString _subSectionName) private
Gets the list of variables of a subsection.
Parameters
_subSectionName
Returns
QStringList
Definition at line 404 of file templatemanager.cpp.
References _selectedVariables, and StrEqual.
Referenced by getVariables().
 {
     QStringList _result;
     if (_subSectionName.isEmpty())
             return _result;
     QHashIterator<QString, QString> _iter(_selectedVariables);
     while (_iter.hasNext())
     {
         _iter.next();
         if (QString::compare(_iter.value(), _subSectionName) == StrEqual)
              _result.append(_iter.key());
     }
     return _result;
 }
QList< SolverVariableVO > TemplateManager::getVariables (QString _subSectionName) private
Gets teh list of solver variables associated to a subSection.
Parameters
_subSectionName
Returns
QList<SolverVariableVO>
Definition at line 307 of file templatemanager.cpp.
References _sectionTreeList, SolverSectionDAO::findSubSection(), SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableName(), and getVariableNames().
Referenced by createVariableList().
 {
     SolverSectionDAO _solverDAO;
     QList<SolverVariableVO> _result;
     SolverSectionVO _section = _solverDAO.findSubSection(_subSectionName,_sectionTreeList);
     QList<SolverVariableVO> _fullList = _section.getSubsectionVarList();
     QStringList _varNameList = getVariableNames(_subSectionName);
     if (!_fullList.isEmpty())
         for (int i = 0 ; i < _fullList.size(); i++)
         {
             SolverVariableVO _varVO = _fullList.at(i);
             QString _varName = _varVO.getVariableName();
             if (_varNameList.contains(_varName))
                 _result.append(_varVO);
         }
     return _result;
 }
void TemplateManager::saveTemplate (QString _templatePath, QHash< QString, QString > _selVar)
Save the template values in a file.
Parameters
_templatePath
QHash<QString
_selVar
Definition at line 49 of file templatemanager.cpp.
References _selectedVariables, createTemplateFile(), and getSectionNames().
Referenced by TemplateDialog::on_buttonBox_accepted().
 {
     if ( (_templatePath.isEmpty()) || (_selVar.isEmpty()) )
         return;
     _selectedVariables = _selVar;
     QString _suffix = QFileInfo(_templatePath).suffix();
     if (_suffix.isEmpty())
         _templatePath = _templatePath + ".xml";
     QFile _file(_templatePath);
     if (_file.exists())
         _file.remove();
     bool _fileCreated = _file.open(QIODevice::ReadWrite);
     if ( (_fileCreated) && (!_selectedVariables.isEmpty()) )
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         QStringList _sectionNames = getSectionNames();
         if  (!_sectionNames.isEmpty())
             createTemplateFile(_sectionNames,&xmlWriter);
         xmlWriter.writeEndDocument();
     }
     _file.close();
 }
void TemplateManager::setSectionTreeList (QList< SolverSectionVO > _list)
Sets the tree list.
Parameters
_list
Definition at line 297 of file templatemanager.cpp.
References _sectionTreeList.
Referenced by TemplateDialog::on_buttonBox_accepted().
 {
     _sectionTreeList = _list;
 }
Member Data Documentation
int TemplateManager::_sectionId private
Definition at line 19 of file templatemanager.h.
Referenced by createSectionElement(), and TemplateManager().
QList<SolverSectionVO> TemplateManager::_sectionTreeList private
Definition at line 22 of file templatemanager.h.
Referenced by getSectionNames(), getSubSectionNamesBySectionName(), getVariables(), and setSectionTreeList().
QHash<QString,QString> TemplateManager::_selectedVariables private
Definition at line 23 of file templatemanager.h.
Referenced by getSubSectionNames(), getVariableNames(), and saveTemplate().
int TemplateManager::_subsectionId private
Definition at line 20 of file templatemanager.h.
Referenced by createSubsectionList(), and TemplateManager().
int TemplateManager::_variableId private
Definition at line 21 of file templatemanager.h.
Referenced by createVariable(), createVariableList(), and TemplateManager().
The documentation for this class was generated from the following files:
Templates/templatemanager.h
Templates/templatemanager.cpp