BBIPED Platform: VirtualRotatingDialog Class Reference
VirtualRotatingDialog Class Reference
#include <virtualrotatingdialog.h>
Public Member Functions
VirtualRotatingDialog (QWidget *parent=0)
~VirtualRotatingDialog ()
void fillTable ()
QList< QString > getPreviousZoneInfo ()
QList< SolverVariableVO > getSolverVariableInfoList ()
QList< VirtualMrfVO > getUserDefinedVirtualMRFValues ()
QList< QString > getUserDefinedZoneInfo ()
bool hasUserAcceptModifiedValues ()
void initializeDialog ()
void set2DMeshCase (bool _val)
void setPreviousZoneInfo (QList< QString > _list)
void setSelectedSubmenu (QString _selMenu)
void setSolverSection (SolverSectionVO _element)
void setSolverVariableInfoList (QList< SolverVariableVO > _list)
void setUserDefinedVirtualMRFValues (QList< VirtualMrfVO > _list)
void setUserDefinedZoneInfo (QList< QString > _list)
void updateTableWithUserValues ()
Private Types
enum ColumnTypes
Private Slots
void on_acceptButton_clicked ()
void on_cancelButton_clicked ()
void on_numVirtualZonesSpinBox_valueChanged (int arg1)
void on_zoneInfoTable_cellClicked (int row, int column)
Private Member Functions
void addRow (int _rowPos)
void addRow (int _rowPos, VirtualMrfVO _virtualVO)
void buildAssociatedHelp (int _row)
void createVirtualMRFData (int _row)
void deleteRow (int _rowPos)
void launchCurveDialog (int _row)
void updateVirtualInformation ()
Private Attributes
bool _deletedByUser
bool _is2DMesh
int _numZones
QList< QString > _previousZoneInfo
QList< VirtualMrfVO > _resultUserVirtualMRFList
QString _selectedSubmenu
SolverSectionVO _solverSection
QList< SolverVariableVO > _solverVariableInfoList
bool _userAcceptModifiedValues
QList< QString > _userDefinedZoneInfo
Ui::VirtualRotatingDialog * ui
Detailed Description
Definition at line 16 of file virtualrotatingdialog.h.
Member Enumeration Documentation
enum VirtualRotatingDialog::ColumnTypes private
Enumerator
ColumnDone
ColumnZoneName
ColumnOmega
ColumnAxisCenter
ColumnAxisNormal
ColumnConfigure
ColumnDelete
ColumnHelp
Definition at line 67 of file virtualrotatingdialog.h.
                     {
         ColumnDone=0,
         ColumnZoneName = 1,
         ColumnOmega = 2,
         ColumnAxisCenter =3,
         ColumnAxisNormal = 4,
         ColumnConfigure = 5,
         ColumnDelete =6,
         ColumnHelp=7
     };
Constructor & Destructor Documentation
VirtualRotatingDialog::VirtualRotatingDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 32 of file virtualrotatingdialog.cpp.
References _deletedByUser, _is2DMesh, _selectedSubmenu, _userAcceptModifiedValues, and ui.
                                                             :
     QDialog(parent),
     ui(new Ui::VirtualRotatingDialog)
 {
     ui->setupUi(this);
     _selectedSubmenu = "";
     _deletedByUser  = false;
     _userAcceptModifiedValues = false;
     _is2DMesh = true; // By default, we consider that is a 2D Mesh case
 }
VirtualRotatingDialog::~VirtualRotatingDialog ()
Definition at line 411 of file virtualrotatingdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void VirtualRotatingDialog::addRow (int _rowPos) private
Parameters
_rowPos
Definition at line 150 of file virtualrotatingdialog.cpp.
References _is2DMesh, QtableUtil::addChangedColumn(), QtableUtil::addEditText(), QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnAxisCenter, ColumnAxisNormal, ColumnConfigure, ColumnDelete, ColumnDone, ColumnHelp, ColumnOmega, ColumnZoneName, IconDelete, IconEdit, IconHelp, and ui.
Referenced by fillTable(), and on_numVirtualZonesSpinBox_valueChanged().
 {
     QtableUtil _tableHelper;
     ui->zoneInfoTable->insertRow(_rowPos);
     ui->zoneInfoTable->setItem(_rowPos,ColumnDone,_tableHelper.addChangedColumn());
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnZoneName,_tableHelper.addEditText("Name"));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnOmega,_tableHelper.addEditText("0"));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnAxisCenter,_tableHelper.addEditText("0,0"));
     if (_is2DMesh)
         ui->zoneInfoTable->setItem(_rowPos,ColumnAxisNormal,_tableHelper.addNonEditableText("0,0,1"));
     else
         ui->zoneInfoTable->setCellWidget(_rowPos,ColumnAxisNormal,_tableHelper.addEditText("0,0,0"));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnConfigure,_tableHelper.addIcon(IconEdit));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnDelete,_tableHelper.addIcon(IconDelete));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnHelp,_tableHelper.addIcon(IconHelp));
 }
void VirtualRotatingDialog::addRow (int _rowPos, VirtualMrfVO _virtualVO) private
Parameters
_rowPos
_virtualVO
Definition at line 174 of file virtualrotatingdialog.cpp.
References _is2DMesh, QtableUtil::addChangedColumn(), QtableUtil::addEditText(), QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnAxisCenter, ColumnAxisNormal, ColumnConfigure, ColumnDelete, ColumnDone, ColumnHelp, ColumnOmega, ColumnZoneName, VirtualMrfVO::getAxisCenter(), VirtualMrfVO::getAxisNormal(), VirtualMrfVO::getOmega(), VirtualMrfVO::getZoneName(), IconDelete, IconEdit, IconHelp, and ui.
 {
     QtableUtil _tableHelper;
     ui->zoneInfoTable->insertRow(_rowPos);
     ui->zoneInfoTable->setItem(_rowPos,ColumnDone,_tableHelper.addChangedColumn());
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnZoneName,_tableHelper.addEditText(_virtualVO.getZoneName()));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnOmega,_tableHelper.addEditText(_virtualVO.getOmega()));
     if (_is2DMesh)
     {
         QStringList _centerValues = _virtualVO.getAxisCenter();
         if (_centerValues.size()>2)
             _centerValues.removeAt(2);
         ui->zoneInfoTable->setCellWidget(_rowPos,ColumnAxisCenter,_tableHelper.addEditText(_centerValues.join(",")));
         ui->zoneInfoTable->setItem(_rowPos,ColumnAxisNormal,_tableHelper.addNonEditableText("0,0,1"));
     }else
     {
         ui->zoneInfoTable->setCellWidget(_rowPos,ColumnAxisCenter,_tableHelper.addEditText(_virtualVO.getAxisCenter().join(",")));
         ui->zoneInfoTable->setCellWidget(_rowPos,ColumnAxisNormal,_tableHelper.addEditText(_virtualVO.getAxisNormal().join(",")));
     }
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnConfigure,_tableHelper.addIcon(IconEdit));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnDelete,_tableHelper.addIcon(IconDelete));
     ui->zoneInfoTable->setCellWidget(_rowPos,ColumnHelp,_tableHelper.addIcon(IconHelp));
 }
void VirtualRotatingDialog::buildAssociatedHelp (int _row) private
Parameters
_row
Definition at line 305 of file virtualrotatingdialog.cpp.
References _selectedSubmenu, _solverSection, SolverVariableVO::getHelpContents(), SolverSectionVO::getSubsectionVarList(), HTML_FORMAT_ON, HelpDialog::loadHelpText(), and HelpDialog::setHelpText().
Referenced by on_zoneInfoTable_cellClicked().
 {
     if (_selectedSubmenu.isEmpty())
         return;
     QList<SolverVariableVO> _infoVarVO = _solverSection.getSubsectionVarList();
     if (_infoVarVO.isEmpty())
         return;
     SolverVariableVO _variableVirtualZoneGeneralInfo =  _infoVarVO.at(0);
     QString _helpText = _variableVirtualZoneGeneralInfo.getHelpContents(HTML_FORMAT_ON);
     HelpDialog *  _helpDialog = new HelpDialog();
      _helpDialog->setHelpText(_helpText);
      _helpDialog->loadHelpText();
      _helpDialog->exec();
 }
void VirtualRotatingDialog::createVirtualMRFData (int _row) private
Parameters
_row
Definition at line 253 of file virtualrotatingdialog.cpp.
References _is2DMesh, _resultUserVirtualMRFList, ColumnAxisCenter, ColumnAxisNormal, ColumnOmega, ColumnZoneName, VirtualMrfVO::setAxisCenter(), VirtualMrfVO::setAxisNormal(), VirtualMrfVO::setOmega(), VirtualMrfVO::setZoneName(), and ui.
Referenced by on_zoneInfoTable_cellClicked(), and updateVirtualInformation().
 {
     int _totalRows = ui->zoneInfoTable->rowCount();
     int _totalObjects = _resultUserVirtualMRFList.count();
     bool _needToAdd = false;
     for (int i = 0; i < _totalRows; i++)
     {
         VirtualMrfVO _virtualInfo;
         if (i >= _totalObjects)
             _needToAdd = true;
         else
              _virtualInfo = _resultUserVirtualMRFList.at(i);
         if (i == _row)
         {
             _virtualInfo.setZoneName(((QLineEdit *) ui->zoneInfoTable->cellWidget(_row,ColumnZoneName))->text());
             _virtualInfo.setOmega(((QLineEdit *) ui->zoneInfoTable->cellWidget(_row,ColumnOmega))->text());
             QString _centerValue = ((QLineEdit *) ui->zoneInfoTable->cellWidget(_row,ColumnAxisCenter))->text();
             if (_is2DMesh)
             {
                 QStringList _centerValueList = _centerValue.split(",");
                 if (_centerValueList.size() > 2)
                     for (int i=_centerValueList.size(); i >= 2;i--)
                         _centerValueList.removeAt(i);
                 _centerValueList.append("0");
                 _centerValue = _centerValueList.join(",");
             }
             _virtualInfo.setAxisCenter(_centerValue.split(","));
             if (_is2DMesh)
                 _virtualInfo.setAxisNormal(QString("0,0,1").split(","));
             else
                 _virtualInfo.setAxisNormal(((QLineEdit *) ui->zoneInfoTable->cellWidget(_row,ColumnAxisNormal))->text().split(","));
         }
         if (_needToAdd)
             _resultUserVirtualMRFList.append(_virtualInfo);
         else
             _resultUserVirtualMRFList[i] = _virtualInfo;
     }
 }
void VirtualRotatingDialog::deleteRow (int _rowPos) private
Parameters
_rowPos
Definition at line 205 of file virtualrotatingdialog.cpp.
References _resultUserVirtualMRFList, and ui.
Referenced by on_numVirtualZonesSpinBox_valueChanged(), and on_zoneInfoTable_cellClicked().
 {
     // We need to delete the objects that corresponds
     if ((!_resultUserVirtualMRFList.isEmpty()) && (_rowPos < _resultUserVirtualMRFList.count()))
         _resultUserVirtualMRFList.removeAt(_rowPos);
     // Updating and removing the view
     ui->zoneInfoTable->removeRow(_rowPos);
     int _totalZones = ui->zoneInfoTable->rowCount();
     // Update the spinBox value accordingly
     ui->numVirtualZonesSpinBox->setValue(_totalZones);
 }
void VirtualRotatingDialog::fillTable ()
Definition at line 67 of file virtualrotatingdialog.cpp.
References _resultUserVirtualMRFList, and addRow().
Referenced by initializeDialog().
 {
     int _numRows = _resultUserVirtualMRFList.count();
     for (int i = 0; i < _numRows; i++)
     {
         VirtualMrfVO _virtualVO = _resultUserVirtualMRFList.at(i);
         addRow(i,_virtualVO);
     }
 }
QList< QString > VirtualRotatingDialog::getPreviousZoneInfo ()
Returns
QList<QString>
Definition at line 482 of file virtualrotatingdialog.cpp.
References _previousZoneInfo.
 {
     return _previousZoneInfo;
 }
QList< SolverVariableVO > VirtualRotatingDialog::getSolverVariableInfoList ()
Returns
QList<SolverVariableVO>
Definition at line 462 of file virtualrotatingdialog.cpp.
References _solverVariableInfoList.
 {
     return _solverVariableInfoList;
 }
QList< VirtualMrfVO > VirtualRotatingDialog::getUserDefinedVirtualMRFValues ()
Returns
QList<VirtualMrfVO>
Definition at line 431 of file virtualrotatingdialog.cpp.
References _resultUserVirtualMRFList.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     return _resultUserVirtualMRFList;
 }
QList< QString > VirtualRotatingDialog::getUserDefinedZoneInfo ()
Returns
QList<QString>
Definition at line 502 of file virtualrotatingdialog.cpp.
References _userDefinedZoneInfo.
 {
     return _userDefinedZoneInfo;
 }
bool VirtualRotatingDialog::hasUserAcceptModifiedValues ()
Returns
bool
Definition at line 421 of file virtualrotatingdialog.cpp.
References _userAcceptModifiedValues.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     return _userAcceptModifiedValues;
 }
void VirtualRotatingDialog::initializeDialog ()
Definition at line 49 of file virtualrotatingdialog.cpp.
References _resultUserVirtualMRFList, fillTable(), and ui.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     if (!_resultUserVirtualMRFList.isEmpty())
     {
         fillTable();
         ui->numVirtualZonesSpinBox->blockSignals(true);
         ui->numVirtualZonesSpinBox->setValue(_resultUserVirtualMRFList.count());
         ui->numVirtualZonesSpinBox->blockSignals(false);
     }
 }
void VirtualRotatingDialog::launchCurveDialog (int _row) private
Parameters
_row
Definition at line 326 of file virtualrotatingdialog.cpp.
References _is2DMesh, _resultUserVirtualMRFList, _solverSection, ColumnDone, VirtualMrfVO::getInnerCurvePoints(), VirtualCurveDialog::getInnerValues(), VirtualMrfVO::getOuterCurvePoints(), VirtualCurveDialog::getOuterValues(), VirtualCurveDialog::hasUserModifiedValues(), VirtualCurveDialog::initializeDialog(), VirtualCurveDialog::is3DCoordinates(), VirtualMrfVO::isEmpty(), VirtualCurveDialog::set3DCoordinates(), VirtualMrfVO::setCoordinatesIn3D(), VirtualMrfVO::setInnerCurvePoints(), VirtualCurveDialog::setInnerValues(), VirtualMrfVO::setOuterCurvePoints(), VirtualCurveDialog::setOuterValues(), VirtualCurveDialog::setSolverSection(), and ui.
Referenced by on_zoneInfoTable_cellClicked().
 {
     VirtualMrfVO _virtualVO;
     _virtualVO = _resultUserVirtualMRFList.at(_row);
     VirtualCurveDialog  _virtualCurveDialog;
     _virtualCurveDialog.setSolverSection(_solverSection);
     if (!_virtualVO.isEmpty())
     {
         QStringList _listInnerPoints = _virtualVO.getInnerCurvePoints();
         QStringList _listOuterPoints = _virtualVO.getOuterCurvePoints();
         QString _point1;
         QString _point2;
         if (_is2DMesh)
         {
              _point1 = "-1,0";
              _point2 = "1,0";
         }else
         {
             // By default in 3D, we need a minimum of 2 points
             _point1 = "0,0";
             _point2 = "0,0";
         }
         if (_listInnerPoints.size() == 0)
         {
             _listInnerPoints.append(_point1.split(","));
             _listInnerPoints.append(_point2.split(","));
         }
         if (_listOuterPoints.size() == 0)
         {
             _listOuterPoints.append(_point1.split(","));
             _listOuterPoints.append(_point2.split(","));
         }
         if ((_is2DMesh) && (_listInnerPoints.size() > 4 ))
             for (int i=_listInnerPoints.size();i>3;i--)
                 _listInnerPoints.removeAt(i);
         // we need to be sure that the points follow the same structre 1,x; -1,y
         _listInnerPoints.replace(0, QString("-1"));
         _listInnerPoints.replace(2, QString("1"));
         if ((_is2DMesh) && (_listOuterPoints.size() > 4 ))
             for (int i=_listOuterPoints.size();i>3;i--)
                 _listOuterPoints.removeAt(i);
         // we need to be sure that the points follow the same structre 1,x; -1,y
         _listOuterPoints.replace(0, QString("-1"));
         _listOuterPoints.replace(2, QString("1"));
         _virtualCurveDialog.setInnerValues(_listInnerPoints);
         _virtualCurveDialog.setOuterValues(_listOuterPoints);
         _virtualCurveDialog.set3DCoordinates(!_is2DMesh);
         _virtualCurveDialog.initializeDialog();
     }
     _virtualCurveDialog.exec();
     // If it is accepted the changes we can mark is as done
    if (_virtualCurveDialog.hasUserModifiedValues())
     {
         ui->zoneInfoTable->item(_row,ColumnDone)->setCheckState(Qt::Checked);
         // Save the results of the user
         _virtualVO.setInnerCurvePoints(_virtualCurveDialog.getInnerValues());
         _virtualVO.setOuterCurvePoints(_virtualCurveDialog.getOuterValues());
         _virtualVO.setCoordinatesIn3D(_virtualCurveDialog.is3DCoordinates());
         _resultUserVirtualMRFList.replace(_row,_virtualVO);
     }
 }
void VirtualRotatingDialog::on_acceptButton_clicked () private slot
Definition at line 83 of file virtualrotatingdialog.cpp.
References _userAcceptModifiedValues, and updateVirtualInformation().
 {
     _userAcceptModifiedValues = true;
     updateVirtualInformation();
     close();
 }
void VirtualRotatingDialog::on_cancelButton_clicked () private slot
Definition at line 94 of file virtualrotatingdialog.cpp.
References _userAcceptModifiedValues.
 {
     _userAcceptModifiedValues = false;
     close();
 }
void VirtualRotatingDialog::on_numVirtualZonesSpinBox_valueChanged (int arg1) private slot
Parameters
arg1
Definition at line 119 of file virtualrotatingdialog.cpp.
References addRow(), deleteRow(), and ui.
 {
     int _totalRows = ui->zoneInfoTable->rowCount();
     int _newZoneNo = arg1;
     int _cZoneNo = _totalRows;
     if (_newZoneNo > _cZoneNo) // We need to add new rows
     {
         int _noNewRows = _newZoneNo - _cZoneNo;
         for (int i = 0;i < _noNewRows;i++)
             addRow(_cZoneNo+i);
     }
     else{
         if (_newZoneNo < _cZoneNo) // We need to delete rows
         {
             int _noDeletedRows = _cZoneNo -_newZoneNo;
             ui->numVirtualZonesSpinBox->blockSignals(true);
             for (int i = 0; i <= _noDeletedRows;i++)
                 deleteRow(_totalRows - i);
             ui->numVirtualZonesSpinBox->blockSignals(false);
         }
     }
 }
void VirtualRotatingDialog::on_zoneInfoTable_cellClicked (int row, int column) private slot
Parameters
row
column
Definition at line 228 of file virtualrotatingdialog.cpp.
References buildAssociatedHelp(), ColumnConfigure, ColumnDelete, ColumnHelp, createVirtualMRFData(), deleteRow(), launchCurveDialog(), and ui.
 {
     switch (column)
     {
     case ColumnConfigure:
         createVirtualMRFData(row); //We only create them at the moment of configuration
         launchCurveDialog(row);
         break;
     case ColumnDelete: // We need to remove the objects accordingly
         ui->numVirtualZonesSpinBox->blockSignals(true);
         deleteRow(row);
         ui->numVirtualZonesSpinBox->blockSignals(false);
         break;
     case ColumnHelp:
         buildAssociatedHelp(row);
         break;
     }
 }
void VirtualRotatingDialog::set2DMeshCase (bool _val)
Definition at line 401 of file virtualrotatingdialog.cpp.
References _is2DMesh.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     _is2DMesh = _val;
 }
void VirtualRotatingDialog::setPreviousZoneInfo (QList< QString > _list)
Parameters
_list
Definition at line 492 of file virtualrotatingdialog.cpp.
References _previousZoneInfo.
 {
     _previousZoneInfo = _list;
 }
void VirtualRotatingDialog::setSelectedSubmenu (QString _selMenu)
Parameters
_selMenu
Definition at line 451 of file virtualrotatingdialog.cpp.
References _selectedSubmenu.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     _selectedSubmenu = _selMenu;
 }
void VirtualRotatingDialog::setSolverSection (SolverSectionVO _element)
Parameters
_element
Definition at line 441 of file virtualrotatingdialog.cpp.
References _solverSection.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     _solverSection =_element;
 }
void VirtualRotatingDialog::setSolverVariableInfoList (QList< SolverVariableVO > _list)
Parameters
_list
Definition at line 472 of file virtualrotatingdialog.cpp.
References _solverVariableInfoList.
 {
     _solverVariableInfoList = _list;
 }
void VirtualRotatingDialog::setUserDefinedVirtualMRFValues (QList< VirtualMrfVO > _list)
Parameters
_list
Definition at line 521 of file virtualrotatingdialog.cpp.
References _resultUserVirtualMRFList.
Referenced by SolverBasicDialog::launchVirtualRotatingDialog().
 {
     _resultUserVirtualMRFList = _list;
 }
void VirtualRotatingDialog::setUserDefinedZoneInfo (QList< QString > _list)
Parameters
_list
Definition at line 512 of file virtualrotatingdialog.cpp.
References _userDefinedZoneInfo.
 {
     _userDefinedZoneInfo = _list;
 }
void VirtualRotatingDialog::updateTableWithUserValues ()
void VirtualRotatingDialog::updateVirtualInformation () private
Definition at line 104 of file virtualrotatingdialog.cpp.
References createVirtualMRFData(), and ui.
Referenced by on_acceptButton_clicked().
 {
     int _totalRows = ui->zoneInfoTable->rowCount();
     if ( _totalRows== 0)
         return;
     for (int i = 0; i <_totalRows; i++ )
         createVirtualMRFData(i);
 }
Member Data Documentation
bool VirtualRotatingDialog::_deletedByUser private
Definition at line 64 of file virtualrotatingdialog.h.
Referenced by VirtualRotatingDialog().
bool VirtualRotatingDialog::_is2DMesh private
Definition at line 65 of file virtualrotatingdialog.h.
Referenced by addRow(), createVirtualMRFData(), launchCurveDialog(), set2DMeshCase(), and VirtualRotatingDialog().
int VirtualRotatingDialog::_numZones private
Definition at line 61 of file virtualrotatingdialog.h.
QList<QString> VirtualRotatingDialog::_previousZoneInfo private
Definition at line 59 of file virtualrotatingdialog.h.
Referenced by getPreviousZoneInfo(), and setPreviousZoneInfo().
QList<VirtualMrfVO> VirtualRotatingDialog::_resultUserVirtualMRFList private
Definition at line 63 of file virtualrotatingdialog.h.
Referenced by createVirtualMRFData(), deleteRow(), fillTable(), getUserDefinedVirtualMRFValues(), initializeDialog(), launchCurveDialog(), and setUserDefinedVirtualMRFValues().
QString VirtualRotatingDialog::_selectedSubmenu private
Definition at line 78 of file virtualrotatingdialog.h.
Referenced by buildAssociatedHelp(), setSelectedSubmenu(), and VirtualRotatingDialog().
SolverSectionVO VirtualRotatingDialog::_solverSection private
Definition at line 57 of file virtualrotatingdialog.h.
Referenced by buildAssociatedHelp(), launchCurveDialog(), and setSolverSection().
QList<SolverVariableVO> VirtualRotatingDialog::_solverVariableInfoList private
Definition at line 58 of file virtualrotatingdialog.h.
Referenced by getSolverVariableInfoList(), and setSolverVariableInfoList().
bool VirtualRotatingDialog::_userAcceptModifiedValues private
Definition at line 79 of file virtualrotatingdialog.h.
Referenced by hasUserAcceptModifiedValues(), on_acceptButton_clicked(), on_cancelButton_clicked(), and VirtualRotatingDialog().
QList<QString> VirtualRotatingDialog::_userDefinedZoneInfo private
Definition at line 60 of file virtualrotatingdialog.h.
Referenced by getUserDefinedZoneInfo(), and setUserDefinedZoneInfo().
Ui::VirtualRotatingDialog* VirtualRotatingDialog::ui private
Definition at line 56 of file virtualrotatingdialog.h.
Referenced by addRow(), createVirtualMRFData(), deleteRow(), initializeDialog(), launchCurveDialog(), on_numVirtualZonesSpinBox_valueChanged(), on_zoneInfoTable_cellClicked(), updateVirtualInformation(), VirtualRotatingDialog(), and ~VirtualRotatingDialog().
The documentation for this class was generated from the following files:
Forms/VirtualRotatingDialog/virtualrotatingdialog.h
Forms/VirtualRotatingDialog/virtualrotatingdialog.cpp