BBIPED Platform: HtmlFormatter Class Reference
HtmlFormatter Class Reference
#include <htmlformatter.h>
Public Member Functions
HtmlFormatter ()
Constructor.
void appendParagraph (QString _paragraph)
This fucntion adds a paragraph with the correspondent html tags.
void appendTable (QStringList _headerList, QList< QStringList > _rowContent)
This fucntion adds a table with the correspondent html tags.
void appendTitle (QString _title)
This fucntion adds a title (header 1) with the correspondent html tags.
void appendTitleParagraph (QString _title)
This fucntion adds a paragraph (header 2, image, title) with the correspondent html tags.
void endFormatting ()
This fucntion adds a the footer of the html document.
QString getFormatedText ()
This function returns the Html formated text.
void startFormatting ()
Destructor.
Private Member Functions
QString getFooter ()
This fucntion gets the Html footer.
QString getHeader ()
This fucntion gets the Html header.
Private Attributes
QString _formattedText
Detailed Description
Definition at line 8 of file htmlformatter.h.
Constructor & Destructor Documentation
HtmlFormatter::HtmlFormatter ()
Constructor.
Definition at line 23 of file htmlformatter.cpp.
References _formattedText.
 {
     _formattedText ="";
 }
Member Function Documentation
void HtmlFormatter::appendParagraph (QString _paragraph)
This fucntion adds a paragraph with the correspondent html tags.
Parameters
_paragraph
Definition at line 75 of file htmlformatter.cpp.
References _formattedText.
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText +=  "<p> ";
     _formattedText += _paragraph;
     _formattedText += "</p> ";
 }
void HtmlFormatter::appendTable (QStringList _headerList, QList< QStringList > _rowContent)
This fucntion adds a table with the correspondent html tags.
Parameters
_headerList
_rowContent
Definition at line 136 of file htmlformatter.cpp.
References _formattedText.
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText += "<p><table border=1>";
     // Setting the header
     if (!_headerList.isEmpty())
     {
         _formattedText += "<tr>";
         for (int j = 0; j < _headerList.count();j++)
         {
             _formattedText += "<th>";
             _formattedText += _headerList.at(j);
             _formattedText += "</th>";
         }
         _formattedText += "</tr>";
     }
     // Setting Row Contents
     if (!_rowContent.isEmpty())
     {
         for (int i = 0; i < _rowContent.count(); i++)
         {
             QStringList _row = _rowContent.at(i);
             if (!_row.isEmpty())
             {
                 _formattedText += "<tr>";
                  for (int k = 0; k<_row.count();k++)
                  {
                      _formattedText += "<td>";
                      _formattedText += _row.at(k);
                      _formattedText += "</td>";
                  }
                  _formattedText += "</tr>";
             }
         }
     }
     _formattedText += "</table></p>";
 }
void HtmlFormatter::appendTitle (QString _title)
This fucntion adds a title (header 1) with the correspondent html tags.
Parameters
_title
Definition at line 45 of file htmlformatter.cpp.
References _formattedText.
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText += "<h1>";
     _formattedText +=  "<span style= \" color:#000080; \"> ";
     _formattedText += _title    ;
     _formattedText += "</span> ";
     _formattedText += "</h1>";
 }
void HtmlFormatter::appendTitleParagraph (QString _title)
This fucntion adds a paragraph (header 2, image, title) with the correspondent html tags.
Parameters
_title
Definition at line 59 of file htmlformatter.cpp.
References _formattedText.
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText += "<h2>";
     _formattedText += "<img src=\":/helpicons/images/bullet_blue.png\" />";
     _formattedText +=  "<span style= \" color:#000080; \"> ";
     _formattedText += _title    ;
     _formattedText += "</span> ";
     _formattedText += "</h2>";
 }
void HtmlFormatter::endFormatting ()
This fucntion adds a the footer of the html document.
Definition at line 86 of file htmlformatter.cpp.
References _formattedText, and getFooter().
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText += getFooter();
 }
QString HtmlFormatter::getFooter () private
This fucntion gets the Html footer.
Returns
QString
Definition at line 122 of file htmlformatter.cpp.
Referenced by endFormatting().
 {
     QString _footerText;
     _footerText +=  "</body></html>";
     return _footerText;
 }
QString HtmlFormatter::getFormatedText ()
This function returns the Html formated text.
Returns
QString
Definition at line 96 of file htmlformatter.cpp.
References _formattedText.
Referenced by SolverVariableVO::getHelpContents().
 {
     return _formattedText;
 }
QString HtmlFormatter::getHeader () private
This fucntion gets the Html header.
Returns
QString
Definition at line 107 of file htmlformatter.cpp.
Referenced by startFormatting().
 {
     QString _headerText;
     _headerText = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\"><html>";
     _headerText += "<head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">";
     _headerText += "p, li { white-space: pre-wrap; } </style></head>";
     _headerText += "<body> ";
     return _headerText;
 }
void HtmlFormatter::startFormatting ()
Destructor.
Definition at line 33 of file htmlformatter.cpp.
References _formattedText, and getHeader().
Referenced by SolverVariableVO::getHelpContents().
 {
     _formattedText += getHeader();
 }
Member Data Documentation
QString HtmlFormatter::_formattedText private
Definition at line 26 of file htmlformatter.h.
Referenced by appendParagraph(), appendTable(), appendTitle(), appendTitleParagraph(), endFormatting(), getFormatedText(), HtmlFormatter(), and startFormatting().
The documentation for this class was generated from the following files:
Html/htmlformatter.h
Html/htmlformatter.cpp