BBIPED Platform: QtableUtil Class Reference
QtableUtil Class Reference
#include <qtableutil.h>
Public Member Functions
QtableUtil ()
QTableWidgetItem * addChangedColumn ()
Function that creates check widget cell to the table.
QTableWidgetItem * addChangedColumn (bool _isSelectable)
QListWidget * addCheckBox (QStringList _list, QString _defaultValue)
QListWidget * addCheckBox (QStringList _list, QString _defaultValue, bool _isSelectable)
QComboBox * addCombo (QStringList _list, QList< bool > _selectableList)
QComboBox * addCombo (QStringList _list, QList< bool > _selectableList, bool _isSelectable)
Function that creates combo widget cell to the table.
void addDoubleValidator (QLineEdit *_editTxt)
This function adds a validator to control the user input in double type fields.
QTableWidgetItem * addEditIcon ()
Function that creates a script edit icon widget cell element to be added to the table.
QLineEdit * addEditText (QString _value)
Function that creates edit default text cell to the table.
QLineEdit * addEditText (QString _value, bool _isSelectable)
QTableWidgetItem * addEditText2 (QString _value)
Function that creates edit default text cell to the table.
QTableWidgetItem * addIcon (bool _isSelectable)
Function that creates a help icon widget cell element to be added to the table.
QTableWidgetItem * addIcon ()
QLabel * addIcon (int _idIcon)
Fucntion to add a icon according the _idICon(0:Help, 1:Edit, 2:Import, 3:Delete,4:Add)
QTableWidgetItem * addNonEditableText (QString _value)
Function that creates non edit default text cell to the table.
QTableWidgetItem * addNonEditableText (QString _value, bool _isSelectable)
QTableWidgetItem * addSelectableCheckColumn ()
QTableWidgetItem * addVariable (QString _variableName)
QTableWidgetItem * addVariable (QString _variableName, bool _isSelectable)
Function that creates variable widget cell to the table.
bool isInitialized ()
void registerTable (QTableWidget *_table)
void resetTable ()
Private Member Functions
void addColumns (int _nColumns)
Funciton that add new columns to an existent table.
void addRows (int _nRows)
Function that adds new rows into an existent table.
Private Attributes
bool _isInitialized
QTableWidget * _registeredTable
Detailed Description
Definition at line 15 of file qtableutil.h.
Constructor & Destructor Documentation
QtableUtil::QtableUtil ()
Definition at line 33 of file qtableutil.cpp.
 {
     _isInitialized = false;
 }
Member Function Documentation
QTableWidgetItem * QtableUtil::addChangedColumn ()
Function that creates check widget cell to the table.
Returns
QTableWidgetItem
Definition at line 189 of file qtableutil.cpp.
Referenced by SolverMarkerMenuHelper::addMarkerVariable(), VirtualRotatingDialog::addRow(), SpecificBoundaryVariableDialog::addRow(), SalomeTemplateDialog::addRow(), SalomeOptimizationDialog::addRow(), SolverConfigMenuHelper::addVariableToTable(), SolverBasicDialog::insertRowSpecific(), and SolverBasicDialog::insertRowSpecificWithoutIcons().
 {
     QTableWidgetItem * _checkStatusItem = new QTableWidgetItem("");
     _checkStatusItem->setFlags(_checkStatusItem->flags() &= ~(Qt::ItemIsEditable | Qt::ItemIsUserCheckable));
     _checkStatusItem->setCheckState(Qt::Unchecked);
     return _checkStatusItem;
 }
QTableWidgetItem * QtableUtil::addChangedColumn (bool _isSelectable)
Definition at line 197 of file qtableutil.cpp.
 {
     QTableWidgetItem * _checkStatusItem = new QTableWidgetItem("");
     if (!_isSelectable)
     {
         _checkStatusItem->setFlags(_checkStatusItem->flags() &= ~(Qt::ItemIsEditable | Qt::ItemIsUserCheckable| Qt::ItemIsEnabled));
         _checkStatusItem->setCheckState(Qt::Unchecked);
         return _checkStatusItem;
     }else
         return addChangedColumn();
 }
QListWidget * QtableUtil::addCheckBox (QStringList _list, QString _defaultValue)
Definition at line 310 of file qtableutil.cpp.
References COMMA_SEPARATOR.
Referenced by SolverConfigMenuHelper::addVariableToTable().
 {
     QListWidget* _listCombo = new QListWidget();
     QStringList _defaultValueList;
     if (!_defaultValue.isEmpty())
         _defaultValueList=_defaultValue.split(COMMA_SEPARATOR);
     for (int i = 0; i < _list.size();i++)
     {
         QString _itemName = _list.at(i);
         QListWidgetItem * _itemToAdd = new QListWidgetItem(_itemName,_listCombo);
         _itemToAdd->setFlags(_itemToAdd->flags() | Qt::ItemIsUserCheckable); // set checkable flag
         if (_defaultValue.contains(_itemName))
             _itemToAdd->setCheckState(Qt::Checked); // AND initialize check state
         else
             _itemToAdd->setCheckState(Qt::Unchecked); // AND initialize check state
     }
     //_listCombo->addItems(_list);
     _listCombo->setSelectionMode(QAbstractItemView::MultiSelection );
     return _listCombo;
 }
QListWidget * QtableUtil::addCheckBox (QStringList _list, QString _defaultValue, bool _isSelectable)
Definition at line 297 of file qtableutil.cpp.
 {
     QListWidget* _listCombo = new QListWidget();
     if (!_isSelectable)
     {
         _listCombo->setEnabled(false);
         return _listCombo;
     }
     return( addCheckBox(_list,_defaultValue));
 }
void QtableUtil::addColumns (int _nColumns) private
Funciton that add new columns to an existent table.
Parameters
_nColumns
Definition at line 93 of file qtableutil.cpp.
 {
     for (int i = 0; i < _nColumns; i++)
         _registeredTable->insertColumn(i);
 }
QComboBox * QtableUtil::addCombo (QStringList _list, QList< bool > _selectableList)
Definition at line 263 of file qtableutil.cpp.
References XML_CUSTOMISED_TAG.
Referenced by SolverMarkerMenuHelper::addMarkerVariable(), SolverConfigMenuHelper::addVariableToTable(), WarningMultizoneDialog::buildRow(), and FileComparisonDialog::fillUserValueInCell().
 {
     QComboBox* _listCombo = new QComboBox();
     if (_list.contains(XML_CUSTOMISED_TAG))
     {
         _listCombo->setEditable(true);
         _listCombo->InsertAtBottom;
     }
     _listCombo->addItems(_list);
     // Changing the selectability
     // SOL: http://stackoverflow.com/questions/7632645/how-to-set-non-selectable-default-text-on-qcombobox
     // SOL color: http://stackoverflow.com/questions/3070450/qt-how-do-i-change-the-text-color-of-one-item-of-a-qcombobox-c
     QStandardItemModel* model =  qobject_cast<QStandardItemModel*>(_listCombo->model());
     for (int i=0; i < _selectableList.size(); i++)
     {
         bool _itemIsSelectable = _selectableList.at(i);
         if (!_itemIsSelectable)
         {
             QModelIndex firstIndex = model->index(i, _listCombo->modelColumn(), _listCombo->rootModelIndex());
             QStandardItem* _item = model->itemFromIndex(firstIndex);
             _item->setSelectable(false);
             _listCombo->setItemData(i, Qt::gray, Qt::TextColorRole);
         }
       }
     return _listCombo;
 }
QComboBox * QtableUtil::addCombo (QStringList _list, QList< bool > _selectableList, bool _isSelectable)
Function that creates combo widget cell to the table.
Parameters
_list
Returns
QComboBox
Definition at line 251 of file qtableutil.cpp.
 {
     QComboBox* _listCombo = new QComboBox();
     if (!_isSelectable)
     {
         _listCombo->setEditable(false);
         _listCombo->setEnabled(false);
         return _listCombo;
     }
     return( addCombo(_list,_selectableList ));
 }
void QtableUtil::addDoubleValidator (QLineEdit * _editTxt)
This function adds a validator to control the user input in double type fields.
Parameters
_editTxt
Definition at line 386 of file qtableutil.cpp.
 {
     QDoubleValidator * _validator = new QDoubleValidator(_editTxt);
     _validator->setNotation(QDoubleValidator::ScientificNotation);
     _editTxt->setValidator(_validator);
 }
QTableWidgetItem * QtableUtil::addEditIcon ()
Function that creates a script edit icon widget cell element to be added to the table.
Returns
QTableWidgetItem
Definition at line 175 of file qtableutil.cpp.
Referenced by SolverMarkerMenuHelper::addEditIconToColumn().
 {
     QIcon icon(":/solverIcons/images/script_edit.png");
     QTableWidgetItem *icon_item = new QTableWidgetItem;
     icon_item->setIcon(icon);
     icon_item->setFlags(Qt::ItemIsSelectable | Qt::ItemIsEnabled);
     return icon_item;
 }
QLineEdit * QtableUtil::addEditText (QString _value)
Function that creates edit default text cell to the table.
Parameters
_value
Returns
QLineEdit
Definition at line 353 of file qtableutil.cpp.
Referenced by VirtualCurveDialog::addRow(), VirtualRotatingDialog::addRow(), SpecificBoundaryVariableDialog::addRow(), SalomeTemplateDialog::addRow(), SolverConfigMenuHelper::addVariableToTable(), SalomeOptimizationDialog::addvarToSelectedTable(), ClipDomainDialog::fillTable(), and FileComparisonDialog::fillUserValueInCell().
 {
      QLineEdit * _defaultTxt = new QLineEdit(_value);
      // Setting the validator
      bool isDouble;
      double _doubleVal = _value.toDouble(&isDouble);
      if (isDouble)
      {
          addDoubleValidator(_defaultTxt);
      }
      return _defaultTxt;
 }
QLineEdit * QtableUtil::addEditText (QString _value, bool _isSelectable)
Definition at line 367 of file qtableutil.cpp.
 {
      QLineEdit * _defaultTxt = new QLineEdit(_value);
      if (!_isSelectable)
      {
          _defaultTxt->setEnabled(false);
          return _defaultTxt;
      }
      else
         return (addEditText(_value));
 }
QTableWidgetItem * QtableUtil::addEditText2 (QString _value)
Function that creates edit default text cell to the table.
Parameters
_value
Returns
QTableWidgetItem
Definition at line 341 of file qtableutil.cpp.
Referenced by SolverMarkerMenuHelper::addMarkerVariable(), SolverConfigMenuHelper::addVariableToTable(), and FileComparisonDialog::fillUserValueInCell().
 {
      QTableWidgetItem * _defaultTxt = new QTableWidgetItem(_value);
      return _defaultTxt;
 }
QTableWidgetItem * QtableUtil::addIcon (bool _isSelectable)
Function that creates a help icon widget cell element to be added to the table.
Returns
QTableWidgetItem
Definition at line 105 of file qtableutil.cpp.
Referenced by SolverMarkerMenuHelper::addMarkerVariable(), VirtualRotatingDialog::addRow(), ProjectSettingsDialog::addRowToTable(), SolverConfigMenuHelper::addVariableToTable(), TemplateDialog::addVariableToTable(), MultizoneProjectDialog::createConfigurationRow(), MultizoneProjectDialog::createMeshFileRow(), SolverBasicDialog::insertRowSpecific(), SolverBasicDialog::launchSpecificWindow(), and SolverBasicDialog::updateTableHeaderSpecific().
 {
     QIcon icon(":/solverIcons/images/help.png");
     QTableWidgetItem *icon_item = new QTableWidgetItem;
     icon_item->setIcon(icon);
     if (_isSelectable)
         icon_item->setFlags(Qt::ItemIsSelectable | Qt::ItemIsEnabled);
     else
     {
         icon_item->setFlags(icon_item->flags() &= ~Qt::ItemIsEditable);
         icon_item->setFlags(icon_item->flags() &= ~Qt::ItemIsEnabled);
     }
     return icon_item;
 }
QTableWidgetItem * QtableUtil::addIcon ()
Definition at line 123 of file qtableutil.cpp.
 {
     QIcon icon(":/solverIcons/images/help.png");
     QTableWidgetItem *icon_item = new QTableWidgetItem;
     icon_item->setIcon(icon);
     icon_item->setFlags(Qt::ItemIsSelectable | Qt::ItemIsEnabled);
     return icon_item;
 }
QLabel * QtableUtil::addIcon (int _idIcon)
Fucntion to add a icon according the _idICon(0:Help, 1:Edit, 2:Import, 3:Delete,4:Add)
Parameters
_idIcon
Returns
QLabel
Definition at line 141 of file qtableutil.cpp.
References IconAdd, IconDelete, IconEdit, IconHelp, and IconImport.
 {
     QPixmap icon;
     switch(_idIcon)
     {
     case IconHelp:
         icon.load(":/solverIcons/images/help.png");
         break;
     case IconEdit:
         icon.load(":/solverIcons/images/script_edit.png");
         break;
     case IconImport:
          icon.load(":/new/toolbarIcons/images/document_import.png");
         break;
     case IconDelete:
          icon.load(":/new/toolbarIcons/images/cross.png");
         break;
     case IconAdd:
          icon.load(":/new/toolbarIcons/images/add.png");
         break;
     }
     QLabel * _labelWithIcon = new QLabel;
     _labelWithIcon->setPixmap(icon);
     _labelWithIcon->setAlignment(Qt::AlignCenter);
     return _labelWithIcon;
 }
QTableWidgetItem * QtableUtil::addNonEditableText (QString _value)
Function that creates non edit default text cell to the table.
Parameters
_value
Returns
QTableWidgetItem
Definition at line 400 of file qtableutil.cpp.
Referenced by SolverMarkerMenuHelper::addExtraColumn(), SolverMarkerMenuHelper::addMarkerVariable(), VirtualCurveDialog::addRow(), VirtualRotatingDialog::addRow(), SpecificBoundaryVariableDialog::addRow(), SalomeTemplateDialog::addRow(), SalomeOptimizationDialog::addRow(), ProjectSettingsDialog::addRowToTable(), SolverConfigMenuHelper::addVariableToTable(), SalomeOptimizationDialog::addvarToSelectedTable(), WarningMultizoneDialog::buildRow(), MultizoneProjectDialog::createConfigurationRow(), MultizoneProjectDialog::createMeshFileRow(), MultizoneSummaryDialog::fillConfigTable(), FileComparisonDialog::fillRowWithData(), ClipDomainDialog::fillTable(), FileComparisonDialog::insertHeaderTitles(), MainWindow::insertMultizoneRow(), MultizoneSummaryDialog::insertRow(), SolverBasicDialog::insertRowSpecific(), SolverBasicDialog::insertRowSpecificWithoutIcons(), and FileComparisonDialog::updateTableHeader().
 {
     QTableWidgetItem * _defaultTxt = new QTableWidgetItem(_value);
     _defaultTxt->setFlags(_defaultTxt->flags() &= ~Qt::ItemIsEditable);
     return _defaultTxt;
 }
QTableWidgetItem * QtableUtil::addNonEditableText (QString _value, bool _isSelectable)
Definition at line 408 of file qtableutil.cpp.
 {
     QTableWidgetItem * _defaultTxt = new QTableWidgetItem(_value);
     _defaultTxt->setFlags(_defaultTxt->flags() &= ~Qt::ItemIsEditable);
     if (!_isSelectable)
          _defaultTxt->setFlags(_defaultTxt->flags() &= ~Qt::ItemIsEnabled);
     return _defaultTxt;
 }
void QtableUtil::addRows (int _nRows) private
Function that adds new rows into an existent table.
Parameters
_nRows
Definition at line 82 of file qtableutil.cpp.
 {
     for (int i = 0; i < _nRows; i++)
         _registeredTable->insertRow(i);
 }
QTableWidgetItem * QtableUtil::addSelectableCheckColumn ()
Definition at line 209 of file qtableutil.cpp.
Referenced by SalomeOptimizationDialog::addRow(), TemplateDialog::addVariableToTable(), MultizoneSummaryDialog::fillConfigTable(), and MainWindow::insertMultizoneRow().
 {
     QTableWidgetItem * _checkStatusItem = new QTableWidgetItem("");
     //_checkStatusItem->setFlags(_checkStatusItem->flags() &= ~(Qt::ItemIsEditable | Qt::ItemIsUserCheckable));
     _checkStatusItem->setCheckState(Qt::Unchecked);
     return _checkStatusItem;
 }
QTableWidgetItem * QtableUtil::addVariable (QString _variableName)
Definition at line 234 of file qtableutil.cpp.
Referenced by SolverConfigMenuHelper::addVariableToTable(), and TemplateDialog::addVariableToTable().
 {
     QTableWidgetItem * _varTextItem = new QTableWidgetItem();
     _varTextItem->setFlags(_varTextItem->flags() &= ~Qt::ItemIsEditable);
     _varTextItem->setText(_variableName);
     return _varTextItem;
 }
QTableWidgetItem * QtableUtil::addVariable (QString _variableName, bool _isSelectable)
Function that creates variable widget cell to the table.
Parameters
_variableName
Returns
QTableWidgetItem
Definition at line 223 of file qtableutil.cpp.
 {
     QTableWidgetItem * _varTextItem = new QTableWidgetItem();
     _varTextItem->setFlags(_varTextItem->flags() &= ~Qt::ItemIsEditable);
     if (!_isSelectable)
         _varTextItem->setFlags(_varTextItem->flags() &= ~Qt::ItemIsEnabled);
     _varTextItem->setText(_variableName);
     return _varTextItem;
 }
bool QtableUtil::isInitialized ()
Definition at line 429 of file qtableutil.cpp.
Referenced by SalomeTemplateDialog::on_deleteTemplateButton_clicked(), SalomeOptimizationDialog::on_templateComboBox_currentIndexChanged(), and SalomeTemplateDialog::on_templateSelComboBox_currentIndexChanged().
 {
     return _isInitialized;
 }
void QtableUtil::registerTable (QTableWidget * _table)
Definition at line 38 of file qtableutil.cpp.
Referenced by SalomeTemplateDialog::registerHelpers(), and SalomeOptimizationDialog::registerHelpers().
 {
    _registeredTable = _table;
    _isInitialized = true;
 }
void QtableUtil::resetTable ()
Definition at line 418 of file qtableutil.cpp.
Referenced by SalomeTemplateDialog::on_deleteTemplateButton_clicked(), SalomeOptimizationDialog::on_templateComboBox_currentIndexChanged(), and SalomeTemplateDialog::on_templateSelComboBox_currentIndexChanged().
 {
     if (_registeredTable->rowCount() > 0)
     {
         //  Delete all rows
         int _totalRows = _registeredTable->rowCount();
         for (int i = _totalRows; i >= 0; i--)
             _registeredTable->removeRow(i);
     }
 }
Member Data Documentation
bool QtableUtil::_isInitialized private
Definition at line 55 of file qtableutil.h.
QTableWidget* QtableUtil::_registeredTable private
Definition at line 54 of file qtableutil.h.
The documentation for this class was generated from the following files:
Utility/qtableutil.h
Utility/qtableutil.cpp