BBIPED Platform: JobManager Namespace Reference
JobManager Namespace Reference
Classes
class Write_No_Multizone
Functions
def Compute_BB
def Compute_Mesh
def CopyMesh
def EXPORTMesh
def ModifyCfg
def ModifyMeshTemplate
def ParseCfg
def Report
Variables
string _AutomatizationPath = "/home/BCAMATH/calonso/ToolDevelopment/workspace/CFD_REPO/build/debug/.tools/Automatization/"
string _BBipedExecPath = "./BBipedxSU2"
float _meshScaleFactor = 0.001
string _salomePath = "/home/BCAMATH/calonso/salome/appli_V7_2_0/runSalomeScript"
Function Documentation
def JobManager.Compute_BB (ConfigFile)
Simply runs the executable by command call([_BBipedExecPath, _cfgToCompute])
Definition at line 112 of file JobManager.py.
 def Compute_BB(ConfigFile):
  """ Simply runs the executable by command call([_BBipedExecPath, _cfgToCompute]) """
  _cfgToCompute=ConfigFile
  print "\n\nJobManager > Comput_BB"
  try:
   pro=call([_BBipedExecPath, _cfgToCompute])
  except IOError:
   raise RuntimeError, "check path _BBipedExecPath: %s is correct in JobManager" % (_BBipedExecPath,)
   raise RuntimeError, "check path _cfgToCompute: %s is correct in JobManager" % (_cfgToCompute,)
def JobManager.Compute_Mesh (CallerPath, TemplateFile, argv)
In this function we create the SU2 mesh as .case_mesh.py in the callers path. We first modify the mesh template for our needs Using "TemplateFile_Calculations". Then we compute the mesh which will always be called AutomaticMesh.su2 (Name is actually given in JobManager.EXPORTMesh function)
Definition at line 26 of file JobManager.py.
References ModifyMeshTemplate().
 def Compute_Mesh(CallerPath,TemplateFile, *argv):
  """ In this function we create the SU2 mesh as .case_mesh.py in the callers path. We first modify the mesh template for our needs Using "TemplateFile_Calculations". Then we compute the mesh which will always be called AutomaticMesh.su2 (Name is actually given in JobManager.EXPORTMesh function)"""
  VariablesToComp = argv
  print "\n\nJobManager > ComputingMesh"
  print "Compute Mesh for Template File: %s" % (TemplateFile,)
  print "Local working directory: %s" % (CallerPath,)
  ModifyMeshTemplate(CallerPath,TemplateFile,VariablesToComp) # Modifies template and writes .case_mesh.py in callers path
  _MeshToCompute = CallerPath+"/case_mesh.py" # writes out the case dump script which salome will read
  print "Imanol : _salomePath",_salomePath
  print "Imanol : _MeshToCompute",_MeshToCompute
  try:
   pro=call([_salomePath, _MeshToCompute]) # return mesh called AutomaticMesh.su2
  except IOError:
   raise RuntimeError, "check path _salomePath: %s is correct in JobManager" % (_salomePath,)
   raise RuntimeError, "check path _MeshToCompute: %s is correct in JobManager" % (_MeshToCompute,)
def JobManager.CopyMesh (CallerPath, newMeshName)
Optionall function that copies the automatically created mesh to a unique name, in order to save it
Definition at line 226 of file JobManager.py.
 def CopyMesh(CallerPath,newMeshName):
  """ Optionall function that copies the automatically created mesh to a unique name, in order to save it """
  MeshPath = CallerPath + "/AutomaticMesh.su2"
  shutil.copyfile(MeshPath,CallerPath+"/"+newMeshName)
 #def CopyCfgFile(CallerPath,OldCfgFilePath,newMeshName):   ##### BORRAR
 # shutil.copyfile(OldCfgFilePath,CallerPath+"/"+newMeshName)
def JobManager.EXPORTMesh (Multizone, dirname, AutomaticMesh, SMESH, SALOMEDS, smeshBuilder, smesh)
Export mesh exports salome mesh into SU2 (and if manually uncomented in this function, also to STL mesh). It is called directly from the case_mesh.py. It currently doesn't support Multizone.
Definition at line 235 of file JobManager.py.
 def EXPORTMesh(Multizone, dirname, AutomaticMesh, SMESH, SALOMEDS, smeshBuilder, smesh): # Multizone = true or false
  """ Export mesh exports salome mesh into SU2 (and if manually uncomented in this function, also to STL mesh). It is called directly from the case_mesh.py. It currently doesn't support Multizone. """
  globMultiZoneActive = Multizone # THERE IS NO TK IN THIS VERISION!! # From tk we will change to true if we click on MultiZone export
 # VARIABLE DEFINITIONS
  globMesh = [] #global Mesh list variable, if the value is 1 it means we selected to export the corresponding mesh
  # i/o definitions
  old_stdout=sys.stdout # We copy Salome stdout to return from file write to console output
 #def PrintToConsole(old_stdout):
 # stdout.close()
 # sys.stdout = old_stdout
 #if globMesh[MeshIter]==1: # If we checked we want to export this mesh
  OutMeshName = dirname + "/" + "AutomaticMesh" # we extend the path to the main directory. We will turn this to file or folder depending if we export mesh or submeshes
  FilePath = OutMeshName + ".su2" # Set the path with file .su2 extension
  wrt=Write_No_Multizone(AutomaticMesh,FilePath, SMESH, SALOMEDS, smeshBuilder, smesh)
  sys.stdout = old_stdout  # We return the stdout to the salome console
  # AutomaticMesh.ExportSTL(dirname +"/TUIMesh.stl") #
 #                  ********************************                                   \
 #                  *         Export Mesh
 #                  ********************************                                   \
 #                                                                                     \
 #vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv\
 #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
 #                                                                                     \
 #                        *********************************                            \
 #                        *        Export Mesh
 #                        *********************************                            \
def JobManager.ModifyCfg (CurrentPath, old_Configuration_File, new_Config_File, argv)
When called reads a provided configuration file, and rewrites it changing the options provided by user: structure has to be ModifyCfg(CurrentPath,old_Configuration_File,new_Config_File, par1, par1_value, par2, par2_value,...)
Definition at line 86 of file JobManager.py.
References ParseCfg().
 def ModifyCfg(CurrentPath,old_Configuration_File,new_Config_File,*argv):
  """ When called reads a provided configuration file, and rewrites it changing the options provided by user: structure has to be ModifyCfg(CurrentPath,old_Configuration_File,new_Config_File, par1, par1_value, par2, par2_value,...) """
  VariablesToModify = ParseCfg(argv)  # Creates a dictionary by the user provided Markers and values.
  VariablesToModify_str=VariablesToModify.keys()
  fout= open(CurrentPath+'/'+new_Config_File, 'w')
  with open(old_Configuration_File) as _OldConfigFile:
   for line in _OldConfigFile:
    _break = 0
    for keyword in VariablesToModify_str:
     if keyword in line:
      _strToWrite = "%s%s\n" % (keyword, VariablesToModify[keyword])
      fout.write(_strToWrite)
      _break=1
    if _break == 0:
     fout.write(line)
  fout.close()
def JobManager.ModifyMeshTemplate (CallerPath, TemplateFile, VariablesToChangeFromTemplate)
Computes the ..._Calculations.py and copies the TemplateFile into the Caller working directory, substituting template default values by the optionals set by the user call ModifyMeshTemplate(CallerPath,TemplateFile,VariablesToChangeFromTemplate). VariablesToChangeFromTemplate has to be of the structure ModifyMeshTemplate(CallerPath,TemplateFile, par1, par1_value, par2, par2_value,...)
Definition at line 44 of file JobManager.py.
Referenced by Compute_Mesh().
 def ModifyMeshTemplate(CallerPath,TemplateFile,VariablesToChangeFromTemplate):
  """ Computes the ..._Calculations.py and copies the TemplateFile into the Caller working directory, substituting template default values by the optionals set by the user call ModifyMeshTemplate(CallerPath,TemplateFile,VariablesToChangeFromTemplate). VariablesToChangeFromTemplate has to be of the structure ModifyMeshTemplate(CallerPath,TemplateFile, par1, par1_value, par2, par2_value,...) """
  _template_Geometry_Modifier=_AutomatizationPath+"templates/"+TemplateFile+"/"+TemplateFile+"_Calculations.py"
  print "\n\nJob Manager > ModifyMeshTemplate"
  _template_fullpath=_AutomatizationPath+"templates/"+TemplateFile+"/"+TemplateFile+".py"
  try:
   _template_calc = imp.load_source('_foo', _template_Geometry_Modifier) # The precious lines defines the template _Calculation file and lods it in _template_calc
  except IOError:
   raise RuntimeError, "check path _template_Geometry_Modifier exists (maybe template doesn't exist?): %s " % (_template_Geometry_Modifier,)
  GeometryVariablesToComp=_template_calc.UserValues(VariablesToChangeFromTemplate) # Loads _Calculation default values, and if there is any new value from the Task_to_perform call, it sets it to the case. Returns a dictionary of all the variables and values. It will pass the key parameter and the value: If we want to pass 3 new geometry values, there will be 6 parameters in the function (key1, value1, key 2...)
  SalomeVariablesToComp=_template_calc.ComputeGeometry(GeometryVariablesToComp)
  SalomeVariablesToComp_str=SalomeVariablesToComp.keys()
  fout= open(CallerPath+'/case_mesh.py', 'w') # Next loop reads the salome template file, and copies it to the case_mesh.py file. But writes out the SalomeVariablesToComp dictionary values in notebook, instead of template ones.
  with open(_template_fullpath) as _template:
   for line in _template:
    _break = 0
    for keyword in SalomeVariablesToComp_str:
     key_temp = 'notebook.set("%s"'% keyword
     if key_temp in line: # write here all geometry modifications
      if key_temp not in 'notebook.set("Blade_Number"':
       _strToWrite = 'notebook.set("%s", %f)\n' % (keyword, SalomeVariablesToComp[keyword])
       fout.write(_strToWrite)
      else:
       _strToWrite = 'notebook.set("%s", %i)\n' % (keyword, SalomeVariablesToComp[keyword])
       fout.write(_strToWrite)
      _break = 1
    if _break == 0:
     if "this line is where BB mesh will be exported" in line:
      _foo=str("dirname = '" + CallerPath + "'\n")
      fout.write(_foo)
     else:
      fout.write(line)
  fout.close()
def JobManager.ParseCfg (arguments)
Definition at line 105 of file JobManager.py.
Referenced by ModifyCfg().
 def ParseCfg(arguments):
  MarkersDict = dict()
  for _iter in range(len(arguments)/2):
   _iter = _iter * 2
   MarkersDict[arguments[_iter]]=arguments[_iter+1]
  return MarkersDict
def JobManager.Report (ReportName, ConfigFileID, CallerPath, argv)
It reads the history of ConfigFileID CONV_FILENAME file, which. For the user given variables in the (Report call), creates a column based report of those values. Its line represents an independent simulations. I still didn't add the Report Header line to identify the variable reported. However, this matches with the user call variables.'
Definition at line 124 of file JobManager.py.
 def Report(ReportName, ConfigFileID,CallerPath,*argv):
  """ It reads the history of ConfigFileID CONV_FILENAME file, which. For the user given variables in the (Report call), creates a column based report of those values. Its line represents an independent simulations. I still didn't add the Report Header line to identify the variable reported. However, this matches with the user call variables.'"""
  #### HERE WE CHECK THE HISTORY FILE NAME FOR A CONFIG FILE, OPEN IT AND SEARCH FOR THE INDICATED VARIABLES
  _newconf = CallerPath+"/"+ConfigFileID
  try:
   with open(_newconf) as NewConfigName:
    for _line in NewConfigName:
     #if len(_line)<4:
     # _line=""
     # continue
     _parsed = _line.split("=")
     _parsed[0] = _parsed[0].translate(None,' ') # remove strange characters
     if _parsed[0] == "CONV_FILENAME": # % Output file convergence history (w/o extension) in configuration file
      HistoryFileName = _parsed[1].replace(".csv","")
      #HistoryFileName = _parsed[1].replace(".cfg","")
      HistoryFileName = HistoryFileName.replace("\n","")
      HistoryFileName = HistoryFileName.replace("\r","")
      if HistoryFileName[0:1] == " ":
       HistoryFileName = HistoryFileName [1:]
      HistoryFileName = HistoryFileName+".csv"
      print "history file, %s" % (HistoryFileName,)
      break
    NewConfigName.close()
  except IOError:
   raise RuntimeError, "check path _newconf: %s is correct in JobManager" % (_newconf,)
  _HistoryCall = CallerPath + "/"+ HistoryFileName
  try:
   with open(_HistoryCall) as History:
    _line = History.readline() # We read first line (variable headers) and We split it in an array
    _line = _line.split(",") #
    _ReportIndexPointer=dict() # This dictionary will point for the user asked variables the entry index in the previously created array.
    __ReportDict=dict() # Initialize dictionary for variables values.
    for _var in argv: # For each variable reported by user, we find the index and store it in dictionary
     _var=str(_var)
     try:
      _ReportIndexPointer['"'+_var+'"'] = _line.index('"'+_var+'"')
     except ValueError:
      pass
    for _line in History:
     _line = _line.split(",")
     for _key, _value in _ReportIndexPointer.iteritems(): # For each variable reported by user, we find the value and store it in dictionary at each history line. When last line is arrived, the bucle stops and the values of the dictionary will be last history line values
      __ReportDict[_key] = _line[_value]
  except IOError:
   raise RuntimeError, "check path _HistoryCall: %s is correct in JobManager" % (_HistoryCall,)
  #### HERE WE CHECK THE FILE NAMED Efficiency.csv, OPEN IT AND SEARCH FOR THE INDICATED VARIABLES
  _HistoryCall = "Efficiency.csv"
  try:
   with open(_HistoryCall) as History:
    _line = History.readline() # We read first line (variable headers) and We split it in an array
    _line = _line.split(",") #
    _ReportIndexPointerEff=dict() # This dictionary will point for the user asked variables the entry index in the previously created array.
    _ReportDictEff=dict() # Initialize dictionary for variables values.
    for _var in argv: # For each variable reported by user, we find the index and store it in dictionary
     _var=str(_var)
     try:
      _ReportIndexPointerEff[_var] = _line.index(_var)
     except ValueError:
      pass
    for _line in History:
     _line = _line.split(",")
     for _key, _value in _ReportIndexPointerEff.iteritems(): # For each variable reported by user, we find the value and store it in dictionary at each history line. When last line is arrived, the bucle stops and the values of the dictionary will be last history line values
      _ReportDictEff[_key] = _line[_value]
  except IOError:
   pass
  ### MERGE BOTH DICTIONARIES IN __ReportDict ####
  for _key, _value in _ReportDictEff.iteritems():
   __ReportDict[_key] = _ReportDictEff[_key] # Copy dictionary
  ### HERE STARTS THE WRITE OUT OF REPORT FILE ####
  _textTobeWriten = ConfigFileID # Name of the simulated configuration file will be writen in first column. helps to identify the line in the report with a simulation
  for _key, _value in __ReportDict.iteritems():
   _textTobeWriten = _textTobeWriten + "  ," + str(_value)  # Write out the variables values
  _textTobeWriten = _textTobeWriten.replace("\n","")
  existRep = os.path.isfile(ReportName)
  if existRep == False:
   with open(ReportName, "a") as myfile: # Append title
    mystr = "config file name, "
    for _key, _value in __ReportDict.iteritems():
     mystr = mystr + str(_key) + "  ,  "
    mystr = mystr[:-4]
    myfile.write(mystr)
    myfile.write("\n")
  with open(ReportName, "a") as myfile: # Append a jump of line
    myfile.write(_textTobeWriten)
    myfile.write("\n")
Variable Documentation
string JobManager._AutomatizationPath = "/home/BCAMATH/calonso/ToolDevelopment/workspace/CFD_REPO/build/debug/.tools/Automatization/"
Definition at line 18 of file JobManager.py.
string JobManager._BBipedExecPath = "./BBipedxSU2"
Definition at line 15 of file JobManager.py.
float JobManager._meshScaleFactor = 0.001
Definition at line 23 of file JobManager.py.
string JobManager._salomePath = "/home/BCAMATH/calonso/salome/appli_V7_2_0/runSalomeScript"
Definition at line 11 of file JobManager.py.
Referenced by SalomeTemplateDialog.setMeshViewerPath().