BBIPED Platform: SolverPlotter Class Reference
SolverPlotter Class Reference
#include <solverplotter.h>
Public Types
enum ResidualData
Public Member Functions
SolverPlotter (QWidget *=0)
Constructor.
void clearCanvas ()
Function to clear the current Canvas.
void exportPlot ()
const QwtPlotCurve * plotterCurve (int id) const
void resetLegend (SolverResidualVO *_obj)
void showPoints (SolverResidualVO *_obj)
Function that shows the points of the read curve.
void updateLegendItemsInGraphic (SolverResidualVO *_obj)
Private Slots
void showCurve (QwtPlotItem *, bool on)
Function to show the curve.
Private Member Functions
QString getCurveName (int _id)
Function that gets the curve names.
void initCurves ()
Function that inits the curves.
void resetAllPointValues (int _iteration)
Function to reset all the points.
void setAxisLayout ()
Function that sets up the Axis Layout.
void setColor (PlotterCurve *_curve, int _id)
Function that sets the color.
void setReadOnlyLegend (QwtLegend *legend, QwtPlotItem *item, bool on)
void showCurves ()
Function to show the curves.
void updateValues (PlotterCurve *curve, int id)
Function that updates the values of the curve.
Private Attributes
struct {
QPolygonF _points
QwtPlotCurve * curve
} data [NResidualData]
int dataCount
double timeData [HISTORY]
Detailed Description
Definition at line 14 of file solverplotter.h.
Member Enumeration Documentation
enum SolverPlotter::ResidualData
Enumerator
resRho
resRhoe
NResidualData
Definition at line 18 of file solverplotter.h.
     {
 //        TimeSim,
         resRho,
         resRhoe,
 //        cliftTotal,
 //        cDragTotal,
         NResidualData
     };
Constructor & Destructor Documentation
SolverPlotter::SolverPlotter (QWidget * parent = 0)
Constructor.
Parameters
parent
Definition at line 54 of file solverplotter.cpp.
References initCurves(), setAxisLayout(), showCurve(), and showCurves().
                                             :
     QwtPlot(parent),
   dataCount( 0 )
 {
     setAutoReplot( true );
     canvas()->setBorderRadius( 10 );
     setCanvasBackground(Qt::white);
     plotLayout()->setAlignCanvasToScales(true);
     QwtLegend *legend = new QwtLegend;
     legend->setItemMode(QwtLegend::CheckableItem);
     this->insertLegend(legend, QwtPlot::RightLegend);
     setAxisLayout();
     initCurves();
     showCurves();
     connect(this, SIGNAL(legendChecked(QwtPlotItem *, bool)),
          SLOT(showCurve(QwtPlotItem *, bool)));
 }
Member Function Documentation
void SolverPlotter::clearCanvas ()
Function to clear the current Canvas.
Definition at line 77 of file solverplotter.cpp.
References _points, data, resRho, resRhoe, and showCurves().
Referenced by MainWindow::closeProject(), MainWindow::on_restartButton_clicked(), and MainWindow::runSolverProject().
 {
  /*    data[TimeSim]._points.clear();
      data[TimeSim].curve->setSamples(data[TimeSim]._points);*/
      data[resRho]._points.clear();
      data[resRho].curve->setSamples(data[resRho]._points);
      data[resRhoe]._points.clear();
      data[resRhoe].curve->setSamples(data[resRhoe]._points);
  /*    data[cliftTotal]._points.clear();
      data[cliftTotal].curve->setSamples(data[cliftTotal]._points);
      data[cDragTotal]._points.clear();
      data[cDragTotal].curve->setSamples(data[cDragTotal]._points);*/
      showCurves();
      replot();
 }
void SolverPlotter::exportPlot ()
Definition at line 317 of file solverplotter.cpp.
Referenced by MainWindow::on_actionSave_Residual_Image_triggered().
 {
 #ifndef QT_NO_PRINTER
     QString fileName = "image.pdf";
 #else
     QString fileName = "image.png";
 #endif
 #ifndef QT_NO_FILEDIALOG
     const QList<QByteArray> imageFormats =
         QImageWriter::supportedImageFormats();
     QStringList filter;
     filter += "PDF Documents (*.pdf)";
 #ifndef QWT_NO_SVG
     filter += "SVG Documents (*.svg)";
 #endif
     filter += "Postscript Documents (*.ps)";
     if ( imageFormats.size() > 0 )
     {
         QString imageFilter("Images (");
         for ( int i = 0; i < imageFormats.size(); i++ )
         {
             if ( i > 0 )
                 imageFilter += " ";
             imageFilter += "*.";
             imageFilter += imageFormats[i];
         }
         imageFilter += ")";
         filter += imageFilter;
     }
     fileName = QFileDialog::getSaveFileName(
         this, "Export File Name", fileName,
         filter.join(";;"), NULL, QFileDialog::DontConfirmOverwrite);
 #endif
     if ( !fileName.isEmpty() )
     {
         QwtPlotRenderer renderer;
         renderer.setDiscardFlag(QwtPlotRenderer::DiscardBackground, false);
         renderer.renderDocument(this, fileName, QSizeF(300, 200), 85);
     }
 }
QString SolverPlotter::getCurveName (int _id) private
Function that gets the curve names.
Parameters
_id
Returns
QString
Definition at line 122 of file solverplotter.cpp.
Referenced by initCurves().
 {
     switch(_id)
     {
        case 0:
          return "resRho";
          break;
     case 1:
          return "resRhoe";
          break;
     otherwise:
         return "";
     }
 }
void SolverPlotter::initCurves () private
Function that inits the curves.
Definition at line 181 of file solverplotter.cpp.
References curve, getCurveName(), setColor(), and updateValues().
Referenced by SolverPlotter().
 {
     PlotterCurve * curve;
     int _numCurves =2; // 5
     for (int i = 0; i < _numCurves; i++)
     {
         QString _nameCurve = getCurveName(i);
         curve = new PlotterCurve( _nameCurve);
         setColor(curve,i);
         curve->setStyle(QwtPlotCurve::Lines);
         curve->attach( this );
         updateValues(curve,i);
     }
 }
const QwtPlotCurve* SolverPlotter::plotterCurve (int id) const inline
Definition at line 30 of file solverplotter.h.
References data.
     {
         return data[id].curve;
     }
void SolverPlotter::resetAllPointValues (int _iteration) private
Function to reset all the points.
Parameters
_iteration
Definition at line 236 of file solverplotter.cpp.
References data, dataCount, HISTORY, resRho, and resRhoe.
 {
     data[resRho]._points.clear();
     data[resRhoe]._points.clear();
     setAxisScale( QwtPlot::xBottom, dataCount, dataCount + HISTORY );
     replot();
 }
void SolverPlotter::resetLegend (SolverResidualVO * _obj)
Parameters
_obj
Definition at line 284 of file solverplotter.cpp.
References curve, data, SolverResidualVO::getResRhoeEnabled(), SolverResidualVO::getResRhoEnabled(), resRho, and resRhoe.
Referenced by MainWindow::closeProject().
 {
     if (_obj->getResRhoEnabled())
         data[resRho].curve->setItemAttribute(QwtPlotItem::Legend,false);
     if (_obj->getResRhoeEnabled())
          data[resRhoe].curve->setItemAttribute(QwtPlotItem::Legend,false);
     replot();
      data[resRho].curve->setItemAttribute(QwtPlotItem::Legend,true);
     data[resRhoe].curve->setItemAttribute(QwtPlotItem::Legend,true);
      replot();
 }
void SolverPlotter::setAxisLayout () private
Function that sets up the Axis Layout.
Definition at line 97 of file solverplotter.cpp.
References HISTORY.
Referenced by SolverPlotter().
 {
     setAxisTitle( QwtPlot::xBottom, " Iteration No." );
     setAxisScale( QwtPlot::xBottom, 0, HISTORY );
     setAxisTitle( QwtPlot::yLeft, "Log(Residuals)" );
     setAxisScale( QwtPlot::yLeft, -50, 50 );
 }
void SolverPlotter::setColor (PlotterCurve * _curve, int _id) private
Function that sets the color.
Parameters
_curve
_id
Definition at line 143 of file solverplotter.cpp.
References PlotterCurve::setColor().
Referenced by initCurves().
 {
     switch(_id)
     {
         case 0:
            _curve->setColor( Qt::red );
            break;
         case 1:
             _curve->setColor( Qt::blue );
             break;
    }
 }
void SolverPlotter::setReadOnlyLegend (QwtLegend * legend, QwtPlotItem * item, bool on) private
Parameters
legend
item
on
Definition at line 308 of file solverplotter.cpp.
Referenced by updateLegendItemsInGraphic().
 {
     item->setItemAttribute(QwtPlotItem::Legend,on); // This function removes the item from the legend
 }
void SolverPlotter::showCurve (QwtPlotItem * item, bool on) private slot
Function to show the curve.
Parameters
item
on
Definition at line 254 of file solverplotter.cpp.
Referenced by showCurves(), and SolverPlotter().
 {
     item->setVisible(on);
     QWidget *w = legend()->find(item);
     if ( w && w->inherits("QwtLegendItem") )
         ((QwtLegendItem *)w)->setChecked(on);
     replot();
 }
void SolverPlotter::showCurves () private
Function to show the curves.
Definition at line 109 of file solverplotter.cpp.
References curve, data, resRho, resRhoe, and showCurve().
Referenced by clearCanvas(), and SolverPlotter().
 {
     showCurve( data[resRho].curve, true );
     showCurve( data[resRhoe].curve, true );
 }
void SolverPlotter::showPoints (SolverResidualVO * _obj)
Function that shows the points of the read curve.
Parameters
_obj
Definition at line 204 of file solverplotter.cpp.
References _points, data, SolverResidualVO::getIteration(), SolverResidualVO::getResRho(), SolverResidualVO::getResRhoe(), SolverResidualVO::getResRhoeEnabled(), SolverResidualVO::getResRhoEnabled(), resRho, resRhoe, and updateLegendItemsInGraphic().
Referenced by MainWindow::outlog().
 {
     int _iteration  =  _obj->getIteration();
     updateLegendItemsInGraphic(_obj);
     if (_iteration < 0 )
         return;
     // Timing
      if (_obj->getResRhoEnabled())
     {
        data[resRho]._points << QPointF(_iteration,_obj->getResRho());
        data[resRho].curve->setSamples( data[resRho]._points);
     }
     if (_obj->getResRhoeEnabled())
     {
        data[resRhoe]._points << QPointF(_iteration,_obj->getResRhoe());
        data[resRhoe].curve->setSamples( data[resRhoe]._points);
     }
     if( (_obj->getResRhoe() > 50) || (_obj->getResRhoe() < -50) ||
            (_obj->getResRho() > 50) || (_obj->getResRho() < -50)  )
         setAxisAutoScale(QwtPlot::yLeft,true);
     if (_iteration > 100)
         setAxisAutoScale(QwtPlot::xBottom,true);
     replot();
 }
void SolverPlotter::updateLegendItemsInGraphic (SolverResidualVO * _obj)
Parameters
_obj
Definition at line 271 of file solverplotter.cpp.
References curve, data, SolverResidualVO::getResRhoeEnabled(), SolverResidualVO::getResRhoEnabled(), resRho, resRhoe, and setReadOnlyLegend().
Referenced by showPoints().
 {
     setReadOnlyLegend(this->legend(),data[resRho].curve, _obj->getResRhoEnabled() );
     setReadOnlyLegend(this->legend(),data[resRhoe].curve, _obj->getResRhoeEnabled() );
 }
void SolverPlotter::updateValues (PlotterCurve * curve, int _id) private
Function that updates the values of the curve.
Parameters
curve
_id
Definition at line 162 of file solverplotter.cpp.
References curve, data, resRho, and resRhoe.
Referenced by initCurves().
 {
     switch(_id)
     {
     case 0:
         data[resRho].curve = curve;
         (data[resRho]._points) << QPointF(0,0);
         break;
     case 1:
         data[resRhoe].curve = curve;
         (data[resRhoe]._points) << QPointF(0,0);
         break;
     }
 }
Member Data Documentation
QPolygonF SolverPlotter::_points
Definition at line 47 of file solverplotter.h.
Referenced by clearCanvas(), and showPoints().
QwtPlotCurve* SolverPlotter::curve
Definition at line 46 of file solverplotter.h.
Referenced by initCurves(), resetLegend(), showCurves(), updateLegendItemsInGraphic(), and updateValues().
struct { ... } SolverPlotter::data[NResidualData]
Referenced by clearCanvas(), plotterCurve(), resetAllPointValues(), resetLegend(), showCurves(), showPoints(), updateLegendItemsInGraphic(), and updateValues().
int SolverPlotter::dataCount private
Definition at line 52 of file solverplotter.h.
Referenced by resetAllPointValues().
double SolverPlotter::timeData[HISTORY] private
Definition at line 50 of file solverplotter.h.
The documentation for this class was generated from the following files:
Plotter/solverplotter.h
Plotter/solverplotter.cpp