BBIPED Platform: SalomeVariableData Class Reference
SalomeVariableData Class Reference
#include <salomevariabledata.h>
Public Member Functions
SalomeVariableData ()
Constructor.
QString getCurrentValue ()
get the current value of the variable
QString getDefaultValue ()
get the default value
QString getFileName ()
get the file name of the template
QString getName ()
Destructor.
QString getOptimizedValue ()
get the optimized values
void setCurrentValue (QString _val)
Set the current value of the variable.
void setDefaultValue (QString _val)
set the default value
void setFileName (QString _newName)
set the file name of the template
void setName (QString _newName)
Set the template name.
void setOptimizedValue (QString _val)
Set the optimized values.
Private Member Functions
QString removeWhiteSpaces (QString _str)
Remove white spaces.
Private Attributes
QString _currentValue
QString _defaultValue
QString _fileName
QString _name
QString _optimizedValue
Detailed Description
Definition at line 4 of file salomevariabledata.h.
Constructor & Destructor Documentation
SalomeVariableData::SalomeVariableData ()
Constructor.
Definition at line 23 of file salomevariabledata.cpp.
References _currentValue, _defaultValue, _fileName, _name, and _optimizedValue.
 {
     _name = "";
     _fileName = "";
     _defaultValue = "";
     _currentValue = "";
     _optimizedValue = "NO";
 }
Member Function Documentation
QString SalomeVariableData::getCurrentValue ()
get the current value of the variable
Returns
QString
Definition at line 93 of file salomevariabledata.cpp.
References _currentValue.
Referenced by SalomeTemplateDialog::addRow(), SalomeOptimizationDialog::addRow(), SalomePythonFileUtil::getVariables(), SalomePythonFileUtil::getVariablesFromTemplate(), SalomeTemplateManager::restoreToDefaultTemplate(), SalomeTemplateManager::saveVariableData(), and SalomeTemplateDialog::updateTemplateValues().
 {
     return _currentValue;
 }
QString SalomeVariableData::getDefaultValue ()
get the default value
Returns
QString
Definition at line 75 of file salomevariabledata.cpp.
References _defaultValue.
Referenced by SalomeTemplateDialog::addRow(), SalomeOptimizationDialog::addRow(), SalomeTemplateDialog::createTemplateFromUserValues(), SalomePythonFileUtil::getVariablesFromTemplate(), SalomeTemplateDialog::resetValuesToDefault(), SalomeTemplateManager::restoreToDefaultTemplate(), and SalomeTemplateManager::saveVariableData().
 {
     return _defaultValue;
 }
QString SalomeVariableData::getFileName ()
get the file name of the template
Returns
QString
Definition at line 56 of file salomevariabledata.cpp.
References _fileName.
Referenced by SalomeTemplateDialog::createTemplateFromUserValues(), SalomePythonFileUtil::getVariables(), SalomePythonFileUtil::getVariablesFromTemplate(), and SalomeTemplateManager::saveVariableData().
 {
    return _fileName;
 }
QString SalomeVariableData::getName ()
Destructor.
Returns
QString
Definition at line 36 of file salomevariabledata.cpp.
References _name.
Referenced by SalomeTemplateDialog::addRow(), SalomeOptimizationDialog::addRow(), SalomeTemplateData::findByName(), and SalomeTemplateManager::saveVariableData().
 {
     return _name;
 }
QString SalomeVariableData::getOptimizedValue ()
get the optimized values
Returns
QString
Definition at line 113 of file salomevariabledata.cpp.
References _optimizedValue.
Referenced by SalomeOptimizationDialog::addRow(), and SalomeTemplateManager::saveVariableData().
 {
     return _optimizedValue;
 }
QString SalomeVariableData::removeWhiteSpaces (QString _str) private
Remove white spaces.
Parameters
_str
Returns
QString
Definition at line 135 of file salomevariabledata.cpp.
Referenced by setCurrentValue(), setDefaultValue(), setFileName(), and setOptimizedValue().
 {
     _str = _str.simplified();
     _str.replace( " ", "" );
     return _str;
 }
void SalomeVariableData::setCurrentValue (QString _val)
Set the current value of the variable.
Parameters
_val
Definition at line 103 of file salomevariabledata.cpp.
References _currentValue, and removeWhiteSpaces().
Referenced by SalomeTemplateManager::buildVariableData(), SalomeTemplateDialog::createTemplateFromUserValues(), SalomeOptimizationDialog::getVariablesList(), SalomeTemplateManager::restoreToDefaultTemplate(), and SalomeTemplateDialog::updateTemplateValues().
 {
     _currentValue =  removeWhiteSpaces(_val);
 }
void SalomeVariableData::setDefaultValue (QString _val)
set the default value
Parameters
_val
Definition at line 84 of file salomevariabledata.cpp.
References _defaultValue, and removeWhiteSpaces().
Referenced by SalomeTemplateManager::buildVariableData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _defaultValue = removeWhiteSpaces(_val);
 }
void SalomeVariableData::setFileName (QString _newName)
set the file name of the template
Parameters
_newName
Definition at line 65 of file salomevariabledata.cpp.
References _fileName, and removeWhiteSpaces().
Referenced by SalomeTemplateManager::buildVariableData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _fileName = removeWhiteSpaces(_newName);
 }
void SalomeVariableData::setName (QString _newName)
Set the template name.
Parameters
_newName
Definition at line 46 of file salomevariabledata.cpp.
References _name.
Referenced by SalomeTemplateManager::buildVariableData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _name =_newName;
 }
void SalomeVariableData::setOptimizedValue (QString _val)
Set the optimized values.
Parameters
_val
Definition at line 123 of file salomevariabledata.cpp.
References _optimizedValue, and removeWhiteSpaces().
Referenced by SalomeTemplateManager::buildVariableData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _optimizedValue = removeWhiteSpaces(_val);
 }
Member Data Documentation
QString SalomeVariableData::_currentValue private
Definition at line 28 of file salomevariabledata.h.
Referenced by getCurrentValue(), SalomeVariableData(), and setCurrentValue().
QString SalomeVariableData::_defaultValue private
Definition at line 27 of file salomevariabledata.h.
Referenced by getDefaultValue(), SalomeVariableData(), and setDefaultValue().
QString SalomeVariableData::_fileName private
Definition at line 26 of file salomevariabledata.h.
Referenced by getFileName(), SalomeVariableData(), and setFileName().
QString SalomeVariableData::_name private
Definition at line 25 of file salomevariabledata.h.
Referenced by getName(), SalomeVariableData(), and setName().
QString SalomeVariableData::_optimizedValue private
Definition at line 29 of file salomevariabledata.h.
Referenced by getOptimizedValue(), SalomeVariableData(), and setOptimizedValue().
The documentation for this class was generated from the following files:
Data/SalomeTemplateData/salomevariabledata.h
Data/SalomeTemplateData/salomevariabledata.cpp