BBIPED Platform: SummaryDialog Class Reference
SummaryDialog Class Reference
#include <summarydialog.h>
Public Member Functions
SummaryDialog (QWidget *parent=0)
Constructor.
~SummaryDialog ()
Destructor.
void buildSummaryTable ()
Function that builds up the summary table.
void resetDialog ()
Function to reset the dialog.
void setSectionMenuList (QList< SolverSectionVO > _sectionList)
Function to set up the menu elements.
void setValuesToShow (QHash< QString, QString > *_valuesMap)
Function that stores the values from the user to be shown in the dialog.
bool userHasMadeChanges ()
Function that returns true if the user has made changes.
Private Slots
void on_summaryButtonGroup_accepted ()
Function that launchs the actions when the user clicks accept button.
void on_summaryButtonGroup_rejected ()
Function that launchs the actions when the user clicks cancel button.
void on_summaryTable_cellClicked (int row, int column)
Function that loads the help text in a new window.
Private Member Functions
void buildRows ()
Function that builds up the rows of the table.
void buildTableHeader ()
Function that builds up the header of the table.
int getRowTableByVarName (QString _varName)
Function that obatins the row of a specific variable name.
QString getVariableValue (int _row)
Function that gets the value of a specific variable in a row.
void insertVariableInTable (SolverVariableVO _varVO, int _row)
Function that inserts each variabel with the correspondent value in the table.
void updateNewValues ()
Function that update the values changed by the user.
Private Attributes
HelpDialog * _helpDialog
QList< SolverSectionVO > _menuSectionList
QList< SolverVariableVO > _summaryVariables
bool _userHasMadeChanges
QHash< QString, QString > * _valuesToShow
Ui::SummaryDialog * ui
Detailed Description
Definition at line 16 of file summarydialog.h.
Constructor & Destructor Documentation
SummaryDialog::SummaryDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
parent
Definition at line 40 of file summarydialog.cpp.
References _userHasMadeChanges, and ui.
                                             :
     QDialog(parent),
     ui(new Ui::SummaryDialog)
 {
     ui->setupUi(this);
     _userHasMadeChanges = false;
 }
SummaryDialog::~SummaryDialog ()
Destructor.
Definition at line 56 of file summarydialog.cpp.
References ui.
 {
    delete ui;
 }
Member Function Documentation
void SummaryDialog::buildRows () private
Function that builds up the rows of the table.
Definition at line 147 of file summarydialog.cpp.
References _menuSectionList, _summaryVariables, _valuesToShow, SolverSectionDAO::findVariableByFileName(), insertVariableInTable(), SolverVariableVO::isEmpty(), ui, and SolverConfigMenuHelper::updateVariableValueinTable().
Referenced by buildSummaryTable().
 {
     SolverSectionDAO _dao;
     SolverConfigMenuHelper _uiHelper;
     int _row = 0;
     if( (!_valuesToShow->isEmpty()) && (!_menuSectionList.isEmpty()))
     {
         QHashIterator<QString,QString> iter(*_valuesToShow);
         while(iter.hasNext())
         {
             iter.next();
             QString _keyValue = iter.key();
             SolverVariableVO _varVO = _dao.findVariableByFileName(_menuSectionList,_keyValue);
             if (!_varVO.isEmpty())
             {
                 insertVariableInTable(_varVO,_row);
                 _row++;
                 _uiHelper.updateVariableValueinTable(_varVO,ui->summaryTable, _valuesToShow->value(_keyValue));
                 _summaryVariables.append(_varVO);
             }
         }
     }
 }
void SummaryDialog::buildSummaryTable ()
Function that builds up the summary table.
Definition at line 117 of file summarydialog.cpp.
References buildRows(), buildTableHeader(), and ui.
Referenced by MainWindow::on_seeSummaryChangesButton_clicked(), and SolverBasicDialog::on_summarySolverButton_clicked().
 {
     buildTableHeader();
     buildRows();
     ui->summaryTable->resizeColumnsToContents();
 }
void SummaryDialog::buildTableHeader () private
Function that builds up the header of the table.
Definition at line 132 of file summarydialog.cpp.
References ui.
Referenced by buildSummaryTable().
 {
     ui->summaryTable->setColumnCount(4);
     ui->summaryTable->setHorizontalHeaderLabels( QString("Changed;Variable;Value;Help").split(";"));
     ui->summaryTable->horizontalHeader()->setVisible(true);
 }
int SummaryDialog::getRowTableByVarName (QString _varName) private
Function that obatins the row of a specific variable name.
Parameters
_varName
Returns
int
Parameters
_varName
Returns
int
Definition at line 288 of file summarydialog.cpp.
References StrEqual, and ui.
Referenced by updateNewValues().
  {
      for (int i = 0;i < ui->summaryTable->rowCount();i++)
      {
          QString _cVarName = ui->summaryTable->item(i,1)->text();
          if (QString::compare(_cVarName,_varName) == StrEqual)
          {
              return i;
          }
      }
      return -1;
  }
QString SummaryDialog::getVariableValue (int _row) private
Function that gets the value of a specific variable in a row.
Parameters
_row
Returns
QString
Parameters
_row
Returns
QString
Definition at line 313 of file summarydialog.cpp.
References ui.
Referenced by updateNewValues().
  {
      QLineEdit * _lineEdit = qobject_cast<QLineEdit * >(ui->summaryTable->cellWidget(_row,2));
      if (_lineEdit)
      {
          QString _text = _lineEdit->text();
        return _text;
      }
      QComboBox* combo =  qobject_cast<QComboBox * > (ui->summaryTable->cellWidget(_row, 2));
      if (combo)
      {
          QString _text = combo->currentText();
         return _text;
      }
      return QString();
  }
void SummaryDialog::insertVariableInTable (SolverVariableVO _varVO, int _row) private
Function that inserts each variabel with the correspondent value in the table.
Parameters
_varVO
_row
_varVO
_row
Definition at line 184 of file summarydialog.cpp.
References SolverConfigMenuHelper::addVariableToTable(), and ui.
Referenced by buildRows().
 {
         SolverConfigMenuHelper _uiHelper;
         _uiHelper.addVariableToTable(_varVO,ui->summaryTable,_row);
 }
void SummaryDialog::on_summaryButtonGroup_accepted () private slot
Function that launchs the actions when the user clicks accept button.
Definition at line 225 of file summarydialog.cpp.
References updateNewValues().
 {
     updateNewValues();
 }
void SummaryDialog::on_summaryButtonGroup_rejected () private slot
Function that launchs the actions when the user clicks cancel button.
Definition at line 239 of file summarydialog.cpp.
 {
     close();
 }
void SummaryDialog::on_summaryTable_cellClicked (int row, int column) private slot
Function that loads the help text in a new window.
Parameters
row
column
row
column
Definition at line 203 of file summarydialog.cpp.
References _helpDialog, _summaryVariables, SolverVariableVO::getHelpContents(), HelpDialog::loadHelpText(), and HelpDialog::setHelpText().
 {
     if (column == 3)
     {
         _helpDialog = new HelpDialog();
         SolverVariableVO _variable = _summaryVariables.at(row);
         _helpDialog->setHelpText(_variable.getHelpContents(true)); // TO BE REVIEWED
         _helpDialog->loadHelpText();
         _helpDialog->exec();
       }
 }
void SummaryDialog::resetDialog ()
Function to reset the dialog.
Definition at line 69 of file summarydialog.cpp.
References _userHasMadeChanges.
Referenced by SolverBasicDialog::on_summarySolverButton_clicked().
 {
         _userHasMadeChanges = false;
 }
void SummaryDialog::setSectionMenuList (QList< SolverSectionVO > _sectionList)
Function to set up the menu elements.
Parameters
_sectionList
_sectionList
Definition at line 102 of file summarydialog.cpp.
References _menuSectionList.
Referenced by MainWindow::on_seeSummaryChangesButton_clicked(), and SolverBasicDialog::on_summarySolverButton_clicked().
 {
     _menuSectionList = _sectionList;
 }
void SummaryDialog::setValuesToShow (QHash< QString, QString > * _valuesMap)
Function that stores the values from the user to be shown in the dialog.
Parameters
QHash<QString
_valuesMap
QHash<QString
_valuesMap
Definition at line 87 of file summarydialog.cpp.
References _valuesToShow.
Referenced by MainWindow::on_seeSummaryChangesButton_clicked(), and SolverBasicDialog::on_summarySolverButton_clicked().
 {
     _valuesToShow  = _valuesMap;
 }
void SummaryDialog::updateNewValues () private
Function that update the values changed by the user.
Definition at line 253 of file summarydialog.cpp.
References _menuSectionList, _userHasMadeChanges, _valuesToShow, SolverSectionDAO::findVariableByFileName(), getRowTableByVarName(), SolverVariableVO::getVariableName(), getVariableValue(), and StrEqual.
Referenced by on_summaryButtonGroup_accepted().
 {
     QHashIterator<QString,QString> iter(*_valuesToShow);
     while(iter.hasNext())
     {
         iter.next();
         QString _keyValue = iter.key();
         SolverSectionDAO _dao;
         SolverVariableVO _varVO = _dao.findVariableByFileName(_menuSectionList,_keyValue);
         QString _varName = _varVO.getVariableName();
         if( (!_varName.isEmpty()) && (!_varName.isNull()))
         {
             QString _actualValue = getVariableValue(getRowTableByVarName(_varName));
             if (QString::compare(_actualValue,_valuesToShow->value(_keyValue)) != StrEqual)
             {
                 _valuesToShow->insert(_keyValue,_actualValue);
                 _userHasMadeChanges = true;
             }
         }
     }
 }
bool SummaryDialog::userHasMadeChanges ()
Function that returns true if the user has made changes.
Returns
bool
bool
Definition at line 343 of file summarydialog.cpp.
References _userHasMadeChanges.
Referenced by MainWindow::on_seeSummaryChangesButton_clicked(), and SolverBasicDialog::on_summarySolverButton_clicked().
  {
      return _userHasMadeChanges;
  }
Member Data Documentation
HelpDialog* SummaryDialog::_helpDialog private
Definition at line 45 of file summarydialog.h.
Referenced by on_summaryTable_cellClicked().
QList<SolverSectionVO> SummaryDialog::_menuSectionList private
Definition at line 47 of file summarydialog.h.
Referenced by buildRows(), setSectionMenuList(), and updateNewValues().
QList<SolverVariableVO> SummaryDialog::_summaryVariables private
Definition at line 48 of file summarydialog.h.
Referenced by buildRows(), and on_summaryTable_cellClicked().
bool SummaryDialog::_userHasMadeChanges private
Definition at line 49 of file summarydialog.h.
Referenced by resetDialog(), SummaryDialog(), updateNewValues(), and userHasMadeChanges().
QHash<QString,QString>* SummaryDialog::_valuesToShow private
Definition at line 46 of file summarydialog.h.
Referenced by buildRows(), setValuesToShow(), and updateNewValues().
Ui::SummaryDialog* SummaryDialog::ui private
Definition at line 44 of file summarydialog.h.
Referenced by buildRows(), buildSummaryTable(), buildTableHeader(), getRowTableByVarName(), getVariableValue(), insertVariableInTable(), SummaryDialog(), and ~SummaryDialog().
The documentation for this class was generated from the following files:
Forms/summarydialog.h
Forms/summarydialog.cpp