BBIPED Platform: HelpManager Class Reference
HelpManager Class Reference
#include <helpmanager.h>
Public Member Functions
HelpManager ()
void openHelp (QString _file, QString _folder)
This function opens the help URK.
void openQtAssistant ()
This function opens the Qt Assistant with the correspondent help files.
Detailed Description
Definition at line 6 of file helpmanager.h.
Constructor & Destructor Documentation
HelpManager::HelpManager ()
Definition at line 28 of file helpmanager.cpp.
 {
 }
Member Function Documentation
void HelpManager::openHelp (QString _file, QString _folder)
This function opens the help URK.
Parameters
_file
_folder
Definition at line 37 of file helpmanager.cpp.
Referenced by MainWindow::on_actionDeveloper_Guide_2_triggered(), MainWindow::on_actionOnline_Help_triggered(), and MainWindow::on_actionUser_GuideLine_2_triggered().
 {
     QString _currentPath = QCoreApplication::applicationDirPath();//QDir::currentPath();
     QString _docPath = QDir(QDir(QDir(_currentPath).filePath("Documentation")).filePath(_folder)).filePath(_file);
     QUrl  _url  = QUrl("file://"+_docPath);
     QDesktopServices::openUrl(_url);
 }
void HelpManager::openQtAssistant ()
This function opens the Qt Assistant with the correspondent help files.
Definition at line 49 of file helpmanager.cpp.
Referenced by MainWindow::on_actionHelp_Contents_triggered().
 {
     QString _path = QDir(QCoreApplication::applicationDirPath()).filePath("Documentation");
                // QDir::currentPath()).filePath("Documentation");
     QProcess * _helpProcess = new QProcess;
     _helpProcess->setWorkingDirectory(_path);
     QStringList args;
     args << QLatin1String("-collectionFile") << QLatin1String("bbiped.qhc") << QLatin1String("-enableRemoteControl");
     _helpProcess->start(QLatin1String("assistant"), args);
     if (!_helpProcess->waitForStarted())
         return;
 }
The documentation for this class was generated from the following files:
Help/helpmanager.h
Help/helpmanager.cpp