BBIPED Platform: SolverConfigManager Class Reference
SolverConfigManager Class Reference
#include <solverconfigmanager.h>
Public Member Functions
SolverConfigManager ()
Constructor.
~SolverConfigManager ()
void buildMenuVariablesList ()
Function that builds the menu elements.
QDomDocument * getAdvancedMenuList ()
Function that returns the Advanced Menu List elements.
QDomDocument * getAllMenuList ()
Returns the complete menu list from the Xml document.
QList< SolverSectionVO > getAllPersonalizedSectionMenuList ()
QList< SolverSectionVO > getAllSectionMenuList ()
Function that gets all the sections to be shown in the menu list.
QDomDocument * getBasicMenuList ()
Function that returns the Basic Menu List elements.
QDomDocument * getBoundaryMenuList ()
Function that returns the Boundary Menu List elements.
QDomDocument * getBoundaryMenuListWithoutMultizoneChildren ()
QDomDocument * getConfigDomTree ()
Function that gets the current DOM Tree.
QDomDocument * getPersonalizedTemplateMenuList ()
Returns the personalized template menu list.
SolverSectionVO getPersonalizedVariableListofSubsections (QString _subsection)
Returns.
SolverSectionVO getVariableListofSubsections (QString _subsection)
Function that gets the list of variables from a Subsection Element of the menu.
void initializeManager ()
Function that initialize the Solver Manager loading the Config template.
bool isInitialized ()
Function that checks if the config manager is initialized.
bool isPersonalizedMenuListAvailable ()
Returns true if a personalized view is available.
void loadPersonalizedTemplate (QString _path)
This fucntion loads a personalized user defined template.
void resetPersonalizedMenu ()
Reset all the variables associated to the Personalized Menu.
void saveConfigFile (QString _file, QHash< QString, QString > _userConfigValues, ProjectDetails _projectDetails, QList< VirtualMrfVO > _virtualMRFList)
Functions that save the user configuration values into the file.
void setConfigDomTree (QDomDocument *_newDom)
Function that sets a new DOM tree.
void updateDOMTree (QHash< QString, QString > _solverHash)
Function that uptades teh values of the DOM tree according to the Map values.
void updateVisibility (QStringList _listVariables, bool _visibility)
This function allows to update the visibility of the variables according the rules and the user selection.
Private Member Functions
void buildAdvancedMenuList ()
Function to build all the elements of the advanced menu.
void buildBasicMenuList ()
Function to build all the elements of the basic menu.
void buildBoundaryMenuList ()
Function to build the Boundary menu.
void buildCompleteMenuList ()
This function builds the complete menu list regardless the basic or advanced view from the XMl file.
void buildCompleteMenuList (bool _basicView, QDomDocument *_fullTree, QDomDocument *_menuTree)
This function builds the menu to be shown in the tree.
void buildMainMenu (bool _basicView, QDomDocument *_fullTree, QDomDocument *_menuTree)
Function to build all the elements main menu.
void buildPersonalizedMenuList ()
This function builds a personalized menu list.
void buildPersonalizedMenuVariablesList ()
This function builds the personalized variable list.
void loadConfigTemplate ()
Function that loads the config template from an XML file.
bool loadConfigTemplate (QDomDocument *_tree, QString _path)
This function loads the config template from a specific file path (for the case of loading a template)
Private Attributes
QDomDocument * _advancedMenuList
QDomDocument * _basicMenuList
QDomDocument * _boundaryMenuList
QDomDocument * _completeMenuList
QDomDocument * _configDomTree
bool _isInitialized
bool _isPersonalizedViewInitialized
SolverSectionVO _markerMenu
QDomDocument * _personalizedDomTree
QList< SolverSectionVO > _personalizedMenuList
QDomDocument * _personalizedTemplateMenuList
QList< SolverSectionVO > _sectionMenuList
Detailed Description
Definition at line 11 of file solverconfigmanager.h.
Constructor & Destructor Documentation
SolverConfigManager::SolverConfigManager ()
Constructor.
Definition at line 40 of file solverconfigmanager.cpp.
 {
     _isInitialized = false;
     _isPersonalizedViewInitialized = false;
 }
SolverConfigManager::~SolverConfigManager ()
Definition at line 45 of file solverconfigmanager.cpp.
 {
 }
Member Function Documentation
void SolverConfigManager::buildAdvancedMenuList () private
Function to build all the elements of the advanced menu.
Definition at line 221 of file solverconfigmanager.cpp.
 {
     _advancedMenuList = new QDomDocument("advancedView");
     buildMainMenu(false, _configDomTree,_advancedMenuList);
 }
void SolverConfigManager::buildBasicMenuList () private
Function to build all the elements of the basic menu.
Definition at line 147 of file solverconfigmanager.cpp.
 {
     _basicMenuList = new QDomDocument("basicMenuList");
     buildMainMenu(true, _configDomTree,_basicMenuList);
 }
void SolverConfigManager::buildBoundaryMenuList () private
Function to build the Boundary menu.
Definition at line 209 of file solverconfigmanager.cpp.
References SolverMarkerMenuHelper::addMarkerMenu().
 {
     SolverMarkerMenuHelper _markerMenuHelper;
     _boundaryMenuList = new QDomDocument("boundaryView");
     _markerMenuHelper.addMarkerMenu(_configDomTree,_boundaryMenuList);
 }
void SolverConfigManager::buildCompleteMenuList () private
This function builds the complete menu list regardless the basic or advanced view from the XMl file.
Definition at line 159 of file solverconfigmanager.cpp.
 {
     _completeMenuList = new QDomDocument("completeMenuList");
     buildCompleteMenuList(false,_configDomTree,_completeMenuList);
 }
void SolverConfigManager::buildCompleteMenuList (bool _basicView, QDomDocument * _fullTree, QDomDocument * _menuTree) private
This function builds the menu to be shown in the tree.
Parameters
_basicView
_fullTree
_menuTree
Definition at line 181 of file solverconfigmanager.cpp.
 {
     SolverConfigMenuHelper _uiHelper;
     buildMainMenu(_basicView,_fullTree,_menuTree);
  }
void SolverConfigManager::buildMainMenu (bool _basicView, QDomDocument * _fullTree, QDomDocument * _menuTree) private
Function to build all the elements main menu.
Parameters
_basicView
_fullTree
_menuTree
Definition at line 195 of file solverconfigmanager.cpp.
References SolverConfigMenuHelper::addMenuElements(), IO_TITLE, MARKER_TITLE, MESH_TITLE, SolverConfigMenuHelper::removeMenuElementByName(), and SolverConfigMenuHelper::removeSubsectionElementByName().
 {
      SolverConfigMenuHelper _solverUIHelper;
     _solverUIHelper.addMenuElements(_basicView,_fullTree,_menuTree);
     _solverUIHelper.removeMenuElementByName(MARKER_TITLE,_menuTree);
     _solverUIHelper.removeSubsectionElementByName(IO_TITLE,MESH_TITLE,_menuTree);
 }
void SolverConfigManager::buildMenuVariablesList ()
Function that builds the menu elements.
Definition at line 232 of file solverconfigmanager.cpp.
References SolverConfigReader::getAllSectionVariableMenus().
 {
     SolverConfigReader _reader;
     _sectionMenuList = _reader.getAllSectionVariableMenus(_configDomTree);
 }
void SolverConfigManager::buildPersonalizedMenuList () private
This function builds a personalized menu list.
Definition at line 169 of file solverconfigmanager.cpp.
{
     _personalizedTemplateMenuList = new QDomDocument("personalizedMenuList");
     buildCompleteMenuList(false,_personalizedDomTree,_personalizedTemplateMenuList);
 }
void SolverConfigManager::buildPersonalizedMenuVariablesList () private
This function builds the personalized variable list.
Definition at line 245 of file solverconfigmanager.cpp.
References SolverConfigReader::getAllSectionVariableMenus().
 {
     SolverConfigReader _reader;
     _personalizedMenuList = _reader.getAllSectionVariableMenus(_personalizedDomTree);
 }
QDomDocument * SolverConfigManager::getAdvancedMenuList ()
Function that returns the Advanced Menu List elements.
Returns
QDomDocument
Definition at line 383 of file solverconfigmanager.cpp.
Referenced by SolverBasicDialog::loadMenu().
 {
     return _advancedMenuList;
 }
QDomDocument * SolverConfigManager::getAllMenuList ()
Returns the complete menu list from the Xml document.
Returns
QDomDocument
Definition at line 363 of file solverconfigmanager.cpp.
Referenced by TemplateDialog::setSolverConfigManager().
 {
     return _completeMenuList;
 }
QList< SolverSectionVO > SolverConfigManager::getAllPersonalizedSectionMenuList ()
Returns
QList<SolverSectionVO>
Definition at line 457 of file solverconfigmanager.cpp.
Referenced by TemplateDialog::loadTemplate().
 {
     return _personalizedMenuList;
 }
QList< SolverSectionVO > SolverConfigManager::getAllSectionMenuList ()
Function that gets all the sections to be shown in the menu list.
Returns
QList<SolverSectionVO>
Definition at line 447 of file solverconfigmanager.cpp.
Referenced by SolverHelper::launchFileComparisonDialog(), TemplateDialog::on_buttonBox_accepted(), MainWindow::on_seeSummaryChangesButton_clicked(), SolverBasicDialog::on_summarySolverButton_clicked(), MultizoneSummaryDialog::removeDefaultValues(), MainWindow::removeDefaultValuesReadFromConfigFile(), and WarningMultizoneDialog::WarningMultizoneDialog().
 {
     return _sectionMenuList;
 }
QDomDocument * SolverConfigManager::getBasicMenuList ()
Function that returns the Basic Menu List elements.
Returns
QDomDocument
Definition at line 373 of file solverconfigmanager.cpp.
Referenced by SolverBasicDialog::loadMenu().
 {
     return _basicMenuList;
 }
QDomDocument * SolverConfigManager::getBoundaryMenuList ()
Function that returns the Boundary Menu List elements.
Returns
QDomDocument
Definition at line 394 of file solverconfigmanager.cpp.
Referenced by MeshDialog::loadMenu().
 {
     return _boundaryMenuList;
 }
QDomDocument * SolverConfigManager::getBoundaryMenuListWithoutMultizoneChildren ()
Definition at line 398 of file solverconfigmanager.cpp.
References MARKER_TITLE, and SolverConfigMenuHelper::removeSubsectionElementByName().
Referenced by MeshDialog::loadMenu().
 {
     SolverConfigMenuHelper _solverUIHelper;
    _solverUIHelper.removeSubsectionElementByName(MARKER_TITLE,"Boundary Multizone",_boundaryMenuList);
    return _boundaryMenuList;
 }
QDomDocument * SolverConfigManager::getConfigDomTree ()
Function that gets the current DOM Tree.
Returns
QDomDocument
Definition at line 353 of file solverconfigmanager.cpp.
 {
     return this->_configDomTree;
 }
QDomDocument * SolverConfigManager::getPersonalizedTemplateMenuList ()
Returns the personalized template menu list.
Returns
QDomDocument
Definition at line 410 of file solverconfigmanager.cpp.
Referenced by SolverBasicDialog::updatePersonalizedMenu().
 {
     return _personalizedTemplateMenuList;
 }
SolverSectionVO SolverConfigManager::getPersonalizedVariableListofSubsections (QString _subsection)
Returns.
Parameters
_subsection
Returns
SolverSectionVO
Definition at line 434 of file solverconfigmanager.cpp.
References SolverSectionDAO::findSubSection().
Referenced by SolverBasicDialog::fillTable().
 {
     SolverSectionDAO _sectionDAO;
     SolverSectionVO _foundList = _sectionDAO.findSubSection(_subsection,_personalizedMenuList);
     return _foundList;
 }
SolverSectionVO SolverConfigManager::getVariableListofSubsections (QString _subsection)
Function that gets the list of variables from a Subsection Element of the menu.
Parameters
_subsection
Returns
SolverSectionVO
Definition at line 421 of file solverconfigmanager.cpp.
References SolverSectionDAO::findSubSection().
Referenced by SolverBasicDialog::buildAllToolTips(), MeshDialog::buildHelpContent(), SolverBasicDialog::checkIsDefaultValue(), MeshDialog::fillTable(), SolverBasicDialog::fillTable(), TemplateDialog::fillTableVarToSelect(), SolverBasicDialog::getAssociatedFileNameValue(), MeshDialog::initializeMeshValues(), SolverBasicDialog::launchSpecificWindow(), MeshDialog::needToOpenSpecificConfigWindow(), TemplateDialog::on_selectedVariablesTableWidget_cellClicked(), SolverBasicDialog::on_solverMenuTree_clicked(), SolverBasicDialog::on_solverVariablesTable_cellClicked(), TemplateDialog::on_variablesToSelectTableWidget_cellClicked(), SolverBasicDialog::resetToDefaultValue(), MeshDialog::restoreValues(), SolverBasicDialog::saveUserChanges(), SolverBasicDialog::saveUserChangesSpecificWindow(), and SearchPairHelper::searchTreeBySearchTerm().
 {
     SolverSectionDAO _sectionDAO;
     SolverSectionVO _foundList = _sectionDAO.findSubSection(_subsection,_sectionMenuList);
     return _foundList;
 }
void SolverConfigManager::initializeManager ()
Function that initialize the Solver Manager loading the Config template.
Definition at line 55 of file solverconfigmanager.cpp.
Referenced by MultizoneProjectDialog::buildFilesInProject(), MainWindow::initializeManagers(), MeshDialog::loadMenu(), SolverBasicDialog::loadMenu(), FileComparisonDialog::on_buttonBox_accepted(), MainWindow::on_solverButton_clicked(), SolverBasicDialog::resetAllConfigurationValues(), TemplateDialog::setSolverConfigManager(), and WarningMultizoneDialog::WarningMultizoneDialog().
 {
     loadConfigTemplate();
 }
bool SolverConfigManager::isInitialized ()
Function that checks if the config manager is initialized.
Returns
bool
Definition at line 324 of file solverconfigmanager.cpp.
Referenced by MultizoneProjectDialog::buildFilesInProject(), MainWindow::initializeManagers(), MeshDialog::loadMenu(), SolverBasicDialog::loadMenu(), MainWindow::on_solverButton_clicked(), MultizoneSummaryDialog::removeDefaultValues(), MainWindow::removeDefaultValuesReadFromConfigFile(), and TemplateDialog::setSolverConfigManager().
 {
     return _isInitialized;
 }
bool SolverConfigManager::isPersonalizedMenuListAvailable ()
Returns true if a personalized view is available.
Returns
bool
Definition at line 334 of file solverconfigmanager.cpp.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     return _isPersonalizedViewInitialized;
 }
void SolverConfigManager::loadConfigTemplate () private
Function that loads the config template from an XML file.
Definition at line 67 of file solverconfigmanager.cpp.
References CONFIG_TEMPLATE_PATH.
 {
     // Loading the file from the resource
     QFile * _templateConfigFile = new QFile(CONFIG_TEMPLATE_PATH);
     _configDomTree = new QDomDocument();
     if( !_templateConfigFile->open( QIODevice::ReadOnly | QIODevice::Text ) )
     {
         qDebug( "Failed to open file for reading." );
     }
     else
     {
         if( !_configDomTree->setContent( _templateConfigFile ) )
         {
             qDebug( "Failed to parse the file into a DOM tree." );
             _templateConfigFile->close();
         }
           _templateConfigFile->close();
           buildBasicMenuList();
           buildAdvancedMenuList();
           buildMenuVariablesList();
           buildBoundaryMenuList();
           buildCompleteMenuList();
           _isInitialized = true;
     }
     _templateConfigFile->close();
 }
bool SolverConfigManager::loadConfigTemplate (QDomDocument * _tree, QString _path) private
This function loads the config template from a specific file path (for the case of loading a template)
Parameters
_tree
_path
Returns
bool
Definition at line 104 of file solverconfigmanager.cpp.
 {
     bool _isLoaded = false;
    // _tree = new QDomDocument();
     QFile * _templateFile = new QFile (_path);
     bool _fileOpened =  _templateFile->open(QIODevice::ReadOnly | QIODevice::Text ) ;
     if (!_fileOpened)
     {   _templateFile->close();
         return _isLoaded;
     }
     // Parsing the file into a Dom Tree
     bool _isSetContent = _tree->setContent(_templateFile);
     if (!_isSetContent)
     {   _templateFile->close();
         return _isLoaded;
     }
     _templateFile->close();
     buildPersonalizedMenuList();
     buildPersonalizedMenuVariablesList();
     _isLoaded = true;
     return _isLoaded;
 }
void SolverConfigManager::loadPersonalizedTemplate (QString _path)
This fucntion loads a personalized user defined template.
Parameters
_path
Definition at line 133 of file solverconfigmanager.cpp.
Referenced by SolverHelper::editConfigurationTemplateByUser(), MainWindow::initializeManagers(), and SolverHelper::loadConfigurationTemplateByUser().
 {
     _personalizedDomTree = new QDomDocument();
     _isPersonalizedViewInitialized = loadConfigTemplate(_personalizedDomTree,_path);
 }
void SolverConfigManager::resetPersonalizedMenu ()
Reset all the variables associated to the Personalized Menu.
Definition at line 469 of file solverconfigmanager.cpp.
Referenced by EditHelper::launchPreferencesDialog().
 {
     _isPersonalizedViewInitialized = false;
     _personalizedDomTree = new QDomDocument();
     _personalizedTemplateMenuList = new QDomDocument();
     _personalizedMenuList.clear();
 }
void SolverConfigManager::saveConfigFile (QString _file, QHash< QString, QString > _userConfigValues, ProjectDetails _projectDetails, QList< VirtualMrfVO > _virtualMRFList)
Functions that save the user configuration values into the file.
Parameters
_file
Definition at line 262 of file solverconfigmanager.cpp.
References SolverSectionDAO::getOptionalVariables(), SolverConfigWriter::setOptionalVariableList(), SolverConfigWriter::setUserValues(), SolverConfigWriter::setVirtualMRFUserValues(), and SolverConfigWriter::writeToConfigurationFile().
Referenced by MultizoneProjectDialog::buildFilesInProject(), MultizoneProjectDialog::checkConsistency(), FileComparisonDialog::on_buttonBox_accepted(), InputDataTabHelper::saveAsConfigFile(), MainWindow::saveConfigFile(), MainWindow::saveMultizoneData(), and MainWindow::updateMultizoneUserData().
 {
     SolverConfigWriter _solverWriter;
     SolverSectionDAO _sectionDAO;
     QList<SolverSectionVO> _sectionList = getAllSectionMenuList();
     _solverWriter.setUserValues(_userConfigValues);
     _solverWriter.setOptionalVariableList(_sectionDAO.getOptionalVariables(_sectionList));
     _solverWriter.setVirtualMRFUserValues(_virtualMRFList);
     _solverWriter.writeToConfigurationFile(_file,_configDomTree,_projectDetails);
 }
void SolverConfigManager::setConfigDomTree (QDomDocument * _newDom)
Function that sets a new DOM tree.
Parameters
_newDom
Definition at line 343 of file solverconfigmanager.cpp.
 {
     this->_configDomTree = _newDom;
 }
void SolverConfigManager::updateDOMTree (QHash< QString, QString > _solverHash)
Function that uptades teh values of the DOM tree according to the Map values.
Parameters
QHash<QString
_solverHash
Definition at line 281 of file solverconfigmanager.cpp.
References SolverConfigReader::updateAllDomTree().
Referenced by MainWindow::saveConfigFile().
 {
     SolverConfigReader _solverReader;
     _solverReader.updateAllDomTree(_solverHash,_configDomTree);
 }
void SolverConfigManager::updateVisibility (QStringList _listVariables, bool _visibility)
This function allows to update the visibility of the variables according the rules and the user selection.
Parameters
_listVariables
_visibility
Definition at line 294 of file solverconfigmanager.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableFileName(), and SolverVariableVO::setVisibility().
Referenced by RuleEngine::updateVisibilitySolverManager().
 {
    if ((!_listVariables.isEmpty()) && (!_sectionMenuList.isEmpty()))
     {
         for(int i = 0; i < _sectionMenuList.size();i++)
         {
             SolverSectionVO _section = _sectionMenuList.at(i);
             QList<SolverVariableVO> _varList = _section.getSubsectionVarList();
             QList<SolverVariableVO> _newVarList;
             if (!_varList.isEmpty())
                 for (int j= 0; j<_varList.size();j++)
                 {
                     SolverVariableVO _var = _varList.at(j);
                     if (_listVariables.contains(_var.getVariableFileName()))
                         _var.setVisibility(_visibility);
                     _newVarList.append(_var);
                 }
             _sectionMenuList[i].setSubsectionVarList(_newVarList);
         }
     }
 }
Member Data Documentation
QDomDocument* SolverConfigManager::_advancedMenuList private
Definition at line 56 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_basicMenuList private
Definition at line 55 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_boundaryMenuList private
Definition at line 57 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_completeMenuList private
Definition at line 54 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_configDomTree private
Definition at line 52 of file solverconfigmanager.h.
bool SolverConfigManager::_isInitialized private
Definition at line 64 of file solverconfigmanager.h.
bool SolverConfigManager::_isPersonalizedViewInitialized private
Definition at line 65 of file solverconfigmanager.h.
SolverSectionVO SolverConfigManager::_markerMenu private
Definition at line 63 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_personalizedDomTree private
Definition at line 53 of file solverconfigmanager.h.
QList<SolverSectionVO> SolverConfigManager::_personalizedMenuList private
Definition at line 61 of file solverconfigmanager.h.
QDomDocument* SolverConfigManager::_personalizedTemplateMenuList private
Definition at line 58 of file solverconfigmanager.h.
QList<SolverSectionVO> SolverConfigManager::_sectionMenuList private
Definition at line 60 of file solverconfigmanager.h.
The documentation for this class was generated from the following files:
Solver/solverconfigmanager.h
Solver/solverconfigmanager.cpp