BBIPED Platform: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Signals
void outlogtext (QString ver)
Public Member Functions
MainWindow (QWidget *parent=0)
Constructor.
~MainWindow ()
Destructor.
void saveMultizoneData (QString _configFile, QString _meshFile, QHash< QString, QString > *_configVal, QList< VirtualMrfVO > *_virtualMrfList)
Protected Member Functions
void closeEvent (QCloseEvent *event)
Function that controls the close event.
Private Types
enum tabVariables
Private Slots
void getSalomePathSlot ()
This function is the one capable of locating the Salome path in the client side.
void on_actionAbout_triggered ()
About us.
void on_actionAutomatic_Optimization_triggered ()
This function is to create automatic mesh using Salome but with optimization parameters.
void on_actionClose_Project_triggered ()
CLOSE a Project.
void on_actionCompare_Configuration_Files_triggered ()
this funciton controls the compare Configuration file action
void on_actionCreate_Configuration_Template_triggered ()
This function is for creating customized templates for the configuration menus.
void on_actionDeveloper_Guide_2_triggered ()
This action shows the html documentation of the tool.
void on_actionEdit_Configuration_Template_triggered ()
This function allows to edit existing configuration templates.
void on_actionExit_triggered ()
Function that controls the exit of the application.
void on_actionHelp_Contents_triggered ()
This function launchs the Qt Assistant for showing the help of BBIPED.
void on_actionImport_Mesh_File_triggered ()
Import Mesh file.
void on_actionLoad_Configuration_Template_triggered ()
This function allows to load specific configuration template.
void on_actionLoad_Templates_triggered ()
This function is to create automatic mesh using Salome.
void on_actionNew_Multizone_Project_triggered ()
This function is to control the action of defining a new Multizone project.
void on_actionNew_Project_triggered ()
Create a New Project.
void on_actionOnline_Help_triggered ()
This action shows the html help.
void on_actionOpen_Multizone_Project_triggered ()
This funciton opens a Multizone project.
void on_actionOpen_Project_triggered ()
Open a Project.
void on_actionParaview_File_triggered ()
Launching the paraview application.
void on_actionPreferences_triggered ()
This method controls the Preference dialog launch.
void on_actionProject_Settings_triggered ()
This funciton controls the project settings action.
void on_actionRun_Project_triggered ()
Run Solver Project.
void on_actionSalome_Mesh_triggered ()
This action is the Menu action for lauching Salome.
void on_actionSave_As_triggered ()
SAVE AS a Project.
void on_actionSave_Configuration_File_As_triggered ()
SOLVER: Main functionality to save the changes of the configuration file with a different name.
void on_actionSave_Configuration_File_triggered ()
SOLVER: Main functionality to save the changes of the configuration file.
void on_actionSave_Residual_Image_triggered ()
This function allows to save the residual image generated in a simulation.
void on_actionSave_Temporal_triggered ()
SAVE TEMPORAL –> TODO.
void on_actionSave_triggered ()
Save a Project.
void on_actionStop_Execution_triggered ()
Stop current simulation.
void on_actionSynchronise_all_files_triggered ()
This function controls the synchronise file action.
void on_actionUser_GuideLine_2_triggered ()
This action shows the PDF user guide documentation.
void on_basivViewEditButton_clicked ()
SOLVER: Main functionality to show the basic configuration view for the Physics config menu.
void on_importMeshFileButton_clicked ()
SOLVER: Import mesh file button.
void on_multizoneDeleteButton_clicked ()
void on_multizoneNewButton_clicked ()
void on_multizoneOpenEditButton_clicked ()
void on_multizoneRestartSimulation_clicked ()
void on_multizoneRunSimulationButton_clicked ()
void on_multizoneSaveAllButton_clicked ()
void on_multizoneStopSimulationButton_clicked ()
void on_multizoneSummaryAllConfigButton_clicked ()
void on_newActionButton_clicked ()
SOLVER: Create New configuration file.
void on_openFileActionButton_clicked ()
SOLVER: Open existent configuration file in the current project folder.
void on_paraviewButton_clicked ()
This function launchs the Paraview tool from the button click.
void on_projectTreeView_doubleClicked (const QModelIndex &index)
This function allow to open in a tab a configuration file or any text file with supported extensions.
void on_restartButton_clicked ()
SOLVER: If restart option is allowed, restart simulation.
void on_runSimulationButton_clicked ()
SOLVER: Run the current simulation.
void on_salomeButton_clicked ()
This function launchs the Salome tool.
void on_savePhysicsButton_clicked ()
Save Physics button functionality, it saves all the information (including the boundaries into a single configuration file.
void on_seeSummaryChangesButton_clicked ()
SOLVER: Shows the user input for the configuration file.
void on_setMeshPropertiesButton_clicked ()
SOLVER: Function to load the menu for configuring the boundaries by the user.
void on_solverButton_clicked ()
Action when the Solver Button is clicked.
void on_solverTabwidget_tabCloseRequested (int index)
Implementation to Close the tabs.
void on_stopButton_clicked ()
This function is to refresh the mesh file.
void openRecentFile ()
This action opens a project selected in the recent project list.
void outlog ()
Slot that allows to capture the standard output and redirect to the console text entry.
void slotFinishResult (int _val, QProcess::ExitStatus status)
Slot function that performs some operations as soon as the process finish.
void slotProcessError (QProcess::ProcessError error)
Slot function that captures the error if something goes wrong in the process.
void slotStarted ()
Slot function that shows when the process has started.
Private Member Functions
void addProjectToRecentProjectsSection (QString _projectPathName)
This function add a new project to the "recent project list".
QString buildSolverCommand ()
Function to build the solver Command according project conditions and user preferences.
void checkMeshNames ()
This function checks the mesh boundary names.
void checkProjectBasePathConsistency (ProjectData *_openedProject, QString _currentFilePath)
This function checks whether the path of the open project and the current project path is equal, if not, it updates it. It is used when we opened a project that has been created in a different computer (similar to import Project)
void clearAllData ()
Clear all the data to the default values.
void clearConsoleText ()
Clear the console text and removes all the text.
void clearProjectTreeView ()
void closeExistentProject ()
This function does all teh actions required to close an existent project, reseting to default values, as well as stopping any existent simulation run.
void closeProject ()
Close Project function.
void connectProcessSignalSlots ()
Connecting the Process Signal Slots.
void createProjectActions (QStringList _list)
This function creates a new recent project action per each element of the list.
QAction * createRecentProjectAction (QString _name)
This function creates the QAction for the "recent project list".
void disableAllMainButtons ()
Disable all the Tool Buttons.
void enableAllMainButtons ()
Enable all the Tool Buttons.
void enableMeshOptions ()
This function enables the GUI mesh button and actions.
void enableMultizoneElements ()
This function controls the enabling of all the elements associated with the Multizone interface.
void enableSolverRunAction ()
Enable the action buttons for running the simulation according with the current status of the application and the configuration made by the user.
void enableToolButtons (int _buttonName)
Enable correspondent Buttons and disable the one that is clicked.
bool exitApplication ()
This function controls the exit of the Application, to close everything and to save the data to the user preferences file if needed.
void fillMultizoneTable ()
int getCurrentUserPreferences ()
This function returns which type of Solver Engine is defined.
void getLoadedBoundaryValues ()
load the Boundary values
QList< int > getSelectedFiles ()
QString getSolverCommand ()
This function decides which Solver running executable is going to be called. At the moment there are 3 options: SU2_CFD, SU2_CFD_VMRF, SU2_CFD_MULTIZONE.
void importMeshFile ()
void importMeshFile (QString _meshConfigFile)
Dialog for importing a mesh file.
void importMeshInfoFile (QString _file)
void initializeHelper ()
This fucntion initalize all the data of the Tab helper, like button registration and so on.
void initializeManagers ()
Initialize Solver manager, user Preferences data manager.
void initializeStructures ()
Initialize Main Window structures.
void initializeUserPreferences ()
This function initialize the variables associated with user preferences.
void insertMultizoneRow (int _pos, QString _configName, QString _meshName)
void launchActionProjectSettingsDialog ()
This function controls the launching of the Project Settings Dialog.
void launchSalomeMeshTool ()
This internal function controls how to launch the Salome tool, specially due to the path of this tool (not in traditional Linux paths like usr/bin). So, with this function we locate the path to Salome to run it.
void loadMeshDialog ()
SOLVER: funtion to load the MESH dialog.
void multizoneSaveAll ()
bool notSavedMultizoneData ()
void openProject (QString _projectFilePath)
This function controls the opening of a project.
bool openSolverConfigurationFileDialog ()
Dialog for open a configuration file.
void registerUIMultizoneElements ()
This function register all the elements of the multizone interaface (buttons, editors, etc)
void removeDefaultValuesReadFromConfigFile ()
This function removes those variables loaded from the configuration file which value corresponds to the default value.
void removeMarkerElementsFromConfigFile ()
void resetBooleanValues ()
This function resets all the boolean variables of mainwindow.
void resetBoundaryValues ()
void resetMultizoneTable ()
void resetOldMarkerValues ()
Reset the marker values to their old values.
void resetSolverMenu ()
Reset the values of the menus of Solver to the default values.
void resetSolverTabEnabledElements ()
Reset of Solver tab elements to their default values.
void resetUserConfigurationValues ()
Reset the current values of the Solver configuration made by the user.
void runSimulation ()
SOLVER: run the simulation.
void runSolverProject ()
Run the current Solver project.
void runSolverProject (QString _projectPath)
bool saveConfigFile ()
Save helper function to save the configuration file and all the associated info.
void saveMeshVariables ()
SOLVER: Save Mesh variables values, changed by the user.
void seeParaviewResults ()
This internal function controls if the Paraview is opened passing a file or to open a new instance of Paraview.
void setEnableCloseProjectIcons (bool _val)
Disable the close project icons (at the moment only one)
void setEnabledInputTabSaveButtons (bool _val)
This function changes the disable/enable nature of the Physics button.
void setEnabledProjectIconButtons (bool _val)
This function is to enable of the different buttons according to _val for the user.
void setEnabledRunIcon (bool _val)
Activate the run elemenst (button and menu element9.
void setEnabledSaveConfigIcons (bool _val)
Activate the save Congifuration elements and save config as from the menu.
void setEnableSaveProjectIcons (bool _val)
Enable all the Save actions fo the project.
void setResidualPlot ()
RESIDUAL: restart the current simulation –> TODO.
void setUpStatusBar ()
Establish the main contents of the status bar (logo, labels, etc)
void stopSolverProcess ()
Stop current solver running process.
void updateBoundaryValues ()
SOLVER: function to update the values changed by the user in the mesh variables.
void updateMainWindowElements (QString _projectPath, bool _isNewProject, QString _finalPath)
This function update all the elements of the main window, restore the icons, etc.
void updateMeshView (QString _solverFilePath)
void updateMultizoneUserData (QString _configFile, QString _meshFile)
void updateProjectDataToFile ()
Update Project Data Paths.
void updateRecentProjectsSection ()
This function update the project list of the "recent project list" of the menu.
Private Attributes
QHash< QString, QString > _boundaryConfigValues
QHash< QString, QString > _boundaryMeshValues
InputDataTabHelper _inputDataTabHelper
bool _is3DMesh
bool _isMultizoneProject
bool _isNewConfigFile
MeshInfoVO _meshData
MeshDialog * _meshWindow
MultizoneManager _mManager
MultizoneProjectData _multizoneProjectData
QProcess * _myprocess
OutputSolverParser * _outputSolverParser
ProjectData _projectData
ProjectDetails _projectDetailsData
bool _projectExists
QTextEdit * _projectTextEditor
QList< QAction * > _recentProjectsList
QSignalMapper * _recentProjectsMapper
ResidualTabHelper * _residualTabHelper
SolverResidualVO * _residualVO
QProcess * _salomeLocationProccess
SolverConfigManager _solverManager
bool _status_NeedToBeSaved
bool _stopped
SummaryDialog * _summaryDialog
ProjectMenuTreeHelper _treeHelper
bool _updatedLegend
QHash< QString, QString > _userBoundaryValuesSolver
QHash< QString, QString > _userConfigValuesSolver
UserPreferencesData _userPreferencesData
QList< VirtualMrfVO > _userVirtualMRFDataList
QwtPlotCurve * curve
SolverPlotter * plotResiduals
QPolygonF points
Ui::MainWindow * ui
Detailed Description
Definition at line 41 of file mainwindow.h.
Member Enumeration Documentation
enum MainWindow::tabVariables private
Enumerator
tabInputData
tabMultizoneInputData
tabResidual
Definition at line 241 of file mainwindow.h.
                      {
         tabInputData = 0,
         tabMultizoneInputData =1,
         tabResidual = 2
     };
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 92 of file mainwindow.cpp.
References _inputDataTabHelper, _is3DMesh, _stopped, disableAllMainButtons(), InputDataTabHelper::hideAllSolverMenus(), initializeHelper(), initializeManagers(), initializeStructures(), initializeUserPreferences(), setResidualPlot(), setUpStatusBar(), and ui.
                                       :
     QMainWindow(parent),
     ui(new Ui::MainWindow)
 {
     ui->setupUi(this);
     // Initialize all Elements
     initializeHelper();
     initializeUserPreferences();
     initializeManagers();
     // Disable all elements
   _inputDataTabHelper.hideAllSolverMenus();
    disableAllMainButtons();
    initializeStructures();
    ui->actionSave_Temporal->setEnabled(false);
    ui->actionConfigurator->setEnabled(false);
    ui->actionResidual->setEnabled(false);
    // Set all the status
    setResidualPlot();
    setUpStatusBar();
    // set Boolean values
    _stopped = false;
    _is3DMesh = false;
   }
MainWindow::~MainWindow ()
Destructor.
Definition at line 138 of file mainwindow.cpp.
References _myprocess, _outputSolverParser, _projectTextEditor, _residualVO, and ui.
 {
     delete _projectTextEditor;
     delete _myprocess;
     delete _residualVO;
     delete _outputSolverParser;
     delete ui;
 }
Member Function Documentation
void MainWindow::addProjectToRecentProjectsSection (QString _projectPathName) private
This function add a new project to the "recent project list".
Parameters
_projectPathName
Definition at line 296 of file FileMenuHelper.cpp.
References _recentProjectsList, createRecentProjectAction(), StrEqual, and ui.
Referenced by updateMainWindowElements().
 {
     if (_projectPathName.isEmpty())
         return;
     if (ui->action_Empty->isVisible())
         ui->action_Empty->setVisible(false);
     // Update According
     bool _projectExist = false;
     int _pos = -1;
     for (int i = 0; (i < _recentProjectsList.size()) && (!_projectExist);i++)
     {
         QString _projectActionName = _recentProjectsList.at(i)->data().toString();
         if (QString::compare(_projectActionName,_projectPathName) == StrEqual)
         {
             _projectExist = true;
             _pos = i;
         }
     }
     QAction * _newRecentProjectAction = createRecentProjectAction(_projectPathName);
     if (!_projectExist)
     {
         if (_recentProjectsList.size() >= 10)
         {
             ui->menuRecent_Projects->removeAction(_recentProjectsList.at(0));
             _recentProjectsList.removeFirst();
         }
     }else
     {
         if (_pos != -1)
         {
             ui->menuRecent_Projects->removeAction(_recentProjectsList.at(_pos));
             _recentProjectsList.removeAt(_pos);
         }
     }
     _recentProjectsList.append(_newRecentProjectAction);
     ui->menuRecent_Projects->addAction(_newRecentProjectAction);
 }
QString MainWindow::buildSolverCommand () private
Function to build the solver Command according project conditions and user preferences.
Returns
QString
Definition at line 1261 of file mainwindow.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), getSolverCommand(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SPACE_TAB, and StrEqual.
Referenced by runSolverProject().
 {
     QString _processCommand;
     _processCommand += getSolverCommand();
     if (_isMultizoneProject)
     {
        QStringList _listConfig = _multizoneProjectData.getListConfigFileNames();
        QStringList _listMesh = _multizoneProjectData.getListMeshFileNames();
        // Choose the exact number of Config Files that matchs with the number of mesh files
        int _availableConfigFiles = _listConfig.size();
        if (_listConfig.size() > _listMesh.size())
             _availableConfigFiles = _listMesh.size();
        // Build the command with the Config file names
        for (int i = 0; i < _availableConfigFiles ;i++)
        {
            _processCommand += SPACE_TAB;
            _processCommand += _listConfig.at(i);
        }
     }else
     {
         QString _configFilePath = _projectData.getSolverDataInformation().getSolverConfigFilePath();
         if (QString::compare(_configFilePath,"") != StrEqual)
         {
             QFileInfo _configFileInfo(_configFilePath);
             QString _configFileName = _configFileInfo.fileName();
             _processCommand += SPACE_TAB;
             _processCommand += _configFileName;
          }
     }
     return _processCommand;
 }
void MainWindow::checkMeshNames () private
This function checks the mesh boundary names.
Definition at line 931 of file mainwindow.cpp.
References _boundaryMeshValues, _meshData, _projectData, _userConfigValuesSolver, SolverMarkerMenuHelper::checkMarkerMeshVariables(), WarningMultizoneDialog::getConfigValues(), MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), WarningMultizoneDialog::initializeFileNames(), WarningMultizoneDialog::isNeedToUpdate(), resetOldMarkerValues(), WarningMultizoneDialog::setConfigValues(), WarningMultizoneDialog::setMeshValueNames(), and WarningMultizoneDialog::userAcceptChanges().
Referenced by importMeshFile(), importMeshInfoFile(), and openSolverConfigurationFileDialog().
 {
     SolverMarkerMenuHelper _markerHelper;
     QString _configFilePath = _projectData.getSolverDataInformation().getSolverConfigFilePath();
     QString _meshFilePath = QDir(_meshData.getMeshPath()).filePath(_meshData.getMeshFileName());
             //_projectData.getSolverDataInformation().getSolverFilePath();
     if ((!_userConfigValuesSolver.isEmpty()) && (! _boundaryMeshValues.isEmpty()) )
     {
         bool _areEqual = _markerHelper.checkMarkerMeshVariables(_userConfigValuesSolver,_boundaryMeshValues);
         if (!_areEqual)
         {
             WarningMultizoneDialog  _warningDialog;
             _warningDialog.initializeFileNames(_configFilePath,_meshFilePath);
             _warningDialog.setConfigValues(_userConfigValuesSolver);
             _warningDialog.setMeshValueNames(_boundaryMeshValues);
             _warningDialog.exec();
             if (!_warningDialog.userAcceptChanges())
             {
                 resetOldMarkerValues();
             }
             else{
                 if ( (_warningDialog.userAcceptChanges()) && (_warningDialog.isNeedToUpdate()) )
                 {
                     _userConfigValuesSolver.clear();
                     _userConfigValuesSolver.insert("MESH_FILENAME",_meshFilePath);
                     _userConfigValuesSolver = _warningDialog.getConfigValues();
                 }else
                     resetOldMarkerValues();
             }
         }
     }
 }
void MainWindow::checkProjectBasePathConsistency (ProjectData * _openedProject, QString _currentFilePath) private
This function checks whether the path of the open project and the current project path is equal, if not, it updates it. It is used when we opened a project that has been created in a different computer (similar to import Project)
Parameters
_openedProject
_currentFilePath
Definition at line 201 of file mainwindow.cpp.
References _status_NeedToBeSaved, ProjectData::getProjectPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), ProjectData::setProjectPath(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), SolverVO::setSolverFilePath(), StrEqual, and TOOL4.
Referenced by openProject().
 {
     QString _projectPath = _openedProject->getProjectPath();
     QString _cRootPath = QFileInfo(QFileInfo(_currentFilePath).path()).path();
     if (_projectPath.isNull())
         return;
     QFileInfo _basePathInfo(_projectPath);
     QString _rootPath = _basePathInfo.path();
     QString _projectBaseName = _basePathInfo.fileName();
     if (QString::compare(_rootPath, _cRootPath) != StrEqual)
     {
         QString _updatedProjectPath = QDir(_cRootPath).filePath(_projectBaseName);
         _openedProject->setProjectPath(_updatedProjectPath);
         // Update the values of the solver files (config and mesh files)
         SolverVO _solverVO = _openedProject->getSolverDataInformation();
         if (!_solverVO.getSolverConfigFilePath().isEmpty())
         {
             QString _configFileName = QFileInfo(_solverVO.getSolverConfigFilePath()).fileName();
             QString _updatedConfigRootPath = QDir(QDir(_updatedProjectPath).filePath(TOOL4)).filePath(_configFileName);
             _solverVO.setSolverConfigFilePath(_updatedConfigRootPath);
         }
         if (!_solverVO.getSolverFilePath().isEmpty())
         {
             QString _meshFileName = QFileInfo(_solverVO.getSolverFilePath()).fileName();
             QString _updatedMeshRootPath = QDir(QDir(_updatedProjectPath).filePath(TOOL4)).filePath(_meshFileName);
             _solverVO.setSolverFilePath(_updatedMeshRootPath);
         }
         _openedProject->setSolverDataInformation(_solverVO);
         _status_NeedToBeSaved = true;
     }
 }
void MainWindow::clearAllData () private
Clear all the data to the default values.
Definition at line 1118 of file mainwindow.cpp.
References _meshData, _outputSolverParser, _projectData, _projectDetailsData, _projectExists, _projectTextEditor, _status_NeedToBeSaved, _userConfigValuesSolver, _userVirtualMRFDataList, ProjectDetails::clear(), MeshInfoVO::clear(), ProjectData::clear(), and resetBoundaryValues().
Referenced by closeProject().
 {
     // Project Data
     _projectData.clear();
     _projectDetailsData.clear();
     _meshData.clear();
     delete _projectTextEditor; // TO BE REVIEWED
     _projectTextEditor = new QTextEdit();
     _status_NeedToBeSaved = false;
     _projectExists = false;
     // Solver
      _userConfigValuesSolver.clear();
      resetBoundaryValues();
      /*_userBoundaryValuesSolver.clear();
      _boundaryMeshValues.clear();*/
      delete _outputSolverParser; // TO BE REVIEWED
      _outputSolverParser = new OutputSolverParser();
      _userVirtualMRFDataList.clear();
 }
void MainWindow::clearConsoleText () private
Clear the console text and removes all the text.
Definition at line 1023 of file mainwindow.cpp.
References ui.
Referenced by closeProject(), on_multizoneRunSimulationButton_clicked(), and runSimulation().
 {
     ui->textEdit->clear();
 }
void MainWindow::clearProjectTreeView () private
void MainWindow::closeEvent (QCloseEvent * event) protected
Function that controls the close event.
Parameters
event
Definition at line 1405 of file mainwindow.cpp.
References exitApplication().
 {
    bool _needToClose = exitApplication();
    if (!_needToClose)
        event->ignore();
 }
void MainWindow::closeExistentProject () private
This function does all teh actions required to close an existent project, reseting to default values, as well as stopping any existent simulation run.
Definition at line 182 of file mainwindow.cpp.
References _projectExists, closeProject(), resetSolverTabEnabledElements(), and stopSolverProcess().
Referenced by exitApplication(), on_actionClose_Project_triggered(), on_actionNew_Project_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionOpen_Project_triggered(), and openRecentFile().
 {
     if (_projectExists)
     {
         stopSolverProcess();
         closeProject();
         resetSolverTabEnabledElements();
         _projectExists = false;
     }
 }
void MainWindow::closeProject () private
Close Project function.
Definition at line 1044 of file mainwindow.cpp.
References _inputDataTabHelper, _isMultizoneProject, _mManager, _projectData, _residualVO, _salomeLocationProccess, _status_NeedToBeSaved, _treeHelper, SolverResidualVO::clearAllData(), clearAllData(), SolverPlotter::clearCanvas(), clearConsoleText(), ProjectMenuTreeHelper::clearProjectTreeView(), InputDataTabHelper::disableAllInputDataTab(), disableAllMainButtons(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), InputDataTabHelper::hideAllSolverMenus(), plotResiduals, resetBooleanValues(), SolverPlotter::resetLegend(), resetSolverMenu(), MultizoneManager::restoreTabViewToGeneralProject(), saveConfigFile(), setEnabledRunIcon(), ShowMessageHelper::showMessageForSaving(), and updateProjectDataToFile().
Referenced by closeExistentProject().
 {
     //ProjectMenuTreeHelper _treeHelper;
     bool _savedFile = true;
     if (_status_NeedToBeSaved)
     {
        ShowMessageHelper _showHelper;
        bool _saveResults = _showHelper.showMessageForSaving();
        if (_saveResults)
        {
            if (_isMultizoneProject)
            {
                if (!_projectData.getSolverDataInformation().getSolverConfigFilePath().isEmpty())
                    _savedFile = saveConfigFile();
                else
                {
                    updateProjectDataToFile();
                    _savedFile = true;
                }
             }else
                if ((_saveResults) && (_status_NeedToBeSaved))
                  _savedFile = saveConfigFile();
        }
     }
     if (_savedFile)
     {
         // Reset Multizone View
         if (_isMultizoneProject)
             _mManager.restoreTabViewToGeneralProject();
         // Clear All Data
         clearConsoleText();
         clearAllData();
         _treeHelper.clearProjectTreeView();//ui->projectTreeView);
         // Hide Disable
         _inputDataTabHelper.hideAllSolverMenus();
         _inputDataTabHelper.disableAllInputDataTab();
         disableAllMainButtons();
         // Set up boolean values
         resetBooleanValues();
         // Plot Actions
         plotResiduals->resetLegend(_residualVO);
         plotResiduals->clearCanvas();
         _residualVO->clearAllData();
         setEnabledRunIcon(false);
         resetSolverMenu();
         if (_salomeLocationProccess->pid() > 0)
             _salomeLocationProccess->kill();
     }
 }
void MainWindow::connectProcessSignalSlots () private
Connecting the Process Signal Slots.
Definition at line 1245 of file mainwindow.cpp.
References _myprocess, outlog(), slotFinishResult(), slotProcessError(), and slotStarted().
Referenced by initializeStructures().
 {
     connect(_myprocess, SIGNAL(readyReadStandardOutput()), this, SLOT(outlog()));
     connect(_myprocess, SIGNAL(error(QProcess::ProcessError)),
             this, SLOT(slotProcessError(QProcess::ProcessError)));
     connect(_myprocess,SIGNAL(finished(int,QProcess::ExitStatus)),this,
             SLOT(slotFinishResult(int, QProcess::ExitStatus)));
     connect(_myprocess,SIGNAL(started()),this,SLOT(slotStarted()));
     //connect(_myprocess, SIGNAL(readyReadStandardError()), this, SLOT(outlog()));
 }
void MainWindow::createProjectActions (QStringList _list) private
This function creates a new recent project action per each element of the list.
Parameters
_list
Definition at line 343 of file FileMenuHelper.cpp.
References _recentProjectsList, createRecentProjectAction(), and ui.
Referenced by updateRecentProjectsSection().
 {
     for (int i = 0; i < _list.size();i++)
     {
         QAction * _newRecentProjectAction = createRecentProjectAction(_list.at(i));
         _recentProjectsList.append(_newRecentProjectAction);
         ui->menuRecent_Projects->addAction(_newRecentProjectAction);
     }
 }
QAction * MainWindow::createRecentProjectAction (QString _name) private
This function creates the QAction for the "recent project list".
Parameters
_name
Returns
QAction
Definition at line 360 of file FileMenuHelper.cpp.
References openRecentFile().
Referenced by addProjectToRecentProjectsSection(), and createProjectActions().
 {
     QAction * _newRecentProjectAction = new QAction(this);
     _newRecentProjectAction->setText(_name );
     _newRecentProjectAction->setData(_name);
     _newRecentProjectAction->setVisible(true);
     connect(_newRecentProjectAction, SIGNAL(triggered()),this, SLOT(openRecentFile()));
     return _newRecentProjectAction;
 }
void MainWindow::disableAllMainButtons () private
Disable all the Tool Buttons.
Definition at line 997 of file mainwindow.cpp.
References ui.
Referenced by closeProject(), and MainWindow().
 {
     ui->salomeButton->setEnabled(false);
     ui->paraviewButton->setEnabled(false);
     ui->solverButton->setEnabled(false);
 }
void MainWindow::enableAllMainButtons () private
Enable all the Tool Buttons.
Definition at line 1008 of file mainwindow.cpp.
References ui.
Referenced by enableMultizoneElements(), enableToolButtons(), and updateMainWindowElements().
 {
     ui->salomeButton->setEnabled(true);
     ui->paraviewButton->setEnabled(true);
     ui->solverButton->setEnabled(true);
 }
void MainWindow::enableMeshOptions () private
This function enables the GUI mesh button and actions.
Definition at line 421 of file mainwindow.cpp.
References _projectData, ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), ProjectData::isEmpty(), and ui.
Referenced by on_importMeshFileButton_clicked(), and on_solverButton_clicked().
 {
     ui->actionImport_Mesh_File->setEnabled(true);
     if ( (!_projectData.isEmpty()) && (!_projectData.getSolverDataInformation().getSolverFilePath().isEmpty()) )
     {
         ui->setMeshPropertiesButton->setEnabled(true);
 //        ui->meshRefreshButton->setEnabled(true);
     }
 }
void MainWindow::enableMultizoneElements () private
This function controls the enabling of all the elements associated with the Multizone interface.
Definition at line 113 of file MultizoneTabHelper.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectExists, _status_NeedToBeSaved, enableAllMainButtons(), MultizoneProjectData::getProjectPath(), setEnableCloseProjectIcons(), setEnableSaveProjectIcons(), ShowMessageHelper::showMessage(), and ui.
Referenced by on_actionNew_Multizone_Project_triggered(), and on_actionOpen_Multizone_Project_triggered().
 {
     ShowMessageHelper _showHelper;
     _showHelper.showMessage("Open Multizone Project:"+ _multizoneProjectData.getProjectPath() , statusBar());
     _projectExists = true;
     _isMultizoneProject = true;
     setEnableCloseProjectIcons(true);
     enableAllMainButtons();
     if(_status_NeedToBeSaved)
         setEnableSaveProjectIcons(true);
     ui->restartButton->setEnabled(false);
     // Disable the Input Tab
     ui->solverTabwidget->setTabEnabled(0,false);
     ui->solverTabwidget->setTabEnabled(1,true);
 }
void MainWindow::enableSolverRunAction () private
Enable the action buttons for running the simulation according with the current status of the application and the configuration made by the user.
Definition at line 1674 of file mainwindow.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, MultizoneProjectData::isEmpty(), setEnabledRunIcon(), and ProjectData::solverDataComplete().
Referenced by on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), and on_savePhysicsButton_clicked().
 {
     if ((_isMultizoneProject) && (!_multizoneProjectData.isEmpty()))
     {
         setEnabledRunIcon(true);
     }else
         if (_projectData.solverDataComplete())
            setEnabledRunIcon(true);
 }
void MainWindow::enableToolButtons (int _buttonName) private
Enable correspondent Buttons and disable the one that is clicked.
Parameters
_buttonName
Definition at line 29 of file MainWindowHelper.cpp.
References _inputDataTabHelper, enableAllMainButtons(), InputDataTabHelper::hideAllSolverMenus(), Tool1Id, Tool3Id, Tool4Id, and ui.
Referenced by on_solverButton_clicked().
 {
     enableAllMainButtons();
     switch(_buttonName)
     {
         case (Tool1Id):
             ui->salomeButton->setEnabled(false);
             _inputDataTabHelper.hideAllSolverMenus();
             break;
         case(Tool3Id):
             ui->paraviewButton->setEnabled(false);
             _inputDataTabHelper.hideAllSolverMenus();
             break;
         case (Tool4Id):
             ui->solverButton->setEnabled(false);
             break;
     }
 }
bool MainWindow::exitApplication () private
This function controls the exit of the Application, to close everything and to save the data to the user preferences file if needed.
Returns
bool
Definition at line 252 of file FileMenuHelper.cpp.
References _userPreferencesData, closeExistentProject(), WarningClosingDialog::getShowAgainValue(), WarningClosingDialog::needsToCloseApplication(), PreferencesManager::saveUserPreferences(), UserPreferencesData::setShowCloseWarning(), and UserPreferencesData::showCloseWarning().
Referenced by closeEvent(), and on_actionExit_triggered().
 {
    bool _closeApplication = true;
    if (_userPreferencesData.showCloseWarning())
    {
        WarningClosingDialog _closingDialog;
        _closingDialog.exec();
        _closeApplication = _closingDialog.needsToCloseApplication();
        _userPreferencesData.setShowCloseWarning(_closingDialog.getShowAgainValue());
    }
    if (_closeApplication)
    {
        closeExistentProject();
         close();
    }
    PreferencesManager _prefManager;
    _prefManager.saveUserPreferences(_userPreferencesData);
    return _closeApplication;
 }
void MainWindow::fillMultizoneTable () private
Definition at line 134 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), insertMultizoneRow(), and ui.
Referenced by on_actionNew_Multizone_Project_triggered(), and on_actionOpen_Multizone_Project_triggered().
 {
     int _noFiles = _multizoneProjectData.getListConfigFileNames().size();
     QStringList _configFileNames = _multizoneProjectData.getListConfigFileNames();
     QStringList _meshFileNames = _multizoneProjectData.getListMeshFileNames();
     for (int i = 0; i < _noFiles;i++)
     {
         QString _meshName("");
         if (_meshFileNames.size()> i)
           _meshName = _meshFileNames.at(i);
          insertMultizoneRow(i,_configFileNames.at(i), _meshName);
     }
     ui->multizoneFilesTable->resizeColumnsToContents();
     ui->multizoneFilesTable->resizeRowsToContents();
 }
int MainWindow::getCurrentUserPreferences () private
This function returns which type of Solver Engine is defined.
Returns
int
Definition at line 113 of file EditMenuHelper.cpp.
References _userPreferencesData, DefaultSolverOption, UserPreferencesData::isDefaultSolverEngineSelected(), UserPreferencesData::isMultizoneSolverEngineSelected(), UserPreferencesData::isVirtualSolverEngineSelected(), MultizoneSolverOption, and VirtualSolverOption.
 {
     if (_userPreferencesData.isDefaultSolverEngineSelected())
         return DefaultSolverOption;
     if (_userPreferencesData.isVirtualSolverEngineSelected())
         return VirtualSolverOption;
     if (_userPreferencesData.isMultizoneSolverEngineSelected())
         return MultizoneSolverOption;
     return -1;
 }
void MainWindow::getLoadedBoundaryValues () private
load the Boundary values
Definition at line 1619 of file mainwindow.cpp.
References _userBoundaryValuesSolver, _userConfigValuesSolver, BC_PREFIX, and MARKER_PREFIX.
Referenced by loadMeshDialog(), on_newActionButton_clicked(), and on_openFileActionButton_clicked().
 {
     if (!_userConfigValuesSolver.isEmpty())
     {
         QHashIterator<QString,QString> _iter(_userConfigValuesSolver);
         while (_iter.hasNext())
         {
             _iter.next();
             QString _keyVal = _iter.key();
             QString _val = _iter.value();
             if( (!_keyVal.isEmpty()) && (!_val.isEmpty()) )
                 if (( (_keyVal.contains(MARKER_PREFIX)) ||
                      (_keyVal.contains(BC_PREFIX))) &&
                     (!_val.contains("NONE") ) )
                 {
                     if (_val.contains("("))
                         _val.remove("(");
                     if (_val.contains(")"))
                         _val.remove(")");
                     _userBoundaryValuesSolver.insert(_keyVal,_val);
                 }
         }
     }
 }
void MainWindow::getSalomePathSlot () private slot
This function is the one capable of locating the Salome path in the client side.
Definition at line 71 of file ViewMenuHelper.cpp.
References _salomeLocationProccess, _userPreferencesData, UserPreferencesData::setMeshViewerPath(), and slotProcessError().
Referenced by initializeStructures().
 {
     QString _pathSalomeBin = _salomeLocationProccess->readAllStandardOutput();
     _userPreferencesData.setMeshViewerPath(_pathSalomeBin);
     QProcess * _runSalome = new QProcess(this) ;
     connect(_runSalome, SIGNAL(error(QProcess::ProcessError)),
             this, SLOT(slotProcessError(QProcess::ProcessError)));
     _runSalome->start(_pathSalomeBin);
 }
QList< int > MainWindow::getSelectedFiles () private
Definition at line 261 of file MultizoneTabHelper.cpp.
References configFileSelected, and ui.
Referenced by on_multizoneDeleteButton_clicked(), and on_multizoneOpenEditButton_clicked().
 {
     int _totalRows = ui->multizoneFilesTable->rowCount();
     QList<int> _selectedElements;
     for (int i= 0; i< _totalRows;i++)
     {
        if (ui->multizoneFilesTable->item(i,configFileSelected)->checkState() == Qt::Checked)
            _selectedElements.append(i);
     }
     return _selectedElements;
 }
QString MainWindow::getSolverCommand () private
This function decides which Solver running executable is going to be called. At the moment there are 3 options: SU2_CFD, SU2_CFD_VMRF, SU2_CFD_MULTIZONE.
Parameters
_solver
Returns
QString
Definition at line 1302 of file mainwindow.cpp.
References _isMultizoneProject, _userConfigValuesSolver, _userPreferencesData, UserPreferencesData::getUserDefinedSolverPath(), UserPreferencesData::isDefaultSolverEngineSelected(), UserPreferencesData::isMultizoneSolverEngineSelected(), UserPreferencesData::isVirtualSolverEngineSelected(), SOLVER_MULTIZONE_RUN_COMMAND, SOLVER_RUN_COMMAND, SOLVER_VIRTUAL_RUN_COMMAND, and StrEqual.
Referenced by buildSolverCommand().
 {
     QString _command;
     _command = SOLVER_RUN_COMMAND;
     // If the user chooses a local Engine, this is the priority
     if  ( (!_userPreferencesData.isDefaultSolverEngineSelected()) && (!_userPreferencesData.isVirtualSolverEngineSelected()) &&
           (!_userPreferencesData.isMultizoneSolverEngineSelected()) && (!_userPreferencesData.getUserDefinedSolverPath().isEmpty()) )
         return _userPreferencesData.getUserDefinedSolverPath();
     // Now the rest of the options can be analised
     if ((_isMultizoneProject) || (_userPreferencesData.isMultizoneSolverEngineSelected()) )
         return SOLVER_MULTIZONE_RUN_COMMAND;
     if (!_userConfigValuesSolver.isEmpty())
     {
         QString _val = _userConfigValuesSolver.value("VIRTUAL_ROTATING_FRAME");
         if ((!_val.isEmpty()) && (QString::compare(_val, "YES") == StrEqual) )
             return SOLVER_VIRTUAL_RUN_COMMAND;
     }
     if (_userPreferencesData.isDefaultSolverEngineSelected())
         return SOLVER_RUN_COMMAND;
     if (_userPreferencesData.isVirtualSolverEngineSelected())
         return SOLVER_VIRTUAL_RUN_COMMAND;
     return _command;
 }
void MainWindow::importMeshFile () private
Definition at line 1491 of file mainwindow.cpp.
References _projectData, _status_NeedToBeSaved, ProjectData::getProjectPath(), importMeshInfoFile(), MESH_CONFIG_SUFFIX, saveMeshVariables(), StrEqual, and TOOL4.
Referenced by on_actionImport_Mesh_File_triggered(), and on_importMeshFileButton_clicked().
 {
     // Check if mesh config information exists, otherwise import file and create mesh config information
     MeshInfoFileReader _meshInfoHelper;
     QString _meshConfigFile = QFileDialog::getOpenFileName(this, tr("Import SU2 Mesh File or Configuration Mesh File"),
                                                             QDir(_projectData.getProjectPath()).filePath(TOOL4),
                                                             tr("Mesh File s(*.su2 *.meshcfg)"));
     if (_meshConfigFile.isNull())
          return;
    bool _isMeshInfo = false;
    if (QString::compare(QFileInfo(_meshConfigFile).completeSuffix(),MESH_CONFIG_SUFFIX) == StrEqual)
        _isMeshInfo = true;
     if (_isMeshInfo)
         importMeshInfoFile(_meshConfigFile);
     else
         importMeshFile(_meshConfigFile);
     saveMeshVariables();
     _status_NeedToBeSaved = true;
 }
void MainWindow::importMeshFile (QString _meshConfigFile) private
Dialog for importing a mesh file.
Definition at line 878 of file mainwindow.cpp.
References _boundaryMeshValues, _inputDataTabHelper, _is3DMesh, _meshData, _projectData, _userConfigValuesSolver, _userVirtualMRFDataList, checkMeshNames(), ProjectData::getProjectPath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), IS_3D_MESH_TAG, MESH_CONFIG_SUFFIX, InputDataTabHelper::parseFile(), ParserSolverMeshFile, MeshInfoVO::saveMeshInfoFile(), MeshInfoVO::set3DMesh(), MeshInfoVO::setBoundaryNameList(), MeshInfoVO::setMeshDetailsFileName(), MeshInfoVO::setMeshFileName(), MeshInfoVO::setMeshPath(), ProjectData::setSolverDataInformation(), SolverVO::setSolverFilePath(), SOLVER_DIR_NAME, SolverUtil::uiImportSolverMeshFile(), and updateMeshView().
 {
     SolverUtil _solverUtil;
     SolverVO _resultSolver = _solverUtil.uiImportSolverMeshFile(_meshConfigFile,_projectData);
     SolverVO _storedSolverData = _projectData.getSolverDataInformation();
     _storedSolverData.setSolverFilePath(_resultSolver.getSolverFilePath());
     this->_projectData.setSolverDataInformation(_storedSolverData);
     // Loading the Mesh Values
     _inputDataTabHelper.parseFile(ParserSolverMeshFile,_resultSolver.getSolverFilePath(),&_userConfigValuesSolver,
               &_boundaryMeshValues,&_userVirtualMRFDataList);
     if (_boundaryMeshValues.contains(IS_3D_MESH_TAG))
     {
         _is3DMesh = true;
         _boundaryMeshValues.remove(IS_3D_MESH_TAG);
     }
     checkMeshNames();
     //________________________________________________________________________________________________________________
     // Saving Mesh information
     _meshData.set3DMesh(_is3DMesh);
     _meshData.setBoundaryNameList(_boundaryMeshValues);
     _meshData.setMeshPath(QFileInfo(_meshConfigFile).absolutePath());
     _meshData.setMeshFileName(QFileInfo(_meshConfigFile).fileName());
     QString _meshfileName =  QFileInfo(_meshConfigFile).baseName() + "." + MESH_CONFIG_SUFFIX;
     QString _meshDetailsFileName = QDir(QDir(_projectData.getProjectPath()).filePath(SOLVER_DIR_NAME)).filePath(_meshfileName);
     _meshData.setMeshDetailsFileName(_meshDetailsFileName);
     _meshData.saveMeshInfoFile();
     //________________________________________________________________________________________________________________
     updateMeshView(_resultSolver.getSolverFilePath());
 }
void MainWindow::importMeshInfoFile (QString _file) private
Definition at line 853 of file mainwindow.cpp.
References _boundaryMeshValues, _is3DMesh, _meshData, _projectData, checkMeshNames(), MeshInfoVO::getBoundaryNameListMap(), MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), ProjectData::getProjectPath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), MeshInfoVO::is3DMesh(), MESH_CONFIG_SUFFIX, MeshInfoFileReader::readMeshInfo(), MeshInfoVO::saveMeshInfoFile(), MeshInfoVO::setMeshDetailsFileName(), TOOL4, SolverUtil::uiImportSolverMeshFile(), and updateMeshView().
Referenced by importMeshFile().
 {
     QString _meshFileInfoPath = QDir(QDir(_projectData.getProjectPath()).filePath(TOOL4)).filePath(
                 QString(QFileInfo(_file).baseName() + "." + MESH_CONFIG_SUFFIX)  );
     MeshInfoFileReader _meshHelper;
     _meshHelper.readMeshInfo(_file,&_meshData);
     _is3DMesh = _meshData.is3DMesh();
     _boundaryMeshValues = _meshData.getBoundaryNameListMap();
     _meshData.setMeshDetailsFileName(_meshFileInfoPath);
     QString _meshPath = QDir(_meshData.getMeshPath()).filePath(_meshData.getMeshFileName());
     // Creating the link to the mesh
     SolverUtil _solverUtil;
     _solverUtil.uiImportSolverMeshFile(_meshPath,_projectData);
     _meshData.saveMeshInfoFile();
    // _solverUtil.uiImportSolverMeshInfoFile(_file,_projectData);
     checkMeshNames();
     updateMeshView(_projectData.getSolverDataInformation().getSolverFilePath());
 }
void MainWindow::initializeHelper () private
This fucntion initalize all the data of the Tab helper, like button registration and so on.
Definition at line 27 of file HelpMenuHelper.cpp.
References _inputDataTabHelper, _treeHelper, InputDataTabHelper::registerButtons(), InputDataTabHelper::registerLineEdits(), ProjectMenuTreeHelper::registerMenuTree(), InputDataTabHelper::registerTab(), and ui.
Referenced by MainWindow().
 {
     _inputDataTabHelper.registerButtons(ui->basivViewEditButton,
                          ui->seeSummaryChangesButton,  ui->runSimulationButton,
                          ui->restartButton);
     _inputDataTabHelper.registerLineEdits(ui->configFileLineLabel,ui->meshFileLineLabel);
     _inputDataTabHelper.registerTab(ui->solverTabwidget);
     // Initialize TreeViewHelper
     _treeHelper.registerMenuTree(ui->projectTreeView);
 }
void MainWindow::initializeManagers () private
Initialize Solver manager, user Preferences data manager.
Definition at line 123 of file mainwindow.cpp.
References _solverManager, _userPreferencesData, UserPreferencesData::getTemplateConfigPath(), SolverConfigManager::initializeManager(), SolverConfigManager::isInitialized(), and SolverConfigManager::loadPersonalizedTemplate().
Referenced by MainWindow().
 {
     // Initialize Solver Manager
     if (!_solverManager.isInitialized())
         _solverManager.initializeManager();
     if (!_userPreferencesData.getTemplateConfigPath().isEmpty())
         _solverManager.loadPersonalizedTemplate(_userPreferencesData.getTemplateConfigPath());
 }
void MainWindow::initializeStructures () private
Initialize Main Window structures.
Definition at line 750 of file mainwindow.cpp.
References _myprocess, _outputSolverParser, _projectTextEditor, _residualVO, _salomeLocationProccess, connectProcessSignalSlots(), getSalomePathSlot(), resetBooleanValues(), and slotProcessError().
Referenced by MainWindow().
 {
     // Editor & QProcess
      _projectTextEditor = new QTextEdit();
      _myprocess = new QProcess(this);
      _salomeLocationProccess = new QProcess(this);
      _residualVO = new SolverResidualVO();
      _outputSolverParser = new OutputSolverParser();
      resetBooleanValues();
    // Connecting signals
       connectProcessSignalSlots();
      connect(_salomeLocationProccess, SIGNAL(readyReadStandardOutput()),this,SLOT(getSalomePathSlot()));
      connect(_salomeLocationProccess, SIGNAL(error(QProcess::ProcessError)),this, SLOT(slotProcessError(QProcess::ProcessError)));
 }
void MainWindow::initializeUserPreferences () private
This function initialize the variables associated with user preferences.
Definition at line 128 of file EditMenuHelper.cpp.
References _userPreferencesData, PreferencesManager::getUserPreferences(), and updateRecentProjectsSection().
Referenced by MainWindow().
 {
     PreferencesManager _prefManager;
     _userPreferencesData = _prefManager.getUserPreferences();
     // Updating the Recent Files Area
     updateRecentProjectsSection();
 }
void MainWindow::insertMultizoneRow (int _pos, QString _configName, QString _meshName) private
Definition at line 155 of file MultizoneTabHelper.cpp.
References QtableUtil::addNonEditableText(), QtableUtil::addSelectableCheckColumn(), configFileName, configFileSelected, meshFileName, and ui.
Referenced by fillMultizoneTable(), and on_multizoneNewButton_clicked().
 {
     QtableUtil _tableUtil;
     ui->multizoneFilesTable->insertRow(_pos);
     ui->multizoneFilesTable->setItem(_pos,configFileSelected,_tableUtil.addSelectableCheckColumn());
     ui->multizoneFilesTable->setItem(_pos,configFileName,_tableUtil.addNonEditableText(_configName));
     ui->multizoneFilesTable->setItem(_pos,meshFileName,_tableUtil.addNonEditableText(_meshName));
 }
void MainWindow::launchActionProjectSettingsDialog () private
This function controls the launching of the Project Settings Dialog.
Definition at line 36 of file EditMenuHelper.cpp.
References _inputDataTabHelper, _isMultizoneProject, _mManager, _multizoneProjectData, _projectData, _projectDetailsData, _status_NeedToBeSaved, _userConfigValuesSolver, SolverVO::clear(), MultizoneProjectData::getListConfigFiles(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::isConfigFileEmpty(), ProjectData::isEmpty(), SolverVO::isMeshFileEmpty(), EditHelper::launchSettingsDialog(), MultizoneManager::refreshSimulationFilesView(), resetBoundaryValues(), setEnableSaveProjectIcons(), ui, MultizoneManager::updateConfigFileNameinTabView(), InputDataTabHelper::updateConfigurationFilePathInActionGroup(), and MultizoneManager::updateMeshFileNameinTabView().
Referenced by on_actionProject_Settings_triggered(), and on_projectTreeView_doubleClicked().
 {
     EditHelper _editHelper;
     bool _userMadeChanges = _editHelper.launchSettingsDialog(_isMultizoneProject,&_multizoneProjectData,&_projectData,&_projectDetailsData);
     if (_userMadeChanges)
     {
         bool _needToRemoveMaps = false;
         if (!_isMultizoneProject)
         {
            // _projectData =  _settingsDialog.getProjectData();
             if (_projectData.getSolverDataInformation().isConfigFileEmpty())
             {
                _inputDataTabHelper.updateConfigurationFilePathInActionGroup("");
                ui->meshFileLineLabel->setText("");
                _userConfigValuesSolver.remove("MESH_FILENAME");
              // If we remove the configuration file we MUST remove the associated mesh file and their values
                if (!_projectData.getSolverDataInformation().isMeshFileEmpty())
                    _projectData.getSolverDataInformation().clear();
               _needToRemoveMaps = true;
             }
         }
         else
         {
            // Refresh the Multizone Project Data
            _mManager.refreshSimulationFilesView(&_multizoneProjectData);
            QString _openProject;
            if (!_projectData.isEmpty())
                _openProject = _projectData.getSolverDataInformation().getSolverConfigFilePath();
             QStringList _listConfigFiles = _multizoneProjectData.getListConfigFiles();
             // We must remove all the data only in the case that the opened project has been removed by the user
             if (!_listConfigFiles.contains(_openProject))
             {
                 _needToRemoveMaps = true;
                 // Restore the view names
                 _mManager.updateConfigFileNameinTabView("");
                 _mManager.updateMeshFileNameinTabView("");
             }
         }
         if (_needToRemoveMaps)
         {
             _userConfigValuesSolver.clear();
             resetBoundaryValues();
             /*_userBoundaryValuesSolver.clear();
             _boundaryMeshValues.clear();*/
             // Disable the elements of the menu
             ui->basivViewEditButton->setEnabled(false);
             //ui->meshRefreshButton->setEnabled(false);
             ui->setMeshPropertiesButton->setEnabled(false);
             ui->savePhysicsButton->setEnabled(false);
             ui->seeSummaryChangesButton->setEnabled(false);
         }
         // Enabling the values
         setEnableSaveProjectIcons(true);
         _status_NeedToBeSaved = true;
     }
 }
void MainWindow::launchSalomeMeshTool () private
This internal function controls how to launch the Salome tool, specially due to the path of this tool (not in traditional Linux paths like usr/bin). So, with this function we locate the path to Salome to run it.
Definition at line 35 of file ViewMenuHelper.cpp.
References _projectData, _salomeLocationProccess, _solverManager, _userPreferencesData, UserPreferencesData::getMeshViewerPath(), ProjectData::getProjectPath(), MeshingToolConfigurationWarningDialog::initializeStructures(), slotProcessError(), and TOOL4.
Referenced by on_actionSalome_Mesh_triggered(), and on_salomeButton_clicked().
 {
    // Step 1. Set up the working directory in the project
    QString _workingDir = QDir(_projectData.getProjectPath()).filePath(TOOL4);
    _salomeLocationProccess->setWorkingDirectory(_workingDir);
    // Esto no funciona --> Revisar ...
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    env.insert("WORKINGDIR", _workingDir); // Add an environment variable
    _salomeLocationProccess->setProcessEnvironment(env);
    // Step 2. Launch Mesh Tool
  //  QString _command = "export WORKINGDIR=\"" +_workingDir +"\"; echo $WORKINGDIR";//+
    QString _command = _userPreferencesData.getMeshViewerPath();
    // By default for Salome tools
    if ( (_command.isNull()) || (_command.isEmpty()) )
    {
        // There is no configuration for the Salome Mesher. The user shall provide the location of the executable
         MeshingToolConfigurationWarningDialog _meshingWarning;
         _meshingWarning.initializeStructures(&_userPreferencesData,&_solverManager);
         _meshingWarning.exec();
         return;
    }
     QProcess * _runSalome = new QProcess(this) ;
     connect(_runSalome, SIGNAL(error(QProcess::ProcessError)),
              this, SLOT(slotProcessError(QProcess::ProcessError)));
     _runSalome->start(_command);
 }
void MainWindow::loadMeshDialog () private
SOLVER: funtion to load the MESH dialog.
Definition at line 1544 of file mainwindow.cpp.
References _boundaryMeshValues, _isMultizoneProject, _meshWindow, _solverManager, _status_NeedToBeSaved, _userBoundaryValuesSolver, _userConfigValuesSolver, getLoadedBoundaryValues(), MeshDialog::getUserBndVariableValues(), MeshDialog::hasUserAcceptChanges(), MeshDialog::loadMenu(), setEnabledProjectIconButtons(), MeshDialog::setIsMultizoneProject(), MeshDialog::setIsNSProblem(), MeshDialog::setMeshValues(), MeshDialog::setSolverConfigManager(), MeshDialog::setUserConfiguredMeshValues(), StrEqual, and updateBoundaryValues().
Referenced by on_setMeshPropertiesButton_clicked().
 {
     if (_userBoundaryValuesSolver.isEmpty())
         getLoadedBoundaryValues();
     _meshWindow = new MeshDialog(this);
     _meshWindow->setMeshValues(_boundaryMeshValues);
     _meshWindow->setSolverConfigManager(&_solverManager);
     _meshWindow->setUserConfiguredMeshValues(_userBoundaryValuesSolver); //TBR
     _meshWindow->setIsMultizoneProject(_isMultizoneProject);
     bool _isNSProblem = false;
     if (!_userConfigValuesSolver.isEmpty())
     {
         QString _physicalPbVal = _userConfigValuesSolver.value("PHYSICAL_PROBLEM");
         if (QString::compare(_physicalPbVal,"NAVIER_STOKES") == StrEqual)
             _isNSProblem = true;
         else _isNSProblem = false;
     }
     _meshWindow->setIsNSProblem(_isNSProblem);
     _meshWindow->loadMenu();
     _meshWindow->exec();
     if (_meshWindow->hasUserAcceptChanges())
     {
         _userBoundaryValuesSolver = _meshWindow->getUserBndVariableValues();
         updateBoundaryValues();
         _status_NeedToBeSaved = true;
         setEnabledProjectIconButtons(true);
     }
 }
void MainWindow::multizoneSaveAll () private
Definition at line 330 of file MultizoneTabHelper.cpp.
References _status_NeedToBeSaved, MultizoneIndividualTabForm::getConfigFile(), MultizoneIndividualTabForm::getConfigValues(), MultizoneIndividualTabForm::getMeshFile(), MultizoneIndividualTabForm::getVirtualValues(), MultizoneIndividualTabForm::isDataModified(), MultizoneIndividualTabForm::savedData(), saveMultizoneData(), ShowMessageHelper::showWarningMessage(), and ui.
Referenced by on_multizoneRunSimulationButton_clicked(), and on_multizoneSaveAllButton_clicked().
 {
     int _noTabs = ui->solverTabwidget->count();
     QList<int> _indexTabsToSave;
     if (_noTabs > 3)
     {
         for (int i=3; i < _noTabs;i++)
         {
            MultizoneIndividualTabForm * _indivTab = qobject_cast<MultizoneIndividualTabForm *>(ui->solverTabwidget->widget(i));
            if (_indivTab)
            {
                if (_indivTab->isDataModified())
                    _indexTabsToSave.append(i);
            }
         }
         if (_indexTabsToSave.isEmpty())
             return;
         // Show a message per each Tab
         ShowMessageHelper _msgHelper;
         bool _saveAll = _msgHelper.showWarningMessage("Modified Values in the Zones!","Warning! There unsaved in the files you have open. Do you want to save all of them?");
         if (!_saveAll)
             return;
         for (int i=0; i < _indexTabsToSave.size();i++)
         {
             MultizoneIndividualTabForm * _indivTab = qobject_cast<MultizoneIndividualTabForm *>
                     (ui->solverTabwidget->widget(_indexTabsToSave.at(i)));
             if (_indivTab)
             {
                 saveMultizoneData(_indivTab->getConfigFile(), _indivTab->getMeshFile(),_indivTab->getConfigValues(),_indivTab->getVirtualValues());
                 _indivTab->savedData();
             }
         }
         _status_NeedToBeSaved = false;
     }
 }
bool MainWindow::notSavedMultizoneData () private
Definition at line 310 of file MultizoneTabHelper.cpp.
References _status_NeedToBeSaved, MultizoneIndividualTabForm::isDataModified(), and ui.
Referenced by on_multizoneRunSimulationButton_clicked(), and on_multizoneSaveAllButton_clicked().
 {
     if (_status_NeedToBeSaved)
         return true;
     int _noTabs = ui->solverTabwidget->count();
     if (_noTabs > 3)
     {
         for (int i=3; i < _noTabs;i++)
         {
            MultizoneIndividualTabForm * _indivTab = qobject_cast<MultizoneIndividualTabForm *>(ui->solverTabwidget->widget(i));
            if (_indivTab)
            {
                if (_indivTab->isDataModified())
                    return true;
            }
         }
     }
     return false;
 }
void MainWindow::on_actionAbout_triggered () private slot
About us.
Definition at line 94 of file HelpMenuHelper.cpp.
 {
     AboutUsDialog _aboutDialog;
     _aboutDialog.exec();
 }
void MainWindow::on_actionAutomatic_Optimization_triggered () private slot
This function is to create automatic mesh using Salome but with optimization parameters.
Definition at line 39 of file ToolsMenuHelper.cpp.
References _projectData, _userPreferencesData, and ToolsHelper::createAutomaticMeshWithOptimization().
 {
     ToolsHelper _meshGenerationHelper;
     _meshGenerationHelper.createAutomaticMeshWithOptimization( _projectData, _userPreferencesData);
 }
void MainWindow::on_actionClose_Project_triggered () private slot
CLOSE a Project.
Definition at line 213 of file FileMenuHelper.cpp.
References _projectExists, _userPreferencesData, closeExistentProject(), WarningClosingDialog::getShowAgainValue(), WarningClosingDialog::needsToCloseApplication(), setEnableCloseProjectIcons(), setEnableSaveProjectIcons(), UserPreferencesData::setShowCloseProjectWarning(), WarningClosingDialog::setTitleMessage(), UserPreferencesData::showCloseProjectWarning(), and ui.
 {
     if (_projectExists)
     {
         bool _needToClose = true;
         if (_userPreferencesData.showCloseProjectWarning())
         {
            WarningClosingDialog _closingDialog;
            _closingDialog.setTitleMessage("You are about to close the current Project");
            _closingDialog.exec();
            _needToClose = _closingDialog.needsToCloseApplication();
            _userPreferencesData.setShowCloseProjectWarning(_closingDialog.getShowAgainValue());
         }
         if (_needToClose)
         {
            closeExistentProject();
            setEnableSaveProjectIcons(false);
            setEnableCloseProjectIcons(false);
            ui->solverTabwidget->setCurrentIndex(0);
            ui->menuSalome_Tools->setEnabled(false);
         }
     }
 }
void MainWindow::on_actionCompare_Configuration_Files_triggered () private slot
this funciton controls the compare Configuration file action
Definition at line 124 of file SolverMenuHelper.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, _projectDetailsData, _solverManager, _userVirtualMRFDataList, and SolverHelper::launchFileComparisonDialog().
 {
     SolverHelper _solverHelper;
     _solverHelper.launchFileComparisonDialog(_isMultizoneProject,_multizoneProjectData, _projectData,
                                                        _solverManager, _projectDetailsData,
                                                       _userVirtualMRFDataList);
 }
void MainWindow::on_actionCreate_Configuration_Template_triggered () private slot
This function is for creating customized templates for the configuration menus.
Definition at line 156 of file SolverMenuHelper.cpp.
References _solverManager, and SolverHelper::createConfigurationTemplateByUser().
 {
     SolverHelper _solverHelper;
     _solverHelper.createConfigurationTemplateByUser(&_solverManager);
 }
void MainWindow::on_actionDeveloper_Guide_2_triggered () private slot
This action shows the html documentation of the tool.
This action shows the PDF documentation of the tool
Definition at line 63 of file HelpMenuHelper.cpp.
References HelpManager::openHelp().
 {
     HelpManager _helpManager;
     _helpManager.openHelp("developerGuide.pdf","pdf");
 }
void MainWindow::on_actionEdit_Configuration_Template_triggered () private slot
This function allows to edit existing configuration templates.
Definition at line 167 of file SolverMenuHelper.cpp.
References _solverManager, and SolverHelper::editConfigurationTemplateByUser().
 {
     SolverHelper _solverHelper;
     _solverHelper.editConfigurationTemplateByUser(this,&_solverManager);
 }
void MainWindow::on_actionExit_triggered () private slot
Function that controls the exit of the application.
Definition at line 243 of file FileMenuHelper.cpp.
References exitApplication().
 {
     exitApplication();
 }
void MainWindow::on_actionHelp_Contents_triggered () private slot
This function launchs the Qt Assistant for showing the help of BBIPED.
Definition at line 43 of file HelpMenuHelper.cpp.
References HelpManager::openQtAssistant().
 {
     HelpManager _helpManager;
     _helpManager.openQtAssistant();
 }
void MainWindow::on_actionImport_Mesh_File_triggered () private slot
Import Mesh file.
Definition at line 27 of file SolverMenuHelper.cpp.
References _status_NeedToBeSaved, importMeshFile(), resetOldMarkerValues(), saveMeshVariables(), and setEnabledProjectIconButtons().
 {
     resetOldMarkerValues();
     importMeshFile();
     saveMeshVariables();
     _status_NeedToBeSaved = true;
     setEnabledProjectIconButtons(true);
 }
void MainWindow::on_actionLoad_Configuration_Template_triggered () private slot
This function allows to load specific configuration template.
Definition at line 178 of file SolverMenuHelper.cpp.
References _solverManager, _userPreferencesData, and SolverHelper::loadConfigurationTemplateByUser().
 {
     SolverHelper _solverHelper;
     _solverHelper.loadConfigurationTemplateByUser(this,&_solverManager,&_userPreferencesData);
 }
void MainWindow::on_actionLoad_Templates_triggered () private slot
This function is to create automatic mesh using Salome.
Definition at line 27 of file ToolsMenuHelper.cpp.
References _projectData, _userPreferencesData, ToolsHelper::createAutomaticMesh(), and ui.
 {
     ToolsHelper _meshGenerationHelper;
     _meshGenerationHelper.createAutomaticMesh(ui->textEdit,_projectData, _userPreferencesData);
 }
void MainWindow::on_actionNew_Multizone_Project_triggered () private slot
This function is to control the action of defining a new Multizone project.
Definition at line 67 of file MultizoneTabHelper.cpp.
References _mManager, _multizoneProjectData, _projectData, _userPreferencesData, enableMultizoneElements(), fillMultizoneTable(), MultizoneManager::isUIRegistered(), MultizoneManager::launchMultizoneDialog(), registerUIMultizoneElements(), and resetMultizoneTable().
 {
     if (!_mManager.isUIRegistered())
         registerUIMultizoneElements();
     bool _isMultizoneProjectCreated = _mManager.launchMultizoneDialog(&_multizoneProjectData,&_userPreferencesData,&_projectData);
     if (_isMultizoneProjectCreated)
     {
         resetMultizoneTable();
         enableMultizoneElements();
         fillMultizoneTable();
     }
 }
void MainWindow::on_actionNew_Project_triggered () private slot
Create a New Project.
Definition at line 33 of file FileMenuHelper.cpp.
References _projectData, closeExistentProject(), UtilFiles::createProjectStructure(), UtilFiles::getFinalPath(), ProjectData::saveProjectInformation(), ShowMessageHelper::showMessage(), ShowMessageHelper::showMessageWindow(), and updateMainWindowElements().
 {
     bool _fileCreated = false;
     ShowMessageHelper _showHelper;
     closeExistentProject();
     while (!_fileCreated)
     {
         // Creating the dialog for asking the user for the project name
         QString projectPath = QFileDialog::getSaveFileName(this, tr("Create Project File"),QCoreApplication::applicationDirPath(),
                                    //QDir::currentPath(),
                                    tr("Solver Project (*.prj)"));
         // Conditions: (1) Check that this project does not exist --> Otherwise warning
         //             (2) If everything is ok --> Create project folder structure
         //                  projectName --> Folder
         //                  projectName.prj --> Project File Name
         //                  Other folders --> Tool1, Tool2, Tool3, Solver
         if (projectPath.isNull())
         {
             // Button Cancel is pressed, so whe go out from this function
             return;
         }
         UtilFiles _utilFiles;
         // Creating all the project structure
         _fileCreated = _utilFiles.createProjectStructure(projectPath);
         if (!_fileCreated)
         {
             QString _title(tr("Error Creating the new project") );
             QString _message(tr("If this project already exists. Please, select a different name. Otherwise, check your writing rights in the folder"));
             _showHelper.showMessageWindow(_title,_message,this);
         }
         else
         {
             QFileInfo _qFileInfo( _utilFiles.getFinalPath());
             this->_projectData.saveProjectInformation(_utilFiles.getFinalPath());
             _showHelper.showMessage("Project:"+ _utilFiles.getFinalPath(),statusBar());
             // Updating the values in the GUI
             updateMainWindowElements(_qFileInfo.absolutePath(),true,_utilFiles.getFinalPath());
         }
     }
 }
void MainWindow::on_actionOnline_Help_triggered () private slot
This action shows the html help.
Definition at line 84 of file HelpMenuHelper.cpp.
References HelpManager::openHelp().
 {
     HelpManager _helpManager;
     _helpManager.openHelp("index.html","html");
 }
void MainWindow::on_actionOpen_Multizone_Project_triggered () private slot
This funciton opens a Multizone project.
Definition at line 87 of file MultizoneTabHelper.cpp.
References _mManager, _multizoneProjectData, _projectData, _projectDetailsData, _status_NeedToBeSaved, _userPreferencesData, closeExistentProject(), enableMultizoneElements(), fillMultizoneTable(), MultizoneManager::isUIRegistered(), MultizoneManager::openMultizoneProject(), registerUIMultizoneElements(), and resetMultizoneTable().
 {
     closeExistentProject();
     resetMultizoneTable();
     if (!_mManager.isUIRegistered())
         registerUIMultizoneElements();
     QString _projectFilePath = QFileDialog::getOpenFileName(this, tr("Open Multizone Project File"),
                                                             QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                                                             tr("Multizone Solver Project (*.mprj)"));
     if (_projectFilePath.isNull())
         // Button Cancel Pressed
         return;
     _status_NeedToBeSaved =  _mManager.openMultizoneProject(_projectFilePath,&_multizoneProjectData,&_userPreferencesData,&_projectData,&_projectDetailsData);
     enableMultizoneElements();
     fillMultizoneTable();
 }
void MainWindow::on_actionOpen_Project_triggered () private slot
Open a Project.
Definition at line 89 of file FileMenuHelper.cpp.
References closeExistentProject(), and openProject().
 {
     closeExistentProject();
     QString _projectFilePath = QFileDialog::getOpenFileName(this, tr("Open Project File"),QCoreApplication::applicationDirPath(),
                                                             //QDir::currentPath(),
                                                             tr("Solver Project (*.prj)"));
     if (_projectFilePath.isNull())
             return;
     openProject(_projectFilePath);
 }
void MainWindow::on_actionParaview_File_triggered () private slot
Launching the paraview application.
Definition at line 87 of file ViewMenuHelper.cpp.
References seeParaviewResults().
 {
     seeParaviewResults();
 }
void MainWindow::on_actionPreferences_triggered () private slot
This method controls the Preference dialog launch.
Definition at line 101 of file EditMenuHelper.cpp.
References _solverManager, _userPreferencesData, and EditHelper::launchPreferencesDialog().
 {
     EditHelper _editHelper;
     _editHelper.launchPreferencesDialog(&_userPreferencesData, &_solverManager);
 }
void MainWindow::on_actionProject_Settings_triggered () private slot
This funciton controls the project settings action.
Definition at line 27 of file EditMenuHelper.cpp.
References launchActionProjectSettingsDialog().
 {
     launchActionProjectSettingsDialog();
 }
void MainWindow::on_actionRun_Project_triggered () private slot
Run Solver Project.
Definition at line 39 of file SolverMenuHelper.cpp.
References _isMultizoneProject, _status_NeedToBeSaved, _userConfigValuesSolver, runSimulation(), and StrEqual.
 {
     if (!_isMultizoneProject)
     {
         if (_userConfigValuesSolver.isEmpty())
             return;
         // Checking if RESTART_SOL is enabled
        if ( (_userConfigValuesSolver.contains("RESTART_SOL")) &&
             (QString::compare(_userConfigValuesSolver.value("RESTART_SOL"),"NO") != StrEqual) )
         {
                 _userConfigValuesSolver.insert("RESTART_SOL","NO");
                 _status_NeedToBeSaved = true;
         }
     }
     runSimulation();
 }
void MainWindow::on_actionSalome_Mesh_triggered () private slot
This action is the Menu action for lauching Salome.
Definition at line 26 of file ViewMenuHelper.cpp.
References launchSalomeMeshTool().
 {
     launchSalomeMeshTool();
 }
void MainWindow::on_actionSave_As_triggered () private slot
SAVE AS a Project.
Definition at line 136 of file FileMenuHelper.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, _projectDetailsData, _projectExists, _status_NeedToBeSaved, _treeHelper, UtilFiles::copyAllToolData(), UtilFiles::createMultizoneProjectStructure(), UtilFiles::createProjectStructure(), ProjectMenuTreeHelper::fillProjectTreeView(), UtilFiles::getFinalPath(), ProjectData::saveProjectInformation(), setEnableSaveProjectIcons(), MultizoneProjectData::setProjectName(), MultizoneProjectData::setProjectPath(), ShowMessageHelper::showMessage(), UtilFiles::updateMultizoneProjectDataToFile(), UtilFiles::updateMultizoneToolPaths(), UtilFiles::updateProjectDataToFile(), and UtilFiles::updateToolPaths().
 {
     if (_projectExists)
     {
         QString filename;
         if (!_isMultizoneProject)
             filename = QFileDialog::getSaveFileName( this, tr("Save Project As"),QCoreApplication::applicationDirPath(),// QDir::currentPath(),
                                tr("Project Document name (*.prj)") );
         else
             filename = QFileDialog::getSaveFileName( this, tr("Save Multizone Project As"),QCoreApplication::applicationDirPath(),// QDir::currentPath(),
                                tr("Project Document name (*.mprj)") );
         if( filename.isNull() )
          return;
         UtilFiles _utilFiles;
         bool _projectCreated;
         if (!_isMultizoneProject)
             _projectCreated =  _utilFiles.createProjectStructure(filename);
         else
            _projectCreated =  _utilFiles.createMultizoneProjectStructure(filename);
         // Copy all the files from origin to new location and update in accordance
         if (_projectCreated)
         {
             QFileInfo _qFileInfo(_utilFiles.getFinalPath());
             if (!_isMultizoneProject)
             {
                 ProjectData _newProjectData;
                 _newProjectData.saveProjectInformation(_utilFiles.getFinalPath());
                 _utilFiles.copyAllToolData(this->_projectData,_newProjectData);
                 _projectData = _utilFiles.updateToolPaths(_projectData,_newProjectData);
                 _utilFiles.updateProjectDataToFile(_projectData, _projectDetailsData);
             }else{
                 // TO BE REVIEWED
                 MultizoneProjectData _newMultizoneProjectData ;
                 _newMultizoneProjectData.setProjectPath(_qFileInfo.path());
                 _newMultizoneProjectData.setProjectName(_qFileInfo.baseName());
                 _utilFiles.copyAllToolData(_multizoneProjectData,_newMultizoneProjectData);
                _multizoneProjectData = _utilFiles.updateMultizoneToolPaths(_multizoneProjectData,_newMultizoneProjectData);
                 _utilFiles.updateMultizoneProjectDataToFile(_newMultizoneProjectData,_projectDetailsData);
             }
             _status_NeedToBeSaved = false;
             setEnableSaveProjectIcons(false);
             // Updating the Status Bar
             ShowMessageHelper _showHelper;
            _showHelper.showMessage("Project:"+ _utilFiles.getFinalPath(),statusBar());
            // Fill the Project tree view
           _treeHelper.fillProjectTreeView(_qFileInfo.absolutePath());//,ui->projectTreeView);
         }
     }
 }
void MainWindow::on_actionSave_Configuration_File_As_triggered () private slot
SOLVER: Main functionality to save the changes of the configuration file with a different name.
Definition at line 87 of file SolverMenuHelper.cpp.
References _isMultizoneProject, _isNewConfigFile, _mManager, _multizoneProjectData, _projectData, _status_NeedToBeSaved, enableSolverRunAction(), ProjectData::getProjectPath(), ProjectData::getSolverDataInformation(), saveConfigFile(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), TOOL4, ui, and MultizoneManager::updateOpenEditConfigFile().
 {
     QString filename = QFileDialog::getSaveFileName(
                 this,
                 tr("Save Solver Configuration File As"),
                      QDir(_projectData.getProjectPath()).filePath(TOOL4),
                 tr("Configuration File name (*.cfg)") );
     QString _fileName = QFileInfo(filename).fileName();
     QString _fileExt = QFileInfo(filename).suffix();
     if (_fileExt.isEmpty())
         _fileName = _fileName +".cfg";
     QString _newFileConfigPath = QDir (QDir(_projectData.getProjectPath()).filePath(TOOL4)).filePath(_fileName);
     SolverVO _solver = _projectData.getSolverDataInformation();
     _solver.setSolverConfigFilePath(_newFileConfigPath);
     _projectData.setSolverDataInformation(_solver);
     if (_isMultizoneProject)
         _mManager.updateOpenEditConfigFile(_newFileConfigPath, &_multizoneProjectData,&_projectData, _isNewConfigFile);
    // Saving the Configuration File
    bool _savedFile = saveConfigFile();
    if (_savedFile)
    {
         _status_NeedToBeSaved = false;
         setEnableSaveProjectIcons(_status_NeedToBeSaved);
         setEnabledSaveConfigIcons(_status_NeedToBeSaved);
         ui->savePhysicsButton->setEnabled(_status_NeedToBeSaved);
         enableSolverRunAction();
    }
 }
void MainWindow::on_actionSave_Configuration_File_triggered () private slot
SOLVER: Main functionality to save the changes of the configuration file.
Definition at line 70 of file SolverMenuHelper.cpp.
References _status_NeedToBeSaved, enableSolverRunAction(), saveConfigFile(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), and ui.
 {
     bool _savedFile = saveConfigFile();
     if (_savedFile)
     {
         enableSolverRunAction();
         setEnableSaveProjectIcons(_status_NeedToBeSaved);
         setEnabledSaveConfigIcons(_status_NeedToBeSaved);
         ui->savePhysicsButton->setEnabled(_status_NeedToBeSaved);
     }
 }
void MainWindow::on_actionSave_Residual_Image_triggered () private slot
This function allows to save the residual image generated in a simulation.
Definition at line 147 of file SolverMenuHelper.cpp.
References SolverPlotter::exportPlot(), and plotResiduals.
 {
     plotResiduals->exportPlot();
 }
void MainWindow::on_actionSave_Temporal_triggered () private slot
SAVE TEMPORAL –> TODO.
Definition at line 197 of file FileMenuHelper.cpp.
References _projectExists, and ShowMessageHelper::showMessageWindow().
 {
     ShowMessageHelper _showHelper;
     if (_projectExists)
     {
         QString filename = QFileDialog::getSaveFileName( this, tr("Save Project in a Temporal"), QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                tr("Temporal Project (*.tmp.prj)") );
            if( !filename.isNull() )
              _showHelper.showMessageWindow("Temporal Saving","Pending Implementation",this);
     }
      _showHelper.showMessageWindow("Temporal Saving","Pending Implementation",this);
 }
void MainWindow::on_actionSave_triggered () private slot
Save a Project.
Definition at line 104 of file FileMenuHelper.cpp.
References _isMultizoneProject, _projectData, _projectExists, _status_NeedToBeSaved, ProjectData::isEmpty(), saveConfigFile(), setEnableSaveProjectIcons(), and updateProjectDataToFile().
 {
     // Note: In this case, we are going to save only the associated project
     // documents of each tool.
     if((_projectExists) && (_status_NeedToBeSaved))
     {
         if ((!_isMultizoneProject))
         {
          bool _savedFile = saveConfigFile();
          if (_savedFile)
             setEnableSaveProjectIcons(false);
         }else
         {
             if (!_projectData.isEmpty())
             {
                 bool _savedFile = saveConfigFile();
                 if (_savedFile)
                    setEnableSaveProjectIcons(false);
             }else{
                 updateProjectDataToFile();
                 _status_NeedToBeSaved = false;
             }
         }
     }
 }
void MainWindow::on_actionStop_Execution_triggered () private slot
Stop current simulation.
Definition at line 61 of file SolverMenuHelper.cpp.
References stopSolverProcess().
 {
     stopSolverProcess();
 }
void MainWindow::on_actionSynchronise_all_files_triggered () private slot
This function controls the synchronise file action.
Definition at line 135 of file SolverMenuHelper.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, _projectDetailsData, _solverManager, _userVirtualMRFDataList, and SolverHelper::launchFileComparisonDialog().
 {
     SolverHelper _solverHelper;
     _solverHelper.launchFileComparisonDialog(_isMultizoneProject,_multizoneProjectData, _projectData,
                                                        _solverManager, _projectDetailsData,
                                                       _userVirtualMRFDataList);
 }
void MainWindow::on_actionUser_GuideLine_2_triggered () private slot
This action shows the PDF user guide documentation.
Definition at line 74 of file HelpMenuHelper.cpp.
References HelpManager::openHelp().
 {
     HelpManager _helpManager;
     _helpManager.openHelp("userGuideline.pdf","pdf");
 }
void MainWindow::on_basivViewEditButton_clicked () private slot
SOLVER: Main functionality to show the basic configuration view for the Physics config menu.
Definition at line 1459 of file mainwindow.cpp.
References _inputDataTabHelper, _is3DMesh, _solverManager, _status_NeedToBeSaved, _userConfigValuesSolver, _userVirtualMRFDataList, InputDataTabHelper::launchSolverConfigDialog(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), and ui.
 {
    bool _needToSave =  _inputDataTabHelper.launchSolverConfigDialog(this,true,&_userConfigValuesSolver,
                                             &_solverManager,&_userVirtualMRFDataList,_is3DMesh);
    if (_needToSave)
    {
        _status_NeedToBeSaved = true;
        setEnableSaveProjectIcons(_status_NeedToBeSaved);
        setEnabledSaveConfigIcons(_status_NeedToBeSaved);
        ui->savePhysicsButton->setEnabled(_status_NeedToBeSaved);
    }
 }
void MainWindow::on_importMeshFileButton_clicked () private slot
SOLVER: Import mesh file button.
Definition at line 1482 of file mainwindow.cpp.
References _status_NeedToBeSaved, enableMeshOptions(), importMeshFile(), and setEnabledProjectIconButtons().
 {
     importMeshFile();
     _status_NeedToBeSaved = true;
     setEnabledProjectIconButtons(true);
     enableMeshOptions();
 }
void MainWindow::on_multizoneDeleteButton_clicked () private slot
Definition at line 273 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, _status_NeedToBeSaved, configFileName, MultizoneProjectData::getProjectPath(), getSelectedFiles(), meshFileName, MultizoneProjectData::removeConfigFile(), MultizoneProjectData::removeMeshFile(), and ui.
 {
     QList<int> _selRows = getSelectedFiles();
     if (_selRows.isEmpty())
         return;
     for (int i = _selRows.size()-1; i>=0;i--)
     {
         // Update the Multizone Project Information
         QString _configFile = QDir(_multizoneProjectData.getProjectPath()).
                 filePath(ui->multizoneFilesTable->item(_selRows.at(i),configFileName)->text());
         QString _meshFile  = QDir(_multizoneProjectData.getProjectPath()).
                 filePath(ui->multizoneFilesTable->item(_selRows.at(i),meshFileName)->text());
         _multizoneProjectData.removeConfigFile(_configFile);
         _multizoneProjectData.removeMeshFile(_meshFile);
         ui->multizoneFilesTable->removeRow(_selRows.at(i));
     }
     _status_NeedToBeSaved = true;
 }
void MainWindow::on_multizoneNewButton_clicked () private slot
Definition at line 174 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, MultizoneSelectFilesDialog::getConfigFilePath(), MultizoneSelectFilesDialog::getMeshFilePath(), MultizoneProjectData::getProjectPath(), MultizoneSelectFilesDialog::hasSelectedFiles(), insertMultizoneRow(), MultizoneSelectFilesDialog::setProjectPath(), ui, and updateMultizoneUserData().
 {
     // Launch Menu Dialog for selecting the Configuration File and the Mesh File
     MultizoneSelectFilesDialog _multiZoneSelectFilesDialog;
     _multiZoneSelectFilesDialog.setProjectPath(_multizoneProjectData.getProjectPath());
     _multiZoneSelectFilesDialog.exec();
     if (!_multiZoneSelectFilesDialog.hasSelectedFiles())
         return;
     QString _configFile = _multiZoneSelectFilesDialog.getConfigFilePath();
     QString _meshFile = _multiZoneSelectFilesDialog.getMeshFilePath();
     if (_configFile.isEmpty()) return;
     // Update the MultizoneObject
     updateMultizoneUserData(_configFile,_meshFile);
     // Add the data into the table
     insertMultizoneRow(ui->multizoneFilesTable->rowCount(),QFileInfo(_configFile).fileName(),
                        QFileInfo(_meshFile).fileName());
 }
void MainWindow::on_multizoneOpenEditButton_clicked () private slot
Definition at line 234 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, _solverManager, configFileName, MultizoneProjectData::getProjectPath(), getSelectedFiles(), meshFileName, MultizoneIndividualTabForm::registerInitialStructures(), MultizoneIndividualTabForm::setConfigFile(), MultizoneIndividualTabForm::setMeshFile(), MultizoneIndividualTabForm::setProjectPath(), TOOL4, and ui.
 {
     QList<int> _selRows = getSelectedFiles();
     if (_selRows.isEmpty())
         return;
     QString _projectPath =  QDir(_multizoneProjectData.getProjectPath()).filePath(TOOL4);
     for (int i = 0; i < _selRows.size();i++)
     {
         QString _configFileName = ui->multizoneFilesTable->item(_selRows.at(i),configFileName)->text();
         QString _meshFileName = ui->multizoneFilesTable->item(_selRows.at(i),meshFileName)->text();
         MultizoneIndividualTabForm * _newTab = new MultizoneIndividualTabForm(ui->solverTabwidget);
         _newTab->setProjectPath(_projectPath);
         _newTab->setConfigFile(QDir(_projectPath).filePath(_configFileName));
         _newTab->setMeshFile(QDir(_projectPath).filePath(_meshFileName));
         // TODO --> Tengo que cargar y leer cada configuration file y su correspondientes boundary variables
         _newTab->registerInitialStructures(this,&_solverManager);
         ui->solverTabwidget->addTab(_newTab,_configFileName);
         ui->solverTabwidget->setTabsClosable(true);
     }
     // Put the focus on the last tab open
     int _lastTab = ui->solverTabwidget->count();
     ui->solverTabwidget->setCurrentIndex(_lastTab-1);
 }
void MainWindow::on_multizoneRestartSimulation_clicked () private slot
Definition at line 394 of file MultizoneTabHelper.cpp.
 {
     // TODO --> TO BE confirmed before the logic in the restart in BBIPED!
 }
void MainWindow::on_multizoneRunSimulationButton_clicked () private slot
Definition at line 369 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, clearConsoleText(), MultizoneProjectData::getProjectPath(), multizoneSaveAll(), notSavedMultizoneData(), runSolverProject(), tabResidual, and ui.
 {
     clearConsoleText();
     // Check if we need to save the Status
     if (notSavedMultizoneData())
         multizoneSaveAll();
     // Run the project
     runSolverProject(_multizoneProjectData.getProjectPath());
     ui->multizoneRunSimulationButton->setEnabled(false);
     ui->solverTabwidget->setCurrentIndex(tabResidual);
 }
void MainWindow::on_multizoneSaveAllButton_clicked () private slot
Definition at line 302 of file MultizoneTabHelper.cpp.
References multizoneSaveAll(), and notSavedMultizoneData().
 {
    if (notSavedMultizoneData())
         multizoneSaveAll();
 }
void MainWindow::on_multizoneStopSimulationButton_clicked () private slot
Definition at line 388 of file MultizoneTabHelper.cpp.
References _myprocess.
 {
     if (_myprocess->pid() > 0)
         _myprocess->kill();
 }
void MainWindow::on_multizoneSummaryAllConfigButton_clicked () private slot
Definition at line 293 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, _solverManager, MultizoneProjectData::getListConfigFiles(), MultizoneProjectData::getProjectPath(), MultizoneSummaryDialog::setConfigFileList(), MultizoneSummaryDialog::setProjectPath(), and MultizoneSummaryDialog::setSolverManager().
 {
     MultizoneSummaryDialog _multizoneSummary;
     _multizoneSummary.setProjectPath(_multizoneProjectData.getProjectPath());
     _multizoneSummary.setConfigFileList(_multizoneProjectData.getListConfigFiles());
     _multizoneSummary.setSolverManager(&_solverManager);
     _multizoneSummary.exec();
 }
void MainWindow::on_newActionButton_clicked () private slot
SOLVER: Create New configuration file.
Definition at line 325 of file mainwindow.cpp.
References _inputDataTabHelper, _isMultizoneProject, _isNewConfigFile, _mManager, _multizoneProjectData, _projectData, _projectDetailsData, _status_NeedToBeSaved, _userBoundaryValuesSolver, InputDataTabHelper::enableConfigurationViewMenu(), getLoadedBoundaryValues(), ProjectData::getProjectPath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), UtilFiles::hasFileExtension(), OptionMzConfigPath, OptionMzMeshPath, resetBoundaryValues(), resetUserConfigurationValues(), setEnabledRunIcon(), setEnabledSaveConfigIcons(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), ShowMessageHelper::showWarningMessage(), TOOL4, ui, InputDataTabHelper::updateConfigurationFilePathInActionGroup(), MultizoneManager::updateMeshFileNameinTabView(), MultizoneManager::updateViewForNewFile(), and SolverConfigWriter::writeToConfigurationFile().
 {
     bool _fileCreated = false;
     while (!_fileCreated)
     {
         QString _configPath = QFileDialog::getSaveFileName(this, tr("Create New Configuration File"),
                                     QDir(_projectData.getProjectPath()).filePath(TOOL4),
                                    tr("Configuration File (*.cfg)"));
         if (_configPath.isNull())
         {
             // Button Cancel is pressed, so whe go out from this function
             return;
         }
         // Importing the Mesh File is needed
        resetUserConfigurationValues();
         // Writing the initial Configuration File
         SolverConfigWriter _writer;
         QDomDocument * _emptyTree = new QDomDocument();
         UtilFiles _utilFiles;
         if (!_utilFiles.hasFileExtension(_configPath,"cfg"))
                    _configPath =  _configPath + ".cfg";
         _writer.writeToConfigurationFile(_configPath, _emptyTree, _projectDetailsData);
         // Updating the Configuration File info in the project Data
         SolverVO _solverVO = _projectData.getSolverDataInformation();
         _solverVO.setSolverConfigFilePath(_configPath);
         _projectData.setSolverDataInformation(_solverVO);
         // Enabling correspondent bool values
         _fileCreated = true;
         _status_NeedToBeSaved = true;
         _isNewConfigFile = true;
         _inputDataTabHelper.enableConfigurationViewMenu(_projectData);
        setEnabledRunIcon(ui->runSimulationButton->isEnabled());
        setEnabledSaveConfigIcons(true);
        ui->savePhysicsButton->setEnabled(true);
        if (!_userBoundaryValuesSolver.isEmpty())
        {
            _userBoundaryValuesSolver.clear();
             getLoadedBoundaryValues();
        }
        // Updating Values
        if (!_isMultizoneProject)
            _inputDataTabHelper.updateConfigurationFilePathInActionGroup(_configPath);
        else
        {
            _mManager.updateViewForNewFile(_configPath, OptionMzConfigPath,&_multizoneProjectData,
                                           &_projectData, _isNewConfigFile);
            // If a mesh file has been already opened, ask the user to keep the values or not
            if (!_projectData.getSolverDataInformation().getSolverFilePath().isEmpty())
            {
                ShowMessageHelper _showMessage;
                bool _keepMeshValues = _showMessage.showWarningMessage("Mesh Information",
                                        "A boundary configuration already exists. Do you want to keep the old boundary configuration?");
                if (_keepMeshValues)
                   _mManager.updateViewForNewFile(_projectData.getSolverDataInformation().getSolverFilePath(),
                                                   OptionMzMeshPath,&_multizoneProjectData,&_projectData,
                                                   _isNewConfigFile);
                else
                {
                    // Reset the values from Mesh file
                    _projectData.getSolverDataInformation().clear();
                    _projectData.getSolverDataInformation().setSolverConfigFilePath(_configPath);
                    _mManager.updateMeshFileNameinTabView("");
                    // Reset the values for the boundaries
                    resetBoundaryValues();
                }
            }
        }
     }
 }
void MainWindow::on_openFileActionButton_clicked () private slot
SOLVER: Open existent configuration file in the current project folder.
Definition at line 451 of file mainwindow.cpp.
References _inputDataTabHelper, _isMultizoneProject, _isNewConfigFile, _projectData, _status_NeedToBeSaved, _userBoundaryValuesSolver, InputDataTabHelper::enableChangeConfigActionMenu(), getLoadedBoundaryValues(), ProjectData::getSolverDataInformation(), SolverVO::isConfigFileEmpty(), SolverVO::isMeshFileEmpty(), openSolverConfigurationFileDialog(), removeDefaultValuesReadFromConfigFile(), saveConfigFile(), setEnabledSaveConfigIcons(), and ui.
 {
     if ( (_status_NeedToBeSaved) && (_isMultizoneProject) && (!_projectData.getSolverDataInformation().isConfigFileEmpty())
          && (!_projectData.getSolverDataInformation().isMeshFileEmpty()) )
            saveConfigFile();
     if (openSolverConfigurationFileDialog())
     {
         removeDefaultValuesReadFromConfigFile();
         _inputDataTabHelper.enableChangeConfigActionMenu();
         //_inputDataTabHelper.enableSimulationFileEdits();
         _status_NeedToBeSaved = true;
         _isNewConfigFile = false; // TBR
         setEnabledSaveConfigIcons(true);
         ui->savePhysicsButton->setEnabled(true);
         if (!_userBoundaryValuesSolver.isEmpty())
         {
             _userBoundaryValuesSolver.clear();
              getLoadedBoundaryValues();
         }
     }
 }
void MainWindow::on_paraviewButton_clicked () private slot
This function launchs the Paraview tool from the button click.
Definition at line 110 of file MainWindowHelper.cpp.
References seeParaviewResults().
 {
     seeParaviewResults();
 }
void MainWindow::on_projectTreeView_doubleClicked (const QModelIndex & _index) private slot
This function allow to open in a tab a configuration file or any text file with supported extensions.
Parameters
_index
Definition at line 58 of file MainWindowHelper.cpp.
References _projectTextEditor, _treeHelper, launchActionProjectSettingsDialog(), MULTIZONE_PROJECT_FILE_EXT, ProjectMenuTreeHelper::openFileInTabFromClickedElement(), SOLVER_PROJECT_FILE_EXT, StrEqual, and ui.
 {
   QFileSystemModel * _model = (QFileSystemModel *) ui->projectTreeView->model();
   QFileInfo _file = _model->fileInfo(_index);
   if( (_file.exists()) && (!_file.isDir()) &&  (_file.isFile()) )
           if ( ((QString::compare(_file.suffix(),SOLVER_PROJECT_FILE_EXT) == StrEqual))
                ||((QString::compare(_file.suffix(),MULTIZONE_PROJECT_FILE_EXT) == StrEqual)) )
       launchActionProjectSettingsDialog();
    else
    {
           _projectTextEditor = new QTextEdit(this);
          // ProjectMenuTreeHelper _treeHelper;
           _treeHelper.openFileInTabFromClickedElement(_file,_projectTextEditor,ui->solverTabwidget);
           //QSyntaxHighlighter * _highlighter = new QSyntaxHighlighter(_projectTextEditor->document());
     }
 }
void MainWindow::on_restartButton_clicked () private slot
SOLVER: If restart option is allowed, restart simulation.
Definition at line 558 of file mainwindow.cpp.
References _projectData, _residualVO, _status_NeedToBeSaved, _userConfigValuesSolver, SolverResidualVO::clearAllData(), SolverPlotter::clearCanvas(), ProjectData::getProjectPath(), plotResiduals, runSimulation(), StrEqual, and WarningRestartDialog::userAcceptToRestart().
 {
     plotResiduals->clearCanvas();
     _residualVO->clearAllData();
     if (_userConfigValuesSolver.isEmpty())
         return;
     // Checking if RESTART_SOL is enabled
     // If not --> Warning Message to know if it is worthy to continue
     if ( (!_userConfigValuesSolver.contains("RESTART_SOL")) ||
         ( (_userConfigValuesSolver.contains("RESTART_SOL")) &&
          (QString::compare(_userConfigValuesSolver.value("RESTART_SOL"),"YES") != StrEqual) ) )
     {
         WarningRestartDialog * _warningRestartDialog = new WarningRestartDialog(this);
         _warningRestartDialog->exec();
         if (_warningRestartDialog->userAcceptToRestart())
         {
             _userConfigValuesSolver.insert("RESTART_SOL","YES");
             _status_NeedToBeSaved = true;
         }else
             return;
     }
     // Ask for the file
     QString _selectedRestartFile = QFileDialog::getOpenFileName(this, tr("Select the file to be used to restart the simulation."),
                                                                 _projectData.getProjectPath(),
                                                             tr("All files(*)"));
     if (_selectedRestartFile.isNull())
             return;
     // Parse the file name
     QFileInfo _fileInfo(_selectedRestartFile);
     QStringList _noIteration = (_fileInfo.completeBaseName()).split("-");
     QString _restartValue("");
     // We need to get the number of iteration that it is in the shape of
     // solution-flow.dat-10.dat --> And we need the 10
     if (_noIteration.size() > 0)
         _restartValue =  _noIteration.at(_noIteration.size()-1);
      _userConfigValuesSolver.insert("RESTART_SOL",QString("YES").append(",").append(_restartValue));
      _status_NeedToBeSaved = true;
     // Running the simulation
      runSimulation();
 /*
     if (!_userConfigValuesSolver.contains("RESTART_SOL"))
     {
         //TODO ASK the user to select the file
         // Parse the file name and get the number
         //QString _restartYesVal = "YES" +
         _userConfigValuesSolver.insert("RESTART_SOL","YES");
         _status_NeedToBeSaved = true;
     }
     else
         if ( (_userConfigValuesSolver.contains("RESTART_SOL")) &&
             (QString::compare(_userConfigValuesSolver.value("RESTART_SOL"),"YES") != StrEqual) )
         {
                 _userConfigValuesSolver.insert("RESTART_SOL","YES");
                 _status_NeedToBeSaved = true;
         }
     // Getting the user file Names
     QString _restartFileName;
     QString _solutionFileName;
     if (_userConfigValuesSolver.contains("RESTART_FLOW_FILENAME"))
     {
         _restartFileName = _userConfigValuesSolver.value("RESTART_FLOW_FILENAME");
         if (_restartFileName.isEmpty())
             _restartFileName = "restart_flow.dat";
     }
     if (_userConfigValuesSolver.contains("SOLUTION_FLOW_FILENAME"))
     {
         _solutionFileName = _userConfigValuesSolver.value("SOLUTION_FLOW_FILENAME");
         if (_solutionFileName.isEmpty())
             _solutionFileName = "solution_flow.dat";
     }
      // Copying the restart flow data into the solution one
    UtilFiles _utilFiles;
    QString _filePath = _projectData.getProjectPath();
    _filePath = QDir(_filePath).filePath(TOOL4);
    _filePath = QDir(_filePath).filePath(_restartFileName);
    _utilFiles.copyFileToNewName(_filePath,_solutionFileName);
    // Running the simulation
     runSimulation();
     */
 }
void MainWindow::on_runSimulationButton_clicked () private slot
SOLVER: Run the current simulation.
Definition at line 658 of file mainwindow.cpp.
References _isMultizoneProject, _status_NeedToBeSaved, _userConfigValuesSolver, runSimulation(), and StrEqual.
 {
     if (!_isMultizoneProject)
     {
         if (_userConfigValuesSolver.isEmpty())
             return;
         // Checking if RESTART_SOL is enabled
        if ( (_userConfigValuesSolver.contains("RESTART_SOL")) &&
             (QString::compare(_userConfigValuesSolver.value("RESTART_SOL"),"NO") != StrEqual) )
         {
                 _userConfigValuesSolver.insert("RESTART_SOL","NO");
                 _status_NeedToBeSaved = true;
         }
     }
     runSimulation();
 }
void MainWindow::on_salomeButton_clicked () private slot
This function launchs the Salome tool.
Definition at line 121 of file MainWindowHelper.cpp.
References launchSalomeMeshTool().
 {
     // Check if Salome is set up
     launchSalomeMeshTool();
 }
void MainWindow::on_savePhysicsButton_clicked () private slot
Save Physics button functionality, it saves all the information (including the boundaries into a single configuration file.
Definition at line 1652 of file mainwindow.cpp.
References _status_NeedToBeSaved, enableSolverRunAction(), removeDefaultValuesReadFromConfigFile(), saveConfigFile(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), and ui.
 {
     bool _savedFile = saveConfigFile();
     // Remove the default values
     if (_savedFile)
     {
         removeDefaultValuesReadFromConfigFile();
         setEnableSaveProjectIcons(_status_NeedToBeSaved);
         setEnabledSaveConfigIcons(_status_NeedToBeSaved);
         ui->savePhysicsButton->setEnabled(_status_NeedToBeSaved);
         if (!_status_NeedToBeSaved)
              enableSolverRunAction();
     }
 }
void MainWindow::on_seeSummaryChangesButton_clicked () private slot
SOLVER: Shows the user input for the configuration file.
Definition at line 529 of file mainwindow.cpp.
References _solverManager, _status_NeedToBeSaved, _summaryDialog, _userConfigValuesSolver, SummaryDialog::buildSummaryTable(), SolverConfigManager::getAllSectionMenuList(), removeDefaultValuesReadFromConfigFile(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), SummaryDialog::setSectionMenuList(), SummaryDialog::setValuesToShow(), ui, and SummaryDialog::userHasMadeChanges().
 {
     _summaryDialog = new SummaryDialog(this);
     removeDefaultValuesReadFromConfigFile();
     _summaryDialog->setValuesToShow(&_userConfigValuesSolver);
     _summaryDialog->setSectionMenuList(_solverManager.getAllSectionMenuList());
     _summaryDialog->buildSummaryTable();
     _summaryDialog->exec();
     if (_summaryDialog->userHasMadeChanges())
     {
         _status_NeedToBeSaved = true;
         setEnabledSaveConfigIcons(_status_NeedToBeSaved);
         setEnableSaveProjectIcons(_status_NeedToBeSaved);
         ui->runSimulationButton->setEnabled(_status_NeedToBeSaved);
     }
 }
void MainWindow::on_setMeshPropertiesButton_clicked () private slot
SOLVER: Function to load the menu for configuring the boundaries by the user.
Definition at line 1535 of file mainwindow.cpp.
References loadMeshDialog().
 {
     loadMeshDialog();
 }
void MainWindow::on_solverButton_clicked () private slot
Action when the Solver Button is clicked.
Definition at line 86 of file MainWindowHelper.cpp.
References _inputDataTabHelper, _isMultizoneProject, _projectData, _solverManager, _userConfigValuesSolver, enableMeshOptions(), enableToolButtons(), InputDataTabHelper::fillFileNamesInTab(), SolverConfigManager::initializeManager(), SolverConfigManager::isInitialized(), setEnabledRunIcon(), InputDataTabHelper::showAllSolverMenus(), Tool4Id, and ui.
 {
     enableToolButtons(Tool4Id);
     _inputDataTabHelper.showAllSolverMenus(_projectData);
     if (!_solverManager.isInitialized())
         _solverManager.initializeManager();
     if (!_isMultizoneProject)
         _inputDataTabHelper.fillFileNamesInTab(_projectData, &_userConfigValuesSolver);
     enableMeshOptions();
     setEnabledRunIcon(true);
     ui->actionSave_Residual_Image->setEnabled(true);
     if (!_isMultizoneProject)
     {
         ui->solverTabwidget->setTabEnabled(0,true);
         ui->solverTabwidget->setTabEnabled(1,false);
     }
 }
void MainWindow::on_solverTabwidget_tabCloseRequested (int index) private slot
Implementation to Close the tabs.
Parameters
index
Definition at line 309 of file mainwindow.cpp.
References ShowMessageHelper::showMessageWindow(), and ui.
 {
     ShowMessageHelper _showHelper;
     if (index > 2)
         ui->solverTabwidget->removeTab(index);
     else
         _showHelper.showMessageWindow("CLosing Tabs", "These tabs cannot be closed",this);
 }
void MainWindow::on_stopButton_clicked () private slot
This function is to refresh the mesh file.
This function stops the current simulation
Definition at line 1734 of file mainwindow.cpp.
References stopSolverProcess().
 {
     stopSolverProcess();
 }
void MainWindow::openProject (QString _projectFilePath) private
This function controls the opening of a project.
Parameters
_projectFilePath
Definition at line 397 of file FileMenuHelper.cpp.
References _boundaryConfigValues, _boundaryMeshValues, _inputDataTabHelper, _projectData, _projectDetailsData, _status_NeedToBeSaved, _userConfigValuesSolver, _userVirtualMRFDataList, checkProjectBasePathConsistency(), ProjectData::copy(), InputDataTabHelper::enableConfigurationViewMenu(), ProjectData::getProjectFileName(), ProjectData::getProjectPath(), UtilFiles::openProjectDetails(), UtilFiles::openProjectStructure(), removeDefaultValuesReadFromConfigFile(), setEnableSaveProjectIcons(), ShowMessageHelper::showMessage(), ui, updateMainWindowElements(), and InputDataTabHelper::updateSolverUserValues().
Referenced by on_actionOpen_Project_triggered(), and openRecentFile().
 {
     UtilFiles _utilFiles;
     // Update Project Data
     ProjectData _openedProject = _utilFiles.openProjectStructure(_projectFilePath);
     // Update Paths, if necessary
      checkProjectBasePathConsistency(&_openedProject,_projectFilePath);
     _projectDetailsData = _utilFiles.openProjectDetails(_projectFilePath);
     // Update Status Bar
     QString _openedProjectPath = _openedProject.getProjectPath() + QDir::separator() + _openedProject.getProjectFileName();
     ShowMessageHelper _showHelper;
     _showHelper.showMessage("Open Project:"+ _openedProjectPath, statusBar());
      // Getting the associated info
     _projectData.copy(_openedProject);
      // Update Variables according the Solver
     bool _needToBeSaved = _inputDataTabHelper.updateSolverUserValues(_projectData,&_userConfigValuesSolver,
                                                                          &_boundaryMeshValues,&_boundaryConfigValues,
                                                                      &_userVirtualMRFDataList);
     if (_needToBeSaved)
         _status_NeedToBeSaved = _needToBeSaved;
     // Update configuration values removing those that corresponds with default values
      removeDefaultValuesReadFromConfigFile();
     _inputDataTabHelper.enableConfigurationViewMenu(_projectData);
     updateMainWindowElements(_openedProject.getProjectPath(),false,_openedProjectPath);
      if (_status_NeedToBeSaved)
      {
          setEnableSaveProjectIcons(true);
          ui->savePhysicsButton->setEnabled(true);
      }
 }
void MainWindow::openRecentFile () private slot
This action opens a project selected in the recent project list.
Definition at line 374 of file FileMenuHelper.cpp.
References _userPreferencesData, closeExistentProject(), UserPreferencesData::getRecentProjectsList(), and openProject().
Referenced by createRecentProjectAction().
 {
     closeExistentProject();
     QString _file;
     QAction *action = qobject_cast<QAction *>(sender());
     if (action)
         _file = action->data().toString();
     if (_file.isEmpty())
         return;
     int _pos = _userPreferencesData.getRecentProjectsList().indexOf(_file);
     if (_pos == -1 )
         return;
     openProject(_file);
 }
bool MainWindow::openSolverConfigurationFileDialog () private
Dialog for open a configuration file.
Definition at line 789 of file mainwindow.cpp.
References _boundaryConfigValues, _boundaryMeshValues, _inputDataTabHelper, _isMultizoneProject, _isNewConfigFile, _meshData, _mManager, _multizoneProjectData, _projectData, _userConfigValuesSolver, _userVirtualMRFDataList, MultizoneManager::buildProjectDataForMultizoneProject(), checkMeshNames(), MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), ProjectData::getProjectPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), InputDataTabHelper::parseFile(), ParserSolverConfigFile, removeDefaultValuesReadFromConfigFile(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), TOOL4, InputDataTabHelper::updateConfigurationFilePathInActionGroup(), MultizoneManager::updateOpenEditConfigFile(), and InputDataTabHelper::updateSolverUserValues().
Referenced by on_openFileActionButton_clicked().
 {
     bool _successOpeningFile = false;
     QString _projectFilePath = QFileDialog::getOpenFileName(this, tr("Open Configuration File"),
                                                             QDir(_projectData.getProjectPath()).filePath(TOOL4),
                                                             tr("Configuration File (*.cfg)"));
     if (!_projectFilePath.isNull())
     {
         if (!_isMultizoneProject)
         {
             _inputDataTabHelper.parseFile(ParserSolverConfigFile,_projectFilePath,&_userConfigValuesSolver,
                                   &_boundaryMeshValues, &_userVirtualMRFDataList);
             SolverVO _oldSolverData = _projectData.getSolverDataInformation();
             _oldSolverData.setSolverConfigFilePath(_projectFilePath);
             _projectData.setSolverDataInformation(_oldSolverData);
             _inputDataTabHelper.updateConfigurationFilePathInActionGroup(_oldSolverData.getSolverConfigFilePath());
             if (!_projectData.getSolverDataInformation().getSolverFilePath().isEmpty())
                _userConfigValuesSolver.insert("MESH_FILENAME",QDir(_meshData.getMeshPath()).filePath(_meshData.getMeshFileName()));
           }else{
             // A Multizone project needs to build the projectData with the correspondent values
              _mManager.buildProjectDataForMultizoneProject(_projectFilePath,&_multizoneProjectData,&_projectData);
             _inputDataTabHelper.updateSolverUserValues(_projectData,&_userConfigValuesSolver,
                                                        &_boundaryMeshValues,&_boundaryConfigValues,
                                                        &_userVirtualMRFDataList);
             checkMeshNames();
             _mManager.updateOpenEditConfigFile(_projectFilePath,&_multizoneProjectData,&_projectData, _isNewConfigFile);
            }
          removeDefaultValuesReadFromConfigFile();
         _successOpeningFile = true;
     }
     return _successOpeningFile;
 }
void MainWindow::outlog () private slot
Slot that allows to capture the standard output and redirect to the console text entry.
Definition at line 717 of file mainwindow.cpp.
References _myprocess, _outputSolverParser, _residualVO, OutputSolverParser::checkWhenDataToPaintAvailable(), OutputSolverParser::getStartParsing(), OutputSolverParser::parseOutput(), plotResiduals, SolverPlotter::showPoints(), stopSolverProcess(), and ui.
Referenced by connectProcessSignalSlots().
 {
     QString _solverOutput =_myprocess->readAllStandardOutput() ;
     qDebug ( _myprocess->readAllStandardError());
    if (!_solverOutput.contains("Press any key to exit"))
     {
         if (!_outputSolverParser->getStartParsing())
             _outputSolverParser->checkWhenDataToPaintAvailable(_solverOutput);
         else
         {
             _outputSolverParser->parseOutput(_residualVO,_solverOutput);
             plotResiduals->showPoints(_residualVO);
         }
     }else
    {
        ui->textEdit->append(_solverOutput);
         stopSolverProcess();
     }
     ui->textEdit->append(_solverOutput);
 }
void MainWindow::outlogtext (QString ver) signal
void MainWindow::registerUIMultizoneElements () private
This function register all the elements of the multizone interaface (buttons, editors, etc)
Definition at line 53 of file MultizoneTabHelper.cpp.
References _mManager, MultizoneManager::registerUIElements(), and ui.
Referenced by on_actionNew_Multizone_Project_triggered(), and on_actionOpen_Multizone_Project_triggered().
 {
     _mManager.registerUIElements(ui->runSimulationButton,ui->setMeshPropertiesButton,ui->confFileLabel,ui->meshFileLabel,
                                  ui->actionRun_Project,ui->actionCompare_Configuration_Files,
                                  //ui->currentFilesGroupBox,
                                  ui->viewGroupBox,
                                  ui->setMeshPropertiesGroup,ui->configFileLineLabel,ui->meshFileLineLabel,ui->projectTreeView);
 }
void MainWindow::removeDefaultValuesReadFromConfigFile () private
This function removes those variables loaded from the configuration file which value corresponds to the default value.
Definition at line 832 of file mainwindow.cpp.
References _solverManager, _userConfigValuesSolver, SolverConfigManager::getAllSectionMenuList(), SolverSectionDAO::isDefaultValueByFileName(), and SolverConfigManager::isInitialized().
Referenced by on_openFileActionButton_clicked(), on_savePhysicsButton_clicked(), on_seeSummaryChangesButton_clicked(), openProject(), and openSolverConfigurationFileDialog().
 {
     if (!_userConfigValuesSolver.isEmpty())
     {
         QHash<QString,QString> _cleanedConfigValues;
         QHashIterator<QString,QString> iter(_userConfigValuesSolver);
         SolverSectionDAO _dao;
         if (!_solverManager.isInitialized())
             _solverManager.isInitialized();
         QList<SolverSectionVO> _menuList = _solverManager.getAllSectionMenuList();
         while(iter.hasNext())
         {
             iter.next();
             if ( (!_dao.isDefaultValueByFileName(_menuList, iter.key(), iter.value()))
                 || (iter.key().contains("BC_")) || (iter.key().contains("MARKER")) )
                 _cleanedConfigValues.insert(iter.key(),iter.value());
         }
         _userConfigValuesSolver = _cleanedConfigValues;
     }
 }
void MainWindow::removeMarkerElementsFromConfigFile () private
void MainWindow::resetBooleanValues () private
This function resets all the boolean variables of mainwindow.
Definition at line 773 of file mainwindow.cpp.
References _isMultizoneProject, _isNewConfigFile, _projectExists, and _status_NeedToBeSaved.
Referenced by closeProject(), and initializeStructures().
 {
     // Boolean Values
      _projectExists = false;
      _status_NeedToBeSaved = false;
      _isMultizoneProject = false;
      _isNewConfigFile = false;
 }
void MainWindow::resetBoundaryValues () private
Definition at line 1754 of file mainwindow.cpp.
References _boundaryMeshValues, and _userBoundaryValuesSolver.
Referenced by clearAllData(), launchActionProjectSettingsDialog(), and on_newActionButton_clicked().
 {
     _userBoundaryValuesSolver.clear();
     _boundaryMeshValues.clear();
 }
void MainWindow::resetMultizoneTable () private
Definition at line 164 of file MultizoneTabHelper.cpp.
References ui.
Referenced by on_actionNew_Multizone_Project_triggered(), and on_actionOpen_Multizone_Project_triggered().
 {
     int _totalRows = ui->multizoneFilesTable->rowCount();
     for (int i = _totalRows; i>=0;i--)
           ui->multizoneFilesTable->removeRow(i);
 }
void MainWindow::resetOldMarkerValues () private
Reset the marker values to their old values.
Definition at line 1600 of file mainwindow.cpp.
References _userConfigValuesSolver, BC_PREFIX, and MARKER_PREFIX.
Referenced by checkMeshNames(), on_actionImport_Mesh_File_triggered(), and updateBoundaryValues().
 {
     if (!_userConfigValuesSolver.isEmpty())
     {
         QHashIterator<QString,QString> _iter(_userConfigValuesSolver);
         while(_iter.hasNext())
         {
             _iter.next();
             QString _keyName = _iter.key();
             if( (_keyName.contains(MARKER_PREFIX)) || (_keyName.contains(BC_PREFIX)) )
                  _userConfigValuesSolver.insert(_keyName,"NONE");
         }
     }
 }
void MainWindow::resetSolverMenu () private
Reset the values of the menus of Solver to the default values.
Definition at line 1106 of file mainwindow.cpp.
References setEnabledRunIcon(), and ui.
Referenced by closeProject().
 {
     ui->actionImport_Mesh_File->setEnabled(false);
     ui->actionSave_Configuration_File->setEnabled(false);
     ui->actionSave_Configuration_File_As->setEnabled(false);
     setEnabledRunIcon(false);
 }
void MainWindow::resetSolverTabEnabledElements () private
Reset of Solver tab elements to their default values.
Definition at line 1690 of file mainwindow.cpp.
References setEnabledRunIcon(), setEnabledSaveConfigIcons(), and ui.
Referenced by closeExistentProject().
 {
     setEnabledRunIcon(false);
     ui->actionStop_Execution->setEnabled(false);
     ui->stopButton->setEnabled(false);
     ui->actionSave_Residual_Image->setEnabled(false);
     setEnabledSaveConfigIcons(false);
     ui->savePhysicsButton->setEnabled(false);
     ui->setMeshPropertiesButton->setEnabled(false);
     //ui->meshRefreshButton->setEnabled(false);
 }
void MainWindow::resetUserConfigurationValues () private
Reset the current values of the Solver configuration made by the user.
Definition at line 1033 of file mainwindow.cpp.
References _userConfigValuesSolver.
Referenced by on_newActionButton_clicked().
 {
     _userConfigValuesSolver.clear();
 }
void MainWindow::runSimulation () private
SOLVER: run the simulation.
Definition at line 680 of file mainwindow.cpp.
References _status_NeedToBeSaved, clearConsoleText(), runSolverProject(), saveConfigFile(), setEnabledRunIcon(), ShowMessageHelper::showMessageForSaving(), tabInputData, tabResidual, and ui.
Referenced by on_actionRun_Project_triggered(), on_restartButton_clicked(), and on_runSimulationButton_clicked().
 {
     clearConsoleText();
     setEnabledRunIcon(false);
     ui->solverTabwidget->setCurrentIndex(tabResidual);
     if (_status_NeedToBeSaved)
     {
         ShowMessageHelper _showHelper;
         bool _saveResults = _showHelper.showMessageForSaving();
         if (_saveResults)
         {
             bool _savedFile = true;
             if (_status_NeedToBeSaved)
                 _savedFile = saveConfigFile();
             if (_savedFile)
                 runSolverProject();
         }else
         {
            setEnabledRunIcon(true);
            ui->solverTabwidget->setCurrentIndex(tabInputData);
         }
     }
     else
         runSolverProject();
 }
void MainWindow::runSolverProject () private
Run the current Solver project.
Definition at line 1157 of file mainwindow.cpp.
References _myprocess, _outputSolverParser, _projectData, _residualVO, _updatedLegend, buildSolverCommand(), SolverResidualVO::clearAllData(), SolverPlotter::clearCanvas(), ProjectData::getProjectPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), MPI_EXEC_COMMAND, PARALLEL_BBIPED_PARTITION_COMMAND, PARALLEL_BBIPED_RUN_COMMAND, plotResiduals, SPACE_TAB, TOOL4, and ui.
Referenced by on_multizoneRunSimulationButton_clicked(), and runSimulation().
 {
     bool _serialExecution = true;
     if (!ui->noProcessorslineEdit->text().isEmpty())
        _serialExecution = false;
     // Clear data just in case
     //plot->resetLegend(_residualVO);
      _residualVO->clearAllData();
      plotResiduals->clearCanvas();
     _updatedLegend = false;
     _outputSolverParser = new OutputSolverParser();
     // SOL: http://stackoverflow.com/questions/11921004/cannot-read-output-using-readyreadstandardoutput-in-qt
     // Setting the working directory
     QString _workingDir = QDir(_projectData.getProjectPath()).filePath(TOOL4);
     _myprocess->setWorkingDirectory(_workingDir);
     QString _processCommand;
     if (_serialExecution)
     {
         _processCommand = buildSolverCommand();
         if (!_processCommand.isEmpty())
         {
             ui->textEdit->append( "EXECUTING ***********************");
             ui->textEdit->append("PATH--> "+_workingDir);
             ui->textEdit->append("COMMAND--> " +_processCommand);
             _myprocess->start(_processCommand);
         }else
             ui->textEdit->append( "ERROR running the solver program" );
     }
     else
     {
         _processCommand = MPI_EXEC_COMMAND + SPACE_TAB + ui->noProcessorslineEdit->text() + SPACE_TAB + PARALLEL_BBIPED_PARTITION_COMMAND +
                 SPACE_TAB + _projectData.getSolverDataInformation().getSolverConfigFilePath();
         if (!_processCommand.isEmpty())
         {
         ui->textEdit->append( "EXECUTING ***********************");
         ui->textEdit->append("PATH--> "+_workingDir);
         ui->textEdit->append("COMMAND--> " +_processCommand);
         _myprocess->start(_processCommand);
         }else
             ui->textEdit->append( "ERROR running the solver program" );
         _processCommand = MPI_EXEC_COMMAND + SPACE_TAB + ui->noProcessorslineEdit->text() + SPACE_TAB + PARALLEL_BBIPED_RUN_COMMAND +
                 SPACE_TAB + _projectData.getSolverDataInformation().getSolverConfigFilePath();
         if (!_processCommand.isEmpty())
         {
             ui->textEdit->append( "EXECUTING ***********************");
             ui->textEdit->append("PATH--> "+_workingDir);
             ui->textEdit->append("COMMAND--> " +_processCommand);
             _myprocess->start(_processCommand);
         }else
         ui->textEdit->append( "ERROR running the solver program" );
     }
 }
void MainWindow::runSolverProject (QString _projectPath) private
Definition at line 1216 of file mainwindow.cpp.
References _myprocess, _outputSolverParser, _residualVO, _updatedLegend, buildSolverCommand(), SolverResidualVO::clearAllData(), SolverPlotter::clearCanvas(), plotResiduals, TOOL4, and ui.
 {
     // Clear data just in case
     //plot->resetLegend(_residualVO);
      _residualVO->clearAllData();
      plotResiduals->clearCanvas();
     _updatedLegend = false;
     _outputSolverParser = new OutputSolverParser();
     // SOL: http://stackoverflow.com/questions/11921004/cannot-read-output-using-readyreadstandardoutput-in-qt
     // Setting the working directory
     QString _workingDir = QDir(_projectPath).filePath(TOOL4);
     _myprocess->setWorkingDirectory(_workingDir);
     QString _processCommand = buildSolverCommand();
     if (!_processCommand.isEmpty())
     {
         ui->textEdit->append( "EXECUTING ***********************");
         ui->textEdit->append("PATH--> "+_workingDir);
         ui->textEdit->append("COMMAND--> " +_processCommand);
         _myprocess->start(_processCommand);
     }else
         ui->textEdit->append( "ERROR running the solver program" );
 }
bool MainWindow::saveConfigFile () private
Save helper function to save the configuration file and all the associated info.
Definition at line 485 of file mainwindow.cpp.
References _inputDataTabHelper, _meshData, _projectData, _projectDetailsData, _projectExists, _solverManager, _status_NeedToBeSaved, _userConfigValuesSolver, _userVirtualMRFDataList, MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), ProjectData::getProjectPath(), SolverVO::getSolverConfigFileMapValues(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), InputDataTabHelper::saveAsConfigFile(), SolverConfigManager::saveConfigFile(), StrEqual, TOOL4, SolverConfigManager::updateDOMTree(), and updateProjectDataToFile().
Referenced by closeProject(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), on_actionSave_triggered(), on_openFileActionButton_clicked(), on_savePhysicsButton_clicked(), and runSimulation().
 {
     QString _fileConfigPathName = _projectData.getSolverDataInformation().getSolverConfigFilePath();
     QFileInfo _fileInfo(_fileConfigPathName);
     QString _cConfigPath = _fileInfo.absolutePath();
     QString _projecSolvertPath = QDir(_projectData.getProjectPath()).filePath(TOOL4);
     bool _savedFile = true;
     // Updating the Tree View
     _solverManager.updateDOMTree(this->_projectData.getSolverDataInformation().getSolverConfigFileMapValues());
     // Updating the Mesh file Name
     if (!_projectData.getSolverDataInformation().getSolverFilePath().isEmpty())
         _userConfigValuesSolver.insert("MESH_FILENAME",QDir(_meshData.getMeshPath()).filePath(_meshData.getMeshFileName()));
     if ( (_projectExists) && ( (_fileConfigPathName.isEmpty()) || (_fileConfigPathName.isNull())
          || (QString::compare(_projecSolvertPath ,_cConfigPath) != StrEqual) ) )
     {
         QString filename = QFileDialog::getSaveFileName(this,tr("Save Solver Configuration File As"),
                                                         QDir(_projectData.getProjectPath()).filePath(TOOL4),
                                                         tr("Configuration File name (*.cfg)") );
         if (!filename.isEmpty())
         {
             _inputDataTabHelper.saveAsConfigFile(filename,&_projectData,&_solverManager,_userConfigValuesSolver, _projectDetailsData,
                                                  _userVirtualMRFDataList);
             updateProjectDataToFile();
             _status_NeedToBeSaved = false;
         }else
            _savedFile = false;
     }
     else
     {
         _solverManager.saveConfigFile(_fileConfigPathName,_userConfigValuesSolver, _projectDetailsData,_userVirtualMRFDataList);
         updateProjectDataToFile();
         _status_NeedToBeSaved = false;
     }
     return _savedFile;
 }
void MainWindow::saveMeshVariables () private
SOLVER: Save Mesh variables values, changed by the user.
Definition at line 1517 of file mainwindow.cpp.
References _meshData, _projectData, _userConfigValuesSolver, MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), ProjectData::getSolverDataInformation(), ProjectData::setSolverDataInformation(), SolverVO::setSolverFilePath(), and StrEqual.
Referenced by importMeshFile(), and on_actionImport_Mesh_File_triggered().
 {
     QString _meshFile = QDir(_meshData.getMeshPath()).filePath(_meshData.getMeshFileName());
     _userConfigValuesSolver.insert("MESH_FILENAME",_meshFile);
     QString _ext = QFileInfo(_meshFile).suffix();
     if (QString::compare(_ext.toLower(), "su2") == StrEqual)
         _userConfigValuesSolver.insert("MESH_FORMAT",_ext.toUpper());
     else
         _userConfigValuesSolver.insert("MESH_FORMAT",_ext);
     SolverVO _oldData = _projectData.getSolverDataInformation();
     _oldData.setSolverFilePath(_meshFile);
     _projectData.setSolverDataInformation(_oldData);
 }
void MainWindow::saveMultizoneData (QString _configFile, QString _meshFile, QHash< QString, QString > * _configVal, QList< VirtualMrfVO > * _virtualMrfList)
Definition at line 401 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, _projectDetailsData, _solverManager, SolverConfigManager::saveConfigFile(), and MultizoneProjectData::updatePair().
Referenced by multizoneSaveAll(), MultizoneIndividualTabForm::on_cancelButton_clicked(), MultizoneIndividualTabForm::on_closeButton_clicked(), and MultizoneIndividualTabForm::on_saveButton_clicked().
 {
     _multizoneProjectData.updatePair(_configFile,_meshFile);
     _solverManager.saveConfigFile(_configFile,*_configVal,_projectDetailsData,*_virtualMrfList);
 }
void MainWindow::seeParaviewResults () private
This internal function controls if the Paraview is opened passing a file or to open a new instance of Paraview.
Definition at line 97 of file ViewMenuHelper.cpp.
References _projectData, _userPreferencesData, UserPreferencesData::getPostProcessorViewerPath(), ProjectData::getProjectPath(), slotProcessError(), and TOOL4.
Referenced by on_actionParaview_File_triggered(), and on_paraviewButton_clicked().
 {
     QString _currentPath;
     if (_projectData.getProjectPath().isEmpty())
         _currentPath = QCoreApplication::applicationDirPath();//QDir::currentPath();
     else
         _currentPath = QDir(_projectData.getProjectPath()).filePath(TOOL4);
     QString _viewFile = QFileDialog::getOpenFileName(this, tr("Select the file to see with Paraview"),
                                                             _currentPath,
                                                             tr("Paraview Files (*.vtk)"));
     if (!_viewFile.isEmpty())
     {
         QString _postProcessorPath = _userPreferencesData.getPostProcessorViewerPath();
         QString _command;
         if ( (!_postProcessorPath.isNull()) && (!_postProcessorPath.isEmpty()) )
             _command = _postProcessorPath;
         else
             _command = "paraview";
         QProcess * _viewProcess = new QProcess(this);
         _command = _command + " --data="+_viewFile;
         connect(_viewProcess, SIGNAL(error(QProcess::ProcessError)),
                 this, SLOT(slotProcessError(QProcess::ProcessError)));
         _viewProcess->start(_command);
     }
 }
void MainWindow::setEnableCloseProjectIcons (bool _val) private
Disable the close project icons (at the moment only one)
Parameters
_val
Definition at line 158 of file mainwindow.cpp.
References ui.
Referenced by enableMultizoneElements(), on_actionClose_Project_triggered(), and updateMainWindowElements().
 {
     ui->actionClose_Project->setEnabled(_val);
 }
void MainWindow::setEnabledInputTabSaveButtons (bool _val) private
This function changes the disable/enable nature of the Physics button.
Parameters
_val
Definition at line 275 of file mainwindow.cpp.
References ui.
Referenced by setEnabledProjectIconButtons().
 {
     ui->savePhysicsButton->setEnabled(_val);
 }
void MainWindow::setEnabledProjectIconButtons (bool _val) private
This function is to enable of the different buttons according to _val for the user.
Parameters
_val
Definition at line 1745 of file mainwindow.cpp.
References _status_NeedToBeSaved, setEnabledInputTabSaveButtons(), setEnabledRunIcon(), setEnabledSaveConfigIcons(), and setEnableSaveProjectIcons().
Referenced by loadMeshDialog(), on_actionImport_Mesh_File_triggered(), and on_importMeshFileButton_clicked().
 {
     setEnabledRunIcon(_status_NeedToBeSaved);
     setEnableSaveProjectIcons(_status_NeedToBeSaved);
     setEnabledSaveConfigIcons(_status_NeedToBeSaved);
     setEnabledInputTabSaveButtons(_val);
 }
void MainWindow::setEnabledRunIcon (bool _val) private
Activate the run elemenst (button and menu element9.
Parameters
_val
Definition at line 436 of file mainwindow.cpp.
References _isMultizoneProject, and ui.
Referenced by closeProject(), enableSolverRunAction(), on_newActionButton_clicked(), on_solverButton_clicked(), resetSolverMenu(), resetSolverTabEnabledElements(), runSimulation(), setEnabledProjectIconButtons(), slotFinishResult(), stopSolverProcess(), and updateMeshView().
 {
     ui->actionRun_Project->setEnabled(_val);
     ui->runSimulationButton->setEnabled(_val);
     if (!_isMultizoneProject)
         ui->restartButton->setEnabled(_val);
     ui->actionStop_Execution->setEnabled(!_val);
     ui->stopButton->setEnabled(!_val);
 }
void MainWindow::setEnabledSaveConfigIcons (bool _val) private
Activate the save Congifuration elements and save config as from the menu.
Parameters
_val
Definition at line 412 of file mainwindow.cpp.
References ui.
Referenced by on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), on_basivViewEditButton_clicked(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_savePhysicsButton_clicked(), on_seeSummaryChangesButton_clicked(), resetSolverTabEnabledElements(), and setEnabledProjectIconButtons().
 {
     ui->actionSave_Configuration_File->setEnabled(_val);
     ui->actionSave_Configuration_File_As->setEnabled(_val);
 }
void MainWindow::setEnableSaveProjectIcons (bool _val) private
Enable all the Save actions fo the project.
Parameters
_val
Definition at line 168 of file mainwindow.cpp.
References ui.
Referenced by enableMultizoneElements(), launchActionProjectSettingsDialog(), on_actionClose_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), on_actionSave_triggered(), on_basivViewEditButton_clicked(), on_savePhysicsButton_clicked(), on_seeSummaryChangesButton_clicked(), openProject(), setEnabledProjectIconButtons(), and updateMainWindowElements().
 {
     ui->actionSave->setEnabled(_val);
     ui->actionSave_As->setEnabled(_val);
 }
void MainWindow::setResidualPlot () private
RESIDUAL: restart the current simulation –> TODO.
Definition at line 1424 of file mainwindow.cpp.
References PlotterManager::createPlotTab(), plotResiduals, and ui.
Referenced by MainWindow().
 {
     PlotterManager _plotManager;
     QWidget * vBox = new QWidget(this);
     plotResiduals = new SolverPlotter( vBox );
     _plotManager.createPlotTab(vBox, ui->solverTabwidget,plotResiduals, "Residual Plot","Press the legend to en/disable a curve");
 /*
     vBox->setWindowTitle( "Residual Plot" );
     plot = new SolverPlotter( vBox );
     const int margin = 5;
     plot->setContentsMargins( margin, margin, margin, margin );
     QString info( "Press the legend to en/disable a curve" );
     QLabel *label = new QLabel( info, vBox );
     QVBoxLayout *layout = new QVBoxLayout( vBox );
     layout->addWidget( plot );
     layout->addWidget( label );
     vBox->show();
     ui->solverTabwidget->addTab(vBox,"Residual");
 */
 }
void MainWindow::setUpStatusBar () private
Establish the main contents of the status bar (logo, labels, etc)
Definition at line 285 of file mainwindow.cpp.
Referenced by MainWindow().
 {
     QPixmap *pixmap = new QPixmap (":/logo/images/icon_8x16.png");
     QLabel *iconLbl = new QLabel;
     iconLbl->setPixmap(*pixmap);
     statusBar()->addPermanentWidget(iconLbl);
     delete pixmap;
 }
void MainWindow::slotFinishResult (int _val, QProcess::ExitStatus status) private slot
Slot function that performs some operations as soon as the process finish.
Parameters
val
status
Definition at line 1356 of file mainwindow.cpp.
References setEnabledRunIcon(), stopSolverProcess(), and ui.
Referenced by connectProcessSignalSlots().
 {
     ui->textEdit->append("-------------------------------- END PROCESSS -------------------------");
     setEnabledRunIcon(true);
     stopSolverProcess();
 }
void MainWindow::slotProcessError (QProcess::ProcessError error) private slot
Slot function that captures the error if something goes wrong in the process.
Parameters
error
Definition at line 1368 of file mainwindow.cpp.
References stopSolverProcess(), and ui.
Referenced by connectProcessSignalSlots(), getSalomePathSlot(), initializeStructures(), launchSalomeMeshTool(), and seeParaviewResults().
 {
     switch (error) {
         case QProcess::FailedToStart :
         ui->textEdit->append("FAILED to start the application: Check the executable configuration in the Preferences Menu");
             break;
     case QProcess::Crashed:
          ui->textEdit->append( "STOP Running simulation" );
         break;
        case QProcess::Timedout:
          ui->textEdit->append("TimedOut process: Contact Support");
         break;
     case QProcess::WriteError:
          ui->textEdit->append("Write Error: Check the permissions of the folder");
         break;
     case QProcess::ReadError:
          ui->textEdit->append( "Read Error: Check the permissions of the files ");
         break;
     case QProcess::UnknownError:
          ui->textEdit->append("Unknown Error: Contact Support ");
         break;
     }
  stopSolverProcess();
 }
void MainWindow::slotStarted () private slot
Slot function that shows when the process has started.
Definition at line 1335 of file mainwindow.cpp.
References ui.
Referenced by connectProcessSignalSlots().
 {
     ui->textEdit->append("Process Started");
 // TODO --> Read if hte history file is written
  /*   QString _fileName;
     if (_userConfigValuesSolver.contains("CONV_FILENAME"))
         _fileName = QDir(QDir(_projectData.getProjectPath()).filePath(TOOL4)).filePath(_userConfigValuesSolver.value("CONV_FILENAME"));
     if( (!_fileName.isEmpty()) && (!_fileName.isNull()))
     {
         ui->textEdit->append("Process Started" +_fileName);
       }*/
 }
void MainWindow::stopSolverProcess () private
Stop current solver running process.
Definition at line 1144 of file mainwindow.cpp.
References _myprocess, and setEnabledRunIcon().
Referenced by closeExistentProject(), on_actionStop_Execution_triggered(), on_stopButton_clicked(), outlog(), slotFinishResult(), and slotProcessError().
 {
     if (_myprocess->pid() > 0)
         _myprocess->kill();
     setEnabledRunIcon(true);
 }
void MainWindow::updateBoundaryValues () private
SOLVER: function to update the values changed by the user in the mesh variables.
Definition at line 1577 of file mainwindow.cpp.
References _userBoundaryValuesSolver, _userConfigValuesSolver, and resetOldMarkerValues().
Referenced by loadMeshDialog().
 {
     resetOldMarkerValues();
     if (!_userBoundaryValuesSolver.isEmpty())
     {
         QHashIterator<QString,QString> _iter(_userBoundaryValuesSolver);
         while (_iter.hasNext())
         {
             _iter.next();
             QString _keyname = _iter.key();
             QString _value = _iter.value();
             _userConfigValuesSolver.insert(_keyname,_value);
         }
     }
 }
void MainWindow::updateMainWindowElements (QString _projectPath, bool _isNewProject, QString _finalPath) private
This function update all the elements of the main window, restore the icons, etc.
Parameters
_projectPath
_isNewProject
_finalPath
Definition at line 247 of file mainwindow.cpp.
References _projectExists, _status_NeedToBeSaved, _treeHelper, _userPreferencesData, UserPreferencesData::addProjectToList(), addProjectToRecentProjectsSection(), enableAllMainButtons(), ProjectMenuTreeHelper::fillProjectTreeView(), setEnableCloseProjectIcons(), setEnableSaveProjectIcons(), and ui.
Referenced by on_actionNew_Project_triggered(), and openProject().
 {
    // ProjectMenuTreeHelper _treeHelper;
     _treeHelper.fillProjectTreeView(_projectPath);//,ui->projectTreeView);
     enableAllMainButtons();
     _projectExists = true;
     if (_isNewProject)
         _status_NeedToBeSaved = true;
     setEnableCloseProjectIcons(true);
     setEnableSaveProjectIcons(true);
     _userPreferencesData.addProjectToList(_finalPath);
     addProjectToRecentProjectsSection(_finalPath);
     ui->menuSalome_Tools->setEnabled(true);
 }
void MainWindow::updateMeshView (QString _solverFilePath) private
Definition at line 912 of file mainwindow.cpp.
References _inputDataTabHelper, _isMultizoneProject, _isNewConfigFile, _mManager, _multizoneProjectData, _projectData, _userConfigValuesSolver, InputDataTabHelper::enableChangeConfigActionMenu(), InputDataTabHelper::enableConfigurationViewMenu(), OptionMzMeshPath, setEnabledRunIcon(), InputDataTabHelper::updateMeshFileNameInActionGroup(), and MultizoneManager::updateViewForNewFile().
Referenced by importMeshFile(), and importMeshInfoFile().
 {
     // Updating View
     if (!_isMultizoneProject)
         _inputDataTabHelper.updateMeshFileNameInActionGroup(_solverFilePath, &_userConfigValuesSolver);
     else
         _mManager.updateViewForNewFile(_solverFilePath,OptionMzMeshPath,&_multizoneProjectData,&_projectData, _isNewConfigFile);
     // Enabling and disabling
     _inputDataTabHelper.enableConfigurationViewMenu(_projectData);
     _inputDataTabHelper.enableChangeConfigActionMenu();
     setEnabledRunIcon(false);
 }
void MainWindow::updateMultizoneUserData (QString _configFile, QString _meshFile) private
Definition at line 195 of file MultizoneTabHelper.cpp.
References _multizoneProjectData, _projectDetailsData, _solverManager, _status_NeedToBeSaved, _userVirtualMRFDataList, MultizoneProjectData::addConfigFile(), MultizoneProjectData::addMeshFile(), MultizoneProjectData::getProjectPath(), UtilFiles::importFile(), SolverConfigManager::saveConfigFile(), StrEqual, TOOL4, and SolverConfigWriter::writeToConfigurationFile().
Referenced by on_multizoneNewButton_clicked().
 {
     QFileInfo _configFileInfo(_configFile);
     QFileInfo _meshFileInfo(_meshFile);
     // Checking the paths of the files, if they are different to the project path they must be copied here
     QString _projectPath = QDir(_multizoneProjectData.getProjectPath()).filePath(TOOL4);
     QString _configPath = _configFileInfo.absolutePath();
     QString _meshFilePath = _meshFileInfo.absolutePath();
     UtilFiles _utilFilesHelper;
     if (!_configFile.isEmpty())
     {
             //_inputDataTabHelper->parseFile(ParserSolverConfigFile,_configFile,_configVal,_bndMeshVal,_virtualMRFList);
             if ((QString::compare(_projectPath,_configPath) != StrEqual))
                 _configFile = _utilFilesHelper.importFile(_multizoneProjectData.getProjectPath(),_configFile,TOOL4);
             else
             {
                 // Create the _configFile
                  SolverConfigWriter _writer;
                  _writer.writeToConfigurationFile(_configFile, new QDomDocument(), _projectDetailsData);
             }
             if (!_meshFile.isEmpty())// && ( QString::compare(_projectPath,_meshFilePath) != StrEqual))
             {
                 _meshFile =  _utilFilesHelper.importFile(_multizoneProjectData.getProjectPath(),_meshFile,TOOL4);
                 QHash<QString,QString> _configValues;
                 _configValues.insert("MESH_FILENAME",_meshFile);
                 _solverManager.saveConfigFile(_configFile,_configValues,_projectDetailsData,_userVirtualMRFDataList);
             }
      }
     // Update Multizone Information
     _multizoneProjectData.addConfigFile(_configFile);
     _multizoneProjectData.addMeshFile(_meshFile);
     _status_NeedToBeSaved = true;
 }
void MainWindow::updateProjectDataToFile () private
Update Project Data Paths.
Definition at line 973 of file mainwindow.cpp.
References _isMultizoneProject, _multizoneProjectData, _projectData, _projectDetailsData, UtilFiles::updateMultizoneProjectDataToFile(), and UtilFiles::updateProjectDataToFile().
Referenced by closeProject(), on_actionSave_triggered(), and saveConfigFile().
 {
     UtilFiles _utilFiles;
     if (!_isMultizoneProject)
         _utilFiles.updateProjectDataToFile(_projectData, _projectDetailsData);
     else
         _utilFiles.updateMultizoneProjectDataToFile(_multizoneProjectData, _projectDetailsData);
 }
void MainWindow::updateRecentProjectsSection () private
This function update the project list of the "recent project list" of the menu.
Definition at line 280 of file FileMenuHelper.cpp.
References _userPreferencesData, createProjectActions(), UserPreferencesData::getRecentProjectsList(), and ui.
Referenced by initializeUserPreferences().
 {
     if (!_userPreferencesData.getRecentProjectsList().isEmpty())
     {
        if (ui->action_Empty->isVisible())
             ui->action_Empty->setVisible(false);
        createProjectActions(_userPreferencesData.getRecentProjectsList());
     }
 }
Member Data Documentation
QHash<QString,QString> MainWindow::_boundaryConfigValues private
Definition at line 214 of file mainwindow.h.
Referenced by openProject(), and openSolverConfigurationFileDialog().
QHash<QString,QString> MainWindow::_boundaryMeshValues private
Definition at line 213 of file mainwindow.h.
Referenced by checkMeshNames(), importMeshFile(), importMeshInfoFile(), loadMeshDialog(), openProject(), openSolverConfigurationFileDialog(), and resetBoundaryValues().
InputDataTabHelper MainWindow::_inputDataTabHelper private
Definition at line 186 of file mainwindow.h.
Referenced by closeProject(), enableToolButtons(), importMeshFile(), initializeHelper(), launchActionProjectSettingsDialog(), MainWindow(), on_basivViewEditButton_clicked(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_solverButton_clicked(), openProject(), openSolverConfigurationFileDialog(), saveConfigFile(), and updateMeshView().
bool MainWindow::_is3DMesh private
Definition at line 238 of file mainwindow.h.
Referenced by importMeshFile(), importMeshInfoFile(), MainWindow(), and on_basivViewEditButton_clicked().
bool MainWindow::_isMultizoneProject private
Definition at line 229 of file mainwindow.h.
Referenced by buildSolverCommand(), closeProject(), enableMultizoneElements(), enableSolverRunAction(), getSolverCommand(), launchActionProjectSettingsDialog(), loadMeshDialog(), on_actionCompare_Configuration_Files_triggered(), on_actionRun_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_triggered(), on_actionSynchronise_all_files_triggered(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_runSimulationButton_clicked(), on_solverButton_clicked(), openSolverConfigurationFileDialog(), resetBooleanValues(), setEnabledRunIcon(), updateMeshView(), and updateProjectDataToFile().
bool MainWindow::_isNewConfigFile private
Definition at line 230 of file mainwindow.h.
Referenced by on_actionSave_Configuration_File_As_triggered(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), openSolverConfigurationFileDialog(), resetBooleanValues(), and updateMeshView().
MeshInfoVO MainWindow::_meshData private
Definition at line 194 of file mainwindow.h.
Referenced by checkMeshNames(), clearAllData(), importMeshFile(), importMeshInfoFile(), openSolverConfigurationFileDialog(), saveConfigFile(), and saveMeshVariables().
MeshDialog* MainWindow::_meshWindow private
Definition at line 176 of file mainwindow.h.
Referenced by loadMeshDialog().
MultizoneManager MainWindow::_mManager private
Definition at line 232 of file mainwindow.h.
Referenced by closeProject(), launchActionProjectSettingsDialog(), on_actionNew_Multizone_Project_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionSave_Configuration_File_As_triggered(), on_newActionButton_clicked(), openSolverConfigurationFileDialog(), registerUIMultizoneElements(), and updateMeshView().
MultizoneProjectData MainWindow::_multizoneProjectData private
Definition at line 192 of file mainwindow.h.
Referenced by buildSolverCommand(), enableMultizoneElements(), enableSolverRunAction(), fillMultizoneTable(), launchActionProjectSettingsDialog(), on_actionCompare_Configuration_Files_triggered(), on_actionNew_Multizone_Project_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSynchronise_all_files_triggered(), on_multizoneDeleteButton_clicked(), on_multizoneNewButton_clicked(), on_multizoneOpenEditButton_clicked(), on_multizoneRunSimulationButton_clicked(), on_multizoneSummaryAllConfigButton_clicked(), on_newActionButton_clicked(), openSolverConfigurationFileDialog(), saveMultizoneData(), updateMeshView(), updateMultizoneUserData(), and updateProjectDataToFile().
QProcess* MainWindow::_myprocess private
Definition at line 218 of file mainwindow.h.
Referenced by connectProcessSignalSlots(), initializeStructures(), on_multizoneStopSimulationButton_clicked(), outlog(), runSolverProject(), stopSolverProcess(), and ~MainWindow().
OutputSolverParser* MainWindow::_outputSolverParser private
Definition at line 206 of file mainwindow.h.
Referenced by clearAllData(), initializeStructures(), outlog(), runSolverProject(), and ~MainWindow().
ProjectData MainWindow::_projectData private
Definition at line 191 of file mainwindow.h.
Referenced by buildSolverCommand(), checkMeshNames(), clearAllData(), closeProject(), enableMeshOptions(), enableSolverRunAction(), importMeshFile(), importMeshInfoFile(), launchActionProjectSettingsDialog(), launchSalomeMeshTool(), on_actionAutomatic_Optimization_triggered(), on_actionCompare_Configuration_Files_triggered(), on_actionLoad_Templates_triggered(), on_actionNew_Multizone_Project_triggered(), on_actionNew_Project_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_triggered(), on_actionSynchronise_all_files_triggered(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_restartButton_clicked(), on_solverButton_clicked(), openProject(), openSolverConfigurationFileDialog(), runSolverProject(), saveConfigFile(), saveMeshVariables(), seeParaviewResults(), updateMeshView(), and updateProjectDataToFile().
ProjectDetails MainWindow::_projectDetailsData private
Definition at line 193 of file mainwindow.h.
Referenced by clearAllData(), launchActionProjectSettingsDialog(), on_actionCompare_Configuration_Files_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionSave_As_triggered(), on_actionSynchronise_all_files_triggered(), on_newActionButton_clicked(), openProject(), saveConfigFile(), saveMultizoneData(), updateMultizoneUserData(), and updateProjectDataToFile().
bool MainWindow::_projectExists private
Definition at line 202 of file mainwindow.h.
Referenced by clearAllData(), closeExistentProject(), enableMultizoneElements(), on_actionClose_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Temporal_triggered(), on_actionSave_triggered(), resetBooleanValues(), saveConfigFile(), and updateMainWindowElements().
QTextEdit* MainWindow::_projectTextEditor private
Definition at line 177 of file mainwindow.h.
Referenced by clearAllData(), initializeStructures(), on_projectTreeView_doubleClicked(), and ~MainWindow().
QList<QAction *> MainWindow::_recentProjectsList private
Definition at line 181 of file mainwindow.h.
Referenced by addProjectToRecentProjectsSection(), and createProjectActions().
QSignalMapper* MainWindow::_recentProjectsMapper private
Definition at line 180 of file mainwindow.h.
ResidualTabHelper* MainWindow::_residualTabHelper private
Definition at line 185 of file mainwindow.h.
SolverResidualVO* MainWindow::_residualVO private
Definition at line 207 of file mainwindow.h.
Referenced by closeProject(), initializeStructures(), on_restartButton_clicked(), outlog(), runSolverProject(), and ~MainWindow().
QProcess* MainWindow::_salomeLocationProccess private
Definition at line 219 of file mainwindow.h.
Referenced by closeProject(), getSalomePathSlot(), initializeStructures(), and launchSalomeMeshTool().
SolverConfigManager MainWindow::_solverManager private
Definition at line 205 of file mainwindow.h.
Referenced by initializeManagers(), launchSalomeMeshTool(), loadMeshDialog(), on_actionCompare_Configuration_Files_triggered(), on_actionCreate_Configuration_Template_triggered(), on_actionEdit_Configuration_Template_triggered(), on_actionLoad_Configuration_Template_triggered(), on_actionPreferences_triggered(), on_actionSynchronise_all_files_triggered(), on_basivViewEditButton_clicked(), on_multizoneOpenEditButton_clicked(), on_multizoneSummaryAllConfigButton_clicked(), on_seeSummaryChangesButton_clicked(), on_solverButton_clicked(), removeDefaultValuesReadFromConfigFile(), saveConfigFile(), saveMultizoneData(), and updateMultizoneUserData().
bool MainWindow::_status_NeedToBeSaved private
Definition at line 201 of file mainwindow.h.
Referenced by checkProjectBasePathConsistency(), clearAllData(), closeProject(), enableMultizoneElements(), importMeshFile(), launchActionProjectSettingsDialog(), loadMeshDialog(), multizoneSaveAll(), notSavedMultizoneData(), on_actionImport_Mesh_File_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionRun_Project_triggered(), on_actionSave_As_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), on_actionSave_triggered(), on_basivViewEditButton_clicked(), on_importMeshFileButton_clicked(), on_multizoneDeleteButton_clicked(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_restartButton_clicked(), on_runSimulationButton_clicked(), on_savePhysicsButton_clicked(), on_seeSummaryChangesButton_clicked(), openProject(), resetBooleanValues(), runSimulation(), saveConfigFile(), setEnabledProjectIconButtons(), updateMainWindowElements(), and updateMultizoneUserData().
bool MainWindow::_stopped private
Definition at line 225 of file mainwindow.h.
Referenced by MainWindow().
SummaryDialog* MainWindow::_summaryDialog private
Definition at line 175 of file mainwindow.h.
Referenced by on_seeSummaryChangesButton_clicked().
ProjectMenuTreeHelper MainWindow::_treeHelper private
Definition at line 187 of file mainwindow.h.
Referenced by closeProject(), initializeHelper(), on_actionSave_As_triggered(), on_projectTreeView_doubleClicked(), and updateMainWindowElements().
bool MainWindow::_updatedLegend private
Definition at line 226 of file mainwindow.h.
Referenced by runSolverProject().
QHash<QString, QString> MainWindow::_userBoundaryValuesSolver private
Definition at line 211 of file mainwindow.h.
Referenced by getLoadedBoundaryValues(), loadMeshDialog(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), resetBoundaryValues(), and updateBoundaryValues().
QHash<QString, QString> MainWindow::_userConfigValuesSolver private
Definition at line 210 of file mainwindow.h.
Referenced by checkMeshNames(), clearAllData(), getLoadedBoundaryValues(), getSolverCommand(), importMeshFile(), launchActionProjectSettingsDialog(), loadMeshDialog(), on_actionRun_Project_triggered(), on_basivViewEditButton_clicked(), on_restartButton_clicked(), on_runSimulationButton_clicked(), on_seeSummaryChangesButton_clicked(), on_solverButton_clicked(), openProject(), openSolverConfigurationFileDialog(), removeDefaultValuesReadFromConfigFile(), resetOldMarkerValues(), resetUserConfigurationValues(), saveConfigFile(), saveMeshVariables(), updateBoundaryValues(), and updateMeshView().
UserPreferencesData MainWindow::_userPreferencesData private
Definition at line 197 of file mainwindow.h.
Referenced by exitApplication(), getCurrentUserPreferences(), getSalomePathSlot(), getSolverCommand(), initializeManagers(), initializeUserPreferences(), launchSalomeMeshTool(), on_actionAutomatic_Optimization_triggered(), on_actionClose_Project_triggered(), on_actionLoad_Configuration_Template_triggered(), on_actionLoad_Templates_triggered(), on_actionNew_Multizone_Project_triggered(), on_actionOpen_Multizone_Project_triggered(), on_actionPreferences_triggered(), openRecentFile(), seeParaviewResults(), updateMainWindowElements(), and updateRecentProjectsSection().
QList<VirtualMrfVO> MainWindow::_userVirtualMRFDataList private
Definition at line 235 of file mainwindow.h.
Referenced by clearAllData(), importMeshFile(), on_actionCompare_Configuration_Files_triggered(), on_actionSynchronise_all_files_triggered(), on_basivViewEditButton_clicked(), openProject(), openSolverConfigurationFileDialog(), saveConfigFile(), and updateMultizoneUserData().
QwtPlotCurve* MainWindow::curve private
Definition at line 223 of file mainwindow.h.
SolverPlotter* MainWindow::plotResiduals private
Definition at line 224 of file mainwindow.h.
Referenced by closeProject(), on_actionSave_Residual_Image_triggered(), on_restartButton_clicked(), outlog(), runSolverProject(), and setResidualPlot().
QPolygonF MainWindow::points private
Definition at line 222 of file mainwindow.h.
Ui::MainWindow* MainWindow::ui private
Definition at line 172 of file mainwindow.h.
Referenced by addProjectToRecentProjectsSection(), clearConsoleText(), createProjectActions(), disableAllMainButtons(), enableAllMainButtons(), enableMeshOptions(), enableMultizoneElements(), enableToolButtons(), fillMultizoneTable(), getSelectedFiles(), initializeHelper(), insertMultizoneRow(), launchActionProjectSettingsDialog(), MainWindow(), multizoneSaveAll(), notSavedMultizoneData(), on_actionClose_Project_triggered(), on_actionLoad_Templates_triggered(), on_actionSave_Configuration_File_As_triggered(), on_actionSave_Configuration_File_triggered(), on_basivViewEditButton_clicked(), on_multizoneDeleteButton_clicked(), on_multizoneNewButton_clicked(), on_multizoneOpenEditButton_clicked(), on_multizoneRunSimulationButton_clicked(), on_newActionButton_clicked(), on_openFileActionButton_clicked(), on_projectTreeView_doubleClicked(), on_savePhysicsButton_clicked(), on_seeSummaryChangesButton_clicked(), on_solverButton_clicked(), on_solverTabwidget_tabCloseRequested(), openProject(), outlog(), registerUIMultizoneElements(), resetMultizoneTable(), resetSolverMenu(), resetSolverTabEnabledElements(), runSimulation(), runSolverProject(), setEnableCloseProjectIcons(), setEnabledInputTabSaveButtons(), setEnabledRunIcon(), setEnabledSaveConfigIcons(), setEnableSaveProjectIcons(), setResidualPlot(), slotFinishResult(), slotProcessError(), slotStarted(), updateMainWindowElements(), updateRecentProjectsSection(), and ~MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp
WindowHelper/MainWindow/MainWindowHelper.cpp
WindowHelper/Menu/EditMenuHelper.cpp
WindowHelper/Menu/FileMenuHelper.cpp
WindowHelper/Menu/HelpMenuHelper.cpp
WindowHelper/Menu/SolverMenuHelper.cpp
WindowHelper/Menu/ToolsMenuHelper.cpp
WindowHelper/Menu/ViewMenuHelper.cpp
WindowHelper/Multizone/MultizoneTabHelper.cpp