BBIPED Platform: SolverMarkerMenu Class Reference
SolverMarkerMenu Class Reference
#include <solvermarkermenu.h>
Public Member Functions
SolverMarkerMenu ()
Constructor.
QStringList getDefaultValueList ()
QString getHelp ()
Returns the associated help.
QString getMarkerFileName ()
Get marker value name (marker tag in the file)
QString getMarkerTitle ()
Get the marker title.
QStringList getParametersList ()
Get the parameter list.
QStringList getTypeList ()
gets the type list
QStringList getUnitList ()
get the list of units associated to the different values
bool isEmpty ()
Checks if the object is empty.
void setDefaultValueList (QStringList _list)
void setHelp (QString _helpText)
Sets the help text.
void setMarkerFileName (QString _newFileName)
returns marker value name (marker tag in the file)
void setMarkerTitle (QString _newTitle)
SEt the marker title.
void setParametersList (QStringList _newList)
set the parameter list
void setTypeList (QStringList _newType)
Set the type list.
void setUnitList (QStringList _list)
Set the list of units associated to the different values.
Private Attributes
QStringList _defaultValueList
QString _help
QString _markerFileName
QString _markerTitle
QStringList _parameterList
QStringList _typeList
QStringList _unitList
Detailed Description
Definition at line 6 of file solvermarkermenu.h.
Constructor & Destructor Documentation
SolverMarkerMenu::SolverMarkerMenu ()
Constructor.
Definition at line 24 of file solvermarkermenu.cpp.
References _help, _markerFileName, and _markerTitle.
 {
     _markerTitle = "";
     _markerFileName = "";
     _help = "";
 }
Member Function Documentation
QStringList SolverMarkerMenu::getDefaultValueList ()
Definition at line 167 of file solvermarkermenu.cpp.
References _defaultValueList.
Referenced by SpecificBoundaryVariableDialog::addRow().
 {
     return _defaultValueList;
 }
QString SolverMarkerMenu::getHelp ()
Returns the associated help.
Returns
QString
Definition at line 130 of file solvermarkermenu.cpp.
References _help.
 {
     return _help;
 }
QString SolverMarkerMenu::getMarkerFileName ()
Get marker value name (marker tag in the file)
Returns
QString
Definition at line 70 of file solvermarkermenu.cpp.
References _markerFileName.
 {
     return _markerFileName;
 }
QString SolverMarkerMenu::getMarkerTitle ()
Get the marker title.
Returns
QString
Definition at line 50 of file solvermarkermenu.cpp.
References _markerTitle.
Referenced by MarkerMenuManager::getMarkerNodeByName().
 {
     return _markerTitle;
 }
QStringList SolverMarkerMenu::getParametersList ()
Get the parameter list.
Returns
QStringList
Definition at line 90 of file solvermarkermenu.cpp.
References _parameterList.
Referenced by SpecificBoundaryVariableDialog::addRow().
 {
     return _parameterList;
 }
QStringList SolverMarkerMenu::getTypeList ()
gets the type list
Returns
QStringList
Definition at line 120 of file solvermarkermenu.cpp.
References _typeList.
Referenced by SpecificBoundaryVariableDialog::addRow().
 {
     return _typeList;
 }
QStringList SolverMarkerMenu::getUnitList ()
get the list of units associated to the different values
Returns
QStringList
Definition at line 150 of file solvermarkermenu.cpp.
References _unitList.
Referenced by SpecificBoundaryVariableDialog::addRow().
 {
     return _unitList;
 }
bool SolverMarkerMenu::isEmpty ()
Checks if the object is empty.
Returns
bool
Definition at line 37 of file solvermarkermenu.cpp.
References _help, _markerFileName, and _markerTitle.
 {
     if  ((_markerTitle.isEmpty()) && (_markerFileName.isEmpty()) && (_help.isEmpty()))
          return true;
     else
         return false;
 }
void SolverMarkerMenu::setDefaultValueList (QStringList _list)
Definition at line 172 of file solvermarkermenu.cpp.
References _defaultValueList.
Referenced by MarkerMenuReader::createMarkerNode().
 {
     _defaultValueList = _list;
 }
void SolverMarkerMenu::setHelp (QString _helpText)
Sets the help text.
Parameters
_helpText
Definition at line 140 of file solvermarkermenu.cpp.
References _help.
 {
     _help = _helpText;
 }
void SolverMarkerMenu::setMarkerFileName (QString _newFileName)
returns marker value name (marker tag in the file)
Parameters
_newFileName
Definition at line 80 of file solvermarkermenu.cpp.
References _markerFileName.
Referenced by MarkerMenuReader::createMarkerNode().
 {
     _markerFileName = _newFileName;
 }
void SolverMarkerMenu::setMarkerTitle (QString _newTitle)
SEt the marker title.
Parameters
_newTitle
Definition at line 60 of file solvermarkermenu.cpp.
References _markerTitle.
Referenced by MarkerMenuReader::createMarkerNode().
 {
    _markerTitle = _newTitle;
 }
void SolverMarkerMenu::setParametersList (QStringList _newList)
set the parameter list
Parameters
_newList
Definition at line 100 of file solvermarkermenu.cpp.
References _parameterList.
Referenced by MarkerMenuReader::createMarkerNode().
 {
     _parameterList = _newList;
 }
void SolverMarkerMenu::setTypeList (QStringList _newType)
Set the type list.
Parameters
_newType
Definition at line 110 of file solvermarkermenu.cpp.
References _typeList.
Referenced by MarkerMenuReader::createMarkerNode().
 {
     _typeList = _newType;
 }
void SolverMarkerMenu::setUnitList (QStringList _list)
Set the list of units associated to the different values.
Parameters
_list
Definition at line 161 of file solvermarkermenu.cpp.
References _unitList.
Referenced by MarkerMenuReader::createMarkerNode().
 {
     _unitList = _list;
 }
Member Data Documentation
QStringList SolverMarkerMenu::_defaultValueList private
Definition at line 42 of file solvermarkermenu.h.
Referenced by getDefaultValueList(), and setDefaultValueList().
QString SolverMarkerMenu::_help private
Definition at line 40 of file solvermarkermenu.h.
Referenced by getHelp(), isEmpty(), setHelp(), and SolverMarkerMenu().
QString SolverMarkerMenu::_markerFileName private
Definition at line 37 of file solvermarkermenu.h.
Referenced by getMarkerFileName(), isEmpty(), setMarkerFileName(), and SolverMarkerMenu().
QString SolverMarkerMenu::_markerTitle private
Definition at line 36 of file solvermarkermenu.h.
Referenced by getMarkerTitle(), isEmpty(), setMarkerTitle(), and SolverMarkerMenu().
QStringList SolverMarkerMenu::_parameterList private
Definition at line 38 of file solvermarkermenu.h.
Referenced by getParametersList(), and setParametersList().
QStringList SolverMarkerMenu::_typeList private
Definition at line 39 of file solvermarkermenu.h.
Referenced by getTypeList(), and setTypeList().
QStringList SolverMarkerMenu::_unitList private
Definition at line 41 of file solvermarkermenu.h.
Referenced by getUnitList(), and setUnitList().
The documentation for this class was generated from the following files:
Data/Solver/VO/solvermarkermenu.h
Data/Solver/VO/solvermarkermenu.cpp