BBIPED Platform: SolverVO Class Reference
SolverVO Class Reference
#include <solvervo.h>
Public Member Functions
SolverVO ()
Constructor.
~SolverVO ()
Destructor.
void clear ()
Clear values.
void copy (SolverVO _objToCopy)
Deep copy of one object to other.
QHash< QString, QString > getSolverConfigFileMapValues ()
Returns the solver map values.
QString getSolverConfigFilePath ()
Returns the Solver Config File Path.
QString getSolverFilePath ()
Returns the Solver File Path info.
bool isConfigFileEmpty ()
Checks if the values of the config file are empty.
bool isMeshFileEmpty ()
Checks if the Mesh File Path is empty.
void resetMapValues ()
Reset map valeus.
void setSolverConfigFileMapValues (QHash< QString, QString > _newMapValues)
Set the values for the configuration file.
void setSolverConfigFilePath (QString _path)
Set the Solver Config File Path.
void setSolverFilePath (QString _path)
Set the Solver File Path infor.
void updateSolverConfigFileMapValues (QString _varName, QString _varValue)
Update the solver map values.
Private Attributes
QHash< QString, QString > _solverConfigFileMapValues
QString _solverConfigFilePath
QString _solverEngine
QString _solverFilePath
Detailed Description
Definition at line 8 of file solvervo.h.
Constructor & Destructor Documentation
SolverVO::SolverVO ()
Constructor.
Definition at line 26 of file solvervo.cpp.
References _solverConfigFilePath, _solverEngine, _solverFilePath, and SOLVER_DEFAULT_ENGINE.
 {
     _solverFilePath = "";
     _solverConfigFilePath = "";
     _solverEngine = SOLVER_DEFAULT_ENGINE;
 }
SolverVO::~SolverVO ()
Destructor.
Definition at line 38 of file solvervo.cpp.
 {
 }
Member Function Documentation
void SolverVO::clear ()
Clear values.
Definition at line 169 of file solvervo.cpp.
References _solverConfigFileMapValues, _solverConfigFilePath, and _solverFilePath.
Referenced by ProjectData::clear(), MainWindow::launchActionProjectSettingsDialog(), and ProjectSettingsDialog::updateProjectData().
 {
     _solverFilePath = "";
     _solverConfigFilePath = "";
     _solverConfigFileMapValues.clear();
 }
void SolverVO::copy (SolverVO _objToCopy)
Deep copy of one object to other.
Parameters
_objToCopy
Definition at line 149 of file solvervo.cpp.
References getSolverConfigFilePath(), getSolverFilePath(), setSolverConfigFilePath(), and setSolverFilePath().
Referenced by ProjectData::setSolverDataInformation().
 {
     this->setSolverConfigFilePath(_objToCopy.getSolverConfigFilePath());
     this->setSolverFilePath(_objToCopy.getSolverFilePath());
 }
QHash< QString, QString > SolverVO::getSolverConfigFileMapValues ()
Returns the solver map values.
Returns
QHash<QString, QString>
Definition at line 126 of file solvervo.cpp.
References _solverConfigFileMapValues.
Referenced by MainWindow::saveConfigFile().
 {
     return _solverConfigFileMapValues;
 }
QString SolverVO::getSolverConfigFilePath ()
Returns the Solver Config File Path.
Returns
QString
Definition at line 105 of file solvervo.cpp.
References _solverConfigFilePath.
Referenced by MainWindow::buildSolverCommand(), MainWindow::checkMeshNames(), MainWindow::checkProjectBasePathConsistency(), MainWindow::closeProject(), copy(), InputDataTabHelper::enableConfigurationViewMenu(), InputDataTabHelper::fillFileNamesInTab(), MultizoneManager::getConfigurationFilePosition(), MainWindow::launchActionProjectSettingsDialog(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::runSolverProject(), InputDataTabHelper::saveAsConfigFile(), MainWindow::saveConfigFile(), ProjectSettingsDialog::updateFileTableInSettingsView(), ProjectSettingsDialog::updateProjectData(), UtilFiles::updateProjectDataToFile(), InputDataTabHelper::updateSolverUserValues(), and UtilFiles::updateToolPaths().
 {
     return _solverConfigFilePath;
 }
QString SolverVO::getSolverFilePath ()
Returns the Solver File Path info.
Returns
QString
Definition at line 85 of file solvervo.cpp.
References _solverFilePath.
Referenced by MainWindow::checkProjectBasePathConsistency(), copy(), MainWindow::enableMeshOptions(), InputDataTabHelper::fillFileNamesInTab(), MainWindow::importMeshFile(), MainWindow::importMeshInfoFile(), MainWindow::on_newActionButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::saveConfigFile(), ProjectSettingsDialog::updateFileTableInSettingsView(), MultizoneManager::updateOpenEditConfigFile(), ProjectSettingsDialog::updateProjectData(), UtilFiles::updateProjectDataToFile(), InputDataTabHelper::updateSolverUserValues(), and UtilFiles::updateToolPaths().
 {
     return _solverFilePath;
 }
bool SolverVO::isConfigFileEmpty ()
Checks if the values of the config file are empty.
Returns
bool
Definition at line 62 of file solvervo.cpp.
References _solverConfigFilePath.
Referenced by MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_openFileActionButton_clicked(), ProjectData::solverDataComplete(), and UtilFiles::updateToolPaths().
 {
     if (_solverConfigFilePath.isEmpty())
         return true;
     else
         return false;
 }
bool SolverVO::isMeshFileEmpty ()
Checks if the Mesh File Path is empty.
Returns
bool
Definition at line 49 of file solvervo.cpp.
References _solverFilePath.
Referenced by MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_openFileActionButton_clicked(), ProjectData::solverDataComplete(), and UtilFiles::updateToolPaths().
 {
     if (_solverFilePath.isEmpty())
         return true;
     else
         return false;
 }
void SolverVO::resetMapValues ()
Reset map valeus.
Definition at line 160 of file solvervo.cpp.
References _solverConfigFileMapValues.
 {
     this->_solverConfigFileMapValues.clear();
 }
void SolverVO::setSolverConfigFileMapValues (QHash< QString, QString > _newMapValues)
Set the values for the configuration file.
Parameters
QHash<QString
_newMapValues
Definition at line 116 of file solvervo.cpp.
References _solverConfigFileMapValues.
 {
     _solverConfigFileMapValues = _newMapValues;
 }
void SolverVO::setSolverConfigFilePath (QString _path)
Set the Solver Config File Path.
Parameters
_path
Definition at line 95 of file solvervo.cpp.
References _solverConfigFilePath.
Referenced by MultizoneManager::buildProjectDataForMultizoneProject(), MainWindow::checkProjectBasePathConsistency(), copy(), XmlUtil::getSU2Information(), MainWindow::on_actionSave_Configuration_File_As_triggered(), MainWindow::on_newActionButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), InputDataTabHelper::saveAsConfigFile(), SolverUtil::uiImportSolverConfigFile(), and UtilFiles::updateToolPaths().
 {
     _solverConfigFilePath = _path;
 }
void SolverVO::setSolverFilePath (QString _path)
Set the Solver File Path infor.
Parameters
_path
Definition at line 75 of file solvervo.cpp.
References _solverFilePath.
Referenced by MultizoneManager::buildProjectDataForMultizoneProject(), MainWindow::checkProjectBasePathConsistency(), copy(), XmlUtil::getSU2Information(), MainWindow::importMeshFile(), MainWindow::saveMeshVariables(), SolverUtil::uiImportSolverMeshFile(), SolverUtil::uiImportSolverMeshInfoFile(), and UtilFiles::updateToolPaths().
 {
     _solverFilePath = _path;
 }
void SolverVO::updateSolverConfigFileMapValues (QString _varName, QString _varValue)
Update the solver map values.
Parameters
_varName
_varValue
Definition at line 138 of file solvervo.cpp.
References _solverConfigFileMapValues.
 {
     // If the variable does not exist, create it, otherwise, the variable is updated
     _solverConfigFileMapValues.insert(_varName,_varValue);
 }
Member Data Documentation
QHash<QString, QString> SolverVO::_solverConfigFileMapValues private
Definition at line 40 of file solvervo.h.
Referenced by clear(), getSolverConfigFileMapValues(), resetMapValues(), setSolverConfigFileMapValues(), and updateSolverConfigFileMapValues().
QString SolverVO::_solverConfigFilePath private
Definition at line 39 of file solvervo.h.
Referenced by clear(), getSolverConfigFilePath(), isConfigFileEmpty(), setSolverConfigFilePath(), and SolverVO().
QString SolverVO::_solverEngine private
Definition at line 41 of file solvervo.h.
Referenced by SolverVO().
QString SolverVO::_solverFilePath private
Definition at line 38 of file solvervo.h.
Referenced by clear(), getSolverFilePath(), isMeshFileEmpty(), setSolverFilePath(), and SolverVO().
The documentation for this class was generated from the following files:
Data/Solver/VO/solvervo.h
Data/Solver/VO/solvervo.cpp