BBIPED Platform: MultizoneIndividualTabForm Class Reference
MultizoneIndividualTabForm Class Reference
#include <multizoneindividualtabform.h>
Public Member Functions
MultizoneIndividualTabForm (QWidget *parent=0)
~MultizoneIndividualTabForm ()
QString getConfigFile ()
QHash< QString, QString > * getConfigValues ()
QString getMeshFile ()
QList< VirtualMrfVO > * getVirtualValues ()
bool isDataModified ()
void registerInitialStructures (MainWindow *_object, SolverConfigManager *_manager)
void savedData ()
void setConfigFile (QString _filePath)
void setMeshFile (QString _filePath)
void setProjectPath (QString _path)
Private Types
enum iconSelection
Private Slots
void on_cancelButton_clicked ()
void on_closeButton_clicked ()
void on_editBoundConfigButton_clicked ()
void on_editConfigFileButton_clicked ()
void on_importMeshFileButton_clicked ()
void on_saveButton_clicked ()
Private Member Functions
void addSaveIconTab (int _option)
void closeTab ()
void getLoadedBoundaryValues ()
void removeAssociatedMeshValues ()
void updateBoundaryValues ()
Private Attributes
QHash< QString, QString > * _bndMeshVal
QHash< QString, QString > * _bndValuesSolver
QString _configFile
QHash< QString, QString > * _configVal
QString _meshFile
bool _needToSave
MainWindow * _parentWindow
QString _projectPath
InputDataTabHelper * _regTabHelper
SolverConfigManager * _solverManager
int _tabIndex
QList< VirtualMrfVO > * _virtualMRFList
Ui::MultizoneIndividualTabForm * ui
Detailed Description
Definition at line 16 of file multizoneindividualtabform.h.
Member Enumeration Documentation
enum MultizoneIndividualTabForm::iconSelection private
Enumerator
iconSaveSepia
noIcon
Definition at line 74 of file multizoneindividualtabform.h.
                       {
         iconSaveSepia = 0,
         noIcon = -1
     };
Constructor & Destructor Documentation
MultizoneIndividualTabForm::MultizoneIndividualTabForm (QWidget * parent = 0) explicit
Definition at line 34 of file multizoneindividualtabform.cpp.
References _bndMeshVal, _bndValuesSolver, _configFile, _configVal, _meshFile, _needToSave, _virtualMRFList, and ui.
                                                                       :
     QWidget(parent),
     ui(new Ui::MultizoneIndividualTabForm)
 {
     ui->setupUi(this);
     _configFile ="";
     _meshFile ="";
     _needToSave = false;
     _configVal = new QHash<QString,QString>();
     _bndMeshVal = new QHash<QString,QString>();
     _virtualMRFList = new QList<VirtualMrfVO>();
     _bndValuesSolver = new QHash<QString,QString>();
     // set up the initial view
     ui->saveButton->setEnabled(false);
 }
MultizoneIndividualTabForm::~MultizoneIndividualTabForm ()
Definition at line 53 of file multizoneindividualtabform.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void MultizoneIndividualTabForm::addSaveIconTab (int _option) private
Definition at line 71 of file multizoneindividualtabform.cpp.
References iconSaveSepia.
Referenced by on_editBoundConfigButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), and savedData().
 {
     QTabWidget * _tabWidget = qobject_cast<QTabWidget *> (parent()->parent());
     if (_tabWidget)
     {
         int _index = _tabWidget->indexOf(this);
         QIcon _icon;
         switch (_option)
         {
             case iconSaveSepia:
                 _icon.addFile(":/new/toolbarIcons/images/disk_sepia.png");
                 break;
             otherwise:
                 _icon.addFile("");
                 break;
         }
         _tabWidget->setTabIcon(_index,_icon);
     }
 }
void MultizoneIndividualTabForm::closeTab () private
Definition at line 244 of file multizoneindividualtabform.cpp.
Referenced by on_cancelButton_clicked(), and on_closeButton_clicked().
 {
     QTabWidget * _tabWidget = qobject_cast<QTabWidget *> (parent()->parent());
     if (_tabWidget)
     {
         int _index = _tabWidget->indexOf(this);
         _tabWidget->removeTab(_index);
         close();
     }
 }
QString MultizoneIndividualTabForm::getConfigFile ()
Definition at line 305 of file multizoneindividualtabform.cpp.
References _configFile.
Referenced by MainWindow::multizoneSaveAll().
 {
     return _configFile;
 }
QHash< QString, QString > * MultizoneIndividualTabForm::getConfigValues ()
Definition at line 315 of file multizoneindividualtabform.cpp.
References _configVal.
Referenced by MainWindow::multizoneSaveAll().
 {
     return _configVal;
 }
void MultizoneIndividualTabForm::getLoadedBoundaryValues () private
Definition at line 143 of file multizoneindividualtabform.cpp.
References _bndValuesSolver, _configVal, BC_PREFIX, and MARKER_PREFIX.
Referenced by on_editBoundConfigButton_clicked().
 {
     if (!_configVal->isEmpty())
     {
         QHashIterator<QString,QString> _iter(*_configVal);
         while (_iter.hasNext())
         {
             _iter.next();
             QString _keyVal = _iter.key();
             QString _val = _iter.value();
             if( (!_keyVal.isEmpty()) && (!_val.isEmpty()) )
                 if (( (_keyVal.contains(MARKER_PREFIX)) ||
                      (_keyVal.contains(BC_PREFIX))) &&
                     (!_val.contains("NONE") ) )
                 {
                     if (_val.contains("("))
                         _val.remove("(");
                     if (_val.contains(")"))
                         _val.remove(")");
                     _bndValuesSolver->insert(_keyVal,_val);
                 }
         }
     }
 }
QString MultizoneIndividualTabForm::getMeshFile ()
Definition at line 310 of file multizoneindividualtabform.cpp.
References _meshFile.
Referenced by MainWindow::multizoneSaveAll().
 {
     return _meshFile;
 }
QList< VirtualMrfVO > * MultizoneIndividualTabForm::getVirtualValues ()
Definition at line 320 of file multizoneindividualtabform.cpp.
References _virtualMRFList.
Referenced by MainWindow::multizoneSaveAll().
 {
     return _virtualMRFList;
 }
bool MultizoneIndividualTabForm::isDataModified ()
Definition at line 300 of file multizoneindividualtabform.cpp.
References _needToSave.
Referenced by MainWindow::multizoneSaveAll(), and MainWindow::notSavedMultizoneData().
 {
     return _needToSave;
 }
void MultizoneIndividualTabForm::on_cancelButton_clicked () private slot
Definition at line 256 of file multizoneindividualtabform.cpp.
References _configFile, _configVal, _meshFile, _needToSave, _parentWindow, _virtualMRFList, closeTab(), MainWindow::saveMultizoneData(), and ShowMessageHelper::showWarningMessage().
 {
     if (_needToSave)
     {
         ShowMessageHelper _warningMsg;
         bool _saveResults = _warningMsg.showWarningMessage("Unsaved Changes!","You need to save your modifications. Do you want to save?");
         if (_saveResults)
             _parentWindow->saveMultizoneData(_configFile, _meshFile, _configVal,_virtualMRFList);
     }
     closeTab();
 }
void MultizoneIndividualTabForm::on_closeButton_clicked () private slot
Definition at line 230 of file multizoneindividualtabform.cpp.
References _configFile, _configVal, _meshFile, _needToSave, _parentWindow, _virtualMRFList, closeTab(), MainWindow::saveMultizoneData(), and ShowMessageHelper::showWarningMessage().
 {
   if (_needToSave)
   {
       ShowMessageHelper _warningMsg;
       bool _saveResults = _warningMsg.showWarningMessage("Unsaved Changes!","You need to save your modifications. Do you want to save?");
       if (_saveResults)
           _parentWindow->saveMultizoneData(_configFile, _meshFile, _configVal,_virtualMRFList);
   }
   // Closing the tab
   closeTab();
 }
void MultizoneIndividualTabForm::on_editBoundConfigButton_clicked () private slot
Definition at line 170 of file multizoneindividualtabform.cpp.
References _bndMeshVal, _bndValuesSolver, _configVal, _needToSave, _solverManager, addSaveIconTab(), getLoadedBoundaryValues(), MeshDialog::getUserBndVariableValues(), MeshDialog::hasUserAcceptChanges(), iconSaveSepia, MeshDialog::loadMenu(), MeshDialog::setIsMultizoneProject(), MeshDialog::setIsNSProblem(), MeshDialog::setMeshValues(), MeshDialog::setSolverConfigManager(), MeshDialog::setUserConfiguredMeshValues(), StrEqual, ui, and updateBoundaryValues().
 {
     if (_bndValuesSolver->isEmpty())
         getLoadedBoundaryValues();
     MeshDialog * _meshWindow = new MeshDialog(this);
     _meshWindow->setMeshValues(*_bndMeshVal);
     _meshWindow->setSolverConfigManager(_solverManager);
     _meshWindow->setUserConfiguredMeshValues(*_bndValuesSolver); //TBR
     _meshWindow->setIsMultizoneProject(true);
     bool _isNSProblem = false;
     if (!_configVal->isEmpty())
     {
         QString _physicalPbVal = _configVal->value("PHYSICAL_PROBLEM");
         if (QString::compare(_physicalPbVal,"NAVIER_STOKES") == StrEqual)
             _isNSProblem = true;
         else _isNSProblem = false;
     }
     _meshWindow->setIsNSProblem(_isNSProblem);
     _meshWindow->loadMenu();
     _meshWindow->exec();
     if (_meshWindow->hasUserAcceptChanges())
     {
         (* _bndValuesSolver) = _meshWindow->getUserBndVariableValues();
          updateBoundaryValues();
         _needToSave = true;
         ui->saveButton->setEnabled(true);
         addSaveIconTab(iconSaveSepia);
     }
 }
void MultizoneIndividualTabForm::on_editConfigFileButton_clicked () private slot
Definition at line 58 of file multizoneindividualtabform.cpp.
References _configVal, _needToSave, _parentWindow, _regTabHelper, _solverManager, _virtualMRFList, addSaveIconTab(), iconSaveSepia, InputDataTabHelper::launchSolverConfigDialog(), and ui.
 {
     // TODO --> The 3D configuration for VMRF is disabled, only 2D accepted at the moment
     // MUst check how is the behaviour in Multizone
     _needToSave = _regTabHelper->launchSolverConfigDialog(_parentWindow,true,
                                                                _configVal,_solverManager,_virtualMRFList,false);
     if (_needToSave)
     {
         ui->saveButton->setEnabled(true);
         addSaveIconTab(iconSaveSepia);
     }
 }
void MultizoneIndividualTabForm::on_importMeshFileButton_clicked () private slot
Definition at line 93 of file multizoneindividualtabform.cpp.
References _bndMeshVal, _bndValuesSolver, _configVal, _meshFile, _needToSave, _parentWindow, _projectPath, _regTabHelper, _virtualMRFList, addSaveIconTab(), iconSaveSepia, UtilFiles::importFile(), InputDataTabHelper::parseFile(), ParserSolverMeshFile, removeAssociatedMeshValues(), ShowMessageHelper::showWarningMessage(), TOOL4, and ui.
 {
     if (!_meshFile.isEmpty())
     {
         ShowMessageHelper _msgHelper;
         bool _overWrite = _msgHelper.showWarningMessage("Mesh File Overwrite!","If you import a new file, you will loose all your previous configuration. Do you want to continue?");
         if (!_overWrite)
             return;
     }
     QString _meshFilePath = QFileDialog::getOpenFileName(_parentWindow,"Import SU2 Mesh File",
                                                             QDir(_projectPath).filePath(TOOL4),
                                                             "SU2 Mesh File (*.su2)");
     if (_meshFilePath.isNull())
          return;
     // Step 1. Import the mesh File into the project folder
     UtilFiles _utilHelper;
     _meshFile = _utilHelper.importFile(QFileInfo(_projectPath).path(),_meshFilePath,TOOL4);
     // Step 2. Reset previous Bnd Values
     _bndMeshVal->clear();
     _bndValuesSolver->clear();
      removeAssociatedMeshValues();
     // Step 2. Parse the mesh file to get the bnd Variables
     _regTabHelper->parseFile(ParserSolverMeshFile,_meshFile,_configVal,_bndMeshVal,_virtualMRFList);
     _configVal->insert("MESH_FILENAME",_meshFile);
     // Step 4. Update the view
     ui->currentMeshFileLabel->setText(QFileInfo(_meshFile).fileName());
     _needToSave = true;
     ui->saveButton->setEnabled(true);
     addSaveIconTab(iconSaveSepia);
 }
void MultizoneIndividualTabForm::on_saveButton_clicked () private slot
Definition at line 217 of file multizoneindividualtabform.cpp.
References _configFile, _configVal, _meshFile, _parentWindow, _virtualMRFList, savedData(), and MainWindow::saveMultizoneData().
 {
     _parentWindow->saveMultizoneData(_configFile, _meshFile, _configVal,_virtualMRFList);
     savedData();
 }
void MultizoneIndividualTabForm::registerInitialStructures (MainWindow * _object, SolverConfigManager * _manager)
Definition at line 290 of file multizoneindividualtabform.cpp.
References _parentWindow, and _solverManager.
Referenced by MainWindow::on_multizoneOpenEditButton_clicked().
 {
      _parentWindow = _object;
      _solverManager = _manager;
 }
void MultizoneIndividualTabForm::removeAssociatedMeshValues () private
Definition at line 128 of file multizoneindividualtabform.cpp.
References _configVal, BC_PREFIX, and MARKER_PREFIX.
Referenced by on_importMeshFileButton_clicked(), and updateBoundaryValues().
 {
     if (!_configVal->isEmpty())
     {
         QHashIterator<QString,QString> _iter(*_configVal);
         while(_iter.hasNext())
         {
             _iter.next();
             QString _keyName = _iter.key();
             if( (_keyName.contains(MARKER_PREFIX)) || (_keyName.contains(BC_PREFIX)) )
                  _configVal->insert(_keyName,"NONE");
         }
     }
 }
void MultizoneIndividualTabForm::savedData ()
Definition at line 223 of file multizoneindividualtabform.cpp.
References _needToSave, addSaveIconTab(), noIcon, and ui.
Referenced by MainWindow::multizoneSaveAll(), and on_saveButton_clicked().
 {
     ui->saveButton->setEnabled(false);
     addSaveIconTab(noIcon);
     _needToSave = false;
 }
void MultizoneIndividualTabForm::setConfigFile (QString _filePath)
Definition at line 271 of file multizoneindividualtabform.cpp.
References _bndMeshVal, _configFile, _configVal, _regTabHelper, _virtualMRFList, InputDataTabHelper::parseFile(), ParserSolverConfigFile, and ui.
Referenced by MainWindow::on_multizoneOpenEditButton_clicked().
 {
     _configFile = _filePath;
     ui->currentConfigFileLabel->setText(QFileInfo(_configFile).fileName());
     if (_configFile.isEmpty())
         return;
     _regTabHelper->parseFile(ParserSolverConfigFile,_configFile,_configVal,_bndMeshVal,_virtualMRFList);
 }
void MultizoneIndividualTabForm::setMeshFile (QString _filePath)
Definition at line 280 of file multizoneindividualtabform.cpp.
References _bndMeshVal, _configVal, _meshFile, _regTabHelper, _virtualMRFList, InputDataTabHelper::parseFile(), ParserSolverMeshFile, and ui.
Referenced by MainWindow::on_multizoneOpenEditButton_clicked().
 {
     _meshFile = _filePath;
     ui->currentMeshFileLabel->setText(QFileInfo(_meshFile).fileName());
     if (_meshFile.isEmpty())
         return;
     _regTabHelper->parseFile(ParserSolverMeshFile,_meshFile,_configVal,_bndMeshVal,_virtualMRFList);
 }
void MultizoneIndividualTabForm::setProjectPath (QString _path)
Definition at line 295 of file multizoneindividualtabform.cpp.
References _projectPath.
Referenced by MainWindow::on_multizoneOpenEditButton_clicked().
 {
     _projectPath = _path;
 }
void MultizoneIndividualTabForm::updateBoundaryValues () private
Definition at line 201 of file multizoneindividualtabform.cpp.
References _bndValuesSolver, _configVal, and removeAssociatedMeshValues().
Referenced by on_editBoundConfigButton_clicked().
 {
     removeAssociatedMeshValues();
     if (!_bndValuesSolver->isEmpty())
     {
         QHashIterator<QString,QString> _iter(*_bndValuesSolver);
         while (_iter.hasNext())
         {
             _iter.next();
             QString _keyname = _iter.key();
             QString _value = _iter.value();
             _configVal->insert(_keyname,_value);
         }
     }
 }
Member Data Documentation
QHash<QString,QString>* MultizoneIndividualTabForm::_bndMeshVal private
Definition at line 67 of file multizoneindividualtabform.h.
Referenced by MultizoneIndividualTabForm(), on_editBoundConfigButton_clicked(), on_importMeshFileButton_clicked(), setConfigFile(), and setMeshFile().
QHash<QString,QString>* MultizoneIndividualTabForm::_bndValuesSolver private
Definition at line 66 of file multizoneindividualtabform.h.
Referenced by getLoadedBoundaryValues(), MultizoneIndividualTabForm(), on_editBoundConfigButton_clicked(), on_importMeshFileButton_clicked(), and updateBoundaryValues().
QString MultizoneIndividualTabForm::_configFile private
Definition at line 52 of file multizoneindividualtabform.h.
Referenced by getConfigFile(), MultizoneIndividualTabForm(), on_cancelButton_clicked(), on_closeButton_clicked(), on_saveButton_clicked(), and setConfigFile().
QHash<QString,QString>* MultizoneIndividualTabForm::_configVal private
Definition at line 61 of file multizoneindividualtabform.h.
Referenced by getConfigValues(), getLoadedBoundaryValues(), MultizoneIndividualTabForm(), on_cancelButton_clicked(), on_closeButton_clicked(), on_editBoundConfigButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), on_saveButton_clicked(), removeAssociatedMeshValues(), setConfigFile(), setMeshFile(), and updateBoundaryValues().
QString MultizoneIndividualTabForm::_meshFile private
Definition at line 53 of file multizoneindividualtabform.h.
Referenced by getMeshFile(), MultizoneIndividualTabForm(), on_cancelButton_clicked(), on_closeButton_clicked(), on_importMeshFileButton_clicked(), on_saveButton_clicked(), and setMeshFile().
bool MultizoneIndividualTabForm::_needToSave private
Definition at line 69 of file multizoneindividualtabform.h.
Referenced by isDataModified(), MultizoneIndividualTabForm(), on_cancelButton_clicked(), on_closeButton_clicked(), on_editBoundConfigButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), and savedData().
MainWindow* MultizoneIndividualTabForm::_parentWindow private
Definition at line 57 of file multizoneindividualtabform.h.
Referenced by on_cancelButton_clicked(), on_closeButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), on_saveButton_clicked(), and registerInitialStructures().
QString MultizoneIndividualTabForm::_projectPath private
Definition at line 54 of file multizoneindividualtabform.h.
Referenced by on_importMeshFileButton_clicked(), and setProjectPath().
InputDataTabHelper* MultizoneIndividualTabForm::_regTabHelper private
Definition at line 63 of file multizoneindividualtabform.h.
Referenced by on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), setConfigFile(), and setMeshFile().
SolverConfigManager* MultizoneIndividualTabForm::_solverManager private
Definition at line 58 of file multizoneindividualtabform.h.
Referenced by on_editBoundConfigButton_clicked(), on_editConfigFileButton_clicked(), and registerInitialStructures().
int MultizoneIndividualTabForm::_tabIndex private
Definition at line 70 of file multizoneindividualtabform.h.
QList<VirtualMrfVO>* MultizoneIndividualTabForm::_virtualMRFList private
Definition at line 62 of file multizoneindividualtabform.h.
Referenced by getVirtualValues(), MultizoneIndividualTabForm(), on_cancelButton_clicked(), on_closeButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), on_saveButton_clicked(), setConfigFile(), and setMeshFile().
Ui::MultizoneIndividualTabForm* MultizoneIndividualTabForm::ui private
Definition at line 51 of file multizoneindividualtabform.h.
Referenced by MultizoneIndividualTabForm(), on_editBoundConfigButton_clicked(), on_editConfigFileButton_clicked(), on_importMeshFileButton_clicked(), savedData(), setConfigFile(), setMeshFile(), and ~MultizoneIndividualTabForm().
The documentation for this class was generated from the following files:
WindowHelper/Multizone/multizoneindividualtabform.h
WindowHelper/Multizone/multizoneindividualtabform.cpp