BBIPED Platform: DomItem Class Reference
DomItem Class Reference
[0]
#include <domitem.h>
Public Member Functions
DomItem (QDomNode &node, int row, DomItem *parent=0)
Cosntructor Item element of the DOM tree.
~DomItem ()
Destructor.
DomItem * child (int i)
Child of the DOM item.
QDomNode node () const
Node of the DOM item.
DomItem * parent ()
Parent of the DOM item.
int row ()
Row number of the DOM item.
Private Attributes
QHash< int, DomItem * > childItems
QDomNode domNode
DomItem * parentItem
int rowNumber
Detailed Description
[0]
Definition at line 8 of file domitem.h.
Constructor & Destructor Documentation
DomItem::DomItem (QDomNode & node, int row, DomItem * parent = 0)
Cosntructor Item element of the DOM tree.
Parameters
node
row
parent
Definition at line 54 of file domitem.cpp.
References domNode, node(), parent(), parentItem, row(), and rowNumber.
Referenced by child().
 {
     domNode = node;
     // Record the item's location within its parent.
     rowNumber = row;
     parentItem = parent;
 }
DomItem::~DomItem ()
Destructor.
Definition at line 69 of file domitem.cpp.
References childItems.
 {
     QHash<int,DomItem*>::iterator it;
     for (it = childItems.begin(); it != childItems.end(); ++it)
         delete it.value();
 }
Member Function Documentation
DomItem * DomItem::child (int i)
Child of the DOM item.
Parameters
i
Returns
DomItem
Definition at line 108 of file domitem.cpp.
References childItems, DomItem(), and domNode.
Referenced by DomModel::index().
 {
     if (childItems.contains(i))
         return childItems[i];
     if (i >= 0 && i < domNode.childNodes().count()) {
         QDomNode childNode = domNode.childNodes().item(i);
         DomItem *childItem = new DomItem(childNode, i, this);
         childItems[i] = childItem;
         return childItem;
     }
     return 0;
 }
QDomNode DomItem::node () const
Node of the DOM item.
Returns
QDomNode
Definition at line 83 of file domitem.cpp.
References domNode.
Referenced by DomModel::data(), DomItem(), and DomModel::rowCount().
 {
     return domNode;
 }
DomItem * DomItem::parent ()
Parent of the DOM item.
Returns
DomItem
Definition at line 95 of file domitem.cpp.
References parentItem.
Referenced by DomItem(), and DomModel::parent().
 {
     return parentItem;
 }
int DomItem::row ()
Row number of the DOM item.
Returns
int
Definition at line 129 of file domitem.cpp.
References rowNumber.
Referenced by DomItem(), and DomModel::parent().
 {
     return rowNumber;
 }
Member Data Documentation
QHash<int,DomItem*> DomItem::childItems private
Definition at line 20 of file domitem.h.
Referenced by child(), and ~DomItem().
QDomNode DomItem::domNode private
Definition at line 19 of file domitem.h.
Referenced by child(), DomItem(), and node().
DomItem* DomItem::parentItem private
Definition at line 21 of file domitem.h.
Referenced by DomItem(), and parent().
int DomItem::rowNumber private
Definition at line 22 of file domitem.h.
Referenced by DomItem(), and row().
The documentation for this class was generated from the following files:
Utility/Model/DomModel/domitem.h
Utility/Model/DomModel/domitem.cpp