BBIPED Platform: FileComparisonDialog Class Reference
FileComparisonDialog Class Reference
#include <filecomparisondialog.h>
Public Member Functions
FileComparisonDialog (QWidget *parent=0)
Constructor.
~FileComparisonDialog ()
Destructor.
void setFilesToCompare (QStringList _list)
Set the list of files to be compared.
void setProjectDetails (ProjectDetails _details)
Set the project details.
void setSectionMenuList (QList< SolverSectionVO > _list)
Set the section Menu List.
void setVirtualMRFData (QList< VirtualMrfVO > _list)
Private Slots
void changedComboValueByUser (QString position)
Slot: Controls if the user change the value in a combo.
void on_buttonBox_accepted ()
Action that controls when the user accept the changes.
void on_buttonBox_rejected ()
Action that controls when the user reject the changes.
void on_compareButton_clicked ()
This function allows to compare the files.
void textChangedSlot (QString _position)
Slot: Controls if the user change the value of a line Edit.
Private Member Functions
void addSignals ()
Add signals to the combos and the line edits to control user input.
void addSignalToCombo (QComboBox *_combo, int _idRow, int _idCol)
This function add the signal to a combo.
void addSignalToLinEdit (QLineEdit *_lineEdit, int _idRow, int _idCol)
This function add the signal to a line Edit.
bool areAllEmpty (QList< QHash< QString, QString > > _list)
Check if the lists are all Empty.
void buildRow (QString _keyval, QString _value)
This function build the individual rows according with the data.
QCheckBox * createCheckBoxElement (QString _name)
void fillRowWithData (SolverVariableVO _varVO, QStringList _valueList)
This function fill the row with the data.
void fillUserValueInCell (SolverVariableVO _varVO, QString _userValue, int _row, int _col)
This function fill the User Values in the cell.
QString getComparedValuesList (QString _keyValue)
Get the list of values for a specific keyvalue.
void getDifferences ()
Get the differences among the files.
int getIdSmallVariableSet (QList< QHash< QString, QString > > _list, QStringList _removedPositions)
Get the id of the list with less values.
void hideColumnsView ()
void insertHeaderTitles ()
This function insert the Header titles.
bool isDifferent (QString _keyValue)
Check if for a keyvalue are different values.
void loadFileValues (QString _fileName)
This function loads the values of a file.
void resetTable ()
This function reset the table values.
void saveUserChanges (QString _value, int _row, int _col)
This function saves the changes made by the user.
void showValuesInTable ()
This function shows those values that are different in the table.
void updateTableHeader ()
This function updates the Header table.
Private Attributes
QHash< QString, QString > _differentValues
QStringList _filesToCompare
QList< QHash< QString, QString > > _loadedValues
QList< SolverSectionVO > _menuSectionList
ProjectDetails _projectDetails
QSignalMapper * _signalMapper
QSignalMapper * _signalMapperTxtEdit
QList< bool > _statusSelection
QList< QHash< QString, QString > > _virtualLoadedValues
QList< VirtualMrfVO > _virtualMRFData
Ui::FileComparisonDialog * ui
Detailed Description
Definition at line 24 of file filecomparisondialog.h.
Constructor & Destructor Documentation
FileComparisonDialog::FileComparisonDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 39 of file filecomparisondialog.cpp.
References _signalMapper, _signalMapperTxtEdit, and ui.
                                                           :
     QDialog(parent),
     ui(new Ui::FileComparisonDialog)
 {
     ui->setupUi(this);
     _signalMapper = new QSignalMapper(this);
     //_isLoadingTable = false;
     _signalMapper = new QSignalMapper(this);
     _signalMapperTxtEdit = new QSignalMapper(this);
 }
FileComparisonDialog::~FileComparisonDialog ()
Destructor.
Definition at line 54 of file filecomparisondialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void FileComparisonDialog::addSignals () private
Add signals to the combos and the line edits to control user input.
Definition at line 585 of file filecomparisondialog.cpp.
References _filesToCompare, _signalMapper, _signalMapperTxtEdit, addSignalToCombo(), addSignalToLinEdit(), changedComboValueByUser(), INITIAL_COL_VALUES, textChangedSlot(), and ui.
Referenced by showValuesInTable().
 {
     bool _foundCombos = false;
     bool _foundLineEdit = false;
     int _tableSize = ui->comparisonTable->rowCount();
     if ( _tableSize > 0)
     {
         for (int i = 0; i< _tableSize;i++)
         {
             for (int j = 0; j < _filesToCompare.size(); j++)
             {
                 QWidget * _item;
                 int _cPosition = INITIAL_COL_VALUES +j;
                 _item = ui->comparisonTable->cellWidget(i,_cPosition);
                 if (_item)
                 {
                     QComboBox *_comboItem = qobject_cast<QComboBox *> (_item);
                     if (_comboItem)
                     {
                         addSignalToCombo(_comboItem,i, _cPosition);
                         _foundCombos = true;
                     }else
                     {
                         QLineEdit * _lineEdit = qobject_cast<QLineEdit *> (_item);
                         if (_lineEdit)
{
                             addSignalToLinEdit(_lineEdit,i,_cPosition);
                             _foundLineEdit = true;
                         }
                     }
                 }
             }
         }
     }
     if (_foundCombos)
         connect(_signalMapper, SIGNAL(mapped(const QString &)),this, SLOT(changedComboValueByUser(const QString &)),Qt::UniqueConnection);
     if (_foundLineEdit)
         connect(_signalMapperTxtEdit, SIGNAL(mapped(const QString &)),this, SLOT(textChangedSlot(const QString &)),Qt::UniqueConnection);
 }
void FileComparisonDialog::addSignalToCombo (QComboBox * _combo, int _idRow, int _idCol) private
This function add the signal to a combo.
Parameters
_combo
_idRow
_idCol
Definition at line 637 of file filecomparisondialog.cpp.
References _signalMapper.
Referenced by addSignals().
 {
       if (_combo->isEditable())
         {
             connect(_combo,SIGNAL(editTextChanged(QString)),_signalMapper,SLOT(map()),Qt::UniqueConnection);
             _signalMapper->setMapping(_combo,QString("%1-%2").arg(_idRow).arg(_idCol));
         }
         connect(_combo, SIGNAL(currentIndexChanged(int)), _signalMapper, SLOT(map()),Qt::UniqueConnection);
        _signalMapper->setMapping(_combo, QString("%1-%2").arg(_idRow).arg(_idCol));
 }
void FileComparisonDialog::addSignalToLinEdit (QLineEdit * _lineEdit, int _idRow, int _idCol) private
This function add the signal to a line Edit.
Parameters
_lineEdit
_idRow
_idCol
Definition at line 655 of file filecomparisondialog.cpp.
References _signalMapperTxtEdit.
Referenced by addSignals().
 {
         connect(_lineEdit,SIGNAL(editingFinished()),_signalMapperTxtEdit,SLOT(map()),Qt::UniqueConnection);
         _signalMapperTxtEdit->setMapping(_lineEdit,QString("%1-%2").arg(_idRow).arg(_idCol));
 }
bool FileComparisonDialog::areAllEmpty (QList< QHash< QString, QString > > _list) private
Check if the lists are all Empty.
Parameters
QList<QHash<QString
_list
Returns
bool
Definition at line 525 of file filecomparisondialog.cpp.
Referenced by getDifferences().
 {
     bool _allEmpty = true;
     if (!_list.isEmpty())
     {
         for (int i = 0; i < _list.size();i++)
             if (!_list.at(i).isEmpty() )
                 return false;
     }
     return _allEmpty;
 }
void FileComparisonDialog::buildRow (QString _keyval, QString _value) private
This function build the individual rows according with the data.
Parameters
_keyval
_value
Definition at line 199 of file filecomparisondialog.cpp.
References _menuSectionList, fillRowWithData(), SolverSectionDAO::findVariableByFileName(), SolverVariableVO::isEmpty(), and SEMICOLON_SEPARATOR.
Referenced by showValuesInTable().
 {
     QStringList _valueList = _value.split(SEMICOLON_SEPARATOR);
     SolverSectionDAO _dao;
     SolverVariableVO _varVO = _dao.findVariableByFileName(_menuSectionList,_keyval);
     if (!_varVO.isEmpty())
         fillRowWithData(_varVO,_valueList);
 }
void FileComparisonDialog::changedComboValueByUser (QString _position) private slot
Slot: Controls if the user change the value in a combo.
Parameters
_position
Definition at line 666 of file filecomparisondialog.cpp.
References saveUserChanges(), and ui.
Referenced by addSignals().
 {
 //    if (!_isLoadingTable)
 //    {
         QStringList coordinates = _position.split("-");
         int row = coordinates[0].toInt();
         int col = coordinates[1].toInt();
         QComboBox* combo = (QComboBox*) ui->comparisonTable->cellWidget(row, col);
         QString _value = combo->currentText();
         saveUserChanges(_value,row,col);
   //  }
 }
QCheckBox* FileComparisonDialog::createCheckBoxElement (QString _name) private
void FileComparisonDialog::fillRowWithData (SolverVariableVO _varVO, QStringList _valueList) private
This function fill the row with the data.
Parameters
_varVO
_valueList
Definition at line 214 of file filecomparisondialog.cpp.
References QtableUtil::addNonEditableText(), fillUserValueInCell(), SolverVariableVO::getVariableName(), INITIAL_COL_VALUES, and ui.
Referenced by buildRow().
 {
     QtableUtil _tableUtil;
     int _lastRow = ui->comparisonTable->rowCount();
     ui->comparisonTable->insertRow(_lastRow);
     ui->comparisonTable->setItem(_lastRow,0,_tableUtil.addNonEditableText(_varVO.getVariableName()));
     for (int i = 0; i < _valueList.size();i++)
     {
         int _column =  INITIAL_COL_VALUES +i;
         QString _fileValue = _valueList.at(i);
         fillUserValueInCell( _varVO,  _fileValue, _lastRow,  _column);
     }
 }
void FileComparisonDialog::fillUserValueInCell (SolverVariableVO _varVO, QString _userValue, int _row, int _col) private
This function fill the User Values in the cell.
Parameters
_varVO
_userValue
_row
_col
Definition at line 238 of file filecomparisondialog.cpp.
References QtableUtil::addCombo(), QtableUtil::addEditText(), QtableUtil::addEditText2(), SolverVariableVO::getComboValuesList(), SolverVariableVO::getSelectableComboValues(), SolverVariableVO::getVariableFileName(), and ui.
Referenced by fillRowWithData().
 {
     QtableUtil _tableUtil;
     if ( (_varVO.getVariableFileName().contains("MARKER")) || (_varVO.getVariableFileName().contains("BC_"))|| (_varVO.getComboValuesList().isEmpty()) )
     {
         ui->comparisonTable->setCellWidget(_row,_col,_tableUtil.addEditText(_userValue));
         ui->comparisonTable->setItem(_row,_col,_tableUtil.addEditText2("") );
     }else{
         QComboBox * _combo = _tableUtil.addCombo(_varVO.getComboValuesList(),_varVO.getSelectableComboValues());
         int _indexVal = _combo->findText(_userValue);
         if (_indexVal != -1)
             _combo->setCurrentIndex(_indexVal);
         else
         {
             _combo->insertItem(0,_userValue);
             _combo->setCurrentIndex(0);
         }
         ui->comparisonTable->setCellWidget(_row,_col,_combo);
         ui->comparisonTable->setItem(_row,_col,_tableUtil.addEditText2("") );
     }
 }
QString FileComparisonDialog::getComparedValuesList (QString _keyValue) private
Get the list of values for a specific keyvalue.
Parameters
_keyValue
Returns
QString
Definition at line 478 of file filecomparisondialog.cpp.
References _loadedValues, and SEMICOLON_SEPARATOR.
Referenced by getDifferences().
 {
     QString _result;
     QStringList _resultList;
     for (int i = 0; i < _loadedValues.size(); i++)
     {
         if (!_loadedValues.at(i).isEmpty())
             _resultList.append(_loadedValues.at(i).value(_keyValue));
         else
             _resultList.append("");
     }
     _result = _resultList.join(SEMICOLON_SEPARATOR);
     return _result;
 }
void FileComparisonDialog::getDifferences () private
Get the differences among the files.
Definition at line 329 of file filecomparisondialog.cpp.
References _differentValues, _loadedValues, areAllEmpty(), getComparedValuesList(), getIdSmallVariableSet(), and isDifferent().
Referenced by on_compareButton_clicked().
 {
     if ( (!_loadedValues.isEmpty()) && (_loadedValues.size() > 1) )
     {
         QList< QHash<QString,QString> > _loadedValueSetAux = _loadedValues;
         QStringList _removedMapPos;
         bool _stop = areAllEmpty(_loadedValueSetAux);
         int _posMapToCompare =  getIdSmallVariableSet(_loadedValueSetAux,_removedMapPos);
         while(!_stop)
         {
             if (_posMapToCompare != -1)
             {
                 QHash<QString,QString> _mapToCompare = _loadedValueSetAux.at(_posMapToCompare);
                 QHashIterator<QString,QString> iter(_mapToCompare);
                 while(iter.hasNext())
                 {
                     iter.next();
                     QString _keyValue = iter.key();
                     if (isDifferent(_keyValue))
                     {
                         QString _comparedValues = getComparedValuesList(_keyValue);
                         _differentValues.insert(_keyValue,_comparedValues);
                     }
                     // Remove the key value
                     for (int i = 0; i < _loadedValueSetAux.size();i++)
                        if (!_loadedValueSetAux.at(i).isEmpty())
{
                            QHash<QString,QString> _map = _loadedValueSetAux.at(i);
                            _map.remove(_keyValue);
                            _loadedValueSetAux[i] = _map;
                        }
                 }
                 // Fill with the other Values
                 if (!areAllEmpty(_loadedValueSetAux))
                 {
                     if (_posMapToCompare != -1)
                     {
                         _removedMapPos.append(QString::number(_posMapToCompare));
                         _posMapToCompare = getIdSmallVariableSet(_loadedValueSetAux,_removedMapPos);
                         _stop = false;
                     }
                     else
                         _stop = true;
                 }
                 else
                     _stop = true;
             }
         }
     }
 }
int FileComparisonDialog::getIdSmallVariableSet (QList< QHash< QString, QString > > _list, QStringList _removedPositions) private
Get the id of the list with less values.
Parameters
QList<QHash<QString
_list
Returns
int
Definition at line 545 of file filecomparisondialog.cpp.
Referenced by getDifferences().
 {
     int _id = -1;
     if (!_list.isEmpty())
     {
         _id = 0;
         int _sizePrevList = _list.at(0).size();
         for (int i = 0; i < _list.size();i++)
         {
             QString _cPos = QString::number(i);
             if (_sizePrevList > _list.at(i).size())
             {
                 if  (!_removedPositions.isEmpty())
                 {
                     if (!_removedPositions.contains(_cPos))
                     {
                         _sizePrevList = _list.at(i).size();
                         _id = i;
                     }
                 }
                 else
                 {
                     _sizePrevList = _list.at(i).size();
                     _id = i;
                 }
             }
         }
     }
     return _id;
 }
void FileComparisonDialog::hideColumnsView () private
void FileComparisonDialog::insertHeaderTitles () private
This function insert the Header titles.
Definition at line 168 of file filecomparisondialog.cpp.
References QtableUtil::addNonEditableText(), and ui.
Referenced by setFilesToCompare().
 {
     QtableUtil _tableUtil;
     ui->comparisonTable->insertRow(0);
     ui->comparisonTable->insertColumn(0);
     ui->comparisonTable->insertColumn(1);
     ui->comparisonTable->setItem(0,0,_tableUtil.addNonEditableText("Variable"));
     ui->comparisonTable->setItem(0,1,_tableUtil.addNonEditableText("Values"));
 }
bool FileComparisonDialog::isDifferent (QString _keyValue) private
Check if for a keyvalue are different values.
Parameters
_keyValue
Returns
bool
Definition at line 500 of file filecomparisondialog.cpp.
References _loadedValues, and StrEqual.
Referenced by getDifferences().
 {
     bool _isDifferent = false;
     if ( (!_loadedValues.isEmpty()) && (_loadedValues.size() > 1) )
     {
        QString _prevVal = _loadedValues.at(0).value(_keyValue);
        for (int i = 1; i < _loadedValues.size(); i++)
        {
          if (_loadedValues.at(i).isEmpty())
              return true;
          if (QString::compare(_prevVal,_loadedValues.at(i).value(_keyValue)) != StrEqual)
                return true;
        }
     }
     return _isDifferent;
 }
void FileComparisonDialog::loadFileValues (QString _fileName) private
This function loads the values of a file.
Parameters
_fileName
Definition at line 92 of file filecomparisondialog.cpp.
References _loadedValues, _virtualLoadedValues, _virtualMRFData, COMMA_SEPARATOR, VirtualMrfVO::getAxisCenter(), VirtualMrfVO::getAxisNormal(), VirtualMrfVO::getInnerCurvePoints(), VirtualMrfVO::getOmega(), VirtualMrfVO::getOuterCurvePoints(), ParserFiles::getParsedValues(), ConfigurationFileParser::getParsedVirtualMRFData(), VirtualMrfVO::getZoneName(), ConfigurationFileParser::parseFileProcess(), and ParserFiles::setFilePath().
Referenced by on_compareButton_clicked().
 {
     ConfigurationFileParser _configParser;
    _configParser.setFilePath(_fileName);
     _configParser.parseFileProcess();
     QHash<QString,QString>  _userConfigVal = _configParser.getParsedValues();
     _loadedValues.append(_userConfigVal);
      // Adding the data of VirtualMRFData
     QHash<QString,QString> _virtualConfigVal;
     _virtualMRFData = _configParser.getParsedVirtualMRFData();
      for (int i = 0; i<_virtualMRFData.size();i++)
         {
             VirtualMrfVO _virtualVO = _virtualMRFData.at(i);
             QString _keyName = "VMRF_AXIS,"+QString::number(i);
             QString _value = _virtualVO.getZoneName() + COMMA_SEPARATOR + _virtualVO.getOmega() + COMMA_SEPARATOR +
                     _virtualVO.getAxisCenter().join(COMMA_SEPARATOR) + COMMA_SEPARATOR + _virtualVO.getAxisNormal().join(COMMA_SEPARATOR);
             _virtualConfigVal.insert(_keyName,_value);
             if (_virtualVO.getInnerCurvePoints().count() > 0)
             {
                 QString _keyName_inner = "VMRF_INNER_CURVE,"+QString::number(i);
                 QString _valueInnerCurve = _virtualVO.getZoneName() + COMMA_SEPARATOR + QString::number(_virtualVO.getInnerCurvePoints().count()) +
                         COMMA_SEPARATOR + _virtualVO.getInnerCurvePoints().join(COMMA_SEPARATOR);
                 _virtualConfigVal.insert(_keyName_inner,_valueInnerCurve);
             }
             if (_virtualVO.getOuterCurvePoints().count() > 0)
             {
                 QString _keyName_outer = "VMRF_OUTTER_CURVE,"+QString::number(i);
                 QString _valueOuterCurve = _virtualVO.getZoneName() + COMMA_SEPARATOR + QString::number(_virtualVO.getOuterCurvePoints().count()) +
                         COMMA_SEPARATOR + _virtualVO.getOuterCurvePoints().join(COMMA_SEPARATOR);
                  _virtualConfigVal.insert(_keyName_outer,_valueOuterCurve);
             }
         }
     _virtualLoadedValues.append(_virtualConfigVal);
 }
void FileComparisonDialog::on_buttonBox_accepted () private slot
Action that controls when the user accept the changes.
Definition at line 732 of file filecomparisondialog.cpp.
References _differentValues, _filesToCompare, _projectDetails, _virtualMRFData, SolverConfigManager::initializeManager(), SolverConfigManager::saveConfigFile(), and SEMICOLON_SEPARATOR.
 {
     SolverConfigManager _solverManager;
     _solverManager.initializeManager();
     for (int i = 0; i < _filesToCompare.size();i++)
     {
          QHash<QString,QString> _mapDiff;
          QHashIterator<QString,QString> iter(_differentValues);
          while(iter.hasNext())
          {
              iter.next();
              QString _keyVal = iter.key();
              QStringList _valueList = iter.value().split(SEMICOLON_SEPARATOR);
              QString _val;
              if (i < _valueList.size())
                  _val = _valueList.at(i);
              _mapDiff.insert(_keyVal,_val);
          }
          _solverManager.saveConfigFile(_filesToCompare.at(i),_mapDiff, _projectDetails,_virtualMRFData);
     }
     close();
 }
void FileComparisonDialog::on_buttonBox_rejected () private slot
Action that controls when the user reject the changes.
Definition at line 760 of file filecomparisondialog.cpp.
 {
     close();
 }
void FileComparisonDialog::on_compareButton_clicked () private slot
This function allows to compare the files.
Definition at line 66 of file filecomparisondialog.cpp.
References _filesToCompare, getDifferences(), loadFileValues(), showValuesInTable(), and ui.
 {
     //_isLoadingTable = true;
     ui->comparisonTable->blockSignals(true); // Block the signals while we add the values
     for (int i = 0; i < _filesToCompare.size();i++)
     {
             QString _fileSelected = _filesToCompare.at(i);
            loadFileValues(_fileSelected);
     }
     getDifferences();
     //getDifferencesAmongVirtualMRFData(); // TO BE DONE (FUTURE...)
     showValuesInTable();
     ui->compareButton->setEnabled(false);
     ui->comparisonTable->blockSignals(false);
     //_isLoadingTable = false;
 }
void FileComparisonDialog::resetTable () private
This function reset the table values.
Definition at line 182 of file filecomparisondialog.cpp.
References ui.
Referenced by setFilesToCompare().
 {
     if (ui->comparisonTable->rowCount() > 0)
         for (int i = (ui->comparisonTable->rowCount()-1); i >= 0; i--)
             ui->comparisonTable->removeRow(i);
     if (ui->comparisonTable->columnCount() > 2)
         for (int i = (ui->comparisonTable->columnCount()-1); i >= 0; i--)
             ui->comparisonTable->removeColumn(i);
 }
void FileComparisonDialog::saveUserChanges (QString _value, int _row, int _col) private
This function saves the changes made by the user.
Parameters
_value
_row
_col
Definition at line 709 of file filecomparisondialog.cpp.
References _differentValues, _menuSectionList, SolverSectionDAO::findValueNameByVariableName(), SEMICOLON_SEPARATOR, and ui.
Referenced by changedComboValueByUser(), and textChangedSlot().
 {
     if (!_differentValues.isEmpty())
     {
         SolverSectionDAO _dao;
         QString _varName = ui->comparisonTable->item(_row,_col)->text();
         QString _keyValue = _dao.findValueNameByVariableName(_menuSectionList,_varName);
         if (_differentValues.contains(_keyValue))
         {
             QString _oldValues = _differentValues.value(_keyValue);
             QStringList _oldValList = _oldValues.split(SEMICOLON_SEPARATOR);
             if (_col < _oldValList.size())
                 _oldValList[_col] = _value;
             _differentValues.insert(_keyValue,_oldValList.join(SEMICOLON_SEPARATOR));
         }
     }
 }
void FileComparisonDialog::setFilesToCompare (QStringList _list)
Set the list of files to be compared.
Parameters
_list
Definition at line 316 of file filecomparisondialog.cpp.
References _filesToCompare, insertHeaderTitles(), resetTable(), ui, and updateTableHeader().
Referenced by SolverHelper::launchFileComparisonDialog().
 {
     _filesToCompare = _list;
     resetTable();
     insertHeaderTitles();
     updateTableHeader();
     ui->comparisonTable->resizeColumnsToContents();
 }
void FileComparisonDialog::setProjectDetails (ProjectDetails _details)
Set the project details.
Parameters
_details
Definition at line 301 of file filecomparisondialog.cpp.
References _projectDetails.
Referenced by SolverHelper::launchFileComparisonDialog().
 {
     _projectDetails = _details;
 }
void FileComparisonDialog::setSectionMenuList (QList< SolverSectionVO > _list)
Set the section Menu List.
Parameters
_list
Definition at line 291 of file filecomparisondialog.cpp.
References _menuSectionList.
Referenced by SolverHelper::launchFileComparisonDialog().
 {
     _menuSectionList = _list;
 }
void FileComparisonDialog::setVirtualMRFData (QList< VirtualMrfVO > _list)
Definition at line 306 of file filecomparisondialog.cpp.
References _virtualMRFData.
Referenced by SolverHelper::launchFileComparisonDialog().
 {
     _virtualMRFData = _list;
 }
void FileComparisonDialog::showValuesInTable () private
This function shows those values that are different in the table.
Definition at line 264 of file filecomparisondialog.cpp.
References _differentValues, addSignals(), buildRow(), and ui.
Referenced by on_compareButton_clicked().
 {
     if (!_differentValues.isEmpty())
     {
         QHashIterator<QString,QString> iter(_differentValues);
         while(iter.hasNext())
         {
             iter.next();
             QString _keyValue = iter.key();
             QString _value = iter.value();
             buildRow(_keyValue,_value);
         }
         addSignals();
         ui->comparisonTable->resizeColumnsToContents();
     }
 }
void FileComparisonDialog::textChangedSlot (QString _position) private slot
Slot: Controls if the user change the value of a line Edit.
Parameters
_position
Definition at line 688 of file filecomparisondialog.cpp.
References saveUserChanges(), and ui.
Referenced by addSignals().
 {
 //   if (!_isLoadingTable)
 //    {
        QStringList coordinates = _position.split("-");
        int row = coordinates[0].toInt();
        int col = coordinates[1].toInt();
        QLineEdit * _lineEdit = (QLineEdit *) ui->comparisonTable->cellWidget(row,col);
        QString _value = _lineEdit->text();
        saveUserChanges(_value,row,col);
 //    }
 }
void FileComparisonDialog::updateTableHeader () private
This function updates the Header table.
Definition at line 135 of file filecomparisondialog.cpp.
References _filesToCompare, QtableUtil::addNonEditableText(), INITIAL_COL_VALUES, INITIAL_ROW, and ui.
Referenced by setFilesToCompare().
 {
     int _lastRow = ui->comparisonTable->rowCount();
     ui->comparisonTable->insertRow(_lastRow);
     int _noFileCols = _filesToCompare.size();
     if (_noFileCols >= 2)
     {
         int _initColPos = ui->comparisonTable->columnCount();
         int _noColToInsert =  _noFileCols -_initColPos +1;
         QtableUtil _tableUtil;
         for (int i = 0; i < _noColToInsert; i++)
             ui->comparisonTable->insertColumn(_initColPos+i);
         for (int j = 0; j < _filesToCompare.size();j++)
         {
             QString _fileName = QFileInfo(_filesToCompare.at(j)).fileName();
             ui->comparisonTable->setItem(_lastRow,(_initColPos + j -1),_tableUtil.addNonEditableText(_fileName));
         }
         // Setting the style of the header Rows and columns
         ui->comparisonTable->setSpan(INITIAL_ROW,INITIAL_COL_VALUES,1,_noFileCols);
         ui->comparisonTable->item(INITIAL_ROW,INITIAL_COL_VALUES)->setTextAlignment(Qt::AlignCenter);
         ui->comparisonTable->setSpan(INITIAL_ROW,INITIAL_COL_VALUES-1,2,1);
         ui->comparisonTable->item(INITIAL_ROW,INITIAL_COL_VALUES-1)->setTextAlignment(Qt::AlignCenter);
     }
 }
Member Data Documentation
QHash<QString,QString> FileComparisonDialog::_differentValues private
Definition at line 51 of file filecomparisondialog.h.
Referenced by getDifferences(), on_buttonBox_accepted(), saveUserChanges(), and showValuesInTable().
QStringList FileComparisonDialog::_filesToCompare private
Definition at line 46 of file filecomparisondialog.h.
Referenced by addSignals(), on_buttonBox_accepted(), on_compareButton_clicked(), setFilesToCompare(), and updateTableHeader().
QList< QHash<QString,QString> > FileComparisonDialog::_loadedValues private
Definition at line 49 of file filecomparisondialog.h.
Referenced by getComparedValuesList(), getDifferences(), isDifferent(), and loadFileValues().
QList<SolverSectionVO> FileComparisonDialog::_menuSectionList private
Definition at line 52 of file filecomparisondialog.h.
Referenced by buildRow(), saveUserChanges(), and setSectionMenuList().
ProjectDetails FileComparisonDialog::_projectDetails private
Definition at line 55 of file filecomparisondialog.h.
Referenced by on_buttonBox_accepted(), and setProjectDetails().
QSignalMapper* FileComparisonDialog::_signalMapper private
Definition at line 47 of file filecomparisondialog.h.
Referenced by addSignals(), addSignalToCombo(), and FileComparisonDialog().
QSignalMapper* FileComparisonDialog::_signalMapperTxtEdit private
Definition at line 54 of file filecomparisondialog.h.
Referenced by addSignals(), addSignalToLinEdit(), and FileComparisonDialog().
QList<bool> FileComparisonDialog::_statusSelection private
Definition at line 48 of file filecomparisondialog.h.
QList< QHash<QString,QString> > FileComparisonDialog::_virtualLoadedValues private
Definition at line 50 of file filecomparisondialog.h.
Referenced by loadFileValues().
QList<VirtualMrfVO> FileComparisonDialog::_virtualMRFData private
Definition at line 56 of file filecomparisondialog.h.
Referenced by loadFileValues(), on_buttonBox_accepted(), and setVirtualMRFData().
Ui::FileComparisonDialog* FileComparisonDialog::ui private
Definition at line 45 of file filecomparisondialog.h.
Referenced by addSignals(), changedComboValueByUser(), FileComparisonDialog(), fillRowWithData(), fillUserValueInCell(), insertHeaderTitles(), on_compareButton_clicked(), resetTable(), saveUserChanges(), setFilesToCompare(), showValuesInTable(), textChangedSlot(), updateTableHeader(), and ~FileComparisonDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/filecomparisondialog.h
Forms/SolverMenuDialog/filecomparisondialog.cpp