BBIPED Platform: SearchedPair Class Reference
SearchedPair Class Reference
#include <searchedpair.h>
Public Member Functions
SearchedPair ()
bool contains (int _nidParent, int _nidChild)
Returns true if the id of the parent and the child are the same as stored in the object.
QList< int > getChildrenList ()
Get the children list.
int getIdChild ()
Gets the Id of the child (read from the xml file)
int getIdParent ()
Gets the Id of the parent (read from the xml file)
void setChildrenList (QList< int > _list)
Set the children list.
void setIdChild (int _id)
sets the Id of the child (read from the xml file)
void setIdParent (int _id)
Set the Id of the parent.
Private Attributes
int _idChild
int _idParent
QList< int > _listChildren
Detailed Description
Definition at line 4 of file searchedpair.h.
Constructor & Destructor Documentation
SearchedPair::SearchedPair ()
Definition at line 23 of file searchedpair.cpp.
 {
 }
Member Function Documentation
bool SearchedPair::contains (int _nidParent, int _nidChild)
Returns true if the id of the parent and the child are the same as stored in the object.
Parameters
_nidParent
_nidChild
Returns
bool
Definition at line 94 of file searchedpair.cpp.
References _idChild, and _idParent.
Referenced by SearchPairHelper::findParentChildinSearchList().
 {
     if ((_idParent ==_nidParent) && (_idChild == _nidChild))
             return true;
     else
         return false;
 }
QList< int > SearchedPair::getChildrenList ()
Get the children list.
Returns
QList<int>
Definition at line 72 of file searchedpair.cpp.
References _listChildren.
Referenced by SearchPairHelper::findParentChildinSearchList().
 {
     return _listChildren;
 }
int SearchedPair::getIdChild ()
Gets the Id of the child (read from the xml file)
Returns
int
Definition at line 51 of file searchedpair.cpp.
References _idChild.
Referenced by SearchPairHelper::refreshHighlight(), and SearchPairHelper::searchItems().
 {
     return _idChild;
 }
int SearchedPair::getIdParent ()
Gets the Id of the parent (read from the xml file)
Returns
int
Definition at line 31 of file searchedpair.cpp.
References _idParent.
Referenced by SearchPairHelper::refreshHighlight(), and SearchPairHelper::searchItems().
 {
     return _idParent;
 }
void SearchedPair::setChildrenList (QList< int > _list)
Set the children list.
Parameters
_list
Definition at line 82 of file searchedpair.cpp.
References _listChildren.
Referenced by SearchPairHelper::searchTreeBySearchTerm().
 {
     _listChildren = _list;
 }
void SearchedPair::setIdChild (int _id)
sets the Id of the child (read from the xml file)
Parameters
_id
Definition at line 61 of file searchedpair.cpp.
References _idChild.
Referenced by SearchPairHelper::searchTreeBySearchTerm().
 {
     _idChild = _id;
 }
void SearchedPair::setIdParent (int _id)
Set the Id of the parent.
Parameters
_id
Definition at line 41 of file searchedpair.cpp.
References _idParent.
Referenced by SearchPairHelper::searchTreeBySearchTerm().
 {
     _idParent = _id;
 }
Member Data Documentation
int SearchedPair::_idChild private
Definition at line 23 of file searchedpair.h.
Referenced by contains(), getIdChild(), and setIdChild().
int SearchedPair::_idParent private
Definition at line 22 of file searchedpair.h.
Referenced by contains(), getIdParent(), and setIdParent().
QList<int> SearchedPair::_listChildren private
Definition at line 24 of file searchedpair.h.
Referenced by getChildrenList(), and setChildrenList().
The documentation for this class was generated from the following files:
Searcher/searchedpair.h
Searcher/searchedpair.cpp