BBIPED Platform: VirtualMrfVO Class Reference
VirtualMrfVO Class Reference
#include <virtualmrfvo.h>
Public Member Functions
VirtualMrfVO ()
Constructor of the class Virtual MRF.
QStringList getAxisCenter ()
Get the axis center.
QStringList getAxisNormal ()
get the Axis Normal
QStringList getInnerCurvePoints ()
get Inner curve points (list)
QString getOmega ()
Get the omega.
QStringList getOuterCurvePoints ()
get Outer curve points (list)
QString getZoneName ()
Get tbe name of the zone.
bool isCoordinatesIn3D ()
Returns if the coordinates are set in 3D (true), otherwise is false.
bool isEmpty ()
Check if all the elements are empty.
void setAxisCenter (QStringList _list)
Set Axis Center.
void setAxisNormal (QStringList _list)
Set Axis Normal.
void setCoordinatesIn3D (bool _val)
True if the coordinates are in 3D, false otherwise.
void setInnerCurvePoints (QStringList _list)
Set the list of inner curve points.
void setOmega (QString _val)
Set omega.
void setOuterCurvePoints (QStringList _list)
Set the list of outer curve points.
void setZoneName (QString _val)
Set Zone name.
Private Attributes
QStringList _axisCenter
QStringList _axisNormal
bool _coordinatesIn3D
QStringList _innerCurvePoints
QString _omega
QStringList _outerCurvePoints
QString _zoneName
Detailed Description
Definition at line 6 of file virtualmrfvo.h.
Constructor & Destructor Documentation
VirtualMrfVO::VirtualMrfVO ()
Constructor of the class Virtual MRF.
Definition at line 24 of file virtualmrfvo.cpp.
References _axisCenter, _axisNormal, _coordinatesIn3D, _innerCurvePoints, _omega, _outerCurvePoints, and _zoneName.
 {
     _coordinatesIn3D = false; // By default, coordinates of inner and outer curves will be in 2D
     _zoneName = "";
     _omega = "";
     _axisCenter.clear();
     _axisNormal.clear();
     _innerCurvePoints.clear();
     _outerCurvePoints.clear();
 }
Member Function Documentation
QStringList VirtualMrfVO::getAxisCenter ()
Get the axis center.
Returns
QStringList
Definition at line 61 of file virtualmrfvo.cpp.
References _axisCenter.
Referenced by VirtualRotatingDialog::addRow(), MultizoneSummaryDialog::fillDataTable(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
      return _axisCenter;
 }
QStringList VirtualMrfVO::getAxisNormal ()
get the Axis Normal
Returns
QStringList
Definition at line 71 of file virtualmrfvo.cpp.
References _axisNormal.
Referenced by VirtualRotatingDialog::addRow(), MultizoneSummaryDialog::fillDataTable(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
      return _axisNormal;
 }
QStringList VirtualMrfVO::getInnerCurvePoints ()
get Inner curve points (list)
Returns
QStringList
Definition at line 81 of file virtualmrfvo.cpp.
References _innerCurvePoints.
Referenced by VirtualRotatingDialog::launchCurveDialog(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
      return _innerCurvePoints;
 }
QString VirtualMrfVO::getOmega ()
Get the omega.
Returns
QString
Definition at line 51 of file virtualmrfvo.cpp.
References _omega.
Referenced by VirtualRotatingDialog::addRow(), MultizoneSummaryDialog::fillDataTable(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
      return _omega;
 }
QStringList VirtualMrfVO::getOuterCurvePoints ()
get Outer curve points (list)
Returns
QStringList
Definition at line 91 of file virtualmrfvo.cpp.
References _outerCurvePoints.
Referenced by VirtualRotatingDialog::launchCurveDialog(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
      return _outerCurvePoints;
 }
QString VirtualMrfVO::getZoneName ()
Get tbe name of the zone.
Returns
QString
Definition at line 41 of file virtualmrfvo.cpp.
References _zoneName.
Referenced by VirtualRotatingDialog::addRow(), MultizoneSummaryDialog::fillDataTable(), ConfigurationFileParser::findVirtualMRFPositionByZoneName(), FileComparisonDialog::loadFileValues(), and SolverConfigWriter::printVirtualMRFValues().
 {
     return _zoneName;
 }
bool VirtualMrfVO::isCoordinatesIn3D ()
Returns if the coordinates are set in 3D (true), otherwise is false.
Returns
bool
Definition at line 193 of file virtualmrfvo.cpp.
References _coordinatesIn3D.
 {
     return _coordinatesIn3D ;
 }
bool VirtualMrfVO::isEmpty ()
Check if all the elements are empty.
Returns
bool
Definition at line 164 of file virtualmrfvo.cpp.
References _axisCenter, _axisNormal, _innerCurvePoints, _omega, _outerCurvePoints, and _zoneName.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     bool _isEmpty = true;
     if (!_axisCenter.isEmpty()) _isEmpty = false;
     if (!_axisNormal.isEmpty()) _isEmpty = false;
     if (!_innerCurvePoints.isEmpty()) _isEmpty = false;
     if (!_outerCurvePoints.isEmpty()) _isEmpty = false;
     if (!_zoneName.isEmpty()) _isEmpty = false;
     if (!_omega.isEmpty()) _isEmpty = false;
     return _isEmpty;
 }
void VirtualMrfVO::setAxisCenter (QStringList _list)
Set Axis Center.
Parameters
_list
Definition at line 122 of file virtualmrfvo.cpp.
References _axisCenter.
Referenced by VirtualRotatingDialog::createVirtualMRFData(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _axisCenter = _list;
 }
void VirtualMrfVO::setAxisNormal (QStringList _list)
Set Axis Normal.
Parameters
_list
Definition at line 132 of file virtualmrfvo.cpp.
References _axisNormal.
Referenced by VirtualRotatingDialog::createVirtualMRFData(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _axisNormal = _list;
 }
void VirtualMrfVO::setCoordinatesIn3D (bool _val)
True if the coordinates are in 3D, false otherwise.
Parameters
_val
Definition at line 183 of file virtualmrfvo.cpp.
References _coordinatesIn3D.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     _coordinatesIn3D = _val;
 }
void VirtualMrfVO::setInnerCurvePoints (QStringList _list)
Set the list of inner curve points.
Parameters
_list
Definition at line 142 of file virtualmrfvo.cpp.
References _innerCurvePoints.
Referenced by VirtualRotatingDialog::launchCurveDialog(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _innerCurvePoints = _list;
 }
void VirtualMrfVO::setOmega (QString _val)
Set omega.
Parameters
_val
Definition at line 112 of file virtualmrfvo.cpp.
References _omega.
Referenced by VirtualRotatingDialog::createVirtualMRFData(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _omega = _val;
 }
void VirtualMrfVO::setOuterCurvePoints (QStringList _list)
Set the list of outer curve points.
Parameters
_list
Definition at line 152 of file virtualmrfvo.cpp.
References _outerCurvePoints.
Referenced by VirtualRotatingDialog::launchCurveDialog(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _outerCurvePoints = _list;
 }
void VirtualMrfVO::setZoneName (QString _val)
Set Zone name.
Parameters
_val
Definition at line 102 of file virtualmrfvo.cpp.
References _zoneName.
Referenced by VirtualRotatingDialog::createVirtualMRFData(), and ConfigurationFileParser::saveVirtualMRFValue().
 {
     _zoneName = _val;
 }
Member Data Documentation
QStringList VirtualMrfVO::_axisCenter private
Definition at line 35 of file virtualmrfvo.h.
Referenced by getAxisCenter(), isEmpty(), setAxisCenter(), and VirtualMrfVO().
QStringList VirtualMrfVO::_axisNormal private
Definition at line 36 of file virtualmrfvo.h.
Referenced by getAxisNormal(), isEmpty(), setAxisNormal(), and VirtualMrfVO().
bool VirtualMrfVO::_coordinatesIn3D private
Definition at line 40 of file virtualmrfvo.h.
Referenced by isCoordinatesIn3D(), setCoordinatesIn3D(), and VirtualMrfVO().
QStringList VirtualMrfVO::_innerCurvePoints private
Definition at line 37 of file virtualmrfvo.h.
Referenced by getInnerCurvePoints(), isEmpty(), setInnerCurvePoints(), and VirtualMrfVO().
QString VirtualMrfVO::_omega private
Definition at line 34 of file virtualmrfvo.h.
Referenced by getOmega(), isEmpty(), setOmega(), and VirtualMrfVO().
QStringList VirtualMrfVO::_outerCurvePoints private
Definition at line 38 of file virtualmrfvo.h.
Referenced by getOuterCurvePoints(), isEmpty(), setOuterCurvePoints(), and VirtualMrfVO().
QString VirtualMrfVO::_zoneName private
Definition at line 33 of file virtualmrfvo.h.
Referenced by getZoneName(), isEmpty(), setZoneName(), and VirtualMrfVO().
The documentation for this class was generated from the following files:
Data/Solver/VirtualMRF/virtualmrfvo.h
Data/Solver/VirtualMRF/virtualmrfvo.cpp