BBIPED Platform: ProjectDetails Class Reference
ProjectDetails Class Reference
#include <projectdetails.h>
Public Member Functions
ProjectDetails ()
void clear ()
This function clear all the values of the object.
QString getAuthor ()
This function gets the author name.
QString getOtherDetails ()
This function get the other details field.
QString getProjectTile ()
This function gets the project title.
QString getStartingDate ()
This function gets the starting data added by the user.
void setAuthor (QString _newAuthor)
This function sets the author name.
void setOtherDetails (QString _newDetails)
This function set the other details field.
void setProjectTile (QString _title)
This function sets the project title.
void setStartingDate (QString _newDate)
This function sets the starting data added by the user.
void updateProjectDetails (ProjectDetails _newProjectDetails)
This function is to update the data from another object.
Private Attributes
QString _author
QString _otherDetails
QString _projectTile
QString _startingDate
Detailed Description
Definition at line 4 of file projectdetails.h.
Constructor & Destructor Documentation
ProjectDetails::ProjectDetails ()
Definition at line 24 of file projectdetails.cpp.
References _author, _otherDetails, _projectTile, and _startingDate.
 {
     // Project Details
     _projectTile = "";
     _author = "";
     _startingDate  = "";
     _otherDetails  = "";
 }
Member Function Documentation
void ProjectDetails::clear ()
This function clear all the values of the object.
Definition at line 121 of file projectdetails.cpp.
References _author, _otherDetails, _projectTile, and _startingDate.
Referenced by MainWindow::clearAllData().
 {
     _projectTile = "";
     _author = "";
     _startingDate  = "";
     _otherDetails  = "";
 }
QString ProjectDetails::getAuthor ()
This function gets the author name.
Returns
QString
Definition at line 59 of file projectdetails.cpp.
References _author.
Referenced by XmlUtil::createProjectDetailsXmlElements(), updateProjectDetails(), ProjectSettingsDialog::updateProjectDetailsInProjectDetailsTabView(), and SolverConfigWriter::writeHeaderFile().
 {
     return _author;
 }
QString ProjectDetails::getOtherDetails ()
This function get the other details field.
Returns
QString
Definition at line 99 of file projectdetails.cpp.
References _otherDetails.
Referenced by XmlUtil::createProjectDetailsXmlElements(), updateProjectDetails(), ProjectSettingsDialog::updateProjectDetailsInProjectDetailsTabView(), and SolverConfigWriter::writeHeaderFile().
 {
     return _otherDetails;
 }
QString ProjectDetails::getProjectTile ()
This function gets the project title.
Returns
QString
Definition at line 39 of file projectdetails.cpp.
References _projectTile.
Referenced by XmlUtil::createProjectDetailsXmlElements(), updateProjectDetails(), ProjectSettingsDialog::updateProjectDetailsInProjectDetailsTabView(), and SolverConfigWriter::writeHeaderFile().
 {
     return _projectTile;
 }
QString ProjectDetails::getStartingDate ()
This function gets the starting data added by the user.
Returns
QString
Definition at line 79 of file projectdetails.cpp.
References _startingDate.
Referenced by XmlUtil::createProjectDetailsXmlElements(), updateProjectDetails(), ProjectSettingsDialog::updateProjectDetailsInProjectDetailsTabView(), and SolverConfigWriter::writeHeaderFile().
 {
     return _startingDate;
 }
void ProjectDetails::setAuthor (QString _newAuthor)
This function sets the author name.
Parameters
_newAuthor
Definition at line 69 of file projectdetails.cpp.
References _author.
Referenced by XmlUtil::getProjectDetailsInformation(), ProjectSettingsDialog::on_buttonBox_accepted(), and updateProjectDetails().
 {
     _author = _newAuthor;
 }
void ProjectDetails::setOtherDetails (QString _newDetails)
This function set the other details field.
Parameters
_newDetails
Definition at line 109 of file projectdetails.cpp.
References _otherDetails.
Referenced by XmlUtil::getProjectDetailsInformation(), ProjectSettingsDialog::on_buttonBox_accepted(), and updateProjectDetails().
 {
     _otherDetails = _newDetails;
 }
void ProjectDetails::setProjectTile (QString _title)
This function sets the project title.
Parameters
_title
Definition at line 49 of file projectdetails.cpp.
References _projectTile.
Referenced by XmlUtil::getProjectDetailsInformation(), ProjectSettingsDialog::on_buttonBox_accepted(), and updateProjectDetails().
 {
     _projectTile = _title;
 }
void ProjectDetails::setStartingDate (QString _newDate)
This function sets the starting data added by the user.
Parameters
_newDate
Definition at line 89 of file projectdetails.cpp.
References _startingDate.
Referenced by XmlUtil::getProjectDetailsInformation(), ProjectSettingsDialog::on_buttonBox_accepted(), and updateProjectDetails().
 {
     _startingDate = _newDate;
 }
void ProjectDetails::updateProjectDetails (ProjectDetails _newProjectDetails)
This function is to update the data from another object.
Parameters
_newProjectDetails
Definition at line 135 of file projectdetails.cpp.
References getAuthor(), getOtherDetails(), getProjectTile(), getStartingDate(), setAuthor(), setOtherDetails(), setProjectTile(), and setStartingDate().
Referenced by EditHelper::launchSettingsDialog().
 {
     setProjectTile(_newProjectDetails.getProjectTile());
     setAuthor(_newProjectDetails.getAuthor());
     setStartingDate(_newProjectDetails.getStartingDate());
     setOtherDetails(_newProjectDetails.getOtherDetails());
 }
Member Data Documentation
QString ProjectDetails::_author private
Definition at line 25 of file projectdetails.h.
Referenced by clear(), getAuthor(), ProjectDetails(), and setAuthor().
QString ProjectDetails::_otherDetails private
Definition at line 27 of file projectdetails.h.
Referenced by clear(), getOtherDetails(), ProjectDetails(), and setOtherDetails().
QString ProjectDetails::_projectTile private
Definition at line 24 of file projectdetails.h.
Referenced by clear(), getProjectTile(), ProjectDetails(), and setProjectTile().
QString ProjectDetails::_startingDate private
Definition at line 26 of file projectdetails.h.
Referenced by clear(), getStartingDate(), ProjectDetails(), and setStartingDate().
The documentation for this class was generated from the following files:
Data/ProjectData/VO/projectdetails.h
Data/ProjectData/VO/projectdetails.cpp