BBIPED Platform: MultizoneProjectData Class Reference
MultizoneProjectData Class Reference
#include <multizoneprojectdata.h>
Public Member Functions
MultizoneProjectData ()
Constructor.
void addConfigFile (QString _file)
Add a config file to the lists of the multizone. The file is the full path file.
void addMeshFile (QString _file)
QStringList getListConfigFileNames ()
Get the list of the configuration file names (without path)
QStringList getListConfigFiles ()
Get the list of configuration files.
QStringList getListMeshFileNames ()
Get the list of the mesh file names (without path)
QStringList getListMeshFiles ()
Get the list of mesh files.
QString getProjectName ()
Get the project name.
QString getProjectPath ()
Get the project Path.
bool isEmpty ()
Returns true if there is no value in the project path and name.
void removeConfigFile (QString _file)
void removeMeshFile (QString _file)
void setListConfigFiles (QStringList _list)
Set the list of configuration files.
void setListMeshFiles (QStringList _list)
Set the list of mesh files.
void setProjectName (QString _name)
Set the project name.
void setProjectPath (QString _path)
Set the project Path.
void updateMultizoneProjectData (MultizoneProjectData _newMultiData)
This function is to update the data from another object.
void updatePair (QString _configPath, QString _meshPath)
Private Member Functions
void buildListofFileNames (QStringList _list, int _option)
This function builds the list of file names (removing paths)
Private Attributes
QStringList _listConfigFileNames
QStringList _listConfigFiles
QStringList _listMeshFileNames
QStringList _listMeshFiles
QString _projectName
QString _projectPath
Detailed Description
Definition at line 7 of file multizoneprojectdata.h.
Constructor & Destructor Documentation
MultizoneProjectData::MultizoneProjectData ()
Constructor.
Definition at line 30 of file multizoneprojectdata.cpp.
References _projectName, and _projectPath.
 {
     _projectPath = "";
     _projectName = "";
 }
Member Function Documentation
void MultizoneProjectData::addConfigFile (QString _file)
Add a config file to the lists of the multizone. The file is the full path file.
Parameters
_file
Definition at line 207 of file multizoneprojectdata.cpp.
References _listConfigFiles, and setListConfigFiles().
Referenced by MainWindow::updateMultizoneUserData(), and updatePair().
 {
     _listConfigFiles.append(_file);
     setListConfigFiles(_listConfigFiles);
 }
void MultizoneProjectData::addMeshFile (QString _file)
Definition at line 213 of file multizoneprojectdata.cpp.
References _listMeshFiles, and setListMeshFiles().
Referenced by MainWindow::updateMultizoneUserData(), and updatePair().
 {
     _listMeshFiles.append(_file);
     setListMeshFiles(_listMeshFiles);
 }
void MultizoneProjectData::buildListofFileNames (QStringList _list, int _option) private
This function builds the list of file names (removing paths)
Parameters
_list
_option
Definition at line 164 of file multizoneprojectdata.cpp.
References _listConfigFileNames, _listMeshFileNames, OPTION_CONFIG_FILE, and OPTION_MESH_FILE.
Referenced by setListConfigFiles(), and setListMeshFiles().
 {
     if (!_list.isEmpty())
     {
         for (int i = 0; i< _list.count();i++)
         {
              QString _fullPath = _list.at(i);
              QFileInfo _fileInfo(_fullPath);
              QString _filename = _fileInfo.fileName();
              switch(_option)
              {
              case OPTION_CONFIG_FILE:
                  _listConfigFileNames.append(_filename);
                  break;
              case OPTION_MESH_FILE:
                  _listMeshFileNames.append(_filename);
                  break;
              }
         }
     }
 }
QStringList MultizoneProjectData::getListConfigFileNames ()
Get the list of the configuration file names (without path)
Returns
QStringList
Definition at line 141 of file multizoneprojectdata.cpp.
References _listConfigFileNames.
Referenced by MainWindow::buildSolverCommand(), MultizoneManager::checkProjectBasePathConsistency(), MainWindow::fillMultizoneTable(), MultizoneManager::refreshSimulationFilesView(), ProjectSettingsDialog::updateFileTableInSettingsView(), UtilFiles::updateMultizoneToolPaths(), MultizoneManager::updateOpenEditConfigFile(), and ProjectSettingsDialog::updateProjectData().
 {
     return _listConfigFileNames;
 }
QStringList MultizoneProjectData::getListConfigFiles ()
Get the list of configuration files.
Returns
QStringList
Definition at line 96 of file multizoneprojectdata.cpp.
References _listConfigFiles.
Referenced by MultizoneManager::buildProjectDataForMultizoneProject(), XmlUtil::createXmlMultizoneProjectFile(), MultizoneManager::getConfigurationFilePosition(), MultizoneManager::getPositionToAddFileMultizone(), MainWindow::launchActionProjectSettingsDialog(), SolverHelper::launchFileComparisonDialog(), MainWindow::on_multizoneSummaryAllConfigButton_clicked(), updateMultizoneProjectData(), MultizoneManager::updateMultiZoneValues(), and ProjectSettingsDialog::updateProjectData().
 {
     return _listConfigFiles;
 }
QStringList MultizoneProjectData::getListMeshFileNames ()
Get the list of the mesh file names (without path)
Returns
QStringList
Definition at line 151 of file multizoneprojectdata.cpp.
References _listMeshFileNames.
Referenced by MainWindow::buildSolverCommand(), MultizoneManager::checkProjectBasePathConsistency(), MainWindow::fillMultizoneTable(), MultizoneManager::refreshSimulationFilesView(), ProjectSettingsDialog::updateFileTableInSettingsView(), UtilFiles::updateMultizoneToolPaths(), and ProjectSettingsDialog::updateProjectData().
 {
     return _listMeshFileNames;
 }
QStringList MultizoneProjectData::getListMeshFiles ()
Get the list of mesh files.
Returns
QStringList
Definition at line 119 of file multizoneprojectdata.cpp.
References _listMeshFiles.
Referenced by MultizoneManager::buildProjectDataForMultizoneProject(), XmlUtil::createXmlMultizoneProjectFile(), MultizoneManager::getPositionToAddFileMultizone(), updateMultizoneProjectData(), MultizoneManager::updateMultiZoneValues(), and ProjectSettingsDialog::updateProjectData().
 {
     return _listMeshFiles;
 }
QString MultizoneProjectData::getProjectName ()
Get the project name.
Returns
QString
Definition at line 74 of file multizoneprojectdata.cpp.
References _projectName.
Referenced by MultizoneManager::createInitialProjectDataForMultizoneProject(), XmlUtil::createXmlMultizoneProjectFile(), updateMultizoneProjectData(), UtilFiles::updateMultizoneProjectDataToFile(), UtilFiles::updateMultizoneToolPaths(), and ProjectSettingsDialog::updateProjectInformationInSettingsView().
 {
     return _projectName;
 }
QString MultizoneProjectData::getProjectPath ()
Get the project Path.
Returns
QString
Definition at line 54 of file multizoneprojectdata.cpp.
References _projectPath.
Referenced by MultizoneManager::checkProjectBasePathConsistency(), UtilFiles::copyAllToolData(), MultizoneManager::createInitialProjectDataForMultizoneProject(), XmlUtil::createXmlMultizoneProjectFile(), MainWindow::enableMultizoneElements(), MultizoneProjectDialog::launchCreateNewFile(), MultizoneProjectDialog::launchImportNewFile(), MultizoneManager::launchMultizoneDialog(), MainWindow::on_multizoneDeleteButton_clicked(), MainWindow::on_multizoneNewButton_clicked(), MainWindow::on_multizoneOpenEditButton_clicked(), MainWindow::on_multizoneRunSimulationButton_clicked(), MainWindow::on_multizoneSummaryAllConfigButton_clicked(), MultizoneManager::openMultizoneProject(), updateMultizoneProjectData(), UtilFiles::updateMultizoneProjectDataToFile(), UtilFiles::updateMultizoneToolPaths(), and MainWindow::updateMultizoneUserData().
 {
     return _projectPath;
 }
bool MultizoneProjectData::isEmpty ()
Returns true if there is no value in the project path and name.
Returns
bool
Definition at line 128 of file multizoneprojectdata.cpp.
References _projectName, _projectPath, and StrEqual.
Referenced by MultizoneProjectDialog::accept(), MultizoneManager::buildProjectDataForMultizoneProject(), MainWindow::enableSolverRunAction(), MultizoneManager::refreshSimulationFilesView(), ProjectSettingsDialog::updateFileTableInSettingsView(), ProjectSettingsDialog::updateProjectData(), and ProjectSettingsDialog::updateProjectInformationInSettingsView().
 {
     if (QString::compare(_projectPath,"") != StrEqual)
         return false;
     if (QString::compare(_projectName,"") != StrEqual)
         return false;
     return true;
 }
void MultizoneProjectData::removeConfigFile (QString _file)
Definition at line 219 of file multizoneprojectdata.cpp.
References _listConfigFileNames, _listConfigFiles, _listMeshFileNames, and _listMeshFiles.
Referenced by MainWindow::on_multizoneDeleteButton_clicked().
 {
     int _pos = _listConfigFiles.indexOf(_file);
     if (_pos != -1)
     {
         _listConfigFiles.removeAt(_pos);
         _listConfigFileNames.removeAt(_pos);
         _listMeshFiles.removeAt(_pos);
         _listMeshFileNames.removeAt(_pos);
     }
 }
void MultizoneProjectData::removeMeshFile (QString _file)
Definition at line 231 of file multizoneprojectdata.cpp.
References _listMeshFileNames, and _listMeshFiles.
Referenced by MainWindow::on_multizoneDeleteButton_clicked().
 {
     int _pos = _listMeshFiles.indexOf(_file);
     if (_pos != -1)
     {
         _listMeshFiles.insert(_pos,"NONE");
         _listMeshFileNames.insert(_pos,"NONE");
     }
 }
void MultizoneProjectData::setListConfigFiles (QStringList _list)
Set the list of configuration files.
Parameters
_list
Definition at line 84 of file multizoneprojectdata.cpp.
References _listConfigFileNames, _listConfigFiles, buildListofFileNames(), and OPTION_CONFIG_FILE.
Referenced by addConfigFile(), MultizoneProjectDialog::buildFilesInProject(), MultizoneManager::checkProjectBasePathConsistency(), XmlUtil::readXmlMultizoneProjectFile(), updateMultizoneProjectData(), UtilFiles::updateMultizoneToolPaths(), MultizoneManager::updateMultiZoneValues(), and ProjectSettingsDialog::updateProjectData().
 {
     _listConfigFiles = _list;
     _listConfigFileNames.clear();
     buildListofFileNames(_listConfigFiles,OPTION_CONFIG_FILE);
 }
void MultizoneProjectData::setListMeshFiles (QStringList _list)
Set the list of mesh files.
Parameters
_list
Definition at line 106 of file multizoneprojectdata.cpp.
References _listMeshFileNames, _listMeshFiles, buildListofFileNames(), and OPTION_MESH_FILE.
Referenced by addMeshFile(), MultizoneProjectDialog::buildFilesInProject(), MultizoneManager::checkProjectBasePathConsistency(), XmlUtil::readXmlMultizoneProjectFile(), updateMultizoneProjectData(), UtilFiles::updateMultizoneToolPaths(), MultizoneManager::updateMultiZoneValues(), and ProjectSettingsDialog::updateProjectData().
 {
     _listMeshFiles = _list;
     _listMeshFileNames.clear();
     buildListofFileNames(_listMeshFiles,OPTION_MESH_FILE);
 }
void MultizoneProjectData::setProjectName (QString _name)
Set the project name.
Parameters
_name
Definition at line 64 of file multizoneprojectdata.cpp.
References _projectName.
Referenced by XmlUtil::getInitialMultizoneProjectInformation(), MainWindow::on_actionSave_As_triggered(), MultizoneProjectDialog::on_projectSelectionToolButton_clicked(), updateMultizoneProjectData(), and UtilFiles::updateMultizoneToolPaths().
 {
     _projectName = _name;
 }
void MultizoneProjectData::setProjectPath (QString _path)
Set the project Path.
Parameters
_path
Definition at line 44 of file multizoneprojectdata.cpp.
References _projectPath.
Referenced by MultizoneManager::checkProjectBasePathConsistency(), XmlUtil::getInitialMultizoneProjectInformation(), MainWindow::on_actionSave_As_triggered(), MultizoneProjectDialog::on_projectSelectionToolButton_clicked(), updateMultizoneProjectData(), and UtilFiles::updateMultizoneToolPaths().
 {
     _projectPath = _path;
 }
void MultizoneProjectData::updateMultizoneProjectData (MultizoneProjectData _newMultiData)
This function is to update the data from another object.
Parameters
_newMultiData
Definition at line 193 of file multizoneprojectdata.cpp.
References getListConfigFiles(), getListMeshFiles(), getProjectName(), getProjectPath(), setListConfigFiles(), setListMeshFiles(), setProjectName(), and setProjectPath().
Referenced by EditHelper::launchSettingsDialog().
 {
     setProjectPath(_newMultiData.getProjectPath());
     setProjectName(_newMultiData.getProjectName());
     setListConfigFiles(_newMultiData.getListConfigFiles());
     setListMeshFiles(_newMultiData.getListMeshFiles());
 }
void MultizoneProjectData::updatePair (QString _configPath, QString _meshPath)
Definition at line 241 of file multizoneprojectdata.cpp.
References _listConfigFileNames, _listMeshFileNames, _listMeshFiles, addConfigFile(), and addMeshFile().
Referenced by MainWindow::saveMultizoneData().
 {
     QString _configFileName = QFileInfo(_configPath).fileName();
     if (_listConfigFileNames.contains(_configFileName))
     {
         int _pos = _listConfigFileNames.indexOf(_configFileName);
         if (_pos != -1)
         {
             if (_pos> _listMeshFileNames.size())
                 addMeshFile(_meshPath);
             else
             {
                 _listMeshFiles.insert(_pos,_meshPath);
                 _listMeshFileNames.insert(_pos,QFileInfo(_meshPath).fileName());
             }
         }
     }else
     {
         addConfigFile(_configPath);
         addMeshFile(_meshPath);
     }
 }
Member Data Documentation
QStringList MultizoneProjectData::_listConfigFileNames private
Definition at line 43 of file multizoneprojectdata.h.
Referenced by buildListofFileNames(), getListConfigFileNames(), removeConfigFile(), setListConfigFiles(), and updatePair().
QStringList MultizoneProjectData::_listConfigFiles private
Definition at line 41 of file multizoneprojectdata.h.
Referenced by addConfigFile(), getListConfigFiles(), removeConfigFile(), and setListConfigFiles().
QStringList MultizoneProjectData::_listMeshFileNames private
Definition at line 44 of file multizoneprojectdata.h.
Referenced by buildListofFileNames(), getListMeshFileNames(), removeConfigFile(), removeMeshFile(), setListMeshFiles(), and updatePair().
QStringList MultizoneProjectData::_listMeshFiles private
Definition at line 42 of file multizoneprojectdata.h.
Referenced by addMeshFile(), getListMeshFiles(), removeConfigFile(), removeMeshFile(), setListMeshFiles(), and updatePair().
QString MultizoneProjectData::_projectName private
Definition at line 40 of file multizoneprojectdata.h.
Referenced by getProjectName(), isEmpty(), MultizoneProjectData(), and setProjectName().
QString MultizoneProjectData::_projectPath private
Definition at line 39 of file multizoneprojectdata.h.
Referenced by getProjectPath(), isEmpty(), MultizoneProjectData(), and setProjectPath().
The documentation for this class was generated from the following files:
Data/ProjectData/VO/multizoneprojectdata.h
Data/ProjectData/VO/multizoneprojectdata.cpp