BBIPED Platform: SalomeOptimizationDialog Class Reference
SalomeOptimizationDialog Class Reference
#include <salomeoptimizationdialog.h>
Signals
void outlogtext (QString ver)
Public Member Functions
SalomeOptimizationDialog (QWidget *parent=0)
~SalomeOptimizationDialog ()
void initializeDialog ()
void setMeshViewerPath (QString _path)
void setProjectName (QString _name)
void setProjectPath (QString _path)
void setTemplateData (QList< SalomeTemplateData > _template)
Private Types
enum
enum
enum
Private Slots
void errorConsole ()
void meshCreationFinished ()
void on_finishButton_clicked ()
void on_noIterationsLineEdit_editingFinished ()
void on_pushButton_clicked ()
void on_templateComboBox_currentIndexChanged (int index)
void on_variablesListTable_cellChanged (int row, int column)
void outputConsole ()
void slotProcessError (QProcess::ProcessError error)
Private Member Functions
void addColumns ()
void addRow (SalomeVariableData _var)
void addvarToSelectedTable (int _varRow)
void fillTable (int _templatePosition)
int findRowByVarName (QString _name)
int getPosMenu ()
QList< QList
< SalomeVariableData > > getVariablesList ()
void loadTemplateMenu ()
void refreshComboTemplates (QString _templateName)
void registerHelpers ()
void removevarFromSelectedTable (int _varRow)
void resetColumns ()
void runPythonFile ()
void updateHeader ()
Private Attributes
bool _isLoadingTable
QProcess * _meshCreationProcess
int _noIterations
QString _projectName
QString _projectPath
QTextEdit * _regEditor
QString _salomeMeshPath
QString _selectedTemplate
QtableUtil _tableHelper
QtableUtil _tableSelVarHelper
QList< SalomeTemplateData > _templateDataList
SalomeTemplateManager _templateManager
Ui::SalomeOptimizationDialog * ui
Detailed Description
Definition at line 19 of file salomeoptimizationdialog.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
variableChangedCol
variableNameCol
variableValueCol
variableOptimizeCol
Definition at line 66 of file salomeoptimizationdialog.h.
         {
         variableChangedCol = 0,
         variableNameCol = 1,
         variableValueCol = 2,
         variableOptimizeCol = 3
     };
anonymous enum private
Enumerator
selFirstIterCol
Definition at line 73 of file salomeoptimizationdialog.h.
         {
         selFirstIterCol = 2
     };
anonymous enum private
Enumerator
selVarName
selActualVal
initIterationCol
Definition at line 77 of file salomeoptimizationdialog.h.
         {
         selVarName = 0,
         selActualVal = 1,
         initIterationCol = 2
     };
Constructor & Destructor Documentation
SalomeOptimizationDialog::SalomeOptimizationDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 31 of file salomeoptimizationdialog.cpp.
References _isLoadingTable, _noIterations, _regEditor, _selectedTemplate, registerHelpers(), and ui.
                                                                   :
     QDialog(parent),
     ui(new Ui::SalomeOptimizationDialog)
 {
     ui->setupUi(this);
     registerHelpers();
     _selectedTemplate = "";
     _isLoadingTable = false;
     _noIterations = 0;
     _regEditor = ui->consoleTextEdit;
 }
SalomeOptimizationDialog::~SalomeOptimizationDialog ()
Definition at line 47 of file salomeoptimizationdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void SalomeOptimizationDialog::addColumns () private
Definition at line 231 of file salomeoptimizationdialog.cpp.
References _noIterations, and ui.
Referenced by on_noIterationsLineEdit_editingFinished().
 {
     int _lastCol = ui->selectedVarListTable->columnCount();
     for (int i = _lastCol; i < (_lastCol + _noIterations) ; i++)
         ui->selectedVarListTable->insertColumn(i);
 }
void SalomeOptimizationDialog::addRow (SalomeVariableData _var) private
Parameters
_var
Definition at line 183 of file salomeoptimizationdialog.cpp.
References _tableHelper, QtableUtil::addChangedColumn(), QtableUtil::addNonEditableText(), QtableUtil::addSelectableCheckColumn(), SalomeVariableData::getCurrentValue(), SalomeVariableData::getDefaultValue(), SalomeVariableData::getName(), SalomeVariableData::getOptimizedValue(), StrEqual, ui, variableChangedCol, variableNameCol, variableOptimizeCol, and variableValueCol.
Referenced by fillTable().
 {
    // QtableUtil _tableHelper;
     int _lastPos = ui->variablesListTable->rowCount();
     ui->variablesListTable->insertRow(_lastPos);
     ui->variablesListTable->setItem(_lastPos,variableChangedCol,_tableHelper.addChangedColumn());
     ui->variablesListTable->setItem(_lastPos,variableNameCol,_tableHelper.addNonEditableText(_var.getName()));
     ui->variablesListTable->setItem(_lastPos,variableValueCol,_tableHelper.addNonEditableText(_var.getCurrentValue()));
     ui->variablesListTable->setItem(_lastPos,variableOptimizeCol,_tableHelper.addSelectableCheckColumn());
     // Updating the values of the checkbox
     if (QString::compare(_var.getDefaultValue(),_var.getCurrentValue()) != StrEqual)
         ui->variablesListTable->item(_lastPos,variableChangedCol)->setCheckState(Qt::Checked);
     if (QString::compare(_var.getOptimizedValue(),"YES") == StrEqual)
     {
         ui->variablesListTable->item(_lastPos,variableOptimizeCol)->setCheckState(Qt::Checked);
         ui->variablesListTable->item(_lastPos,variableChangedCol)->setCheckState(Qt::Checked);
     }
 }
void SalomeOptimizationDialog::addvarToSelectedTable (int _varRow) private
Parameters
_varRow
Definition at line 273 of file salomeoptimizationdialog.cpp.
References _noIterations, _tableSelVarHelper, QtableUtil::addEditText(), QtableUtil::addNonEditableText(), initIterationCol, selActualVal, selVarName, ui, variableNameCol, and variableValueCol.
Referenced by on_variablesListTable_cellChanged().
 {
     int _lastRow = ui->selectedVarListTable->rowCount();
     QString _varName = ui->variablesListTable->item(_varRow,variableNameCol)->text();
     QString _varValue = ui->variablesListTable->item(_varRow,variableValueCol)->text();
     ui->selectedVarListTable->insertRow(_lastRow);
     ui->selectedVarListTable->setItem(_lastRow,selVarName,_tableSelVarHelper.addNonEditableText(_varName));
     ui->selectedVarListTable->setItem(_lastRow,selActualVal,_tableSelVarHelper.addNonEditableText(_varValue));
     for (int i = 0; i < _noIterations;i++)
         ui->selectedVarListTable->setCellWidget(_lastRow,(initIterationCol+i), _tableSelVarHelper.addEditText(""));
 }
void SalomeOptimizationDialog::errorConsole () private slot
Definition at line 512 of file salomeoptimizationdialog.cpp.
References _meshCreationProcess, and _regEditor.
Referenced by runPythonFile().
 {
     QString _output =_meshCreationProcess->readAllStandardError();
      //emit outlogtext(_output);
     _output = "[ERROR] -->" + _output;
     _regEditor->append(_output);
 }
void SalomeOptimizationDialog::fillTable (int _templatePosition) private
Parameters
_templatePosition
Definition at line 128 of file salomeoptimizationdialog.cpp.
References _isLoadingTable, _selectedTemplate, _templateManager, addRow(), getPosMenu(), SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), SalomeTemplateData::getVariableList(), and ui.
Referenced by on_templateComboBox_currentIndexChanged().
 {
     _isLoadingTable = true;
     if ((_selectedTemplate.isEmpty()) || (_templatePosition == -1) )
         return;
     int _templateNo = getPosMenu();
     if (_templateNo == -1)
         return;
     SalomeTemplateData _templateData;
     int _sizePredefinedTemplates = _templateManager.getTemplateNameList().size();
     if ( (_templatePosition <= _sizePredefinedTemplates ) && (_templateNo < _templateManager.getTemplates().size()) )
         _templateData = _templateManager.getTemplates().at(_templateNo);
     if ( (_templatePosition > _sizePredefinedTemplates ) && (_templateNo < _templateManager.getUserTemplates().size()) )
         _templateData = _templateManager.getUserTemplates().at(_templateNo);
     QList<SalomeVariableData> _variableList = _templateData.getVariableList();
     for (int i = 0; i < _variableList.size();i++)
         addRow(_variableList.at(i));
     ui->variablesListTable->resizeColumnsToContents();
     ui->variablesListTable->show();
     _isLoadingTable = false;
 }
int SalomeOptimizationDialog::findRowByVarName (QString _name) private
Parameters
_name
Returns
int
Definition at line 308 of file salomeoptimizationdialog.cpp.
References selVarName, StrEqual, and ui.
Referenced by removevarFromSelectedTable().
 {
     int _pos = -1;
     int _noRows = ui->selectedVarListTable->rowCount();
     for (int i = 0; i < _noRows;i++)
     {
         QString _cName= ui->selectedVarListTable->item(i,selVarName)->text();
         if (QString::compare(_cName,_name) == StrEqual)
             return i;
     }
     return _pos;
 }
int SalomeOptimizationDialog::getPosMenu () private
Returns
int
Definition at line 161 of file salomeoptimizationdialog.cpp.
References _selectedTemplate, _templateManager, SalomeTemplateManager::getTemplateNameList(), and SalomeTemplateManager::getUserTemplateNameList().
Referenced by fillTable(), getVariablesList(), and on_pushButton_clicked().
 {
    int _result = -1;
    if (!_selectedTemplate.isEmpty())
    {
        QStringList _listTemplates = _templateManager.getTemplateNameList();
        if (_listTemplates.contains(_selectedTemplate,Qt::CaseSensitive))
             return _listTemplates.indexOf(_selectedTemplate,0);
        _listTemplates.clear();
        _listTemplates = _templateManager.getUserTemplateNameList();
        if (_listTemplates.contains(_selectedTemplate,Qt::CaseSensitive))
            return _listTemplates.indexOf(_selectedTemplate,0) ;
    }
    return _result;
 }
QList< QList< SalomeVariableData > > SalomeOptimizationDialog::getVariablesList () private
Returns
QList<QList<SalomeVariableData> >
Definition at line 392 of file salomeoptimizationdialog.cpp.
References _templateManager, SalomeTemplateData::findByName(), getPosMenu(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), SalomeVariableData::setCurrentValue(), and ui.
Referenced by on_pushButton_clicked().
 {
    int _noRows = ui->selectedVarListTable->rowCount();
    int _noCols = ui->selectedVarListTable->columnCount();
    int _selectedTemplateIndex = ui->templateComboBox->currentIndex();
    int _posSelTemplate = getPosMenu();
    SalomeTemplateData _origTemplate;
 // Nota: mirar en el caso de user defined templates (seguramente anhadir getPos()
   if (_selectedTemplateIndex > _templateManager.getTemplates().size())
        _origTemplate = _templateManager.getUserTemplates().at(_posSelTemplate);
   else
        _origTemplate = _templateManager.getTemplates().at(_posSelTemplate);
    // We skip the first 2 columns
    // We build a List per each Iteration (Column)
    QList< QList<SalomeVariableData> > _listOfVariables;
     for (int _cColumn = 2; _cColumn < _noCols ; _cColumn++)
     {
        QList<SalomeVariableData> _listVariablesIteration;
        for (int _cRow = 0; _cRow < _noRows; _cRow++)
        {
            QString _variableName = ui->selectedVarListTable->item(_cRow,0)->text();
            QString _value = ((QLineEdit *)ui->selectedVarListTable->cellWidget(_cRow,_cColumn))->text();
            SalomeVariableData _variable = _origTemplate.findByName(_variableName);
            _variable.setCurrentValue(_value);
            _listVariablesIteration.push_back(_variable);
        }
        _listOfVariables.push_back(_listVariablesIteration);
     }
     return _listOfVariables;
 }
void SalomeOptimizationDialog::initializeDialog ()
Definition at line 55 of file salomeoptimizationdialog.cpp.
References _templateManager, SalomeTemplateManager::isInitialized(), SalomeTemplateManager::loadTemplate(), and loadTemplateMenu().
Referenced by ToolsHelper::createAutomaticMeshWithOptimization().
 {
     if (!_templateManager.isInitialized())
         _templateManager.loadTemplate();
     loadTemplateMenu();
 }
void SalomeOptimizationDialog::loadTemplateMenu () private
Definition at line 66 of file salomeoptimizationdialog.cpp.
References refreshComboTemplates().
Referenced by initializeDialog().
 {
     refreshComboTemplates("");
 }
void SalomeOptimizationDialog::meshCreationFinished () private slot
Definition at line 523 of file salomeoptimizationdialog.cpp.
References _meshCreationProcess, _regEditor, and ui.
Referenced by runPythonFile().
 {
     ui->finishButton->setEnabled(true);
     if (_meshCreationProcess->exitStatus() < 0)
      {
          _regEditor->append("[ERROR] --> Mesh cannot be created. Check your files");
          _regEditor->append(_meshCreationProcess->errorString());
      }else
         _regEditor->append("[OUTPUT] --> Mesh created. Check your folder");
 }
void SalomeOptimizationDialog::on_finishButton_clicked () private slot
Definition at line 540 of file salomeoptimizationdialog.cpp.
 {
     close();
 }
void SalomeOptimizationDialog::on_noIterationsLineEdit_editingFinished () private slot
Definition at line 207 of file salomeoptimizationdialog.cpp.
References _noIterations, addColumns(), resetColumns(), ui, and updateHeader().
 {
     resetColumns();
     _noIterations = ui->noIterationsLineEdit->text().toInt();
     addColumns();
     updateHeader();
 }
void SalomeOptimizationDialog::on_pushButton_clicked () private slot
Definition at line 328 of file salomeoptimizationdialog.cpp.
References _projectName, _projectPath, _templateManager, SalomePythonFileUtil::buildPythonFileForOptimization(), getPosMenu(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), getVariablesList(), runPythonFile(), SalomePythonFileUtil::setFileName(), SalomePythonFileUtil::setPathProject(), SalomePythonFileUtil::setTemplateData(), SalomePythonFileUtil::setVariableList(), and ui.
 {
     // TODO
     QList< QList<SalomeVariableData> > _userListVarOpt =  getVariablesList();
     int _posSelTemplate = getPosMenu();
     SalomeTemplateData _origTemplate;
     int _selectedTemplateIndex = ui->templateComboBox->currentIndex();
  // Nota: mirar en el caso de user defined templates (seguramente anhadir getPos()
    if (_selectedTemplateIndex > _templateManager.getTemplates().size())
         _origTemplate = _templateManager.getUserTemplates().at(_posSelTemplate);
    else
         _origTemplate = _templateManager.getTemplates().at(_posSelTemplate);
     SalomePythonFileUtil _pythonUtil;
     _pythonUtil.setFileName(_projectName);
     _pythonUtil.setPathProject(_projectPath);
     _pythonUtil.setTemplateData(_origTemplate);
     _pythonUtil.setVariableList(_userListVarOpt);
     int _iterations = ui->noIterationsLineEdit->text().toInt();
     _pythonUtil.buildPythonFileForOptimization(_iterations);
      // Running the python file
     runPythonFile();
 }
void SalomeOptimizationDialog::on_templateComboBox_currentIndexChanged (int index) private slot
Parameters
index
Definition at line 92 of file salomeoptimizationdialog.cpp.
References _selectedTemplate, _tableHelper, _tableSelVarHelper, fillTable(), QtableUtil::isInitialized(), QtableUtil::resetTable(), and ui.
 {
     _selectedTemplate = ui->templateComboBox->itemText(index);
     /*if (isUserTemplateSelected(index))
     {
         _isUserDefinedTemplate = true;
     }else
     {
         _isUserDefinedTemplate = false;
     }*/
     if(_tableHelper.isInitialized())
         _tableHelper.resetTable();
     if (_tableSelVarHelper.isInitialized())
         _tableSelVarHelper.resetTable();
     fillTable(index);
     //addSignals();
 }
void SalomeOptimizationDialog::on_variablesListTable_cellChanged (int row, int column) private slot
Parameters
row
column
Definition at line 257 of file salomeoptimizationdialog.cpp.
References _isLoadingTable, addvarToSelectedTable(), removevarFromSelectedTable(), ui, and variableOptimizeCol.
 {
     if ( (!_isLoadingTable) && (column == variableOptimizeCol) )
     {
         if (ui->variablesListTable->item(row,variableOptimizeCol)->checkState() == Qt::Checked)
             addvarToSelectedTable(row);
         else
             removevarFromSelectedTable(row);
     }
 }
void SalomeOptimizationDialog::outlogtext (QString ver) signal
Referenced by outputConsole().
void SalomeOptimizationDialog::outputConsole () private slot
Definition at line 501 of file salomeoptimizationdialog.cpp.
References _meshCreationProcess, _regEditor, and outlogtext().
Referenced by runPythonFile().
 {
     QString _output =_meshCreationProcess->readAllStandardOutput() ;
     _output = "[OUTPUT] --> " + _output;
     emit outlogtext(_output);
     _regEditor->append(_output);
 }
void SalomeOptimizationDialog::refreshComboTemplates (QString _templateName) private
Parameters
_templateName
Definition at line 75 of file salomeoptimizationdialog.cpp.
References _selectedTemplate, _templateManager, SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getUserTemplateNameList(), and ui.
Referenced by loadTemplateMenu().
 {
     ui->templateComboBox->clear();
     QStringList _templateNameList;
     _templateNameList.append("");
     _templateNameList.append(_templateManager.getTemplateNameList());
     _templateNameList.append(_templateManager.getUserTemplateNameList());
    ui->templateComboBox->addItems(_templateNameList);
    _selectedTemplate = _templateName;
 }
void SalomeOptimizationDialog::registerHelpers () private
Definition at line 117 of file salomeoptimizationdialog.cpp.
References _tableHelper, _tableSelVarHelper, QtableUtil::registerTable(), and ui.
Referenced by SalomeOptimizationDialog().
 {
     _tableHelper.registerTable(ui->variablesListTable);
     _tableSelVarHelper.registerTable(ui->selectedVarListTable);
 }
void SalomeOptimizationDialog::removevarFromSelectedTable (int _varRow) private
Parameters
_varRow
Definition at line 291 of file salomeoptimizationdialog.cpp.
References findRowByVarName(), ui, and variableNameCol.
Referenced by on_variablesListTable_cellChanged().
 {
     QString _varName = ui->variablesListTable->item(_varRow,variableNameCol)->text();
     if (_varName.isEmpty())
         return;
     int _posToRemove = findRowByVarName(_varName);
     if ( (_posToRemove == -1) || (_posToRemove >= ui->selectedVarListTable->rowCount()) )
         return;
     ui->selectedVarListTable->removeRow(_posToRemove);
 }
void SalomeOptimizationDialog::resetColumns () private
Definition at line 219 of file salomeoptimizationdialog.cpp.
References ui.
Referenced by on_noIterationsLineEdit_editingFinished().
 {
     int _noCol = ui->selectedVarListTable->columnCount();
     if (_noCol > 2)
         for (int i = _noCol; i >= 2; i--)
             ui->selectedVarListTable->removeColumn(i);
 }
void SalomeOptimizationDialog::runPythonFile () private
Definition at line 361 of file salomeoptimizationdialog.cpp.
References _meshCreationProcess, _projectName, _projectPath, _regEditor, _salomeMeshPath, errorConsole(), meshCreationFinished(), outputConsole(), slotProcessError(), and ui.
Referenced by on_pushButton_clicked().
 {
     QFileInfo _salomeFilePath(_salomeMeshPath);
     QString _salomeToolPath = _salomeFilePath.absolutePath();
     if (_salomeToolPath.isEmpty())
         return;
     ui->pushButton->setEnabled(false);
     _regEditor->append("Starting Python JobManager Execution ....");
     _meshCreationProcess = new QProcess(this);
     _meshCreationProcess->setWorkingDirectory(QDir(_projectPath).filePath("Python"));
   QString _meshCommand("") ;
     _meshCommand = _salomeToolPath + "/runSession runSalome -t -u" + _projectName +"_opt.py";
     connect(_meshCreationProcess, SIGNAL(error(QProcess::ProcessError)),
             this, SLOT(slotProcessError(QProcess::ProcessError)));
     connect(_meshCreationProcess, SIGNAL(readyReadStandardOutput()), this, SLOT(outputConsole()));
     connect(_meshCreationProcess, SIGNAL(readyReadStandardError()), this, SLOT(errorConsole()));
     connect(_meshCreationProcess, SIGNAL(finished(int)), this, SLOT(meshCreationFinished()));
     _regEditor->append("[START MESH CREATION] --> Running " + _meshCommand);
     _meshCreationProcess->start(_meshCommand);
     // Updating the Text of the Create Mesh Button
 }
void SalomeOptimizationDialog::setMeshViewerPath (QString _path)
Parameters
_path
Definition at line 459 of file salomeoptimizationdialog.cpp.
References _salomeMeshPath.
Referenced by ToolsHelper::createAutomaticMeshWithOptimization().
 {
     _salomeMeshPath = _path;
 }
void SalomeOptimizationDialog::setProjectName (QString _name)
Parameters
_name
Definition at line 440 of file salomeoptimizationdialog.cpp.
References _projectName.
Referenced by ToolsHelper::createAutomaticMeshWithOptimization().
 {
     _projectName = _name;
 }
void SalomeOptimizationDialog::setProjectPath (QString _path)
Parameters
_path
Definition at line 450 of file salomeoptimizationdialog.cpp.
References _projectPath.
Referenced by ToolsHelper::createAutomaticMeshWithOptimization().
 {
     _projectPath = _path;
 }
void SalomeOptimizationDialog::setTemplateData (QList< SalomeTemplateData > _template)
Parameters
_template
Definition at line 431 of file salomeoptimizationdialog.cpp.
References _templateDataList.
 {
     _templateDataList = _template;
 }
void SalomeOptimizationDialog::slotProcessError (QProcess::ProcessError error) private slot
Parameters
error
Definition at line 470 of file salomeoptimizationdialog.cpp.
References _regEditor.
Referenced by runPythonFile().
 {
     switch (error) {
         case QProcess::FailedToStart :
         _regEditor->append("FAILED to start the application: Check the executable configuration in the Preferences Menu");
             break;
     case QProcess::Crashed:
        _regEditor->append( "STOP Running simulation" );
         break;
        case QProcess::Timedout:
        _regEditor->append("TimedOut process: Contact Support");
         break;
     case QProcess::WriteError:
        _regEditor->append("Write Error: Check the permissions of the folder");
         break;
     case QProcess::ReadError:
        _regEditor->append( "Read Error: Check the permissions of the files ");
         break;
     case QProcess::UnknownError:
       _regEditor->append("Unknown Error: Contact Support ");
         break;
     }
 }
void SalomeOptimizationDialog::updateHeader () private
Definition at line 243 of file salomeoptimizationdialog.cpp.
References _noIterations, and ui.
Referenced by on_noIterationsLineEdit_editingFinished().
 {
     QString _headerTitle="Variable Name;Actual Value";
     for (int i = 1; i <=_noIterations;i++ )
         _headerTitle = _headerTitle + ";Iteration "+QString::number(i);
     ui->selectedVarListTable->setHorizontalHeaderLabels(_headerTitle.split(";"));
 }
Member Data Documentation
bool SalomeOptimizationDialog::_isLoadingTable private
Definition at line 62 of file salomeoptimizationdialog.h.
Referenced by fillTable(), on_variablesListTable_cellChanged(), and SalomeOptimizationDialog().
QProcess* SalomeOptimizationDialog::_meshCreationProcess private
Definition at line 89 of file salomeoptimizationdialog.h.
Referenced by errorConsole(), meshCreationFinished(), outputConsole(), and runPythonFile().
int SalomeOptimizationDialog::_noIterations private
Definition at line 64 of file salomeoptimizationdialog.h.
Referenced by addColumns(), addvarToSelectedTable(), on_noIterationsLineEdit_editingFinished(), SalomeOptimizationDialog(), and updateHeader().
QString SalomeOptimizationDialog::_projectName private
Definition at line 85 of file salomeoptimizationdialog.h.
Referenced by on_pushButton_clicked(), runPythonFile(), and setProjectName().
QString SalomeOptimizationDialog::_projectPath private
Definition at line 86 of file salomeoptimizationdialog.h.
Referenced by on_pushButton_clicked(), runPythonFile(), and setProjectPath().
QTextEdit* SalomeOptimizationDialog::_regEditor private
Definition at line 90 of file salomeoptimizationdialog.h.
Referenced by errorConsole(), meshCreationFinished(), outputConsole(), runPythonFile(), SalomeOptimizationDialog(), and slotProcessError().
QString SalomeOptimizationDialog::_salomeMeshPath private
Definition at line 87 of file salomeoptimizationdialog.h.
Referenced by runPythonFile(), and setMeshViewerPath().
QString SalomeOptimizationDialog::_selectedTemplate private
Definition at line 57 of file salomeoptimizationdialog.h.
Referenced by fillTable(), getPosMenu(), on_templateComboBox_currentIndexChanged(), refreshComboTemplates(), and SalomeOptimizationDialog().
QtableUtil SalomeOptimizationDialog::_tableHelper private
Definition at line 59 of file salomeoptimizationdialog.h.
Referenced by addRow(), on_templateComboBox_currentIndexChanged(), and registerHelpers().
QtableUtil SalomeOptimizationDialog::_tableSelVarHelper private
Definition at line 60 of file salomeoptimizationdialog.h.
Referenced by addvarToSelectedTable(), on_templateComboBox_currentIndexChanged(), and registerHelpers().
QList<SalomeTemplateData> SalomeOptimizationDialog::_templateDataList private
Definition at line 84 of file salomeoptimizationdialog.h.
Referenced by setTemplateData().
SalomeTemplateManager SalomeOptimizationDialog::_templateManager private
Definition at line 56 of file salomeoptimizationdialog.h.
Referenced by fillTable(), getPosMenu(), getVariablesList(), initializeDialog(), on_pushButton_clicked(), and refreshComboTemplates().
Ui::SalomeOptimizationDialog* SalomeOptimizationDialog::ui private
Definition at line 55 of file salomeoptimizationdialog.h.
Referenced by addColumns(), addRow(), addvarToSelectedTable(), fillTable(), findRowByVarName(), getVariablesList(), meshCreationFinished(), on_noIterationsLineEdit_editingFinished(), on_pushButton_clicked(), on_templateComboBox_currentIndexChanged(), on_variablesListTable_cellChanged(), refreshComboTemplates(), registerHelpers(), removevarFromSelectedTable(), resetColumns(), runPythonFile(), SalomeOptimizationDialog(), updateHeader(), and ~SalomeOptimizationDialog().
The documentation for this class was generated from the following files:
Forms/ToolsDialog/salomeoptimizationdialog.h
Forms/ToolsDialog/salomeoptimizationdialog.cpp