BBIPED Platform: SpecificBoundaryVariableDialog Class Reference
SpecificBoundaryVariableDialog Class Reference
#include <specificboundaryvariabledialog.h>
Public Member Functions
SpecificBoundaryVariableDialog (QWidget *parent=0)
Constructor.
~SpecificBoundaryVariableDialog ()
Destructor.
QString getBoundaryName ()
Returns the boundary name.
QString getBoundaryType ()
Returns the boundary type.
QStringList getConfiguredBoundary ()
Returns the configured Boundary list.
QStringList getCurrentValues ()
void loadValues ()
Function that load the values.
void setBoundaryName (QString _newBoundName)
Set the boundary name.
void setBoundaryType (QString _newBoundType)
Set the boundary type.
void setCurrentValues (QStringList _list)
void setHelpContent (QString _help)
Function to set the help content.
void setMarkerMenuManager (MarkerMenuManager *_manager)
set the marker menu manager
void setMeshVariables (QHash< QString, QString > _list)
Function that sest the values of the boundary values.
void setStoredUserConfigValues (QHash< QString, QString > _userValues)
Function that saves the changes made by the user.
bool userAcceptChanges ()
Function that controls when the user press the accept button.
Private Slots
void changedComboValueByUser (QString position)
Slot that controls the combo value changed by the user.
void changedLineTextSlot (QString position)
SLot that controls the change of text.
void on_boundaryDialogGroupBox_accepted ()
Function that provides the functionality when the user accpets the changes.
void on_boundaryDialogGroupBox_rejected ()
Function that controls when the user press the cancel button.
void on_boundaryHelpButton_clicked ()
Function that controls when the user press the help button.
Private Member Functions
void addRow (SolverMarkerMenu _element)
Function that adds a row to the table.
void addSignals ()
Function that adds the signals.
QString getValueFromTable (int _row)
Function that gets the values from the table.
void loadTableHeader ()
Function that loads the table header.
void loadUserTableForConfiguration (QString _fileName)
Function that loads the correspondent table.
void updateWithUserValues ()
Function that update the boundary values with the user ones.
Private Attributes
QString _boundName
QString _boundType
QStringList _configuredBoundary
QStringList _cValues
QString _helpContent
bool _isLoadingTable
MarkerMenuManager * _markerManager
QStringList _meshList
QHash< QString, QString > _meshVariables
QHash< QString, QString > _previousBoundConfig
QSignalMapper * _signalMapper
QSignalMapper * _signalMapperTxtEdit
bool _userAcceptChanges
Ui::SpecificBoundaryVariableDialog * ui
Detailed Description
Definition at line 15 of file specificboundaryvariabledialog.h.
Constructor & Destructor Documentation
SpecificBoundaryVariableDialog::SpecificBoundaryVariableDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 35 of file specificboundaryvariabledialog.cpp.
References _isLoadingTable, _signalMapper, _signalMapperTxtEdit, _userAcceptChanges, and ui.
                                                                               :
     QDialog(parent),
     ui(new Ui::SpecificBoundaryVariableDialog)
 {
     ui->setupUi(this);
     _isLoadingTable = false;
     _signalMapper = new QSignalMapper(this);
     _signalMapperTxtEdit = new QSignalMapper(this);
     _userAcceptChanges = false;
 }
SpecificBoundaryVariableDialog::~SpecificBoundaryVariableDialog ()
Destructor.
Definition at line 50 of file specificboundaryvariabledialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void SpecificBoundaryVariableDialog::addRow (SolverMarkerMenu _element) private
Function that adds a row to the table.
Parameters
_element
Definition at line 252 of file specificboundaryvariabledialog.cpp.
References _meshList, QtableUtil::addChangedColumn(), QtableUtil::addEditText(), QtableUtil::addNonEditableText(), ColumnCheck, ColumnMarkerUnitMeasure, ColumnSelVal, ColumnVarName, SolverMarkerMenu::getDefaultValueList(), SolverMarkerMenu::getParametersList(), SolverMarkerMenu::getTypeList(), SolverMarkerMenu::getUnitList(), StrEqual, and ui.
Referenced by loadUserTableForConfiguration().
 {
     QtableUtil _tableHelper;
     QStringList _parameterList = _element.getParametersList();
     QStringList _typeList = _element.getTypeList();
     if (_parameterList.count() != _typeList.count())
         return;
     for (int i = 0; i < _parameterList.count();i++)
     {
         int _lastRow = ui->boundaryTable->rowCount();
         ui->boundaryTable->insertRow(_lastRow);
         ui->boundaryTable->setItem(_lastRow,ColumnCheck,_tableHelper.addChangedColumn() );
         ui->boundaryTable->setItem(_lastRow,ColumnVarName,
                                    _tableHelper.addNonEditableText(_parameterList.at(i)));
         // In this case all the options are selectable. Otherwise this needs to be modified
         QList<bool> _selectable;
         for (int i = 0; i < _meshList.size();i++)
             _selectable.append(true);
         //if (QString::compare(_typeList.at(i),XML_MARKER_TYPE_NUMBER_VAL_ATT) == StrEqual)
         //{
         // Adding Default Values
         QString _defaultValue = _element.getDefaultValueList().at(i);
           ui->boundaryTable->setCellWidget(_lastRow,ColumnSelVal,_tableHelper.addEditText(_defaultValue));
         //}
         //else
         //    ui->boundaryTable->setCellWidget(_lastRow,ColumnSelVal,_tableHelper.addCombo(_meshList,_selectable));
         // Adding the Unit Column
         QString _unitElement = _element.getUnitList().at(i);
         if( (_unitElement.isEmpty()) || (QString::compare(_unitElement,"NONE") == StrEqual) )
             _unitElement = "";
         ui->boundaryTable->setItem(_lastRow,ColumnMarkerUnitMeasure,_tableHelper.addNonEditableText(_unitElement));
     }
 }
void SpecificBoundaryVariableDialog::addSignals () private
Function that adds the signals.
Definition at line 154 of file specificboundaryvariabledialog.cpp.
References _signalMapper, _signalMapperTxtEdit, changedComboValueByUser(), changedLineTextSlot(), ColumnSelVal, and ui.
Referenced by loadUserTableForConfiguration().
 {
     bool _foundCombos = false;
     bool _foundLineEdit = true;
     if (ui->boundaryTable->rowCount() > 0)
     {
         for (int i = 0; i< ui->boundaryTable->rowCount();i++)
         {
                 QWidget * _item;
                 _item = ui->boundaryTable->cellWidget(i,ColumnSelVal);
                 if (_item)
                 {
                     QComboBox *_comboItem = qobject_cast<QComboBox *> (_item);
                     if (_comboItem)
                     {
                         connect(_comboItem, SIGNAL(currentIndexChanged(int)), _signalMapper, SLOT(map()),Qt::UniqueConnection);
                        _signalMapper->setMapping(_comboItem, QString("%1-%2").arg(i).arg(ColumnSelVal));
                         _foundCombos = true;
                     }
                     else
                     {
                       QLineEdit * _line = qobject_cast<QLineEdit *> (_item);
                         if (_line)
{
                             connect(_line,SIGNAL(editingFinished()),_signalMapperTxtEdit,SLOT(map()),Qt::UniqueConnection);
                             _signalMapperTxtEdit->setMapping(_line,QString("%1-%2").arg(i).arg(ColumnSelVal));
                             _foundLineEdit = true;
                         }
                     }
                 }
         }
     }
    if (_foundCombos)
         connect(_signalMapper, SIGNAL(mapped(const QString &)),this, SLOT(changedComboValueByUser(const QString &)),Qt::UniqueConnection);
    if (_foundLineEdit)
         connect(_signalMapperTxtEdit, SIGNAL(mapped(const QString &)),this, SLOT(changedLineTextSlot(const QString &)),Qt::UniqueConnection);
 }
void SpecificBoundaryVariableDialog::changedComboValueByUser (QString position) private slot
Slot that controls the combo value changed by the user.
Parameters
position
Definition at line 220 of file specificboundaryvariabledialog.cpp.
References _isLoadingTable, ColumnCheck, and ui.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
         QStringList coordinates = position.split("-");
         int row = coordinates[0].toInt();
         ui->boundaryTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
     }
 }
void SpecificBoundaryVariableDialog::changedLineTextSlot (QString position) private slot
SLot that controls the change of text.
Parameters
position
Definition at line 205 of file specificboundaryvariabledialog.cpp.
References _isLoadingTable, ColumnCheck, and ui.
Referenced by addSignals().
 {
    if (!_isLoadingTable)
     {
        QStringList coordinates = position.split("-");
        int row = coordinates[0].toInt();
        ui->boundaryTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
     }
 }
QString SpecificBoundaryVariableDialog::getBoundaryName ()
Returns the boundary name.
Returns
QString
Definition at line 374 of file specificboundaryvariabledialog.cpp.
References _boundName.
 {
     return _boundName;
 }
QString SpecificBoundaryVariableDialog::getBoundaryType ()
Returns the boundary type.
Returns
QString
Definition at line 353 of file specificboundaryvariabledialog.cpp.
References _boundType.
 {
     return _boundType;
 }
QStringList SpecificBoundaryVariableDialog::getConfiguredBoundary ()
Returns the configured Boundary list.
Returns
QStringList
Definition at line 384 of file specificboundaryvariabledialog.cpp.
References _configuredBoundary.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     return _configuredBoundary;
 }
QStringList SpecificBoundaryVariableDialog::getCurrentValues ()
Definition at line 447 of file specificboundaryvariabledialog.cpp.
References _cValues.
 {
     return _cValues;
 }
QString SpecificBoundaryVariableDialog::getValueFromTable (int _row) private
Function that gets the values from the table.
Parameters
_row
Returns
QString
Definition at line 324 of file specificboundaryvariabledialog.cpp.
References ColumnSelVal, and ui.
Referenced by on_boundaryDialogGroupBox_accepted().
 {
     QComboBox * _combo = qobject_cast<QComboBox *> (ui->boundaryTable->cellWidget(_row,ColumnSelVal));
     if (_combo)
          return (_combo->currentText());
     else{
         QLineEdit * _line = qobject_cast<QLineEdit *>  (ui->boundaryTable->cellWidget(_row,ColumnSelVal));
         if (_line)
             return (_line->text());
     }
     return QString("");
 }
void SpecificBoundaryVariableDialog::loadTableHeader () private
Function that loads the table header.
Definition at line 139 of file specificboundaryvariabledialog.cpp.
References ui.
Referenced by loadValues().
 {
     ui->boundaryTable->setColumnCount(4);
     ui->boundaryTable->setHorizontalHeaderLabels( QString("Changed;Parameter Name;Parameter Value;Unit").split(";"));
     ui->boundaryTable->horizontalHeader()->setVisible(true);
 }
void SpecificBoundaryVariableDialog::loadUserTableForConfiguration (QString _fileName) private
Function that loads the correspondent table.
Parameters
_fileName
Definition at line 125 of file specificboundaryvariabledialog.cpp.
References _isLoadingTable, _markerManager, addRow(), addSignals(), MarkerMenuManager::getMarkerNodeByName(), and updateWithUserValues().
Referenced by loadValues().
 {
     _isLoadingTable = true;
     SolverMarkerMenu _element = _markerManager->getMarkerNodeByName(_fileName);
     addRow(_element);
     updateWithUserValues();
     addSignals();
     _isLoadingTable = false;
 }
void SpecificBoundaryVariableDialog::loadValues ()
Function that load the values.
Definition at line 63 of file specificboundaryvariabledialog.cpp.
References _boundName, _boundType, loadTableHeader(), loadUserTableForConfiguration(), and ui.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     ui->boundaryTypeText->setText(_boundType);
     ui->boundaryNameText->setText(_boundName);
     loadTableHeader();
     loadUserTableForConfiguration(_boundType);
     ui->boundaryTable->resizeColumnsToContents();
 }
void SpecificBoundaryVariableDialog::on_boundaryDialogGroupBox_accepted () private slot
Function that provides the functionality when the user accpets the changes.
Definition at line 234 of file specificboundaryvariabledialog.cpp.
References _configuredBoundary, _userAcceptChanges, getValueFromTable(), and ui.
 {
     for (int i = 0; i < ui->boundaryTable->rowCount(); i++)
     {
         QString _result = getValueFromTable(i);
         if (!_result.isEmpty())
             _configuredBoundary.append(_result);
     }
    _userAcceptChanges = true;
 }
void SpecificBoundaryVariableDialog::on_boundaryDialogGroupBox_rejected () private slot
Function that controls when the user press the cancel button.
Definition at line 403 of file specificboundaryvariabledialog.cpp.
References _userAcceptChanges.
 {
     _userAcceptChanges = false;
 }
void SpecificBoundaryVariableDialog::on_boundaryHelpButton_clicked () private slot
Function that controls when the user press the help button.
Definition at line 422 of file specificboundaryvariabledialog.cpp.
References _helpContent, HelpDialog::loadHelpText(), and HelpDialog::setHelpText().
 {
     HelpDialog *  _helpDialog = new HelpDialog();
      _helpDialog->setHelpText(_helpContent);
      _helpDialog->loadHelpText();
      _helpDialog->exec();
      delete _helpDialog;
 }
void SpecificBoundaryVariableDialog::setBoundaryName (QString _newBoundName)
Set the boundary name.
Parameters
_newBoundName
Definition at line 364 of file specificboundaryvariabledialog.cpp.
References _boundName.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _boundName = _newBoundName;
 }
void SpecificBoundaryVariableDialog::setBoundaryType (QString _newBoundType)
Set the boundary type.
Parameters
_newBoundType
Definition at line 343 of file specificboundaryvariabledialog.cpp.
References _boundType.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _boundType = _newBoundType;
 }
void SpecificBoundaryVariableDialog::setCurrentValues (QStringList _list)
Definition at line 442 of file specificboundaryvariabledialog.cpp.
References _cValues.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _cValues = _list;
 }
void SpecificBoundaryVariableDialog::setHelpContent (QString _help)
Function to set the help content.
Parameters
_help
Definition at line 437 of file specificboundaryvariabledialog.cpp.
References _helpContent.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _helpContent = _help;
 }
void SpecificBoundaryVariableDialog::setMarkerMenuManager (MarkerMenuManager * _manager)
set the marker menu manager
Parameters
_manager
Definition at line 394 of file specificboundaryvariabledialog.cpp.
References _markerManager.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _markerManager = _manager;
 }
void SpecificBoundaryVariableDialog::setMeshVariables (QHash< QString, QString > _list)
Function that sest the values of the boundary values.
Parameters
QHash<QString
_list
Definition at line 299 of file specificboundaryvariabledialog.cpp.
References _meshList, and _meshVariables.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _meshVariables = _list;
     if (!_meshVariables.isEmpty())
     {
         QHashIterator<QString,QString> _iter(_meshVariables);
         while(_iter.hasNext())
         {
             _iter.next();
             QString _value = _iter.value();
             _meshList.append(_value);
         }
     }
 }
void SpecificBoundaryVariableDialog::setStoredUserConfigValues (QHash< QString, QString > _userValues)
Function that saves the changes made by the user.
Parameters
QHash<QString
_userValues
Definition at line 114 of file specificboundaryvariabledialog.cpp.
References _previousBoundConfig.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     _previousBoundConfig = _userValues;
 }
void SpecificBoundaryVariableDialog::updateWithUserValues () private
Function that update the boundary values with the user ones.
Definition at line 77 of file specificboundaryvariabledialog.cpp.
References _cValues, ColumnCheck, ColumnSelVal, and ui.
Referenced by loadUserTableForConfiguration().
 {
     int _row = 0;
         for (int i = 0; i < _cValues.size();i++)
         {
             QString _valueToSet = _cValues.at(i);
             QComboBox *  _combo = qobject_cast<QComboBox *> ( ui->boundaryTable->cellWidget(_row,ColumnSelVal));
             if (_combo)
             {
                 int _index = _combo->findText(_valueToSet);
                 if (_index != -1)
                 {
                     _combo->setCurrentIndex(_index);
                     ui->boundaryTable->item(_row,ColumnCheck)->setCheckState(Qt::Checked);
                 }
             }else
             {
                 QLineEdit *  _line = qobject_cast<QLineEdit *> ( ui->boundaryTable->cellWidget(_row,ColumnSelVal));
                 if ((_line) && (!_valueToSet.isNull()) && (!_valueToSet.isEmpty()) )
                 {
                     _line->setText(_valueToSet);
                     ui->boundaryTable->item(_row,ColumnCheck)->setCheckState(Qt::Checked);
                 }
             }
             _row++;
         }
 }
bool SpecificBoundaryVariableDialog::userAcceptChanges ()
Function that controls when the user press the accept button.
Returns
bool
Definition at line 412 of file specificboundaryvariabledialog.cpp.
References _userAcceptChanges.
Referenced by MeshDialog::launchSpecificBoundaryConfigWindow().
 {
     return _userAcceptChanges;
 }
Member Data Documentation
QString SpecificBoundaryVariableDialog::_boundName private
Definition at line 62 of file specificboundaryvariabledialog.h.
Referenced by getBoundaryName(), loadValues(), and setBoundaryName().
QString SpecificBoundaryVariableDialog::_boundType private
Definition at line 61 of file specificboundaryvariabledialog.h.
Referenced by getBoundaryType(), loadValues(), and setBoundaryType().
QStringList SpecificBoundaryVariableDialog::_configuredBoundary private
Definition at line 64 of file specificboundaryvariabledialog.h.
Referenced by getConfiguredBoundary(), and on_boundaryDialogGroupBox_accepted().
QStringList SpecificBoundaryVariableDialog::_cValues private
Definition at line 77 of file specificboundaryvariabledialog.h.
Referenced by getCurrentValues(), setCurrentValues(), and updateWithUserValues().
QString SpecificBoundaryVariableDialog::_helpContent private
Definition at line 65 of file specificboundaryvariabledialog.h.
Referenced by on_boundaryHelpButton_clicked(), and setHelpContent().
bool SpecificBoundaryVariableDialog::_isLoadingTable private
Definition at line 74 of file specificboundaryvariabledialog.h.
Referenced by changedComboValueByUser(), changedLineTextSlot(), loadUserTableForConfiguration(), and SpecificBoundaryVariableDialog().
MarkerMenuManager* SpecificBoundaryVariableDialog::_markerManager private
Definition at line 66 of file specificboundaryvariabledialog.h.
Referenced by loadUserTableForConfiguration(), and setMarkerMenuManager().
QStringList SpecificBoundaryVariableDialog::_meshList private
Definition at line 69 of file specificboundaryvariabledialog.h.
Referenced by addRow(), and setMeshVariables().
QHash<QString,QString> SpecificBoundaryVariableDialog::_meshVariables private
Definition at line 67 of file specificboundaryvariabledialog.h.
Referenced by setMeshVariables().
QHash<QString,QString> SpecificBoundaryVariableDialog::_previousBoundConfig private
Definition at line 68 of file specificboundaryvariabledialog.h.
Referenced by setStoredUserConfigValues().
QSignalMapper* SpecificBoundaryVariableDialog::_signalMapper private
Definition at line 71 of file specificboundaryvariabledialog.h.
Referenced by addSignals(), and SpecificBoundaryVariableDialog().
QSignalMapper* SpecificBoundaryVariableDialog::_signalMapperTxtEdit private
Definition at line 72 of file specificboundaryvariabledialog.h.
Referenced by addSignals(), and SpecificBoundaryVariableDialog().
bool SpecificBoundaryVariableDialog::_userAcceptChanges private
Definition at line 75 of file specificboundaryvariabledialog.h.
Referenced by on_boundaryDialogGroupBox_accepted(), on_boundaryDialogGroupBox_rejected(), SpecificBoundaryVariableDialog(), and userAcceptChanges().
Ui::SpecificBoundaryVariableDialog* SpecificBoundaryVariableDialog::ui private
Definition at line 59 of file specificboundaryvariabledialog.h.
Referenced by addRow(), addSignals(), changedComboValueByUser(), changedLineTextSlot(), getValueFromTable(), loadTableHeader(), loadValues(), on_boundaryDialogGroupBox_accepted(), SpecificBoundaryVariableDialog(), updateWithUserValues(), and ~SpecificBoundaryVariableDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/specificboundaryvariabledialog.h
Forms/SolverMenuDialog/specificboundaryvariabledialog.cpp