BBIPED Platform: MeshDialog Class Reference
MeshDialog Class Reference
#include <meshdialog.h>
Public Member Functions
MeshDialog (QWidget *parent=0)
Constructor.
~MeshDialog ()
Destructor.
QHash< QString, QString > getMeshValues ()
Returns the mesh values.
QHash< QString, QString > getUserBndVariableValues ()
QHash< QString, QString > getUserConfiguredMeshValues ()
Returns user configured mesh values.
bool hasUserAcceptChanges ()
void loadMenu ()
Function that loads the main menu elements.
bool needToSave ()
Returns true if the status is needed to be saved.
void setIsMultizoneProject (bool _val)
void setIsNSProblem (bool _val)
void setMeshValues (QHash< QString, QString > _val)
Function to set the mesh values.
void setSolverConfigManager (SolverConfigManager *_manager)
Set the solver config manager.
void setUserConfiguredMeshValues (QHash< QString, QString > _newUserValues)
Set up configured mesh values.
Private Types
enum ColumnNames
Private Slots
void changedComboValueByUser (QString position)
Slot that controls the change of the combo value by the user.
void handleItem (QString position)
void on_meshButtonBox_accepted ()
Function that performs the functinality when the user clicks accept button.
void on_meshButtonBox_rejected ()
Fucntion that perfomrs the functionality for cancel click button.
void on_meshTableWidget_cellClicked (int row, int column)
Function to perform actions when a cell is clicked.
void on_meshTreeView_clicked (const QModelIndex &index)
Function that performs the functionality when the user click on a element of the tree view.
Private Member Functions
void addSignals ()
Function to add signals.
void buildAllToolTips ()
Function to build up all the tooltips.
QString buildHelpContent (int row)
Function to build up the help content.
void buildUserBndValueMap ()
bool checkIfAllBoundaryNames (QStringList _list)
void createMeshVariables (QString _menu, QList< SolverVariableVO > _varList)
void fillTable (QString _parent)
Function that fills the table according user clicks.
int findMeshVariableToUpdate (QString _nameToFind, QString _menu)
int findMeshVariableToUpdateByBndValue (QString _bndToFind, QString _menu)
int findMeshVariableToUpdateByFileNameVar (QString _nameToFind, QString _menu)
QString getBndTypeName ()
int getBoundaryRow (QString _boundaryName)
Returns the row where the boundary is placed.
void initBndNamesInAssociatedMeshVar ()
void initializeMeshValues ()
bool isAllowedTheAssociatedMeshVariables (QString _variableName)
bool isSpecialBoundary (QString _keyVariable)
Returns if it is a special boundary.
void launchSpecificBoundaryConfigWindow (int row, QString _value, QComboBox *_combo)
Function to launch the Specific Boundary config window.
void loadTableHeader ()
Function that loads the table Header.
bool needToOpenSpecificConfigWindow (QString _varName)
Function that checks if it is needed to open the Specific boundary dialog.
void removeBoundaryNamesInAssociatedVariables ()
QStringList removeEmptyStrings (QStringList _list)
QList< SolverVariableVO > removeNonVisibleVariables (QList< SolverVariableVO > _list)
void resetTable ()
Function that resets the table contents.
void restoreValues (int _prevRow)
Function to restore the values in the row.
void saveUserChanges (QString _value, int _itemRow)
Function to save the user changes.
void showValuesInValueCol (int row, QString _value)
Function to show the values that comes from the specific window.
QStringList splitBndNameAndValues (QStringList _list)
void updateComboValue (int _rowToUpdate, QString _selVarName)
Function to update the combo value with previous values.
void updateTable (QString _userVarName, QStringList _bndNames, QStringList _bndValues)
void updateTableWithUserValues ()
void updateTableWithYesNoValues (QStringList _bndNames, QStringList _bndValues)
Private Attributes
QStringList _associatedMeshVariables
QHash< QString, QString > _configUserMeshValues
bool _isLoadingTable
bool _isMultizoneProject
bool _isNSProblem
MarkerMenuManager * _markerManager
QHash< QString, QString > _meshValues
bool _needToSave
QHash< QString, QString > _previousUserMeshValues
QString _selectedSubMenu
QSignalMapper * _signalMapper
QSignalMapper * _signalMapperCheckList
SolverConfigManager * _solverManager
QHash< QString, QString > _storedSpecificBoundValues
bool _userAcceptChanges
QHash< QString, QString > _userBndVariableValues
QList< UserMeshVO > _userMeshVariablesList
Ui::MeshDialog * ui
Detailed Description
Definition at line 21 of file meshdialog.h.
Member Enumeration Documentation
enum MeshDialog::ColumnNames private
Enumerator
ChangedColumn
BndNameColumn
BndTypeColumn
HelpIconColumn
CurrentValueColumn
EditIconColum
Definition at line 76 of file meshdialog.h.
                     {
         ChangedColumn=0,
         BndNameColumn = 1,
         BndTypeColumn = 2,
         HelpIconColumn = 3,
         CurrentValueColumn = 4,
         EditIconColum = 5
     };
Constructor & Destructor Documentation
MeshDialog::MeshDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 37 of file meshdialog.cpp.
References _isMultizoneProject, _isNSProblem, _markerManager, _needToSave, _signalMapper, _signalMapperCheckList, _userAcceptChanges, loadTableHeader(), and ui.
                                       :
     QDialog(parent),
     ui(new Ui::MeshDialog)
 {
     ui->setupUi(this);
     _signalMapper = new QSignalMapper(this);
     _signalMapperCheckList = new QSignalMapper(this);
     loadTableHeader();
     _markerManager = new MarkerMenuManager();
     _needToSave = false;
     _isNSProblem = false;
     _isMultizoneProject = false;
     _userAcceptChanges = false;
 }
MeshDialog::~MeshDialog ()
Destructor.
Definition at line 57 of file meshdialog.cpp.
References _markerManager, and ui.
 {
     delete _markerManager;
     delete ui;
 }
Member Function Documentation
void MeshDialog::addSignals () private
Function to add signals.
Definition at line 846 of file meshdialog.cpp.
References _signalMapper, _signalMapperCheckList, changedComboValueByUser(), ColumnSelVal, handleItem(), and ui.
Referenced by fillTable().
 {
     bool _foundCombos = false;
     bool _foundCheckList = false;
     if (ui->meshTableWidget->rowCount() > 0)
     {
         for (int i = 0; i< ui->meshTableWidget->rowCount();i++)
         {
                 QWidget * _item;
                 _item = ui->meshTableWidget->cellWidget(i,ColumnSelVal);
                 if (_item)
                 {
                     QComboBox *_comboItem = qobject_cast<QComboBox *> (_item);
                     if (_comboItem)
                     {
                         connect(_comboItem, SIGNAL(currentIndexChanged(int)), _signalMapper, SLOT(map()),Qt::UniqueConnection);
                        _signalMapper->setMapping(_comboItem, QString("%1-%2").arg(i).arg(ColumnSelVal));
                         _foundCombos = true;
                     }else
                     {
                         QListWidget * _checkList = qobject_cast<QListWidget *> (_item);
                         if (_checkList)
{
                             connect(_checkList,SIGNAL(itemClicked(QListWidgetItem*)),_signalMapperCheckList,SLOT(map()),Qt::UniqueConnection);
                            _signalMapperCheckList->setMapping(_checkList,QString("%1").arg(i));
                            _foundCheckList = true;
                         }
                     }
                 }
         }
     }
     if (_foundCombos)
         connect(_signalMapper, SIGNAL(mapped(const QString &)),this, SLOT(changedComboValueByUser(const QString &)),Qt::UniqueConnection);
     if (_foundCheckList)
         connect(_signalMapperCheckList, SIGNAL(mapped(const QString &)),this, SLOT(handleItem(const QString &)),Qt::UniqueConnection);
 }
void MeshDialog::buildAllToolTips () private
Function to build up all the tooltips.
Definition at line 1098 of file meshdialog.cpp.
References BndNameColumn, BndTypeColumn, and ui.
Referenced by fillTable().
 {
     for (int i = 0; i < ui->meshTableWidget->rowCount(); i++)
     {
         ui->meshTableWidget->item(i,BndNameColumn)->setToolTip("Mesh Variable Name found in the Mesh file");
         ui->meshTableWidget->item(i,BndTypeColumn)->setToolTip("Select the most suitable option for the corresponding mesh variable");
     }
 }
QString MeshDialog::buildHelpContent (int row) private
Function to build up the help content.
Parameters
row
Returns
QString
Definition at line 1115 of file meshdialog.cpp.
References _selectedSubMenu, _solverManager, ColumnSelVal, SolverConfigMenuHelper::getAssociatedHelpText(), SolverVariableVO::getHelpContents(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), HTML_FORMAT_ON, MARKER_CHILD_TITLE, StrEqual, and ui.
Referenced by launchSpecificBoundaryConfigWindow(), and on_meshTableWidget_cellClicked().
 {
     QString _variableName;
     int _pos = 0;
     SolverSectionVO _sectionVO;
      _sectionVO=  _solverManager->getVariableListofSubsections(_selectedSubMenu);
        if (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual)
     {
         QComboBox * _combo =  qobject_cast<QComboBox* >(ui->meshTableWidget->cellWidget(row,ColumnSelVal));
         if (_combo)
         {
             _variableName = _combo->currentText();
         }
         if (!_variableName.isEmpty())
         {
             SolverConfigMenuHelper _uiHelper;
             return _uiHelper.getAssociatedHelpText(_variableName,_sectionVO.getSubsectionVarList(),HTML_FORMAT_ON);
         }
     }
     QList<SolverVariableVO> _list  = _sectionVO.getSubsectionVarList();
     if (!_list.isEmpty())
     {
         SolverVariableVO _solverVarVO =  _list.at(_pos);
         return _solverVarVO.getHelpContents(HTML_FORMAT_ON);
     }
     return QString("");
 }
void MeshDialog::buildUserBndValueMap () private
Definition at line 107 of file meshdialog.cpp.
References _userBndVariableValues, _userMeshVariablesList, COMMA_SEPARATOR, UserMeshVO::getBoundaryAssociatedValues(), UserMeshVO::getBoundaryNameList(), UserMeshVO::getFilename(), UserMeshVO::getParentMenu(), MARKER_MONITORING_TITLE, MARKER_PLOTTING_TITLE, and removeEmptyStrings().
Referenced by on_meshButtonBox_accepted().
 {
     for (int i = 0; i<_userMeshVariablesList.size();i++)
     {
         bool _printAssociatedVal = true;
         UserMeshVO _meshVar = _userMeshVariablesList.at(i);
         QString _keyName = _meshVar.getFilename();
         QString _valuesToSave;
         QString _parentMenu = _meshVar.getParentMenu();
         if ((_parentMenu.contains(MARKER_PLOTTING_TITLE)) || (_parentMenu.contains(MARKER_MONITORING_TITLE))
                 || (_keyName.contains("MULTIZONE")))
                 _printAssociatedVal = false;
         QStringList _bndList = _meshVar.getBoundaryNameList();
         QStringList _bndValues = _meshVar.getBoundaryAssociatedValues();
         // Remove empty QString
         _bndList = removeEmptyStrings(_bndList);
         _bndValues = removeEmptyStrings(_bndValues);
         if (_bndList.isEmpty())
             _valuesToSave = "NONE";
         else
         {
             if (_bndValues.isEmpty())
                 _valuesToSave = _bndList.join(COMMA_SEPARATOR);
             else
             {
                 QStringList _tmpList;
                 for (int j=0; j<_bndList.size();j++)
                 {
                     _tmpList.append(_bndList.at(j));
                     if ( (_printAssociatedVal) && (j < _bndValues.size()))
                         _tmpList.append(_bndValues.at(j));
                 }
                 _tmpList.removeAll("NONE");
                 _valuesToSave = _tmpList.join(COMMA_SEPARATOR);
             }
         }
         _userBndVariableValues.insert(_keyName,_valuesToSave);
     }
 }
void MeshDialog::changedComboValueByUser (QString position) private slot
Slot that controls the change of the combo value by the user.
Parameters
position
Definition at line 710 of file meshdialog.cpp.
References _isLoadingTable, _isNSProblem, _needToSave, _selectedSubMenu, ColumnCheck, launchSpecificBoundaryConfigWindow(), MARKER_CHILD_TITLE, needToOpenSpecificConfigWindow(), saveUserChanges(), showValuesInValueCol(), StrEqual, and ui.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
         QStringList coordinates = position.split("-");
         int row = coordinates[0].toInt();
         int col = coordinates[1].toInt();
         QComboBox* combo = (QComboBox*) ui->meshTableWidget->cellWidget(row, col);
         ui->meshTableWidget->item(row,ColumnCheck)->setCheckState(Qt::Checked);
         QString _value = combo->currentText();
         if (!needToOpenSpecificConfigWindow(_value))
         {
             if ((QString::compare(_value,"Wall") == StrEqual) && (_isNSProblem))
                   launchSpecificBoundaryConfigWindow(row,_value,combo);
             else
             {
                 saveUserChanges(_value,row);
                 if (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual)
                      showValuesInValueCol(row,"");
             }
             _needToSave = true;
         }else
             launchSpecificBoundaryConfigWindow(row,_value,combo);
     }
     }
bool MeshDialog::checkIfAllBoundaryNames (QStringList _list) private
Definition at line 301 of file meshdialog.cpp.
References _meshValues.
Referenced by createMeshVariables().
 {
     for (int i = 0; i< _list.size();i++)
     {
         QString _item = _list.at(i);
         QString _keyVal = _meshValues.key(_item);
         bool _isBnd = _meshValues.contains(_keyVal);
         //QString
         if (!_isBnd)
             return false;
     }
     return true;
 }
void MeshDialog::createMeshVariables (QString _menu, QList< SolverVariableVO > _varList) private
Definition at line 189 of file meshdialog.cpp.
References _configUserMeshValues, _userMeshVariablesList, checkIfAllBoundaryNames(), COMMA_SEPARATOR, SolverVariableVO::getAssociatedVariables(), SolverVariableVO::getVariableFileName(), SolverVariableVO::getVariableName(), MARKER_MONITORING_TITLE, MARKER_PLOTTING_TITLE, SEMICOLON_SEPARATOR, UserMeshVO::setAssociatedMeshVariables(), UserMeshVO::setBoundaryAssociatedValues(), UserMeshVO::setBoundaryNameList(), UserMeshVO::setFilename(), UserMeshVO::setHasAssociatedMeshVariables(), UserMeshVO::setParentMenu(), UserMeshVO::setUserName(), and splitBndNameAndValues().
Referenced by initializeMeshValues().
 {
     for (int i = 0; i < _varList.size(); i++)
     {
         SolverVariableVO _element = _varList.at(i);
         QString _key = _element.getVariableFileName();//BC_WALL
         QString _userKeyName = _element.getVariableName(); //Wall
         UserMeshVO _meshVO;
         _meshVO.setUserName(_userKeyName);
         _meshVO.setFilename(_key);
         _meshVO.setParentMenu(_menu);
         // Checking if it has associated Variables
         QStringList _associatedVariables = _element.getAssociatedVariables();
        if( (!_associatedVariables.isEmpty()) && (_associatedVariables.size() > 0) )
         {
             _meshVO.setHasAssociatedMeshVariables(true);
             QStringList _keyNameAssociatedMeshVariable = _element.getAssociatedVariables();
             _meshVO.setAssociatedMeshVariables(_keyNameAssociatedMeshVariable);
         }
         // Initialize with the user values
         if (!_configUserMeshValues.empty())
         {
             QStringList _value = _configUserMeshValues.value(_key).split(COMMA_SEPARATOR);
             bool _allBndNames = checkIfAllBoundaryNames(_value);
             if ((!_value.isEmpty()) && (!_allBndNames))
             {
                 QStringList _boundValList = splitBndNameAndValues(_value);
                 if( (!_boundValList.isEmpty()) && (_boundValList.size() == 2))
                 {
                     _meshVO.setBoundaryNameList(_boundValList.at(0).split(COMMA_SEPARATOR));
                     _meshVO.setBoundaryAssociatedValues(_boundValList.at(1).split(SEMICOLON_SEPARATOR));
                 }
             }else
             {
                 // In this case is purely a set of Boundary Names
                 _meshVO.setBoundaryNameList(_value);
                 if ((_menu.contains(MARKER_PLOTTING_TITLE)) || (_menu.contains(MARKER_MONITORING_TITLE)) ||
                    (_key.contains("MULTIZONE")) )
                 {
                     QStringList _yesValues;
                     for (int j=0;j< _value.size();j++)
                         _yesValues.append("YES");
                     _meshVO.setBoundaryAssociatedValues(_yesValues);
                 }
             }
         }
         _userMeshVariablesList.append(_meshVO);
     }
 }
void MeshDialog::fillTable (QString _parent) private
Function that fills the table according user clicks.
Parameters
_parent
Definition at line 424 of file meshdialog.cpp.
References _meshValues, _selectedSubMenu, _solverManager, _userMeshVariablesList, SolverMarkerMenuHelper::addExtraColumn(), addSignals(), buildAllToolTips(), CurrentValueColumn, EditIconColum, SolverMarkerMenuHelper::fillMarkerMenuTable(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), MARKER_CHILD_TITLE, MARKER_MULTIZONE_TITLE, removeNonVisibleVariables(), StrEqual, ui, and updateTableWithUserValues().
Referenced by on_meshTreeView_clicked().
 {
    // ui->meshTableWidget->blockSignals(true);
     if (QString::compare(_parent,"") != StrEqual)
     {
         SolverSectionVO _sectionVO;
         SolverMarkerMenuHelper _markerHelper;
         _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
         QList<SolverVariableVO> _listVariables = _sectionVO.getSubsectionVarList();
         // Removing the non visible variables
         _listVariables = removeNonVisibleVariables(_listVariables);
         _markerHelper.fillMarkerMenuTable(_selectedSubMenu,_meshValues,ui->meshTableWidget,_listVariables);
         if (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual)
         {
             _markerHelper.addExtraColumn(ui->meshTableWidget,CurrentValueColumn,"");
             _markerHelper.addExtraColumn(ui->meshTableWidget,EditIconColum,"");
         }
         addSignals();
        if (!_userMeshVariablesList.isEmpty())
            updateTableWithUserValues();
         if (QString::compare(_selectedSubMenu,MARKER_MULTIZONE_TITLE) != StrEqual)
             buildAllToolTips(); // FALLA CON EL MULTIZONE MIRAR PORQUE
     }
 }
int MeshDialog::findMeshVariableToUpdate (QString _nameToFind, QString _menu) private
Definition at line 667 of file meshdialog.cpp.
References _userMeshVariablesList, UserMeshVO::getParentMenu(), UserMeshVO::getUserName(), and StrEqual.
Referenced by initBndNamesInAssociatedMeshVar(), removeBoundaryNamesInAssociatedVariables(), saveUserChanges(), and updateTableWithUserValues().
 {
     for (int i = 0; i < _userMeshVariablesList.size();i++)
     {
         UserMeshVO _cMeshVariable = _userMeshVariablesList.at(i);
         if (_cMeshVariable.getParentMenu().contains(_menu))
             if (QString::compare(_cMeshVariable.getUserName(),_nameToFind) == StrEqual)
                  return i;
     }
     return -1;
  }
int MeshDialog::findMeshVariableToUpdateByBndValue (QString _bndToFind, QString _menu) private
Definition at line 692 of file meshdialog.cpp.
References _userMeshVariablesList, UserMeshVO::containsBoundary(), and UserMeshVO::getParentMenu().
Referenced by saveUserChanges().
 {
     for (int i = 0; i < _userMeshVariablesList.size();i++)
     {
         UserMeshVO _cMeshVariable = _userMeshVariablesList.at(i);
         if (_cMeshVariable.getParentMenu().contains(_menu))
             if (_cMeshVariable.containsBoundary(_bndToFind))
                  return i;
     }
     return -1;
 }
int MeshDialog::findMeshVariableToUpdateByFileNameVar (QString _nameToFind, QString _menu) private
Definition at line 680 of file meshdialog.cpp.
References _userMeshVariablesList, UserMeshVO::getFilename(), UserMeshVO::getParentMenu(), and StrEqual.
Referenced by saveUserChanges().
 {
     for (int i = 0; i < _userMeshVariablesList.size();i++)
     {
         UserMeshVO _cMeshVariable = _userMeshVariablesList.at(i);
         if (_cMeshVariable.getParentMenu().contains(_menu))
             if (QString::compare(_cMeshVariable.getFilename(),_nameToFind) == StrEqual)
                  return i;
     }
     return -1;
 }
QString MeshDialog::getBndTypeName () private
Definition at line 585 of file meshdialog.cpp.
References _selectedSubMenu.
Referenced by saveUserChanges().
 {
     QString _result;
     if (_selectedSubMenu.contains("Monitoring"))
         _result = "MARKER_MONITORING";
     if (_selectedSubMenu.contains("Plotting"))
         _result = "MARKER_PLOTTING";
     if (_selectedSubMenu.contains("Multizone"))
         _result = "BC_MULTIZONE_INTERFACE";
     return _result;
 }
int MeshDialog::getBoundaryRow (QString _boundaryName) private
Returns the row where the boundary is placed.
Parameters
_boundaryName
Returns
int
Definition at line 976 of file meshdialog.cpp.
References BndNameColumn, StrEqual, and ui.
 {
     int _result = -1;
     for (int _row = 0; _row < ui->meshTableWidget->rowCount();_row++)
     {
         QString _varName = ui->meshTableWidget->item(_row,BndNameColumn)->text();
         if (QString::compare(_varName,_boundaryName) == StrEqual)
             return _row;
     }
     return _result;
 }
QHash< QString, QString > MeshDialog::getMeshValues ()
Returns the mesh values.
Returns
QHash<QString, QString>
Definition at line 955 of file meshdialog.cpp.
References _meshValues.
 {
     return _meshValues;
 }
QHash< QString, QString > MeshDialog::getUserBndVariableValues ()
Definition at line 1155 of file meshdialog.cpp.
References _userBndVariableValues.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     return _userBndVariableValues;
 }
QHash< QString, QString > MeshDialog::getUserConfiguredMeshValues ()
Returns user configured mesh values.
Returns
QHash<QString, QString>
Definition at line 1030 of file meshdialog.cpp.
References _configUserMeshValues.
 {
     return _configUserMeshValues;
 }
void MeshDialog::handleItem (QString position) private slot
Definition at line 886 of file meshdialog.cpp.
Referenced by addSignals().
 {
    /* if (!_isLoadingTable)
     {
         int row = position.toInt();
          QListWidget * _checkList = qobject_cast<QListWidget *> (ui->solverVariablesTable->cellWidget(row,ColumnSelVal));
          if (!_checkList)
              return;
          // Recovering the previous value of the user
          QString _rowVariableName = ui->solverVariablesTable->item(row,ColumnVarName)->text();
          QStringList _valueList;
          for (int i = 0; i < _checkList->count();i++)
          {
              QListWidgetItem * _item = _checkList->item(i);
              if (_item->checkState() == Qt::Checked)
                  _valueList.append(_item->text());
          }
          QString _value = _valueList.join(",");
          ui->solverVariablesTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
          saveUserChanges(_value,row);
     }*/
 }
bool MeshDialog::hasUserAcceptChanges ()
Definition at line 1159 of file meshdialog.cpp.
References _userAcceptChanges.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     return _userAcceptChanges;
 }
void MeshDialog::initBndNamesInAssociatedMeshVar () private
Definition at line 266 of file meshdialog.cpp.
References _userMeshVariablesList, findMeshVariableToUpdate(), UserMeshVO::getAssociatedMeshVariables(), UserMeshVO::getBoundaryAssociatedValues(), UserMeshVO::getBoundaryNameList(), UserMeshVO::hasAssociatedMeshVariables(), isAllowedTheAssociatedMeshVariables(), MARKER_CHILD_TITLE, UserMeshVO::setBoundaryAssociatedValues(), and UserMeshVO::setBoundaryNameList().
Referenced by initializeMeshValues().
 {
     for (int i = 0; i < _userMeshVariablesList.size();i++)
     {
         UserMeshVO _userMeshVO =_userMeshVariablesList.at(i);
         if(_userMeshVO.hasAssociatedMeshVariables())
         {
             bool _removeAssociatedValues = false;
             if (!isAllowedTheAssociatedMeshVariables(_userMeshVO.getAssociatedMeshVariables().at(0)))
                 _removeAssociatedValues = true;
             QStringList  _bndList = _userMeshVO.getBoundaryNameList();
             if (!_bndList.isEmpty())
             {
                 int _pos = findMeshVariableToUpdate(_userMeshVO.getAssociatedMeshVariables().at(0),MARKER_CHILD_TITLE);
                 if (_pos != -1)
                 {
                     UserMeshVO _assocMeshVO = _userMeshVariablesList.at(_pos);
                     if (!_removeAssociatedValues)
                     {
                         QString _listVal = _assocMeshVO.getBoundaryAssociatedValues().join(",");
                         _assocMeshVO.setBoundaryAssociatedValues(_listVal.split(","));
                         _assocMeshVO.setBoundaryNameList(_userMeshVO.getBoundaryNameList());
                     }else
                     {
                         QStringList _emptyList;
                         _assocMeshVO.setBoundaryAssociatedValues(_emptyList);
                     }
                     _userMeshVariablesList.replace(_pos,_assocMeshVO);
                 }
             }
          }
     }
 }
void MeshDialog::initializeMeshValues () private
Definition at line 246 of file meshdialog.cpp.
References _isMultizoneProject, _solverManager, createMeshVariables(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), initBndNamesInAssociatedMeshVar(), MARKER_CHILD_TITLE, MARKER_MONITORING_TITLE, MARKER_MULTIZONE_TITLE, and MARKER_PLOTTING_TITLE.
Referenced by loadMenu().
 {
      SolverSectionVO _sectionVO;
     // Building the complete list of Variables for the whole Boundary Menu
     _sectionVO =  _solverManager->getVariableListofSubsections(MARKER_CHILD_TITLE);
     createMeshVariables(MARKER_CHILD_TITLE,_sectionVO.getSubsectionVarList());
     _sectionVO =  _solverManager->getVariableListofSubsections(MARKER_PLOTTING_TITLE);
      createMeshVariables(MARKER_PLOTTING_TITLE,_sectionVO.getSubsectionVarList());
     _sectionVO =  _solverManager->getVariableListofSubsections(MARKER_MONITORING_TITLE);
      createMeshVariables(MARKER_MONITORING_TITLE,_sectionVO.getSubsectionVarList());
     if (_isMultizoneProject)
     {
         _sectionVO =  _solverManager->getVariableListofSubsections(MARKER_MULTIZONE_TITLE);
          createMeshVariables(MARKER_MULTIZONE_TITLE,_sectionVO.getSubsectionVarList());
     }
     initBndNamesInAssociatedMeshVar();
 }
bool MeshDialog::isAllowedTheAssociatedMeshVariables (QString _variableName) private
Definition at line 494 of file meshdialog.cpp.
References _isNSProblem, and StrEqual.
Referenced by initBndNamesInAssociatedMeshVar(), saveUserChanges(), and updateTableWithUserValues().
 {
     if( (QString::compare(_variableName,"Wall") == StrEqual) && (_isNSProblem))
         return true;
     return false;
 }
bool MeshDialog::isSpecialBoundary (QString _keyVariable) private
Returns if it is a special boundary.
Parameters
_keyVariable
Returns
bool
Definition at line 996 of file meshdialog.cpp.
References BC_FARFIELD_NAME, MARKER_INLET_NAME, MARKER_OUTLET_NAME, MARKER_PERIODIC_NAME, MARKER_ROTB_NAME, and StrEqual.
 {
     if (QString::compare(_keyVariable,MARKER_ROTB_NAME) == StrEqual)
         return true;
     if (QString::compare(_keyVariable,MARKER_INLET_NAME) == StrEqual)
         return true;
     if (QString::compare(_keyVariable,MARKER_OUTLET_NAME) == StrEqual)
         return true;
     if (QString::compare(_keyVariable,MARKER_PERIODIC_NAME)  == StrEqual)
         return true;
     if (QString::compare(_keyVariable,BC_FARFIELD_NAME)  == StrEqual)
         return true;
      return false;
 }
void MeshDialog::launchSpecificBoundaryConfigWindow (int row, QString _value, QComboBox * _combo) private
Function to launch the Specific Boundary config window.
Parameters
row
_value
_combo
Definition at line 750 of file meshdialog.cpp.
References _markerManager, _meshValues, _needToSave, _storedSpecificBoundValues, BndNameColumn, buildHelpContent(), COMMA_SEPARATOR, CurrentValueColumn, SpecificBoundaryVariableDialog::getConfiguredBoundary(), SpecificBoundaryVariableDialog::loadValues(), restoreValues(), saveUserChanges(), SpecificBoundaryVariableDialog::setBoundaryName(), SpecificBoundaryVariableDialog::setBoundaryType(), SpecificBoundaryVariableDialog::setCurrentValues(), SpecificBoundaryVariableDialog::setHelpContent(), SpecificBoundaryVariableDialog::setMarkerMenuManager(), SpecificBoundaryVariableDialog::setMeshVariables(), SpecificBoundaryVariableDialog::setStoredUserConfigValues(), showValuesInValueCol(), ui, and SpecificBoundaryVariableDialog::userAcceptChanges().
Referenced by changedComboValueByUser(), and on_meshTableWidget_cellClicked().
 {
     SpecificBoundaryVariableDialog * _boundaryDialog = new SpecificBoundaryVariableDialog(this);
     _boundaryDialog->setHelpContent(buildHelpContent(row));
     QStringList _cValues = ui->meshTableWidget->item(row,CurrentValueColumn)->text().split(",");
     QString _bndName = ui->meshTableWidget->item(row,BndNameColumn)->text();
     _boundaryDialog->setBoundaryName(_bndName);
     _boundaryDialog->setCurrentValues(_cValues);
     _boundaryDialog->setMarkerMenuManager(_markerManager);
     _boundaryDialog->setMeshVariables(_meshValues);
     _boundaryDialog->setBoundaryType(_value);
     _boundaryDialog->setStoredUserConfigValues(_storedSpecificBoundValues);
     _boundaryDialog->loadValues();
     _boundaryDialog->exec();
     if (_boundaryDialog->userAcceptChanges())
     {
        QString _keyname = _combo->currentText();
         QStringList  _result =_boundaryDialog->getConfiguredBoundary();
         QString _value = _result.join(COMMA_SEPARATOR);
          showValuesInValueCol(row,_value);
         saveUserChanges(_keyname,row);
         _needToSave = true;
     }else
        restoreValues(row);
 }
void MeshDialog::loadMenu ()
Function that loads the main menu elements.
Definition at line 169 of file meshdialog.cpp.
References _isMultizoneProject, _solverManager, SolverConfigManager::getBoundaryMenuList(), SolverConfigManager::getBoundaryMenuListWithoutMultizoneChildren(), SolverConfigManager::initializeManager(), initializeMeshValues(), SolverConfigManager::isInitialized(), and ui.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     DomModel * _model;
     if (!_solverManager->isInitialized())
         _solverManager->initializeManager();
     if (_isMultizoneProject)
         _model = new DomModel(*_solverManager->getBoundaryMenuList(),this);
     else
         _model = new DomModel(*_solverManager->getBoundaryMenuListWithoutMultizoneChildren(),this);
     // Setting and showing the model tree
     ui->meshTreeView->setModel(_model);
     ui->meshTreeView->hideColumn(1);
     ui->meshTreeView->hideColumn(2);
     ui->meshTreeView->show();
     // Creating the new list of objects containing the essential information of the mesh list
     initializeMeshValues();
 }
void MeshDialog::loadTableHeader () private
Function that loads the table Header.
Definition at line 363 of file meshdialog.cpp.
References _selectedSubMenu, MARKER_CHILD_TITLE, MARKER_TITLE, StrEqual, and ui.
Referenced by MeshDialog(), and on_meshTreeView_clicked().
 {
     if (_selectedSubMenu.isEmpty())
         return;
     ui->meshTableWidget->setColumnCount(4);
     if( (!_selectedSubMenu.isEmpty()) &&
             ( (QString::compare(_selectedSubMenu,MARKER_TITLE) == StrEqual) ||
             (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual ) ) )
     {
         ui->meshTableWidget->setColumnCount(6);
         ui->meshTableWidget->setHorizontalHeaderLabels( QString("Changed;Boundary Name;Boundary Type;Help;Current Value;Edit").split(";"));
     }
     else
         ui->meshTableWidget->setHorizontalHeaderLabels( QString("Changed;Boundary Name;Select?;Help").split(";"));
     ui->meshTableWidget->horizontalHeader()->setVisible(true);
 }
bool MeshDialog::needToOpenSpecificConfigWindow (QString _varName) private
Function that checks if it is needed to open the Specific boundary dialog.
Parameters
_varName
Returns
bool
Definition at line 918 of file meshdialog.cpp.
References _selectedSubMenu, _solverManager, SolverSectionDAO::findValueNameByVariableName(), SolverConfigManager::getVariableListofSubsections(), MARKER_CHILD_TITLE, MARKER_INLET_NAME, MARKER_OUTLET_NAME, MARKER_PERIODIC_NAME, and StrEqual.
Referenced by changedComboValueByUser(), and on_meshTableWidget_cellClicked().
 {
     QString _valueName;
     SolverSectionDAO _solverDAO;
     if (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual)
     {
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(MARKER_CHILD_TITLE);
         _valueName = _solverDAO.findValueNameByVariableName(_sectionVO,_varName);
     }
     if (
          (QString::compare(_valueName,MARKER_PERIODIC_NAME) == StrEqual) ||
          (QString::compare(_valueName,MARKER_INLET_NAME) == StrEqual) ||
          (QString::compare(_valueName,MARKER_OUTLET_NAME) == StrEqual) ||
          (QString::compare(_valueName,"BC_FARFIELD") == StrEqual)
          )
         return true;
     return false;
 }
bool MeshDialog::needToSave ()
Returns true if the status is needed to be saved.
Returns
bool
Definition at line 1054 of file meshdialog.cpp.
References _needToSave.
 {
     return _needToSave;
 }
void MeshDialog::on_meshButtonBox_accepted () private slot
Function that performs the functinality when the user clicks accept button.
Definition at line 67 of file meshdialog.cpp.
References _userAcceptChanges, buildUserBndValueMap(), and removeBoundaryNamesInAssociatedVariables().
 {
     buildUserBndValueMap();
     removeBoundaryNamesInAssociatedVariables();
     _userAcceptChanges = true;
     close();
 }
void MeshDialog::on_meshButtonBox_rejected () private slot
Fucntion that perfomrs the functionality for cancel click button.
Definition at line 1042 of file meshdialog.cpp.
References _configUserMeshValues, and _needToSave.
 {
     _configUserMeshValues.clear();
     _needToSave = false;
     close();
 }
void MeshDialog::on_meshTableWidget_cellClicked (int row, int column) private slot
Function to perform actions when a cell is clicked.
Parameters
row
column
Definition at line 1065 of file meshdialog.cpp.
References _isNSProblem, buildHelpContent(), ColumnSelVal, launchSpecificBoundaryConfigWindow(), HelpDialog::loadHelpText(), MarkerColumnHelp, needToOpenSpecificConfigWindow(), HelpDialog::setHelpText(), StrEqual, and ui.
 {
     if(column == MarkerColumnHelp)
     {
        HelpDialog *  _helpDialog = new HelpDialog();
        QString _helpText = buildHelpContent(row);
         _helpDialog->setHelpText(_helpText);
         _helpDialog->loadHelpText();
         _helpDialog->exec();
         delete _helpDialog;
     }
     else
     {
         if (column == 5)
         {
             QComboBox * _combo = qobject_cast<QComboBox * > (ui->meshTableWidget->cellWidget(row,ColumnSelVal));
             QString _value = _combo->currentText();
             if (needToOpenSpecificConfigWindow(_value))
             {
                 launchSpecificBoundaryConfigWindow(row,_value,_combo);
             }else
                 if ((QString::compare(_value,"Wall") == StrEqual) && (_isNSProblem))
                     launchSpecificBoundaryConfigWindow(row,_value,_combo);
         }
     }
 }
void MeshDialog::on_meshTreeView_clicked (const QModelIndex & index) private slot
Function that performs the functionality when the user click on a element of the tree view.
Parameters
index
Definition at line 543 of file meshdialog.cpp.
References _isLoadingTable, _selectedSubMenu, fillTable(), loadTableHeader(), resetTable(), and ui.
 {
    QVariant _data = index.data(Qt::DisplayRole);
    _selectedSubMenu = _data.toString();
    _isLoadingTable = true;
    QString _parent = index.parent().data(Qt::DisplayRole).toString();
    resetTable();
    loadTableHeader();
    fillTable(_parent);
    _isLoadingTable = false;
    ui->meshTableWidget->resizeColumnsToContents();
    ui->meshTableWidget->show();
 }
void MeshDialog::removeBoundaryNamesInAssociatedVariables () private
Definition at line 75 of file meshdialog.cpp.
References _userBndVariableValues, _userMeshVariablesList, COMMA_SEPARATOR, findMeshVariableToUpdate(), UserMeshVO::getAssociatedMeshVariables(), UserMeshVO::getBoundaryNameList(), UserMeshVO::getFilename(), UserMeshVO::hasAssociatedMeshVariables(), and MARKER_CHILD_TITLE.
Referenced by on_meshButtonBox_accepted().
 {
     QStringList _associatedVariables;
     for (int i = 0; i<_userMeshVariablesList.size();i++)
     {
         UserMeshVO _meshVar = _userMeshVariablesList.at(i);
         if (_meshVar.hasAssociatedMeshVariables())
             _associatedVariables.append(_meshVar.getAssociatedMeshVariables());
     }
     if (_associatedVariables.isEmpty())
         return;
     for (int j = 0; j< _associatedVariables.size();j++)
     {
         int _pos = findMeshVariableToUpdate(_associatedVariables.at(j),MARKER_CHILD_TITLE);
         if (_pos != -1)
         {
             UserMeshVO _associatedMeshVar =_userMeshVariablesList.at(_pos);
             QStringList _bndNamesToRemove = _associatedMeshVar.getBoundaryNameList();
             QString _keyName = _associatedMeshVar.getFilename();
             QStringList _storedValue =_userBndVariableValues.value(_keyName).split(COMMA_SEPARATOR);
             for (int k=0;k<_bndNamesToRemove.size();k++)
             {
                 QString _bndName = _bndNamesToRemove.at(k);
                 if (!_bndName.isEmpty())
                     _storedValue.removeAll(_bndName);
             }
            _userBndVariableValues.insert(_keyName,_storedValue.join(COMMA_SEPARATOR));
         }
     }
 }
QStringList MeshDialog::removeEmptyStrings (QStringList _list) private
Definition at line 149 of file meshdialog.cpp.
Referenced by buildUserBndValueMap().
 {
     QStringList _result;
     for (int i =0; i< _list.size();i++)
     {
         QString _val = _list.at(i);
         _val.simplified();
         _val.replace(" ","");
         if ( (!_val.isEmpty()) && (!_val.isNull()))
             _result.append(_val);
     }
     return _result;
 }
QList< SolverVariableVO > MeshDialog::removeNonVisibleVariables (QList< SolverVariableVO > _list) private
Definition at line 400 of file meshdialog.cpp.
References SolverVariableVO::isVisibleInMenu().
Referenced by fillTable().
 {
     QList<int> _positionsToRemove;
     for (int i = 0; i< _list.size();i++)
     {
         SolverVariableVO _var = _list.at(i);
         if (!_var.isVisibleInMenu())
             _positionsToRemove.append(i);
     }
     if (!_positionsToRemove.isEmpty())
     {
         int _totalPosToRemove = _positionsToRemove.size();
         for (int j=_totalPosToRemove-1; j>= 0;j--)
             _list.removeAt(_positionsToRemove.at(j));
     }
     return _list;
 }
void MeshDialog::resetTable () private
Function that resets the table contents.
Definition at line 388 of file meshdialog.cpp.
References ui.
Referenced by on_meshTreeView_clicked().
 {
     if (ui->meshTableWidget->rowCount() > 0)
     {
         //  Delete all rows
         int _totalRows = ui->meshTableWidget->rowCount();
         for (int i = _totalRows; i >= 0; i--)
             ui->meshTableWidget->removeRow(i);
     }
 }
void MeshDialog::restoreValues (int row) private
Function to restore the values in the row.
Parameters
row
Definition at line 784 of file meshdialog.cpp.
References _previousUserMeshValues, _selectedSubMenu, _solverManager, ColumnSelVal, ColumnVarName, COMMA_SEPARATOR, SolverSectionDAO::findVariableByFileName(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), SolverVariableVO::getVariableName(), MARKER_CHILD_TITLE, StrEqual, and ui.
Referenced by launchSpecificBoundaryConfigWindow().
 {
     if (QString::compare(_selectedSubMenu,MARKER_CHILD_TITLE) == StrEqual)
     {
         QComboBox * _combo = qobject_cast<QComboBox * > ( ui->meshTableWidget->cellWidget(row,ColumnSelVal) );
         if (_combo)
         {
             QString _key =  ui->meshTableWidget->item(row,ColumnVarName)->text();
             QStringList _prevValList = _previousUserMeshValues.value(_key).split(COMMA_SEPARATOR);
             if (!_prevValList.isEmpty())
             {
                 QString _prevValue = _prevValList.at(0);
                 SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
                 QList<SolverVariableVO> _list = _sectionVO.getSubsectionVarList();
                 SolverSectionDAO _solverDAO ;
                 SolverVariableVO _prevVar = _solverDAO.findVariableByFileName(_list, _prevValue);
                 int _index = _combo->findText(_prevVar.getVariableName());
                 if (_index != -1)
                     _combo->setCurrentIndex(_index);
             }
         }
     }
 }
void MeshDialog::saveUserChanges (QString _value, int _itemRow) private
Function to save the user changes.
Parameters
_value
_itemRow
Definition at line 608 of file meshdialog.cpp.
References _selectedSubMenu, _userMeshVariablesList, UserMeshVO::addBoundary(), BndNameColumn, CurrentValueColumn, UserMeshVO::deleteBoundary(), findMeshVariableToUpdate(), findMeshVariableToUpdateByBndValue(), findMeshVariableToUpdateByFileNameVar(), UserMeshVO::getAssociatedMeshVariables(), getBndTypeName(), UserMeshVO::getBoundaryAssociatedValues(), UserMeshVO::getBoundaryNameList(), UserMeshVO::getUserName(), UserMeshVO::hasAssociatedMeshVariables(), UserMeshVO::initializeBndAssociatedValuesToDefault(), isAllowedTheAssociatedMeshVariables(), MARKER_CHILD_TITLE, UserMeshVO::setBoundaryNameList(), and ui.
Referenced by changedComboValueByUser(), and launchSpecificBoundaryConfigWindow().
 {
     UserMeshVO _meshToUpdate;
     QString _bndNameInRow = ui->meshTableWidget->item(_itemRow,BndNameColumn)->text();
     QString _bndTypeInRow = _value;
     int _posToRemove = findMeshVariableToUpdateByBndValue(_bndNameInRow,_selectedSubMenu);
     int _posToUpdate;
     if (_selectedSubMenu.contains(MARKER_CHILD_TITLE))
         _posToUpdate = findMeshVariableToUpdate(_bndTypeInRow,_selectedSubMenu);
     else
         _posToUpdate = findMeshVariableToUpdateByFileNameVar(getBndTypeName(),_selectedSubMenu);
     if (_posToRemove!=-1)
     {
         _meshToUpdate = _userMeshVariablesList.at(_posToRemove);
         _meshToUpdate.deleteBoundary(_bndNameInRow);
         _userMeshVariablesList.replace(_posToRemove,_meshToUpdate);
     }
     if (_posToUpdate != -1)
     {
         QString _bndVal;
         if (ui->meshTableWidget->columnCount() == 6)
             _bndVal = ui->meshTableWidget->item(_itemRow,CurrentValueColumn)->text();
         else
             _bndVal = _value; // TBR
         // Update the main MeshVariable
         _meshToUpdate = _userMeshVariablesList.at(_posToUpdate);
         // Now update the Associated Mesh Variables accordingly
         if ((_meshToUpdate.hasAssociatedMeshVariables()) && (isAllowedTheAssociatedMeshVariables(_meshToUpdate.getUserName())))
         {
             QStringList _associatedMeshName = _meshToUpdate.getAssociatedMeshVariables();
             int _pos = findMeshVariableToUpdate(_associatedMeshName.at(0),_selectedSubMenu);
             if ((_pos != -1) && (_pos < _userMeshVariablesList.size()))
             {
                 UserMeshVO _associatedMeshVO = _userMeshVariablesList.at(_pos);
                 QStringList _associatedValList = _associatedMeshVO.getBoundaryAssociatedValues();
                 if ((_associatedValList.isEmpty()) || (_associatedValList.size() <= 0))
                 {    // We need to create an initial structure with the default values and the same number of Boundaries than the parent Var
                     int _noElements = _meshToUpdate.getBoundaryNameList().size();
                     _associatedMeshVO.initializeBndAssociatedValuesToDefault("0",_noElements);
                     _associatedMeshVO.setBoundaryNameList(_meshToUpdate.getBoundaryNameList());
                 }
                 _associatedMeshVO.addBoundary(_bndNameInRow,_bndVal);
                 _userMeshVariablesList.replace(_pos,_associatedMeshVO);
                 _bndVal.clear(); // We donot need to store it
             }
         }
         // Update the values of the mesh with the new Boundary and boundary values
         _meshToUpdate.addBoundary(_bndNameInRow,_bndVal);
         _userMeshVariablesList.replace(_posToUpdate,_meshToUpdate);
     }
 }
void MeshDialog::setIsMultizoneProject (bool _val)
Definition at line 1151 of file meshdialog.cpp.
References _isMultizoneProject.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     _isMultizoneProject = _val;
 }
void MeshDialog::setIsNSProblem (bool _val)
Definition at line 1147 of file meshdialog.cpp.
References _isNSProblem.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
    _isNSProblem = _val;
 }
void MeshDialog::setMeshValues (QHash< QString, QString > _val)
Function to set the mesh values.
Parameters
QHash<QString
_val
Definition at line 945 of file meshdialog.cpp.
References _meshValues.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
        _meshValues = _val;
 }
void MeshDialog::setSolverConfigManager (SolverConfigManager * _manager)
Set the solver config manager.
Parameters
_manager
Definition at line 964 of file meshdialog.cpp.
References _solverManager.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     _solverManager = _manager;
 }
void MeshDialog::setUserConfiguredMeshValues (QHash< QString, QString > _userValues)
Set up configured mesh values.
Parameters
QHash<QString
_userValues
Definition at line 1020 of file meshdialog.cpp.
References _configUserMeshValues.
Referenced by MainWindow::loadMeshDialog(), and MultizoneIndividualTabForm::on_editBoundConfigButton_clicked().
 {
     _configUserMeshValues =_userValues;
 }
void MeshDialog::showValuesInValueCol (int row, QString _value) private
Function to show the values that comes from the specific window.
Parameters
row
_value
Definition at line 820 of file meshdialog.cpp.
References SolverMarkerMenuHelper::addEditIconToColumn(), CurrentValueColumn, EditIconColum, and ui.
Referenced by changedComboValueByUser(), launchSpecificBoundaryConfigWindow(), and updateTable().
 {
     ui->meshTableWidget->item(row,CurrentValueColumn)->setText(_value);
     if (!_value.isEmpty())
     {
         SolverMarkerMenuHelper _markerHelper;
         _markerHelper.addEditIconToColumn(ui->meshTableWidget,row,EditIconColum);
     }
     else
         ui->meshTableWidget->item(row,EditIconColum)->setIcon(QIcon(""));
 }
QStringList MeshDialog::splitBndNameAndValues (QStringList _list) private
Definition at line 317 of file meshdialog.cpp.
References _meshValues, COMMA_SEPARATOR, and SEMICOLON_SEPARATOR.
Referenced by createMeshVariables().
 {
     QStringList _result;
     QStringList _bndNames;
     QStringList _bndValues;
     QStringList _tmpBndValues;
     for (int i = 0; i < _list.size();i++)
     {
         //QString _valToCompare = _list.at(i);
         QString _item = _list.at(i);
         QString _keyVal = _meshValues.key(_item);
         bool _isBnd = _meshValues.contains(_keyVal);
         if (_isBnd)
         {
             _bndNames.append(_item);
             if (!_tmpBndValues.isEmpty())
             {
                 _bndValues.append(_tmpBndValues.join(COMMA_SEPARATOR));
                 _tmpBndValues.clear();
             }
          }else
             _tmpBndValues.append(_item);
         if (i == _list.size()-1)
             _bndValues.append(_tmpBndValues.join(COMMA_SEPARATOR));
     }
     _result.append(_bndNames.join(COMMA_SEPARATOR));
     _result.append(_bndValues.join(SEMICOLON_SEPARATOR));
     return _result;
 }
void MeshDialog::updateComboValue (int _rowToUpdate, QString _selVarName) private
Function to update the combo value with previous values.
Parameters
_rowToUpdate
_selVarName
Definition at line 565 of file meshdialog.cpp.
References ColumnCheck, ColumnSelVal, and ui.
Referenced by updateTable(), and updateTableWithYesNoValues().
 {
    QComboBox * _combo = qobject_cast<QComboBox * > ( ui->meshTableWidget->cellWidget(_rowToUpdate,ColumnSelVal));
    int _index = -1;
    if (_combo)
    {
            _index = _combo->findText(_selVarName);
            if (_index != -1)
                _combo->setCurrentIndex(_index);
    }
    if (_index >0)
     ui->meshTableWidget->item(_rowToUpdate,ColumnCheck)->setCheckState(Qt::Checked);
 /*   else
        ui->meshTableWidget->item(_rowToUpdate,ColumnCheck)->setCheckState(Qt::Unchecked);
 */
 }
void MeshDialog::updateTable (QString _userVarName, QStringList _bndNames, QStringList _bndValues) private
Definition at line 518 of file meshdialog.cpp.
References showValuesInValueCol(), ui, and updateComboValue().
Referenced by updateTableWithUserValues().
 {
     for (int i = 0; i < ui->meshTableWidget->rowCount();i++)
     {
         QString _bndTableName = ui->meshTableWidget->item(i,1)->text();
         if (_bndNames.contains(_bndTableName))
         {
              updateComboValue(i,_userVarName);
             if (!_bndValues.isEmpty())
              {
                int _pos = _bndNames.indexOf(_bndTableName);
                if( (_pos != -1) && (_pos < _bndValues.size()) )
                     showValuesInValueCol(i, _bndValues.at(_pos));
             }
         }
     }
 }
void MeshDialog::updateTableWithUserValues () private
Definition at line 459 of file meshdialog.cpp.
References _selectedSubMenu, _userMeshVariablesList, findMeshVariableToUpdate(), UserMeshVO::getAssociatedMeshVariables(), UserMeshVO::getBoundaryAssociatedValues(), UserMeshVO::getBoundaryNameList(), UserMeshVO::getParentMenu(), UserMeshVO::getUserName(), UserMeshVO::hasAssociatedMeshVariables(), isAllowedTheAssociatedMeshVariables(), MARKER_CHILD_TITLE, updateTable(), and updateTableWithYesNoValues().
Referenced by fillTable().
 {
     for (int i = 0; i < _userMeshVariablesList.size();i++)
     {
         UserMeshVO _userMeshVar = _userMeshVariablesList.at(i);
         QString _parentMenu = _userMeshVar.getParentMenu();
         if (_selectedSubMenu.contains(_parentMenu))
         {
             QString _userVarName =_userMeshVar.getUserName();
             QStringList _bndNames = _userMeshVar.getBoundaryNameList();
             QStringList _bndValues = _userMeshVar.getBoundaryAssociatedValues();
             if (_selectedSubMenu.contains(MARKER_CHILD_TITLE))
             {
                 if ((_userMeshVar.hasAssociatedMeshVariables()) && (isAllowedTheAssociatedMeshVariables(_userVarName)))
                 {
                     QStringList _associatedMeshNameList = _userMeshVar.getAssociatedMeshVariables();
                     // Notice: At the moment we only consider the option of having ONLY ONE associated Mesh
                     // This is done as QStringList for the future, although the logic was not implemented
                     // .... In case of this need, it is needed to do the full logic (TODO)
                     int _pos = findMeshVariableToUpdate(_associatedMeshNameList.at(0),_selectedSubMenu);
                     if (_pos != -1)
                     {
                         UserMeshVO _associatedMeshVar = _userMeshVariablesList.at(_pos);
                         _bndValues =_associatedMeshVar.getBoundaryAssociatedValues();
                     }
                 }
                 updateTable(_userVarName,_bndNames,_bndValues);
             }
             else
                 updateTableWithYesNoValues(_bndNames,_bndValues);
         }
     }
 }
void MeshDialog::updateTableWithYesNoValues (QStringList _bndNames, QStringList _bndValues) private
Definition at line 502 of file meshdialog.cpp.
References BndNameColumn, ui, and updateComboValue().
Referenced by updateTableWithUserValues().
 {
     for (int i=0 ; i < ui->meshTableWidget->rowCount();i++)
     {
         QString _cBndName = ui->meshTableWidget->item(i,BndNameColumn)->text();
         int _pos = _bndNames.indexOf(_cBndName);
         if ( (_pos != -1) && (_pos < _bndValues.size()))
              updateComboValue(i,_bndValues.at(_pos));
         else
             updateComboValue(i,"NO");
     }
 }
Member Data Documentation
QStringList MeshDialog::_associatedMeshVariables private
Definition at line 72 of file meshdialog.h.
QHash<QString,QString> MeshDialog::_configUserMeshValues private
Definition at line 57 of file meshdialog.h.
Referenced by createMeshVariables(), getUserConfiguredMeshValues(), on_meshButtonBox_rejected(), and setUserConfiguredMeshValues().
bool MeshDialog::_isLoadingTable private
Definition at line 64 of file meshdialog.h.
Referenced by changedComboValueByUser(), and on_meshTreeView_clicked().
bool MeshDialog::_isMultizoneProject private
Definition at line 68 of file meshdialog.h.
Referenced by initializeMeshValues(), loadMenu(), MeshDialog(), and setIsMultizoneProject().
bool MeshDialog::_isNSProblem private
Definition at line 67 of file meshdialog.h.
Referenced by changedComboValueByUser(), isAllowedTheAssociatedMeshVariables(), MeshDialog(), on_meshTableWidget_cellClicked(), and setIsNSProblem().
MarkerMenuManager* MeshDialog::_markerManager private
Definition at line 65 of file meshdialog.h.
Referenced by launchSpecificBoundaryConfigWindow(), MeshDialog(), and ~MeshDialog().
QHash<QString,QString> MeshDialog::_meshValues private
Definition at line 56 of file meshdialog.h.
Referenced by checkIfAllBoundaryNames(), fillTable(), getMeshValues(), launchSpecificBoundaryConfigWindow(), setMeshValues(), and splitBndNameAndValues().
bool MeshDialog::_needToSave private
Definition at line 66 of file meshdialog.h.
Referenced by changedComboValueByUser(), launchSpecificBoundaryConfigWindow(), MeshDialog(), needToSave(), and on_meshButtonBox_rejected().
QHash<QString,QString> MeshDialog::_previousUserMeshValues private
Definition at line 58 of file meshdialog.h.
Referenced by restoreValues().
QString MeshDialog::_selectedSubMenu private
Definition at line 63 of file meshdialog.h.
Referenced by buildHelpContent(), changedComboValueByUser(), fillTable(), getBndTypeName(), loadTableHeader(), needToOpenSpecificConfigWindow(), on_meshTreeView_clicked(), restoreValues(), saveUserChanges(), and updateTableWithUserValues().
QSignalMapper* MeshDialog::_signalMapper private
Definition at line 61 of file meshdialog.h.
Referenced by addSignals(), and MeshDialog().
QSignalMapper* MeshDialog::_signalMapperCheckList private
Definition at line 62 of file meshdialog.h.
Referenced by addSignals(), and MeshDialog().
SolverConfigManager* MeshDialog::_solverManager private
Definition at line 60 of file meshdialog.h.
Referenced by buildHelpContent(), fillTable(), initializeMeshValues(), loadMenu(), needToOpenSpecificConfigWindow(), restoreValues(), and setSolverConfigManager().
QHash<QString,QString> MeshDialog::_storedSpecificBoundValues private
Definition at line 59 of file meshdialog.h.
Referenced by launchSpecificBoundaryConfigWindow().
bool MeshDialog::_userAcceptChanges private
Definition at line 69 of file meshdialog.h.
Referenced by hasUserAcceptChanges(), MeshDialog(), and on_meshButtonBox_accepted().
QHash<QString,QString> MeshDialog::_userBndVariableValues private
Definition at line 71 of file meshdialog.h.
Referenced by buildUserBndValueMap(), getUserBndVariableValues(), and removeBoundaryNamesInAssociatedVariables().
QList<UserMeshVO> MeshDialog::_userMeshVariablesList private
Definition at line 74 of file meshdialog.h.
Referenced by buildUserBndValueMap(), createMeshVariables(), fillTable(), findMeshVariableToUpdate(), findMeshVariableToUpdateByBndValue(), findMeshVariableToUpdateByFileNameVar(), initBndNamesInAssociatedMeshVar(), removeBoundaryNamesInAssociatedVariables(), saveUserChanges(), and updateTableWithUserValues().
Ui::MeshDialog* MeshDialog::ui private
Definition at line 54 of file meshdialog.h.
Referenced by addSignals(), buildAllToolTips(), buildHelpContent(), changedComboValueByUser(), fillTable(), getBoundaryRow(), launchSpecificBoundaryConfigWindow(), loadMenu(), loadTableHeader(), MeshDialog(), on_meshTableWidget_cellClicked(), on_meshTreeView_clicked(), resetTable(), restoreValues(), saveUserChanges(), showValuesInValueCol(), updateComboValue(), updateTable(), updateTableWithYesNoValues(), and ~MeshDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/meshdialog.h
Forms/SolverMenuDialog/meshdialog.cpp