BBIPED Platform: SolverUtil Class Reference
SolverUtil Class Reference
#include <solverutil.h>
Public Member Functions
SolverUtil ()
Constructor.
SolverVO uiImportSolverConfigFile (QString _filePath, ProjectData _projectVO)
Function to import an existent solver configuration file.
SolverVO uiImportSolverMeshFile (QString _meshFilePath, ProjectData _projectVO)
Function to import an existent mesh file.
SolverVO uiImportSolverMeshInfoFile (QString _meshFilePath, ProjectData _projectVO)
Detailed Description
Definition at line 9 of file solverutil.h.
Constructor & Destructor Documentation
SolverUtil::SolverUtil ()
Constructor.
Definition at line 31 of file solverutil.cpp.
 {
 }
Member Function Documentation
SolverVO SolverUtil::uiImportSolverConfigFile (QString _filePath, ProjectData _projectVO)
Function to import an existent solver configuration file.
Parameters
_filePath
_projectVO
Returns
SolverVO
Definition at line 46 of file solverutil.cpp.
References UtilFiles::importFile(), SolverVO::setSolverConfigFilePath(), and TOOL4.
 {
     SolverVO _solverVO;
     UtilFiles _fileHelper;
     QString _destFilePath = _fileHelper.importFile(_filePath,_projectVO,TOOL4);
     _solverVO.setSolverConfigFilePath(_destFilePath);
     return _solverVO;
 }
SolverVO SolverUtil::uiImportSolverMeshFile (QString _meshFilePath, ProjectData _projectVO)
Function to import an existent mesh file.
Parameters
_meshFilePath
_projectVO
Returns
SolverVO
Definition at line 65 of file solverutil.cpp.
References UtilFiles::createLink(), ProjectData::getProjectPath(), SolverVO::setSolverFilePath(), and TOOL4.
Referenced by MainWindow::importMeshFile(), and MainWindow::importMeshInfoFile().
 {
     UtilFiles _fileHelper;
     SolverVO _solverVO;
     _fileHelper.createLink(_meshFilePath,_projectVO,TOOL4);
     QString _destFilePath = QDir(QDir(_projectVO.getProjectPath()).filePath(TOOL4)).filePath(QFileInfo(_meshFilePath).fileName());
     //QString _destFilePath = _fileHelper.importFile(_meshFilePath,_projectVO,TOOL4);
     _solverVO.setSolverFilePath(_destFilePath);
     return _solverVO;
 }
SolverVO SolverUtil::uiImportSolverMeshInfoFile (QString _meshFilePath, ProjectData _projectVO)
Definition at line 76 of file solverutil.cpp.
References UtilFiles::importFile(), SolverVO::setSolverFilePath(), and TOOL4.
 {
     UtilFiles _fileHelper;
     SolverVO _solverVO;
     QString _destFilePath = _fileHelper.importFile(_meshFilePath,_projectVO,TOOL4);
     _solverVO.setSolverFilePath(_destFilePath);
     return _solverVO;
 }
The documentation for this class was generated from the following files:
Solver/solverutil.h
Solver/solverutil.cpp