BBIPED Platform: XmlUtil Class Reference
XmlUtil Class Reference
#include <xmlutil.h>
Public Member Functions
XmlUtil ()
bool createInitialXmlMultizoneProjectFile (QString _filePath, QString _projectPath, QString _projectFileName)
Function that creates the project XML file initial for Multizone project.
bool createInitialXmlProjectFile (QString _filePath, QString _projectPath, QString _projectFileName)
Function that creates the project XML file initial.
void createSU2XmlElements (QString _su2FilePath, QString _su2ConfigFilePath, QXmlStreamWriter *_xmlWriter)
Function that creates the correspondent Solver elements to be included in the XML project file.
bool createXmlMultizoneProjectFile (QString _filePath, MultizoneProjectData _multizoneProjectData, ProjectDetails _projectDetails)
Function that creates the multizone project details element from the xml.
bool createXmlProjectFile (QString _filePath, QString _projectPath, QString _projectFileName, QString _su2FilePath, QString _su2ConfigFilePath, ProjectDetails _projectDetails)
Function that creates and updates if needed the XML project file.
void getFileListInformation (QXmlStreamReader *xmlReader, QStringList *_configFileList, QStringList *_meshFileList)
Function to get the all the information of config and mesh lists.
MultizoneProjectData getInitialMultizoneProjectInformation (QXmlStreamReader *xmlReader)
Function to get the all the information of the multizone project.
ProjectData getInitialProjectInformation (QXmlStreamReader *xmlReader)
Function to get the all the information of the project.
SolverVO getSU2Information (QXmlStreamReader *xmlReader)
Function to get the Solver information.
ProjectDetails getXmlProjectDetails (QString _projectFilePath)
Function to read the XML Project Details file.
MultizoneProjectData readXmlMultizoneProjectFile (QString _projectFilePath)
Function to read the XML Multizone Project file.
ProjectData readXmlProjectFile (QString _projectFilePath)
Function to read the XML Project file.
Private Member Functions
void createProjectDetailsXmlElements (QXmlStreamWriter *_xmlWriter, ProjectDetails _projectDetails)
Function that creates the project details element from the xml.
ProjectDetails getProjectDetailsInformation (QXmlStreamReader *xmlReader)
Function to get the XML Project Details file.
Detailed Description
Definition at line 14 of file xmlutil.h.
Constructor & Destructor Documentation
XmlUtil::XmlUtil ()
Definition at line 28 of file xmlutil.cpp.
 {
 }
Member Function Documentation
bool XmlUtil::createInitialXmlMultizoneProjectFile (QString _filePath, QString _projectPath, QString _projectFileName)
Function that creates the project XML file initial for Multizone project.
Parameters
_filePath
_projectPath
_projectFileName
Returns
bool
Definition at line 89 of file xmlutil.cpp.
References createProjectDetailsXmlElements(), createSU2XmlElements(), INITIAL_PATH, PROJECT_DATA_TAG, PROJECT_ELEMENT, PROJECT_FILENAME_ATT, PROJECT_FULLPATH_ATT, PROJECT_PATH_ATT, and SOLVER_LIST_ELEMENT.
Referenced by UtilFiles::createMultizoneProjectFile().
 {
     QFile _file(_filePath);
     bool _fileCreated = false;
     if (!_file.exists())
     {
          _fileCreated = _file.open(QIODevice::ReadWrite);
         if (_fileCreated)
         {
             QXmlStreamWriter xmlWriter(&_file);
             xmlWriter.setAutoFormatting(true);
             xmlWriter.writeStartDocument();
             xmlWriter.writeStartElement(PROJECT_ELEMENT);
             xmlWriter.writeStartElement(PROJECT_DATA_TAG);
                 xmlWriter.writeAttribute(PROJECT_PATH_ATT,_projectPath);
                 xmlWriter.writeAttribute(PROJECT_FILENAME_ATT,_projectFileName);
                 xmlWriter.writeAttribute(PROJECT_FULLPATH_ATT,_filePath);
             xmlWriter.writeEndElement();
             xmlWriter.writeStartElement(SOLVER_LIST_ELEMENT);
             // Adding Solver structure
             createSU2XmlElements(INITIAL_PATH, INITIAL_PATH,&xmlWriter);
             // Adding Project Details
             ProjectDetails _newProjectDetails;
             createProjectDetailsXmlElements(&xmlWriter,_newProjectDetails);
             xmlWriter.writeEndElement();
             xmlWriter.writeEndElement();
             xmlWriter.writeEndDocument();
             _file.close();
         }
     }
     return _fileCreated;
 }
bool XmlUtil::createInitialXmlProjectFile (QString _filePath, QString _projectPath, QString _projectFileName)
Function that creates the project XML file initial.
Parameters
_filePath
_projectPath
_projectFileName
Returns
bool
Definition at line 40 of file xmlutil.cpp.
References createProjectDetailsXmlElements(), createSU2XmlElements(), INITIAL_PATH, PROJECT_DATA_TAG, PROJECT_ELEMENT, PROJECT_FILENAME_ATT, PROJECT_FULLPATH_ATT, and PROJECT_PATH_ATT.
Referenced by UtilFiles::createProjectFile().
 {
     QFile _file(_filePath);
     bool _fileCreated = false;
     if (!_file.exists())
     {
          _fileCreated = _file.open(QIODevice::ReadWrite);
         if (_fileCreated)
         {
             QXmlStreamWriter xmlWriter(&_file);
             xmlWriter.setAutoFormatting(true);
             xmlWriter.writeStartDocument();
             xmlWriter.writeStartElement(PROJECT_ELEMENT);
             xmlWriter.writeStartElement(PROJECT_DATA_TAG);
                 xmlWriter.writeAttribute(PROJECT_PATH_ATT,_projectPath);
                 xmlWriter.writeAttribute(PROJECT_FILENAME_ATT,_projectFileName);
                 xmlWriter.writeAttribute(PROJECT_FULLPATH_ATT,_filePath);
             xmlWriter.writeEndElement();
             // Adding Solver structure
             createSU2XmlElements(INITIAL_PATH, INITIAL_PATH,&xmlWriter);
             // Adding Project Details
             ProjectDetails _newProjectDetails;
             createProjectDetailsXmlElements(&xmlWriter,_newProjectDetails);
             xmlWriter.writeEndElement();
             // Closing the root and the document
             xmlWriter.writeEndElement();
             xmlWriter.writeEndDocument();
             _file.close();
         }
     }
     return _fileCreated;
 }
void XmlUtil::createProjectDetailsXmlElements (QXmlStreamWriter * _xmlWriter, ProjectDetails _projectDetails) private
Function that creates the project details element from the xml.
Parameters
_xmlWriter
_projectDetails
Definition at line 184 of file xmlutil.cpp.
References ProjectDetails::getAuthor(), ProjectDetails::getOtherDetails(), ProjectDetails::getProjectTile(), ProjectDetails::getStartingDate(), PROJECT_DETAIL_AUTHOR_TAG, PROJECT_DETAIL_OTHERDETAILS_TAG, PROJECT_DETAIL_STARTINGDATE_TAG, PROJECT_DETAIL_TAG, and PROJECT_DETAIL_TITLE_TAG.
Referenced by createInitialXmlMultizoneProjectFile(), createInitialXmlProjectFile(), createXmlMultizoneProjectFile(), and createXmlProjectFile().
 {
     _xmlWriter->writeStartElement(PROJECT_DETAIL_TAG);
         _xmlWriter->writeAttribute(PROJECT_DETAIL_TITLE_TAG,_projectDetails.getProjectTile());
         _xmlWriter->writeAttribute(PROJECT_DETAIL_AUTHOR_TAG,_projectDetails.getAuthor());
         _xmlWriter->writeAttribute(PROJECT_DETAIL_STARTINGDATE_TAG,_projectDetails.getStartingDate());
         _xmlWriter->writeAttribute(PROJECT_DETAIL_OTHERDETAILS_TAG,_projectDetails.getOtherDetails());
     _xmlWriter->writeEndElement();
 }
void XmlUtil::createSU2XmlElements (QString _su2FilePath, QString _su2ConfigFilePath, QXmlStreamWriter * _xmlWriter)
Function that creates the correspondent Solver elements to be included in the XML project file.
Parameters
_su2FilePath
_su2ConfigFilePath
_xmlWriter
Definition at line 256 of file xmlutil.cpp.
References PATH_ATT, SU2_CONFIG_FILE_ELEMENT, SU2_ELEMENT, and SU2_FILE_ELEMENT.
Referenced by createInitialXmlMultizoneProjectFile(), createInitialXmlProjectFile(), createXmlMultizoneProjectFile(), and createXmlProjectFile().
 {
     _xmlWriter->writeStartElement(SU2_ELEMENT);
         _xmlWriter->writeStartElement(SU2_FILE_ELEMENT);
         _xmlWriter->writeAttribute(PATH_ATT,_su2FilePath);
         _xmlWriter->writeEndElement();
         _xmlWriter->writeStartElement(SU2_CONFIG_FILE_ELEMENT);
         _xmlWriter->writeAttribute(PATH_ATT,_su2ConfigFilePath);
         _xmlWriter->writeEndElement();
     _xmlWriter->writeEndElement();
 }
bool XmlUtil::createXmlMultizoneProjectFile (QString _filePath, MultizoneProjectData _multizoneProjectData, ProjectDetails _projectDetails)
Function that creates the multizone project details element from the xml.
Parameters
_filePath
_multizoneProjectData
Returns
bool
Definition at line 201 of file xmlutil.cpp.
References createProjectDetailsXmlElements(), createSU2XmlElements(), MultizoneProjectData::getListConfigFiles(), MultizoneProjectData::getListMeshFiles(), MultizoneProjectData::getProjectName(), MultizoneProjectData::getProjectPath(), MULTIZONE_PROJECT_FILE_EXT, PROJECT_DATA_TAG, PROJECT_ELEMENT, PROJECT_FILENAME_ATT, PROJECT_FULLPATH_ATT, PROJECT_PATH_ATT, and SOLVER_LIST_ELEMENT.
Referenced by UtilFiles::updateMultizoneProjectDataToFile().
 {
     QFile _file(_filePath);
     bool _fileCreated = false;
     if (_file.exists())
         _file.remove();
     _fileCreated = _file.open(QIODevice::ReadWrite);
     if (_fileCreated)
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         xmlWriter.writeStartElement(PROJECT_ELEMENT);
         xmlWriter.writeStartElement(PROJECT_DATA_TAG);
             xmlWriter.writeAttribute(PROJECT_PATH_ATT,_multizoneProjectData.getProjectPath());
             QString _projectNameWithExt = _multizoneProjectData.getProjectName() + "." + MULTIZONE_PROJECT_FILE_EXT;
             xmlWriter.writeAttribute(PROJECT_FILENAME_ATT,_projectNameWithExt);
             xmlWriter.writeAttribute(PROJECT_FULLPATH_ATT,_filePath);
         xmlWriter.writeEndElement();
         // Adding SU2 structure
          xmlWriter.writeStartElement(SOLVER_LIST_ELEMENT);
          QStringList _configFiles =  _multizoneProjectData.getListConfigFiles();
          QStringList _meshFiles = _multizoneProjectData.getListMeshFiles();
          int _totalsize =_configFiles.size();
          if (_configFiles.size() != _meshFiles.size())
              if (_configFiles.size() > _meshFiles.size())
                  _totalsize = _meshFiles.size();
          for (int i = 0; i < _totalsize; i++)
              createSU2XmlElements(_meshFiles.at(i), _configFiles.at(i),&xmlWriter);
          xmlWriter.writeEndElement();
         // Adding the project details
          createProjectDetailsXmlElements(&xmlWriter,_projectDetails);
         // Closing the root and the document
         xmlWriter.writeEndElement();
         xmlWriter.writeEndDocument();
         _file.close();
     }
   //  }
     return _fileCreated;
 }
bool XmlUtil::createXmlProjectFile (QString _filePath, QString _projectPath, QString _projectFileName, QString _su2FilePath, QString _su2ConfigFilePath, ProjectDetails _projectDetails)
Function that creates and updates if needed the XML project file.
Parameters
_filePath
_projectPath
_projectFileName
_su2FilePath
_su2ConfigFilePath
Returns
bool
Definition at line 138 of file xmlutil.cpp.
References createProjectDetailsXmlElements(), createSU2XmlElements(), PROJECT_DATA_TAG, PROJECT_ELEMENT, PROJECT_FILENAME_ATT, PROJECT_FULLPATH_ATT, and PROJECT_PATH_ATT.
Referenced by UtilFiles::updateProjectDataToFile().
 {
     QFile _file(_filePath);
     bool _fileCreated = false;
     if (_file.exists())
         _file.remove();
     _fileCreated = _file.open(QIODevice::ReadWrite);
     if (_fileCreated)
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         xmlWriter.writeStartElement(PROJECT_ELEMENT);
         xmlWriter.writeStartElement(PROJECT_DATA_TAG);
             xmlWriter.writeAttribute(PROJECT_PATH_ATT,_projectPath);
             xmlWriter.writeAttribute(PROJECT_FILENAME_ATT,_projectFileName);
             xmlWriter.writeAttribute(PROJECT_FULLPATH_ATT,_filePath);
         xmlWriter.writeEndElement();
         // Adding SU2 structure
         createSU2XmlElements(_su2FilePath, _su2ConfigFilePath,&xmlWriter);
         // Add the Project Details
         createProjectDetailsXmlElements(&xmlWriter,_projectDetails);
         // Ending the root and the document
         xmlWriter.writeEndElement();
         xmlWriter.writeEndDocument();
         _file.close();
     }
   //  }
     return _fileCreated;
 }
void XmlUtil::getFileListInformation (QXmlStreamReader * xmlReader, QStringList * _configFileList, QStringList * _meshFileList)
Function to get the all the information of config and mesh lists.
Parameters
xmlReader
_configFileList
_meshFileList
Definition at line 472 of file xmlutil.cpp.
References StrEqual, SU2_CONFIG_FILE_ELEMENT, SU2_ELEMENT, and SU2_FILE_ELEMENT.
Referenced by readXmlMultizoneProjectFile().
  {
      bool _foundSolverTag = false;
      while ( (!xmlReader->atEnd()) && (!xmlReader->hasError()) )
      {
          QXmlStreamReader::TokenType token = xmlReader->readNext();
          if (token == QXmlStreamReader::StartDocument) continue;
          if (token == QXmlStreamReader::StartElement)
          {
              if (QString::compare(xmlReader->name().toString(), SU2_ELEMENT) == StrEqual)
              {
                  _foundSolverTag = true;
                  continue;
              }
              if (_foundSolverTag)
              {
                  if (QString::compare(xmlReader->name().toString(), SU2_FILE_ELEMENT) == StrEqual)
                  {
                          QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                          if (_elementAtt.hasAttribute("path"))
                              _meshFileList->append(_elementAtt.value("path").toString());
                   }
                  if (QString::compare(xmlReader->name().toString(), SU2_CONFIG_FILE_ELEMENT) == StrEqual)
                  {
                          QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                          if (_elementAtt.hasAttribute("path"))
                           _configFileList->append(_elementAtt.value("path").toString());
                   }
              }
          }
      }
  }
MultizoneProjectData XmlUtil::getInitialMultizoneProjectInformation (QXmlStreamReader * xmlReader)
Function to get the all the information of the multizone project.
Parameters
xmlReader
Returns
MultizoneProjectData
Definition at line 432 of file xmlutil.cpp.
References PROJECT_DATA_TAG, PROJECT_FILENAME_ATT, PROJECT_PATH_ATT, MultizoneProjectData::setProjectName(), MultizoneProjectData::setProjectPath(), and StrEqual.
Referenced by readXmlMultizoneProjectFile().
  {
      MultizoneProjectData _projectData;
      bool endInformation = false;
      while ( (!xmlReader->atEnd()) && (!xmlReader->hasError()) && (!endInformation))
      {
          QXmlStreamReader::TokenType token = xmlReader->readNext();
          if (token == QXmlStreamReader::StartDocument) continue;
          if (token == QXmlStreamReader::StartElement)
          {
              if (QString::compare(xmlReader->name().toString(), PROJECT_DATA_TAG) == StrEqual)
              {
                 QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                 if (_elementAtt.hasAttribute(PROJECT_PATH_ATT))
                 {
                    _projectData.setProjectPath(_elementAtt.value(PROJECT_PATH_ATT).toString());
                 }
                 if (_elementAtt.hasAttribute(PROJECT_FILENAME_ATT))
                 {
                     QString _fileNameBase = QFileInfo(_elementAtt.value(PROJECT_FILENAME_ATT).toString()).baseName();
                     _projectData.setProjectName(_fileNameBase);
                 }
                 return _projectData;
              }
          }
      }
      return _projectData;
  }
ProjectData XmlUtil::getInitialProjectInformation (QXmlStreamReader * xmlReader)
Function to get the all the information of the project.
Parameters
xmlReader
Returns
ProjectData
Definition at line 398 of file xmlutil.cpp.
References PROJECT_DATA_TAG, PROJECT_FILENAME_ATT, PROJECT_PATH_ATT, ProjectData::setProjectFileName(), ProjectData::setProjectPath(), and StrEqual.
Referenced by readXmlProjectFile().
  {
      ProjectData _projectData;
      bool endInformation = false;
      while ( (!xmlReader->atEnd()) && (!xmlReader->hasError()) && (!endInformation))
      {
          QXmlStreamReader::TokenType token = xmlReader->readNext();
          if (token == QXmlStreamReader::StartDocument) continue;
          if (token == QXmlStreamReader::StartElement)
          {
              if (QString::compare(xmlReader->name().toString(), PROJECT_DATA_TAG) == StrEqual)
              {
                 QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                 if (_elementAtt.hasAttribute(PROJECT_PATH_ATT))
                    _projectData.setProjectPath(_elementAtt.value(PROJECT_PATH_ATT).toString());
                 if (_elementAtt.hasAttribute(PROJECT_FILENAME_ATT))
                     _projectData.setProjectFileName(_elementAtt.value(PROJECT_FILENAME_ATT).toString());
                 return _projectData;
              }
          }
      }
      return _projectData;
  }
ProjectDetails XmlUtil::getProjectDetailsInformation (QXmlStreamReader * xmlReader) private
Function to get the XML Project Details file.
Parameters
xmlReader
Returns
ProjectDetails
Definition at line 363 of file xmlutil.cpp.
References PROJECT_DETAIL_AUTHOR_TAG, PROJECT_DETAIL_OTHERDETAILS_TAG, PROJECT_DETAIL_STARTINGDATE_TAG, PROJECT_DETAIL_TAG, PROJECT_DETAIL_TITLE_TAG, ProjectDetails::setAuthor(), ProjectDetails::setOtherDetails(), ProjectDetails::setProjectTile(), ProjectDetails::setStartingDate(), and StrEqual.
Referenced by getXmlProjectDetails().
 {
   ProjectDetails _projectDetails;
   bool endInformation = false;
    while ( (!xmlReader->atEnd()) && (!xmlReader->hasError()) && (!endInformation))
    {
        QXmlStreamReader::TokenType token = xmlReader->readNext();
        if (token == QXmlStreamReader::StartDocument) continue;
        if (token == QXmlStreamReader::StartElement)
        {
            if (QString::compare(xmlReader->name().toString(), PROJECT_DETAIL_TAG) == StrEqual){
                QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                if (_elementAtt.hasAttribute(PROJECT_DETAIL_TITLE_TAG))
                   _projectDetails.setProjectTile(_elementAtt.value(PROJECT_DETAIL_TITLE_TAG).toString());
                if (_elementAtt.hasAttribute(PROJECT_DETAIL_AUTHOR_TAG))
                    _projectDetails.setAuthor(_elementAtt.value(PROJECT_DETAIL_AUTHOR_TAG).toString());
                if (_elementAtt.hasAttribute(PROJECT_DETAIL_STARTINGDATE_TAG))
                    _projectDetails.setStartingDate(_elementAtt.value(PROJECT_DETAIL_STARTINGDATE_TAG).toString());
                if (_elementAtt.hasAttribute(PROJECT_DETAIL_OTHERDETAILS_TAG))
                    _projectDetails.setOtherDetails(_elementAtt.value(PROJECT_DETAIL_OTHERDETAILS_TAG).toString());
                return _projectDetails;
        }
       }
    }
    return _projectDetails;
 }
SolverVO XmlUtil::getSU2Information (QXmlStreamReader * xmlReader)
Function to get the Solver information.
Parameters
xmlReader
Returns
SolverVO
Definition at line 514 of file xmlutil.cpp.
References SolverVO::setSolverConfigFilePath(), SolverVO::setSolverFilePath(), StrEqual, SU2_CONFIG_FILE_ELEMENT, SU2_ELEMENT, and SU2_FILE_ELEMENT.
Referenced by readXmlProjectFile().
  {
      SolverVO _solverObj;
      bool _foundSu2Tag = false;
      int _su2TagsProcessed = 0;
      bool endInformation = false;
      while ( (!xmlReader->atEnd()) && (!xmlReader->hasError()) && (!endInformation))
      {
          QXmlStreamReader::TokenType token = xmlReader->readNext();
          if (token == QXmlStreamReader::StartDocument) continue;
          if (token == QXmlStreamReader::StartElement)
          {
              if (QString::compare(xmlReader->name().toString(), SU2_ELEMENT) == StrEqual)
              {
                  _foundSu2Tag = true;
                  continue;
              }
              if (_foundSu2Tag)
              {
                  if (QString::compare(xmlReader->name().toString(), SU2_FILE_ELEMENT) == StrEqual)
                  {
                          QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                          if (_elementAtt.hasAttribute("path"))
{
                             _solverObj.setSolverFilePath(_elementAtt.value("path").toString());
                             _su2TagsProcessed++;
                          }
                   }
                  if (QString::compare(xmlReader->name().toString(), SU2_CONFIG_FILE_ELEMENT) == StrEqual)
                  {
                          QXmlStreamAttributes _elementAtt = xmlReader->attributes();
                          if (_elementAtt.hasAttribute("path"))
{
                             _solverObj.setSolverConfigFilePath(_elementAtt.value("path").toString());
                             _su2TagsProcessed++;
                          }
                   }
              }
          }
          else
            if ((_foundSu2Tag) && (token == QXmlStreamReader::EndElement) && (_su2TagsProcessed == 2))
               endInformation = true;
      }
      return _solverObj;
  }
ProjectDetails XmlUtil::getXmlProjectDetails (QString _projectFilePath)
Function to read the XML Project Details file.
Parameters
_projectFilePath
Returns
ProjectDetails
Definition at line 340 of file xmlutil.cpp.
References getProjectDetailsInformation().
Referenced by UtilFiles::openProjectDetails().
 {
     QFile _file(_projectFilePath);
     bool _fileRead = true;
     ProjectDetails _projectDetails;
     _fileRead = _file.open(QIODevice::ReadOnly | QIODevice::Text);
     if (_fileRead)
     {
         QXmlStreamReader xmlReader(&_file);
         _projectDetails = getProjectDetailsInformation(&xmlReader);
    }
     _file.close();
     return _projectDetails;
 }
MultizoneProjectData XmlUtil::readXmlMultizoneProjectFile (QString _projectFilePath)
Function to read the XML Multizone Project file.
Parameters
_projectFilePath
Returns
MultizoneProjectData
Definition at line 308 of file xmlutil.cpp.
References getFileListInformation(), getInitialMultizoneProjectInformation(), MultizoneProjectData::setListConfigFiles(), and MultizoneProjectData::setListMeshFiles().
Referenced by UtilFiles::openMultizoneProjectStructure().
 {
     QFile _file(_projectFilePath);
     bool _fileRead = true;
     MultizoneProjectData _multizoneProjectData;
     _fileRead = _file.open(QIODevice::ReadOnly | QIODevice::Text);
     if (_fileRead)
     {
         QXmlStreamReader xmlReader(&_file);
         _multizoneProjectData = getInitialMultizoneProjectInformation(&xmlReader);
         QStringList _configFileList;
         QStringList _meshFileList;
         // Solver List information
         getFileListInformation(&xmlReader,&_configFileList,&_meshFileList);
         _multizoneProjectData.setListConfigFiles(_configFileList);
         _multizoneProjectData.setListMeshFiles(_meshFileList);
     }
     _file.close();
     return _multizoneProjectData;
 }
ProjectData XmlUtil::readXmlProjectFile (QString _projectFilePath)
Function to read the XML Project file.
Parameters
_projectFilePath
Returns
ProjectData
Definition at line 279 of file xmlutil.cpp.
References getInitialProjectInformation(), getSU2Information(), and ProjectData::setSolverDataInformation().
Referenced by UtilFiles::openProjectStructure().
 {
     QFile _file(_projectFilePath);
     bool _fileRead = true;
     ProjectData _projectData;
     SolverVO _solverData;
     _fileRead = _file.open(QIODevice::ReadOnly | QIODevice::Text);
     if (_fileRead)
     {
         QXmlStreamReader xmlReader(&_file);
         _projectData = getInitialProjectInformation(&xmlReader);
        //TODO: Read the rest of the Xml File and load it into the GUI
         // SU2 reading
         _solverData = getSU2Information(&xmlReader);
         _projectData.setSolverDataInformation(_solverData);
     }
     _file.close();
     return _projectData;
 }
The documentation for this class was generated from the following files:
Utility/Xml/xmlutil.h
Utility/Xml/xmlutil.cpp