BBIPED Platform: MeshInfoFileReader Class Reference
MeshInfoFileReader Class Reference
#include <meshinfofilereader.h>
Public Member Functions
MeshInfoFileReader ()
bool checkMeshInfoExist (QString _projectPath, QString _meshDetailsFileName)
void readMeshInfo (QString _filePath, MeshInfoVO *_meshData)
Private Member Functions
void get3DMeshData (QXmlStreamReader *_xmlReader, MeshInfoVO *_meshData)
QString getBndName (QXmlStreamReader *_xmlReader)
void getBndNameList (QXmlStreamReader *_xmlReader, MeshInfoVO *_meshData)
void getMeshFileName (QXmlStreamReader *_xmlReader, MeshInfoVO *_meshData)
void getMeshPath (QXmlStreamReader *_xmlReader, MeshInfoVO *_meshData)
Detailed Description
Definition at line 8 of file meshinfofilereader.h.
Constructor & Destructor Documentation
MeshInfoFileReader::MeshInfoFileReader ()
Definition at line 7 of file meshinfofilereader.cpp.
 {
 }
Member Function Documentation
bool MeshInfoFileReader::checkMeshInfoExist (QString _projectPath, QString _meshDetailsFileName)
Definition at line 11 of file meshinfofilereader.cpp.
References MESH_CONFIG_SUFFIX.
 {
     QString _filePath = QDir(_projectPath).filePath(QString(_meshDetailsFileName + "." + MESH_CONFIG_SUFFIX));
     QFile _file(_filePath);
      return _file.exists();
 }
void MeshInfoFileReader::get3DMeshData (QXmlStreamReader * _xmlReader, MeshInfoVO * _meshData) private
Definition at line 38 of file meshinfofilereader.cpp.
References MeshInfoVO::set3DMesh(), StrEqual, and XML_MESH_3D_NATURE_NODE.
Referenced by readMeshInfo().
 {
     bool _finish = false;
     bool _is3DToken = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         QString _name = _xmlReader->name().toString();
         if ( (!_is3DToken) && (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_MESH_3D_NATURE_NODE ) == StrEqual))
             _is3DToken = true;
         if ((_is3DToken) && (token != QXmlStreamReader::EndElement))
         {
            QString _is3DMesh = _xmlReader->text().toString();
            if (!_is3DMesh.isEmpty())
            {
                if (QString::compare(_is3DMesh,"YES") == StrEqual)
                    _meshData->set3DMesh(true);
                else
                    _meshData->set3DMesh(false);
            }
         }
         if ((_is3DToken) && (token == QXmlStreamReader::EndElement)&&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_3D_NATURE_NODE ) == StrEqual))
             _finish = true;
     }
 }
QString MeshInfoFileReader::getBndName (QXmlStreamReader * _xmlReader) private
Definition at line 99 of file meshinfofilereader.cpp.
References StrEqual, and XML_MESH_BND_NAME.
Referenced by getBndNameList().
 {
     bool _finish = false;
     QString _tokenVal = "";
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         QString _token = _xmlReader->name().toString();
         if ((token != QXmlStreamReader::EndElement))
             _tokenVal = _xmlReader->text().toString();
         if ((token == QXmlStreamReader::EndElement) &&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_BND_NAME ) == StrEqual))
             _finish= true;
     }
     return _tokenVal;
 }
void MeshInfoFileReader::getBndNameList (QXmlStreamReader * _xmlReader, MeshInfoVO * _meshData) private
Definition at line 66 of file meshinfofilereader.cpp.
References getBndName(), MeshInfoVO::setBoundaryNameList(), StrEqual, XML_MESH_BND_LIST, and XML_MESH_BND_NAME.
Referenced by readMeshInfo().
 {
     bool _finish = false;
     bool _isBndList = false;
     QStringList _bndList;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         QString _tokenName2 = _xmlReader->name().toString();
         if ( (!_isBndList) &&  (token == QXmlStreamReader::StartElement) &&
              (QString::compare(_xmlReader->name().toString(), XML_MESH_BND_LIST ) == StrEqual))
             _isBndList = true;
         if (_isBndList)
         {
             QString _tokenName = _xmlReader->name().toString();
             if ( (token == QXmlStreamReader::StartElement) &&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_BND_NAME ) == StrEqual))
             {
                 QString _val = getBndName(_xmlReader);
                 _bndList.append(_val);
             }
             if ( (token == QXmlStreamReader::EndElement) &&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_BND_LIST ) == StrEqual))
                 _finish = true;
         }
     }
     _meshData->setBoundaryNameList(_bndList);
 }
void MeshInfoFileReader::getMeshFileName (QXmlStreamReader * _xmlReader, MeshInfoVO * _meshData) private
Definition at line 119 of file meshinfofilereader.cpp.
References MeshInfoVO::setMeshFileName(), StrEqual, and XML_MESH_FILE_NAME.
Referenced by readMeshInfo().
 {
     bool _finish = false;
     bool _isMeshToken = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (!_isMeshToken) && (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_MESH_FILE_NAME ) == StrEqual))
                 _isMeshToken = true;
         if ((_isMeshToken) && (token != QXmlStreamReader::EndElement) && (!_xmlReader->text().toString().isEmpty()))
         {
             QString _val = _xmlReader->text().toString();
            _meshData->setMeshFileName(_val);
         }
         if ((_isMeshToken) && (token == QXmlStreamReader::EndElement) &&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_FILE_NAME ) == StrEqual))
             _finish = true;
     }
 }
void MeshInfoFileReader::getMeshPath (QXmlStreamReader * _xmlReader, MeshInfoVO * _meshData) private
Definition at line 141 of file meshinfofilereader.cpp.
References MeshInfoVO::setMeshPath(), StrEqual, and XML_MESH_PATH.
Referenced by readMeshInfo().
 {
     bool _finish = false;
     bool _isMeshToken = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (!_isMeshToken) && (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_MESH_PATH ) == StrEqual))
                 _isMeshToken = true;
         if ((_isMeshToken) && (token != QXmlStreamReader::EndElement) && (!_xmlReader->text().toString().isEmpty()))
         {
             QString _val = _xmlReader->text().toString();
            _meshData->setMeshPath(_val);
         }
         if ((_isMeshToken) && (token == QXmlStreamReader::EndElement) &&
                 (QString::compare(_xmlReader->name().toString(), XML_MESH_PATH ) == StrEqual))
             _finish = true;
     }
 }
void MeshInfoFileReader::readMeshInfo (QString _filePath, MeshInfoVO * _meshData)
Definition at line 18 of file meshinfofilereader.cpp.
References get3DMeshData(), getBndNameList(), getMeshFileName(), getMeshPath(), and MeshInfoVO::setMeshDetailsFileName().
Referenced by MainWindow::importMeshInfoFile().
 {
     QFile _file(_filePath);
     bool _fileExist = true;
     _fileExist = _file.open(QIODevice::ReadOnly | QIODevice::Text);
     if (_fileExist)
     {
         QXmlStreamReader _xmlReader(&_file);
         get3DMeshData(&_xmlReader,_meshData);
         getBndNameList(&_xmlReader,_meshData);
         getMeshFileName(&_xmlReader,_meshData);
         getMeshPath(&_xmlReader,_meshData);
         _meshData->setMeshDetailsFileName(_filePath);
     }
     _file.close();
 }
The documentation for this class was generated from the following files:
Data/Solver/MeshInfo/meshinfofilereader.h
Data/Solver/MeshInfo/meshinfofilereader.cpp