#ifndef USERPREFERENCESDEFINES_H
#define USERPREFERENCESDEFINES_H
#include <QString>

const QString XML_PREFERENCES_BBIPED_SESSION_ROOT_TAG = "bbiped-session";
const QString XML_PREFERENCES_RECENTPROJECTS_TAG = "recentprojects";
const QString XML_PREFERENCES_PROJECT_TAG=  "project";
const QString XML_PREFERENCES_PROJECT_PATH_ATT_TAG = "path";

const QString XML_PREFERENCES_USER_PREFERENCES_TAG = "userpreferences";
const QString XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_TAG = "mesviewer";
const QString XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_PATH_ATT_TAG = "path";
const QString XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_TAG = "postprocessorviewer";
const QString XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_PATH_ATT_TAG=  "path";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG = "solverengine";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG = "path";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG = "virtual";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG = "multizone";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PARALLEL_ATT_TAG = "parallel";
const QString XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PARTITION_ATT_TAG = "partition";


const QString XML_PREFERENCES_WARNING_TAG = "warningpreferences";
const QString XML_PREFERENCES_WARNING_CLOSE_APP_TAG = "close-application";
const QString XML_PREFERENCES_WARNING_CLOSE_APP_SHOW_ATT=  "show";
const QString XML_PREFERENCES_WARNING_CLOSE_PROJECT_TAG = "close-project";
const QString XML_PREFERENCES_WARNING_CLOSE_PROJECT_SHOW_ATT=  "show";

const QString XML_PREFERENCES_TEMPLATE_TAG = "template-preferences";
const QString XML_PREFERENCES_TEMPLATE_PATH_ATT = "path";

#endif // USERPREFERENCESDEFINES_H
