BBIPED Platform: SearchPairHelper Class Reference
SearchPairHelper Class Reference
#include <searchpairhelper.h>
Public Member Functions
SearchPairHelper ()
Constructor.
void clearSearchStatus ()
It clear the status to default.
QList< int > findParentChildinSearchList (int _parent, int _child)
This function is able to find the children (variable elemnts) that correspond to a specific search of a child + parent (the unique element formed by the combination of both)
int getTotalFoundElements ()
Returns the total number of found elements.
void refreshHighlight ()
This function allows to refresh the highligt according the search.
void refreshSearchInTree (const QModelIndex &index)
void registerTreeView (QTreeView *_newTree)
This function registers the TreeView.
void registerUIElements (QTreeView *_newTree, QLineEdit *_lineEdit, QLabel *_label, QTableWidget *_newTable)
This function allows the register of the UI elements.
void searchItems ()
This function searchs the items.
void setSolverManager (SolverConfigManager *_manager)
Sets the solver Manager.
void setTotalFoundElements (int _val)
Sets the total number of found elements.
Private Member Functions
void expandParentChild (int _idParent)
This function allows to expand the parent children.
void hihghlightRowTree (int _row, int _col, QModelIndex _modelIdx)
This function is able to highlight those rows in the tree that corresponds with the search.
void searchTreeBySearchTerm (QString _searchTerm)
This fucntion allows to search in the tree model by a specific search term.
Private Attributes
QLabel * _nFoundItemsLabel
QList< SearchedPair > _searchedTermList
QLineEdit * _searchLineEdit
SolverConfigManager * _solverManager
QTableWidget * _table
int _totalFoundElements
QTreeView * _tree
Detailed Description
Definition at line 11 of file searchpairhelper.h.
Constructor & Destructor Documentation
SearchPairHelper::SearchPairHelper ()
Constructor.
Definition at line 25 of file searchpairhelper.cpp.
References _totalFoundElements.
 {
     _totalFoundElements = 0;
 }
Member Function Documentation
void SearchPairHelper::clearSearchStatus ()
It clear the status to default.
Definition at line 282 of file searchpairhelper.cpp.
References _nFoundItemsLabel, _searchedTermList, _searchLineEdit, _table, _totalFoundElements, and _tree.
Referenced by TemplateDialog::on_clearSearchButton_clicked(), and SolverBasicDialog::on_clearSearchButton_clicked().
 {
     _searchLineEdit->clear();
     _tree->clearSelection();
     _table->clearSelection();
    _searchedTermList.clear();
    _totalFoundElements = 0;
    _nFoundItemsLabel->setText("0");
 }
void SearchPairHelper::expandParentChild (int _idParent) private
This function allows to expand the parent children.
Parameters
_idParent
Definition at line 158 of file searchpairhelper.cpp.
References _tree.
Referenced by refreshHighlight(), and searchItems().
 {
     QModelIndex _idx = _tree->model()->index(_idParent,0, QModelIndex());
     _tree->setExpanded(_idx,true);
 }
QList< int > SearchPairHelper::findParentChildinSearchList (int _parent, int _child)
This function is able to find the children (variable elemnts) that correspond to a specific search of a child + parent (the unique element formed by the combination of both)
Parameters
_parent
_child
Returns
QList<int>
Definition at line 225 of file searchpairhelper.cpp.
References _searchedTermList, SearchedPair::contains(), and SearchedPair::getChildrenList().
Referenced by refreshSearchInTree().
 {
     QList<int> _result;
     for (int i = 0; i < _searchedTermList.count();i++)
     {
         SearchedPair _pair = _searchedTermList.at(i);
         if (_pair.contains(_parent, _child))
             _result = _pair.getChildrenList();
     }
     return _result;
 }
int SearchPairHelper::getTotalFoundElements ()
Returns the total number of found elements.
Returns
int
Definition at line 64 of file searchpairhelper.cpp.
References _totalFoundElements.
 {
     return _totalFoundElements;
 }
void SearchPairHelper::hihghlightRowTree (int _row, int _col, QModelIndex _modelIdx) private
This function is able to highlight those rows in the tree that corresponds with the search.
Parameters
_row
_col
_modelIdx
Definition at line 119 of file searchpairhelper.cpp.
References _tree.
Referenced by refreshHighlight(), and searchItems().
 {
     QModelIndex _idx = _tree->model()->index(_row,_col,_modelIdx);
     _tree->selectionModel()->setCurrentIndex(_idx, QItemSelectionModel::Select| QItemSelectionModel::Rows);
 }
void SearchPairHelper::refreshHighlight ()
This function allows to refresh the highligt according the search.
Definition at line 95 of file searchpairhelper.cpp.
References _searchedTermList, _tree, expandParentChild(), SearchedPair::getIdChild(), SearchedPair::getIdParent(), and hihghlightRowTree().
Referenced by refreshSearchInTree().
 {
     if (!_searchedTermList.isEmpty())
     {
         for (int i = 0; i < _searchedTermList.count();i++)
         {
             SearchedPair _pair = _searchedTermList.at(i);
             hihghlightRowTree(_pair.getIdParent(),0,QModelIndex());
             expandParentChild(_pair.getIdParent());
             QModelIndex _idxParent = _tree->model()->index(_pair.getIdParent(),0,QModelIndex());
             hihghlightRowTree(_pair.getIdChild(),0,_idxParent);
         }
     }
 }
void SearchPairHelper::refreshSearchInTree (const QModelIndex & index)
This function resfresh the search in the tree
Parameters
index
Definition at line 130 of file searchpairhelper.cpp.
References _searchedTermList, _table, findParentChildinSearchList(), and refreshHighlight().
Referenced by SolverBasicDialog::on_solverMenuTree_clicked(), and TemplateDialog::on_variablesToSelectTree_clicked().
 {
     if (!_searchedTermList.isEmpty())
    {
        int _parentRow = index.parent().row();
        int _childRow = index.row();
        QList<int> _searchedTableRows = findParentChildinSearchList(_parentRow,_childRow);
        if (!_searchedTableRows.isEmpty())
        {
            for (int i = 0; i < _searchedTableRows.count();i++)
            {
                int _pos = _searchedTableRows.at(i);
                _table->selectRow(_pos);
                _table->setFocus();
            }
        }
        refreshHighlight();
    }
 }
void SearchPairHelper::registerTreeView (QTreeView * _newTree)
This function registers the TreeView.
Parameters
_newTree
Definition at line 54 of file searchpairhelper.cpp.
References _tree.
 {
     _tree = _newTree;
 }
void SearchPairHelper::registerUIElements (QTreeView * _newTree, QLineEdit * _lineEdit, QLabel * _label, QTableWidget * _newTable)
This function allows the register of the UI elements.
Parameters
_newTree
_lineEdit
_label
_newTable
Definition at line 39 of file searchpairhelper.cpp.
References _nFoundItemsLabel, _searchLineEdit, _table, and _tree.
Referenced by TemplateDialog::initializeHelpers(), and SolverBasicDialog::initializeHelpers().
 {
     _tree= _newTree;
     _searchLineEdit = _lineEdit;
     _nFoundItemsLabel = _label;
     _table = _newTable;
 }
void SearchPairHelper::searchItems ()
This function searchs the items.
Definition at line 242 of file searchpairhelper.cpp.
References _nFoundItemsLabel, _searchedTermList, _searchLineEdit, _table, _totalFoundElements, _tree, expandParentChild(), SearchedPair::getIdChild(), SearchedPair::getIdParent(), hihghlightRowTree(), and searchTreeBySearchTerm().
Referenced by TemplateDialog::on_searchButton_clicked(), SolverBasicDialog::on_searchButton_clicked(), TemplateDialog::on_searchLineEdit_returnPressed(), and SolverBasicDialog::on_searchVariableNameLabelLineEdit_returnPressed().
 {
     // Reseting the values just in case the search is not cleared
     if (!_searchedTermList.isEmpty())
         _searchedTermList.clear();
     if (_totalFoundElements > 0)
         _totalFoundElements = 0;
     _tree->clearSelection();
     _table->clearSelection();
     //resetTable(); // HACERLO antes de llamar a search Items
     QString _searchTerm = _searchLineEdit->text();
     if (!_searchTerm.isEmpty())
     {
         searchTreeBySearchTerm(_searchTerm);
         if (!_searchedTermList.isEmpty())
         {
             _tree->clearSelection();
             for (int i = 0; i < _searchedTermList.count();i++)
             {
                 SearchedPair _pair = _searchedTermList.at(i);
                 hihghlightRowTree(_pair.getIdParent(),0,QModelIndex());
                 expandParentChild(_pair.getIdParent());
                 QModelIndex _idxParent = _tree->model()->index(_pair.getIdParent(),0,QModelIndex());
                 hihghlightRowTree(_pair.getIdChild(),0,_idxParent);
             }
         }
     }
    _nFoundItemsLabel->setText(QString::number(_totalFoundElements));
     _tree->setFocus();
 }
void SearchPairHelper::searchTreeBySearchTerm (QString _searchTerm) private
This fucntion allows to search in the tree model by a specific search term.
Parameters
_searchTerm
Definition at line 172 of file searchpairhelper.cpp.
References _searchedTermList, _solverManager, _totalFoundElements, _tree, SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), SolverVariableVO::getVariableName(), SearchedPair::setChildrenList(), SearchedPair::setIdChild(), and SearchedPair::setIdParent().
Referenced by searchItems().
 {
     if (!_searchedTermList.isEmpty())
         _searchedTermList.clear();
     int _totalParents = _tree->model()->rowCount(QModelIndex());
     for (int _idParent = 0; _idParent < _totalParents; _idParent++)
     {
         QModelIndex _idxParent = _tree->model()->index(_idParent,0,QModelIndex());
         // Getting the Child
         int _noChildren = _tree->model()->rowCount(_idxParent);
         for (int _idChild = 0; _idChild < _noChildren; _idChild++)
         {
             QModelIndex _idxChildren = _tree->model()->index(_idChild,0,_idxParent);
             QVariant _dataChild = _idxChildren.data(Qt::DisplayRole);
             QString _childName = _dataChild.toString();
             SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_childName);
             QList<SolverVariableVO> _list = _sectionVO.getSubsectionVarList();
             QList<int> _resultChildren;
             for (int i = 0; i< _list.count();i++)
             {
                 SolverVariableVO _solver = _list.at(i);
                 QString _nameVariable = _solver.getVariableName().toLower();
                 if (_nameVariable.contains(_searchTerm.toLower()))
                 {
                     _resultChildren.append(i);
                     _totalFoundElements ++;
                 }
             }
             if (!_resultChildren.isEmpty())
             {
                 SearchedPair _pairFound;
                 _pairFound.setIdParent(_idParent);
                 _pairFound.setIdChild(_idChild);
                 _pairFound.setChildrenList(_resultChildren);
                 _searchedTermList.append(_pairFound);
             }
         }
         }
 }
void SearchPairHelper::setSolverManager (SolverConfigManager * _manager)
Sets the solver Manager.
Parameters
_manager
Definition at line 84 of file searchpairhelper.cpp.
References _solverManager.
Referenced by SolverBasicDialog::initializeHelpers(), SolverBasicDialog::loadMenu(), TemplateDialog::setSolverConfigManager(), and SolverBasicDialog::updatePersonalizedMenu().
 {
     _solverManager = _manager;
 }
void SearchPairHelper::setTotalFoundElements (int _val)
Sets the total number of found elements.
Parameters
_val
Definition at line 74 of file searchpairhelper.cpp.
References _totalFoundElements.
Referenced by SolverBasicDialog::resetDialog().
 {
     _totalFoundElements = _val;
 }
Member Data Documentation
QLabel* SearchPairHelper::_nFoundItemsLabel private
Definition at line 39 of file searchpairhelper.h.
Referenced by clearSearchStatus(), registerUIElements(), and searchItems().
QList<SearchedPair> SearchPairHelper::_searchedTermList private
Definition at line 42 of file searchpairhelper.h.
Referenced by clearSearchStatus(), findParentChildinSearchList(), refreshHighlight(), refreshSearchInTree(), searchItems(), and searchTreeBySearchTerm().
QLineEdit* SearchPairHelper::_searchLineEdit private
Definition at line 38 of file searchpairhelper.h.
Referenced by clearSearchStatus(), registerUIElements(), and searchItems().
SolverConfigManager* SearchPairHelper::_solverManager private
Definition at line 41 of file searchpairhelper.h.
Referenced by searchTreeBySearchTerm(), and setSolverManager().
QTableWidget* SearchPairHelper::_table private
Definition at line 40 of file searchpairhelper.h.
Referenced by clearSearchStatus(), refreshSearchInTree(), registerUIElements(), and searchItems().
int SearchPairHelper::_totalFoundElements private
Definition at line 43 of file searchpairhelper.h.
Referenced by clearSearchStatus(), getTotalFoundElements(), searchItems(), SearchPairHelper(), searchTreeBySearchTerm(), and setTotalFoundElements().
QTreeView* SearchPairHelper::_tree private
Definition at line 37 of file searchpairhelper.h.
Referenced by clearSearchStatus(), expandParentChild(), hihghlightRowTree(), refreshHighlight(), registerTreeView(), registerUIElements(), searchItems(), and searchTreeBySearchTerm().
The documentation for this class was generated from the following files:
Searcher/searchpairhelper.h
Searcher/searchpairhelper.cpp