BBIPED Platform: SolverVarHelpVO Class Reference
SolverVarHelpVO Class Reference
#include <solvervarhelpvo.h>
Public Member Functions
SolverVarHelpVO ()
QString getDefinitionText ()
This function returns the definition content.
QString getDetailsText ()
This function returns the details associated in the help of the variable.
QString getValuesText ()
This function returns these values.
void setDefinitionText (QString _txt)
This function saves the Definition of the variable for the help section.
void setDetailsText (QString _txt)
This function stores the details associated in the help of the variable.
void setValuesText (QString _txt)
This function saves the values of the variable.
Private Attributes
QString _definitionTxt
QString _detailsTxt
QString _valuesTxt
Detailed Description
Definition at line 5 of file solvervarhelpvo.h.
Constructor & Destructor Documentation
SolverVarHelpVO::SolverVarHelpVO ()
Definition at line 23 of file solvervarhelpvo.cpp.
References _definitionTxt, _detailsTxt, and _valuesTxt.
 {
      _definitionTxt ="";
      _valuesTxt ="";
      _detailsTxt ="";
 }
Member Function Documentation
QString SolverVarHelpVO::getDefinitionText ()
This function returns the definition content.
Returns
QString
Definition at line 47 of file solvervarhelpvo.cpp.
References _definitionTxt.
Referenced by TemplateManager::createHelpElement(), and SolverVariableVO::getHelpContents().
 {
     return _definitionTxt;
 }
QString SolverVarHelpVO::getDetailsText ()
This function returns the details associated in the help of the variable.
Returns
QString
Definition at line 87 of file solvervarhelpvo.cpp.
References _detailsTxt.
Referenced by TemplateManager::createHelpElement(), and SolverVariableVO::getHelpContents().
 {
     return _detailsTxt;
 }
QString SolverVarHelpVO::getValuesText ()
This function returns these values.
Returns
QString
Definition at line 67 of file solvervarhelpvo.cpp.
References _valuesTxt.
Referenced by TemplateManager::createHelpElement(), and SolverVariableVO::getHelpContents().
 {
     return _valuesTxt;
 }
void SolverVarHelpVO::setDefinitionText (QString _txt)
This function saves the Definition of the variable for the help section.
Parameters
_txt
Definition at line 37 of file solvervarhelpvo.cpp.
References _definitionTxt.
Referenced by SolverConfigReader::createHelpElement().
 {
     _definitionTxt = _txt;
 }
void SolverVarHelpVO::setDetailsText (QString _txt)
This function stores the details associated in the help of the variable.
Parameters
_txt
Definition at line 77 of file solvervarhelpvo.cpp.
References _detailsTxt.
Referenced by SolverConfigReader::createHelpElement().
 {
     _detailsTxt = _txt;
 }
void SolverVarHelpVO::setValuesText (QString _txt)
This function saves the values of the variable.
Parameters
_txt
Definition at line 57 of file solvervarhelpvo.cpp.
References _valuesTxt.
Referenced by SolverConfigReader::createHelpElement().
 {
     _valuesTxt = _txt;
 }
Member Data Documentation
QString SolverVarHelpVO::_definitionTxt private
Definition at line 21 of file solvervarhelpvo.h.
Referenced by getDefinitionText(), setDefinitionText(), and SolverVarHelpVO().
QString SolverVarHelpVO::_detailsTxt private
Definition at line 23 of file solvervarhelpvo.h.
Referenced by getDetailsText(), setDetailsText(), and SolverVarHelpVO().
QString SolverVarHelpVO::_valuesTxt private
Definition at line 22 of file solvervarhelpvo.h.
Referenced by getValuesText(), setValuesText(), and SolverVarHelpVO().
The documentation for this class was generated from the following files:
Data/Solver/VO/solvervarhelpvo.h
Data/Solver/VO/solvervarhelpvo.cpp