BBIPED Platform: RuleEngine Class Reference
RuleEngine Class Reference
#include <ruleengine.h>
Public Member Functions
RuleEngine ()
void executeRule (VariableRule _rule)
This function gets the list of variables to be enabled/disabled and it analyses it in order to add it to the final list in order to change their visibility.
void setSolverConfigManager (SolverConfigManager *_manager)
Set the associated config manager (since it contains all the lists that are used in the views)
Private Member Functions
void buildVisibilityList (bool _visibility, QString _varName)
This functionadds the variable to the different lists according the visibility to be set.
void changeVisibility (QString _name, bool _visibilityVal)
void setVariableVisibility (QStringList _list, bool _visibility)
This fucntion builds the list of variables according its visibility.
void updateVisibilitySolverManager ()
This function passes the already computed lists to the solver config manager to update the visibilities according their nature.
Private Attributes
QStringList _activatedVariables
QStringList _disabledVariables
SolverConfigManager * _solverManager
Detailed Description
Definition at line 8 of file ruleengine.h.
Constructor & Destructor Documentation
RuleEngine::RuleEngine ()
Definition at line 27 of file ruleengine.cpp.
 {
 }
Member Function Documentation
void RuleEngine::buildVisibilityList (bool _visibility, QString _varName) private
This functionadds the variable to the different lists according the visibility to be set.
Parameters
_visibility
_varName
Definition at line 100 of file ruleengine.cpp.
References _activatedVariables, _disabledVariables, VARIABLE_TO_BE_DISABLED, and VARIABLE_TO_BE_ENABLED.
Referenced by setVariableVisibility().
 {
     switch(_visibility)
     {
         case VARIABLE_TO_BE_DISABLED:
             {
                 if ((!_activatedVariables.isEmpty()) &&
                     (_activatedVariables.contains(_varName)))
                         _activatedVariables.removeOne(_varName);
                 _disabledVariables.append(_varName);
             }
             break;
         case VARIABLE_TO_BE_ENABLED:
             {
                 if ( (!_disabledVariables.isEmpty()) &&
                     (_disabledVariables.contains(_varName)) )
                        _disabledVariables.removeOne(_varName);
                 _activatedVariables.append(_varName);
             }
             break;
     }
 }
void RuleEngine::changeVisibility (QString _name, bool _visibilityVal) private
void RuleEngine::executeRule (VariableRule _rule)
This function gets the list of variables to be enabled/disabled and it analyses it in order to add it to the final list in order to change their visibility.
Parameters
_rule
Definition at line 50 of file ruleengine.cpp.
References AbstractRule::getVariablesToBeDisabled(), AbstractRule::getVariablesToBeEnabled(), setVariableVisibility(), and updateVisibilitySolverManager().
 {
         QStringList _listToDisable = _rule.getVariablesToBeDisabled();
         QStringList _listToEnable = _rule.getVariablesToBeEnabled();
         if (!_listToDisable.isEmpty())
             setVariableVisibility(_listToDisable,false);
         if (!_listToEnable.isEmpty())
             setVariableVisibility(_listToEnable,true);
         updateVisibilitySolverManager();
 }
void RuleEngine::setSolverConfigManager (SolverConfigManager * _manager)
Set the associated config manager (since it contains all the lists that are used in the views)
Parameters
_manager
Definition at line 39 of file ruleengine.cpp.
References _solverManager.
 {
     _solverManager = _manager;
 }
void RuleEngine::setVariableVisibility (QStringList _list, bool _visibility) private
This fucntion builds the list of variables according its visibility.
Parameters
_list
_visibility
Definition at line 68 of file ruleengine.cpp.
References buildVisibilityList().
Referenced by executeRule().
 {
     for (int i = 0; i < _list.size(); i++)
     {
         QString _variableToSet = _list.at(i);
         buildVisibilityList(_visibility,_variableToSet);
     }
 }
void RuleEngine::updateVisibilitySolverManager () private
This function passes the already computed lists to the solver config manager to update the visibilities according their nature.
Definition at line 86 of file ruleengine.cpp.
References _activatedVariables, _disabledVariables, _solverManager, and SolverConfigManager::updateVisibility().
Referenced by executeRule().
 {
     _solverManager->updateVisibility(_disabledVariables,false);
     _solverManager->updateVisibility(_activatedVariables,true);
 }
Member Data Documentation
QStringList RuleEngine::_activatedVariables private
Definition at line 18 of file ruleengine.h.
Referenced by buildVisibilityList(), and updateVisibilitySolverManager().
QStringList RuleEngine::_disabledVariables private
Definition at line 17 of file ruleengine.h.
Referenced by buildVisibilityList(), and updateVisibilitySolverManager().
SolverConfigManager* RuleEngine::_solverManager private
Definition at line 19 of file ruleengine.h.
Referenced by setSolverConfigManager(), and updateVisibilitySolverManager().
The documentation for this class was generated from the following files:
Rule/ruleengine.h
Rule/ruleengine.cpp