BBIPED Platform: PreferencesManager Class Reference
PreferencesManager Class Reference
#include <preferencesmanager.h>
Public Member Functions
PreferencesManager ()
UserPreferencesData getUserPreferences ()
void saveUserPreferences (UserPreferencesData _newPreferences)
Private Member Functions
QStringList getProjectList (QXmlStreamReader *_xmlReader)
void getRecentProjects (QXmlStreamReader *_xmlReader, UserPreferencesData *_userData)
void getUserTemplatePreferences (QXmlStreamReader *_xmlReader, UserPreferencesData *_userData)
void getUserToolPreferences (QXmlStreamReader *_xmlReader, UserPreferencesData *_userData)
void getUserWarningPreferences (QXmlStreamReader *_xmlReader, UserPreferencesData *_userData)
QString getViewerInformation (QXmlStreamReader *_xmlReader, QString _keyName, QString _attName)
bool getWarningPreferences (QXmlStreamReader *_xmlReader, QString _warningType, QString _warningAtt)
void readPreferencesFile (UserPreferencesData *_userData)
void setSolverEngineInformation (QXmlStreamReader *_xmlReader, UserPreferencesData *_userData)
void writeRecentProjects (QXmlStreamWriter *_xmlWriter, UserPreferencesData _userData)
void writeTemplatePreferences (QXmlStreamWriter *_xmlWriter, UserPreferencesData _userData)
void writeUserPreferences (QXmlStreamWriter *_xmlWriter, UserPreferencesData _userData)
void writeWarningPreferences (QXmlStreamWriter *_xmlWriter, UserPreferencesData _userData)
Detailed Description
Definition at line 8 of file preferencesmanager.h.
Constructor & Destructor Documentation
PreferencesManager::PreferencesManager ()
Definition at line 30 of file preferencesmanager.cpp.
 {
 }
Member Function Documentation
QStringList PreferencesManager::getProjectList (QXmlStreamReader * _xmlReader) private
Parameters
_xmlReader
Returns
QStringList
Definition at line 340 of file preferencesmanager.cpp.
References StrEqual, XML_PREFERENCES_PROJECT_PATH_ATT_TAG, XML_PREFERENCES_PROJECT_TAG, and XML_PREFERENCES_RECENTPROJECTS_TAG.
Referenced by getRecentProjects().
 {
     bool _finish = false;
     QStringList _resultList;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_PROJECT_TAG ) == StrEqual))
         {
             if (_xmlReader->attributes().hasAttribute(XML_PREFERENCES_PROJECT_PATH_ATT_TAG))
                 _resultList.append(_xmlReader->attributes().value(XML_PREFERENCES_PROJECT_PATH_ATT_TAG).toString());
         }else
         {
             if  ((QString::compare(_xmlReader->name().toString(),XML_PREFERENCES_RECENTPROJECTS_TAG) == StrEqual)
                  && (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
     return _resultList;
 }
void PreferencesManager::getRecentProjects (QXmlStreamReader * _xmlReader, UserPreferencesData * _userData) private
Parameters
_xmlReader
_userData
Definition at line 317 of file preferencesmanager.cpp.
References getProjectList(), UserPreferencesData::setRecentProjectsList(), StrEqual, and XML_PREFERENCES_RECENTPROJECTS_TAG.
Referenced by readPreferencesFile().
 {
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if (token == QXmlStreamReader::StartDocument) continue;
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_RECENTPROJECTS_TAG ) == StrEqual))
         {
             _userData->setRecentProjectsList(getProjectList(_xmlReader));
             _finish = true;
         }
     }
 }
UserPreferencesData PreferencesManager::getUserPreferences ()
Returns
UserPreferencesData
Definition at line 41 of file preferencesmanager.cpp.
References readPreferencesFile().
Referenced by MainWindow::initializeUserPreferences().
 {
     UserPreferencesData _userData;
     readPreferencesFile(&_userData);
     return _userData;
 }
void PreferencesManager::getUserTemplatePreferences (QXmlStreamReader * _xmlReader, UserPreferencesData * _userData) private
Parameters
_xmlReader
_userData
Definition at line 227 of file preferencesmanager.cpp.
References UserPreferencesData::setTemplateConfigPath(), StrEqual, XML_PREFERENCES_TEMPLATE_PATH_ATT, and XML_PREFERENCES_TEMPLATE_TAG.
Referenced by readPreferencesFile().
 {
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_TEMPLATE_TAG ) == StrEqual))
         {
             if (_xmlReader->attributes().hasAttribute(XML_PREFERENCES_TEMPLATE_PATH_ATT))
                 _userData->setTemplateConfigPath(_xmlReader->attributes().value(XML_PREFERENCES_TEMPLATE_PATH_ATT).toString());
         }else{
             if ((QString::compare(_xmlReader->name().toString(),XML_PREFERENCES_TEMPLATE_TAG) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
 }
void PreferencesManager::getUserToolPreferences (QXmlStreamReader * _xmlReader, UserPreferencesData * _userData) private
Parameters
_xmlReader
_userData
Definition at line 371 of file preferencesmanager.cpp.
References getViewerInformation(), UserPreferencesData::setMeshViewerPath(), UserPreferencesData::setPostProcessorViewerPath(), setSolverEngineInformation(), StrEqual, XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_TAG, XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_TAG, and XML_PREFERENCES_USER_PREFERENCES_TAG.
Referenced by readPreferencesFile().
 {
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_USER_PREFERENCES_TAG ) == StrEqual))
         {
             _userData->setMeshViewerPath(getViewerInformation(_xmlReader,XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_TAG,
                                                               XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_PATH_ATT_TAG));
             _userData->setPostProcessorViewerPath(getViewerInformation(_xmlReader,
                                                                        XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_TAG,
                                                                        XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_PATH_ATT_TAG));
             setSolverEngineInformation(_xmlReader,_userData);
         }else
         {
             if ((QString::compare(_xmlReader->name().toString(),XML_PREFERENCES_USER_PREFERENCES_TAG) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
 }
void PreferencesManager::getUserWarningPreferences (QXmlStreamReader * _xmlReader, UserPreferencesData * _userData) private
Parameters
_xmlReader
_userData
Definition at line 253 of file preferencesmanager.cpp.
References getWarningPreferences(), UserPreferencesData::setShowCloseProjectWarning(), UserPreferencesData::setShowCloseWarning(), StrEqual, XML_PREFERENCES_WARNING_CLOSE_APP_SHOW_ATT, XML_PREFERENCES_WARNING_CLOSE_APP_TAG, XML_PREFERENCES_WARNING_CLOSE_PROJECT_SHOW_ATT, XML_PREFERENCES_WARNING_CLOSE_PROJECT_TAG, and XML_PREFERENCES_WARNING_TAG.
Referenced by readPreferencesFile().
 {
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_WARNING_TAG ) == StrEqual))
         {
             _userData->setShowCloseWarning(getWarningPreferences(_xmlReader,XML_PREFERENCES_WARNING_CLOSE_APP_TAG,
                                                               XML_PREFERENCES_WARNING_CLOSE_APP_SHOW_ATT) );
             _userData->setShowCloseProjectWarning(getWarningPreferences(_xmlReader,XML_PREFERENCES_WARNING_CLOSE_PROJECT_TAG,
                                                                      XML_PREFERENCES_WARNING_CLOSE_PROJECT_SHOW_ATT));
         }else{
             if ((QString::compare(_xmlReader->name().toString(),XML_PREFERENCES_WARNING_TAG) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
 }
QString PreferencesManager::getViewerInformation (QXmlStreamReader * _xmlReader, QString _keyName, QString _attName) private
Parameters
_xmlReader
_keyName
_attName
Returns
QString
Definition at line 404 of file preferencesmanager.cpp.
References StrEqual.
Referenced by getUserToolPreferences().
 {
     QString _result;
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), _keyName ) == StrEqual))
         {
             if (_xmlReader->attributes().hasAttribute(_attName))
                 _result = _xmlReader->attributes().value(_attName).toString();
         }else
         {
             if ( (QString::compare(_xmlReader->name().toString(),_keyName) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
     return _result;
 }
bool PreferencesManager::getWarningPreferences (QXmlStreamReader * _xmlReader, QString _warningType, QString _warningAtt) private
Parameters
_xmlReader
_warningType
_warningAtt
Returns
bool
Definition at line 284 of file preferencesmanager.cpp.
References StrEqual.
Referenced by getUserWarningPreferences().
 {
     bool _finish = false;
     bool _showWarning = true;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), _warningType ) == StrEqual))
         {
             if (_xmlReader->attributes().hasAttribute(_warningAtt))
             {
                 if (QString::compare(_xmlReader->attributes().value(_warningAtt).toString(), "NO") == StrEqual)
                     _showWarning = false;
             }
         }else
         {
             if ((QString::compare(_xmlReader->name().toString(),_warningType) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
     return _showWarning;
 }
void PreferencesManager::readPreferencesFile (UserPreferencesData * _userData) private
Parameters
_userData
Definition at line 199 of file preferencesmanager.cpp.
References getRecentProjects(), getUserTemplatePreferences(), getUserToolPreferences(), getUserWarningPreferences(), PREFERENCE_FILE_NAME, and saveUserPreferences().
Referenced by getUserPreferences().
 {
     QString _cPath = QDir(QCoreApplication::applicationDirPath()). filePath(PREFERENCE_FILE_NAME);
                 //QDir::currentPath() ).filePath(PREFERENCE_FILE_NAME);
     QFile _file(_cPath);
     bool _fileExist = true;
     _fileExist = _file.open(QIODevice::ReadOnly | QIODevice::Text);
     if (_fileExist)
     {
         QXmlStreamReader _xmlReader(&_file);
         getRecentProjects(&_xmlReader,_userData);
         getUserToolPreferences(&_xmlReader,_userData);
         getUserWarningPreferences(&_xmlReader,_userData);
         getUserTemplatePreferences(&_xmlReader,_userData);
     }else
         saveUserPreferences(*_userData);
     _file.close();
 }
void PreferencesManager::saveUserPreferences (UserPreferencesData _newPreferences)
Parameters
_newPreferences
Definition at line 55 of file preferencesmanager.cpp.
References PREFERENCE_FILE_NAME, writeRecentProjects(), writeTemplatePreferences(), writeUserPreferences(), writeWarningPreferences(), and XML_PREFERENCES_BBIPED_SESSION_ROOT_TAG.
Referenced by MainWindow::exitApplication(), and readPreferencesFile().
 {
     QString _cPath = QDir(QCoreApplication::applicationDirPath()).filePath(PREFERENCE_FILE_NAME);
                 //QDir::currentPath()).filePath(PREFERENCE_FILE_NAME);
     QFile _file(_cPath);
     bool _fileCreated = false;
     if (_file.exists())
         _file.remove();
      _fileCreated = _file.open(QIODevice::ReadWrite);
     if (_fileCreated)
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         // Writing the root element
         xmlWriter.writeStartElement(XML_PREFERENCES_BBIPED_SESSION_ROOT_TAG);
         // Writing the recent projects
         writeRecentProjects(&xmlWriter,_newPreferences);
         // Writing the user preferences
         writeUserPreferences(&xmlWriter,_newPreferences);
         // Writing the Warning Preferences
         writeWarningPreferences(&xmlWriter,_newPreferences);
         // Writing the Template Preferences
         writeTemplatePreferences(&xmlWriter,_newPreferences);
         // Ending the root element
         xmlWriter.writeEndElement();
         // Ending the document
         xmlWriter.writeEndDocument();
     }
     _file.close();
 }
void PreferencesManager::setSolverEngineInformation (QXmlStreamReader * _xmlReader, UserPreferencesData * _userData) private
Parameters
_xmlReader
_userData
Definition at line 434 of file preferencesmanager.cpp.
References UserPreferencesData::setMultizoneSolverEngineSelected(), UserPreferencesData::setUserDefinedSolverPath(), UserPreferencesData::setVirtualSolverEngineSelected(), StrEqual, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG, and XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG.
Referenced by getUserToolPreferences().
 {
     bool _finish = false;
     while ( (!_xmlReader->atEnd()) && (!_xmlReader->hasError()) && (!_finish))
     {
         QXmlStreamReader::TokenType token = _xmlReader->readNext();
         if ( (token == QXmlStreamReader::StartElement) &&
             (QString::compare(_xmlReader->name().toString(), XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG ) == StrEqual))
         {
             if (_xmlReader->attributes().hasAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG))
             {
                  QString _solverEnginePath =  _xmlReader->attributes().value(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG).toString();
                  if ( (!_solverEnginePath.isEmpty()) && (QString::compare(_solverEnginePath,"") != StrEqual) )
                     _userData->setUserDefinedSolverPath(_solverEnginePath);
             }
             if (_xmlReader->attributes().hasAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG) )
             {
                 QString  _valueSolverVirtualEngine =  _xmlReader->attributes().value(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG).toString();
                 if (QString::compare(_valueSolverVirtualEngine,"YES") == StrEqual)
                     _userData->setVirtualSolverEngineSelected(true);
             }
             if (_xmlReader->attributes().hasAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG) )
             {
                 QString  _valueSolverMultizoneEngine =  _xmlReader->attributes().value(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG).toString();
                 if (QString::compare(_valueSolverMultizoneEngine,"YES") == StrEqual)
                     _userData->setMultizoneSolverEngineSelected(true);
             }
         }else
         {
             if ( (QString::compare(_xmlReader->name().toString(),XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG) == StrEqual) &&
                     (token == QXmlStreamReader::EndElement))
                 _finish = true;
         }
     }
 }
void PreferencesManager::writeRecentProjects (QXmlStreamWriter * _xmlWriter, UserPreferencesData _userData) private
Parameters
_xmlWriter
_userData
Definition at line 140 of file preferencesmanager.cpp.
References UserPreferencesData::getRecentProjectsList(), XML_PREFERENCES_PROJECT_PATH_ATT_TAG, XML_PREFERENCES_PROJECT_TAG, and XML_PREFERENCES_RECENTPROJECTS_TAG.
Referenced by saveUserPreferences().
 {
     _xmlWriter->writeStartElement(XML_PREFERENCES_RECENTPROJECTS_TAG);
     QStringList _listProjects = _userData.getRecentProjectsList();
     if (!_listProjects.isEmpty())
         for (int i = 0; i < _listProjects.size();i++)
         {
             _xmlWriter->writeStartElement(XML_PREFERENCES_PROJECT_TAG);
             _xmlWriter->writeAttribute(XML_PREFERENCES_PROJECT_PATH_ATT_TAG,_listProjects.at(i));
             _xmlWriter->writeEndElement();
         }
     _xmlWriter->writeEndElement();
 }
void PreferencesManager::writeTemplatePreferences (QXmlStreamWriter * _xmlWriter, UserPreferencesData _userData) private
Parameters
_xmlWriter
_userData
Definition at line 125 of file preferencesmanager.cpp.
References UserPreferencesData::getTemplateConfigPath(), XML_PREFERENCES_TEMPLATE_PATH_ATT, and XML_PREFERENCES_TEMPLATE_TAG.
Referenced by saveUserPreferences().
 {
     _xmlWriter->writeStartElement(XML_PREFERENCES_TEMPLATE_TAG);
         _xmlWriter->writeAttribute(XML_PREFERENCES_TEMPLATE_PATH_ATT,_userData.getTemplateConfigPath());
         _xmlWriter->writeEndElement();
     _xmlWriter->writeEndElement();
 }
void PreferencesManager::writeUserPreferences (QXmlStreamWriter * _xmlWriter, UserPreferencesData _userData) private
Parameters
_xmlWriter
_userData
Definition at line 161 of file preferencesmanager.cpp.
References UserPreferencesData::getMeshViewerPath(), UserPreferencesData::getPostProcessorViewerPath(), UserPreferencesData::getUserDefinedSolverPath(), UserPreferencesData::isMultizoneSolverEngineSelected(), UserPreferencesData::isVirtualSolverEngineSelected(), XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_TAG, XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG, XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG, and XML_PREFERENCES_USER_PREFERENCES_TAG.
Referenced by saveUserPreferences().
 {
     _xmlWriter->writeStartElement(XML_PREFERENCES_USER_PREFERENCES_TAG);
     // Writing the Mesh Viewer Information
         _xmlWriter->writeStartElement(XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_TAG);
          _xmlWriter->writeAttribute(XML_PREFERENCES_USER_PREFERENCES_MESH_VIEWER_PATH_ATT_TAG,_userData.getMeshViewerPath());
         _xmlWriter->writeEndElement();
     // Writing the PostProcessor Viewer Information
         _xmlWriter->writeStartElement(XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_TAG);
          _xmlWriter->writeAttribute(XML_PREFERENCES_USER_PREFERENCES_POSTPROCESSOR_VIEWER_PATH_ATT_TAG,_userData.getPostProcessorViewerPath());
         _xmlWriter->writeEndElement();
     // Writing the Solver Engine Information
         _xmlWriter->writeStartElement(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_TAG);
             _xmlWriter->writeAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_PATH_ATT_TAG,_userData.getUserDefinedSolverPath());
             QString _virtualValue = "NO";
             if (_userData.isVirtualSolverEngineSelected())
                 _virtualValue = "YES";
             _xmlWriter->writeAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_VIRTUAL_ATT_TAG,_virtualValue);
             QString _multizoneValue = "NO";
             if (_userData.isMultizoneSolverEngineSelected())
                 _multizoneValue = "YES";
             _xmlWriter->writeAttribute(XML_PREFERENCES_USER_PREFERENCES_SOLVER_ENGINE_MULTIZONE_ATT_TAG,_multizoneValue);
         _xmlWriter->writeEndElement();
     _xmlWriter->writeEndElement();
 }
void PreferencesManager::writeWarningPreferences (QXmlStreamWriter * _xmlWriter, UserPreferencesData _userData) private
Parameters
_xmlWriter
_userData
Definition at line 100 of file preferencesmanager.cpp.
References UserPreferencesData::showCloseWarning(), XML_PREFERENCES_WARNING_CLOSE_APP_SHOW_ATT, XML_PREFERENCES_WARNING_CLOSE_APP_TAG, XML_PREFERENCES_WARNING_CLOSE_PROJECT_SHOW_ATT, XML_PREFERENCES_WARNING_CLOSE_PROJECT_TAG, and XML_PREFERENCES_WARNING_TAG.
Referenced by saveUserPreferences().
 {
     _xmlWriter->writeStartElement(XML_PREFERENCES_WARNING_TAG);
         QString _value("YES");
         if (!_userData.showCloseWarning())
             _value = "NO";
         _xmlWriter->writeStartElement(XML_PREFERENCES_WARNING_CLOSE_APP_TAG);
         _xmlWriter->writeAttribute(XML_PREFERENCES_WARNING_CLOSE_APP_SHOW_ATT,_value);
         _xmlWriter->writeEndElement();
         _value = "YES";
         if (!_userData.showCloseWarning())
             _value = "NO";
         _xmlWriter->writeStartElement(XML_PREFERENCES_WARNING_CLOSE_PROJECT_TAG);
         _xmlWriter->writeAttribute(XML_PREFERENCES_WARNING_CLOSE_PROJECT_SHOW_ATT,_value);
         _xmlWriter->writeEndElement();
     _xmlWriter->writeEndElement();
 }
The documentation for this class was generated from the following files:
Preferences/preferencesmanager.h
Preferences/preferencesmanager.cpp