BBIPED Platform: SolverSectionVO Class Reference
SolverSectionVO Class Reference
#include <solversectionvo.h>
Public Member Functions
SolverSectionVO ()
Constructor.
~SolverSectionVO ()
Destructor.
QString getSectionName ()
Get associated Section Name.
QString getSubsectionName ()
Get Associated Subsection Name.
QList< SolverVariableVO > getSubsectionVarList ()
returns the associated variable list
void setSectionName (QString _name)
Set the Section Name.
void setSubsectionName (QString _name)
Set Subsection name.
void setSubsectionVarList (QList< SolverVariableVO > _list)
Set Associated list of variables of a Subsection.
Private Attributes
QString _sectionName
QString _subsectionName
QList< SolverVariableVO > _variableList
Detailed Description
Definition at line 7 of file solversectionvo.h.
Constructor & Destructor Documentation
SolverSectionVO::SolverSectionVO ()
Constructor.
Definition at line 23 of file solversectionvo.cpp.
References _sectionName, and _subsectionName.
 {
     _sectionName = "";
     _subsectionName =  "";
 }
SolverSectionVO::~SolverSectionVO ()
Destructor.
Definition at line 33 of file solversectionvo.cpp.
 {
 }
Member Function Documentation
QString SolverSectionVO::getSectionName ()
Get associated Section Name.
Returns
QString
Definition at line 54 of file solversectionvo.cpp.
References _sectionName.
Referenced by SolverSectionDAO::findSection(), SolverSectionDAO::findSectionNameBySubSectionName(), and SolverSectionDAO::findSubSectionNamesBySectionName().
 {
     return _sectionName;
 }
QString SolverSectionVO::getSubsectionName ()
Get Associated Subsection Name.
Returns
QString
Definition at line 74 of file solversectionvo.cpp.
References _subsectionName.
Referenced by TemplateDialog::addVariable(), SolverSectionDAO::findSectionNameBySubSectionName(), SolverSectionDAO::findSubSection(), and SolverSectionDAO::findSubSectionNamesBySectionName().
 {
     return _subsectionName;
 }
QList< SolverVariableVO > SolverSectionVO::getSubsectionVarList ()
returns the associated variable list
Returns
QList<SolverVariableVO>
Definition at line 94 of file solversectionvo.cpp.
References _variableList.
Referenced by TemplateDialog::addVariable(), SolverBasicDialog::buildAllToolTips(), VirtualRotatingDialog::buildAssociatedHelp(), MeshDialog::buildHelpContent(), MeshDialog::fillTable(), SolverBasicDialog::fillTable(), TemplateDialog::fillTableVarToSelect(), SolverSectionDAO::findValueNameByVariableName(), SolverSectionDAO::findVariableByFileName(), SolverSectionDAO::findVariableByValueName(), SolverSectionDAO::findVariableNameByValueName(), VirtualCurveDialog::generateHelpDialog(), SolverBasicDialog::getAssociatedFileNameValue(), SolverSectionDAO::getOptionalVariables(), TemplateManager::getVariables(), MeshDialog::initializeMeshValues(), SolverSectionDAO::isDefaultValueByFileName(), SolverBasicDialog::launchSpecificWindow(), TemplateDialog::on_selectedVariablesTableWidget_cellClicked(), SolverBasicDialog::on_solverVariablesTable_cellClicked(), TemplateDialog::on_variablesToSelectTableWidget_cellClicked(), MeshDialog::restoreValues(), SearchPairHelper::searchTreeBySearchTerm(), TemplateDialog::updateSelectedVariableCheckBox(), SolverConfigMenuHelper::updateTableWithUserValues(), and SolverConfigManager::updateVisibility().
 {
     return _variableList;
 }
void SolverSectionVO::setSectionName (QString _name)
Set the Section Name.
Parameters
_name
Definition at line 44 of file solversectionvo.cpp.
References _sectionName.
Referenced by SolverConfigReader::createSectionNode().
 {
     _sectionName = _name;
 }
void SolverSectionVO::setSubsectionName (QString _name)
Set Subsection name.
Parameters
_name
Definition at line 64 of file solversectionvo.cpp.
References _subsectionName.
Referenced by SolverSectionDAO::createSectionElement(), and SolverConfigReader::createSectionNode().
 {
     _subsectionName = _name;
 }
void SolverSectionVO::setSubsectionVarList (QList< SolverVariableVO > _list)
Set Associated list of variables of a Subsection.
Parameters
_list
Definition at line 84 of file solversectionvo.cpp.
References _variableList.
Referenced by SolverSectionDAO::createSectionElement(), and SolverConfigReader::createSectionNode().
 {
     _variableList = _list;
 }
Member Data Documentation
QString SolverSectionVO::_sectionName private
Definition at line 26 of file solversectionvo.h.
Referenced by getSectionName(), setSectionName(), and SolverSectionVO().
QString SolverSectionVO::_subsectionName private
Definition at line 27 of file solversectionvo.h.
Referenced by getSubsectionName(), setSubsectionName(), and SolverSectionVO().
QList<SolverVariableVO> SolverSectionVO::_variableList private
Definition at line 28 of file solversectionvo.h.
Referenced by getSubsectionVarList(), and setSubsectionVarList().
The documentation for this class was generated from the following files:
Data/Solver/VO/solversectionvo.h
Data/Solver/VO/solversectionvo.cpp