BBIPED Platform: ToolsHelper Class Reference
ToolsHelper Class Reference
#include <toolshelper.h>
Public Member Functions
ToolsHelper ()
void createAutomaticMesh (QTextEdit *_textEdit, ProjectData _projectData, UserPreferencesData _userPreferencesData)
void createAutomaticMeshWithOptimization (ProjectData _projectData, UserPreferencesData _userPreferencesData)
Private Member Functions
void launchSalomeWarning ()
Detailed Description
Definition at line 8 of file toolshelper.h.
Constructor & Destructor Documentation
ToolsHelper::ToolsHelper ()
Definition at line 30 of file toolshelper.cpp.
 {
 }
Member Function Documentation
void ToolsHelper::createAutomaticMesh (QTextEdit * _textEdit, ProjectData _projectData, UserPreferencesData _userPreferencesData)
Parameters
_textEdit
_projectData
_userPreferencesData
Definition at line 56 of file toolshelper.cpp.
References UserPreferencesData::getMeshViewerPath(), ProjectData::getProjectFileName(), ProjectData::getProjectPath(), SalomeTemplateDialog::initializeDialog(), launchSalomeWarning(), SalomeTemplateDialog::registerConsole(), SalomeTemplateDialog::setBBIPEDPath(), SalomeTemplateDialog::setMeshViewerPath(), SalomeTemplateDialog::setProjectName(), and SalomeTemplateDialog::setProjectPath().
Referenced by MainWindow::on_actionLoad_Templates_triggered().
 {
     if (_userPreferencesData.getMeshViewerPath().isEmpty())
     {
         launchSalomeWarning();
         return;
     }
     SalomeTemplateDialog _salomeTemplateDialog;
     _salomeTemplateDialog.setMeshViewerPath(_userPreferencesData.getMeshViewerPath());
     _salomeTemplateDialog.setBBIPEDPath(QCoreApplication::applicationDirPath());
     _salomeTemplateDialog.registerConsole(_textEdit);
     _salomeTemplateDialog.setProjectPath(_projectData.getProjectPath());
     _salomeTemplateDialog.setProjectName(_projectData.getProjectFileName());
     _salomeTemplateDialog.initializeDialog();
     _salomeTemplateDialog.exec();
 }
void ToolsHelper::createAutomaticMeshWithOptimization (ProjectData _projectData, UserPreferencesData _userPreferencesData)
Parameters
_projectData
_userPreferencesData
Definition at line 82 of file toolshelper.cpp.
References UserPreferencesData::getMeshViewerPath(), ProjectData::getProjectFileName(), ProjectData::getProjectPath(), SalomeOptimizationDialog::initializeDialog(), launchSalomeWarning(), SalomeOptimizationDialog::setMeshViewerPath(), SalomeOptimizationDialog::setProjectName(), and SalomeOptimizationDialog::setProjectPath().
Referenced by MainWindow::on_actionAutomatic_Optimization_triggered().
 {
     if (_userPreferencesData.getMeshViewerPath().isEmpty())
     {
         launchSalomeWarning();
         return;
     }
     SalomeOptimizationDialog _salomeOptDialog;
     _salomeOptDialog.setMeshViewerPath(_userPreferencesData.getMeshViewerPath());
     _salomeOptDialog.setProjectPath(_projectData.getProjectPath());
     QFileInfo _fileInfo(_projectData.getProjectFileName());
     _salomeOptDialog.setProjectName(_fileInfo.baseName());
     _salomeOptDialog.initializeDialog();
     _salomeOptDialog.exec();
 }
void ToolsHelper::launchSalomeWarning () private
Definition at line 40 of file toolshelper.cpp.
References ShowMessageHelper::showWarningMessage().
Referenced by createAutomaticMesh(), and createAutomaticMeshWithOptimization().
 {
     ShowMessageHelper _showMessage;
      _showMessage.showWarningMessage("Problem with Salome Configuration",
                             "Salome is not properly configured, please go to Preferences and set up the path to the Salome binaries");
     return;
 }
The documentation for this class was generated from the following files:
WindowHelper/Menu/MenuHelpers/toolshelper.h
WindowHelper/Menu/MenuHelpers/toolshelper.cpp