BBIPED Platform: SalomeTemplateDialog Class Reference
SalomeTemplateDialog Class Reference
#include <salometemplatedialog.h>
Public Member Functions
SalomeTemplateDialog (QWidget *parent=0)
~SalomeTemplateDialog ()
QString getProjectName ()
QString getProjectPath ()
void initializeDialog ()
void registerConsole (QTextEdit *_editor)
void setBBIPEDPath (QString _path)
void setMeshViewerPath (QString _salomePath)
void setProjectName (QString _name)
void setProjectPath (QString _path)
Private Types
enum
Private Slots
void changedComboSlot (QString _position)
void on_cancelButton_clicked ()
void on_createMeshButton_clicked ()
void on_deleteTemplateButton_clicked ()
void on_dumpGeometryButton_clicked ()
void on_dumpMeshButton_clicked ()
void on_helpButton_clicked ()
void on_reset2DefaultButton_clicked ()
void on_saveAsButton_clicked ()
void on_saveButton_clicked ()
void on_templateSelComboBox_currentIndexChanged (int index)
void textChangedSlot (QString _position)
Private Member Functions
void addRow (SalomeVariableData _var)
void addSignals ()
SalomeTemplateData createTemplateFromUserValues (QString _templateName, QString _templateFileName)
void fillTable (int _templatePosition)
int getPosMenu ()
bool isUserTemplateSelected (int _pos)
void loadTemplateMenu ()
void refreshComboTemplates (QString _templateName)
void registerHelpers ()
void resetValuesToDefault ()
void restoreTemplateDefaults (int _tempId)
void saveData ()
void updateTemplateValues (SalomeTemplateData *_template)
bool valueChangedByUser (int _rowPos, QString _oldValue)
Private Attributes
QString _bbipedPath
bool _isLoadingTable
bool _isUserDefinedTemplate
QString _meshViewerPath
bool _needToSaveUserChanges
QString _projectName
QString _projectPath
QTextEdit * _regEditor
QString _selectedTemplate
QSignalMapper * _signalMapperTxtEdit
QtableUtil _tableHelper
SalomeTemplateManager _templateManager
Ui::SalomeTemplateDialog * ui
Detailed Description
Definition at line 15 of file salometemplatedialog.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
variableChangedCol
variableNameCol
variableValueCol
Definition at line 80 of file salometemplatedialog.h.
         {
         variableChangedCol = 0,
         variableNameCol = 1,
         variableValueCol = 2
     };
Constructor & Destructor Documentation
SalomeTemplateDialog::SalomeTemplateDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 33 of file salometemplatedialog.cpp.
References _bbipedPath, _isLoadingTable, _isUserDefinedTemplate, _meshViewerPath, _needToSaveUserChanges, _signalMapperTxtEdit, registerHelpers(), and ui.
                                                           :
     QDialog(parent),
     ui(new Ui::SalomeTemplateDialog)
 {
        ui->setupUi(this);
        registerHelpers();
        _signalMapperTxtEdit = new QSignalMapper(this);
        _isLoadingTable = true;
        _isUserDefinedTemplate = false;
        _needToSaveUserChanges = false;
        _meshViewerPath = "";
        _bbipedPath = "";
 }
SalomeTemplateDialog::~SalomeTemplateDialog ()
Definition at line 51 of file salometemplatedialog.cpp.
References _bbipedPath, _meshViewerPath, _projectName, _projectPath, and ui.
 {
     delete ui;
     _projectPath = "";
     _projectName = "";
     _meshViewerPath = "";
     _bbipedPath = "";
 }
Member Function Documentation
void SalomeTemplateDialog::addRow (SalomeVariableData _var) private
Parameters
_pos
_var
Definition at line 171 of file salometemplatedialog.cpp.
References _tableHelper, QtableUtil::addChangedColumn(), QtableUtil::addEditText(), QtableUtil::addNonEditableText(), SalomeVariableData::getCurrentValue(), SalomeVariableData::getDefaultValue(), SalomeVariableData::getName(), StrEqual, ui, variableChangedCol, variableNameCol, and variableValueCol.
Referenced by fillTable().
 {
    // QtableUtil _tableHelper;
     int _lastPos = ui->templateVarTable->rowCount();
     ui->templateVarTable->insertRow(_lastPos);
     ui->templateVarTable->setItem(_lastPos,variableChangedCol,_tableHelper.addChangedColumn());
     ui->templateVarTable->setItem(_lastPos,variableNameCol,_tableHelper.addNonEditableText(_var.getName()));
     ui->templateVarTable->setCellWidget(_lastPos,variableValueCol,_tableHelper.addEditText(_var.getCurrentValue()));
     //ui->templateVarTable->setItem(_lastPos,variableOptimizeCol,_tableHelper.addSelectableCheckColumn());
     // Updating the values of the checkbox
     if (QString::compare(_var.getDefaultValue(),_var.getCurrentValue()) != StrEqual)
         ui->templateVarTable->item(_lastPos,variableChangedCol)->setCheckState(Qt::Checked);
     /*if (QString::compare(_var.getOptimizedValue(),"YES") == StrEqual)
     {
         ui->templateVarTable->item(_lastPos,variableOptimizeCol)->setCheckState(Qt::Checked);
         ui->templateVarTable->item(_lastPos,variableChangedCol)->setCheckState(Qt::Checked);
     }*/
 }
void SalomeTemplateDialog::addSignals () private
Definition at line 500 of file salometemplatedialog.cpp.
References _signalMapperTxtEdit, textChangedSlot(), ui, and variableValueCol.
Referenced by on_templateSelComboBox_currentIndexChanged().
 {
     bool _foundLineEdit = false;
     int _tableSize = ui->templateVarTable->rowCount();
     if (_tableSize <= 0)
         return;
     for (int i = 0; i < _tableSize; i++)
     {
         QLineEdit * _lineEdit =  qobject_cast<QLineEdit *> (ui->templateVarTable->cellWidget(i,variableValueCol));
         if (_lineEdit)
         {
             connect(_lineEdit,SIGNAL(editingFinished()),_signalMapperTxtEdit,SLOT(map()),Qt::UniqueConnection);
             _signalMapperTxtEdit->setMapping(_lineEdit,QString("%1").arg(i));
             _foundLineEdit = true;
         }
     }
     if (_foundLineEdit)
         connect(_signalMapperTxtEdit, SIGNAL(mapped(const QString &)),this, SLOT(textChangedSlot(const QString &)),Qt::UniqueConnection);
 }
void SalomeTemplateDialog::changedComboSlot (QString _position) private slot
Parameters
_position
Definition at line 547 of file salometemplatedialog.cpp.
References _isLoadingTable, _needToSaveUserChanges, ui, and variableChangedCol.
 {
     if (!_isLoadingTable)
     {
        int _row = _position.toInt();
        ui->templateVarTable->item(_row,variableChangedCol)->setCheckState(Qt::Checked);
        _needToSaveUserChanges = true;
     }
 }
SalomeTemplateData SalomeTemplateDialog::createTemplateFromUserValues (QString _templateName, QString _templateFileName) private
Parameters
_templateName
_templateFileName
Returns
SalomeTemplateData
Definition at line 360 of file salometemplatedialog.cpp.
References _templateManager, SalomeVariableData::getDefaultValue(), SalomeVariableData::getFileName(), getPosMenu(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), SalomeTemplateData::getVariableList(), SalomeVariableData::setCurrentValue(), SalomeVariableData::setDefaultValue(), SalomeVariableData::setFileName(), SalomeVariableData::setName(), SalomeVariableData::setOptimizedValue(), SalomeTemplateData::setTemplateFileName(), SalomeTemplateData::setTemplateName(), SalomeTemplateData::setVariableList(), ui, variableNameCol, and variableValueCol.
Referenced by on_saveAsButton_clicked().
 {
     SalomeTemplateData _templateResult;
     _templateResult.setTemplateName(_templateName);
     _templateResult.setTemplateFileName(_templateFileName);
     QList<SalomeVariableData> _variableList;
     int _varSize = ui->templateVarTable->rowCount();
     //-----------------------------------
     // The filename variables are the same that those coming from the original template the user modified
     int _posOriginalTemplate = getPosMenu();
     int _indexPos = ui->templateSelComboBox->currentIndex();
     SalomeTemplateData _origTemplate;
     if (_indexPos > _templateManager.getTemplates().size())
         _origTemplate = _templateManager.getUserTemplates().at(_posOriginalTemplate);
     else
         _origTemplate = _templateManager.getTemplates().at(_posOriginalTemplate);
     //-----------------------------------
     for (int i = 0; i < _varSize;i++)
     {
         QString _varName = ui->templateVarTable->item(i,variableNameCol)->text();
         QString _cvalue = ((QLineEdit *) ui->templateVarTable->cellWidget(i,variableValueCol) )->text();
         SalomeVariableData _origVariableData = _origTemplate.getVariableList().at(i);
         QString _isOptimized = "NO";
        // if (ui->templateVarTable->item(i,variableOptimizeCol)->checkState() == Qt::Checked)
        //     _isOptimized = "YES";
         SalomeVariableData _varData;
         _varData.setName(_varName);
         _varData.setFileName(_origVariableData.getFileName());
         _varData.setDefaultValue(_origVariableData.getDefaultValue());
         _varData.setCurrentValue(_cvalue);
         _varData.setOptimizedValue(_isOptimized);
         _variableList.push_back(_varData);
     }
     _templateResult.setVariableList(_variableList);
     return _templateResult;
 }
void SalomeTemplateDialog::fillTable (int _templatePosition) private
Parameters
_templatePosition
Definition at line 137 of file salometemplatedialog.cpp.
References _isLoadingTable, _selectedTemplate, _templateManager, addRow(), getPosMenu(), SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), SalomeTemplateData::getVariableList(), and ui.
Referenced by on_templateSelComboBox_currentIndexChanged().
 {
     _isLoadingTable = true;
     if ((_selectedTemplate.isEmpty()) || (_templatePosition == -1) )
         return;
     int _templateNo = getPosMenu();
     if (_templateNo == -1)
         return;
     SalomeTemplateData _templateData;
     int _sizePredefinedTemplates = _templateManager.getTemplateNameList().size();
     // Checking if it is a predefined template or an user defined one
     if ( (_templatePosition <= _sizePredefinedTemplates ) && (_templateNo < _templateManager.getTemplates().size()) )
         _templateData = _templateManager.getTemplates().at(_templateNo);
     if ( (_templatePosition > _sizePredefinedTemplates ) && (_templateNo < _templateManager.getUserTemplates().size()) )
         _templateData = _templateManager.getUserTemplates().at(_templateNo);
     QList<SalomeVariableData> _variableList = _templateData.getVariableList();
     for (int i = 0; i < _variableList.size();i++)
         addRow(_variableList.at(i));
     ui->templateVarTable->resizeColumnsToContents();
     ui->templateVarTable->show();
     _isLoadingTable = false;
 }
int SalomeTemplateDialog::getPosMenu () private
Returns
int
Definition at line 196 of file salometemplatedialog.cpp.
References _selectedTemplate, _templateManager, SalomeTemplateManager::getTemplateNameList(), and SalomeTemplateManager::getUserTemplateNameList().
Referenced by createTemplateFromUserValues(), fillTable(), on_reset2DefaultButton_clicked(), resetValuesToDefault(), and saveData().
 {
    int _result = -1;
    if (!_selectedTemplate.isEmpty())
    {
        QStringList _listTemplates = _templateManager.getTemplateNameList();
        if (_listTemplates.contains(_selectedTemplate,Qt::CaseSensitive))
             return _listTemplates.indexOf(_selectedTemplate,0);
        _listTemplates.clear();
        _listTemplates = _templateManager.getUserTemplateNameList();
        if (_listTemplates.contains(_selectedTemplate,Qt::CaseSensitive))
            return _listTemplates.indexOf(_selectedTemplate,0) ;
    }
    return _result;
 }
QString SalomeTemplateDialog::getProjectName ()
Returns
QString
Definition at line 107 of file salometemplatedialog.cpp.
References _projectName.
 {
     return _projectName ;
 }
QString SalomeTemplateDialog::getProjectPath ()
Returns
QString
Definition at line 87 of file salometemplatedialog.cpp.
References _projectPath.
 {
     return _projectPath;
 }
void SalomeTemplateDialog::initializeDialog ()
Definition at line 74 of file salometemplatedialog.cpp.
References _templateManager, SalomeTemplateManager::isInitialized(), SalomeTemplateManager::loadTemplate(), and loadTemplateMenu().
Referenced by ToolsHelper::createAutomaticMesh().
 {
     if (!_templateManager.isInitialized())
         _templateManager.loadTemplate();
     loadTemplateMenu();
 }
bool SalomeTemplateDialog::isUserTemplateSelected (int _pos) private
Parameters
_pos
Returns
bool
Definition at line 488 of file salometemplatedialog.cpp.
References _templateManager, and SalomeTemplateManager::getTemplateNameList().
Referenced by on_reset2DefaultButton_clicked(), and on_templateSelComboBox_currentIndexChanged().
 {
     if (_pos > _templateManager.getTemplateNameList().size())
        return true;
     return false;
 }
void SalomeTemplateDialog::loadTemplateMenu () private
Definition at line 127 of file salometemplatedialog.cpp.
References refreshComboTemplates().
Referenced by initializeDialog().
 {
     refreshComboTemplates("");
 }
void SalomeTemplateDialog::on_cancelButton_clicked () private slot
Definition at line 406 of file salometemplatedialog.cpp.
 {
     close();
 }
void SalomeTemplateDialog::on_createMeshButton_clicked () private slot
Definition at line 415 of file salometemplatedialog.cpp.
References _bbipedPath, _isUserDefinedTemplate, _meshViewerPath, _needToSaveUserChanges, _projectName, _projectPath, _selectedTemplate, _templateManager, SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplateNameList(), SalomeTemplateManager::getUserTemplates(), SalomeTemplateData::isEmpty(), saveData(), SalomeToolCreateMeshDialog::setBBIPEDPath(), SalomeToolCreateMeshDialog::setProjectName(), SalomeToolCreateMeshDialog::setProjectPath(), SalomeToolCreateMeshDialog::setSalomeMeshViewerPath(), and SalomeToolCreateMeshDialog::setTemplateData().
 {
     if (_selectedTemplate.isEmpty())
         return;
      // Check if the changes need to be saved
     if (_needToSaveUserChanges)
         saveData();
     int _posTemplate = -1;
     if (_isUserDefinedTemplate)
         _posTemplate = _templateManager.getUserTemplateNameList().indexOf(_selectedTemplate);
     else
         _posTemplate = _templateManager.getTemplateNameList().indexOf(_selectedTemplate);
     SalomeTemplateData _template;
     if (_posTemplate != -1)
     {
        QList<SalomeTemplateData> _list;
         if (_isUserDefinedTemplate)
             _list = _templateManager.getUserTemplates();
        else
             _list = _templateManager.getTemplates();
          _template = _list.at(_posTemplate);
     }
     if (_template.isEmpty())
         return;
     // Creating the Dialog for Meshing names and executing the phyton file
     SalomeToolCreateMeshDialog _createMeshDialog;
     _createMeshDialog.setSalomeMeshViewerPath(_meshViewerPath);
     _createMeshDialog.setBBIPEDPath(_bbipedPath);
     _createMeshDialog.setProjectPath(_projectPath);
     //_createMeshDialog.registerTextEditor(_regEditor);
     QFileInfo _fileInfo(_projectName);
     _createMeshDialog.setProjectName(_fileInfo.baseName());
     _createMeshDialog.setTemplateData(_template);
     close();
     _createMeshDialog.exec();
 }
void SalomeTemplateDialog::on_deleteTemplateButton_clicked () private slot
Definition at line 232 of file salometemplatedialog.cpp.
References _selectedTemplate, _tableHelper, _templateManager, SalomeTemplateManager::deleteUserDefinedTempalte(), QtableUtil::isInitialized(), refreshComboTemplates(), and QtableUtil::resetTable().
 {
     _templateManager.deleteUserDefinedTempalte(_selectedTemplate);
     refreshComboTemplates("");
     if(_tableHelper.isInitialized())
         _tableHelper.resetTable();
 }
void SalomeTemplateDialog::on_dumpGeometryButton_clicked () private slot
Definition at line 586 of file salometemplatedialog.cpp.
 {
     // TODO
 }
void SalomeTemplateDialog::on_dumpMeshButton_clicked () private slot
Definition at line 577 of file salometemplatedialog.cpp.
 {
     // TODO
 }
void SalomeTemplateDialog::on_helpButton_clicked () private slot
Definition at line 220 of file salometemplatedialog.cpp.
References HelpDialog::setHelpText().
 {
     HelpDialog _helpDialog;
     _helpDialog.setHelpText("TODO Help");
     _helpDialog.exec();
 }
void SalomeTemplateDialog::on_reset2DefaultButton_clicked () private slot
Definition at line 596 of file salometemplatedialog.cpp.
References getPosMenu(), isUserTemplateSelected(), and resetValuesToDefault().
 {
     QMessageBox _messageBox;
     int _reset = 0;
     int _posSelTemplate = getPosMenu();
     if (_posSelTemplate < 0)
         return;
     if (isUserTemplateSelected(_posSelTemplate)) // REVISAR
     {
         _messageBox.setText("User defined templates cannot be reseted to default.");
         _messageBox.exec();
         return;
     }else{
         _messageBox.setText("You are about to remove all your configuration to the default values");
         _messageBox.setInformativeText(" Are you sure?");
         _messageBox.setStandardButtons(QMessageBox::Yes|QMessageBox::No);
         _reset = _messageBox.exec();
     }
     if (_reset == QMessageBox::Yes)
         resetValuesToDefault();
 }
void SalomeTemplateDialog::on_saveAsButton_clicked () private slot
Definition at line 312 of file salometemplatedialog.cpp.
References _needToSaveUserChanges, _selectedTemplate, _templateManager, createTemplateFromUserValues(), SalomeTemplateManager::getTemplateFileNameByTemplateName(), AskForTemplateNameDialog::getTemplateName(), SalomeTemplateManager::getUserTemplates(), refreshComboTemplates(), ui, and SalomeTemplateManager::updateUserTemplateValues().
 {
     if (_selectedTemplate.isEmpty())
         return;
     AskForTemplateNameDialog _askForTemplateNameDialog;
     _askForTemplateNameDialog.exec();
     QString _templateName = _askForTemplateNameDialog.getTemplateName();
     if (_templateName.isEmpty())
         return;
 //    QString _templateFileName = _askForTemplateNameDialog.getTemplateFileName();
     QString _templateFileName = _templateManager.getTemplateFileNameByTemplateName(_selectedTemplate);
     SalomeTemplateData _templateToSave  = createTemplateFromUserValues(_templateName,_templateFileName);
     QList<SalomeTemplateData> _templateList;
     _templateList = _templateManager.getUserTemplates();
     _templateList.push_back(_templateToSave);
     _templateManager.updateUserTemplateValues(_templateList);
     ui->templateSelComboBox->clear();
     refreshComboTemplates(_templateName);
     _needToSaveUserChanges = false;
 }
void SalomeTemplateDialog::on_saveButton_clicked () private slot
Definition at line 244 of file salometemplatedialog.cpp.
References _selectedTemplate, and saveData().
 {
     if (_selectedTemplate.isEmpty())
         return;
     saveData();
 }
void SalomeTemplateDialog::on_templateSelComboBox_currentIndexChanged (int index) private slot
Parameters
index
Definition at line 464 of file salometemplatedialog.cpp.
References _isUserDefinedTemplate, _selectedTemplate, _tableHelper, addSignals(), fillTable(), QtableUtil::isInitialized(), isUserTemplateSelected(), QtableUtil::resetTable(), and ui.
 {
     _selectedTemplate = ui->templateSelComboBox->itemText(index);
     if (isUserTemplateSelected(index))
     {
         _isUserDefinedTemplate = true;
         ui->deleteTemplateButton->setEnabled(true);
     }else
     {
         _isUserDefinedTemplate = false;
         ui->deleteTemplateButton->setEnabled(false);
     }
     if(_tableHelper.isInitialized())
         _tableHelper.resetTable();
     fillTable(index);
     addSignals();
 }
void SalomeTemplateDialog::refreshComboTemplates (QString _templateName) private
Parameters
_templateName
Definition at line 342 of file salometemplatedialog.cpp.
References _selectedTemplate, _templateManager, SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getUserTemplateNameList(), and ui.
Referenced by loadTemplateMenu(), on_deleteTemplateButton_clicked(), and on_saveAsButton_clicked().
 {
     ui->templateSelComboBox->clear();
     QStringList _templateNameList;
     _templateNameList.append("");
     _templateNameList.append(_templateManager.getTemplateNameList());
     _templateNameList.append(_templateManager.getUserTemplateNameList());
    ui->templateSelComboBox->addItems(_templateNameList);
    _selectedTemplate = _templateName;
 }
void SalomeTemplateDialog::registerConsole (QTextEdit * _editor)
Parameters
_editor
Definition at line 703 of file salometemplatedialog.cpp.
References _regEditor.
Referenced by ToolsHelper::createAutomaticMesh().
 {
     _regEditor = _editor;
 }
void SalomeTemplateDialog::registerHelpers () private
Definition at line 65 of file salometemplatedialog.cpp.
References _tableHelper, QtableUtil::registerTable(), and ui.
Referenced by SalomeTemplateDialog().
 {
     _tableHelper.registerTable(ui->templateVarTable);
 }
void SalomeTemplateDialog::resetValuesToDefault () private
Definition at line 624 of file salometemplatedialog.cpp.
References _needToSaveUserChanges, _templateManager, SalomeVariableData::getDefaultValue(), getPosMenu(), SalomeTemplateManager::getTemplates(), SalomeTemplateData::getVariableList(), restoreTemplateDefaults(), ui, valueChangedByUser(), variableChangedCol, and variableValueCol.
Referenced by on_reset2DefaultButton_clicked().
 {
     // Reset the values
     int _posSelTemplate = getPosMenu();
     if (_posSelTemplate < 0)
         return;
     SalomeTemplateData _templateToReset;
     _templateToReset = _templateManager.getTemplates().at(_posSelTemplate);
     QList<SalomeVariableData> _varList = _templateToReset.getVariableList();
     int _totalRows = ui->templateVarTable->rowCount();
     for (int i = 0 ; i < _totalRows;i++)
     {
         SalomeVariableData _varData = _varList.at(i);
         if (valueChangedByUser(i,_varData.getDefaultValue()))
         {
             QLineEdit * _lineValue = qobject_cast<QLineEdit * > ( ui->templateVarTable->cellWidget(i,variableValueCol));
             if (_lineValue)
                 _lineValue->setText(_varData.getDefaultValue());
             ui->templateVarTable->item(i,variableChangedCol)->setCheckState(Qt::Unchecked);
             _needToSaveUserChanges = true;
         }
     }
     restoreTemplateDefaults(_posSelTemplate);
 }
void SalomeTemplateDialog::restoreTemplateDefaults (int _tempId) private
Parameters
_tempId
Definition at line 657 of file salometemplatedialog.cpp.
References _templateManager, and SalomeTemplateManager::restoreToDefaultTemplate().
Referenced by resetValuesToDefault().
 {
     // At the moment, only restores for the provided templates not the user defined
     _templateManager.restoreToDefaultTemplate(_tempId);
 }
void SalomeTemplateDialog::saveData () private
Definition at line 668 of file salometemplatedialog.cpp.
References _needToSaveUserChanges, _templateManager, getPosMenu(), SalomeTemplateManager::getTemplateNameList(), SalomeTemplateManager::getTemplates(), SalomeTemplateManager::getUserTemplates(), ui, SalomeTemplateManager::updateTemplateValues(), updateTemplateValues(), and SalomeTemplateManager::updateUserTemplateValues().
Referenced by on_createMeshButton_clicked(), and on_saveButton_clicked().
 {
     int _posTemplateList = getPosMenu();
     int _cPos = ui->templateSelComboBox->currentIndex();
     bool _isUserTemplateModified = false;
     if (_cPos > _templateManager.getTemplateNameList().size())
         _isUserTemplateModified = true;
     SalomeTemplateData _templateToSave;
     QList<SalomeTemplateData> _templateList;
     if (_isUserTemplateModified)
     {
         _templateToSave = _templateManager.getUserTemplates().at(_posTemplateList);
         updateTemplateValues(&_templateToSave);
         _templateList = _templateManager.getUserTemplates();
         _templateList[_posTemplateList]   = _templateToSave;
         _templateManager.updateUserTemplateValues(_templateList);
         _needToSaveUserChanges = false;
     }
     else
     {
         _templateToSave = _templateManager.getTemplates().at(_posTemplateList);
         updateTemplateValues(&_templateToSave);
         _templateList = _templateManager.getTemplates();
         _templateList[_posTemplateList]  = _templateToSave;
         _templateManager.updateTemplateValues(_templateList);
         _needToSaveUserChanges = false;
     }
 }
void SalomeTemplateDialog::setBBIPEDPath (QString _path)
Parameters
_path
Definition at line 723 of file salometemplatedialog.cpp.
References _bbipedPath.
Referenced by ToolsHelper::createAutomaticMesh().
 {
     _bbipedPath = _path;
 }
void SalomeTemplateDialog::setMeshViewerPath (QString _salomePath)
Parameters
_salomePath
Definition at line 713 of file salometemplatedialog.cpp.
References _meshViewerPath, and JobManager::_salomePath.
Referenced by ToolsHelper::createAutomaticMesh().
 {
     _meshViewerPath = _salomePath;
 }
void SalomeTemplateDialog::setProjectName (QString _name)
Parameters
_name
Definition at line 117 of file salometemplatedialog.cpp.
References _projectName.
Referenced by ToolsHelper::createAutomaticMesh().
 {
     _projectName = _name;
 }
void SalomeTemplateDialog::setProjectPath (QString _path)
Parameters
_path
Definition at line 97 of file salometemplatedialog.cpp.
References _projectPath.
Referenced by ToolsHelper::createAutomaticMesh().
 {
     _projectPath = _path;
 }
void SalomeTemplateDialog::textChangedSlot (QString _position) private slot
Parameters
_position
Definition at line 531 of file salometemplatedialog.cpp.
References _isLoadingTable, _needToSaveUserChanges, ui, and variableChangedCol.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
        int _row = _position.toInt();
        ui->templateVarTable->item(_row,variableChangedCol)->setCheckState(Qt::Checked);
         _needToSaveUserChanges = true;
     }
 }
void SalomeTemplateDialog::updateTemplateValues (SalomeTemplateData * _template) private
Parameters
_template
Definition at line 258 of file salometemplatedialog.cpp.
References SalomeVariableData::getCurrentValue(), SalomeTemplateData::getVariableList(), SalomeVariableData::setCurrentValue(), SalomeTemplateData::setVariableList(), ui, valueChangedByUser(), and variableValueCol.
Referenced by saveData().
 {
     QList<SalomeVariableData> _varList = _template->getVariableList();
     int _totalRows = ui->templateVarTable->rowCount();
     for (int i = 0 ; i < _totalRows;i++)
     {
         SalomeVariableData _varData = _varList.at(i);
         if (valueChangedByUser(i,_varData.getCurrentValue()))
         {
             QString _value = ( ( QLineEdit *)  ( ui->templateVarTable->cellWidget(i,variableValueCol) ) )->text();
             _varData.setCurrentValue(_value);
             /*if (ui->templateVarTable->item(i,variableOptimizeCol)->checkState() == Qt::Checked)
                 _varData.setOptimizedValue("YES");
             else
                 _varData.setOptimizedValue("NO");
                 */
             _varList[i] = _varData;
         }
     }
     _template->setVariableList(_varList);
 }
bool SalomeTemplateDialog::valueChangedByUser (int _rowPos, QString _oldValue) private
Parameters
_rowPos
Returns
bool
Definition at line 286 of file salometemplatedialog.cpp.
References StrEqual, ui, variableChangedCol, and variableValueCol.
Referenced by resetValuesToDefault(), and updateTemplateValues().
 {
     QString _cData;
     QLineEdit * _lineValue = qobject_cast<QLineEdit * > (
                 ui->templateVarTable->cellWidget(_rowPos,variableValueCol));
     if (_lineValue)
         _cData = _lineValue->text();
     if (ui->templateVarTable->item(_rowPos,variableChangedCol)->checkState() == Qt::Checked)
         return true;
     else
     {
         if (QString::compare(_oldValue,_cData) != StrEqual)
             return true;
         else
             return false;
     }
 }
Member Data Documentation
QString SalomeTemplateDialog::_bbipedPath private
Definition at line 69 of file salometemplatedialog.h.
Referenced by on_createMeshButton_clicked(), SalomeTemplateDialog(), setBBIPEDPath(), and ~SalomeTemplateDialog().
bool SalomeTemplateDialog::_isLoadingTable private
Definition at line 73 of file salometemplatedialog.h.
Referenced by changedComboSlot(), fillTable(), SalomeTemplateDialog(), and textChangedSlot().
bool SalomeTemplateDialog::_isUserDefinedTemplate private
Definition at line 74 of file salometemplatedialog.h.
Referenced by on_createMeshButton_clicked(), on_templateSelComboBox_currentIndexChanged(), and SalomeTemplateDialog().
QString SalomeTemplateDialog::_meshViewerPath private
Definition at line 68 of file salometemplatedialog.h.
Referenced by on_createMeshButton_clicked(), SalomeTemplateDialog(), setMeshViewerPath(), and ~SalomeTemplateDialog().
bool SalomeTemplateDialog::_needToSaveUserChanges private
Definition at line 75 of file salometemplatedialog.h.
Referenced by changedComboSlot(), on_createMeshButton_clicked(), on_saveAsButton_clicked(), resetValuesToDefault(), SalomeTemplateDialog(), saveData(), and textChangedSlot().
QString SalomeTemplateDialog::_projectName private
Definition at line 66 of file salometemplatedialog.h.
Referenced by getProjectName(), on_createMeshButton_clicked(), setProjectName(), and ~SalomeTemplateDialog().
QString SalomeTemplateDialog::_projectPath private
Definition at line 65 of file salometemplatedialog.h.
Referenced by getProjectPath(), on_createMeshButton_clicked(), setProjectPath(), and ~SalomeTemplateDialog().
QTextEdit* SalomeTemplateDialog::_regEditor private
Definition at line 63 of file salometemplatedialog.h.
Referenced by registerConsole().
QString SalomeTemplateDialog::_selectedTemplate private
Definition at line 71 of file salometemplatedialog.h.
Referenced by fillTable(), getPosMenu(), on_createMeshButton_clicked(), on_deleteTemplateButton_clicked(), on_saveAsButton_clicked(), on_saveButton_clicked(), on_templateSelComboBox_currentIndexChanged(), and refreshComboTemplates().
QSignalMapper* SalomeTemplateDialog::_signalMapperTxtEdit private
Definition at line 77 of file salometemplatedialog.h.
Referenced by addSignals(), and SalomeTemplateDialog().
QtableUtil SalomeTemplateDialog::_tableHelper private
Definition at line 72 of file salometemplatedialog.h.
Referenced by addRow(), on_deleteTemplateButton_clicked(), on_templateSelComboBox_currentIndexChanged(), and registerHelpers().
SalomeTemplateManager SalomeTemplateDialog::_templateManager private
Definition at line 62 of file salometemplatedialog.h.
Referenced by createTemplateFromUserValues(), fillTable(), getPosMenu(), initializeDialog(), isUserTemplateSelected(), on_createMeshButton_clicked(), on_deleteTemplateButton_clicked(), on_saveAsButton_clicked(), refreshComboTemplates(), resetValuesToDefault(), restoreTemplateDefaults(), and saveData().
Ui::SalomeTemplateDialog* SalomeTemplateDialog::ui private
Definition at line 61 of file salometemplatedialog.h.
Referenced by addRow(), addSignals(), changedComboSlot(), createTemplateFromUserValues(), fillTable(), on_saveAsButton_clicked(), on_templateSelComboBox_currentIndexChanged(), refreshComboTemplates(), registerHelpers(), resetValuesToDefault(), SalomeTemplateDialog(), saveData(), textChangedSlot(), updateTemplateValues(), valueChangedByUser(), and ~SalomeTemplateDialog().
The documentation for this class was generated from the following files:
Forms/ToolsDialog/salometemplatedialog.h
Forms/ToolsDialog/salometemplatedialog.cpp