BBIPED Platform: ProjectData Class Reference
ProjectData Class Reference
#include <projectdata.h>
Public Member Functions
ProjectData ()
Constructor.
~ProjectData ()
Destructor.
void clear ()
This function is to clear all the data contained in the object.
void copy (ProjectData _newProjectOBJ)
This function makes a hard (in depth) copy from one object to the other.
QString getProjectFileName ()
returns the path of the project file
QString getProjectPath ()
Returns the absolute path of the project.
SolverVO getSolverDataInformation ()
Returns the Solver VO object with the stored information.
bool isEmpty ()
Returns true if _projectPath and project file name are empty.
void saveProjectInformation (QString _fullPath)
This function stores the path of the project.
void saveProjectInformation (QString _fileName, QString _projectPath, SolverVO _solverVO)
This function saves all the project information.
void setProjectFileName (QString _fileName)
Establish the file path of the project file.
void setProjectPath (QString _path)
Establish the path of the project.
void setSolverDataInformation (SolverVO _newSolverInfo)
Sets a new Solver VO object.
bool solverDataComplete ()
Returns true if the object has both config file and mesh file paths.
void updateProjectData (ProjectData _newProjectData)
This function is to update the data from another object.
Private Attributes
QString _projectFileName
QString _projectPath
SolverVO _solverData
Detailed Description
Definition at line 8 of file projectdata.h.
Constructor & Destructor Documentation
ProjectData::ProjectData ()
Constructor.
Definition at line 28 of file projectdata.cpp.
References _projectFileName, and _projectPath.
 {
     _projectPath = "";
     _projectFileName = "";
 }
ProjectData::~ProjectData ()
Destructor.
Definition at line 38 of file projectdata.cpp.
 {
 }
Member Function Documentation
void ProjectData::clear ()
This function is to clear all the data contained in the object.
Definition at line 181 of file projectdata.cpp.
References _projectFileName, _projectPath, _solverData, and SolverVO::clear().
Referenced by MainWindow::clearAllData().
 {
     _projectPath = "";
     _projectFileName = "";
     _solverData.clear();
 }
void ProjectData::copy (ProjectData _newProjectOBJ)
This function makes a hard (in depth) copy from one object to the other.
Parameters
_newProjectOBJ
Definition at line 107 of file projectdata.cpp.
References getProjectFileName(), getProjectPath(), getSolverDataInformation(), setProjectFileName(), setProjectPath(), and setSolverDataInformation().
Referenced by MainWindow::openProject().
 {
     setProjectFileName(_newProjectOBJ.getProjectFileName());
     setProjectPath(_newProjectOBJ.getProjectPath());
     setSolverDataInformation(_newProjectOBJ.getSolverDataInformation());
 }
QString ProjectData::getProjectFileName ()
returns the path of the project file
Returns
QString
Definition at line 150 of file projectdata.cpp.
References _projectFileName.
Referenced by copy(), ToolsHelper::createAutomaticMesh(), ToolsHelper::createAutomaticMeshWithOptimization(), SolverHelper::launchFileComparisonDialog(), MainWindow::openProject(), updateProjectData(), UtilFiles::updateProjectDataToFile(), ProjectSettingsDialog::updateProjectInformationInSettingsView(), and UtilFiles::updateToolPaths().
 {
     return _projectFileName;
 }
QString ProjectData::getProjectPath ()
Returns the absolute path of the project.
Returns
QString
Definition at line 130 of file projectdata.cpp.
References _projectPath.
Referenced by MainWindow::checkProjectBasePathConsistency(), copy(), UtilFiles::copyAllToolData(), ToolsHelper::createAutomaticMesh(), ToolsHelper::createAutomaticMeshWithOptimization(), UtilFiles::createLink(), UtilFiles::importFile(), MainWindow::importMeshFile(), MainWindow::importMeshInfoFile(), MainWindow::launchSalomeMeshTool(), MainWindow::on_actionSave_Configuration_File_As_triggered(), MainWindow::on_newActionButton_clicked(), MainWindow::on_restartButton_clicked(), MainWindow::openProject(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::runSolverProject(), MainWindow::saveConfigFile(), MainWindow::seeParaviewResults(), SolverUtil::uiImportSolverMeshFile(), updateProjectData(), UtilFiles::updateProjectDataToFile(), and UtilFiles::updateToolPaths().
 {
     return _projectPath;
 }
SolverVO ProjectData::getSolverDataInformation ()
Returns the Solver VO object with the stored information.
Returns
SolverVO
Definition at line 160 of file projectdata.cpp.
References _solverData.
Referenced by MainWindow::buildSolverCommand(), MainWindow::checkMeshNames(), MainWindow::checkProjectBasePathConsistency(), MainWindow::closeProject(), copy(), InputDataTabHelper::enableConfigurationViewMenu(), MainWindow::enableMeshOptions(), InputDataTabHelper::fillFileNamesInTab(), MultizoneManager::getConfigurationFilePosition(), MainWindow::importMeshFile(), MainWindow::importMeshInfoFile(), MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_actionSave_Configuration_File_As_triggered(), MainWindow::on_newActionButton_clicked(), MainWindow::on_openFileActionButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::runSolverProject(), InputDataTabHelper::saveAsConfigFile(), MainWindow::saveConfigFile(), MainWindow::saveMeshVariables(), ProjectSettingsDialog::updateFileTableInSettingsView(), MultizoneManager::updateOpenEditConfigFile(), updateProjectData(), ProjectSettingsDialog::updateProjectData(), UtilFiles::updateProjectDataToFile(), InputDataTabHelper::updateSolverUserValues(), and UtilFiles::updateToolPaths().
 {
     return _solverData;
 }
bool ProjectData::isEmpty ()
Returns true if _projectPath and project file name are empty.
Returns
bool
Definition at line 62 of file projectdata.cpp.
References _projectFileName, and _projectPath.
Referenced by MainWindow::enableMeshOptions(), MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_actionSave_triggered(), ProjectSettingsDialog::updateFileTableInSettingsView(), ProjectSettingsDialog::updateProjectData(), ProjectSettingsDialog::updateProjectInformationInSettingsView(), and UtilFiles::updateToolPaths().
 {
     if (!_projectPath.isEmpty())
         return false;
     if (!_projectFileName.isEmpty())
         return false;
     return true;
 }
void ProjectData::saveProjectInformation (QString _fullPath)
This function stores the path of the project.
Parameters
_fullPath
Definition at line 79 of file projectdata.cpp.
References setProjectFileName(), and setProjectPath().
Referenced by MainWindow::on_actionNew_Project_triggered(), and MainWindow::on_actionSave_As_triggered().
 {
     QFileInfo _qFileInfo(_fullPath);
     setProjectFileName(_qFileInfo.fileName());
     setProjectPath(_qFileInfo.absolutePath());
 }
void ProjectData::saveProjectInformation (QString _fileName, QString _projectPath, SolverVO _solverVO)
This function saves all the project information.
Parameters
_fileName
_projectPath
_solverVO
Definition at line 93 of file projectdata.cpp.
References setProjectFileName(), setProjectPath(), and setSolverDataInformation().
 {
     setProjectFileName(_fileName);
     setProjectPath(_projectPath);
     setSolverDataInformation(_solverVO);
 }
void ProjectData::setProjectFileName (QString _fileName)
Establish the file path of the project file.
Parameters
_fileName
Definition at line 140 of file projectdata.cpp.
References _projectFileName.
Referenced by copy(), MultizoneManager::createInitialProjectDataForMultizoneProject(), XmlUtil::getInitialProjectInformation(), saveProjectInformation(), updateProjectData(), and UtilFiles::updateToolPaths().
 {
     _projectFileName = _fileName;
 }
void ProjectData::setProjectPath (QString _path)
Establish the path of the project.
Parameters
_path
Definition at line 120 of file projectdata.cpp.
References _projectPath.
Referenced by MainWindow::checkProjectBasePathConsistency(), copy(), MultizoneManager::createInitialProjectDataForMultizoneProject(), XmlUtil::getInitialProjectInformation(), saveProjectInformation(), updateProjectData(), and UtilFiles::updateToolPaths().
 {
     _projectPath = _path;
 }
void ProjectData::setSolverDataInformation (SolverVO _newSolverInfo)
Sets a new Solver VO object.
Parameters
_newSolverInfo
Definition at line 170 of file projectdata.cpp.
References _solverData, and SolverVO::copy().
Referenced by MultizoneManager::buildProjectDataForMultizoneProject(), MainWindow::checkProjectBasePathConsistency(), copy(), MainWindow::importMeshFile(), MainWindow::on_actionSave_Configuration_File_As_triggered(), MainWindow::on_newActionButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), XmlUtil::readXmlProjectFile(), InputDataTabHelper::saveAsConfigFile(), MainWindow::saveMeshVariables(), saveProjectInformation(), updateProjectData(), ProjectSettingsDialog::updateProjectData(), and UtilFiles::updateToolPaths().
 {
     _solverData.copy(_newSolverInfo);
 }
bool ProjectData::solverDataComplete ()
Returns true if the object has both config file and mesh file paths.
Returns
bool
Definition at line 49 of file projectdata.cpp.
References _solverData, SolverVO::isConfigFileEmpty(), and SolverVO::isMeshFileEmpty().
Referenced by MainWindow::enableSolverRunAction().
 {
     if ((!_solverData.isConfigFileEmpty()) && (!_solverData.isMeshFileEmpty()))
         return true;
     else
         return false;
 }
void ProjectData::updateProjectData (ProjectData _newProjectData)
This function is to update the data from another object.
Parameters
_newProjectData
Definition at line 195 of file projectdata.cpp.
References getProjectFileName(), getProjectPath(), getSolverDataInformation(), setProjectFileName(), setProjectPath(), and setSolverDataInformation().
Referenced by EditHelper::launchSettingsDialog().
 {
     setProjectFileName(_newProjectData.getProjectFileName());
     setProjectPath(_newProjectData.getProjectPath());
     setSolverDataInformation(_newProjectData.getSolverDataInformation());
 }
Member Data Documentation
QString ProjectData::_projectFileName private
Definition at line 42 of file projectdata.h.
Referenced by clear(), getProjectFileName(), isEmpty(), ProjectData(), and setProjectFileName().
QString ProjectData::_projectPath private
Definition at line 41 of file projectdata.h.
Referenced by clear(), getProjectPath(), isEmpty(), ProjectData(), and setProjectPath().
SolverVO ProjectData::_solverData private
Definition at line 43 of file projectdata.h.
Referenced by clear(), getSolverDataInformation(), setSolverDataInformation(), and solverDataComplete().
The documentation for this class was generated from the following files:
Data/ProjectData/VO/projectdata.h
Data/ProjectData/VO/projectdata.cpp