BBIPED Platform: SolverSectionDAO Class Reference
SolverSectionDAO Class Reference
#include <solversectiondao.h>
Public Member Functions
SolverSectionDAO ()
Constructor.
SolverSectionVO * createSectionElement (QString _sectionName)
Creates a section Element with the name.
SolverSectionVO * createSectionElement (QString _sectionName, QList< SolverVariableVO > _listVariables)
creates a section element
SolverSectionVO findSection (QString _sectionName, QList< SolverSectionVO > _list)
Find a section in a list.
QString findSectionNameBySubSectionName (QString _subSectionName, QList< SolverSectionVO > _list)
Find the section name associated to a subsection name.
SolverSectionVO findSubSection (QString _subSectionName, QList< SolverSectionVO > _list)
find subsection in a list
QStringList findSubSectionNamesBySectionName (QString _sectionName, QList< SolverSectionVO > _list)
Find the subsectionNames associated to a section name.
QString findValueNameByVariableName (QList< SolverSectionVO > _solverList, QString _varName)
Find the value name associated to a variable name.
QString findValueNameByVariableName (SolverSectionVO _solverVO, QString _varName)
find the Value of a variable
SolverVariableVO findVariableByFileName (QList< SolverSectionVO > _list, QString _fileName)
Find a variable by its value name.
SolverVariableVO findVariableByFileName (QList< SolverVariableVO > _list, QString _fileName)
Find a Variable by its value name.
SolverVariableVO findVariableByValueName (SolverSectionVO _solverVO, QString _valueName)
QString findVariableNameByValueName (SolverSectionVO _solverVO, QString _valueName)
Find a Variable by the value name.
QStringList getOptionalVariables (QList< SolverSectionVO > _listSection)
QStringList getVariableNameList (QList< SolverVariableVO > _list)
Get the list fo variables.
bool isDefaultValueByFileName (QList< SolverSectionVO > _list, QString _varFileName, QString _cValue)
Checks if the current value of a variable is the default value.
Detailed Description
Definition at line 9 of file solversectiondao.h.
Constructor & Destructor Documentation
SolverSectionDAO::SolverSectionDAO ()
Constructor.
Definition at line 25 of file solversectiondao.cpp.
 {
 }
Member Function Documentation
SolverSectionVO * SolverSectionDAO::createSectionElement (QString _sectionName)
Creates a section Element with the name.
Parameters
_sectionName
Returns
SolverSectionVO
Definition at line 267 of file solversectiondao.cpp.
References SolverSectionVO::setSubsectionName().
 {
     SolverSectionVO * _createdElement = new SolverSectionVO();
     _createdElement->setSubsectionName(_sectionName);
     return _createdElement;
 }
SolverSectionVO * SolverSectionDAO::createSectionElement (QString _sectionName, QList< SolverVariableVO > _listVariables)
creates a section element
Parameters
_sectionName
_listVariables
Returns
SolverSectionVO
Definition at line 281 of file solversectiondao.cpp.
References SolverSectionVO::setSubsectionName(), and SolverSectionVO::setSubsectionVarList().
 {
     SolverSectionVO * _createdElement = new SolverSectionVO();
     _createdElement->setSubsectionName(_sectionName);
     _createdElement->setSubsectionVarList(_listVariables);
     return _createdElement;
 }
SolverSectionVO SolverSectionDAO::findSection (QString _sectionName, QList< SolverSectionVO > _list)
Find a section in a list.
Parameters
_sectionName
_list
Returns
SolverSectionVO
Definition at line 37 of file solversectiondao.cpp.
References SolverSectionVO::getSectionName(), and StrEqual.
 {
     if (_list.isEmpty())
         return SolverSectionVO();
     for(int i = 0; i < _list.count() ;i++)
     {
         SolverSectionVO _element = _list.at(i);
         if (QString::compare(_element.getSectionName(),_sectionName) == StrEqual)
             return _element;
     }
     return SolverSectionVO();
 }
QString SolverSectionDAO::findSectionNameBySubSectionName (QString _subSectionName, QList< SolverSectionVO > _list)
Find the section name associated to a subsection name.
Parameters
_subSectionName
_list
Returns
QString
Definition at line 81 of file solversectiondao.cpp.
References SolverSectionVO::getSectionName(), SolverSectionVO::getSubsectionName(), and StrEqual.
Referenced by TemplateManager::getSectionNames().
 {
     QString _foundName;
     if ( (_list.isEmpty()) || (_subSectionName.isEmpty()) )
         return _foundName;
     for (int i = 0; i < _list.size();  i++)
     {
         SolverSectionVO _element =  _list.at(i);
         if (QString::compare(_element.getSubsectionName(),_subSectionName) == StrEqual)
             return _element.getSectionName();
     }
     return _foundName;
 }
SolverSectionVO SolverSectionDAO::findSubSection (QString _subSectionName, QList< SolverSectionVO > _list)
find subsection in a list
Parameters
_subSectionName
_list
Returns
SolverSectionVO
Definition at line 104 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionName(), and StrEqual.
Referenced by SolverConfigManager::getPersonalizedVariableListofSubsections(), SolverConfigManager::getVariableListofSubsections(), and TemplateManager::getVariables().
 {
     if (_list.isEmpty())
         return SolverSectionVO();
     for(int i = 0; i < _list.count() ;i++)
     {
         SolverSectionVO _element = _list.at(i);
         if (QString::compare(_element.getSubsectionName(),_subSectionName) == StrEqual)
             return _element;
     }
     return SolverSectionVO();
 }
QStringList SolverSectionDAO::findSubSectionNamesBySectionName (QString _sectionName, QList< SolverSectionVO > _list)
Find the subsectionNames associated to a section name.
Parameters
_sectionName
_list
Returns
QStringList
Definition at line 59 of file solversectiondao.cpp.
References SolverSectionVO::getSectionName(), SolverSectionVO::getSubsectionName(), and StrEqual.
Referenced by TemplateManager::getSubSectionNamesBySectionName().
 {
    QStringList _result;
     if (_list.isEmpty())
         return _result;
     for (int i = 0; i < _list.size(); i++)
     {
         SolverSectionVO _section = _list.at(i);
         if (QString::compare(_sectionName,_section.getSectionName()) == StrEqual)
             _result.append(_section.getSubsectionName());
     }
     return _result;
 }
QString SolverSectionDAO::findValueNameByVariableName (QList< SolverSectionVO > _solverList, QString _varName)
Find the value name associated to a variable name.
Parameters
_solverList
_varName
Returns
QString
Definition at line 156 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableFileName(), SolverVariableVO::getVariableName(), and StrEqual.
Referenced by WarningMultizoneDialog::changedComboValueByUser(), SolverBasicDialog::checkIsDefaultValue(), SolverBasicDialog::getAssociatedFileNameValue(), SolverBasicDialog::launchSpecificWindow(), MeshDialog::needToOpenSpecificConfigWindow(), SolverBasicDialog::resetToDefaultValue(), FileComparisonDialog::saveUserChanges(), SolverBasicDialog::saveUserChanges(), and SolverBasicDialog::saveUserChangesSpecificWindow().
 {
     QString _result;
     if (!_solverList.isEmpty())
         for (int j= 0; j < _solverList.size();j++)
         {
             SolverSectionVO _solverVO = _solverList.at(j);
             QList<SolverVariableVO> _varList = _solverVO.getSubsectionVarList();
             if (!_varList.isEmpty())
                 for (int i = 0; i < _varList.count(); i++)
                 {
                     SolverVariableVO _varVO = _varList.at(i);
                     QString _variable = _varVO.getVariableName();
                     if (QString::compare(_variable, _varName) == StrEqual)
                         return (_varVO.getVariableFileName());
                 }
         }
     return _result;
 }
QString SolverSectionDAO::findValueNameByVariableName (SolverSectionVO _solverVO, QString _varName)
find the Value of a variable
Parameters
_solverVO
_varName
Returns
QString
Definition at line 126 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableFileName(), SolverVariableVO::getVariableName(), and StrEqual.
 {
     QString _result;
     QList<SolverVariableVO> _varList = _solverVO.getSubsectionVarList();
     if (!_varList.isEmpty())
     {
         for (int i = 0; i < _varList.count(); i++)
         {
             SolverVariableVO _varVO = _varList.at(i);
             QString _variable = _varVO.getVariableName();
             if (QString::compare(_variable, _varName) == StrEqual)
             {
                 return (_varVO.getVariableFileName());
             }
         }
     }
     return _result;
 }
SolverVariableVO SolverSectionDAO::findVariableByFileName (QList< SolverSectionVO > _list, QString _fileName)
Find a variable by its value name.
Parameters
_list
_fileName
Returns
SolverVariableVO
Definition at line 184 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), and SolverVariableVO::isEmpty().
Referenced by FileComparisonDialog::buildRow(), SummaryDialog::buildRows(), WarningMultizoneDialog::fillRepairTable(), SolverBasicDialog::getAssociatedFileNameValue(), isDefaultValueByFileName(), SolverBasicDialog::launchSpecificWindow(), MeshDialog::restoreValues(), and SummaryDialog::updateNewValues().
 {
     if (!_list.isEmpty())
         for (int i = 0; i<_list.count();i++)
         {
             SolverSectionVO _sectionVO = _list.at(i);
             QList<SolverVariableVO> _varList = _sectionVO.getSubsectionVarList();
             SolverVariableVO _foundVariable = findVariableByFileName(_varList,_fileName);
             if (!_foundVariable.isEmpty())
                 return _foundVariable;
         }
     return SolverVariableVO();
 }
SolverVariableVO SolverSectionDAO::findVariableByFileName (QList< SolverVariableVO > _list, QString _fileName)
Find a Variable by its value name.
Parameters
_list
_fileName
Returns
SolverVariableVO
Definition at line 206 of file solversectiondao.cpp.
References SolverVariableVO::getVariableFileName(), and StrEqual.
 {
     if (!_list.isEmpty())
         for (int i = 0; i<_list.count();i++)
         {
             SolverVariableVO _variableVO = _list.at(i);
             QString _cFileName = _variableVO.getVariableFileName();
             if (QString::compare(_cFileName,_fileName) == StrEqual)
                 return _variableVO;
         }
     return SolverVariableVO();
 }
SolverVariableVO SolverSectionDAO::findVariableByValueName (SolverSectionVO _solverVO, QString _valueName)
Definition at line 243 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableName(), and StrEqual.
Referenced by SolverBasicDialog::on_solverVariablesTable_cellClicked().
 {
     QList<SolverVariableVO> _listVariables = _solverVO.getSubsectionVarList();
     if (!_listVariables.isEmpty())
         for (int i = 0; i < _listVariables.count();i++)
         {
             SolverVariableVO _varVO = _listVariables.at(i);
            // QString _varFileName = _varVO.getVariableFileName();
             QString _variableName = _varVO.getVariableName();
             if (QString::compare(_valueName,_variableName) == StrEqual)
                 return _varVO;
         }
     SolverVariableVO _result;
     return _result;
 }
QString SolverSectionDAO::findVariableNameByValueName (SolverSectionVO _solverVO, QString _valueName)
Find a Variable by the value name.
Parameters
_solverVO
_valueName
Returns
QString
Definition at line 227 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableFileName(), SolverVariableVO::getVariableName(), and StrEqual.
 {
     QList<SolverVariableVO> _listVariables = _solverVO.getSubsectionVarList();
     if (!_listVariables.isEmpty())
         for (int i = 0; i < _listVariables.count();i++)
         {
             SolverVariableVO _varVO = _listVariables.at(i);
             QString _varFileName = _varVO.getVariableFileName();
             QString _variableName = _varVO.getVariableName();
             if (QString::compare(_valueName,_varFileName) == StrEqual)
                 return _variableName;
         }
     return QString("");
 }
QStringList SolverSectionDAO::getOptionalVariables (QList< SolverSectionVO > _listSection)
Parameters
_listSection
Returns
QStringList
Definition at line 351 of file solversectiondao.cpp.
References SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableFileName(), and SolverVariableVO::isOptional().
Referenced by SolverConfigManager::saveConfigFile().
 {
     QStringList _result;
     for (int i = 0; i < _listSection.size(); i++)
     {
         SolverSectionVO _secVO = _listSection.at(i);
         QList<SolverVariableVO> _varList = _secVO.getSubsectionVarList();
         for (int j = 0; j < _varList.size(); j++)
         {
             SolverVariableVO _varVO = _varList.at(j);
             if (_varVO.isOptional())
                 _result.append(_varVO.getVariableFileName());
         }
     }
     return _result;
 }
QStringList SolverSectionDAO::getVariableNameList (QList< SolverVariableVO > _list)
Get the list fo variables.
Parameters
_list
Returns
QStringList
Definition at line 329 of file solversectiondao.cpp.
References SolverVariableVO::getVariableName().
Referenced by SolverMarkerMenuHelper::fillMarkerMenuTable().
 {
     QStringList _resultList;
     _resultList.append("NONE");
     if (!_list.isEmpty())
         for (int i = 0; i < _list.count(); i++)
         {
             SolverVariableVO _var = _list.at(i);
             _resultList.append(_var.getVariableName());
         }
     return _resultList;
 }
bool SolverSectionDAO::isDefaultValueByFileName (QList< SolverSectionVO > _list, QString _varFileName, QString _cValue)
Checks if the current value of a variable is the default value.
Parameters
_list
_varFileName
_cValue
Returns
bool
Definition at line 299 of file solversectiondao.cpp.
References findVariableByFileName(), SolverVariableVO::getDefaultValue(), SolverSectionVO::getSubsectionVarList(), SolverVariableVO::isEmpty(), and StrEqual.
Referenced by SolverBasicDialog::checkIsDefaultValue(), MultizoneSummaryDialog::removeDefaultValues(), and MainWindow::removeDefaultValuesReadFromConfigFile().
 {
     if (!_list.isEmpty())
         for (int i = 0; i<_list.count();i++)
         {
             SolverSectionVO _sectionVO = _list.at(i);
             QList<SolverVariableVO> _varList = _sectionVO.getSubsectionVarList();
             SolverVariableVO _foundVariable = findVariableByFileName(_varList,_varFileName);
             if  (!_foundVariable.isEmpty())
             {
                 QString _defaultValue = _foundVariable.getDefaultValue().simplified();
                 _defaultValue.replace(" ","");
                 _cValue = _cValue.simplified();
                 _cValue.replace(" ","");
                 if (QString::compare(_defaultValue,_cValue) == StrEqual)
                     return true;
             }
         }
     return false;
 }
The documentation for this class was generated from the following files:
Data/solversectiondao.h
Data/solversectiondao.cpp