BBIPED Platform: MeshFileParser Class Reference
MeshFileParser Class Reference
#include <meshfileparser.h>
Public Member Functions
MeshFileParser ()
Constructor.
bool is3DMesh ()
void parseFileProcess ()
Main function to parse the file.
Public Member Functions inherited from ParserFiles
ParserFiles ()
Constructor.
QString getFilePath ()
Returns the path of the file.
QHash< QString, QString > getParsedValues ()
Returns the map of the parsed values.
QString removeSpaces (QString _value)
Function to remove spaces in the values.
void setFilePath (QString _newPath)
Establish the file path.
void setParsedValues (QHash< QString, QString > _newValues)
Sets the parsed values.
Private Member Functions
void analyseLine (QString _line)
Function that analyses the line to be parsed.
bool containsKeyTagName (QString _line)
Function that checks if the line contains the MARKER_TAG.
void saveTokenElements (QString _line)
Function that stores the parsed toked elements.
Private Attributes
QHash< QString, QString > _currentParsedValues
bool _found3DMesh
int _id
bool _is3dMesh
Detailed Description
Definition at line 6 of file meshfileparser.h.
Constructor & Destructor Documentation
MeshFileParser::MeshFileParser ()
Constructor.
Definition at line 26 of file meshfileparser.cpp.
References _found3DMesh, _id, and _is3dMesh.
 {
     _id = 0;
     _is3dMesh = false; // By default consider 2D
     _found3DMesh = false;
 }
Member Function Documentation
void MeshFileParser::analyseLine (QString _line) private
Function that analyses the line to be parsed.
Parameters
_line
Definition at line 66 of file meshfileparser.cpp.
References containsKeyTagName(), and saveTokenElements().
Referenced by parseFileProcess().
 {
     if (containsKeyTagName(_line))
     {
         saveTokenElements(_line);
     }
 }
bool MeshFileParser::containsKeyTagName (QString _line) private
Function that checks if the line contains the MARKER_TAG.
Parameters
_line
Returns
bool
Definition at line 80 of file meshfileparser.cpp.
References _found3DMesh, and _is3dMesh.
Referenced by analyseLine().
 {
     if (_line.contains("MARKER_TAG"))
         return true;
     else
         if( (!_found3DMesh) && (_line.contains("NDIME")))
         {
             QStringList _listElements = _line.split("=");
             for (int i=0; i < _listElements.size();i++)
             {
                 QString _element =_listElements.at(i);
                 if (!_element.isEmpty())
                 {
                     bool isInt = false;
                     int _dim = _element.toInt(&isInt);
                     if (isInt)
                         if (_dim == 3)
                             _is3dMesh = true;
                 }
             }
             _found3DMesh = true;
             return false;
         }else
             return false;
 }
bool MeshFileParser::is3DMesh ()
Definition at line 125 of file meshfileparser.cpp.
References _is3dMesh.
Referenced by InputDataTabHelper::parseFile().
 {
     return _is3dMesh;
 }
void MeshFileParser::parseFileProcess () virtual
Main function to parse the file.
Implements ParserFiles.
Definition at line 37 of file meshfileparser.cpp.
References _currentParsedValues, analyseLine(), ParserFiles::getFilePath(), and ParserFiles::setParsedValues().
Referenced by MultizoneProjectDialog::checkConsistency(), and InputDataTabHelper::parseFile().
 {
     QString _path = this->getFilePath();
     QFile _file(_path);
     bool _fileCreated = false;
     if (_file.exists())
     {
          _fileCreated = _file.open(QIODevice::ReadOnly);
          if (_fileCreated )
          {
              QTextStream _reader(&_file);
              QString _line = _reader.readLine();
              while(!_line.isNull())
              {
                  analyseLine(_line);
                  _line = _reader.readLine();
              }
              setParsedValues(_currentParsedValues);
          }
          _file.close();
     }
 }
void MeshFileParser::saveTokenElements (QString _line) private
Function that stores the parsed toked elements.
Parameters
_line
Definition at line 113 of file meshfileparser.cpp.
References _currentParsedValues, _id, and ParserFiles::removeSpaces().
Referenced by analyseLine().
 {
     QStringList _values = _line.split("=");
     if ((!_values.isEmpty()) && (_values.size() == 2))
     {
         // Key_name = name of the variable, and the value is Marker_tag
         _currentParsedValues.insert(QString::number(_id), removeSpaces(_values.at(1)));
         _id++;
     }
 }
Member Data Documentation
QHash<QString, QString> MeshFileParser::_currentParsedValues private
Definition at line 16 of file meshfileparser.h.
Referenced by parseFileProcess(), and saveTokenElements().
bool MeshFileParser::_found3DMesh private
Definition at line 14 of file meshfileparser.h.
Referenced by containsKeyTagName(), and MeshFileParser().
int MeshFileParser::_id private
Definition at line 17 of file meshfileparser.h.
Referenced by MeshFileParser(), and saveTokenElements().
bool MeshFileParser::_is3dMesh private
Definition at line 13 of file meshfileparser.h.
Referenced by containsKeyTagName(), is3DMesh(), and MeshFileParser().
The documentation for this class was generated from the following files:
Parser/Solver/meshfileparser.h
Parser/Solver/meshfileparser.cpp