BBIPED Platform: UserPreferencesData Class Reference
UserPreferencesData Class Reference
#include <userpreferencesdata.h>
Public Member Functions
UserPreferencesData ()
Constructor.
void addProjectToList (QString _pathProject)
This function allows to add a new project to the recentProjectList. A max of 10 projects are considered.
QString getMeshViewerPath ()
Returns the mesh viewer path (e.g. Salome)
QString getPostProcessorViewerPath ()
get the postProcessor viewer path (e.g. Paraview)
QStringList getRecentProjectsList ()
Get the current list of already opened projects.
QString getTemplateConfigPath ()
Get the template configuration folder path.
QString getUserDefinedSolverPath ()
Returns the path of the user defined Solver Engine.
bool isDefaultSolverEngineSelected ()
Returns true if the default Solver Engine is selected (SU2_CFD)
bool isMultizoneSolverEngineSelected ()
Returns true if the Virtual Solver Engine is selected (SU2_CFD_MULTIZONE)
bool isVirtualSolverEngineSelected ()
Returns true if the Virtual Solver Engine is selected (SU2_CFD_VIRTUAL)
void setDefaultSolverEngineSelected (bool _val)
Set the default Solver Engine to true.
void setMeshViewerPath (QString _path)
Set the mesh viewer path (e.g. Salome)
void setMultizoneSolverEngineSelected (bool _val)
Set the MULTIZONE Solver Engine to true.
void setPostProcessorViewerPath (QString _path)
Set the postProcessor viewer path (e.g. Paraview)
void setRecentProjectsList (QStringList _list)
Set the current list of already opened projects.
void setShowCloseProjectWarning (bool _val)
Set whether the user wants to see the close project warning.
void setShowCloseWarning (bool _val)
Set whether the user wants to see the close window/application warning.
void setTemplateConfigPath (QString _file)
Set the template configuration folder path.
void setUserDefinedSolverPath (QString _path)
Set the path of the user defined Solver Engine.
void setVirtualSolverEngineSelected (bool _val)
Set the VIRTUAL Solver Engine to true.
bool showCloseProjectWarning ()
Returns true if the Close Project warning window shall appear.
bool showCloseWarning ()
Returns true if the Close Application warning window shall appear.
void updateData (UserPreferencesData _newData)
This function is to update the data from another object.
Private Attributes
bool _isDefaultSolverEngineSelected
bool _isMultizoneSolverEngineSelected
bool _isVirtualSolverEngineSelected
QString _meshViewerPath
QString _postProcessorViewerPath
QStringList _recentProjectsList
bool _showCloseProjectWarning
bool _showCloseWarning
QString _templateConfigPath
QString _userDefinedSolverPath
Detailed Description
Definition at line 7 of file userpreferencesdata.h.
Constructor & Destructor Documentation
UserPreferencesData::UserPreferencesData ()
Constructor.
Definition at line 24 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected, _isMultizoneSolverEngineSelected, _isVirtualSolverEngineSelected, _meshViewerPath, _postProcessorViewerPath, _showCloseProjectWarning, _showCloseWarning, _templateConfigPath, and _userDefinedSolverPath.
 {
     _isDefaultSolverEngineSelected = true;
     _isVirtualSolverEngineSelected = false;
     _isMultizoneSolverEngineSelected = false;
     _userDefinedSolverPath = "";
     _meshViewerPath = "";
     _postProcessorViewerPath = "";
     _showCloseWarning = true;
     _showCloseProjectWarning = true;
     _templateConfigPath = "";
 }
Member Function Documentation
void UserPreferencesData::addProjectToList (QString _pathProject)
This function allows to add a new project to the recentProjectList. A max of 10 projects are considered.
Parameters
_pathProject
Definition at line 240 of file userpreferencesdata.cpp.
References _recentProjectsList.
Referenced by MultizoneManager::launchMultizoneDialog(), MultizoneManager::openMultizoneProject(), and MainWindow::updateMainWindowElements().
 {
     if (_recentProjectsList.contains(_pathProject))
         _recentProjectsList.removeOne(_pathProject);
     if( (_recentProjectsList.isEmpty()) || (_recentProjectsList.size() < 10) )
        _recentProjectsList.append(_pathProject);
     else
     {
        _recentProjectsList.removeAt(0);
        _recentProjectsList.append(_pathProject);
     }
 }
QString UserPreferencesData::getMeshViewerPath ()
Returns the mesh viewer path (e.g. Salome)
Returns
QString
Definition at line 139 of file userpreferencesdata.cpp.
References _meshViewerPath.
Referenced by ToolsHelper::createAutomaticMesh(), ToolsHelper::createAutomaticMeshWithOptimization(), PreferenceDialog::initializeMeshViewerData(), MainWindow::launchSalomeMeshTool(), updateData(), and PreferencesManager::writeUserPreferences().
 {
     return _meshViewerPath;
 }
QString UserPreferencesData::getPostProcessorViewerPath ()
get the postProcessor viewer path (e.g. Paraview)
Returns
QString
Definition at line 159 of file userpreferencesdata.cpp.
References _postProcessorViewerPath.
Referenced by PreferenceDialog::initializePostProcessorViewerData(), MainWindow::seeParaviewResults(), updateData(), and PreferencesManager::writeUserPreferences().
 {
     return _postProcessorViewerPath;
 }
QStringList UserPreferencesData::getRecentProjectsList ()
Get the current list of already opened projects.
Returns
QStringList
Definition at line 179 of file userpreferencesdata.cpp.
References _recentProjectsList.
Referenced by EditHelper::launchPreferencesDialog(), MainWindow::openRecentFile(), updateData(), MainWindow::updateRecentProjectsSection(), and PreferencesManager::writeRecentProjects().
 {
     return _recentProjectsList;
 }
QString UserPreferencesData::getTemplateConfigPath ()
Get the template configuration folder path.
Returns
QString
Definition at line 219 of file userpreferencesdata.cpp.
References _templateConfigPath.
Referenced by MainWindow::initializeManagers(), PreferenceDialog::initializeTemplateConfigData(), EditHelper::launchPreferencesDialog(), updateData(), and PreferencesManager::writeTemplatePreferences().
 {
     return _templateConfigPath;
 }
QString UserPreferencesData::getUserDefinedSolverPath ()
Returns the path of the user defined Solver Engine.
Returns
QString
Definition at line 116 of file userpreferencesdata.cpp.
References _userDefinedSolverPath.
Referenced by MainWindow::getSolverCommand(), PreferenceDialog::initializeSolverData(), updateData(), and PreferencesManager::writeUserPreferences().
 {
     return _userDefinedSolverPath;
 }
bool UserPreferencesData::isDefaultSolverEngineSelected ()
Returns true if the default Solver Engine is selected (SU2_CFD)
Returns
bool
Definition at line 44 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected.
Referenced by MainWindow::getCurrentUserPreferences(), MainWindow::getSolverCommand(), and updateData().
 {
     return  _isDefaultSolverEngineSelected;
 }
bool UserPreferencesData::isMultizoneSolverEngineSelected ()
Returns true if the Virtual Solver Engine is selected (SU2_CFD_MULTIZONE)
Returns
bool
Definition at line 65 of file userpreferencesdata.cpp.
References _isMultizoneSolverEngineSelected.
Referenced by MainWindow::getCurrentUserPreferences(), MainWindow::getSolverCommand(), updateData(), and PreferencesManager::writeUserPreferences().
 {
     return _isMultizoneSolverEngineSelected;
 }
bool UserPreferencesData::isVirtualSolverEngineSelected ()
Returns true if the Virtual Solver Engine is selected (SU2_CFD_VIRTUAL)
Returns
bool
Definition at line 54 of file userpreferencesdata.cpp.
References _isVirtualSolverEngineSelected.
Referenced by MainWindow::getCurrentUserPreferences(), MainWindow::getSolverCommand(), updateData(), and PreferencesManager::writeUserPreferences().
 {
     return _isVirtualSolverEngineSelected;
 }
void UserPreferencesData::setDefaultSolverEngineSelected (bool _val)
Set the default Solver Engine to true.
Parameters
_val
Definition at line 77 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected, _isMultizoneSolverEngineSelected, and _isVirtualSolverEngineSelected.
Referenced by PreferenceDialog::getSolverDataConfiguration(), and updateData().
 {
     _isDefaultSolverEngineSelected = _val;
     _isVirtualSolverEngineSelected = !_val;
     _isMultizoneSolverEngineSelected  = !_val;
 }
void UserPreferencesData::setMeshViewerPath (QString _path)
Set the mesh viewer path (e.g. Salome)
Parameters
_path
Definition at line 149 of file userpreferencesdata.cpp.
References _meshViewerPath.
Referenced by PreferenceDialog::getMeshViewerConfiguration(), MainWindow::getSalomePathSlot(), PreferencesManager::getUserToolPreferences(), and updateData().
 {
     _meshViewerPath = _path;
 }
void UserPreferencesData::setMultizoneSolverEngineSelected (bool _val)
Set the MULTIZONE Solver Engine to true.
Parameters
_val
Definition at line 103 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected, _isMultizoneSolverEngineSelected, and _isVirtualSolverEngineSelected.
Referenced by PreferencesManager::setSolverEngineInformation(), and updateData().
 {
     _isMultizoneSolverEngineSelected  =_val;
     _isDefaultSolverEngineSelected = !_val;
     _isVirtualSolverEngineSelected = !_val;
 }
void UserPreferencesData::setPostProcessorViewerPath (QString _path)
Set the postProcessor viewer path (e.g. Paraview)
Parameters
_path
Definition at line 169 of file userpreferencesdata.cpp.
References _postProcessorViewerPath.
Referenced by PreferenceDialog::getPostProcessorViewerConfiguration(), PreferencesManager::getUserToolPreferences(), and updateData().
 {
     _postProcessorViewerPath = _path;
 }
void UserPreferencesData::setRecentProjectsList (QStringList _list)
Set the current list of already opened projects.
Parameters
_list
Definition at line 189 of file userpreferencesdata.cpp.
References _recentProjectsList.
Referenced by PreferencesManager::getRecentProjects(), EditHelper::launchPreferencesDialog(), and updateData().
 {
    _recentProjectsList = _list;
 }
void UserPreferencesData::setShowCloseProjectWarning (bool _val)
Set whether the user wants to see the close project warning.
Parameters
_val
Definition at line 209 of file userpreferencesdata.cpp.
References _showCloseProjectWarning.
Referenced by PreferencesManager::getUserWarningPreferences(), PreferenceDialog::getWarningConfiguration(), MainWindow::on_actionClose_Project_triggered(), and updateData().
 {
     _showCloseProjectWarning = _val;
 }
void UserPreferencesData::setShowCloseWarning (bool _val)
Set whether the user wants to see the close window/application warning.
Parameters
_val
Definition at line 199 of file userpreferencesdata.cpp.
References _showCloseWarning.
Referenced by MainWindow::exitApplication(), PreferencesManager::getUserWarningPreferences(), PreferenceDialog::getWarningConfiguration(), and updateData().
 {
     _showCloseWarning = _val;
 }
void UserPreferencesData::setTemplateConfigPath (QString _file)
Set the template configuration folder path.
Parameters
_file
Definition at line 229 of file userpreferencesdata.cpp.
References _templateConfigPath.
Referenced by PreferenceDialog::getTemplateConfigPath(), PreferencesManager::getUserTemplatePreferences(), SolverHelper::loadConfigurationTemplateByUser(), and updateData().
 {
     _templateConfigPath = _file;
 }
void UserPreferencesData::setUserDefinedSolverPath (QString _path)
Set the path of the user defined Solver Engine.
Parameters
_path
Definition at line 125 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected, _isMultizoneSolverEngineSelected, _isVirtualSolverEngineSelected, and _userDefinedSolverPath.
Referenced by PreferenceDialog::getSolverDataConfiguration(), PreferencesManager::setSolverEngineInformation(), and updateData().
 {
     _userDefinedSolverPath = _path;
     _isDefaultSolverEngineSelected = false;
     _isVirtualSolverEngineSelected = false;
     _isMultizoneSolverEngineSelected  = false;
 }
void UserPreferencesData::setVirtualSolverEngineSelected (bool _val)
Set the VIRTUAL Solver Engine to true.
Parameters
_val
Definition at line 90 of file userpreferencesdata.cpp.
References _isDefaultSolverEngineSelected, _isMultizoneSolverEngineSelected, and _isVirtualSolverEngineSelected.
Referenced by PreferencesManager::setSolverEngineInformation(), and updateData().
 {
     _isVirtualSolverEngineSelected = _val;
     _isDefaultSolverEngineSelected =! _val;
     _isMultizoneSolverEngineSelected  = !_val;
 }
bool UserPreferencesData::showCloseProjectWarning ()
Returns true if the Close Project warning window shall appear.
Returns
bool
Definition at line 272 of file userpreferencesdata.cpp.
References _showCloseProjectWarning.
Referenced by PreferenceDialog::initializeWarningData(), MainWindow::on_actionClose_Project_triggered(), and updateData().
 {
    return _showCloseProjectWarning ;
 }
bool UserPreferencesData::showCloseWarning ()
Returns true if the Close Application warning window shall appear.
Returns
bool
Definition at line 260 of file userpreferencesdata.cpp.
References _showCloseWarning.
Referenced by MainWindow::exitApplication(), PreferenceDialog::initializeWarningData(), updateData(), and PreferencesManager::writeWarningPreferences().
 {
     return _showCloseWarning;
 }
void UserPreferencesData::updateData (UserPreferencesData _newData)
This function is to update the data from another object.
Parameters
_newData
Definition at line 282 of file userpreferencesdata.cpp.
References getMeshViewerPath(), getPostProcessorViewerPath(), getRecentProjectsList(), getTemplateConfigPath(), getUserDefinedSolverPath(), isDefaultSolverEngineSelected(), isMultizoneSolverEngineSelected(), isVirtualSolverEngineSelected(), setDefaultSolverEngineSelected(), setMeshViewerPath(), setMultizoneSolverEngineSelected(), setPostProcessorViewerPath(), setRecentProjectsList(), setShowCloseProjectWarning(), setShowCloseWarning(), setTemplateConfigPath(), setUserDefinedSolverPath(), setVirtualSolverEngineSelected(), showCloseProjectWarning(), and showCloseWarning().
Referenced by EditHelper::launchPreferencesDialog().
 {
     setDefaultSolverEngineSelected(_newData.isDefaultSolverEngineSelected());
     setVirtualSolverEngineSelected(_newData.isVirtualSolverEngineSelected());
     setMultizoneSolverEngineSelected(_newData.isMultizoneSolverEngineSelected());
     setUserDefinedSolverPath(_newData.getUserDefinedSolverPath());
     setMeshViewerPath(_newData.getMeshViewerPath());
     setPostProcessorViewerPath(_newData. getPostProcessorViewerPath());
     setRecentProjectsList(_newData.getRecentProjectsList());
     setShowCloseWarning(_newData.showCloseWarning());
     setShowCloseProjectWarning(_newData.showCloseProjectWarning());
     setTemplateConfigPath(_newData.getTemplateConfigPath());
 }
Member Data Documentation
bool UserPreferencesData::_isDefaultSolverEngineSelected private
Definition at line 47 of file userpreferencesdata.h.
Referenced by isDefaultSolverEngineSelected(), setDefaultSolverEngineSelected(), setMultizoneSolverEngineSelected(), setUserDefinedSolverPath(), setVirtualSolverEngineSelected(), and UserPreferencesData().
bool UserPreferencesData::_isMultizoneSolverEngineSelected private
Definition at line 49 of file userpreferencesdata.h.
Referenced by isMultizoneSolverEngineSelected(), setDefaultSolverEngineSelected(), setMultizoneSolverEngineSelected(), setUserDefinedSolverPath(), setVirtualSolverEngineSelected(), and UserPreferencesData().
bool UserPreferencesData::_isVirtualSolverEngineSelected private
Definition at line 48 of file userpreferencesdata.h.
Referenced by isVirtualSolverEngineSelected(), setDefaultSolverEngineSelected(), setMultizoneSolverEngineSelected(), setUserDefinedSolverPath(), setVirtualSolverEngineSelected(), and UserPreferencesData().
QString UserPreferencesData::_meshViewerPath private
Definition at line 51 of file userpreferencesdata.h.
Referenced by getMeshViewerPath(), setMeshViewerPath(), and UserPreferencesData().
QString UserPreferencesData::_postProcessorViewerPath private
Definition at line 53 of file userpreferencesdata.h.
Referenced by getPostProcessorViewerPath(), setPostProcessorViewerPath(), and UserPreferencesData().
QStringList UserPreferencesData::_recentProjectsList private
Definition at line 54 of file userpreferencesdata.h.
Referenced by addProjectToList(), getRecentProjectsList(), and setRecentProjectsList().
bool UserPreferencesData::_showCloseProjectWarning private
Definition at line 58 of file userpreferencesdata.h.
Referenced by setShowCloseProjectWarning(), showCloseProjectWarning(), and UserPreferencesData().
bool UserPreferencesData::_showCloseWarning private
Definition at line 57 of file userpreferencesdata.h.
Referenced by setShowCloseWarning(), showCloseWarning(), and UserPreferencesData().
QString UserPreferencesData::_templateConfigPath private
Definition at line 61 of file userpreferencesdata.h.
Referenced by getTemplateConfigPath(), setTemplateConfigPath(), and UserPreferencesData().
QString UserPreferencesData::_userDefinedSolverPath private
Definition at line 52 of file userpreferencesdata.h.
Referenced by getUserDefinedSolverPath(), setUserDefinedSolverPath(), and UserPreferencesData().
The documentation for this class was generated from the following files:
Data/PreferencesData/userpreferencesdata.h
Data/PreferencesData/userpreferencesdata.cpp