BBIPED Platform: SalomeTemplateData Class Reference
SalomeTemplateData Class Reference
#include <salometemplatedata.h>
Public Member Functions
SalomeTemplateData ()
Constructor.
SalomeVariableData findByName (QString _name)
Find any SalomeVariable Data by his name.
QString getTemplateFileName ()
Gets the name of the file associated to the template.
QString getTemplateName ()
Gets the template Name (the one shown to the user)
QList< SalomeVariableData > getVariableList ()
Get the list of variables of the template.
bool isEmpty ()
Checks if the template does not exist (template name, file name and variablelist empty or null)
void setTemplateFileName (QString _name)
Sets the name of the file associated to the template.
void setTemplateName (QString _name)
Sets the name of the template (the one shown to the user)
void setVariableList (QList< SalomeVariableData > _list)
Set the list of variables within the template.
Private Member Functions
QString removeWhiteSpaces (QString _str)
Remove wite spaces of any QString.
Private Attributes
QString _templateFileName
QString _templateName
QList< SalomeVariableData > _variableList
Detailed Description
Definition at line 6 of file salometemplatedata.h.
Constructor & Destructor Documentation
SalomeTemplateData::SalomeTemplateData ()
Constructor.
Definition at line 24 of file salometemplatedata.cpp.
References _templateFileName, _templateName, and _variableList.
 {
     _templateName ="";
     _templateFileName ="";
     _variableList.clear();
 }
Member Function Documentation
SalomeVariableData SalomeTemplateData::findByName (QString _name)
Find any SalomeVariable Data by his name.
Parameters
_name
Returns
SalomeVariableData
Definition at line 124 of file salometemplatedata.cpp.
References _variableList, SalomeVariableData::getName(), and StrEqual.
Referenced by SalomeOptimizationDialog::getVariablesList().
 {
     SalomeVariableData _foundResult;
     if (!_variableList.isEmpty())
     {
         for (int i = 0; i < _variableList.size();i++)
         {
             SalomeVariableData _cVar = _variableList.at(i);
             QString _varName = _cVar.getName();
             if (QString::compare(_varName,_name) == StrEqual)
                 return _cVar;
         }
     }
     return _foundResult;
 }
QString SalomeTemplateData::getTemplateFileName ()
Gets the name of the file associated to the template.
Returns
QString
Definition at line 55 of file salometemplatedata.cpp.
References _templateFileName.
Referenced by SalomePythonFileUtil::buildMain(), SalomePythonFileUtil::buildMainForOptimization(), SalomeTemplateManager::getTemplateFileNameByTemplateName(), and SalomeTemplateManager::saveTemplateData().
 {
     return _templateFileName;
 }
QString SalomeTemplateData::getTemplateName ()
Gets the template Name (the one shown to the user)
Returns
QString
Definition at line 35 of file salometemplatedata.cpp.
References _templateName.
Referenced by SalomeTemplateManager::buildTemplateData(), SalomeTemplateManager::saveTemplateData(), and SalomeTemplateManager::updateTemplateNameList().
 {
     return _templateName;
 }
QList< SalomeVariableData > SalomeTemplateData::getVariableList ()
Get the list of variables of the template.
Returns
QList<SalomeVariableData>
Definition at line 76 of file salometemplatedata.cpp.
References _variableList.
Referenced by SalomeTemplateDialog::createTemplateFromUserValues(), SalomeTemplateDialog::fillTable(), SalomeOptimizationDialog::fillTable(), SalomePythonFileUtil::getVariablesFromTemplate(), SalomeTemplateDialog::resetValuesToDefault(), SalomeTemplateManager::restoreToDefaultTemplate(), SalomeTemplateManager::saveTemplateData(), and SalomeTemplateDialog::updateTemplateValues().
 {
     return _variableList;
 }
bool SalomeTemplateData::isEmpty ()
Checks if the template does not exist (template name, file name and variablelist empty or null)
Returns
bool
Definition at line 97 of file salometemplatedata.cpp.
References _templateFileName, _templateName, and _variableList.
Referenced by SalomeToolCreateMeshDialog::on_createMeshButton_clicked(), SalomeTemplateDialog::on_createMeshButton_clicked(), and SalomeTemplateManager::restoreToDefaultTemplate().
 {
     if ((_templateName.isEmpty()) && (_templateFileName.isEmpty()) && (_variableList.isEmpty()))
         return true;
     else
         return false;
 }
QString SalomeTemplateData::removeWhiteSpaces (QString _str) private
Remove wite spaces of any QString.
Parameters
_str
Returns
QString
Definition at line 110 of file salometemplatedata.cpp.
Referenced by setTemplateFileName().
 {
     _str = _str.simplified();
     _str.replace( " ", "" );
     return _str;
 }
void SalomeTemplateData::setTemplateFileName (QString _name)
Sets the name of the file associated to the template.
Parameters
_name
Definition at line 65 of file salometemplatedata.cpp.
References _templateFileName, and removeWhiteSpaces().
Referenced by SalomeTemplateManager::buildTemplateData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _templateFileName = removeWhiteSpaces(_name);
 }
void SalomeTemplateData::setTemplateName (QString _name)
Sets the name of the template (the one shown to the user)
Parameters
_name
Definition at line 45 of file salometemplatedata.cpp.
References _templateName.
Referenced by SalomeTemplateManager::buildTemplateData(), and SalomeTemplateDialog::createTemplateFromUserValues().
 {
     _templateName = _name;
 }
void SalomeTemplateData::setVariableList (QList< SalomeVariableData > _list)
Set the list of variables within the template.
Parameters
_list
Definition at line 86 of file salometemplatedata.cpp.
References _variableList.
Referenced by SalomeTemplateManager::buildVariableList(), SalomeTemplateDialog::createTemplateFromUserValues(), SalomeTemplateManager::restoreToDefaultTemplate(), and SalomeTemplateDialog::updateTemplateValues().
 {
     _variableList = _list;
 }
Member Data Documentation
QString SalomeTemplateData::_templateFileName private
Definition at line 26 of file salometemplatedata.h.
Referenced by getTemplateFileName(), isEmpty(), SalomeTemplateData(), and setTemplateFileName().
QString SalomeTemplateData::_templateName private
Definition at line 25 of file salometemplatedata.h.
Referenced by getTemplateName(), isEmpty(), SalomeTemplateData(), and setTemplateName().
QList<SalomeVariableData> SalomeTemplateData::_variableList private
Definition at line 27 of file salometemplatedata.h.
Referenced by findByName(), getVariableList(), isEmpty(), SalomeTemplateData(), and setVariableList().
The documentation for this class was generated from the following files:
Data/SalomeTemplateData/salometemplatedata.h
Data/SalomeTemplateData/salometemplatedata.cpp