BBIPED Platform: OutputSolverParser Class Reference
OutputSolverParser Class Reference
#include <outputsolverparser.h>
Public Member Functions
OutputSolverParser ()
Constructor.
void checkWhenDataToPaintAvailable (QString _line)
Returns true if the line contains data available to be parsed.
bool getStartParsing ()
Returns if the parsing has already started.
void parseOutput (SolverResidualVO *_residualObj, QString _line)
Function that performs the parsing of the line to extract the values.
Private Member Functions
QStringList buildResidualList (QList< bool > _validVal, QStringList _list)
QStringList checkNanValues (SolverResidualVO *_residualOb, QStringList _list)
void fillResidualObject (SolverResidualVO *_residualOb, QStringList _list)
Function that fills the object with the parsed values.
QList< bool > getValidElementsToPrint (SolverResidualVO *_residualOb)
void identifyNoElementsToPlot (QStringList _list, SolverResidualVO *_residualObj)
bool isValidLine (QStringList _list)
bool valueIsNan (QString _val)
Private Attributes
bool _identifiedNoElementsToPlot
QList< int > _nanPositions
bool _startParsing
Detailed Description
Definition at line 6 of file outputsolverparser.h.
Constructor & Destructor Documentation
OutputSolverParser::OutputSolverParser ()
Constructor.
Definition at line 29 of file outputsolverparser.cpp.
 {
     _startParsing = false;
     _identifiedNoElementsToPlot = false;
 }
Member Function Documentation
QStringList OutputSolverParser::buildResidualList (QList< bool > _validVal, QStringList _list) private
Parameters
_validVal
_list
Returns
QStringList
Definition at line 231 of file outputsolverparser.cpp.
 {
     QStringList _newList;
     int _cPos = 0;
     for (int i = 0; i < _validVal.size();i++)
     {
        bool _printable = _validVal.at(i);
        if ( (_printable) && (_cPos < _list.size()) )
         {
            _newList.append(_list.at(_cPos));
            _cPos++;
         }
         else
             _newList.append("nan");
     }
     return _newList;
 }
QStringList OutputSolverParser::checkNanValues (SolverResidualVO * _residualOb, QStringList _list) private
Definition at line 256 of file outputsolverparser.cpp.
References SolverResidualVO::getCliftTotalEnabled(), SolverResidualVO::getDragTotalEnabled(), SolverResidualVO::getIterationEnabled(), SolverResidualVO::getResRhoeEnabled(), SolverResidualVO::getResRhoEnabled(), SolverResidualVO::getTimeEnabled(), SolverResidualVO::setCliftTotalEnabled(), SolverResidualVO::setDragTotalEnabled(), SolverResidualVO::setIterationEnabled(), SolverResidualVO::setResRhoeEnabled(), SolverResidualVO::setResRhoEnabled(), and SolverResidualVO::setTimeEnabled().
 {
     // TODO completarlo para cuando la lista sea menor a 6 elementos
     QStringList _newList;
     QList<bool> _printableElements = getValidElementsToPrint(_residualOb);
     // If we only have Iter, we cannot print
     if (_list.size() <=1)
         return _newList;
     if (_list.size()< 6)
         _list = buildResidualList(_printableElements,_list);
     if (_list.size() >= 6)
     {
     // Adding the correspondent values
         if (_residualOb->getIterationEnabled())
         {
             if (!valueIsNan(_list.at(0)))
                 _newList.append(_list.at(0));
             else
                 _residualOb->setIterationEnabled(false);
         }
         if (_residualOb->getTimeEnabled())
         {
             if (!valueIsNan(_list.at(1)))
                 _newList.append(_list.at(1));
             else
                 _residualOb->setTimeEnabled(false);
         }
         if (_residualOb->getResRhoEnabled())
         {
             if (!valueIsNan(_list.at(2)))
                   _newList.append(_list.at(2));
             else
                 _residualOb->setResRhoEnabled(false);
         }
         if (_residualOb->getResRhoeEnabled())
         {
             if (!valueIsNan(_list.at(3)))
                 _newList.append(_list.at(3));
             else
                 _residualOb->setResRhoeEnabled(false);
         }
         if (_residualOb->getCliftTotalEnabled())
         {
             if (!valueIsNan(_list.at(4)))
                 _newList.append(_list.at(4));
             else{
                 _residualOb->setCliftTotalEnabled(false);
             }
         }
         if (_residualOb->getDragTotalEnabled())
         {
             if (!valueIsNan(_list.at(5)))
                 _newList.append(_list.at(5));
             else
                 _residualOb->setDragTotalEnabled(false);
         }
     }
     return _newList;
 }
void OutputSolverParser::checkWhenDataToPaintAvailable (QString _line)
Returns true if the line contains data available to be parsed.
Parameters
_line
Definition at line 52 of file outputsolverparser.cpp.
Referenced by MainWindow::outlog().
 {
     if( (!_startParsing) && (!_line.isEmpty()) &&
             ((_line.contains("------------------------------ Start solver"))
              || (_line.contains("------------------------------ Begin solver")))
             || (_line.contains("Begin Solver")))
         _startParsing = true;
 }
void OutputSolverParser::fillResidualObject (SolverResidualVO * _residualOb, QStringList _list) private
Function that fills the object with the parsed values.
Parameters
_residualOb
_list
Definition at line 176 of file outputsolverparser.cpp.
References SolverResidualVO::fillValues().
 {
     if ((!_list.isEmpty()) && (_list.size() > 1) ) // At least, another parameter more than Iteration to draw
     {
         _list = checkNanValues(_residualOb,_list);
         if ( (!_list.isEmpty()) && (_list.size() > 1) )
             _residualOb->fillValues(_list);
     }
 }
bool OutputSolverParser::getStartParsing ()
Returns if the parsing has already started.
Returns
bool
Definition at line 42 of file outputsolverparser.cpp.
Referenced by MainWindow::outlog().
 {
     return _startParsing;
 }
QList< bool > OutputSolverParser::getValidElementsToPrint (SolverResidualVO * _residualOb) private
Parameters
_residualOb
Returns
QList<bool>
Definition at line 194 of file outputsolverparser.cpp.
References SolverResidualVO::getCliftTotalEnabled(), SolverResidualVO::getDragTotalEnabled(), SolverResidualVO::getIterationEnabled(), SolverResidualVO::getResRhoeEnabled(), SolverResidualVO::getResRhoEnabled(), and SolverResidualVO::getTimeEnabled().
 {
  QList<bool> _validElements;
  for (int i = 0; i < 6;i++)
  {
      switch (i)
      {
      case 0:
          _validElements.append(_residualOb->getIterationEnabled());
          break;
      case 1:
          _validElements.append(_residualOb->getTimeEnabled());
          break;
      case 2:
          _validElements.append(_residualOb->getResRhoEnabled());
          break;
      case 3:
          _validElements.append(_residualOb->getResRhoeEnabled());
          break;
      case 4:
          _validElements.append(_residualOb->getCliftTotalEnabled());
          break;
      case 5:
          _validElements.append(_residualOb->getDragTotalEnabled());
          break;
      }
  }
  return _validElements;
 }
void OutputSolverParser::identifyNoElementsToPlot (QStringList _list, SolverResidualVO * _residualObj) private
Parameters
_list
_residualObj
Definition at line 104 of file outputsolverparser.cpp.
References SolverResidualVO::enableAllValues(), SolverResidualVO::setCliftTotalEnabled(), SolverResidualVO::setDragTotalEnabled(), SolverResidualVO::setIterationEnabled(), SolverResidualVO::setResRhoeEnabled(), SolverResidualVO::setResRhoEnabled(), and SolverResidualVO::setTimeEnabled().
 {
     //qDebug("Identificando los elementos");
    /* if (!_list.empty())
         qDebug(QString("Numero elementos -->"+ QString::number(_list.count())).toLatin1());*/
     if ((!_list.isEmpty()) && (_list.count() <= 6))
     {
         //qDebug("Numero <6");
         //  Iter    Time(s)     Res[Rho]     Res[RhoE]   CLift(Total)   CDrag(Total)
         if (!_list.contains("Iter"))
             _residualObj->setIterationEnabled(false);
         if (!_list.contains("Time(s)")) // tengo que poner Time(s)
             _residualObj->setTimeEnabled(false);
         if (!_list.contains("Res[Rho]"))
             _residualObj->setResRhoEnabled(false);
         if (!_list.contains("Res[RhoE]"))
             _residualObj->setResRhoeEnabled(false);
         if (!_list.contains("CLift(Total)"))
             _residualObj->setCliftTotalEnabled(false);
         if (!_list.contains("CDrag(Total)"))
             _residualObj->setDragTotalEnabled(false);
     }else
         if ((!_list.isEmpty()) && (_list.count() >= 6))
         {
               //qDebug("Numero >= 6");
               _residualObj->enableAllValues();
         }
     _identifiedNoElementsToPlot = true;
 }
bool OutputSolverParser::isValidLine (QStringList _list) private
Parameters
_list
Returns
bool
Definition at line 141 of file outputsolverparser.cpp.
References StrEqual.
 {
     bool _isValid = true;
     //qDebug("Mira si es valida la linea");
     for (int i = 0; (i < _list.size() && (i <= 6));i++)
     {
         bool _isInteger;
         bool _isDouble;
         bool _isInf = false;
         bool _isNan = false;
         if ((QString::compare( _list.at(i),"inf") == StrEqual) || (QString::compare( _list.at(i),"-inf") == StrEqual) )
             _isInf = true;
         if ( (QString::compare( _list.at(i),"nan") == StrEqual) || (QString::compare( _list.at(i),"-nan") == StrEqual) )
             _isNan = true;
        int _val1 = _list.at(i).toInt(&_isInteger);
        double _val2 = _list.at(i).toDouble(&_isDouble);
         if ( (!_isInteger) && (!_isDouble) && (!_isInf) && (!_isNan) )
         {
           //  qDebug("es faaaalso");
             return false;
         }
     }
     return _isValid;
 }
void OutputSolverParser::parseOutput (SolverResidualVO * _residualObj, QString _line)
Function that performs the parsing of the line to extract the values.
Parameters
_residualObj
_line
Definition at line 67 of file outputsolverparser.cpp.
Referenced by MainWindow::outlog().
 {
     _line = _line.simplified();
    // qDebug( "[1]LINE PARSED" + _line.toLatin1());
     if (!_line.isEmpty())
     {
        // qDebug("[2]Analizando la linea"+ _line.toLatin1() );
         _line = _line.simplified();
         _line.replace(" ",";");
         QStringList _numList = _line.split(";");
         if ( (!_identifiedNoElementsToPlot) && (_line.contains("Iter")) )
             identifyNoElementsToPlot(_numList,_residualObj);
         // Filling the object
         if ( (_identifiedNoElementsToPlot) && (!_line.contains("Iter")) && (!_line.contains("Exit")) )
         {
             //qDebug("Mirando si rellenar el objeto");
             if ( (!_numList.isEmpty())  && (_numList.size() > 1) && (isValidLine(_numList)))
             {
               //  qDebug("Objeto relleno");
                 fillResidualObject(_residualObj,_numList);
             }
         }
     }
 }
bool OutputSolverParser::valueIsNan (QString _val) private
Definition at line 323 of file outputsolverparser.cpp.
References StrEqual.
 {
     bool _result = false;
     bool _isaInteger;
     bool _isADouble;
    _val.toInt(&_isaInteger);
     _val.toDouble(&_isADouble);
     if ((!_isaInteger) && (!_isADouble) )
         return true;
     if ((QString::compare(_val,"inf") == StrEqual) || (QString::compare(_val,"-inf") == StrEqual) )
         return true;
     if ( (QString::compare(_val,"nan") == StrEqual) || (QString::compare(_val,"-nan") == StrEqual) )
         return true;
     return _result;
 }
Member Data Documentation
bool OutputSolverParser::_identifiedNoElementsToPlot private
Definition at line 16 of file outputsolverparser.h.
QList<int> OutputSolverParser::_nanPositions private
Definition at line 17 of file outputsolverparser.h.
bool OutputSolverParser::_startParsing private
Definition at line 15 of file outputsolverparser.h.
The documentation for this class was generated from the following files:
Parser/Solver/outputsolverparser.h
Parser/Solver/outputsolverparser.cpp