BBIPED Platform: MultizoneManager Class Reference
MultizoneManager Class Reference
#include <multizonemanager.h>
Public Member Functions
MultizoneManager ()
CONSTRUCTOR.
void buildProjectDataForMultizoneProject (QString _newConfigFile, MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData)
This function builds the project data for a specific config file in a multizone project.
void changeTabViewToMultizoneProject (MultizoneProjectData *_multizoneProjectData)
This function changes the tab view.
void createInitialProjectDataForMultizoneProject (ProjectData *_projectData, MultizoneProjectData *_multizoneProjectData)
This function create the initial data for the multizone project.
bool isUIRegistered ()
This function returns true if the UI elements are registered.
bool launchMultizoneDialog (MultizoneProjectData *_multizoneProjectData, UserPreferencesData *_userPreferencesData, ProjectData *_projectData)
Launch Multizone Dialog.
bool openMultizoneProject (QString _projectFilePath, MultizoneProjectData *_multizoneProjectData, UserPreferencesData *_userPreferencesData, ProjectData *_projectData, ProjectDetails *_projectDetails)
Open Multizone Project Dialog.
void refreshSimulationFilesView (MultizoneProjectData *_multizoneProjectData)
This function refresh the Simulation files.
void registerUIElements (QPushButton *_button, QPushButton *_meshButton, QLabel *_confLabel, QLabel *_meshLabel, QAction *_runAction, QAction *_compareConfigFilesAction, QGroupBox *_viewGB, QGroupBox *_meshProperties, QLabel *_confLineLabel, QLabel *_meshLineLabel, QTreeView *_tree)
This function register all the elements of the UI.
void restoreTabViewToGeneralProject ()
This funciton restores the GUI to the single view.
void updateConfigFileNameinTabView (QString _file)
This function update the fields of the configuration file.
void updateMeshFileNameinTabView (QString _file)
This function updata the fields of the mehs file.
void updateMultiZoneValues (QString _filePath, int _option, MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData, bool _isNewConfigFile)
This function update the data in Multizone Projects.
void updateOpenEditConfigFile (QString _newConfigFile, MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData, bool _isNewConfigFile)
Update the Open Edit config file view.
void updateViewForNewFile (QString _newFile, int _optionMultizone, MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData, bool _isNewConfigFile)
Update the view for a new file.
Private Types
enum ActionNames
enum ButtonNames
enum GroupBoxNames
enum LabelLineNames
Private Member Functions
bool checkProjectBasePathConsistency (MultizoneProjectData *_multizoneProjectData, QString _currentFilePath)
Check for the paths of the project (import project) and update it if needed.
int getConfigurationFilePosition (MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData)
This function gets the id (position in the list) of the configuration file.
int getPositionToAddFileMultizone (MultizoneProjectData *_multizoneProjectData)
This function gets the position for the lists to add a new file controlling the fact that the list can have different sizes.
QStringList updateFilePaths (QStringList _listNames, QString _cPathRoot)
Update file paths.
Private Attributes
QList< QAction * > _registeredActions
QList< QPushButton * > _registeredButton
QList< QGroupBox * > _registeredGroupBox
QList< QLabel * > _registeredLabels
QList< QLineEdit * > _registeredLineEdit
ProjectMenuTreeHelper _treeHelper
bool _uiRegistered
Detailed Description
Definition at line 19 of file multizonemanager.h.
Member Enumeration Documentation
enum MultizoneManager::ActionNames private
Enumerator
runAction
compareConfigFileAction
Definition at line 70 of file multizonemanager.h.
                     {
         runAction = 0,
         compareConfigFileAction = 1
     };
enum MultizoneManager::ButtonNames private
Enumerator
runSimulation
meshProp
meshRefresh
Definition at line 81 of file multizonemanager.h.
                     {
         runSimulation = 0,
         meshProp = 1,
         meshRefresh = 2
     };
enum MultizoneManager::GroupBoxNames private
Enumerator
filesGroupBox
viewGroupBox
meshProperties
Definition at line 75 of file multizonemanager.h.
                       {
         filesGroupBox = 0,
         viewGroupBox = 1,
         meshProperties = 2
     };
enum MultizoneManager::LabelLineNames private
Enumerator
confPos
meshPos
Definition at line 66 of file multizonemanager.h.
{
         confPos = 2, //0
         meshPos =3 //1
     };
Constructor & Destructor Documentation
MultizoneManager::MultizoneManager ()
CONSTRUCTOR.
Definition at line 32 of file multizonemanager.cpp.
References _uiRegistered.
 {
     _uiRegistered = false;
 }
Member Function Documentation
void MultizoneManager::buildProjectDataForMultizoneProject (QString _newConfigFile, MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData)
This function builds the project data for a specific config file in a multizone project.
Parameters
_newConfigFile
Definition at line 264 of file multizonemanager.cpp.
References MultizoneProjectData::getListConfigFiles(), MultizoneProjectData::getListMeshFiles(), MultizoneProjectData::isEmpty(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), and SolverVO::setSolverFilePath().
Referenced by MainWindow::openSolverConfigurationFileDialog().
 {
     SolverVO _newSolverVO;
     _newSolverVO.setSolverConfigFilePath(_newConfigFile);
     if (!_multizoneProjectData->isEmpty())
     {
         QStringList _listFiles = _multizoneProjectData->getListConfigFiles();
         if (_listFiles.contains(_newConfigFile))
         {
             int _posFile = _listFiles.indexOf(_newConfigFile,0);
             if (_posFile != -1)
             {
                 QStringList _listMeshFiles = _multizoneProjectData->getListMeshFiles();
                 _newSolverVO.setSolverFilePath(_listMeshFiles.at(_posFile));
             }
         }
     }
      _projectData->setSolverDataInformation(_newSolverVO);
 }
void MultizoneManager::changeTabViewToMultizoneProject (MultizoneProjectData * _multizoneProjectData)
This function changes the tab view.
Parameters
_multizoneProjectData
Definition at line 114 of file multizonemanager.cpp.
References _registeredActions, _registeredButton, _registeredGroupBox, _registeredLabels, compareConfigFileAction, confPos, filesGroupBox, meshPos, refreshSimulationFilesView(), runAction, and runSimulation.
Referenced by launchMultizoneDialog(), and openMultizoneProject().
 {
     _registeredButton.at(runSimulation)->setText("Run Multizone Simulation");
     _registeredLabels.at(confPos)->setText("Multizone Configuration Files");
     _registeredLabels.at(meshPos)->setText("Multizone Mesh Files");
     _registeredActions.at(runAction)->setText("Run Multizone Simulation");
     _registeredActions.at(compareConfigFileAction)->setEnabled(true);
     _registeredGroupBox.at(filesGroupBox)->setTitle("Current Multizone Simulation Files");
     refreshSimulationFilesView(_multizoneProjectData);
 }
bool MultizoneManager::checkProjectBasePathConsistency (MultizoneProjectData * _multizoneProjectData, QString _currentFilePath) private
Check for the paths of the project (import project) and update it if needed.
Parameters
_multizoneProjectData
_currentFilePath
Returns
bool
Definition at line 211 of file multizonemanager.cpp.
References MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), MultizoneProjectData::getProjectPath(), MultizoneProjectData::setListConfigFiles(), MultizoneProjectData::setListMeshFiles(), MultizoneProjectData::setProjectPath(), StrEqual, TOOL4, and updateFilePaths().
Referenced by openMultizoneProject().
 {
     bool _statusNeedToBeSaved = false;
     QString _projectPath = _multizoneProjectData->getProjectPath();
     QString _cRootPath = QFileInfo(QFileInfo(_currentFilePath).path()).path();
     if (_projectPath.isNull())
         return _statusNeedToBeSaved;
     QFileInfo _basePathInfo(_projectPath);
     QString _rootPath = _basePathInfo.path();
     QString _projectBaseName = _basePathInfo.fileName();
     if (QString::compare(_rootPath, _cRootPath) != StrEqual)
     {
         QString _updatedProjectPath = QDir(_cRootPath).filePath(_projectBaseName);
         _multizoneProjectData->setProjectPath(_updatedProjectPath);
         QString _newProjectPathFiles = QDir(_updatedProjectPath).filePath(TOOL4);
         // Update Configuration Files
         _multizoneProjectData->setListConfigFiles(updateFilePaths(_multizoneProjectData->getListConfigFileNames(), _newProjectPathFiles));
         _multizoneProjectData->setListMeshFiles(updateFilePaths(_multizoneProjectData->getListMeshFileNames(), _newProjectPathFiles));
         _statusNeedToBeSaved = true;
     }
     return _statusNeedToBeSaved;
 }
void MultizoneManager::createInitialProjectDataForMultizoneProject (ProjectData * _projectData, MultizoneProjectData * _multizoneProjectData)
This function create the initial data for the multizone project.
Parameters
_projectData
_multizoneProjectData
Definition at line 103 of file multizonemanager.cpp.
References MultizoneProjectData::getProjectName(), MultizoneProjectData::getProjectPath(), ProjectData::setProjectFileName(), and ProjectData::setProjectPath().
Referenced by launchMultizoneDialog(), and openMultizoneProject().
{
     _projectData->setProjectPath(_multizoneProjectData->getProjectPath());
     _projectData->setProjectFileName(_multizoneProjectData->getProjectName());
 }
int MultizoneManager::getConfigurationFilePosition (MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData) private
This function gets the id (position in the list) of the configuration file.
Returns
int
Definition at line 364 of file multizonemanager.cpp.
References MultizoneProjectData::getListConfigFiles(), SolverVO::getSolverConfigFilePath(), and ProjectData::getSolverDataInformation().
Referenced by updateMultiZoneValues().
 {
     QString _name =  _projectData->getSolverDataInformation().getSolverConfigFilePath();
     if (_multizoneProjectData->getListConfigFiles().contains(_name))
         return _multizoneProjectData->getListConfigFiles().indexOf(_name,0);
     return -1;
 }
int MultizoneManager::getPositionToAddFileMultizone (MultizoneProjectData * _multizoneProjectData) private
This function gets the position for the lists to add a new file controlling the fact that the list can have different sizes.
Returns
int
Definition at line 342 of file multizonemanager.cpp.
References MultizoneProjectData::getListConfigFiles(), and MultizoneProjectData::getListMeshFiles().
Referenced by updateMultiZoneValues().
 {
     int _result = -1;
     QStringList _listConfig = _multizoneProjectData->getListConfigFiles();
     QStringList _listMesh = _multizoneProjectData->getListMeshFiles();
     if (_listConfig.size() == _listMesh.size())
         return (_listConfig.count());
     if (_listConfig.size() > _listMesh.size())
         return (_listConfig.count() - 1);
     if (_listConfig.size() < _listMesh.size())
         return (_listMesh.count() - 1);
     return _result;
 }
bool MultizoneManager::isUIRegistered ()
This function returns true if the UI elements are registered.
Returns
bool
Definition at line 42 of file multizonemanager.cpp.
References _uiRegistered.
Referenced by MainWindow::on_actionNew_Multizone_Project_triggered(), and MainWindow::on_actionOpen_Multizone_Project_triggered().
 {
     return _uiRegistered;
 }
bool MultizoneManager::launchMultizoneDialog (MultizoneProjectData * _multizoneProjectData, UserPreferencesData * _userPreferencesData, ProjectData * _projectData)
Launch Multizone Dialog.
Parameters
_multizoneProjectData
_userPreferencesData
_projectData
Returns
bool
Definition at line 150 of file multizonemanager.cpp.
References _treeHelper, UserPreferencesData::addProjectToList(), changeTabViewToMultizoneProject(), createInitialProjectDataForMultizoneProject(), ProjectMenuTreeHelper::fillProjectTreeView(), MultizoneProjectDialog::getMultizoneProjectData(), MultizoneProjectData::getProjectPath(), and MultizoneProjectDialog::isMultizoneProjectCreated().
Referenced by MainWindow::on_actionNew_Multizone_Project_triggered().
 {
     MultizoneProjectDialog _multizoneDiag;
     _multizoneDiag.exec();
     bool _multizoneProjectCreated = false;
     if (_multizoneDiag.isMultizoneProjectCreated())
     {
         // Updating the data
         (* _multizoneProjectData) =  _multizoneDiag.getMultizoneProjectData();
         _userPreferencesData->addProjectToList(_multizoneProjectData->getProjectPath());
         changeTabViewToMultizoneProject(_multizoneProjectData);
         createInitialProjectDataForMultizoneProject(_projectData,_multizoneProjectData);
         // Filling the Tree
         //ProjectMenuTreeHelper _treeHelper;
         _treeHelper.fillProjectTreeView(_multizoneProjectData->getProjectPath());//,_registeredTreeView);
         _multizoneProjectCreated = true;
     }
     return _multizoneProjectCreated;
 }
bool MultizoneManager::openMultizoneProject (QString _projectFilePath, MultizoneProjectData * _multizoneProjectData, UserPreferencesData * _userPreferencesData, ProjectData * _projectData, ProjectDetails * _projectDetails)
Open Multizone Project Dialog.
Parameters
_projectFilePath
_multizoneProjectData
_userPreferencesData
_projectData
_projectDetails
Returns
bool
Definition at line 185 of file multizonemanager.cpp.
References _treeHelper, UserPreferencesData::addProjectToList(), changeTabViewToMultizoneProject(), checkProjectBasePathConsistency(), createInitialProjectDataForMultizoneProject(), ProjectMenuTreeHelper::fillProjectTreeView(), MultizoneProjectData::getProjectPath(), UtilFiles::openMultizoneProjectStructure(), and UtilFiles::openProjectDetails().
Referenced by MainWindow::on_actionOpen_Multizone_Project_triggered().
 {
     UtilFiles _utilFiles;
     (*_multizoneProjectData) = _utilFiles.openMultizoneProjectStructure(_projectFilePath);
     bool _statusNeedToBeSaved = checkProjectBasePathConsistency(_multizoneProjectData,_projectFilePath);
     (* _projectDetails) = _utilFiles.openProjectDetails(_projectFilePath);
     _userPreferencesData->addProjectToList(_multizoneProjectData->getProjectPath());
     // Show Tree menu elements
    // ProjectMenuTreeHelper _treeHelper;
     _treeHelper.fillProjectTreeView(_multizoneProjectData->getProjectPath());//,_registeredTreeView);
     // Enabling all the buttons
    changeTabViewToMultizoneProject(_multizoneProjectData);
    createInitialProjectDataForMultizoneProject(_projectData,_multizoneProjectData);
    return _statusNeedToBeSaved;
 }
void MultizoneManager::refreshSimulationFilesView (MultizoneProjectData * _multizoneProjectData)
This function refresh the Simulation files.
Definition at line 129 of file multizonemanager.cpp.
References _registeredLabels, COMMA_SEPARATOR, confPos, MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), MultizoneProjectData::isEmpty(), and meshPos.
Referenced by changeTabViewToMultizoneProject(), MainWindow::launchActionProjectSettingsDialog(), updateOpenEditConfigFile(), and updateViewForNewFile().
 {
     if (!_multizoneProjectData->isEmpty())
     {
         _registeredLabels.at(confPos)->setText(_multizoneProjectData->getListConfigFileNames().join(COMMA_SEPARATOR));
         _registeredLabels.at(meshPos)->setText(_multizoneProjectData->getListMeshFileNames().join(COMMA_SEPARATOR));
      /*  _registeredLineEdit.at(confPos)->setText(_multizoneProjectData->getListConfigFileNames().join(COMMA_SEPARATOR));
        _registeredLineEdit.at(meshPos)->setText(_multizoneProjectData->getListMeshFileNames().join(COMMA_SEPARATOR));
        */
     }
 }
void MultizoneManager::registerUIElements (QPushButton * _button, QPushButton * _meshButton, QLabel * _confLabel, QLabel * _meshLabel, QAction * _runAction, QAction * _compareConfigFilesAction, QGroupBox * _viewGB, QGroupBox * _meshProperties, QLabel * _confLineLabel, QLabel * _meshLineLabel, QTreeView * _tree)
This function register all the elements of the UI.
Parameters
_button
_meshButton
_confLabel
_meshLabel
_runAction
_compareConfigFilesAction
_viewGB
_meshProperties
_configLineEdit
_meshLineEdit
_tree
Definition at line 62 of file multizonemanager.cpp.
References _registeredActions, _registeredButton, _registeredGroupBox, _registeredLabels, _treeHelper, _uiRegistered, and ProjectMenuTreeHelper::registerMenuTree().
Referenced by MainWindow::registerUIMultizoneElements().
 {
     _registeredButton.append(_button);
      _registeredButton.append(_meshButton);
    // _registeredButton.append(_meshRefresh);
     _registeredLabels.append(_confLabel);
     _registeredLabels.append(_meshLabel);
     _registeredLabels.append(_confLineLabel);
     _registeredLabels.append(_meshLineLabel);
     _registeredActions.append(_runAction);
     _registeredActions.append(_compareConfigFilesAction);
    // _registeredGroupBox.append(_filesGroupBox);
     _registeredGroupBox.append(_viewGB);
     _registeredGroupBox.append(_meshProperties);
    /* _registeredLineEdit.append(_configLineEdit);
     _registeredLineEdit.append(_meshLineEdit);
     */
     _treeHelper.registerMenuTree(_tree);
     //_registeredTreeView = _tree;
     _uiRegistered = true;
 }
void MultizoneManager::restoreTabViewToGeneralProject ()
This funciton restores the GUI to the single view.
Definition at line 402 of file multizonemanager.cpp.
References _registeredActions, _registeredButton, _registeredGroupBox, _registeredLabels, compareConfigFileAction, confPos, filesGroupBox, meshPos, meshProp, meshProperties, runAction, runSimulation, and viewGroupBox.
Referenced by MainWindow::closeProject().
 {
     _registeredButton.at(runSimulation)->setText("Run Simulation");
     _registeredButton.at(meshProp)->setEnabled(false);
     //_registeredButton.at(meshRefresh)->setEnabled(false);
     _registeredLabels.at(confPos)->setText("Configuration File");
     _registeredLabels.at(meshPos)->setText("Mesh File");
     _registeredActions.at(runAction)->setText("Run");
     _registeredActions.at(compareConfigFileAction)->setEnabled(false);
     _registeredGroupBox.at(filesGroupBox)->setTitle("Current Simulation Files");
     _registeredGroupBox.at(viewGroupBox)->setTitle("Physics Conditions");
     _registeredGroupBox.at(meshProperties)->setTitle("Boundary Conditions");
     _registeredLabels.at(confPos)->clear();
     _registeredLabels.at(meshPos)->clear();
  /*   _registeredLineEdit.at(confPos)->clear();
     _registeredLineEdit.at(meshPos)->clear();
     */
 }
void MultizoneManager::updateConfigFileNameinTabView (QString _file)
This function update the fields of the configuration file.
Parameters
_file
Definition at line 378 of file multizonemanager.cpp.
References _registeredGroupBox, and viewGroupBox.
Referenced by MainWindow::launchActionProjectSettingsDialog(), updateOpenEditConfigFile(), and updateViewForNewFile().
 {
     QFileInfo _fileInfo(_file);
     QString _fileName = _fileInfo.fileName();
     _registeredGroupBox.at(viewGroupBox)->setTitle("Physics Conditions: ["+_fileName+"]");
 }
QStringList MultizoneManager::updateFilePaths (QStringList _listNames, QString _cPathRoot) private
Update file paths.
Parameters
_listNames
_cPathRoot
Returns
QStringList
Definition at line 244 of file multizonemanager.cpp.
Referenced by checkProjectBasePathConsistency().
 {
     QStringList _updatedList;
     if (!_listNames.isEmpty())
     {
         for (int i= 0; i < _listNames.size();i++)
         {
             QString _fileName = _listNames.at(i);
             QString _newPath = QDir(_cPathRoot).filePath(_fileName);
             _updatedList.append(_newPath);
         }
     }
     return _updatedList;
 }
void MultizoneManager::updateMeshFileNameinTabView (QString _file)
This function updata the fields of the mehs file.
Parameters
_file
Definition at line 390 of file multizonemanager.cpp.
References _registeredButton, _registeredGroupBox, meshProp, and meshProperties.
Referenced by MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_newActionButton_clicked(), updateOpenEditConfigFile(), and updateViewForNewFile().
 {
     QFileInfo _fileInfo(_file);
     QString _fileName = _fileInfo.fileName();
     _registeredGroupBox.at(meshProperties)->setTitle("Boundary Conditions: ["+_fileName+"]");
     _registeredButton.at(meshProp)->setEnabled(true);
     //_registeredButton.at(meshRefresh)->setEnabled(true);
 }
void MultizoneManager::updateMultiZoneValues (QString _filePath, int _option, MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData, bool _isNewConfigFile)
This function update the data in Multizone Projects.
Parameters
_filePath
_option
Definition at line 290 of file multizonemanager.cpp.
References getConfigurationFilePosition(), MultizoneProjectData::getListConfigFiles(), MultizoneProjectData::getListMeshFiles(), getPositionToAddFileMultizone(), OptionMzConfigPath, OptionMzMeshPath, MultizoneProjectData::setListConfigFiles(), and MultizoneProjectData::setListMeshFiles().
Referenced by updateOpenEditConfigFile(), and updateViewForNewFile().
 {
     switch(_option)
     {
     case OptionMzConfigPath:
     {
         QStringList _listConfig = _multizoneProjectData->getListConfigFiles();
         if (!_listConfig.contains(_filePath))
         {
             int _posToAdd = getPositionToAddFileMultizone(_multizoneProjectData);
             if (_posToAdd != -1)
             {
                 if (_posToAdd >= _listConfig.size())
                     _listConfig.append(_filePath);
                 else
                     _listConfig[_posToAdd] = _filePath;
                 _multizoneProjectData->setListConfigFiles(_listConfig);
             }
         }
     }
         break;
     case OptionMzMeshPath:
     {
         QStringList _listMesh = _multizoneProjectData->getListMeshFiles();
         int _posToAdd = -1;
         if (_isNewConfigFile)
             _posToAdd = getPositionToAddFileMultizone(_multizoneProjectData);
         else
             _posToAdd = getConfigurationFilePosition(_multizoneProjectData,_projectData);
         if (_posToAdd != -1)
         {
             if (_posToAdd >= _listMesh.size())
                 _listMesh.append(_filePath);
             else
                 _listMesh[_posToAdd] = _filePath;
             _multizoneProjectData->setListMeshFiles(_listMesh);
         }
     }
         break;
     }
 }
void MultizoneManager::updateOpenEditConfigFile (QString _newConfigFile, MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData, bool _isNewConfigFile)
Update the Open Edit config file view.
Parameters
_newConfigFile
_multizoneProjectData
_projectData
_isNewConfigFile
Definition at line 465 of file multizonemanager.cpp.
References MultizoneProjectData::getListConfigFileNames(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), OptionMzConfigPath, OptionMzMeshPath, refreshSimulationFilesView(), updateConfigFileNameinTabView(), updateMeshFileNameinTabView(), and updateMultiZoneValues().
Referenced by MainWindow::on_actionSave_Configuration_File_As_triggered(), and MainWindow::openSolverConfigurationFileDialog().
 {
     updateConfigFileNameinTabView(_newConfigFile);
     updateMultiZoneValues(_newConfigFile, OptionMzConfigPath,_multizoneProjectData,_projectData, _isNewConfigFile);
     SolverVO _solverVO = _projectData->getSolverDataInformation();
     if (!_solverVO.getSolverFilePath().isEmpty())
     {
         updateMeshFileNameinTabView(_solverVO.getSolverFilePath());
         QStringList _listConfigFiles = _multizoneProjectData->getListConfigFileNames();
         if (!_listConfigFiles.contains(_newConfigFile))
             updateMultiZoneValues(_projectData->getSolverDataInformation().getSolverFilePath(), OptionMzMeshPath,
                                             _multizoneProjectData,_projectData, _isNewConfigFile);
     }
     refreshSimulationFilesView(_multizoneProjectData);
 }
void MultizoneManager::updateViewForNewFile (QString _newFile, int _optionMultizone, MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData, bool _isNewConfigFile)
Update the view for a new file.
Parameters
_newFile
_optionMultizone
_multizoneProjectData
_projectData
_isNewConfigFile
Definition at line 437 of file multizonemanager.cpp.
References OptionMzConfigPath, OptionMzMeshPath, refreshSimulationFilesView(), updateConfigFileNameinTabView(), updateMeshFileNameinTabView(), and updateMultiZoneValues().
Referenced by MainWindow::on_newActionButton_clicked(), and MainWindow::updateMeshView().
 {
     if (_optionMultizone == OptionMzConfigPath)
     {
       //  bool _existMeshInfo = checkOldMeshConfiguration();
        updateConfigFileNameinTabView(_newFile);
     }
     if (_optionMultizone == OptionMzMeshPath)
        updateMeshFileNameinTabView(_newFile);
     updateMultiZoneValues(_newFile, _optionMultizone,_multizoneProjectData,_projectData, _isNewConfigFile);
     refreshSimulationFilesView(_multizoneProjectData);
 }
Member Data Documentation
QList<QAction *> MultizoneManager::_registeredActions private
Definition at line 88 of file multizonemanager.h.
Referenced by changeTabViewToMultizoneProject(), registerUIElements(), and restoreTabViewToGeneralProject().
QList<QPushButton *> MultizoneManager::_registeredButton private
Definition at line 86 of file multizonemanager.h.
Referenced by changeTabViewToMultizoneProject(), registerUIElements(), restoreTabViewToGeneralProject(), and updateMeshFileNameinTabView().
QList<QGroupBox *> MultizoneManager::_registeredGroupBox private
Definition at line 89 of file multizonemanager.h.
Referenced by changeTabViewToMultizoneProject(), registerUIElements(), restoreTabViewToGeneralProject(), updateConfigFileNameinTabView(), and updateMeshFileNameinTabView().
QList<QLabel *> MultizoneManager::_registeredLabels private
Definition at line 87 of file multizonemanager.h.
Referenced by changeTabViewToMultizoneProject(), refreshSimulationFilesView(), registerUIElements(), and restoreTabViewToGeneralProject().
QList<QLineEdit *> MultizoneManager::_registeredLineEdit private
Definition at line 90 of file multizonemanager.h.
ProjectMenuTreeHelper MultizoneManager::_treeHelper private
Definition at line 93 of file multizonemanager.h.
Referenced by launchMultizoneDialog(), openMultizoneProject(), and registerUIElements().
bool MultizoneManager::_uiRegistered private
Definition at line 92 of file multizonemanager.h.
Referenced by isUIRegistered(), MultizoneManager(), and registerUIElements().
The documentation for this class was generated from the following files:
Multizone/multizonemanager.h
Multizone/multizonemanager.cpp