BBIPED Platform: EditHelper Class Reference
EditHelper Class Reference
#include <edithelper.h>
Public Member Functions
EditHelper ()
void launchPreferencesDialog (UserPreferencesData *_userPreferencesData, SolverConfigManager *_solverManager)
bool launchSettingsDialog (bool _isMultizoneProject, MultizoneProjectData *_multizoneProjectData, ProjectData *_projectData, ProjectDetails *_projectDetailsData)
Detailed Description
Definition at line 9 of file edithelper.h.
Constructor & Destructor Documentation
EditHelper::EditHelper ()
Definition at line 25 of file edithelper.cpp.
 {
 }
Member Function Documentation
void EditHelper::launchPreferencesDialog (UserPreferencesData * _userPreferencesData, SolverConfigManager * _solverManager)
Parameters
_userPreferencesData
_solverManager
Definition at line 37 of file edithelper.cpp.
References UserPreferencesData::getRecentProjectsList(), UserPreferencesData::getTemplateConfigPath(), PreferenceDialog::getUserPreferencesData(), PreferenceDialog::initialize(), PreferenceDialog::isPreferencesAccepted(), SolverConfigManager::resetPersonalizedMenu(), UserPreferencesData::setRecentProjectsList(), and UserPreferencesData::updateData().
Referenced by MainWindow::on_actionPreferences_triggered(), and MeshingToolConfigurationWarningDialog::on_warningMeshingButtonBox_accepted().
 {
     PreferenceDialog * _prefDialog =  new PreferenceDialog();
     _prefDialog->initialize(* _userPreferencesData);
     // Executing the Dialog
     _prefDialog->exec();
     // Updating the user values from the Dialog
     if  (_prefDialog->isPreferencesAccepted() )
     {
         UserPreferencesData _newData = _prefDialog->getUserPreferencesData();
         _newData.setRecentProjectsList(_userPreferencesData->getRecentProjectsList());
          _userPreferencesData->updateData(_newData);
         if (_userPreferencesData->getTemplateConfigPath().isEmpty())
             _solverManager->resetPersonalizedMenu();
     }
 }
bool EditHelper::launchSettingsDialog (bool _isMultizoneProject, MultizoneProjectData * _multizoneProjectData, ProjectData * _projectData, ProjectDetails * _projectDetailsData)
Parameters
_isMultizoneProject
_multizoneProjectData
_projectData
_projectDetailsData
Returns
bool
Definition at line 63 of file edithelper.cpp.
References ProjectSettingsDialog::getMultizoneProjectData(), ProjectSettingsDialog::getProjectData(), ProjectSettingsDialog::getProjectDetailsData(), ProjectSettingsDialog::setMultizoneProjectData(), ProjectSettingsDialog::setProjectData(), ProjectSettingsDialog::setProjectDetailsData(), MultizoneProjectData::updateMultizoneProjectData(), ProjectData::updateProjectData(), ProjectDetails::updateProjectDetails(), and ProjectSettingsDialog::userAcceptChanges().
Referenced by MainWindow::launchActionProjectSettingsDialog().
 {
     ProjectSettingsDialog _settingsDialog;
     // Loading the data
     if (!_isMultizoneProject)
         _settingsDialog.setProjectData(*_projectData);
     else
         _settingsDialog.setMultizoneProjectData(*_multizoneProjectData);
     _settingsDialog.setProjectDetailsData(*_projectDetailsData);
     // Executing
     _settingsDialog.exec();
     bool _changesDone = _settingsDialog.userAcceptChanges();;
     if (_changesDone)
     {
         if (_isMultizoneProject)
             _multizoneProjectData->updateMultizoneProjectData(_settingsDialog.getMultizoneProjectData());
         else
             _projectData->updateProjectData(_settingsDialog.getProjectData());
         _projectDetailsData->updateProjectDetails(_settingsDialog.getProjectDetailsData());
     }
     return _changesDone;
 }
The documentation for this class was generated from the following files:
WindowHelper/Menu/MenuHelpers/edithelper.h
WindowHelper/Menu/MenuHelpers/edithelper.cpp