BBIPED Platform: WarningClosingDialog Class Reference
WarningClosingDialog Class Reference
#include <warningclosingdialog.h>
Public Member Functions
WarningClosingDialog (QWidget *parent=0)
CONSTRUCTOR.
~WarningClosingDialog ()
DESTRUCTOR.
bool getShowAgainValue ()
Returns true if the window shall be shown again in the future.
bool needsToCloseApplication ()
Returns true if the application needs to be closed.
void setTitleMessage (QString _newTitle)
Establish the message title of the window.
Private Slots
void on_buttonBox_accepted ()
Function that controls when the user accepts.
void on_buttonBox_rejected ()
Function that controls when the user rejects.
void on_donotShowMessageCheckBox_clicked (bool checked)
Function that controls when the user decide not to show the message dialog again.
Private Attributes
bool _needToBeClosed
bool _showWindow
Ui::WarningClosingDialog * ui
Detailed Description
Definition at line 10 of file warningclosingdialog.h.
Constructor & Destructor Documentation
WarningClosingDialog::WarningClosingDialog (QWidget * parent = 0) explicit
CONSTRUCTOR.
Parameters
parent
Definition at line 25 of file warningclosingdialog.cpp.
References _needToBeClosed, _showWindow, and ui.
                                                           :
     QDialog(parent),
     ui(new Ui::WarningClosingDialog)
 {
     ui->setupUi(this);
     _needToBeClosed = false;
     _showWindow = true;
 }
WarningClosingDialog::~WarningClosingDialog ()
DESTRUCTOR.
Definition at line 38 of file warningclosingdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
bool WarningClosingDialog::getShowAgainValue ()
Returns true if the window shall be shown again in the future.
Returns
bool
Definition at line 101 of file warningclosingdialog.cpp.
References _showWindow.
Referenced by MainWindow::exitApplication(), and MainWindow::on_actionClose_Project_triggered().
 {
     return _showWindow;
 }
bool WarningClosingDialog::needsToCloseApplication ()
Returns true if the application needs to be closed.
Returns
bool
Definition at line 80 of file warningclosingdialog.cpp.
References _needToBeClosed.
Referenced by MainWindow::exitApplication(), and MainWindow::on_actionClose_Project_triggered().
 {
     return _needToBeClosed;
 }
void WarningClosingDialog::on_buttonBox_accepted () private slot
Function that controls when the user accepts.
Definition at line 47 of file warningclosingdialog.cpp.
References _needToBeClosed.
 {
     _needToBeClosed = true;
     close();
 }
void WarningClosingDialog::on_buttonBox_rejected () private slot
Function that controls when the user rejects.
Definition at line 57 of file warningclosingdialog.cpp.
 {
     close();
 }
void WarningClosingDialog::on_donotShowMessageCheckBox_clicked (bool checked) private slot
Function that controls when the user decide not to show the message dialog again.
Parameters
checked
Definition at line 68 of file warningclosingdialog.cpp.
References _showWindow.
 {
     _showWindow = !checked;
 }
void WarningClosingDialog::setTitleMessage (QString _newTitle)
Establish the message title of the window.
Parameters
_newTitle
Definition at line 90 of file warningclosingdialog.cpp.
References ui.
Referenced by MainWindow::on_actionClose_Project_triggered().
 {
     ui->titleMessage->setText(_newTitle);
 }
Member Data Documentation
bool WarningClosingDialog::_needToBeClosed private
Definition at line 30 of file warningclosingdialog.h.
Referenced by needsToCloseApplication(), on_buttonBox_accepted(), and WarningClosingDialog().
bool WarningClosingDialog::_showWindow private
Definition at line 31 of file warningclosingdialog.h.
Referenced by getShowAgainValue(), on_donotShowMessageCheckBox_clicked(), and WarningClosingDialog().
Ui::WarningClosingDialog* WarningClosingDialog::ui private
Definition at line 29 of file warningclosingdialog.h.
Referenced by setTitleMessage(), WarningClosingDialog(), and ~WarningClosingDialog().
The documentation for this class was generated from the following files:
Forms/WarningDialog/warningclosingdialog.h
Forms/WarningDialog/warningclosingdialog.cpp