BBIPED Platform: SolverMarkerMenuHelper Class Reference
SolverMarkerMenuHelper Class Reference
#include <solvermarkermenuhelper.h>
Public Member Functions
SolverMarkerMenuHelper ()
Constructor.
void addEditIconToColumn (QTableWidget *_table, int row, int _column)
This function adds a Edit Icon to the correspondent column in the row.
void addExtraColumn (QTableWidget *_table, int _lastColumn, QString _defaultVal)
This function adds an extra column.
void addMarkerMenu (QDomDocument *_rootTree, QDomDocument *_menuToFill)
This function adds the correspondent values in the tree view for the Marker Menu.
void addMarkerVariable (QTableWidget *_table, QString _varName, QStringList _list, bool _isMultizoneMarker)
This function creates the Row in the correspondent table for a Marker Variable.
bool checkMarkerMeshVariables (QHash< QString, QString > _userMarkers, QHash< QString, QString > _meshFileMarkers, QHash< QString, QString > *_markersConfig)
Function that cheks the Marker mesh variables.
bool checkMarkerMeshVariables (QHash< QString, QString > _userMarkers, QHash< QString, QString > _meshFileMarkers)
Function that cheks the Marker mesh variables.
void fillMarkerMenuTable (QString _parentName, QHash< QString, QString > _meshVariables, QTableWidget *_table, QList< SolverVariableVO > _list)
This funtcion allow to fill the specific marker menu table in the Solver Basic dialog.
void removeMarkerElementsFromConfigFile (QHash< QString, QString > *_mapValues)
This function removes the markers elements according to the map values.
Public Member Functions inherited from SolverConfigMenuHelper
SolverConfigMenuHelper ()
Constructor.
void addMenuElements (bool _basicView, QDomDocument *_configDomTree, QDomDocument *_menuToFill)
Function that add elements to the menu.
void addVariableToTable (SolverVariableVO _variable, QTableWidget *_table, int _row)
Function that adds the variable elements to each row in the table.
bool compareSectionTitle (QString _name, QDomElement _element)
functions that compares the section titles
void createNotVisibleSectionElement (QDomElement _element, QDomDocument *_tree)
Function that creates not visible section elements.
void createSectionElement (QDomElement _sectionElement, bool _basicView, QDomDocument *_menuList)
Function that creates section elements.
void createSectionElement (QDomElement _sectionElement, QDomDocument *_menuList)
void createSubSectionElements (QDomElement _element, QDomElement *_root, bool _basicView, QDomDocument *_menuList)
Function that creates a Subsection element.
void fillMenuTable (QString _parentName, QString _childName, QTableWidget *_table, QList< SolverVariableVO > _list)
Function that fills the menu table.
QDomElement findSectionElementByName (QString _sectionName, QDomNodeList _list)
Function that finds a section element by name.
QString getAssociatedFileNameValue (SolverVariableVO _solverVO, QString _value)
Function that gets the associated variable name in the file.
QString getAssociatedHelpText (QString _variableName, QList< SolverVariableVO > _list, bool _withFormat)
Function that gets the correspondent help text of a variable Name.
int getRowofVariable (QString _variableName, QTableWidget *_table)
Function that gets the number of the table's row of the correspondent variableName.
void getSectionMenuElements (QString _sectionName, QDomDocument *_confgiDomTree, QDomDocument *_menuToFill)
Function that creates those non visible section elements.
QString getSectionTitle (QDomElement _element)
function that gets section title from an XML DOM element
QStringList getSubsectionTitle (QDomElement _element)
Function that gets the subsection title.
void removeMenuElementByName (QString _name, QDomDocument *_tree)
Function that removes an elemente name by its name.
void removeSectionNode (QString _sectionName, QDomDocument *_tree)
Function that removes a Section from the Tree.
void removeSubsectionElementByName (QString _parentName, QString _childName, QDomDocument *_tree)
Removes teh correspondent subsection element.
void updateTableWithUserValues (SolverSectionVO _solverSecvo, QTableWidget *_table, QHash< QString, QString > _newMapValues)
Function that updates the table with the user values.
void updateVariableValueinTable (SolverVariableVO _solverVO, QTableWidget *_table, QString _newValue)
Function that updates the value in the table.
Detailed Description
Definition at line 12 of file solvermarkermenuhelper.h.
Constructor & Destructor Documentation
SolverMarkerMenuHelper::SolverMarkerMenuHelper ()
Constructor.
Definition at line 29 of file solvermarkermenuhelper.cpp.
 {
 }
Member Function Documentation
void SolverMarkerMenuHelper::addEditIconToColumn (QTableWidget * _table, int row, int _column)
This function adds a Edit Icon to the correspondent column in the row.
Parameters
_table
row
_column
Definition at line 153 of file solvermarkermenuhelper.cpp.
References QtableUtil::addEditIcon().
Referenced by MeshDialog::showValuesInValueCol().
 {
      QtableUtil _tableHelper;
         _table->setItem(row,_column,_tableHelper.addEditIcon());
 }
void SolverMarkerMenuHelper::addExtraColumn (QTableWidget * _table, int _column, QString _defaultVal)
This function adds an extra column.
Parameters
_table
_column
_defaultVal
Definition at line 139 of file solvermarkermenuhelper.cpp.
References QtableUtil::addNonEditableText().
Referenced by MeshDialog::fillTable().
 {
     QtableUtil _tableHelper;
     for (int i = 0; i < _table->rowCount();i++)
         _table->setItem(i,_column,_tableHelper.addNonEditableText(_defaultVal));
 }
void SolverMarkerMenuHelper::addMarkerMenu (QDomDocument * _rootTree, QDomDocument * _menuToFill)
This function adds the correspondent values in the tree view for the Marker Menu.
Parameters
_menuToFill
Definition at line 164 of file solvermarkermenuhelper.cpp.
References SolverConfigMenuHelper::createSectionElement(), SolverConfigMenuHelper::findSectionElementByName(), and MARKER_TITLE.
Referenced by SolverConfigManager::buildBoundaryMenuList().
 {
     SolverConfigMenuHelper _menuHelper;
     QDomElement _rootElement = _rootTree->documentElement();
     if (!_rootElement.isNull())
     {
         QDomNode _sectionsNode = _rootElement.firstChild();
         QDomNodeList _sectionList = _sectionsNode.childNodes();
         QDomElement _boundarySection = _menuHelper.findSectionElementByName(MARKER_TITLE,_sectionList);
         _menuHelper.createSectionElement(_boundarySection, _menuToFill);
     }
 }
void SolverMarkerMenuHelper::addMarkerVariable (QTableWidget * _table, QString _varName, QStringList _list, bool _isMultizoneMarker)
This function creates the Row in the correspondent table for a Marker Variable.
Parameters
_table
_varName
_list
Definition at line 100 of file solvermarkermenuhelper.cpp.
References QtableUtil::addChangedColumn(), QtableUtil::addCombo(), QtableUtil::addEditText2(), QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnCheck, ColumnSelVal, ColumnVarName, and MarkerColumnHelp.
Referenced by fillMarkerMenuTable().
 {
     int _lastRow =_table->rowCount();
     //-------------------------------------------------------------------------------------------------------------
     // For the marker menu we are assuming that always will be selectable. If not .. then we need to configure it
     QList<bool> _selectable;
     for (int i = 0; i< _list.size(); i++)
         _selectable.append(true);
     //-------------------------------------------------------------------------------------------------------------
     QtableUtil _tableHelper;
     _table->insertRow(_lastRow);
     _table->setItem(_lastRow,ColumnCheck,_tableHelper.addChangedColumn());
     if ((!_list.isEmpty()) && (!_isMultizoneMarker))
     {
         _table->setCellWidget(_lastRow,ColumnSelVal,_tableHelper.addCombo(_list,_selectable));
         _table->setItem(_lastRow,ColumnSelVal,_tableHelper.addEditText2("") );
     }
     else
         if (_isMultizoneMarker)
         {
            _table->setCellWidget(_lastRow,ColumnSelVal,_tableHelper.addCombo(_list,_selectable)); // Antes tenia el AddChecker
            //((QHeaderView*) _table->horizontalHeader())->setResizeMode(ColumnSelVal, QHeaderView::Stretch);
            //((QHeaderView*) _table->verticalHeader())->setResizeMode(_lastRow, QHeaderView::Stretch);
         }
     _table->setItem(_lastRow,ColumnVarName,_tableHelper.addNonEditableText(_varName));
     _table->setItem(_lastRow,MarkerColumnHelp,_tableHelper.addIcon());
 }
bool SolverMarkerMenuHelper::checkMarkerMeshVariables (QHash< QString, QString > _userMarkers, QHash< QString, QString > _meshFileMarkers, QHash< QString, QString > * _markersConfig)
Function that cheks the Marker mesh variables.
Parameters
QHash<QString
_userMarkers
QHash<QString
_meshFileMarkers
QHash<QString
_markersConfig
Returns
bool
Definition at line 215 of file solvermarkermenuhelper.cpp.
References ListHelper::getListFromQHash(), and ListHelper::isContainedInList().
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     QHashIterator<QString,QString> iter(_userMarkers);
     ListHelper _listHelper;
     QStringList _list = _listHelper.getListFromQHash(_meshFileMarkers);
     int _count = 0;
     bool _result = true;
     while(iter.hasNext())
     {
         iter.next();
         QString _keyName = iter.key();
         if  ((_keyName.contains("MARKER_")) || (_keyName.contains("BC_")))
         {
             QString _value = iter.value();
             if (!_value.contains("NONE"))
             {
                 _markersConfig->insert(QString::number(_count),_value);
                 _count++;
                 if(!(_listHelper.isContainedInList(_list,_value)) )
                     _result = false;
             }
         }
     }
     return _result;
 }
bool SolverMarkerMenuHelper::checkMarkerMeshVariables (QHash< QString, QString > _userMarkers, QHash< QString, QString > _meshFileMarkers)
Function that cheks the Marker mesh variables.
Parameters
QHash<QString
_userMarkers
QHash<QString
_meshFileMarkers
Returns
bool
Definition at line 254 of file solvermarkermenuhelper.cpp.
References ListHelper::getListFromQHash(), and ListHelper::isContainedInList().
 {
     ListHelper _listHelper;
     QStringList _list = _listHelper.getListFromQHash(_meshFileMarkers);
     int _count = 0;
     bool _result = true;
     QHashIterator<QString,QString> iter(_userMarkers);
     while(iter.hasNext())
     {
         iter.next();
         QString _keyName = iter.key();
         if ((_keyName.contains("MARKER_")) || (_keyName.contains("BC_")))
         {
             QString _value = iter.value();
             if (!_value.contains("NONE"))
             {
                 _count++;
                 if(!(_listHelper.isContainedInList(_list,_value)) )
                     _result = false;
             }
         }
     }
     return _result;
 }
void SolverMarkerMenuHelper::fillMarkerMenuTable (QString _parentName, QHash< QString, QString > _meshVariables, QTableWidget * _table, QList< SolverVariableVO > _list)
This funtcion allow to fill the specific marker menu table in the Solver Basic dialog.
Parameters
_parentName
QHash<QString
_meshVariables
_table
_list
Definition at line 44 of file solvermarkermenuhelper.cpp.
References addMarkerVariable(), SolverVariableVO::getComboValuesList(), SolverSectionDAO::getVariableNameList(), MARKER_CHILD_TITLE, and StrEqual.
Referenced by MeshDialog::fillTable().
 {
     if ( (_parentName.isEmpty()) || (QString::compare(_parentName,"") == StrEqual) ||
          (_meshVariables.isEmpty()))
         return;
     QStringList _comboItemList;
     SolverSectionDAO _sectionDAO;
     bool _isMultizoneMarker = false;
   /*  if (QString::compare(_parentName,MARKER_MULTIZONE_TITLE) == StrEqual)
     {
         _comboItemList = _sectionDAO.getVariableNameList(_list);
         _isMultizoneMarker = true;
     }else{*/
         if (!_list.isEmpty())
         {
             if ((QString::compare(_parentName,MARKER_CHILD_TITLE) == StrEqual) )
                 _comboItemList = _sectionDAO.getVariableNameList(_list);
             else
             {
                 // Solo puede tener 1 elemento
                 // Que corresponde al MARKER_MONITORING o a MARKER_PLOTTING
                 SolverVariableVO _markerVO = _list.at(0);
                 _comboItemList = _markerVO.getComboValuesList();
             }
         }
    // }
     if (!_meshVariables.isEmpty())
     {
         QHashIterator<QString,QString> iter(_meshVariables);
         while (iter.hasNext())
         {
             iter.next();
             QString _meshVariableName = iter.value();
             addMarkerVariable(_table,_meshVariableName,_comboItemList,_isMultizoneMarker);
         }
     }
 }
void SolverMarkerMenuHelper::removeMarkerElementsFromConfigFile (QHash< QString, QString > * _mapValues)
This function removes the markers elements according to the map values.
Parameters
QHash<QString
_mapValues
Definition at line 184 of file solvermarkermenuhelper.cpp.
 {
     QHashIterator<QString,QString> _iter(*_mapValues);
     QStringList _valuesToRemove;
     while (_iter.hasNext())
     {
         _iter.next();
         QString _keyName = _iter.key();
         if  ((_keyName.contains("MARKER_")) || (_keyName.contains("BC_")))
             _valuesToRemove.append(_keyName);
     }
     if (!_valuesToRemove.isEmpty())
     {
         for (int i = 0; i < _valuesToRemove.count(); i++)
             _mapValues->remove(_valuesToRemove.at(i));
     }
 }
The documentation for this class was generated from the following files:
WindowHelper/Dialog/SolverDialog/solvermarkermenuhelper.h
WindowHelper/Dialog/SolverDialog/solvermarkermenuhelper.cpp