BBIPED Platform: ConfigurationFileParser Class Reference
ConfigurationFileParser Class Reference
#include <configurationfileparser.h>
Public Member Functions
ConfigurationFileParser ()
Constructor.
QList< VirtualMrfVO > getParsedVirtualMRFData ()
void parseFileProcess ()
Main function to parse the file.
Public Member Functions inherited from ParserFiles
ParserFiles ()
Constructor.
QString getFilePath ()
Returns the path of the file.
QHash< QString, QString > getParsedValues ()
Returns the map of the parsed values.
QString removeSpaces (QString _value)
Function to remove spaces in the values.
void setFilePath (QString _newPath)
Establish the file path.
void setParsedValues (QHash< QString, QString > _newValues)
Sets the parsed values.
Private Member Functions
void analyseLine (QString _line)
Function that analyses the line to be parsed.
int findVirtualMRFPositionByZoneName (QString _name)
bool isCommentedLine (QString _line)
Checks if the line is a commented line to skip it.
QString removeCommentedPart (QString _text)
void saveDomainClippingValue (QString _keyName, QString _valueVal)
void saveTokenElements (QString _line)
Save the parsed element.
void saveVirtualMRFValue (QString _keyName, QString _valueVal)
Private Attributes
QHash< QString, QString > _currentParsedValues
QList< VirtualMrfVO > _parsedVirtualMRFData
Detailed Description
Definition at line 10 of file configurationfileparser.h.
Constructor & Destructor Documentation
ConfigurationFileParser::ConfigurationFileParser ()
Constructor.
Definition at line 27 of file configurationfileparser.cpp.
 {
 }
Member Function Documentation
void ConfigurationFileParser::analyseLine (QString _line) private
Function that analyses the line to be parsed.
Parameters
_line
Definition at line 69 of file configurationfileparser.cpp.
References isCommentedLine(), and saveTokenElements().
Referenced by parseFileProcess().
 {
     if (!isCommentedLine(_line))
         saveTokenElements(_line);
 }
int ConfigurationFileParser::findVirtualMRFPositionByZoneName (QString _name) private
Parameters
_name
Returns
int
Definition at line 197 of file configurationfileparser.cpp.
References _parsedVirtualMRFData, VirtualMrfVO::getZoneName(), and StrEqual.
Referenced by saveVirtualMRFValue().
 {
     int _result = -1;
     for (int i = 0; i < _parsedVirtualMRFData.size();i++)
     {
         VirtualMrfVO _virtualData = _parsedVirtualMRFData.at(i);
         QString _cName = _virtualData.getZoneName();
         if (QString::compare(_name,_cName,Qt::CaseSensitive) == StrEqual)
             return i;
     }
     return _result;
 }
QList< VirtualMrfVO > ConfigurationFileParser::getParsedVirtualMRFData ()
Definition at line 31 of file configurationfileparser.cpp.
References _parsedVirtualMRFData.
Referenced by MultizoneProjectDialog::checkConsistency(), FileComparisonDialog::loadFileValues(), and InputDataTabHelper::parseFile().
 {
     return _parsedVirtualMRFData;
 }
bool ConfigurationFileParser::isCommentedLine (QString _line) private
Checks if the line is a commented line to skip it.
Parameters
_line
Returns
bool
Definition at line 82 of file configurationfileparser.cpp.
Referenced by analyseLine().
 {
     if (_line.startsWith("%"))
         return true;
     else
         return false;
 }
void ConfigurationFileParser::parseFileProcess () virtual
Main function to parse the file.
Implements ParserFiles.
Definition at line 40 of file configurationfileparser.cpp.
References _currentParsedValues, analyseLine(), ParserFiles::getFilePath(), and ParserFiles::setParsedValues().
Referenced by MultizoneProjectDialog::checkConsistency(), FileComparisonDialog::loadFileValues(), and InputDataTabHelper::parseFile().
 {
     QString _path = this->getFilePath();
     QFile _file(_path);
     bool _fileCreated = false;
     if (_file.exists())
     {
          _fileCreated = _file.open(QIODevice::ReadOnly);
          if (_fileCreated )
          {
              QTextStream _reader(&_file);
              QString _line = _reader.readLine();
              while(!_line.isNull())
              {
                  analyseLine(_line);
                  _line = _reader.readLine();
              }
             setParsedValues(_currentParsedValues);
          }
          _file.close();
     }
 }
QString ConfigurationFileParser::removeCommentedPart (QString _text) private
Parameters
_text
Returns
QString
Definition at line 217 of file configurationfileparser.cpp.
Referenced by saveTokenElements().
 {
     QString _result;
     QStringList _list = _text.split("%");
     if (!_list.isEmpty())
         return _result.at(0);
     else
         return _result;
 }
void ConfigurationFileParser::saveDomainClippingValue (QString _keyName, QString _valueVal) private
Definition at line 117 of file configurationfileparser.cpp.
References _currentParsedValues.
Referenced by saveTokenElements().
  {
      if ((_valueVal.isEmpty()) || (_valueVal.isNull()))
          return;
      _valueVal = _valueVal.replace("(","");
      _valueVal = _valueVal.replace(")","");
      if (_currentParsedValues.contains(_keyName))
      {
          QStringList _oldValueList = _currentParsedValues.value(_keyName).split(";");
          _oldValueList.append(_valueVal);
          _currentParsedValues.insert(_keyName,_oldValueList.join(";"));
      }else
          _currentParsedValues.insert(_keyName,_valueVal);
  }
void ConfigurationFileParser::saveTokenElements (QString _line) private
Save the parsed element.
Parameters
_line
Definition at line 95 of file configurationfileparser.cpp.
References _currentParsedValues, removeCommentedPart(), ParserFiles::removeSpaces(), saveDomainClippingValue(), and saveVirtualMRFValue().
Referenced by analyseLine().
 {
     QStringList _values = _line.split("=");
     if ((!_values.isEmpty()) && (_values.size() == 2))
     {
         QString _keyName =  removeSpaces(_values.at(0));
         QString _valueVal = _values.at(1);
         if (_valueVal.contains("%"))
            _valueVal = removeCommentedPart(_valueVal);
         if ((!_keyName.contains("VMRF")) && (!_keyName.contains("PARTIAL_OUT")))
             _currentParsedValues.insert(_keyName, removeSpaces(_valueVal));
         else
         {
             if (_keyName.contains("VMRF"))
                 saveVirtualMRFValue(_keyName,_valueVal);
             if (_keyName.contains("PARTIAL_OUT"))
                 saveDomainClippingValue(_keyName,_valueVal);
          }
     }
 }
void ConfigurationFileParser::saveVirtualMRFValue (QString _keyName, QString _valueVal) private
Parameters
_keyName
_valueVal
Definition at line 139 of file configurationfileparser.cpp.
References _parsedVirtualMRFData, COMMA_SEPARATOR, findVirtualMRFPositionByZoneName(), VirtualMrfVO::setAxisCenter(), VirtualMrfVO::setAxisNormal(), VirtualMrfVO::setInnerCurvePoints(), VirtualMrfVO::setOmega(), VirtualMrfVO::setOuterCurvePoints(), VirtualMrfVO::setZoneName(), StrEqual, VMRF_AXIS_KEYNAME, VMRF_INNER_CURVE_KEYNAME, and VMRF_OUTER_CURVE_KEYNAME.
Referenced by saveTokenElements().
 {
     VirtualMrfVO _newVirtualData;
     _valueVal = _valueVal.replace("(","");
     _valueVal = _valueVal.replace(")","");
     QStringList _values = _valueVal.split(",");
     if (_values.isEmpty())
         return;
     QString _valueName = _values.at(0);
     if (QString::compare(_keyName,VMRF_AXIS_KEYNAME) == StrEqual )
     {
         if (_values.size() == 8)
         {
             _newVirtualData.setZoneName(_valueName);
             _newVirtualData.setOmega(_values.at(1));
             QString _axisCenter = _values.at(2) + COMMA_SEPARATOR + _values.at(3) + COMMA_SEPARATOR + _values.at(4);
             _newVirtualData.setAxisCenter(_axisCenter.split(COMMA_SEPARATOR));
             QString _axisNormal = _values.at(5) + COMMA_SEPARATOR + _values.at(6) + COMMA_SEPARATOR + _values.at(7);
             _newVirtualData.setAxisNormal(_axisNormal.split(COMMA_SEPARATOR));
             _parsedVirtualMRFData.append(_newVirtualData);
         }
     }
     if (QString::compare(_keyName,VMRF_INNER_CURVE_KEYNAME)== StrEqual )
     {
         int _objPos = findVirtualMRFPositionByZoneName(_valueName);
         if ((_objPos != -1) && (_objPos < _parsedVirtualMRFData.size()))
         {
             _newVirtualData = _parsedVirtualMRFData.at(_objPos);
             _values.removeAt(1);
             _values.removeAt(0);
             _newVirtualData.setInnerCurvePoints(_values);
             _parsedVirtualMRFData[_objPos]  = _newVirtualData;
         }
     }
     if  (QString::compare(_keyName,VMRF_OUTER_CURVE_KEYNAME)== StrEqual )
     {
         int _objPos = findVirtualMRFPositionByZoneName(_valueName);
         if ((_objPos != -1) && (_objPos < _parsedVirtualMRFData.size()))
          {
             _newVirtualData = _parsedVirtualMRFData.at(_objPos);
             _values.removeAt(1);
             _values.removeAt(0);
             _newVirtualData.setOuterCurvePoints(_values);
             _parsedVirtualMRFData[_objPos]  = _newVirtualData;
         }
     }
 }
Member Data Documentation
QHash<QString, QString> ConfigurationFileParser::_currentParsedValues private
Definition at line 19 of file configurationfileparser.h.
Referenced by parseFileProcess(), saveDomainClippingValue(), and saveTokenElements().
QList<VirtualMrfVO> ConfigurationFileParser::_parsedVirtualMRFData private
Definition at line 20 of file configurationfileparser.h.
Referenced by findVirtualMRFPositionByZoneName(), getParsedVirtualMRFData(), and saveVirtualMRFValue().
The documentation for this class was generated from the following files:
Parser/Solver/configurationfileparser.h
Parser/Solver/configurationfileparser.cpp