BBIPED Platform: MeshInfoVO Class Reference
MeshInfoVO Class Reference
#include <meshinfovo.h>
Public Member Functions
MeshInfoVO ()
void clear ()
QStringList getBoundaryNameList ()
QHash< QString, QString > getBoundaryNameListMap ()
QString getMeshDetailsFileName ()
QString getMeshFileName ()
QString getMeshPath ()
bool is3DMesh ()
void saveMeshInfoFile ()
void set3DMesh (bool _val)
void setBoundaryNameList (QStringList _list)
void setBoundaryNameList (QHash< QString, QString > _map)
void setMeshDetailsFileName (QString _meshdetails)
void setMeshFileName (QString _filename)
void setMeshPath (QString _path)
Private Member Functions
void initializeVariables ()
Private Attributes
QStringList _boundaryNameList
bool _is3DMesh
QString _meshDetailsFileName
QString _meshFileName
QString _meshPath
Detailed Description
Definition at line 7 of file meshinfovo.h.
Constructor & Destructor Documentation
MeshInfoVO::MeshInfoVO ()
Definition at line 5 of file meshinfovo.cpp.
References initializeVariables().
 {
     initializeVariables();
 }
Member Function Documentation
void MeshInfoVO::clear ()
Definition at line 10 of file meshinfovo.cpp.
References initializeVariables().
Referenced by MainWindow::clearAllData().
 {
     initializeVariables();
 }
QStringList MeshInfoVO::getBoundaryNameList ()
Definition at line 41 of file meshinfovo.cpp.
References _boundaryNameList.
Referenced by MeshInfoFileWriter::writeMeshFileWriter().
 {
     return _boundaryNameList;
 }
QHash< QString, QString > MeshInfoVO::getBoundaryNameListMap ()
Definition at line 45 of file meshinfovo.cpp.
References _boundaryNameList.
Referenced by MainWindow::importMeshInfoFile().
 {
     QHash<QString,QString> _result;
     for (int i = 0; i < _boundaryNameList.size();i++)
         _result.insert(QString::number(i),_boundaryNameList.at(i));
     return _result;
 }
QString MeshInfoVO::getMeshDetailsFileName ()
Definition at line 85 of file meshinfovo.cpp.
References _meshDetailsFileName.
Referenced by MeshInfoFileWriter::writeMeshFileWriter().
 {
     return _meshDetailsFileName;
 }
QString MeshInfoVO::getMeshFileName ()
Definition at line 65 of file meshinfovo.cpp.
References _meshFileName.
Referenced by MainWindow::checkMeshNames(), MainWindow::importMeshInfoFile(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::saveConfigFile(), MainWindow::saveMeshVariables(), and MeshInfoFileWriter::writeMeshFileWriter().
 {
     return _meshFileName ;
 }
QString MeshInfoVO::getMeshPath ()
Definition at line 75 of file meshinfovo.cpp.
References _meshPath.
Referenced by MainWindow::checkMeshNames(), MainWindow::importMeshInfoFile(), MainWindow::openSolverConfigurationFileDialog(), MainWindow::saveConfigFile(), MainWindow::saveMeshVariables(), and MeshInfoFileWriter::writeMeshFileWriter().
 {
     return _meshPath;
 }
void MeshInfoVO::initializeVariables () private
Definition at line 21 of file meshinfovo.cpp.
References _is3DMesh, _meshDetailsFileName, _meshFileName, and _meshPath.
Referenced by clear(), and MeshInfoVO().
 {
     _is3DMesh = false;
     _meshFileName = "";
     _meshDetailsFileName = "";
     _meshPath = "";
 }
bool MeshInfoVO::is3DMesh ()
Definition at line 31 of file meshinfovo.cpp.
References _is3DMesh.
Referenced by MainWindow::importMeshInfoFile(), and MeshInfoFileWriter::writeMeshFileWriter().
 {
     return _is3DMesh;
 }
void MeshInfoVO::saveMeshInfoFile ()
Definition at line 14 of file meshinfovo.cpp.
References MeshInfoFileWriter::writeMeshFileWriter().
Referenced by MainWindow::importMeshFile(), and MainWindow::importMeshInfoFile().
 {
    MeshInfoFileWriter _writer;
    _writer.writeMeshFileWriter(this);
 }
void MeshInfoVO::set3DMesh (bool _val)
Definition at line 36 of file meshinfovo.cpp.
References _is3DMesh.
Referenced by MeshInfoFileReader::get3DMeshData(), and MainWindow::importMeshFile().
 {
     _is3DMesh  = _val;
 }
void MeshInfoVO::setBoundaryNameList (QStringList _list)
Definition at line 53 of file meshinfovo.cpp.
References _boundaryNameList.
Referenced by MeshInfoFileReader::getBndNameList(), and MainWindow::importMeshFile().
 {
     _boundaryNameList = _list;
 }
void MeshInfoVO::setBoundaryNameList (QHash< QString, QString > _map)
Definition at line 57 of file meshinfovo.cpp.
References _boundaryNameList.
 {
     QHash<QString, QString>::iterator it;
     _boundaryNameList.clear();
     for (it = _map.begin(); it != _map.end(); ++it)
         _boundaryNameList.append(it.value());
 }
void MeshInfoVO::setMeshDetailsFileName (QString _meshdetails)
Definition at line 90 of file meshinfovo.cpp.
References _meshDetailsFileName.
Referenced by MainWindow::importMeshFile(), MainWindow::importMeshInfoFile(), and MeshInfoFileReader::readMeshInfo().
 {
     _meshDetailsFileName = _meshdetails;
 }
void MeshInfoVO::setMeshFileName (QString _filename)
Definition at line 70 of file meshinfovo.cpp.
References _meshFileName.
Referenced by MeshInfoFileReader::getMeshFileName(), and MainWindow::importMeshFile().
 {
     _meshFileName = _filename;
 }
void MeshInfoVO::setMeshPath (QString _path)
Definition at line 80 of file meshinfovo.cpp.
References _meshPath.
Referenced by MeshInfoFileReader::getMeshPath(), and MainWindow::importMeshFile().
 {
     _meshPath = _path;
 }
Member Data Documentation
QStringList MeshInfoVO::_boundaryNameList private
Definition at line 34 of file meshinfovo.h.
Referenced by getBoundaryNameList(), getBoundaryNameListMap(), and setBoundaryNameList().
bool MeshInfoVO::_is3DMesh private
Definition at line 33 of file meshinfovo.h.
Referenced by initializeVariables(), is3DMesh(), and set3DMesh().
QString MeshInfoVO::_meshDetailsFileName private
Definition at line 37 of file meshinfovo.h.
Referenced by getMeshDetailsFileName(), initializeVariables(), and setMeshDetailsFileName().
QString MeshInfoVO::_meshFileName private
Definition at line 35 of file meshinfovo.h.
Referenced by getMeshFileName(), initializeVariables(), and setMeshFileName().
QString MeshInfoVO::_meshPath private
Definition at line 36 of file meshinfovo.h.
Referenced by getMeshPath(), initializeVariables(), and setMeshPath().
The documentation for this class was generated from the following files:
Data/Solver/MeshInfo/meshinfovo.h
Data/Solver/MeshInfo/meshinfovo.cpp