BBIPED Platform: SalomeTemplateManager Class Reference
SalomeTemplateManager Class Reference
#include <salometemplatemanager.h>
Public Member Functions
SalomeTemplateManager ()
Constructor.
void deleteUserDefinedTempalte (QString _templateName)
QString getTemplateFileNameByTemplateName (QString _templateName)
QStringList getTemplateNameList ()
QList< SalomeTemplateData > getTemplates ()
QStringList getUserTemplateNameList ()
QList< SalomeTemplateData > getUserTemplates ()
bool isInitialized ()
void loadTemplate ()
void restoreToDefaultTemplate (int i)
void saveTemplate ()
void updateTemplateValues (QList< SalomeTemplateData > _templates)
void updateUserTemplateValues (QList< SalomeTemplateData > _templates)
Private Types
enum
Private Member Functions
void buildPredefinedTemplateMenus (QDomElement _domTree)
void buildTemplateData (QDomElement _templateNode, int _option)
void buildTemplateMenus (QDomDocument *_domTree)
void buildUserTemplateMenus (QDomElement _domTree)
SalomeVariableData buildVariableData (QDomElement _variableNode)
void buildVariableList (QDomElement _variableListNode, SalomeTemplateData *_template)
void saveTemplateData (QXmlStreamWriter *_xmlWriter, QList< SalomeTemplateData > _template)
void saveVariableData (QXmlStreamWriter *_xmlWriter, QList< SalomeVariableData > _varList)
void updateTemplateNameList (int _option)
Private Attributes
QString _bbipedHomePath
bool _isInitialized
QStringList _templateNameList
QString _templatePath
QList< SalomeTemplateData > _templatesList
QStringList _userTemplateNameList
QList< SalomeTemplateData > _userTemplatesList
Detailed Description
Definition at line 13 of file salometemplatemanager.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
selectPredefinedTemplates
selectUserDefinedTemplates
Definition at line 49 of file salometemplatemanager.h.
         {
         selectPredefinedTemplates  = 0,
         selectUserDefinedTemplates = 1
     };
Constructor & Destructor Documentation
SalomeTemplateManager::SalomeTemplateManager ()
Constructor.
Definition at line 35 of file salometemplatemanager.cpp.
 {
     _bbipedHomePath = QCoreApplication::applicationDirPath();
     _templatePath = QDir(_bbipedHomePath).filePath(".tools/Automatization/Templates/Salome/templates_salome.xml");
     _isInitialized = false;
 }
Member Function Documentation
void SalomeTemplateManager::buildPredefinedTemplateMenus (QDomElement _templateListNode) private
Parameters
_templateListNode
Definition at line 147 of file salometemplatemanager.cpp.
References StrEqual, TEMPLATE_LIST, and XML_TEMPLATE_LIST_NODE.
 {
     if ((!_templateListNode.isNull() ) && (QString::compare(_templateListNode.tagName(),XML_TEMPLATE_LIST_NODE) == StrEqual))
     {
         QDomNodeList _templateList = _templateListNode.childNodes();
         for (int i = 0; i < _templateList.size(); i++)
         {
             QDomElement _templateEl = _templateList.at(i).toElement();
             buildTemplateData(_templateEl,TEMPLATE_LIST);
         }
     }
 }
void SalomeTemplateManager::buildTemplateData (QDomElement _templateNode, int _option) private
Parameters
_templateNode
_option
Definition at line 168 of file salometemplatemanager.cpp.
References SalomeTemplateData::getTemplateName(), SalomeTemplateData::setTemplateFileName(), SalomeTemplateData::setTemplateName(), StrEqual, TEMPLATE_LIST, XML_TEMPLATE_FILE_NAME_NODE, XML_TEMPLATE_NAME_NODE, XML_TEMPLATE_NODE, and XML_VARIABLE_LIST_NODE.
 {
     if ( (!_templateNode.isNull()) && (QString::compare(_templateNode.tagName(),XML_TEMPLATE_NODE) == StrEqual))
     {
         QDomNodeList _templateChildren= _templateNode.childNodes();
         SalomeTemplateData _templateData;
         for (int i = 0; i < _templateChildren.size(); i++)
         {
             QDomElement _templateEl = _templateChildren.at(i).toElement();
             if ((_templateEl.isNull()) || (_templateEl.tagName().isEmpty()) )
                 continue;
             if (QString::compare(_templateEl.tagName(),XML_TEMPLATE_NAME_NODE) == StrEqual)
                 _templateData.setTemplateName(_templateEl.text());
             if (QString::compare(_templateEl.tagName(),XML_TEMPLATE_FILE_NAME_NODE) == StrEqual)
                 _templateData.setTemplateFileName(_templateEl.text());
             if (QString::compare(_templateEl.tagName(),XML_VARIABLE_LIST_NODE) == StrEqual)
                 buildVariableList(_templateEl,&_templateData);
         }
         // Saving the data of the template
         if (_option == TEMPLATE_LIST)
         {
             _templatesList.push_back(_templateData);
             _templateNameList.push_back(_templateData.getTemplateName());
         }
         else
         {
             _userTemplatesList.push_back(_templateData);
             _userTemplateNameList.push_back(_templateData.getTemplateName());
         }
     }
 }
void SalomeTemplateManager::buildTemplateMenus (QDomDocument * _domTree) private
Parameters
_domTree
Definition at line 122 of file salometemplatemanager.cpp.
References StrEqual, and XML_TEMPLATE_SALOME_NODE.
 {
     QDomElement _rootElement = _domTree->documentElement();
     if (!_rootElement.isNull())
     {
         //cout << "TAG " << _rootElement.tagName().toStdString() << endl;
         if (QString::compare(_rootElement.tagName(),XML_TEMPLATE_SALOME_NODE) == StrEqual)
         {
             QDomElement _templatesNode = _rootElement.firstChild().toElement();
             if (!_templatesNode.isNull())
                 buildPredefinedTemplateMenus(_templatesNode);
             QDomElement _userTemplatesNode = _rootElement.firstChild().nextSibling().toElement();
             if (!_userTemplatesNode.isNull())
                 buildUserTemplateMenus(_userTemplatesNode);
         }
     }
 }
void SalomeTemplateManager::buildUserTemplateMenus (QDomElement _templateListNode) private
Parameters
_templateListNode
Definition at line 266 of file salometemplatemanager.cpp.
References StrEqual, USER_TEMPLATE_LIST, and XML_USER_TEMPLATE_LIST_NODE.
 {
     if ((!_templateListNode.isNull() ) && (QString::compare(_templateListNode.tagName(),XML_USER_TEMPLATE_LIST_NODE) == StrEqual))
     {
         QDomNodeList _templateList = _templateListNode.childNodes();
         for (int i = 0; i < _templateList.size(); i++)
         {
             QDomElement _templateEl = _templateList.at(i).toElement();
             buildTemplateData(_templateEl,USER_TEMPLATE_LIST);
         }
     }
 }
SalomeVariableData SalomeTemplateManager::buildVariableData (QDomElement _variableNode) private
Parameters
_variableNode
Returns
SalomeVariableData
Definition at line 233 of file salometemplatemanager.cpp.
References SalomeVariableData::setCurrentValue(), SalomeVariableData::setDefaultValue(), SalomeVariableData::setFileName(), SalomeVariableData::setName(), SalomeVariableData::setOptimizedValue(), StrEqual, XML_VARIABLE_CURRENT_VALUE_NODE, XML_VARIABLE_DEFAULT_VALUE_NODE, XML_VARIABLE_FILE_NAME_NODE, XML_VARIABLE_ISOPTIMIZED_NODE, XML_VARIABLE_NAME_NODE, and XML_VARIABLE_NODE.
 {
     SalomeVariableData _variableData;
     if ( (!_variableNode.isNull()) && (QString::compare(_variableNode.tagName(),XML_VARIABLE_NODE) == StrEqual))
     {
         QDomNodeList _varChildren= _variableNode.childNodes();
         for (int i=0; i<_varChildren.size();i++)
         {
             QDomElement _varEl = _varChildren.at(i).toElement();
             if (_varEl.isNull())
                 continue;
             if (QString::compare(_varEl.tagName(),XML_VARIABLE_NAME_NODE) == StrEqual)
                _variableData.setName(_varEl.text());
             if (QString::compare(_varEl.tagName(),XML_VARIABLE_FILE_NAME_NODE) == StrEqual)
                _variableData.setFileName(_varEl.text());
             if (QString::compare(_varEl.tagName(),XML_VARIABLE_DEFAULT_VALUE_NODE) == StrEqual)
                _variableData.setDefaultValue(_varEl.text());
             if (QString::compare(_varEl.tagName(),XML_VARIABLE_CURRENT_VALUE_NODE) == StrEqual)
                _variableData.setCurrentValue(_varEl.text());
             if (QString::compare(_varEl.tagName(),XML_VARIABLE_ISOPTIMIZED_NODE) == StrEqual)
                _variableData.setOptimizedValue(_varEl.text());
         }
     }
     return _variableData;
 }
void SalomeTemplateManager::buildVariableList (QDomElement _variableListNode, SalomeTemplateData * _template) private
Parameters
_variableListNode
_template
Definition at line 209 of file salometemplatemanager.cpp.
References SalomeTemplateData::setVariableList(), StrEqual, and XML_VARIABLE_LIST_NODE.
 {
     if ( (!_variableListNode.isNull()) && (QString::compare(_variableListNode.tagName(),XML_VARIABLE_LIST_NODE) == StrEqual))
     {
         QDomNodeList _varChildren= _variableListNode.childNodes();
         QList<SalomeVariableData> _varList;
         for (int i=0; i<_varChildren.size();i++)
         {
             QDomElement _varEl = _varChildren.at(i).toElement();
             if (_varEl.isNull())
                 continue;
            SalomeVariableData _salomeVariable =  buildVariableData(_varEl);
            _varList.push_back(_salomeVariable);
         }
         _template->setVariableList(_varList);
     }
 }
void SalomeTemplateManager::deleteUserDefinedTempalte (QString _templateName)
Definition at line 464 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::on_deleteTemplateButton_clicked().
 {
     if (_templateName.isEmpty())
         return;
     int _pos = _userTemplateNameList.indexOf(_templateName);
     if (_pos == -1)
         return;
     _userTemplatesList.removeAt(_pos);
     _userTemplateNameList.removeAt(_pos);
     saveTemplate();
 }
QString SalomeTemplateManager::getTemplateFileNameByTemplateName (QString _templateName)
Parameters
_templateName
Returns
QString
Definition at line 432 of file salometemplatemanager.cpp.
References SalomeTemplateData::getTemplateFileName().
Referenced by SalomeTemplateDialog::on_saveAsButton_clicked().
 {
     if (_templateName.isEmpty())
         return QString("");
     int _templateNo = _templateNameList.indexOf(_templateName);
     bool _isUserTemplate = false;
     if (_templateNo == -1)
     {
       _templateNo = _userTemplateNameList.indexOf(_templateName);
       if (_templateNo == -1)
           return QString("");
       else
           _isUserTemplate = true;
     }
     SalomeTemplateData _selectedTemplate;
     if( (_isUserTemplate) && (_templateNo < _userTemplatesList.size()) )
     {
         _selectedTemplate = _userTemplatesList.at(_templateNo);
     }else
     {
         if( (!_isUserTemplate) && (_templateNo < _templatesList.size()) )
             _selectedTemplate = _templatesList.at(_templateNo);
     }
     return _selectedTemplate.getTemplateFileName();
 }
QStringList SalomeTemplateManager::getTemplateNameList ()
Returns
QStringList
Definition at line 412 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::fillTable(), SalomeOptimizationDialog::fillTable(), SalomeTemplateDialog::getPosMenu(), SalomeOptimizationDialog::getPosMenu(), SalomeTemplateDialog::isUserTemplateSelected(), SalomeTemplateDialog::on_createMeshButton_clicked(), SalomeOptimizationDialog::refreshComboTemplates(), SalomeTemplateDialog::refreshComboTemplates(), and SalomeTemplateDialog::saveData().
 {
     return _templateNameList;
 }
QList< SalomeTemplateData > SalomeTemplateManager::getTemplates ()
Returns
QList<SalomeTemplateData>
Definition at line 383 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::createTemplateFromUserValues(), SalomeTemplateDialog::fillTable(), SalomeOptimizationDialog::fillTable(), SalomeOptimizationDialog::getVariablesList(), SalomeTemplateDialog::on_createMeshButton_clicked(), SalomeOptimizationDialog::on_pushButton_clicked(), SalomeTemplateDialog::resetValuesToDefault(), and SalomeTemplateDialog::saveData().
 {
     return _templatesList;
 }
QStringList SalomeTemplateManager::getUserTemplateNameList ()
Returns
QStringList
Definition at line 402 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::getPosMenu(), SalomeOptimizationDialog::getPosMenu(), SalomeTemplateDialog::on_createMeshButton_clicked(), SalomeOptimizationDialog::refreshComboTemplates(), and SalomeTemplateDialog::refreshComboTemplates().
 {
     return _userTemplateNameList;
 }
QList< SalomeTemplateData > SalomeTemplateManager::getUserTemplates ()
Returns
QList<SalomeTemplateData>
Definition at line 393 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::createTemplateFromUserValues(), SalomeTemplateDialog::fillTable(), SalomeOptimizationDialog::fillTable(), SalomeOptimizationDialog::getVariablesList(), SalomeTemplateDialog::on_createMeshButton_clicked(), SalomeOptimizationDialog::on_pushButton_clicked(), SalomeTemplateDialog::on_saveAsButton_clicked(), and SalomeTemplateDialog::saveData().
 {
     return _userTemplatesList;
 }
bool SalomeTemplateManager::isInitialized ()
Returns
bool
Definition at line 421 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::initializeDialog(), and SalomeOptimizationDialog::initializeDialog().
 {
     return _isInitialized;
 }
void SalomeTemplateManager::loadTemplate ()
Definition at line 46 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::initializeDialog(), and SalomeOptimizationDialog::initializeDialog().
 {
     // Loading the file from the resource
     QFile * _template = new QFile(_templatePath);
     QDomDocument * _domTree = new QDomDocument();
     if( !_template->open( QIODevice::ReadOnly | QIODevice::Text ) )
         qDebug( "Failed to open file for reading." );
     else
     {
         if( !_domTree->setContent( _template ) )
             qDebug( "Failed to parse the file into a DOM tree." );
         buildTemplateMenus(_domTree);
         _isInitialized = true;
     }
     _template->close();
 }
void SalomeTemplateManager::restoreToDefaultTemplate (int i)
Definition at line 477 of file salometemplatemanager.cpp.
References SalomeVariableData::getCurrentValue(), SalomeVariableData::getDefaultValue(), SalomeTemplateData::getVariableList(), SalomeTemplateData::isEmpty(), SalomeVariableData::setCurrentValue(), SalomeTemplateData::setVariableList(), and StrEqual.
Referenced by SalomeTemplateDialog::restoreTemplateDefaults().
 {
     SalomeTemplateData _tempTemplate = _templatesList.at(i);
     if (_tempTemplate.isEmpty())
         return;
    QList<SalomeVariableData> _varList =  _tempTemplate.getVariableList();
    QList<SalomeVariableData> _newList;
    if (_varList.isEmpty())
        return;
    for (int i = 0; i < _varList.size(); i++)
    {
        SalomeVariableData _data = _varList.at(i);
        if (QString::compare(_data.getCurrentValue(),_data.getDefaultValue()) != StrEqual)
        {
            QString _defaultVal = _data.getDefaultValue();
            _data.setCurrentValue(_defaultVal);
        }
        _newList.push_back(_data);
    }
    _tempTemplate.setVariableList(_newList);
    _templatesList[i] = _tempTemplate;
 }
void SalomeTemplateManager::saveTemplate ()
Definition at line 283 of file salometemplatemanager.cpp.
References XML_TEMPLATE_LIST_NODE, XML_TEMPLATE_SALOME_NODE, and XML_USER_TEMPLATE_LIST_NODE.
 {
     QFile _file(_templatePath);
     bool _fileCreated = false;
     if (_file.exists())
         _file.remove();
     _fileCreated = _file.open(QIODevice::ReadWrite);
     if (_fileCreated)
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         xmlWriter.writeStartElement(XML_TEMPLATE_SALOME_NODE);
         xmlWriter.writeStartElement(XML_TEMPLATE_LIST_NODE);
         saveTemplateData(&xmlWriter, _templatesList);
         xmlWriter.writeEndElement();
         xmlWriter.writeStartElement(XML_USER_TEMPLATE_LIST_NODE);
         saveTemplateData(&xmlWriter,_userTemplatesList);
         xmlWriter.writeEndElement();
         xmlWriter.writeEndDocument();
     }
 }
void SalomeTemplateManager::saveTemplateData (QXmlStreamWriter * _xmlWriter, QList< SalomeTemplateData > _template) private
Parameters
_xmlWriter
_template
Definition at line 318 of file salometemplatemanager.cpp.
References SalomeTemplateData::getTemplateFileName(), SalomeTemplateData::getTemplateName(), SalomeTemplateData::getVariableList(), XML_TEMPLATE_FILE_NAME_NODE, XML_TEMPLATE_NAME_NODE, XML_TEMPLATE_NODE, and XML_VARIABLE_LIST_NODE.
 {
     for (int i = 0; i < _template.size(); i++)
     {
         SalomeTemplateData _templateData = _template.at(i);
         _xmlWriter->writeStartElement(XML_TEMPLATE_NODE);
             // Name of the template
             _xmlWriter->writeStartElement(XML_TEMPLATE_NAME_NODE);
             _xmlWriter->writeCharacters(_templateData.getTemplateName());
             _xmlWriter->writeEndElement();
             // Name of the file name template
             _xmlWriter->writeStartElement(XML_TEMPLATE_FILE_NAME_NODE);
             _xmlWriter->writeCharacters(_templateData.getTemplateFileName());
             _xmlWriter->writeEndElement();
             // Variables Section
             _xmlWriter->writeStartElement(XML_VARIABLE_LIST_NODE);
             saveVariableData(_xmlWriter,_templateData.getVariableList());
             _xmlWriter->writeEndElement();
         _xmlWriter->writeEndElement();
     }
 }
void SalomeTemplateManager::saveVariableData (QXmlStreamWriter * _xmlWriter, QList< SalomeVariableData > _varList) private
Parameters
_xmlWriter
_varList
Definition at line 347 of file salometemplatemanager.cpp.
References SalomeVariableData::getCurrentValue(), SalomeVariableData::getDefaultValue(), SalomeVariableData::getFileName(), SalomeVariableData::getName(), SalomeVariableData::getOptimizedValue(), XML_VARIABLE_CURRENT_VALUE_NODE, XML_VARIABLE_DEFAULT_VALUE_NODE, XML_VARIABLE_FILE_NAME_NODE, XML_VARIABLE_ISOPTIMIZED_NODE, XML_VARIABLE_NAME_NODE, and XML_VARIABLE_NODE.
 {
     for (int i = 0; i < _varList.size();i++)
     {
         SalomeVariableData _var = _varList.at(i);
         _xmlWriter->writeStartElement(XML_VARIABLE_NODE);
         _xmlWriter->writeStartElement(XML_VARIABLE_NAME_NODE);
         _xmlWriter->writeCharacters(_var.getName());
         _xmlWriter->writeEndElement();
         _xmlWriter->writeStartElement(XML_VARIABLE_FILE_NAME_NODE);
         _xmlWriter->writeCharacters(_var.getFileName());
         _xmlWriter->writeEndElement();
         _xmlWriter->writeStartElement(XML_VARIABLE_DEFAULT_VALUE_NODE);
         _xmlWriter->writeCharacters(_var.getDefaultValue());
         _xmlWriter->writeEndElement();
         _xmlWriter->writeStartElement(XML_VARIABLE_CURRENT_VALUE_NODE);
         _xmlWriter->writeCharacters(_var.getCurrentValue());
         _xmlWriter->writeEndElement();
         _xmlWriter->writeStartElement(XML_VARIABLE_ISOPTIMIZED_NODE);
         _xmlWriter->writeCharacters(_var.getOptimizedValue());
         _xmlWriter->writeEndElement();
         _xmlWriter->writeEndElement();
     }
 }
void SalomeTemplateManager::updateTemplateNameList (int _option) private
Parameters
_option
Definition at line 82 of file salometemplatemanager.cpp.
References SalomeTemplateData::getTemplateName().
 {
     if (_option == selectPredefinedTemplates)
     {
         _templateNameList.clear();
         for (int i = 0; i < _templatesList.size();i++)
         {
             SalomeTemplateData _selTemplate = _templatesList.at(i);
             _templateNameList.push_back(_selTemplate.getTemplateName());
         }
     }
     if (_option == selectUserDefinedTemplates)
     {
         _userTemplateNameList.clear();
         for (int i = 0; i < _userTemplatesList.size();i++)
         {
             SalomeTemplateData _selTemplate = _userTemplatesList.at(i);
             _userTemplateNameList.push_back(_selTemplate.getTemplateName());
         }
     }
 }
void SalomeTemplateManager::updateTemplateValues (QList< SalomeTemplateData > _templates)
Parameters
_templates
Definition at line 70 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::saveData().
 {
     _templatesList = _templates;
     updateTemplateNameList(selectPredefinedTemplates);
       saveTemplate();
 }
void SalomeTemplateManager::updateUserTemplateValues (QList< SalomeTemplateData > _templates)
Parameters
_templates
Definition at line 109 of file salometemplatemanager.cpp.
Referenced by SalomeTemplateDialog::on_saveAsButton_clicked(), and SalomeTemplateDialog::saveData().
 {
     _userTemplatesList = _templates;
     updateTemplateNameList(selectUserDefinedTemplates);
     saveTemplate();
 }
Member Data Documentation
QString SalomeTemplateManager::_bbipedHomePath private
Definition at line 45 of file salometemplatemanager.h.
bool SalomeTemplateManager::_isInitialized private
Definition at line 47 of file salometemplatemanager.h.
QStringList SalomeTemplateManager::_templateNameList private
Definition at line 41 of file salometemplatemanager.h.
QString SalomeTemplateManager::_templatePath private
Definition at line 44 of file salometemplatemanager.h.
QList<SalomeTemplateData> SalomeTemplateManager::_templatesList private
Definition at line 39 of file salometemplatemanager.h.
QStringList SalomeTemplateManager::_userTemplateNameList private
Definition at line 42 of file salometemplatemanager.h.
QList<SalomeTemplateData> SalomeTemplateManager::_userTemplatesList private
Definition at line 40 of file salometemplatemanager.h.
The documentation for this class was generated from the following files:
Templates/salometemplatemanager.h
Templates/salometemplatemanager.cpp