BBIPED Platform: DomModel Class Reference
DomModel Class Reference
[0]
#include <dommodel.h>
Public Member Functions
DomModel (QDomDocument document, QObject *parent=0)
Specific DOM model constructor.
~DomModel ()
Destructor.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Number of columns.
QVariant data (const QModelIndex &index, int role) const
Data contained in the DOM Tree.
Qt::ItemFlags flags (const QModelIndex &index) const
Activated flags.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Header Data.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Index within the DOM tree.
QModelIndex parent (const QModelIndex &child) const
Parent within DOM tree.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Row count function.
Private Attributes
QDomDocument domDocument
DomItem * rootItem
Detailed Description
[0]
Definition at line 52 of file dommodel.h.
Constructor & Destructor Documentation
DomModel::DomModel (QDomDocument document, QObject * parent = 0)
Specific DOM model constructor.
Parameters
document
parent
Definition at line 57 of file dommodel.cpp.
References domDocument, and rootItem.
     : QAbstractItemModel(parent), domDocument(document)
 {
     rootItem = new DomItem(domDocument, 0);
 }
DomModel::~DomModel ()
Destructor.
Definition at line 69 of file dommodel.cpp.
References rootItem.
 {
     delete rootItem;
 }
Member Function Documentation
int DomModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Number of columns.
Parameters
@return int
Definition at line 81 of file dommodel.cpp.
 {
     return 3;
 }
QVariant DomModel::data (const QModelIndex & index, int role) const
Data contained in the DOM Tree.
Parameters
index
role
Returns
QVariant
Definition at line 95 of file dommodel.cpp.
References DomItem::node().
 {
     if (!index.isValid())
         return QVariant();
     if (role != Qt::DisplayRole)
         return QVariant();
     DomItem *item = static_cast<DomItem*>(index.internalPointer());
     if (role == Qt::DisplayRole)
         return QVariant(item->node().nodeName());
     QDomNode node = item->node();
     QString _nodeName;
     _nodeName = node.nodeName();
     QStringList attributes;
     QDomNamedNodeMap attributeMap = node.attributes();
     // TODO ... change what we show
     switch (index.column()) {
         case 0:
             return node.nodeName();
        case 1:
             for (int i = 0; i < attributeMap.count(); ++i) {
                 QDomNode attribute = attributeMap.item(i);
                 attributes << attribute.nodeName() + "=\""
                               +attribute.nodeValue() + "\"";
             }
             return attributes.join(" ");
         case 2:
             return node.nodeValue().split("\n").join(" ");
         default:
             return QVariant();
     }
 }
Qt::ItemFlags DomModel::flags (const QModelIndex & index) const
Activated flags.
Parameters
index
Returns
Qt::ItemFlags
Definition at line 142 of file dommodel.cpp.
 {
     if (!index.isValid())
         return 0;
     return Qt::ItemIsEnabled | Qt::ItemIsSelectable;
 }
QVariant DomModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Header Data.
Parameters
section
orientation
role
Returns
QVariant
Definition at line 158 of file dommodel.cpp.
 {
     if (orientation == Qt::Horizontal && role == Qt::DisplayRole) {
         switch (section) {
             case 0:
                 return tr("Name");
             case 1:
                 return tr("Attributes");
             case 2:
                 return tr("Value");
             default:
                 return QVariant();
         }
     }
     return QVariant();
 }
QModelIndex DomModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Index within the DOM tree.
Parameters
row
column
parent
Returns
QModelIndex
Definition at line 185 of file dommodel.cpp.
References DomItem::child(), and rootItem.
 {
     if (!hasIndex(row, column, parent))
         return QModelIndex();
     DomItem *parentItem;
     if (!parent.isValid())
         parentItem = rootItem;
     else
         parentItem = static_cast<DomItem*>(parent.internalPointer());
     DomItem *childItem = parentItem->child(row);
     if (childItem)
         return createIndex(row, column, childItem);
     else
         return QModelIndex();
 }
QModelIndex DomModel::parent (const QModelIndex & child) const
Parent within DOM tree.
Parameters
child
Returns
QModelIndex
Definition at line 211 of file dommodel.cpp.
References DomItem::parent(), rootItem, and DomItem::row().
 {
     if (!child.isValid())
         return QModelIndex();
     DomItem *childItem = static_cast<DomItem*>(child.internalPointer());
     DomItem *parentItem = childItem->parent();
     if (!parentItem || parentItem == rootItem)
         return QModelIndex();
     return createIndex(parentItem->row(), 0, parentItem);
 }
int DomModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Row count function.
Parameters
parent
Returns
int
Definition at line 231 of file dommodel.cpp.
References DomItem::node(), and rootItem.
 {
     if (parent.column() > 0)
         return 0;
     DomItem *parentItem;
     if (!parent.isValid())
         parentItem = rootItem;
     else
         parentItem = static_cast<DomItem*>(parent.internalPointer());
     return parentItem->node().childNodes().count();
 }
Member Data Documentation
QDomDocument DomModel::domDocument private
Definition at line 71 of file dommodel.h.
Referenced by DomModel().
DomItem* DomModel::rootItem private
Definition at line 72 of file dommodel.h.
Referenced by DomModel(), index(), parent(), rowCount(), and ~DomModel().
The documentation for this class was generated from the following files:
Utility/Model/DomModel/dommodel.h
Utility/Model/DomModel/dommodel.cpp