BBIPED Platform: MeshInfoFileWriter Class Reference
MeshInfoFileWriter Class Reference
#include <meshinfofilewriter.h>
Public Member Functions
MeshInfoFileWriter ()
void writeMeshFileWriter (MeshInfoVO *_meshData)
Private Member Functions
void saveBndValues (QXmlStreamWriter *_xmlWriter, QStringList _varList)
Detailed Description
Definition at line 9 of file meshinfofilewriter.h.
Constructor & Destructor Documentation
MeshInfoFileWriter::MeshInfoFileWriter ()
Definition at line 4 of file meshinfofilewriter.cpp.
 {
 }
Member Function Documentation
void MeshInfoFileWriter::saveBndValues (QXmlStreamWriter * _xmlWriter, QStringList _varList) private
Definition at line 50 of file meshinfofilewriter.cpp.
References XML_MESH_BND_NAME.
Referenced by writeMeshFileWriter().
 {
     if (_varList.isEmpty())
         return;
     for (int i = 0; i < _varList.size();i++)
     {
         _xmlWriter->writeStartElement(XML_MESH_BND_NAME);
         _xmlWriter->writeCharacters(_varList.at(i));
         _xmlWriter->writeEndElement();
     }
 }
void MeshInfoFileWriter::writeMeshFileWriter (MeshInfoVO * _meshData)
Definition at line 8 of file meshinfofilewriter.cpp.
References MeshInfoVO::getBoundaryNameList(), MeshInfoVO::getMeshDetailsFileName(), MeshInfoVO::getMeshFileName(), MeshInfoVO::getMeshPath(), MeshInfoVO::is3DMesh(), saveBndValues(), XML_MESH_3D_NATURE_NODE, XML_MESH_BND_LIST, XML_MESH_FILE_NAME, XML_MESH_PATH, and XML_MESH_ROOT.
Referenced by MeshInfoVO::saveMeshInfoFile().
 {
     QString _filePath = _meshData->getMeshDetailsFileName();
     QFile _file(_filePath);
     if (_file.exists())
         _file.remove();
     bool _fileCreated = _file.open(QIODevice::ReadWrite | QIODevice::Text);
     if (_fileCreated)
     {
         QXmlStreamWriter xmlWriter(&_file);
         xmlWriter.setAutoFormatting(true);
         xmlWriter.writeStartDocument();
         xmlWriter.writeStartElement(XML_MESH_ROOT);
         xmlWriter.writeStartElement(XML_MESH_3D_NATURE_NODE);
         if (_meshData->is3DMesh())
             xmlWriter.writeCharacters("YES");
         else
             xmlWriter.writeCharacters("NO");
         xmlWriter.writeEndElement();
         xmlWriter.writeStartElement(XML_MESH_BND_LIST);
         saveBndValues(&xmlWriter,_meshData->getBoundaryNameList());
         xmlWriter.writeEndElement();
         xmlWriter.writeStartElement(XML_MESH_FILE_NAME);
         xmlWriter.writeCharacters(_meshData->getMeshFileName());
         xmlWriter.writeEndElement();
         xmlWriter.writeStartElement(XML_MESH_PATH);
         xmlWriter.writeCharacters(_meshData->getMeshPath());
         xmlWriter.writeEndElement();
         xmlWriter.writeEndDocument();
     }
     _file.close();
 }
The documentation for this class was generated from the following files:
Data/Solver/MeshInfo/meshinfofilewriter.h
Data/Solver/MeshInfo/meshinfofilewriter.cpp