BBIPED Platform: SolverVariableVO Class Reference
SolverVariableVO Class Reference
#include <solvervariablevo.h>
Public Member Functions
SolverVariableVO ()
Constructor.
~SolverVariableVO ()
Destructor.
QStringList getAssociatedVariables ()
Get the list of associated variables.
QStringList getComboValueNamesList ()
Get the names of the combos.
QStringList getComboValuesList ()
Get the associated combo values list.
QString getCurrentValue ()
Get the current value of the variable.
QString getDefaultValue ()
get the Associated default value
QString getHelpContents (bool _withFormat)
Get the associated Help Contents.
SolverVarHelpVO getHelperContents ()
Get the object that contains all the help contents.
VariableRule getRule ()
This function returns the associated rule.
QList< bool > getSelectableComboValues ()
QStringList getSubVariableNames ()
Get the name list of associated subvariables for this SolverVariableVO.
QString getUnitValue ()
Get the value of the units (metric units)
QString getVariableFileName ()
Get the variable name as it appears in the configuration file.
QString getVariableName ()
Get the Associated variable name.
bool isEmpty ()
Returns true if the object is empty.
bool isOptional ()
Check if a variable can be optional (if optional and the user does not give a value, it is not written in the configuration file)
bool isRepeatable ()
Check if this SolverVariable can be repeated.
bool isUniqueSelection ()
This function sets the option of unique selection (COMBOBOX mode) for the values (true) otherwise multiple selection in the combobox values are set By default is TRUE.
bool isVariableSelectable ()
bool isVisible ()
This function gets the value of the variable to be visible or not.
bool isVisibleInMenu ()
Check if a variable is visible in the Menu (by default true)
void setAssociatedVariables (QStringList _list)
Set the list of associated variables.
void setComboValueNamesList (QStringList _list)
Set the names of the combos.
void setComboValuesList (QStringList _newComboValuesList)
Set the associated combo values list.
void setCurrentValue (QString _newValue)
Set the current value of the variable.
void setDefaultValue (QString _newDefaultValue)
set the Associated default value
void setHelpContents (SolverVarHelpVO *_newHelpContents)
Set the associated Help Contents.
void setOptional (bool _val)
Set the possibility for a variable to be optional in the configuration file. By default is false;.
void setRepeatable (bool _val)
Set the possibility to repeat a variable in the configuration file. By default is false;.
void setRule (VariableRule _newRule)
This function allows to store a rule associated to a variable.
void setSelectableComboValues (QList< bool > _list)
void setSubVariableNames (QStringList _newValue)
Set the list of associated subvariables for this SolverVariableVO.
void setUniqueSelection (bool _val)
This function is used to set the value for unique selection or multiple selection of the COMBOBOX values.
void setUnitValue (QString _newValue)
Set the value of the (metric) units.
void setVariableFileName (QString _newName)
Set the variable name as it appears in the configuration file.
void setVariableName (QString _newName)
Set the Variable Name.
void setVariableSelectable (bool _val)
void setVisibility (bool _val)
This function allows to change the visibility of a variable.
void setVisibleInMenu (bool _val)
Set the visibility of a variable in the configuration file. By default is true;.
Private Attributes
QStringList _associatedVariables
QStringList _comboValueNamesList
QStringList _comboValuesList
QString _currentValue
QString _defaultValue
QString _fileName
SolverVarHelpVO * _helpContents
bool _isEmpty
bool _isOptional
bool _isRepeatable
bool _isSelectable
bool _isUniqueSelection
bool _isVisible
bool _isVisibleInMenu
QString _name
VariableRule _rule
QList< bool > _selectableComboValues
QStringList _subVariableNames
QString _unitTxt
Detailed Description
Definition at line 10 of file solvervariablevo.h.
Constructor & Destructor Documentation
SolverVariableVO::SolverVariableVO ()
Constructor.
Definition at line 25 of file solvervariablevo.cpp.
References _currentValue, _defaultValue, _fileName, _isEmpty, _isOptional, _isRepeatable, _isSelectable, _isUniqueSelection, _isVisible, _isVisibleInMenu, _name, and _unitTxt.
 {
     _name = "";
     _defaultValue= "";
     _fileName= "";
     _currentValue= "";
     _isEmpty = true;
     _isVisible = true;
     _unitTxt = "";
     _isUniqueSelection = true;
     _isRepeatable = false;
     _isOptional = false;
     _isVisibleInMenu = true;
     _isSelectable = true;
 }
SolverVariableVO::~SolverVariableVO ()
Destructor.
Definition at line 45 of file solvervariablevo.cpp.
 {
 }
Member Function Documentation
QStringList SolverVariableVO::getAssociatedVariables ()
Get the list of associated variables.
Returns
QStringList
Definition at line 440 of file solvervariablevo.cpp.
References _associatedVariables.
Referenced by MeshDialog::createMeshVariables().
 {
     return _associatedVariables;
 }
QStringList SolverVariableVO::getComboValueNamesList ()
Get the names of the combos.
Returns
QStringList
Definition at line 201 of file solvervariablevo.cpp.
References _comboValueNamesList.
Referenced by SolverConfigMenuHelper::addVariableToTable(), TemplateManager::createComboValues(), SolverConfigMenuHelper::getAssociatedFileNameValue(), and SolverBasicDialog::getAssociatedFileNameValue().
 {
     return _comboValueNamesList;
 }
QStringList SolverVariableVO::getComboValuesList ()
Get the associated combo values list.
Returns
QStringList
Definition at line 179 of file solvervariablevo.cpp.
References _comboValuesList.
Referenced by TemplateManager::createComboValues(), SolverMarkerMenuHelper::fillMarkerMenuTable(), FileComparisonDialog::fillUserValueInCell(), SolverConfigMenuHelper::getAssociatedFileNameValue(), SolverBasicDialog::getAssociatedFileNameValue(), and getHelpContents().
 {
     return _comboValuesList;
 }
QString SolverVariableVO::getCurrentValue ()
Get the current value of the variable.
Returns
QString
Definition at line 243 of file solvervariablevo.cpp.
References _currentValue.
Referenced by SolverConfigMenuHelper::addVariableToTable().
 {
     return _currentValue;
 }
QString SolverVariableVO::getDefaultValue ()
get the Associated default value
Returns
QString
Definition at line 89 of file solvervariablevo.cpp.
References _defaultValue.
Referenced by SolverConfigMenuHelper::addVariableToTable(), TemplateManager::createValueTag(), getHelpContents(), SolverSectionDAO::isDefaultValueByFileName(), SolverBasicDialog::launchSpecificWindow(), and SolverConfigMenuHelper::updateTableWithUserValues().
 {
     return _defaultValue;
 }
QString SolverVariableVO::getHelpContents (bool _withFormat)
Get the associated Help Contents.
Returns
SolverVarHelpVO
Definition at line 110 of file solvervariablevo.cpp.
References _helpContents, HtmlFormatter::appendParagraph(), HtmlFormatter::appendTable(), HtmlFormatter::appendTitle(), HtmlFormatter::appendTitleParagraph(), COMMA_SEPARATOR, HtmlFormatter::endFormatting(), getComboValuesList(), getDefaultValue(), SolverVarHelpVO::getDefinitionText(), SolverVarHelpVO::getDetailsText(), HtmlFormatter::getFormatedText(), SolverVarHelpVO::getValuesText(), getVariableFileName(), getVariableName(), SEMICOLON_SEPARATOR, and HtmlFormatter::startFormatting().
Referenced by VirtualRotatingDialog::buildAssociatedHelp(), MeshDialog::buildHelpContent(), VirtualCurveDialog::generateHelpDialog(), SolverConfigMenuHelper::getAssociatedHelpText(), and SummaryDialog::on_summaryTable_cellClicked().
 {
      QString _text;
      if (_withFormat)
      {
          HtmlFormatter _htmlFormatter;
          _htmlFormatter.startFormatting();
          _htmlFormatter.appendTitle(this->getVariableName());
          _htmlFormatter.appendTitleParagraph("Definition");
          _htmlFormatter.appendParagraph(_helpContents->getDefinitionText());
          _htmlFormatter.appendTitleParagraph("Possible values and default Values");
          _htmlFormatter.appendParagraph( _helpContents->getValuesText());
          _htmlFormatter.appendTitleParagraph("Other Details");
          _htmlFormatter.appendParagraph(_helpContents->getDetailsText());
          // Adding the values in a table
          _htmlFormatter.appendTitleParagraph("Quick Summary");
          QStringList _headerTable;
          QList<QStringList> _contentTable;
          QString _row1("Possible Values;");
          _row1+=(this->getComboValuesList()).join(COMMA_SEPARATOR);
          QString _row2("Default Value;");
          _row2+= this->getDefaultValue();
          QString _row3("Variable Name in SU2 file;");
          _row3+=this->getVariableFileName();
          _contentTable.append(_row1.split(SEMICOLON_SEPARATOR));
          _contentTable.append(_row2.split(SEMICOLON_SEPARATOR));
          _contentTable.append(_row3.split(SEMICOLON_SEPARATOR));
         _htmlFormatter.appendTable(_headerTable,_contentTable);
          _htmlFormatter.endFormatting();
         _text = _htmlFormatter.getFormatedText();
      }else
      {
          _text = _helpContents->getDefinitionText();
      }
     return _text;
 }
SolverVarHelpVO SolverVariableVO::getHelperContents ()
Get the object that contains all the help contents.
Returns
SolverVarHelpVO
Definition at line 325 of file solvervariablevo.cpp.
References _helpContents.
Referenced by TemplateManager::createHelpElement().
 {
     return (* _helpContents);
 }
VariableRule SolverVariableVO::getRule ()
This function returns the associated rule.
Returns
VariableRule
Definition at line 294 of file solvervariablevo.cpp.
References _rule.
 {
     return _rule;
 }
QList< bool > SolverVariableVO::getSelectableComboValues ()
Definition at line 169 of file solvervariablevo.cpp.
References _selectableComboValues.
Referenced by SolverConfigMenuHelper::addVariableToTable(), and FileComparisonDialog::fillUserValueInCell().
 {
     return _selectableComboValues;
 }
QStringList SolverVariableVO::getSubVariableNames ()
Get the name list of associated subvariables for this SolverVariableVO.
Returns
QStringList
Definition at line 368 of file solvervariablevo.cpp.
References _subVariableNames.
Referenced by SolverConfigMenuHelper::addVariableToTable(), and ClipDomainDialog::fillTable().
 {
     return _subVariableNames;
 }
QString SolverVariableVO::getUnitValue ()
Get the value of the units (metric units)
Returns
QString
Definition at line 315 of file solvervariablevo.cpp.
References _unitTxt.
Referenced by SolverConfigMenuHelper::addVariableToTable(), and TemplateManager::createValueTag().
 {
     return _unitTxt;
 }
QString SolverVariableVO::getVariableFileName ()
Get the variable name as it appears in the configuration file.
Returns
QString
Definition at line 222 of file solvervariablevo.cpp.
References _fileName.
Referenced by MeshDialog::createMeshVariables(), TemplateManager::createValueTag(), WarningMultizoneDialog::fillRepairTable(), FileComparisonDialog::fillUserValueInCell(), SolverSectionDAO::findValueNameByVariableName(), SolverSectionDAO::findVariableByFileName(), SolverSectionDAO::findVariableNameByValueName(), getHelpContents(), SolverSectionDAO::getOptionalVariables(), SolverConfigMenuHelper::updateTableWithUserValues(), and SolverConfigManager::updateVisibility().
 {
     return _fileName;
 }
QString SolverVariableVO::getVariableName ()
Get the Associated variable name.
Returns
QString
Definition at line 67 of file solvervariablevo.cpp.
References _isEmpty, and _name.
Referenced by TemplateDialog::addVariable(), SolverConfigMenuHelper::addVariableToTable(), TemplateDialog::addVariableToTable(), MeshDialog::createMeshVariables(), TemplateManager::createVariable(), WarningMultizoneDialog::fillRepairTable(), FileComparisonDialog::fillRowWithData(), SolverSectionDAO::findValueNameByVariableName(), SolverSectionDAO::findVariableByValueName(), SolverSectionDAO::findVariableNameByValueName(), SolverConfigMenuHelper::getAssociatedHelpText(), getHelpContents(), SolverSectionDAO::getVariableNameList(), TemplateManager::getVariables(), SolverBasicDialog::launchSpecificWindow(), MeshDialog::restoreValues(), SearchPairHelper::searchTreeBySearchTerm(), SummaryDialog::updateNewValues(), TemplateDialog::updateSelectedVariableCheckBox(), and SolverConfigMenuHelper::updateVariableValueinTable().
 {
     return _name;
      _isEmpty = false;
 }
bool SolverVariableVO::isEmpty ()
Returns true if the object is empty.
Returns
bool
Definition at line 253 of file solvervariablevo.cpp.
References _isEmpty.
Referenced by FileComparisonDialog::buildRow(), SummaryDialog::buildRows(), WarningMultizoneDialog::fillRepairTable(), SolverSectionDAO::findVariableByFileName(), SolverSectionDAO::isDefaultValueByFileName(), and SolverBasicDialog::on_solverVariablesTable_cellClicked().
 {
     return _isEmpty;
 }
bool SolverVariableVO::isOptional ()
Check if a variable can be optional (if optional and the user does not give a value, it is not written in the configuration file)
Returns
bool
Definition at line 399 of file solvervariablevo.cpp.
References _isOptional.
Referenced by SolverSectionDAO::getOptionalVariables().
 {
     return _isOptional;
 }
bool SolverVariableVO::isRepeatable ()
Check if this SolverVariable can be repeated.
Returns
bool
Definition at line 379 of file solvervariablevo.cpp.
References _isRepeatable.
 {
     return _isRepeatable;
 }
bool SolverVariableVO::isUniqueSelection ()
This function sets the option of unique selection (COMBOBOX mode) for the values (true) otherwise multiple selection in the combobox values are set By default is TRUE.
Returns
bool
Definition at line 337 of file solvervariablevo.cpp.
References _isUniqueSelection.
Referenced by SolverConfigMenuHelper::addVariableToTable().
 {
     return _isUniqueSelection;
 }
bool SolverVariableVO::isVariableSelectable ()
Definition at line 455 of file solvervariablevo.cpp.
References _isSelectable.
Referenced by SolverConfigMenuHelper::addVariableToTable(), and SolverBasicDialog::on_solverVariablesTable_cellClicked().
 {
     return _isSelectable;
 }
bool SolverVariableVO::isVisible ()
This function gets the value of the variable to be visible or not.
Returns
bool
Definition at line 264 of file solvervariablevo.cpp.
References _isVisible.
Referenced by SolverConfigMenuHelper::fillMenuTable().
 {
     return _isVisible;
 }
bool SolverVariableVO::isVisibleInMenu ()
Check if a variable is visible in the Menu (by default true)
Returns
bool
Definition at line 420 of file solvervariablevo.cpp.
References _isVisibleInMenu.
Referenced by MeshDialog::removeNonVisibleVariables().
 {
     return _isVisibleInMenu;
 }
void SolverVariableVO::setAssociatedVariables (QStringList _list)
Set the list of associated variables.
Parameters
_list
Definition at line 450 of file solvervariablevo.cpp.
References _associatedVariables.
Referenced by SolverConfigReader::createVariableSection().
 {
     _associatedVariables = _list;
 }
void SolverVariableVO::setComboValueNamesList (QStringList _list)
Set the names of the combos.
Parameters
_list
Definition at line 189 of file solvervariablevo.cpp.
References _comboValueNamesList, and _isEmpty.
Referenced by SolverConfigReader::createComboValues().
 {
     _comboValueNamesList = _list;
     _isEmpty = false;
 }
void SolverVariableVO::setComboValuesList (QStringList _newComboValuesList)
Set the associated combo values list.
Parameters
_newComboValuesList
Definition at line 158 of file solvervariablevo.cpp.
References _comboValuesList, and _isEmpty.
Referenced by SolverConfigReader::createComboValues().
 {
     _comboValuesList = _newComboValuesList;
      _isEmpty = false;
 }
void SolverVariableVO::setCurrentValue (QString _newValue)
Set the current value of the variable.
Parameters
_newValue
Definition at line 232 of file solvervariablevo.cpp.
References _currentValue, and _isEmpty.
Referenced by SolverConfigReader::createVariableSection().
 {
     _currentValue = _newValue;
      _isEmpty = false;
 }
void SolverVariableVO::setDefaultValue (QString _newDefaultValue)
set the Associated default value
Parameters
_newDefaultValue
Definition at line 78 of file solvervariablevo.cpp.
References _defaultValue, and _isEmpty.
Referenced by SolverConfigReader::createVariableSection().
 {
     _defaultValue = _newDefaultValue;
      _isEmpty = false;
 }
void SolverVariableVO::setHelpContents (SolverVarHelpVO * _newHelpContents)
Set the associated Help Contents.
Parameters
_newHelpContents
Definition at line 99 of file solvervariablevo.cpp.
References _helpContents, and _isEmpty.
Referenced by SolverConfigReader::createVariableSection().
 {
     _helpContents = _newHelpContents;
      _isEmpty = false;
 }
void SolverVariableVO::setOptional (bool _val)
Set the possibility for a variable to be optional in the configuration file. By default is false;.
Parameters
_val
Definition at line 409 of file solvervariablevo.cpp.
References _isOptional.
Referenced by SolverConfigReader::createVariableSection().
 {
     _isOptional = _val;
 }
void SolverVariableVO::setRepeatable (bool _val)
Set the possibility to repeat a variable in the configuration file. By default is false;.
Parameters
_val
Definition at line 389 of file solvervariablevo.cpp.
References _isRepeatable.
Referenced by SolverConfigReader::createVariableSection().
 {
     _isRepeatable = _val;
 }
void SolverVariableVO::setRule (VariableRule _newRule)
This function allows to store a rule associated to a variable.
Parameters
_newRule
Definition at line 284 of file solvervariablevo.cpp.
References _rule.
 {
     _rule = _newRule;
 }
void SolverVariableVO::setSelectableComboValues (QList< bool > _list)
Definition at line 164 of file solvervariablevo.cpp.
References _selectableComboValues.
Referenced by SolverConfigReader::createComboValues().
 {
     _selectableComboValues =_list;
 }
void SolverVariableVO::setSubVariableNames (QStringList _newValue)
Set the list of associated subvariables for this SolverVariableVO.
Parameters
_newValue
Definition at line 358 of file solvervariablevo.cpp.
References _subVariableNames.
Referenced by SolverConfigReader::createVariableSection().
 {
     _subVariableNames = _newValue;
 }
void SolverVariableVO::setUniqueSelection (bool _val)
This function is used to set the value for unique selection or multiple selection of the COMBOBOX values.
Parameters
_val
Definition at line 348 of file solvervariablevo.cpp.
References _isUniqueSelection.
Referenced by SolverConfigReader::createVariableSection().
 {
     _isUniqueSelection = _val;
 }
void SolverVariableVO::setUnitValue (QString _newValue)
Set the value of the (metric) units.
Parameters
_newValue
Definition at line 305 of file solvervariablevo.cpp.
References _unitTxt.
Referenced by SolverConfigReader::createVariableSection().
 {
     _unitTxt = _newValue;
 }
void SolverVariableVO::setVariableFileName (QString _newName)
Set the variable name as it appears in the configuration file.
Parameters
_newName
Definition at line 211 of file solvervariablevo.cpp.
References _fileName, and _isEmpty.
Referenced by SolverConfigReader::createVariableSection().
 {
     _fileName = _newName;
      _isEmpty = false;
 }
void SolverVariableVO::setVariableName (QString _newName)
Set the Variable Name.
Parameters
_newName
Definition at line 56 of file solvervariablevo.cpp.
References _isEmpty, and _name.
Referenced by SolverConfigReader::createVariableSection().
 {
     _name = _newName;
     _isEmpty = false;
 }
void SolverVariableVO::setVariableSelectable (bool _val)
Definition at line 460 of file solvervariablevo.cpp.
References _isSelectable.
Referenced by SolverConfigReader::createVariableSection().
 {
     _isSelectable = _val;
 }
void SolverVariableVO::setVisibility (bool _val)
This function allows to change the visibility of a variable.
Parameters
_val
Definition at line 274 of file solvervariablevo.cpp.
References _isVisible.
Referenced by SolverConfigManager::updateVisibility().
 {
     _isVisible = _val;
 }
void SolverVariableVO::setVisibleInMenu (bool _val)
Set the visibility of a variable in the configuration file. By default is true;.
Parameters
_val
Definition at line 430 of file solvervariablevo.cpp.
References _isVisibleInMenu.
Referenced by SolverConfigReader::createVariableSection().
 {
     _isVisibleInMenu = _val;
 }
Member Data Documentation
QStringList SolverVariableVO::_associatedVariables private
Definition at line 102 of file solvervariablevo.h.
Referenced by getAssociatedVariables(), and setAssociatedVariables().
QStringList SolverVariableVO::_comboValueNamesList private
Definition at line 83 of file solvervariablevo.h.
Referenced by getComboValueNamesList(), and setComboValueNamesList().
QStringList SolverVariableVO::_comboValuesList private
Definition at line 84 of file solvervariablevo.h.
Referenced by getComboValuesList(), and setComboValuesList().
QString SolverVariableVO::_currentValue private
Definition at line 88 of file solvervariablevo.h.
Referenced by getCurrentValue(), setCurrentValue(), and SolverVariableVO().
QString SolverVariableVO::_defaultValue private
Definition at line 80 of file solvervariablevo.h.
Referenced by getDefaultValue(), setDefaultValue(), and SolverVariableVO().
QString SolverVariableVO::_fileName private
Definition at line 87 of file solvervariablevo.h.
Referenced by getVariableFileName(), setVariableFileName(), and SolverVariableVO().
SolverVarHelpVO* SolverVariableVO::_helpContents private
Definition at line 81 of file solvervariablevo.h.
Referenced by getHelpContents(), getHelperContents(), and setHelpContents().
bool SolverVariableVO::_isEmpty private
Definition at line 89 of file solvervariablevo.h.
Referenced by getVariableName(), isEmpty(), setComboValueNamesList(), setComboValuesList(), setCurrentValue(), setDefaultValue(), setHelpContents(), setVariableFileName(), setVariableName(), and SolverVariableVO().
bool SolverVariableVO::_isOptional private
Definition at line 98 of file solvervariablevo.h.
Referenced by isOptional(), setOptional(), and SolverVariableVO().
bool SolverVariableVO::_isRepeatable private
Definition at line 97 of file solvervariablevo.h.
Referenced by isRepeatable(), setRepeatable(), and SolverVariableVO().
bool SolverVariableVO::_isSelectable private
Definition at line 100 of file solvervariablevo.h.
Referenced by isVariableSelectable(), setVariableSelectable(), and SolverVariableVO().
bool SolverVariableVO::_isUniqueSelection private
Definition at line 94 of file solvervariablevo.h.
Referenced by isUniqueSelection(), setUniqueSelection(), and SolverVariableVO().
bool SolverVariableVO::_isVisible private
Definition at line 90 of file solvervariablevo.h.
Referenced by isVisible(), setVisibility(), and SolverVariableVO().
bool SolverVariableVO::_isVisibleInMenu private
Definition at line 99 of file solvervariablevo.h.
Referenced by isVisibleInMenu(), setVisibleInMenu(), and SolverVariableVO().
QString SolverVariableVO::_name private
Definition at line 79 of file solvervariablevo.h.
Referenced by getVariableName(), setVariableName(), and SolverVariableVO().
VariableRule SolverVariableVO::_rule private
Definition at line 91 of file solvervariablevo.h.
Referenced by getRule(), and setRule().
QList<bool> SolverVariableVO::_selectableComboValues private
Definition at line 85 of file solvervariablevo.h.
Referenced by getSelectableComboValues(), and setSelectableComboValues().
QStringList SolverVariableVO::_subVariableNames private
Definition at line 95 of file solvervariablevo.h.
Referenced by getSubVariableNames(), and setSubVariableNames().
QString SolverVariableVO::_unitTxt private
Definition at line 92 of file solvervariablevo.h.
Referenced by getUnitValue(), setUnitValue(), and SolverVariableVO().
The documentation for this class was generated from the following files:
Data/Solver/VO/solvervariablevo.h
Data/Solver/VO/solvervariablevo.cpp