BBIPED Platform: InputDataTabHelper Class Reference
InputDataTabHelper Class Reference
#include <inputdatatabhelper.h>
Public Member Functions
InputDataTabHelper ()
Constructor.
void disableAllInputDataTab ()
Disable All input data tab elements.
void disableChangeConfigActionMenu ()
Disable the change config action menu elements.
void disableRestartSimButtons ()
Disable the restart simulatio button.
void enableChangeConfigActionMenu ()
Enable Change Config Action Menu elements.
void enableConfigurationViewMenu (ProjectData _projectData)
This fucntion enables the configuration action menu according project data information.
void enableRestartSimButtons ()
Enable the restart simulatio button.
void fillFileNamesInTab (ProjectData _projectData, QHash< QString, QString > *_userMap)
Function to fill the names in the line Edit of the Input Data Tab.
void hideAllSolverMenus ()
Hide all the Tabs related with the solver Tool.
bool launchSolverConfigDialog (QWidget *_parent, bool _isBasicView, QHash< QString, QString > *_configValToSave, SolverConfigManager *_manager, QList< VirtualMrfVO > *_virtualVOList, bool _is3DMesh)
Launch the Solver Configuration Dialog.
void parseFile (int _option, QString _pathFile, QHash< QString, QString > *_userConfigVal, QHash< QString, QString > *_boundaryMeshVal, QList< VirtualMrfVO > *_virtualVOList)
Parse the correspondent files to get the values to load into the project variables.
void registerButtons (QPushButton *_mybasicV, QPushButton *_mySummaryB, QPushButton *_myRunSimB, QPushButton *_myRestartB)
This function register the main Buttons of the Solver tab to controls their behaviour.
void registerLineEdits (QLabel *_myConfigLine, QLabel *_myMeshLine)
This function register the main Line Edits of the Solver tab to controls their behaviour.
void registerTab (QTabWidget *_myTab)
This function register the the Solver tab to controls their behaviour.
void saveAsConfigFile (QString _fileName, ProjectData *_projectData, SolverConfigManager *_manager, QHash< QString, QString > _userVal, ProjectDetails _projectDetails, QList< VirtualMrfVO > _virtualVOList)
Dialog to save with a different name a configuration file.
void showAllSolverMenus (ProjectData _projectData)
Show all the Tabs related with the solver Tool.
void updateConfigurationFilePathInActionGroup (QString _newPath)
Update the file path in the line edit of the current configuration file.
void updateMeshFileNameInActionGroup (QString _newMeshPath, QHash< QString, QString > *_userMap)
Update the file path in the line edit of the current mesh file.
bool updateSolverUserValues (ProjectData _projectData, QHash< QString, QString > *_userConfigVal, QHash< QString, QString > *_boundaryMeshVal, QHash< QString, QString > *_boundaryConfigVal, QList< VirtualMrfVO > *_virtualVOList)
Update the user values for the configuration file and the mesh files of the current project.
Private Member Functions
void disableCurrentSimActionMenu ()
Disable All current sim action menu elements.
void enableCurrentSimActionMenu ()
Enable the Simulation Action Menu Elements.
void initializeSolverBasicDialog (SolverBasicDialog *_dialog, bool _basicView, QHash< QString, QString > _userConfigVal, SolverConfigManager *_manager, QList< VirtualMrfVO > _virtualVOList, bool _is3DMesh)
Initialize Solver Basic Dialog Window.
void updateUserConfigValues (QHash< QString, QString > _newMap, QHash< QString, QString > *_configValToSave, bool _reseted)
Update the configuration values of the user in teh correspondent Hash variable.
Private Attributes
QPushButton * _basicV
QLabel * _configLineLabel
QLabel * _meshLineLabel
QPushButton * _restartB
QPushButton * _runSimB
QPushButton * _saveAsB
QPushButton * _saveB
QPushButton * _summaryB
QTabWidget * _tab
Detailed Description
Definition at line 23 of file inputdatatabhelper.h.
Constructor & Destructor Documentation
InputDataTabHelper::InputDataTabHelper ()
Constructor.
Definition at line 38 of file inputdatatabhelper.cpp.
 {
 }
Member Function Documentation
void InputDataTabHelper::disableAllInputDataTab ()
Disable All input data tab elements.
Definition at line 335 of file inputdatatabhelper.cpp.
References disableChangeConfigActionMenu(), disableCurrentSimActionMenu(), and disableRestartSimButtons().
Referenced by MainWindow::closeProject().
 {
     disableChangeConfigActionMenu();
     disableCurrentSimActionMenu();
     disableRestartSimButtons();
 }
void InputDataTabHelper::disableChangeConfigActionMenu ()
Disable the change config action menu elements.
Definition at line 315 of file inputdatatabhelper.cpp.
References _basicV, and _summaryB.
Referenced by disableAllInputDataTab().
 {
     _basicV->setEnabled(false);
     _summaryB->setEnabled(false);
 }
void InputDataTabHelper::disableCurrentSimActionMenu () private
Disable All current sim action menu elements.
Definition at line 326 of file inputdatatabhelper.cpp.
References _runSimB.
Referenced by disableAllInputDataTab().
 {
     _runSimB->setEnabled(false);
 }
void InputDataTabHelper::disableRestartSimButtons ()
Disable the restart simulatio button.
Definition at line 358 of file inputdatatabhelper.cpp.
References _restartB.
Referenced by disableAllInputDataTab().
 {
    _restartB->setEnabled(false);
 }
void InputDataTabHelper::enableChangeConfigActionMenu ()
Enable Change Config Action Menu elements.
Definition at line 292 of file inputdatatabhelper.cpp.
References _basicV, and _summaryB.
Referenced by enableConfigurationViewMenu(), MainWindow::on_openFileActionButton_clicked(), and MainWindow::updateMeshView().
 {
     _basicV->setEnabled(true);
     _summaryB->setEnabled(true);
 }
void InputDataTabHelper::enableConfigurationViewMenu (ProjectData _projectData)
This fucntion enables the configuration action menu according project data information.
Parameters
_projectData
Definition at line 275 of file inputdatatabhelper.cpp.
References enableChangeConfigActionMenu(), enableCurrentSimActionMenu(), SolverVO::getSolverConfigFilePath(), and ProjectData::getSolverDataInformation().
Referenced by MainWindow::on_newActionButton_clicked(), MainWindow::openProject(), showAllSolverMenus(), and MainWindow::updateMeshView().
 {
     SolverVO _solverData = _projectData.getSolverDataInformation();
     if (!_solverData.getSolverConfigFilePath().isEmpty())
     {
            enableChangeConfigActionMenu();
            enableCurrentSimActionMenu();
     }
 }
void InputDataTabHelper::enableCurrentSimActionMenu () private
Enable the Simulation Action Menu Elements.
Definition at line 304 of file inputdatatabhelper.cpp.
References _runSimB.
Referenced by enableConfigurationViewMenu().
 {
     //enableSimulationFileEdits();
     _runSimB->setEnabled(true);
 }
void InputDataTabHelper::enableRestartSimButtons ()
Enable the restart simulatio button.
Definition at line 349 of file inputdatatabhelper.cpp.
References _restartB.
 {
     _restartB->setEnabled(true);
 }
void InputDataTabHelper::fillFileNamesInTab (ProjectData _projectData, QHash< QString, QString > * _userMap)
Function to fill the names in the line Edit of the Input Data Tab.
Definition at line 242 of file inputdatatabhelper.cpp.
References SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), updateConfigurationFilePathInActionGroup(), and updateMeshFileNameInActionGroup().
Referenced by MainWindow::on_solverButton_clicked().
 {
     SolverVO _solverInfo = _projectData.getSolverDataInformation();
     QString _configFilePath = _solverInfo.getSolverConfigFilePath();
     QString _meshFilePath = _solverInfo.getSolverFilePath();
     updateConfigurationFilePathInActionGroup(_configFilePath);
     updateMeshFileNameInActionGroup(_meshFilePath,_userMap);
 }
void InputDataTabHelper::hideAllSolverMenus ()
Hide all the Tabs related with the solver Tool.
Definition at line 370 of file inputdatatabhelper.cpp.
References _tab.
Referenced by MainWindow::closeProject(), MainWindow::enableToolButtons(), and MainWindow::MainWindow().
 {
      _tab->setEnabled(false);
 }
void InputDataTabHelper::initializeSolverBasicDialog (SolverBasicDialog * _dialog, bool _basicView, QHash< QString, QString > _userConfigVal, SolverConfigManager * _manager, QList< VirtualMrfVO > _virtualVOList, bool _is3DMesh) private
Initialize Solver Basic Dialog Window.
Parameters
SolverBasicDialog * _dialog, bool _basicView
Definition at line 51 of file inputdatatabhelper.cpp.
References SolverBasicDialog::enablePersonalizedView(), SolverConfigManager::isPersonalizedMenuListAvailable(), SolverBasicDialog::loadMenu(), SolverBasicDialog::resetDialog(), SolverBasicDialog::set3DMeshType(), SolverBasicDialog::setBasicView(), SolverBasicDialog::setConfigurationValues(), SolverBasicDialog::setData(), and SolverBasicDialog::setVirtualMRFData().
Referenced by launchSolverConfigDialog().
 {
     _dialog->resetDialog();
     _dialog->setVirtualMRFData(_virtualVOList);
     _dialog->setConfigurationValues(_userConfigVal);
     _dialog->setBasicView(_basicView);
     _dialog->set3DMeshType(_is3DMesh);
     // Establishing the new data
     _dialog->setData(_manager);
     // Loading the correspondent menu
     _dialog->loadMenu();
     if (_manager->isPersonalizedMenuListAvailable())
         _dialog->enablePersonalizedView();
 }
bool InputDataTabHelper::launchSolverConfigDialog (QWidget * _parent, bool _isBasicView, QHash< QString, QString > * _configValToSave, SolverConfigManager * _manager, QList< VirtualMrfVO > * _virtualVOList, bool _is3DMesh)
Launch the Solver Configuration Dialog.
Parameters
_isBasicView
Definition at line 145 of file inputdatatabhelper.cpp.
References SolverBasicDialog::getConfigurationValues(), SolverBasicDialog::getVirtualMRFData(), SolverBasicDialog::hasUserMadeChanges(), initializeSolverBasicDialog(), SolverBasicDialog::isReseted(), and updateUserConfigValues().
Referenced by MainWindow::on_basivViewEditButton_clicked(), and MultizoneIndividualTabForm::on_editConfigFileButton_clicked().
 {
     bool _needToSave = false;
     SolverBasicDialog * _dialog = new SolverBasicDialog(_parent);
     initializeSolverBasicDialog(_dialog,_isBasicView,(*_configValToSave),_manager, (* _virtualVOList),_is3DMesh);
     _dialog->exec();
     updateUserConfigValues(_dialog->getConfigurationValues(),_configValToSave, _dialog->isReseted());
     if (_dialog->hasUserMadeChanges())
     {
         _needToSave = true;
         *_virtualVOList = _dialog->getVirtualMRFData(); // Updating the value of the Virtual Values
     }
     delete _dialog;
     return _needToSave;
 }
void InputDataTabHelper::parseFile (int _option, QString _pathFile, QHash< QString, QString > * _userConfigVal, QHash< QString, QString > * _boundaryMeshVal, QList< VirtualMrfVO > * _virtualVOList)
Parse the correspondent files to get the values to load into the project variables.
Parameters
_option
_pathFile
Definition at line 78 of file inputdatatabhelper.cpp.
References ParserFiles::getParsedValues(), ConfigurationFileParser::getParsedVirtualMRFData(), MeshFileParser::is3DMesh(), IS_3D_MESH_TAG, MeshFileParser::parseFileProcess(), ConfigurationFileParser::parseFileProcess(), ParserSolverConfigFile, ParserSolverMeshFile, and ParserFiles::setFilePath().
Referenced by MultizoneSummaryDialog::addConfigData(), MainWindow::importMeshFile(), MultizoneIndividualTabForm::on_importMeshFileButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), MultizoneIndividualTabForm::setConfigFile(), MultizoneIndividualTabForm::setMeshFile(), and updateSolverUserValues().
 {
     switch(_option)
     {
         case ParserSolverConfigFile:
            {
                 ConfigurationFileParser _configParser;
                 _configParser.setFilePath(_pathFile);
                 _configParser.parseFileProcess();
                 *_userConfigVal = _configParser.getParsedValues();
                 * _virtualVOList = _configParser.getParsedVirtualMRFData();
             }
             break;
         case ParserSolverMeshFile:
             {
                 MeshFileParser _meshParser;
                 _meshParser.setFilePath(_pathFile);
                 _meshParser.parseFileProcess();
                 *_boundaryMeshVal = _meshParser.getParsedValues();
                 bool _isMesh3D = _meshParser.is3DMesh();
                 if (_isMesh3D)
                     *_boundaryMeshVal->insert(IS_3D_MESH_TAG,"YES");
             }
         break;
     }
 }
void InputDataTabHelper::registerButtons (QPushButton * _mybasicV, QPushButton * _mySummaryB, QPushButton * _myRunSimB, QPushButton * _myRestartB)
This function register the main Buttons of the Solver tab to controls their behaviour.
Parameters
_mybasicV
_mySummaryB
_myRunSimB
_myRestartB
Definition at line 384 of file inputdatatabhelper.cpp.
References _basicV, _restartB, _runSimB, and _summaryB.
Referenced by MainWindow::initializeHelper().
 {
     _basicV = _mybasicV;
     _summaryB = _mySummaryB;
     _runSimB= _myRunSimB  ;
    _restartB =  _myRestartB ;
 }
void InputDataTabHelper::registerLineEdits (QLabel * _myConfigLine, QLabel * _myMeshLine)
This function register the main Line Edits of the Solver tab to controls their behaviour.
Parameters
_myConfigLine
_myMeshLine
Definition at line 400 of file inputdatatabhelper.cpp.
References _configLineLabel, and _meshLineLabel.
Referenced by MainWindow::initializeHelper().
 {
     _configLineLabel = _myConfigLine;
     _meshLineLabel = _myMeshLine;
 }
void InputDataTabHelper::registerTab (QTabWidget * _myTab)
This function register the the Solver tab to controls their behaviour.
Parameters
_myTab
Definition at line 411 of file inputdatatabhelper.cpp.
References _tab.
Referenced by MainWindow::initializeHelper().
 {
     _tab = _myTab;
 }
void InputDataTabHelper::saveAsConfigFile (QString _fileName, ProjectData * _projectData, SolverConfigManager * _manager, QHash< QString, QString > _userVal, ProjectDetails _projectDetails, QList< VirtualMrfVO > _virtualVOList)
Dialog to save with a different name a configuration file.
Definition at line 116 of file inputdatatabhelper.cpp.
References SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), UtilFiles::hasFileExtension(), SolverConfigManager::saveConfigFile(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), and updateConfigurationFilePathInActionGroup().
Referenced by MainWindow::saveConfigFile().
 {
           if( !_fileName.isNull() )
            {
                UtilFiles _utilFiles;
                if (!_utilFiles.hasFileExtension(_fileName,"cfg"))
                    _fileName =  _fileName + ".cfg";
               _manager->saveConfigFile(_fileName,_userVal, _projectDetails,_virtualVOList);
              // Updatear el solverConfigFile
                 SolverVO _solver = _projectData->getSolverDataInformation();
                 _solver.setSolverConfigFilePath(_fileName);
                 _projectData->setSolverDataInformation(_solver);
                 updateConfigurationFilePathInActionGroup(_solver.getSolverConfigFilePath());
            }
 }
void InputDataTabHelper::showAllSolverMenus (ProjectData _projectData)
Show all the Tabs related with the solver Tool.
Definition at line 264 of file inputdatatabhelper.cpp.
References _tab, and enableConfigurationViewMenu().
Referenced by MainWindow::on_solverButton_clicked().
 {
   _tab->setEnabled(true);
   enableConfigurationViewMenu(_projectData);
 }
void InputDataTabHelper::updateConfigurationFilePathInActionGroup (QString _newPath)
Update the file path in the line edit of the current configuration file.
Parameters
_newPath
Definition at line 212 of file inputdatatabhelper.cpp.
References _configLineLabel.
Referenced by fillFileNamesInTab(), MainWindow::launchActionProjectSettingsDialog(), MainWindow::on_newActionButton_clicked(), MainWindow::openSolverConfigurationFileDialog(), and saveAsConfigFile().
 {
     QFileInfo _fileInfo(_newPath);
     QString _fileName = _fileInfo.fileName();
     _configLineLabel->setText(_fileName);
 }
void InputDataTabHelper::updateMeshFileNameInActionGroup (QString _newMeshPath, QHash< QString, QString > * _userMap)
Update the file path in the line edit of the current mesh file.
Parameters
_newMeshPath
Definition at line 225 of file inputdatatabhelper.cpp.
References _meshLineLabel.
Referenced by fillFileNamesInTab(), and MainWindow::updateMeshView().
 {
     QFileInfo _fileInfo(_newMeshPath);
     QString _fileName = _fileInfo.fileName();
     _meshLineLabel->setText(_fileName);
     _userMap->insert("MESH_FILENAME",_newMeshPath);
 }
bool InputDataTabHelper::updateSolverUserValues (ProjectData _projectData, QHash< QString, QString > * _userConfigVal, QHash< QString, QString > * _boundaryMeshVal, QHash< QString, QString > * _boundaryConfigVal, QList< VirtualMrfVO > * _virtualVOList)
Update the user values for the configuration file and the mesh files of the current project.
Definition at line 188 of file inputdatatabhelper.cpp.
References SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), parseFile(), ParserSolverConfigFile, and ParserSolverMeshFile.
Referenced by MainWindow::openProject(), and MainWindow::openSolverConfigurationFileDialog().
 {
     SolverVO _solverVO = _projectData.getSolverDataInformation();
     if (!_solverVO.getSolverConfigFilePath().isEmpty())
         parseFile(ParserSolverConfigFile,_solverVO.getSolverConfigFilePath(),_userConfigVal,
                   _boundaryMeshVal,_virtualVOList);
     if (!_solverVO.getSolverFilePath().isEmpty())
             parseFile(ParserSolverMeshFile,_solverVO.getSolverFilePath(),_userConfigVal,_boundaryMeshVal,_virtualVOList);
     return false;
 }
void InputDataTabHelper::updateUserConfigValues (QHash< QString, QString > _newMap, QHash< QString, QString > * _configValToSave, bool _reseted) private
Update the configuration values of the user in teh correspondent Hash variable.
Parameters
QHash<QString,QString> _newMap
Definition at line 173 of file inputdatatabhelper.cpp.
Referenced by launchSolverConfigDialog().
 {
     if ( (! _newMap.isEmpty()) ||
          ((_newMap.isEmpty()) && (_reseted)) )
       {
             *_configValToSave = _newMap;
       }
 }
Member Data Documentation
QPushButton* InputDataTabHelper::_basicV private
Definition at line 78 of file inputdatatabhelper.h.
Referenced by disableChangeConfigActionMenu(), enableChangeConfigActionMenu(), and registerButtons().
QLabel* InputDataTabHelper::_configLineLabel private
Definition at line 85 of file inputdatatabhelper.h.
Referenced by registerLineEdits(), and updateConfigurationFilePathInActionGroup().
QLabel* InputDataTabHelper::_meshLineLabel private
Definition at line 86 of file inputdatatabhelper.h.
Referenced by registerLineEdits(), and updateMeshFileNameInActionGroup().
QPushButton* InputDataTabHelper::_restartB private
Definition at line 91 of file inputdatatabhelper.h.
Referenced by disableRestartSimButtons(), enableRestartSimButtons(), and registerButtons().
QPushButton* InputDataTabHelper::_runSimB private
Definition at line 81 of file inputdatatabhelper.h.
Referenced by disableCurrentSimActionMenu(), enableCurrentSimActionMenu(), and registerButtons().
QPushButton* InputDataTabHelper::_saveAsB private
Definition at line 89 of file inputdatatabhelper.h.
QPushButton* InputDataTabHelper::_saveB private
Definition at line 88 of file inputdatatabhelper.h.
QPushButton* InputDataTabHelper::_summaryB private
Definition at line 80 of file inputdatatabhelper.h.
Referenced by disableChangeConfigActionMenu(), enableChangeConfigActionMenu(), and registerButtons().
QTabWidget* InputDataTabHelper::_tab private
Definition at line 90 of file inputdatatabhelper.h.
Referenced by hideAllSolverMenus(), registerTab(), and showAllSolverMenus().
The documentation for this class was generated from the following files:
WindowHelper/MainWindow/inputdatatabhelper.h
WindowHelper/MainWindow/inputdatatabhelper.cpp