BBIPED Platform: MarkerMenuManager Class Reference
MarkerMenuManager Class Reference
#include <markermenumanager.h>
Public Member Functions
MarkerMenuManager ()
Constructor.
QList< SolverMarkerMenu > getAllMarkerMenuList ()
Function that returns the marker menu list to be shown in the tree.
SolverMarkerMenu getMarkerNodeByName (QString _nodeName)
Function that obtains the Marker element by the node name.
Private Attributes
QList< SolverMarkerMenu > _markerMenuList
Detailed Description
Definition at line 10 of file markermenumanager.h.
Constructor & Destructor Documentation
MarkerMenuManager::MarkerMenuManager ()
Constructor.
Definition at line 26 of file markermenumanager.cpp.
References _markerMenuList, MarkerMenuReader::buildAllMarkerMenuNodes(), and MarkerMenuReader::getMarkerMenuList().
 {
   MarkerMenuReader _reader;
   _reader.buildAllMarkerMenuNodes();
   this->_markerMenuList = _reader.getMarkerMenuList();
 }
Member Function Documentation
QList< SolverMarkerMenu > MarkerMenuManager::getAllMarkerMenuList ()
Function that returns the marker menu list to be shown in the tree.
Returns
QList<SolverMarkerMenu>
Definition at line 38 of file markermenumanager.cpp.
References _markerMenuList.
 {
     return _markerMenuList;
 }
SolverMarkerMenu MarkerMenuManager::getMarkerNodeByName (QString _nodeName)
Function that obtains the Marker element by the node name.
Parameters
_nodeName
Returns
SolverMarkerMenu
Definition at line 49 of file markermenumanager.cpp.
References _markerMenuList, SolverMarkerMenu::getMarkerTitle(), and StrEqual.
Referenced by SpecificBoundaryVariableDialog::loadUserTableForConfiguration().
 {
     SolverMarkerMenu _result;
     for (int i = 0; i < _markerMenuList.count(); i++)
     {
         SolverMarkerMenu _nameToComapre = _markerMenuList.at(i);
         if (QString::compare(_nodeName,_nameToComapre.getMarkerTitle()) == StrEqual)
             return _markerMenuList.at(i);
     }
     return _result;
 }
Member Data Documentation
QList<SolverMarkerMenu> MarkerMenuManager::_markerMenuList private
Definition at line 18 of file markermenumanager.h.
Referenced by getAllMarkerMenuList(), getMarkerNodeByName(), and MarkerMenuManager().
The documentation for this class was generated from the following files:
Solver/markermenumanager.h
Solver/markermenumanager.cpp