BBIPED Platform: PreferenceDialog Class Reference
PreferenceDialog Class Reference
#include <preferencedialog.h>
Public Member Functions
PreferenceDialog (QWidget *parent=0)
Constructor.
~PreferenceDialog ()
Destructor.
QString getCustomizedMeshViewerSelectedPath ()
Returns the path of the customized mesh viewer.
QString getCustomizedPostProcessorViewerSelectedPath ()
Returns the path of the customized postprocessor viewer.
QString getCustomizedSolverEnginePath ()
Returns the path of the customized solver engine.
QString getTemplateConfigPath ()
Returns the path of the user selected template file.
UserPreferencesData getUserPreferencesData ()
Returns the User Preferencecs data with the new values.
void initialize ()
This function initializes all the variables needed by this dialog.
void initialize (QString _path)
This function initializes all the variables needed by this dialog in case other solver engine has been selected (a customized solver engine)
void initialize (UserPreferencesData _userData)
Initialize with the user preferences.
bool isCustomizedMeshViewerSelected ()
Returns true if a customized mesh viewer has been selected by the suer.
bool isCustomizedPostProcessorViewerSelectedPath ()
Returns true if the user has selected a specific post processor viewer.
bool isCustomizedSolverSelected ()
Returns true if the customized solver engine is selected.
bool isPreferencesAccepted ()
Returns true if the user has accepted the changes in the dialog.
bool isTemplateConfigSelected ()
Returns true if a template has been selected by the user.
void setCustomizedMeshViewerPath (QString _path)
Set the user path of the mesh viewer tool.
void setCustomizedPostProcessorViewerSelectedPath (QString _path)
Sets the user selected path of the post-processor viewer.
void setTemplateConfigPath (QString _file)
Stores the path of the user selected template file.
Private Slots
void on_customizedSolverEngineToolButton_clicked ()
This function loads the dialog for choosing the path of the customized solver engine.
void on_deleteMeshViewerConfButton_clicked ()
Function that deletes the already selected path for the mesh viewer tool.
void on_deletePostProcessorViewerConfButton_clicked ()
Restore the postprocessor viewer tab to its defaults.
void on_deleteTemplateButton_clicked ()
Function that controls the behaviour of the Template tab when deleting the selected tempalte.
void on_meshViewerConfLineToolButton_clicked ()
Function that defines the dialog launch for selecting the path for the mesh viewer tool.
void on_postProcessorViewerConfLineToolButton_clicked ()
Launchs the dialog to get the path of the postprocessor viewer.
void on_preferenceButtonBox_accepted ()
If the user accepts the change in the dialog.
void on_preferenceButtonBox_rejected ()
Action when the user rejects the changes.
void on_resetPreferencesToDefaultButton_clicked ()
Reset all the tabs to their default values.
void on_templateConfToolButton_clicked ()
Select the path of the template file.
void on_warningAppCheckBox_clicked (bool checked)
Set the option of showing (true value) or not (false value) the warning application close window.
void on_warningProjectCheckBox_clicked (bool checked)
Set the option of showing (true value) or not (false value) the warning project close window.
Private Member Functions
void enableCustomizedSolverMenu (bool _val)
This function enables/disables the Customized Solver line edit.
void getMeshViewerConfiguration (UserPreferencesData *_userData)
Returns the Mesh Data Configuration storing it in the user data.
void getPostProcessorViewerConfiguration (UserPreferencesData *_userData)
Returns the PostProcessor Data Configuration storing it in the user data.
void getSolverDataConfiguration (UserPreferencesData *_userData)
Returns the SolverData Configuration storing it in the user data.
void getTemplateConfigPath (UserPreferencesData *_userData)
Returns the Template Data Configuration storing it in the user data.
void getWarningConfiguration (UserPreferencesData *_userData)
Returns the Warning Data Configuration storing it in the user data.
void initializeMeshViewerData (UserPreferencesData _userData)
Initialize Mesh viewer data.
void initializePostProcessorViewerData (UserPreferencesData _userData)
Initialize post processor Viewer Data.
void initializeSolverData (UserPreferencesData _userData)
Initialize the solver data.
void initializeTemplateConfigData (UserPreferencesData _userData)
Initialize the template associated data according user selection.
void initializeVariables ()
This function initialize all the variables of this dialog.
void initializeWarningData (UserPreferencesData _userData)
Establish the set up for the warnings according user selection.
void resetMeshViewerTab ()
Reset the mesh viewer tab to its defaults.
void resetPostProcessorViewerTab ()
Reset the postprocessor viewer tab to its defaults.
void resetSolverEngineTab ()
Reset the solver engine Tab to its defaults.
void resetTemplateTab ()
Reset the tempalte tab to its defaults.
Private Attributes
QString _customizedMeshViewerPath
QString _customizedPostProcessorViewerPath
QString _customizedSolverEnginePath
bool _isCustomizedMeshViewerSelected
bool _isCustomizedPostProcessorViewerPath
bool _isCustomizedSolverSelected
bool _isDefaultSolverSelected
bool _isTemplateConfigSelected
bool _showWarningAppClose
bool _showWarningProjectClose
QString _templateConfigPath
bool _userAcceptChanges
Ui::PreferenceDialog * ui
Detailed Description
Definition at line 17 of file preferencedialog.h.
Constructor & Destructor Documentation
PreferenceDialog::PreferenceDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 28 of file preferencedialog.cpp.
References initializeVariables(), and ui.
                                                   :
     QDialog(parent),
     ui(new Ui::PreferenceDialog)
 {
     ui->setupUi(this);
     initializeVariables();
 }
PreferenceDialog::~PreferenceDialog ()
Destructor.
Definition at line 40 of file preferencedialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void PreferenceDialog::enableCustomizedSolverMenu (bool _val) private
This function enables/disables the Customized Solver line edit.
Parameters
_val
Definition at line 187 of file preferencedialog.cpp.
References ui.
Referenced by initialize().
 {
     ui->customizedSolverLabel->setEnabled(_val);
     ui->customizedSolverEnginePath->setEnabled(_val);
     ui->customizedSolverEngineToolButton->setEnabled(_val);
 }
QString PreferenceDialog::getCustomizedMeshViewerSelectedPath ()
Returns the path of the customized mesh viewer.
Returns
QString
Definition at line 382 of file preferencedialog.cpp.
References _customizedMeshViewerPath.
 {
     return _customizedMeshViewerPath;
 }
QString PreferenceDialog::getCustomizedPostProcessorViewerSelectedPath ()
Returns the path of the customized postprocessor viewer.
Returns
QString
Definition at line 444 of file preferencedialog.cpp.
References _customizedPostProcessorViewerPath.
 {
     return _customizedPostProcessorViewerPath;
 }
QString PreferenceDialog::getCustomizedSolverEnginePath ()
Returns the path of the customized solver engine.
Returns
QString
Definition at line 372 of file preferencedialog.cpp.
References _customizedSolverEnginePath.
 {
     return _customizedSolverEnginePath;
 }
void PreferenceDialog::getMeshViewerConfiguration (UserPreferencesData * _userData) private
Returns the Mesh Data Configuration storing it in the user data.
Parameters
_userData
Definition at line 568 of file preferencedialog.cpp.
References _customizedMeshViewerPath, _isCustomizedMeshViewerSelected, and UserPreferencesData::setMeshViewerPath().
Referenced by getUserPreferencesData().
 {
     if (_isCustomizedMeshViewerSelected)
         _userData->setMeshViewerPath(_customizedMeshViewerPath);
     else
         _userData->setMeshViewerPath("");
 }
void PreferenceDialog::getPostProcessorViewerConfiguration (UserPreferencesData * _userData) private
Returns the PostProcessor Data Configuration storing it in the user data.
Parameters
_userData
Definition at line 582 of file preferencedialog.cpp.
References _customizedPostProcessorViewerPath, _isCustomizedPostProcessorViewerPath, and UserPreferencesData::setPostProcessorViewerPath().
Referenced by getUserPreferencesData().
 {
     if (_isCustomizedPostProcessorViewerPath)
         _userData->setPostProcessorViewerPath(_customizedPostProcessorViewerPath);
     else
         _userData->setPostProcessorViewerPath("");
 }
void PreferenceDialog::getSolverDataConfiguration (UserPreferencesData * _userData) private
Returns the SolverData Configuration storing it in the user data.
Parameters
_userData
Definition at line 554 of file preferencedialog.cpp.
References _customizedSolverEnginePath, _isCustomizedSolverSelected, UserPreferencesData::setDefaultSolverEngineSelected(), and UserPreferencesData::setUserDefinedSolverPath().
Referenced by getUserPreferencesData().
 {
     if (_isCustomizedSolverSelected)
         _userData->setUserDefinedSolverPath(_customizedSolverEnginePath);
     else
      _userData->setDefaultSolverEngineSelected(true);
 }
QString PreferenceDialog::getTemplateConfigPath ()
Returns the path of the user selected template file.
Returns
QString
Definition at line 629 of file preferencedialog.cpp.
References _templateConfigPath.
Referenced by getUserPreferencesData().
 {
     return _templateConfigPath;
 }
void PreferenceDialog::getTemplateConfigPath (UserPreferencesData * _userData) private
Returns the Template Data Configuration storing it in the user data.
Parameters
_userData
Definition at line 607 of file preferencedialog.cpp.
References _templateConfigPath, and UserPreferencesData::setTemplateConfigPath().
 {
     _userData->setTemplateConfigPath(_templateConfigPath);
 }
UserPreferencesData PreferenceDialog::getUserPreferencesData ()
Returns the User Preferencecs data with the new values.
Returns
UserPreferencesData
Definition at line 526 of file preferencedialog.cpp.
References getMeshViewerConfiguration(), getPostProcessorViewerConfiguration(), getSolverDataConfiguration(), getTemplateConfigPath(), and getWarningConfiguration().
Referenced by EditHelper::launchPreferencesDialog().
 {
     UserPreferencesData _newUserData;
     // Getting the data from the Solver Engine
     getSolverDataConfiguration(&_newUserData);
     // Getting the data from the Mesh Viewer
     getMeshViewerConfiguration(&_newUserData);
     // Getting the data from the PostProcessor Viewer
     getPostProcessorViewerConfiguration(&_newUserData);
     // Getting the data from the Warning Conf
     getWarningConfiguration(&_newUserData);
     // Getting the data from the Template Conf
     getTemplateConfigPath(&_newUserData);
     return _newUserData;
 }
void PreferenceDialog::getWarningConfiguration (UserPreferencesData * _userData) private
Returns the Warning Data Configuration storing it in the user data.
Parameters
_userData
Definition at line 595 of file preferencedialog.cpp.
References _showWarningAppClose, _showWarningProjectClose, UserPreferencesData::setShowCloseProjectWarning(), and UserPreferencesData::setShowCloseWarning().
Referenced by getUserPreferencesData().
 {
     _userData->setShowCloseWarning(_showWarningAppClose);
     _userData->setShowCloseProjectWarning(_showWarningProjectClose);
 }
void PreferenceDialog::initialize ()
This function initializes all the variables needed by this dialog.
Definition at line 51 of file preferencedialog.cpp.
References _customizedMeshViewerPath, _customizedPostProcessorViewerPath, and _customizedSolverEnginePath.
Referenced by initializeSolverData(), and EditHelper::launchPreferencesDialog().
 {
     _customizedSolverEnginePath = "";
     _customizedMeshViewerPath = "";
     _customizedPostProcessorViewerPath = "";
 }
void PreferenceDialog::initialize (QString _path)
This function initializes all the variables needed by this dialog in case other solver engine has been selected (a customized solver engine)
Parameters
_path
Definition at line 154 of file preferencedialog.cpp.
References _customizedSolverEnginePath, _isCustomizedSolverSelected, enableCustomizedSolverMenu(), and ui.
 {
     _customizedSolverEnginePath = _path;
     // Changing the values of the window
     enableCustomizedSolverMenu(true);
     _isCustomizedSolverSelected = true;
     if (!_customizedSolverEnginePath.isEmpty())
         ui->customizedSolverEnginePath->setText(_customizedSolverEnginePath);
 }
void PreferenceDialog::initialize (UserPreferencesData _userData)
Initialize with the user preferences.
Parameters
_userData
Definition at line 63 of file preferencedialog.cpp.
References initializeMeshViewerData(), initializePostProcessorViewerData(), initializeSolverData(), initializeTemplateConfigData(), and initializeWarningData().
 {
     initializeSolverData(_userData);
     initializeMeshViewerData(_userData);
     initializePostProcessorViewerData(_userData);
     initializeWarningData(_userData);
     initializeTemplateConfigData(_userData);
 }
void PreferenceDialog::initializeMeshViewerData (UserPreferencesData _userData) private
Initialize Mesh viewer data.
Parameters
_userData
Definition at line 91 of file preferencedialog.cpp.
References UserPreferencesData::getMeshViewerPath(), and setCustomizedMeshViewerPath().
Referenced by initialize().
 {
     if (!_userData.getMeshViewerPath().isEmpty())
         setCustomizedMeshViewerPath(_userData.getMeshViewerPath());
 }
void PreferenceDialog::initializePostProcessorViewerData (UserPreferencesData _userData) private
Initialize post processor Viewer Data.
Parameters
_userData
Definition at line 103 of file preferencedialog.cpp.
References UserPreferencesData::getPostProcessorViewerPath(), and setCustomizedPostProcessorViewerSelectedPath().
Referenced by initialize().
 {
     if (!_userData.getPostProcessorViewerPath().isEmpty())
         setCustomizedPostProcessorViewerSelectedPath( _userData.getPostProcessorViewerPath());
 }
void PreferenceDialog::initializeSolverData (UserPreferencesData _userData) private
Initialize the solver data.
Parameters
_userData
Definition at line 78 of file preferencedialog.cpp.
References UserPreferencesData::getUserDefinedSolverPath(), and initialize().
Referenced by initialize().
 {
     if (!_userData.getUserDefinedSolverPath().isEmpty())
         initialize(_userData.getUserDefinedSolverPath());
     else
         initialize();
 }
void PreferenceDialog::initializeTemplateConfigData (UserPreferencesData _userData) private
Initialize the template associated data according user selection.
Parameters
_userData
Definition at line 131 of file preferencedialog.cpp.
References _isTemplateConfigSelected, _templateConfigPath, UserPreferencesData::getTemplateConfigPath(), and ui.
Referenced by initialize().
 {
     QString _templatePath = _userData.getTemplateConfigPath();
     if (!_templatePath.isEmpty())
     {
         _isTemplateConfigSelected = true;
         _templateConfigPath = _templatePath;
     }else
     {
         _isTemplateConfigSelected = false;
         _templateConfigPath = "";
     }
     ui->templateConfLineEdit->setText(_templateConfigPath);
 }
void PreferenceDialog::initializeVariables () private
This function initialize all the variables of this dialog.
Definition at line 170 of file preferencedialog.cpp.
References _isCustomizedMeshViewerSelected, _isCustomizedPostProcessorViewerPath, _isTemplateConfigSelected, _templateConfigPath, and _userAcceptChanges.
Referenced by PreferenceDialog().
 {
     _userAcceptChanges = false;
     _isCustomizedMeshViewerSelected = false;
     _isCustomizedPostProcessorViewerPath = false;
     _isTemplateConfigSelected = false;
     _templateConfigPath = "";
 }
void PreferenceDialog::initializeWarningData (UserPreferencesData _userData) private
Establish the set up for the warnings according user selection.
Parameters
_userData
Definition at line 114 of file preferencedialog.cpp.
References _showWarningAppClose, _showWarningProjectClose, UserPreferencesData::showCloseProjectWarning(), UserPreferencesData::showCloseWarning(), and ui.
Referenced by initialize().
 {
      _showWarningAppClose = _userData.showCloseWarning();
      _showWarningProjectClose = _userData.showCloseProjectWarning();
      // Update the checkboxes
      if (_showWarningAppClose)
          ui->warningAppCheckBox->setChecked(Qt::Checked);
      if (_showWarningProjectClose)
          ui->warningProjectCheckBox->setChecked(Qt::Checked);
 }
bool PreferenceDialog::isCustomizedMeshViewerSelected ()
Returns true if a customized mesh viewer has been selected by the suer.
Returns
bool
Definition at line 404 of file preferencedialog.cpp.
References _isCustomizedMeshViewerSelected.
 {
     return _isCustomizedMeshViewerSelected;
 }
bool PreferenceDialog::isCustomizedPostProcessorViewerSelectedPath ()
Returns true if the user has selected a specific post processor viewer.
Returns
bool
Definition at line 454 of file preferencedialog.cpp.
References _isCustomizedPostProcessorViewerPath.
 {
        return _isCustomizedPostProcessorViewerPath;
 }
bool PreferenceDialog::isCustomizedSolverSelected ()
Returns true if the customized solver engine is selected.
Returns
bool
Definition at line 392 of file preferencedialog.cpp.
References _isCustomizedSolverSelected.
 {
     return _isCustomizedSolverSelected;
 }
bool PreferenceDialog::isPreferencesAccepted ()
Returns true if the user has accepted the changes in the dialog.
Returns
bool
Definition at line 431 of file preferencedialog.cpp.
References _userAcceptChanges.
Referenced by EditHelper::launchPreferencesDialog().
 {
     return _userAcceptChanges;
 }
bool PreferenceDialog::isTemplateConfigSelected ()
Returns true if a template has been selected by the user.
Returns
bool
Definition at line 619 of file preferencedialog.cpp.
References _isTemplateConfigSelected.
 {
     return _isTemplateConfigSelected;
 }
void PreferenceDialog::on_customizedSolverEngineToolButton_clicked () private slot
This function loads the dialog for choosing the path of the customized solver engine.
Definition at line 202 of file preferencedialog.cpp.
References _customizedSolverEnginePath, _isCustomizedSolverSelected, and ui.
 {
     QString _binPath = QFileDialog::getOpenFileName(this, tr("Choose the Solver Engine Executable file"),
                                                             QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                                                             tr("All files(*)"));
     if (!_binPath.isNull())
     {
         _customizedSolverEnginePath = _binPath;
         _isCustomizedSolverSelected = true;
         ui->customizedSolverEnginePath->setText(_customizedSolverEnginePath);
     }else
     {
         return;
     }
 }
void PreferenceDialog::on_deleteMeshViewerConfButton_clicked () private slot
Function that deletes the already selected path for the mesh viewer tool.
Definition at line 260 of file preferencedialog.cpp.
References _isCustomizedMeshViewerSelected, and ui.
 {
     ui->meshViewerConfLineEdit->clear();
     _isCustomizedMeshViewerSelected = false;
 }
void PreferenceDialog::on_deletePostProcessorViewerConfButton_clicked () private slot
Restore the postprocessor viewer tab to its defaults.
Definition at line 344 of file preferencedialog.cpp.
References _isCustomizedPostProcessorViewerPath, and ui.
 {
     ui->postProcessorViewerConfLineEdit->clear();
     _isCustomizedPostProcessorViewerPath = false;
 }
void PreferenceDialog::on_deleteTemplateButton_clicked () private slot
Function that controls the behaviour of the Template tab when deleting the selected tempalte.
Definition at line 273 of file preferencedialog.cpp.
References _isTemplateConfigSelected, _templateConfigPath, and ui.
 {
     ui->templateConfLineEdit->clear();
     _isTemplateConfigSelected = false;
     _templateConfigPath = "";
 }
void PreferenceDialog::on_meshViewerConfLineToolButton_clicked () private slot
Function that defines the dialog launch for selecting the path for the mesh viewer tool.
Definition at line 244 of file preferencedialog.cpp.
References setCustomizedMeshViewerPath().
 {
     QString _binPath = QFileDialog::getOpenFileName(this, tr("Choose the Mesh Tool Engine Executable file"),
                                                             QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                                                             tr("All files(*)"));
     if (!_binPath.isNull())
         setCustomizedMeshViewerPath(_binPath);
     else
         return;
 }
void PreferenceDialog::on_postProcessorViewerConfLineToolButton_clicked () private slot
Launchs the dialog to get the path of the postprocessor viewer.
Definition at line 327 of file preferencedialog.cpp.
References setCustomizedPostProcessorViewerSelectedPath().
 {
     QString _binPath = QFileDialog::getOpenFileName(this, tr("Choose the PostProcessor Engine Executable file"),
                                                             QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                                                             tr("All files(*)"));
     if (!_binPath.isNull())
             setCustomizedPostProcessorViewerSelectedPath(_binPath);
     else
         return;
 }
void PreferenceDialog::on_preferenceButtonBox_accepted () private slot
If the user accepts the change in the dialog.
Definition at line 222 of file preferencedialog.cpp.
References _userAcceptChanges.
 {
     _userAcceptChanges = true;
     close();
 }
void PreferenceDialog::on_preferenceButtonBox_rejected () private slot
Action when the user rejects the changes.
Definition at line 232 of file preferencedialog.cpp.
References _userAcceptChanges.
 {
     _userAcceptChanges = false;
     close();
 }
void PreferenceDialog::on_resetPreferencesToDefaultButton_clicked () private slot
Reset all the tabs to their default values.
Definition at line 354 of file preferencedialog.cpp.
References resetMeshViewerTab(), resetPostProcessorViewerTab(), resetSolverEngineTab(), and resetTemplateTab().
 {
     resetSolverEngineTab();
     resetMeshViewerTab();
     resetPostProcessorViewerTab();
     resetTemplateTab();
 }
void PreferenceDialog::on_templateConfToolButton_clicked () private slot
Select the path of the template file.
Definition at line 283 of file preferencedialog.cpp.
References setTemplateConfigPath().
 {
     QString _workingPath = QDir(QCoreApplication::applicationDirPath()).filePath(".templates");
                // QDir::currentPath()).filePath(".templates");
     if (!QDir(_workingPath).exists())
         QDir(QCoreApplication::applicationDirPath()).mkdir(".templates");
                     //QDir::currentPath()).mkdir(".templates");
     QString _binPath = QFileDialog::getOpenFileName(this, tr("Choose the Template for the Physics Configuration"),
                                                             _workingPath,
                                                             tr("Template Config File Type(*.xml)"));
     if (!_binPath.isNull())
            setTemplateConfigPath(_binPath);
     else
         return;
 }
void PreferenceDialog::on_warningAppCheckBox_clicked (bool checked) private slot
Set the option of showing (true value) or not (false value) the warning application close window.
Parameters
checked
Definition at line 306 of file preferencedialog.cpp.
References _showWarningAppClose.
 {
     _showWarningAppClose = checked;
 }
void PreferenceDialog::on_warningProjectCheckBox_clicked (bool checked) private slot
Set the option of showing (true value) or not (false value) the warning project close window.
Parameters
checked
Definition at line 316 of file preferencedialog.cpp.
References _showWarningProjectClose.
 {
     _showWarningProjectClose = checked;
 }
void PreferenceDialog::resetMeshViewerTab () private
Reset the mesh viewer tab to its defaults.
Definition at line 491 of file preferencedialog.cpp.
References _isCustomizedMeshViewerSelected, setCustomizedMeshViewerPath(), and ui.
Referenced by on_resetPreferencesToDefaultButton_clicked().
 {
     _isCustomizedMeshViewerSelected = false;
     setCustomizedMeshViewerPath("");
     ui->meshViewerConfLineEdit->clear();
 }
void PreferenceDialog::resetPostProcessorViewerTab () private
Reset the postprocessor viewer tab to its defaults.
Definition at line 502 of file preferencedialog.cpp.
References _isCustomizedPostProcessorViewerPath, setCustomizedPostProcessorViewerSelectedPath(), and ui.
Referenced by on_resetPreferencesToDefaultButton_clicked().
 {
     _isCustomizedPostProcessorViewerPath = false;
     setCustomizedPostProcessorViewerSelectedPath("");
     ui->postProcessorViewerConfLineEdit->clear();
 }
void PreferenceDialog::resetSolverEngineTab () private
Reset the solver engine Tab to its defaults.
Definition at line 480 of file preferencedialog.cpp.
References _customizedSolverEnginePath, _isDefaultSolverSelected, and ui.
Referenced by on_resetPreferencesToDefaultButton_clicked().
 {
     _isDefaultSolverSelected = true;
     ui->customizedSolverEnginePath->clear();
     _customizedSolverEnginePath = "";
 }
void PreferenceDialog::resetTemplateTab () private
Reset the tempalte tab to its defaults.
Definition at line 513 of file preferencedialog.cpp.
References _isTemplateConfigSelected, setTemplateConfigPath(), and ui.
Referenced by on_resetPreferencesToDefaultButton_clicked().
 {
     _isTemplateConfigSelected = false;
     setTemplateConfigPath("");
     ui->templateConfLineEdit->clear();
 }
void PreferenceDialog::setCustomizedMeshViewerPath (QString _path)
Set the user path of the mesh viewer tool.
Parameters
_path
Definition at line 414 of file preferencedialog.cpp.
References _customizedMeshViewerPath, _isCustomizedMeshViewerSelected, and ui.
Referenced by initializeMeshViewerData(), on_meshViewerConfLineToolButton_clicked(), and resetMeshViewerTab().
 {
     if ( (!_path.isNull()) && (!_path.isEmpty()) )
     {
         _customizedMeshViewerPath = _path;
         _isCustomizedMeshViewerSelected = true;
         ui->meshViewerConfLineEdit->setText(_path);
     }
 }
void PreferenceDialog::setCustomizedPostProcessorViewerSelectedPath (QString _path)
Sets the user selected path of the post-processor viewer.
Parameters
_path
Definition at line 464 of file preferencedialog.cpp.
References _customizedPostProcessorViewerPath, _isCustomizedPostProcessorViewerPath, and ui.
Referenced by initializePostProcessorViewerData(), on_postProcessorViewerConfLineToolButton_clicked(), and resetPostProcessorViewerTab().
 {
     if ( (!_path.isNull()) && (!_path.isEmpty()) )
     {
         _customizedPostProcessorViewerPath = _path;
         _isCustomizedPostProcessorViewerPath = true;
         ui->postProcessorViewerConfLineEdit->setText(_path);
     }
 }
void PreferenceDialog::setTemplateConfigPath (QString _file)
Stores the path of the user selected template file.
Parameters
_file
Definition at line 639 of file preferencedialog.cpp.
References _isTemplateConfigSelected, _templateConfigPath, and ui.
Referenced by on_templateConfToolButton_clicked(), and resetTemplateTab().
 {
     _templateConfigPath = _file;
     if (!_templateConfigPath.isEmpty())
     {
         _isTemplateConfigSelected = true;
          ui->templateConfLineEdit->setText(_templateConfigPath);
     }
     else
     {
         _isTemplateConfigSelected = false;
         ui->templateConfLineEdit->clear();
     }
 }
Member Data Documentation
QString PreferenceDialog::_customizedMeshViewerPath private
Definition at line 74 of file preferencedialog.h.
Referenced by getCustomizedMeshViewerSelectedPath(), getMeshViewerConfiguration(), initialize(), and setCustomizedMeshViewerPath().
QString PreferenceDialog::_customizedPostProcessorViewerPath private
Definition at line 75 of file preferencedialog.h.
Referenced by getCustomizedPostProcessorViewerSelectedPath(), getPostProcessorViewerConfiguration(), initialize(), and setCustomizedPostProcessorViewerSelectedPath().
QString PreferenceDialog::_customizedSolverEnginePath private
Definition at line 73 of file preferencedialog.h.
Referenced by getCustomizedSolverEnginePath(), getSolverDataConfiguration(), initialize(), on_customizedSolverEngineToolButton_clicked(), and resetSolverEngineTab().
bool PreferenceDialog::_isCustomizedMeshViewerSelected private
Definition at line 81 of file preferencedialog.h.
Referenced by getMeshViewerConfiguration(), initializeVariables(), isCustomizedMeshViewerSelected(), on_deleteMeshViewerConfButton_clicked(), resetMeshViewerTab(), and setCustomizedMeshViewerPath().
bool PreferenceDialog::_isCustomizedPostProcessorViewerPath private
Definition at line 82 of file preferencedialog.h.
Referenced by getPostProcessorViewerConfiguration(), initializeVariables(), isCustomizedPostProcessorViewerSelectedPath(), on_deletePostProcessorViewerConfButton_clicked(), resetPostProcessorViewerTab(), and setCustomizedPostProcessorViewerSelectedPath().
bool PreferenceDialog::_isCustomizedSolverSelected private
Definition at line 77 of file preferencedialog.h.
Referenced by getSolverDataConfiguration(), initialize(), isCustomizedSolverSelected(), and on_customizedSolverEngineToolButton_clicked().
bool PreferenceDialog::_isDefaultSolverSelected private
Definition at line 78 of file preferencedialog.h.
Referenced by resetSolverEngineTab().
bool PreferenceDialog::_isTemplateConfigSelected private
Definition at line 87 of file preferencedialog.h.
Referenced by initializeTemplateConfigData(), initializeVariables(), isTemplateConfigSelected(), on_deleteTemplateButton_clicked(), resetTemplateTab(), and setTemplateConfigPath().
bool PreferenceDialog::_showWarningAppClose private
Definition at line 84 of file preferencedialog.h.
Referenced by getWarningConfiguration(), initializeWarningData(), and on_warningAppCheckBox_clicked().
bool PreferenceDialog::_showWarningProjectClose private
Definition at line 85 of file preferencedialog.h.
Referenced by getWarningConfiguration(), initializeWarningData(), and on_warningProjectCheckBox_clicked().
QString PreferenceDialog::_templateConfigPath private
Definition at line 88 of file preferencedialog.h.
Referenced by getTemplateConfigPath(), initializeTemplateConfigData(), initializeVariables(), on_deleteTemplateButton_clicked(), and setTemplateConfigPath().
bool PreferenceDialog::_userAcceptChanges private
Definition at line 79 of file preferencedialog.h.
Referenced by initializeVariables(), isPreferencesAccepted(), on_preferenceButtonBox_accepted(), and on_preferenceButtonBox_rejected().
Ui::PreferenceDialog* PreferenceDialog::ui private
Definition at line 72 of file preferencedialog.h.
Referenced by enableCustomizedSolverMenu(), initialize(), initializeTemplateConfigData(), initializeWarningData(), on_customizedSolverEngineToolButton_clicked(), on_deleteMeshViewerConfButton_clicked(), on_deletePostProcessorViewerConfButton_clicked(), on_deleteTemplateButton_clicked(), PreferenceDialog(), resetMeshViewerTab(), resetPostProcessorViewerTab(), resetSolverEngineTab(), resetTemplateTab(), setCustomizedMeshViewerPath(), setCustomizedPostProcessorViewerSelectedPath(), setTemplateConfigPath(), and ~PreferenceDialog().
The documentation for this class was generated from the following files:
Forms/EditMenuDialog/preferencedialog.h
Forms/EditMenuDialog/preferencedialog.cpp