BBIPED Platform: MarkerMenuReader Class Reference
MarkerMenuReader Class Reference
#include <markermenureader.h>
Public Member Functions
MarkerMenuReader ()
Constructors.
~MarkerMenuReader ()
void buildAllMarkerMenuNodes ()
Function that builds the Marker Menu Nodes to be shown in the Tree view.
QList< SolverMarkerMenu > getMarkerMenuList ()
Get the Boundary/Marker menu list.
QString getMarkerName (QDomElement _element, QString tagName)
Function that gets a Marker node name from the DOM XML file.
void loadAllFile ()
Function that loads the xml file and gets all the nodes of the menu.
Private Member Functions
QStringList createDefaultValueList (QDomElement _element)
SolverMarkerMenu createMarkerNode (QDomNode _node)
Function that creates a Marker node from the DOM XML file.
QStringList createParameterList (QDomElement _element)
Function that creates the Parameter List from the DOM XML file.
QStringList createTypeList (QDomElement _element)
Function that creates a the type list from the DOM XML file.
QStringList createUnitList (QDomElement _element)
Function that creates the Unit type List from the DOM XML file.
Private Attributes
QDomDocument * _domtree
bool _isInitialized
QList< SolverMarkerMenu > _markerMenuList
Detailed Description
Definition at line 8 of file markermenureader.h.
Constructor & Destructor Documentation
MarkerMenuReader::MarkerMenuReader ()
Constructors.
Definition at line 29 of file markermenureader.cpp.
References _isInitialized.
 {
     _isInitialized = false;
 }
MarkerMenuReader::~MarkerMenuReader ()
Definition at line 34 of file markermenureader.cpp.
References _domtree, and _isInitialized.
 {
     if (_isInitialized)
         delete _domtree;
 }
Member Function Documentation
void MarkerMenuReader::buildAllMarkerMenuNodes ()
Function that builds the Marker Menu Nodes to be shown in the Tree view.
Definition at line 75 of file markermenureader.cpp.
References _domtree, _isInitialized, loadAllFile(), and MARKER_XML_TEMPLATE.
Referenced by MarkerMenuManager::MarkerMenuManager().
 {
     QFile * _templateConfigFile = new QFile(MARKER_XML_TEMPLATE);
     _domtree = new QDomDocument();
     if( !_templateConfigFile->open( QIODevice::ReadOnly | QIODevice::Text ) )
     {
         qDebug( "Failed to open file for reading." );
     }
     else
     {
         if( !_domtree->setContent( _templateConfigFile ) )
         {
             qDebug( "Failed to parse the file into a DOM tree." );
             _templateConfigFile->close();
         }
           _templateConfigFile->close();
            loadAllFile();
     }
     _templateConfigFile->close();
     delete _templateConfigFile;
     _isInitialized = true;
 }
QStringList MarkerMenuReader::createDefaultValueList (QDomElement _element) private
Definition at line 145 of file markermenureader.cpp.
References XML_MARKER_DEFAULT_VALUE_ATT, and XML_MARKER_PARAMETER_LIST_TAG_NAME.
Referenced by createMarkerNode().
 {
     QDomNodeList _listParameter =
             _element.elementsByTagName(XML_MARKER_PARAMETER_LIST_TAG_NAME);
     QStringList _result;
     if (!_listParameter.isEmpty())
     {
         QDomNodeList _childNodes = _listParameter.at(0).childNodes();
         for (int i = 0; i < _childNodes.count();i++)
         {
             QDomElement _nodeEl = _childNodes.at(i).toElement();
             if (_nodeEl.hasAttribute(XML_MARKER_DEFAULT_VALUE_ATT))
                 _result.append(_nodeEl.attribute(XML_MARKER_DEFAULT_VALUE_ATT));
         }
     }
     return _result;
 }
SolverMarkerMenu MarkerMenuReader::createMarkerNode (QDomNode _node) private
Function that creates a Marker node from the DOM XML file.
Parameters
_node
Returns
SolverMarkerMenu
Definition at line 129 of file markermenureader.cpp.
References createDefaultValueList(), createParameterList(), createTypeList(), createUnitList(), getMarkerName(), SolverMarkerMenu::setDefaultValueList(), SolverMarkerMenu::setMarkerFileName(), SolverMarkerMenu::setMarkerTitle(), SolverMarkerMenu::setParametersList(), SolverMarkerMenu::setTypeList(), SolverMarkerMenu::setUnitList(), XML_MARKER_FILENAME_TAG_NAME, and XML_MARKER_NAME_TAG_NAME.
Referenced by loadAllFile().
 {
     SolverMarkerMenu _markerVO;
     QDomElement _markerEl = _node.toElement();
     if (!_markerEl.isNull())
     {
         _markerVO.setMarkerTitle(getMarkerName(_markerEl,XML_MARKER_NAME_TAG_NAME));
         _markerVO.setMarkerFileName(getMarkerName(_markerEl,XML_MARKER_FILENAME_TAG_NAME));
         _markerVO.setParametersList(createParameterList(_markerEl));
         _markerVO.setTypeList(createTypeList(_markerEl));
         _markerVO.setUnitList(createUnitList(_markerEl));
         _markerVO.setDefaultValueList(createDefaultValueList(_markerEl));
     }
     return _markerVO;
 }
QStringList MarkerMenuReader::createParameterList (QDomElement _element) private
Function that creates the Parameter List from the DOM XML file.
Parameters
_element
Returns
QStringList
Definition at line 170 of file markermenureader.cpp.
References XML_MARKER_PARAMETER_LIST_TAG_NAME.
Referenced by createMarkerNode().
 {
     QDomNodeList _listParameter =
             _element.elementsByTagName(XML_MARKER_PARAMETER_LIST_TAG_NAME);
     QStringList _result;
     if (!_listParameter.isEmpty())
     {
         QDomNodeList _childNodes = _listParameter.at(0).childNodes();
         for (int i = 0; i < _childNodes.count();i++)
             _result.append(_childNodes.at(i).toElement().text());
     }
     return _result;
 }
QStringList MarkerMenuReader::createTypeList (QDomElement _element) private
Function that creates a the type list from the DOM XML file.
Parameters
_element
Returns
QStringList
Definition at line 217 of file markermenureader.cpp.
References XML_MARKER_PARAMETER_LIST_TAG_NAME, and XML_MARKER_TYPE_ATT.
Referenced by createMarkerNode().
 {
     QDomNodeList _listParameter =
             _element.elementsByTagName(XML_MARKER_PARAMETER_LIST_TAG_NAME);
     QStringList _result;
     if (!_listParameter.isEmpty())
     {
         QDomNodeList _childNodes = _listParameter.at(0).childNodes();
         for (int i = 0; i < _childNodes.count();i++)
         {
             QDomElement _nodeEl = _childNodes.at(i).toElement();
             if (_nodeEl.hasAttribute(XML_MARKER_TYPE_ATT))
                 _result.append(_nodeEl.attribute(XML_MARKER_TYPE_ATT));
         }
     }
     return _result;
 }
QStringList MarkerMenuReader::createUnitList (QDomElement _element) private
Function that creates the Unit type List from the DOM XML file.
Parameters
_element
Returns
QStringList
Definition at line 192 of file markermenureader.cpp.
References XML_MARKER_PARAMETER_LIST_TAG_NAME, and XML_MARKER_UNIT_ATT.
Referenced by createMarkerNode().
 {
     QDomNodeList _listParameter =
             _element.elementsByTagName(XML_MARKER_PARAMETER_LIST_TAG_NAME);
     QStringList _result;
     if (!_listParameter.isEmpty())
     {
         QDomNodeList _childNodes = _listParameter.at(0).childNodes();
         for (int i = 0; i < _childNodes.count();i++)
         {
             QDomElement _nodeEl = _childNodes.at(i).toElement();
             if (_nodeEl.hasAttribute(XML_MARKER_UNIT_ATT))
                 _result.append(_nodeEl.attribute(XML_MARKER_UNIT_ATT));
         }
     }
     return _result;
 }
QList< SolverMarkerMenu > MarkerMenuReader::getMarkerMenuList ()
Get the Boundary/Marker menu list.
Returns
QList<SolverMarkerMenu>
Definition at line 46 of file markermenureader.cpp.
References _markerMenuList.
Referenced by MarkerMenuManager::MarkerMenuManager().
 {
      return _markerMenuList;
 }
QString MarkerMenuReader::getMarkerName (QDomElement _element, QString tagName)
Function that gets a Marker node name from the DOM XML file.
Parameters
_element
tagName
Returns
QString
Definition at line 60 of file markermenureader.cpp.
Referenced by createMarkerNode().
 {
     QDomNodeList _listName = _element.elementsByTagName(tagName);
     if (!_listName.isEmpty())
         return (_listName.at(0).toElement().text());
     return QString("");
 }
void MarkerMenuReader::loadAllFile ()
Function that loads the xml file and gets all the nodes of the menu.
Definition at line 105 of file markermenureader.cpp.
References _domtree, _markerMenuList, createMarkerNode(), and XML_MARKER_NODE_TAG_NAME.
Referenced by buildAllMarkerMenuNodes().
 {
     QDomElement _rootElement = _domtree->documentElement();
     if (!_rootElement.isNull())
     {
         QDomNodeList _list = _rootElement.elementsByTagName(XML_MARKER_NODE_TAG_NAME);
         if (!_list.isEmpty())
             for (int i = 0; i < _list.count();i++)
             {
                 SolverMarkerMenu _node = createMarkerNode(_list.at(i));
                 _markerMenuList.append(_node);
             }
     }
 }
Member Data Documentation
QDomDocument* MarkerMenuReader::_domtree private
Definition at line 25 of file markermenureader.h.
Referenced by buildAllMarkerMenuNodes(), loadAllFile(), and ~MarkerMenuReader().
bool MarkerMenuReader::_isInitialized private
Definition at line 27 of file markermenureader.h.
Referenced by buildAllMarkerMenuNodes(), MarkerMenuReader(), and ~MarkerMenuReader().
QList<SolverMarkerMenu> MarkerMenuReader::_markerMenuList private
Definition at line 26 of file markermenureader.h.
Referenced by getMarkerMenuList(), and loadAllFile().
The documentation for this class was generated from the following files:
Solver/markermenureader.h
Solver/markermenureader.cpp