BBIPED Platform: WarningMultizoneDialog Class Reference
WarningMultizoneDialog Class Reference
#include <warningmultizonedialog.h>
Public Member Functions
WarningMultizoneDialog (QWidget *parent=0)
Constructor.
~WarningMultizoneDialog ()
Destructor.
QHash< QString, QString > getConfigValues ()
Function to get the configuration values.
void initializeFileNames (QString _configFile, QString _meshFile)
Function to set the file names under analysis.
bool isNeedToUpdate ()
Function that returns if it is needed to uptdate the values.
bool keepValues ()
Function that returns if it is needed to keep the values.
void setConfigValues (QHash< QString, QString > _map)
Function to set the configuration values.
void setMeshValueNames (QHash< QString, QString > _map)
Function to set the mesh values.
bool userAcceptChanges ()
Function that returns if the user accept the changes.
Private Slots
void changedComboValueByUser (QString _position)
Slot that controls the change of values by the user in the combos.
void on_buttonBox_accepted ()
Function that provides the actions when the user accepts the changes.
void on_buttonBox_rejected ()
Function that provides the actions when the user rejects the changes.
void on_keepRadioButton_clicked ()
Function that controsl when the user wants to keep the values.
void on_updateRadioButton_clicked ()
Function that controls when the user clicks the update radio button.
Private Member Functions
void addSignalToCombo (QComboBox *_combo, int _idRow, int _idCol)
Function that adds the signal to the combos.
QStringList buildList (QHash< QString, QString > _map)
This function builds a QStringList with all the values of the map.
void buildRow (QString _markerFileName, QString cValue, QStringList _meshVarNameList, QString _markerKeyName)
Function that builds the Rows with the correspondent values.
void fillRepairTable ()
Function that fills the data in the table for repairing the values.
QHash< QString, QString > getMarkerValues ()
Function that get the mesh values.
QStringList getMeshVarNames ()
Function that get the mesh var names.
QString removeBrakets (QString _text)
This function remove Brakets fo a text.
void setEnableRepairSection (bool _val)
Function that enables the sectioos for repairing the data.
void updateConfigurationValues ()
Function that update the configuration values.
Private Attributes
QHash< QString, QString > _configValues
bool _isLoadingTable
bool _keepValues
QList< SolverSectionVO > _menuSectionList
QHash< QString, QString > _meshValueNames
bool _needToUpdate
bool _repairTableFilled
QSignalMapper * _signalMapper
bool _userAcceptChanges
QHash< QString, QString > _userRepairedValues
Ui::WarningMultizoneDialog * ui
Detailed Description
Definition at line 17 of file warningmultizonedialog.h.
Constructor & Destructor Documentation
WarningMultizoneDialog::WarningMultizoneDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 37 of file warningmultizonedialog.cpp.
References _isLoadingTable, _keepValues, _menuSectionList, _needToUpdate, _repairTableFilled, _signalMapper, _userAcceptChanges, SolverConfigManager::getAllSectionMenuList(), SolverConfigManager::initializeManager(), and ui.
                                                               :
     QDialog(parent),
     ui(new Ui::WarningMultizoneDialog)
 {
     ui->setupUi(this);
     _needToUpdate = true;
     _keepValues = false;
     _userAcceptChanges = false;
     _isLoadingTable = false;
     _repairTableFilled = false;
     _signalMapper = new QSignalMapper(this);
     SolverConfigManager _solverManager;
     _solverManager.initializeManager();
     _menuSectionList = _solverManager.getAllSectionMenuList();
 }
WarningMultizoneDialog::~WarningMultizoneDialog ()
Destructor.
Definition at line 57 of file warningmultizonedialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void WarningMultizoneDialog::addSignalToCombo (QComboBox * _combo, int _idRow, int _idCol) private
Function that adds the signal to the combos.
Parameters
_combo
_idRow
_idCol
Definition at line 308 of file warningmultizonedialog.cpp.
References _signalMapper.
Referenced by buildRow().
 {
         connect(_combo, SIGNAL(currentIndexChanged(int)), _signalMapper, SLOT(map()),Qt::UniqueConnection);
        _signalMapper->setMapping(_combo, QString("%1-%2").arg(_idRow).arg(_idCol));
 }
QStringList WarningMultizoneDialog::buildList (QHash< QString, QString > _map) private
This function builds a QStringList with all the values of the map.
Parameters
QHash<QString
_map
Returns
QStringList
Definition at line 265 of file warningmultizonedialog.cpp.
 {
     QStringList _list;
     if (!_map.isEmpty())
     {
         QHashIterator<QString,QString> _iter(_map);
         while(_iter.hasNext())
         {
             _iter.next();
             _list.append(_iter.value());
         }
     }
     return _list;
 }
void WarningMultizoneDialog::buildRow (QString _markerFileName, QString _cValue, QStringList _meshVarNameList, QString _markerKeyName) private
Function that builds the Rows with the correspondent values.
Parameters
_markerFileName
_cValue
_meshVarNameList
Definition at line 223 of file warningmultizonedialog.cpp.
References _userRepairedValues, QtableUtil::addCombo(), QtableUtil::addNonEditableText(), addSignalToCombo(), REPAIR_NEW_VALUE_COLUMN, REPAIR_OLD_VALUE_COLUMN, REPAIR_VARIABLE_NAME_COLUMN, and ui.
Referenced by fillRepairTable().
 {
     QtableUtil _tableHelper;
     int _lastRow = ui->repairMeshValuesTable->rowCount();
     ui->repairMeshValuesTable->insertRow(_lastRow);
     ui->repairMeshValuesTable->setItem(_lastRow,REPAIR_VARIABLE_NAME_COLUMN,_tableHelper.addNonEditableText(_markerFileName));
     ui->repairMeshValuesTable->setItem(_lastRow,REPAIR_OLD_VALUE_COLUMN,_tableHelper.addNonEditableText(_cValue));
     QList<bool> _selectable;
     for (int i = 0; i< _meshVarNameList.size();i++)
         _selectable.append(true);
     QComboBox * _combo = _tableHelper.addCombo(_meshVarNameList,_selectable);
     ui->repairMeshValuesTable->setCellWidget(_lastRow,REPAIR_NEW_VALUE_COLUMN,_combo);
     addSignalToCombo(_combo,_lastRow,REPAIR_NEW_VALUE_COLUMN);
     _userRepairedValues.insert(_markerKeyName,"NONE");
 }
void WarningMultizoneDialog::changedComboValueByUser (QString _position) private slot
Slot that controls the change of values by the user in the combos.
Parameters
_position
Definition at line 142 of file warningmultizonedialog.cpp.
References _configValues, _isLoadingTable, _menuSectionList, _userRepairedValues, COMMA_SEPARATOR, SolverSectionDAO::findValueNameByVariableName(), REPAIR_VARIABLE_NAME_COLUMN, and ui.
Referenced by fillRepairTable().
 {
     if (!_isLoadingTable)
     {
         QStringList coordinates = _position.split("-");
         int row = coordinates[0].toInt();
         int col = coordinates[1].toInt();
         QComboBox* combo = (QComboBox*) ui->repairMeshValuesTable->cellWidget(row, col);
         QString _value = combo->currentText();
         QString _varName = ui->repairMeshValuesTable->item(row,REPAIR_VARIABLE_NAME_COLUMN)->text();
         SolverSectionDAO _dao;
         QString _keyName = _dao.findValueNameByVariableName(_menuSectionList,_varName);
         QString _oldValue = _configValues.value(_keyName);
         if (_oldValue.contains("("))
             _oldValue.remove("(");
         if (_oldValue.contains(")"))
             _oldValue.remove(")");
         QStringList _oldElements = _oldValue.split(COMMA_SEPARATOR);
         if (!_oldElements.isEmpty())
             _oldElements[0] = _value;
         else
             _oldElements.append(_value);
         QString _newValue = "("+_oldElements.join(COMMA_SEPARATOR) +")";
         _userRepairedValues.insert(_keyName,_newValue);
     }
 }
void WarningMultizoneDialog::fillRepairTable () private
Function that fills the data in the table for repairing the values.
Definition at line 194 of file warningmultizonedialog.cpp.
References _menuSectionList, _repairTableFilled, _signalMapper, buildRow(), changedComboValueByUser(), SolverSectionDAO::findVariableByFileName(), getMarkerValues(), getMeshVarNames(), SolverVariableVO::getVariableFileName(), SolverVariableVO::getVariableName(), and SolverVariableVO::isEmpty().
Referenced by on_updateRadioButton_clicked().
 {
     QHash<QString,QString> _oldMeshValues = getMarkerValues();
     QStringList _meshVariableName = getMeshVarNames();
     if (!_oldMeshValues.isEmpty())
     {
         QHashIterator<QString,QString> iter(_oldMeshValues);
         SolverSectionDAO _dao;
         while(iter.hasNext())
         {
             iter.next();
             SolverVariableVO _varVO = _dao.findVariableByFileName(_menuSectionList,iter.key());
             if ( (!_varVO.isEmpty()) && (!iter.value().contains("NONE")) )
                buildRow(_varVO.getVariableName(),iter.value(),_meshVariableName,_varVO.getVariableFileName());
         }
         connect(_signalMapper, SIGNAL(mapped(const QString &)),this, SLOT(changedComboValueByUser(const QString &)),Qt::UniqueConnection);
         _repairTableFilled = true;
     }
 }
QHash< QString, QString > WarningMultizoneDialog::getConfigValues ()
Function to get the configuration values.
Returns
QHash<QString, QString>
Definition at line 344 of file warningmultizonedialog.cpp.
References _configValues.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     return _configValues ;
 }
QHash< QString, QString > WarningMultizoneDialog::getMarkerValues () private
Function that get the mesh values.
Returns
QHash<QString, QString>
Definition at line 407 of file warningmultizonedialog.cpp.
References _configValues.
Referenced by fillRepairTable().
 {
     QHash<QString,QString> _markerSet;
     QHashIterator<QString,QString> iter(_configValues);
     while(iter.hasNext())
     {
         iter.next();
         QString _key = iter.key();
         if( (_key.contains("MARKER_")) || (_key.contains("BC_")) )
            _markerSet.insert(_key,iter.value());
     }
     return _markerSet;
 }
QStringList WarningMultizoneDialog::getMeshVarNames () private
Function that get the mesh var names.
Returns
QStringList
Definition at line 385 of file warningmultizonedialog.cpp.
References _meshValueNames.
Referenced by fillRepairTable().
 {
     QStringList _list;
     QHashIterator<QString,QString> iter(_meshValueNames);
     _list.append("NONE");
     while(iter.hasNext())
     {
         iter.next();
         _list.append(iter.value());
     }
     return _list;
 }
void WarningMultizoneDialog::initializeFileNames (QString _configFile, QString _meshFile)
Function to set the file names under analysis.
Parameters
_configFile
_meshFile
Definition at line 69 of file warningmultizonedialog.cpp.
References setEnableRepairSection(), and ui.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     ui->configFileName->setText(_configFile);
     ui->meshFileName->setText(_meshFile);
     setEnableRepairSection(false);
 }
bool WarningMultizoneDialog::isNeedToUpdate ()
Function that returns if it is needed to uptdate the values.
Returns
bool
Definition at line 355 of file warningmultizonedialog.cpp.
References _needToUpdate.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     return _needToUpdate;
 }
bool WarningMultizoneDialog::keepValues ()
Function that returns if it is needed to keep the values.
Returns
bool
Definition at line 365 of file warningmultizonedialog.cpp.
References _keepValues.
 {
     return _keepValues;
 }
void WarningMultizoneDialog::on_buttonBox_accepted () private slot
Function that provides the actions when the user accepts the changes.
Definition at line 116 of file warningmultizonedialog.cpp.
References _needToUpdate, _userAcceptChanges, and updateConfigurationValues().
 {
     _userAcceptChanges = true;
     if (_needToUpdate)
         updateConfigurationValues();
     close();
 }
void WarningMultizoneDialog::on_buttonBox_rejected () private slot
Function that provides the actions when the user rejects the changes.
Definition at line 129 of file warningmultizonedialog.cpp.
References _userAcceptChanges.
 {
     _userAcceptChanges = false;
     close();
 }
void WarningMultizoneDialog::on_keepRadioButton_clicked () private slot
Function that controsl when the user wants to keep the values.
Definition at line 100 of file warningmultizonedialog.cpp.
References _keepValues, _needToUpdate, setEnableRepairSection(), and ui.
 {
     ui->updateRadioButton->setChecked(false);
     ui->keepRadioButton->setChecked(true);
     _needToUpdate = false;
     _keepValues = true;
     setEnableRepairSection(false);
 }
void WarningMultizoneDialog::on_updateRadioButton_clicked () private slot
Function that controls when the user clicks the update radio button.
Definition at line 83 of file warningmultizonedialog.cpp.
References _isLoadingTable, _keepValues, _needToUpdate, _repairTableFilled, fillRepairTable(), setEnableRepairSection(), and ui.
 {
     ui->updateRadioButton->setChecked(true);
     ui->keepRadioButton->setChecked(false);
     setEnableRepairSection(true);
     _isLoadingTable = true;
     if (!_repairTableFilled)
         fillRepairTable();
     _isLoadingTable = false;
     _needToUpdate = true;
     _keepValues = false;
 }
QString WarningMultizoneDialog::removeBrakets (QString _text) private
This function remove Brakets fo a text.
Parameters
_text
Returns
QString
Definition at line 290 of file warningmultizonedialog.cpp.
Referenced by updateConfigurationValues().
 {
     if (_text.contains("("))
         _text.remove("(");
     if (_text.contains(")"))
         _text.remove(")");
     return _text;
 }
void WarningMultizoneDialog::setConfigValues (QHash< QString, QString > _map)
Function to set the configuration values.
Parameters
QHash<QString
_map
Definition at line 324 of file warningmultizonedialog.cpp.
References _configValues.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     _configValues = _map;
 }
void WarningMultizoneDialog::setEnableRepairSection (bool _val) private
Function that enables the sectioos for repairing the data.
Parameters
_val
Definition at line 180 of file warningmultizonedialog.cpp.
References ui.
Referenced by initializeFileNames(), on_keepRadioButton_clicked(), and on_updateRadioButton_clicked().
 {
     ui->repairLabel->setEnabled(_val);
     ui->repairMeshValuesTable->setEnabled(_val);
 }
void WarningMultizoneDialog::setMeshValueNames (QHash< QString, QString > _map)
Function to set the mesh values.
Parameters
QHash<QString
_map
Definition at line 335 of file warningmultizonedialog.cpp.
References _meshValueNames.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     _meshValueNames = _map;
 }
void WarningMultizoneDialog::updateConfigurationValues () private
Function that update the configuration values.
Definition at line 244 of file warningmultizonedialog.cpp.
References _configValues, _userRepairedValues, and removeBrakets().
Referenced by on_buttonBox_accepted().
 {
     QHashIterator<QString,QString> _iter(_userRepairedValues);
     while(_iter.hasNext())
     {
         _iter.next();
         QString _keyName = _iter.key();
         QString _value = removeBrakets(_iter.value());
        _configValues.insert(_keyName,_value);
     }
    // _configValues.insert("MESH_FILENAME",ui->meshFileName->text());
 }
bool WarningMultizoneDialog::userAcceptChanges ()
Function that returns if the user accept the changes.
Returns
bool
Definition at line 375 of file warningmultizonedialog.cpp.
References _userAcceptChanges.
Referenced by MultizoneProjectDialog::checkConsistency(), and MainWindow::checkMeshNames().
 {
     return _userAcceptChanges;
 }
Member Data Documentation
QHash<QString,QString> WarningMultizoneDialog::_configValues private
Definition at line 48 of file warningmultizonedialog.h.
Referenced by changedComboValueByUser(), getConfigValues(), getMarkerValues(), setConfigValues(), and updateConfigurationValues().
bool WarningMultizoneDialog::_isLoadingTable private
Definition at line 52 of file warningmultizonedialog.h.
Referenced by changedComboValueByUser(), on_updateRadioButton_clicked(), and WarningMultizoneDialog().
bool WarningMultizoneDialog::_keepValues private
Definition at line 45 of file warningmultizonedialog.h.
Referenced by keepValues(), on_keepRadioButton_clicked(), on_updateRadioButton_clicked(), and WarningMultizoneDialog().
QList<SolverSectionVO> WarningMultizoneDialog::_menuSectionList private
Definition at line 53 of file warningmultizonedialog.h.
Referenced by changedComboValueByUser(), fillRepairTable(), and WarningMultizoneDialog().
QHash<QString,QString> WarningMultizoneDialog::_meshValueNames private
Definition at line 49 of file warningmultizonedialog.h.
Referenced by getMeshVarNames(), and setMeshValueNames().
bool WarningMultizoneDialog::_needToUpdate private
Definition at line 44 of file warningmultizonedialog.h.
Referenced by isNeedToUpdate(), on_buttonBox_accepted(), on_keepRadioButton_clicked(), on_updateRadioButton_clicked(), and WarningMultizoneDialog().
bool WarningMultizoneDialog::_repairTableFilled private
Definition at line 47 of file warningmultizonedialog.h.
Referenced by fillRepairTable(), on_updateRadioButton_clicked(), and WarningMultizoneDialog().
QSignalMapper* WarningMultizoneDialog::_signalMapper private
Definition at line 51 of file warningmultizonedialog.h.
Referenced by addSignalToCombo(), fillRepairTable(), and WarningMultizoneDialog().
bool WarningMultizoneDialog::_userAcceptChanges private
Definition at line 46 of file warningmultizonedialog.h.
Referenced by on_buttonBox_accepted(), on_buttonBox_rejected(), userAcceptChanges(), and WarningMultizoneDialog().
QHash<QString,QString> WarningMultizoneDialog::_userRepairedValues private
Definition at line 50 of file warningmultizonedialog.h.
Referenced by buildRow(), changedComboValueByUser(), and updateConfigurationValues().
Ui::WarningMultizoneDialog* WarningMultizoneDialog::ui private
Definition at line 43 of file warningmultizonedialog.h.
Referenced by buildRow(), changedComboValueByUser(), initializeFileNames(), on_keepRadioButton_clicked(), on_updateRadioButton_clicked(), setEnableRepairSection(), WarningMultizoneDialog(), and ~WarningMultizoneDialog().
The documentation for this class was generated from the following files:
Forms/WarningDialog/warningmultizonedialog.h
Forms/WarningDialog/warningmultizonedialog.cpp