BBIPED Platform: SolverHelper Class Reference
SolverHelper Class Reference
#include <solverhelper.h>
Public Member Functions
SolverHelper ()
void createConfigurationTemplateByUser (SolverConfigManager *_solverConfigManager)
void editConfigurationTemplateByUser (QMainWindow *_mainWindow, SolverConfigManager *_solverConfigManager)
void launchFileComparisonDialog (bool _isMultizoneProject, MultizoneProjectData _multizoneProjectData, ProjectData _projectData, SolverConfigManager _solverManager, ProjectDetails _projectDetailsData, QList< VirtualMrfVO > _userVirtualMRFDataList)
This function launchs the dialog for the comparison dialog.
void loadConfigurationTemplateByUser (QMainWindow *_mainWindow, SolverConfigManager *_solverConfigManager, UserPreferencesData *_userPreferencesData)
Detailed Description
Definition at line 13 of file solverhelper.h.
Constructor & Destructor Documentation
SolverHelper::SolverHelper ()
Definition at line 32 of file solverhelper.cpp.
 {
 }
Member Function Documentation
void SolverHelper::createConfigurationTemplateByUser (SolverConfigManager * _solverConfigManager)
Parameters
_solverConfigManager
Definition at line 43 of file solverhelper.cpp.
References TemplateDialog::setSolverConfigManager().
Referenced by MainWindow::on_actionCreate_Configuration_Template_triggered().
 {
     TemplateDialog _templateDialog;
     _templateDialog.setSolverConfigManager(_solverConfigManager);
     _templateDialog.exec();
 }
void SolverHelper::editConfigurationTemplateByUser (QMainWindow * _mainWindow, SolverConfigManager * _solverConfigManager)
Parameters
_mainWindow
_solverConfigManager
Definition at line 56 of file solverhelper.cpp.
References SolverConfigManager::loadPersonalizedTemplate(), TemplateDialog::loadTemplate(), and TemplateDialog::setSolverConfigManager().
Referenced by MainWindow::on_actionEdit_Configuration_Template_triggered().
 {
     QString _workingPath = QDir(QCoreApplication::applicationDirPath()).filePath(".templates");
     if (!QDir(_workingPath).exists())
         QDir(QCoreApplication::applicationDirPath()).mkdir(".templates");
     QString _binPath = QFileDialog::getOpenFileName(_mainWindow, "Select the configuration template to Edit",
                                                             _workingPath,
                                                             "Template Config File Type(*.xml)");
     if (_binPath.isEmpty())
         return;
     TemplateDialog _templateDialog;
     _solverConfigManager->loadPersonalizedTemplate(_binPath);
     _templateDialog.setSolverConfigManager(_solverConfigManager);
     _templateDialog.loadTemplate();
     _templateDialog.exec();
 }
void SolverHelper::launchFileComparisonDialog (bool _isMultizoneProject, MultizoneProjectData _multizoneProjectData, ProjectData _projectData, SolverConfigManager _solverManager, ProjectDetails _projectDetailsData, QList< VirtualMrfVO > _userVirtualMRFDataList)
This function launchs the dialog for the comparison dialog.
Parameters
_isMultizoneProject
_multizoneProjectData
_projectData
_solverManager
_projectDetailsData
_userVirtualMRFDataList
Definition at line 118 of file solverhelper.cpp.
References SolverConfigManager::getAllSectionMenuList(), MultizoneProjectData::getListConfigFiles(), ProjectData::getProjectFileName(), FileComparisonDialog::setFilesToCompare(), FileComparisonDialog::setProjectDetails(), FileComparisonDialog::setSectionMenuList(), and FileComparisonDialog::setVirtualMRFData().
Referenced by MainWindow::on_actionCompare_Configuration_Files_triggered(), and MainWindow::on_actionSynchronise_all_files_triggered().
 {
     FileComparisonDialog _fileComparison;
     QStringList _listFiles;
     if (_isMultizoneProject)
         _listFiles = _multizoneProjectData.getListConfigFiles();
     else
      _listFiles.append(_projectData.getProjectFileName());
     _fileComparison.setFilesToCompare(_listFiles);
     _fileComparison.setSectionMenuList(_solverManager.getAllSectionMenuList());
     _fileComparison.setProjectDetails(_projectDetailsData);
     _fileComparison.setVirtualMRFData(_userVirtualMRFDataList);
     _fileComparison.exec();
 }
void SolverHelper::loadConfigurationTemplateByUser (QMainWindow * _mainWindow, SolverConfigManager * _solverConfigManager, UserPreferencesData * _userPreferencesData)
Parameters
_mainWindow
_solverConfigManager
_userPreferencesData
Definition at line 84 of file solverhelper.cpp.
References SolverConfigManager::loadPersonalizedTemplate(), and UserPreferencesData::setTemplateConfigPath().
Referenced by MainWindow::on_actionLoad_Configuration_Template_triggered().
 {
     QString _workingPath = QDir(QCoreApplication::applicationDirPath()).filePath(".templates");
     if (!QDir(_workingPath).exists())
         QDir(QCoreApplication::applicationDirPath()).mkdir(".templates");
     QString _binPath = QFileDialog::getOpenFileName(_mainWindow, "Select the configuration template to Load",
                                                             _workingPath,
                                                             "Template Config File Type(*.xml)");
     if (_binPath.isEmpty())
         return;
     _userPreferencesData->setTemplateConfigPath(_binPath);
     _solverConfigManager->loadPersonalizedTemplate(_binPath);
 }
The documentation for this class was generated from the following files:
WindowHelper/Menu/MenuHelpers/solverhelper.h
WindowHelper/Menu/MenuHelpers/solverhelper.cpp