BBIPED Platform: HelpDialog Class Reference
HelpDialog Class Reference
#include <helpdialog.h>
Public Member Functions
HelpDialog (QWidget *parent=0)
Constructor.
~HelpDialog ()
Destructor.
void loadHelpText ()
Load the help text.
void setHelpText (QString _text)
Set the help text.
Private Slots
void on_okHelpDialog_clicked ()
Action on click.
Private Attributes
QString _helpText
Ui::HelpDialog * ui
Detailed Description
Definition at line 12 of file helpdialog.h.
Constructor & Destructor Documentation
HelpDialog::HelpDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
parent
Definition at line 31 of file helpdialog.cpp.
References ui.
                                       :
     QDialog(parent),
     ui(new Ui::HelpDialog)
 {
         ui->setupUi(this);
 }
HelpDialog::~HelpDialog ()
Destructor.
Definition at line 47 of file helpdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void HelpDialog::loadHelpText ()
Load the help text.
Definition at line 76 of file helpdialog.cpp.
References _helpText, and ui.
Referenced by VirtualRotatingDialog::buildAssociatedHelp(), VirtualCurveDialog::generateHelpDialog(), TemplateDialog::loadHelp(), SpecificBoundaryVariableDialog::on_boundaryHelpButton_clicked(), MeshDialog::on_meshTableWidget_cellClicked(), SolverBasicDialog::on_solverVariablesTable_cellClicked(), and SummaryDialog::on_summaryTable_cellClicked().
 {
    // ui->helpAreaText->setText(_helpText);
     ui->helpAreaText->insertHtml(_helpText);
 }
void HelpDialog::on_okHelpDialog_clicked () private slot
Action on click.
Definition at line 90 of file helpdialog.cpp.
 {
     this->close();
 }
void HelpDialog::setHelpText (QString _text)
Set the help text.
Parameters
_text
_text
Definition at line 63 of file helpdialog.cpp.
References _helpText.
Referenced by VirtualRotatingDialog::buildAssociatedHelp(), VirtualCurveDialog::generateHelpDialog(), TemplateDialog::loadHelp(), SpecificBoundaryVariableDialog::on_boundaryHelpButton_clicked(), SalomeTemplateDialog::on_helpButton_clicked(), MeshDialog::on_meshTableWidget_cellClicked(), SolverBasicDialog::on_solverVariablesTable_cellClicked(), and SummaryDialog::on_summaryTable_cellClicked().
 {
     _helpText = _text;
 }
Member Data Documentation
QString HelpDialog::_helpText private
Definition at line 29 of file helpdialog.h.
Referenced by loadHelpText(), and setHelpText().
Ui::HelpDialog* HelpDialog::ui private
Definition at line 28 of file helpdialog.h.
Referenced by HelpDialog(), loadHelpText(), and ~HelpDialog().
The documentation for this class was generated from the following files:
Forms/helpdialog.h
Forms/helpdialog.cpp