BBIPED Platform: SalomePythonFileUtil Class Reference
SalomePythonFileUtil Class Reference
#include <salomepythonfileutil.h>
Public Member Functions
SalomePythonFileUtil ()
Constructor.
void buildPythonFile ()
This funciton buillds the python file.
void buildPythonFileForOptimization (int _iterations)
This funciton buillds the python file for the Optimization menu.
void setFileName (QString _name)
Destructor.
void setPathProject (QString _path)
This function stores the project path.
void setTemplateData (SalomeTemplateData _data)
This function stores the template data of the Salome Template.
void setTemplateDataList (QList< SalomeTemplateData > _data)
This function stores the list of possible SalomeTemplateDAta.
void setVariableList (QList< QList< SalomeVariableData > > _variablesList)
This funciton sotres the SalomeVariableData list associated to each template.
Private Member Functions
void buildHeader (QTextStream *_textWriter)
This funciton buillds the python file header.
void buildMain (QTextStream *_textWriter)
This funciton buillds the python file Main Body.
void buildMainForOptimization (QTextStream *_textWriter, int _iterations)
This funciton buillds the python file Main Body for Optimization.
QString getVariables (int _pos)
This funciton buillds get the variable Name in a specific position.
QString getVariablesFromTemplate ()
This function gets the variables names in a QString format from a specifi template (variable name + current value)
Private Attributes
QString _fileName
QString _pathProject
SalomeTemplateData _templateData
QList< SalomeTemplateData > _templateDataList
QList< QList
< SalomeVariableData > > _variablesList
Detailed Description
Definition at line 11 of file salomepythonfileutil.h.
Constructor & Destructor Documentation
SalomePythonFileUtil::SalomePythonFileUtil ()
Constructor.
Definition at line 26 of file salomepythonfileutil.cpp.
 {
 }
Member Function Documentation
void SalomePythonFileUtil::buildHeader (QTextStream * _textWriter) private
This funciton buillds the python file header.
Parameters
_textWriter
Definition at line 135 of file salomepythonfileutil.cpp.
Referenced by buildPythonFile(), and buildPythonFileForOptimization().
 {
     QString _BBIPED_HOME = QCoreApplication::applicationDirPath();
     //----------------------------------------------
     // FOR TESTING REMOVE FOR RELEASE
     //_BBIPED_HOME = _BBIPED_HOME + "/debug";
     //----------------------------------------------
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "# HEADER  " << endl;
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "import os" << endl;
     (* _textWriter) << "import sys" << endl;
     (* _textWriter) << "_AutomatizationPath=\""+_BBIPED_HOME+"/.tools/Automatization/\"" << endl;
     (* _textWriter) << "sys.path.append(_AutomatizationPath)"<< endl;
     (* _textWriter) << "import JobManager" << endl;
     (* _textWriter) << "CurrentPath = os.getcwd()" << endl;
 }
void SalomePythonFileUtil::buildMain (QTextStream * _textWriter) private
This funciton buillds the python file Main Body.
Parameters
_textWriter
Definition at line 162 of file salomepythonfileutil.cpp.
References _templateData, SalomeTemplateData::getTemplateFileName(), and getVariablesFromTemplate().
Referenced by buildPythonFile().
 {
     QString _templateFullName = _templateData.getTemplateFileName();
     _templateFullName.remove("_Calculations");
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "# MAIN BODY  " << endl;
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "Geometry_Template = \""+_templateFullName+"\""<< endl;
     (* _textWriter) << "JobManager.Compute_Mesh(CurrentPath,Geometry_Template"+getVariablesFromTemplate()+")"<< endl;
 }
void SalomePythonFileUtil::buildMainForOptimization (QTextStream * _textWriter, int _iterations) private
This funciton buillds the python file Main Body for Optimization.
Parameters
_textWriter
_iterations
Definition at line 181 of file salomepythonfileutil.cpp.
References _pathProject, _templateData, SalomeTemplateData::getTemplateFileName(), and getVariables().
Referenced by buildPythonFileForOptimization().
 {
     QString _templateFullName = _templateData.getTemplateFileName();
     _templateFullName.remove("_Calculations");
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "# MAIN BODY  " << endl;
     (* _textWriter) << "# ------------------------------------------------------------" << endl;
     (* _textWriter) << "Geometry_Template = \""+_templateFullName+"\""<< endl;
     (* _textWriter) << "def CreateDirectory(WritePath):"<< endl;
     (* _textWriter) << " if not os.path.exists(WritePath):"<< endl;
     (* _textWriter) << "  os.makedirs(WritePath)"<< endl;
     QString _basePath = QDir(_pathProject).filePath("Python");
     for (int i = 0; i< _iterations; i++)
     {
         QString _newFolder;
         _newFolder = QDir(_basePath).filePath("Iter_"+QString::number(i));
         (* _textWriter) << "CreateDirectory(\""+_newFolder+"\")"<< endl;
         (* _textWriter) << "WritePath =\""+_newFolder +"\""<< endl;
         (* _textWriter) << "JobManager.Compute_Mesh(WritePath,Geometry_Template"+getVariables(i)+")"<< endl;
     }
 }
void SalomePythonFileUtil::buildPythonFile ()
This funciton buillds the python file.
Definition at line 83 of file salomepythonfileutil.cpp.
References _fileName, _pathProject, buildHeader(), and buildMain().
Referenced by SalomeToolCreateMeshDialog::on_createMeshButton_clicked().
 {
     QString _pythonFilePath;
     QDir _phythonDir = QDir(_pathProject).filePath("Python");
     _pythonFilePath = _phythonDir.filePath(_fileName+".py");
     // Creating the folder structure
     if (!_phythonDir.exists())
         _phythonDir.mkpath(".");
     // Opening the file
     QFile * _file = new QFile(_pythonFilePath);
     _file->open(QIODevice::WriteOnly | QIODevice::Text);
     QTextStream  _textWriter(_file);
     buildHeader(&_textWriter);
     buildMain(&_textWriter);
     // Closing the file
     _file->close();
 }
void SalomePythonFileUtil::buildPythonFileForOptimization (int _iterations)
This funciton buillds the python file for the Optimization menu.
Parameters
_iterations
Definition at line 108 of file salomepythonfileutil.cpp.
References _fileName, _pathProject, buildHeader(), and buildMainForOptimization().
Referenced by SalomeOptimizationDialog::on_pushButton_clicked().
 {
     QString _pythonFilePath;
     QDir _phythonDir = QDir(_pathProject).filePath("Python");
     _pythonFilePath = _phythonDir.filePath(_fileName+"_opt.py");
     // Creating the folder structure
     if (!_phythonDir.exists())
         _phythonDir.mkpath(".");
     // Opening the file
     QFile * _file = new QFile(_pythonFilePath);
     _file->open(QIODevice::WriteOnly | QIODevice::Text);
     QTextStream  _textWriter(_file);
     buildHeader(&_textWriter);
     buildMainForOptimization(&_textWriter,_iterations);
     // Closing the file
     _file->close();
 }
QString SalomePythonFileUtil::getVariables (int _pos) private
This funciton buillds get the variable Name in a specific position.
Parameters
_pos
Returns
QString
Definition at line 213 of file salomepythonfileutil.cpp.
References _variablesList, SalomeVariableData::getCurrentValue(), and SalomeVariableData::getFileName().
Referenced by buildMainForOptimization().
 {
     QString _variables = "";
     QList<SalomeVariableData> _varList;
     if (_pos < _variablesList.size())
         _varList = _variablesList.at(_pos);
     for (int i = 0; i < _varList.size();i++)
     {
         SalomeVariableData _var = _varList.at(i);
         _variables = _variables + ",\""+_var.getFileName()+"\","+_var.getCurrentValue();
     }
     return _variables;
 }
QString SalomePythonFileUtil::getVariablesFromTemplate () private
This function gets the variables names in a QString format from a specifi template (variable name + current value)
Returns
QString
Definition at line 240 of file salomepythonfileutil.cpp.
References _templateData, SalomeVariableData::getCurrentValue(), SalomeVariableData::getDefaultValue(), SalomeVariableData::getFileName(), SalomeTemplateData::getVariableList(), and StrEqual.
Referenced by buildMain().
 {
     QString _variables = "";
     QList<SalomeVariableData> _varList = _templateData.getVariableList();
     for (int i = 0; i < _varList.size();i++)
     {
         SalomeVariableData _var = _varList.at(i);
         if (QString::compare(_var.getDefaultValue(),_var.getCurrentValue()) != StrEqual)
             _variables = _variables + ",\""+_var.getFileName()+"\","+_var.getCurrentValue();
     }
     return _variables;
 }
void SalomePythonFileUtil::setFileName (QString _name)
Destructor.
Parameters
_name
Definition at line 35 of file salomepythonfileutil.cpp.
References _fileName.
Referenced by SalomeToolCreateMeshDialog::on_createMeshButton_clicked(), and SalomeOptimizationDialog::on_pushButton_clicked().
 {
     _fileName = _name;
 }
void SalomePythonFileUtil::setPathProject (QString _path)
This function stores the project path.
Parameters
_path
Definition at line 44 of file salomepythonfileutil.cpp.
References _pathProject.
Referenced by SalomeToolCreateMeshDialog::on_createMeshButton_clicked(), and SalomeOptimizationDialog::on_pushButton_clicked().
 {
     _pathProject = _path;
 }
void SalomePythonFileUtil::setTemplateData (SalomeTemplateData _data)
This function stores the template data of the Salome Template.
Parameters
_data
Definition at line 54 of file salomepythonfileutil.cpp.
References _templateData.
Referenced by SalomeToolCreateMeshDialog::on_createMeshButton_clicked(), and SalomeOptimizationDialog::on_pushButton_clicked().
 {
     _templateData = _data;
 }
void SalomePythonFileUtil::setTemplateDataList (QList< SalomeTemplateData > _data)
This function stores the list of possible SalomeTemplateDAta.
Parameters
_data
Definition at line 64 of file salomepythonfileutil.cpp.
References _templateDataList.
 {
     _templateDataList = _data;
 }
void SalomePythonFileUtil::setVariableList (QList< QList< SalomeVariableData > > _list)
This funciton sotres the SalomeVariableData list associated to each template.
Parameters
_list
Definition at line 74 of file salomepythonfileutil.cpp.
References _variablesList.
Referenced by SalomeOptimizationDialog::on_pushButton_clicked().
 {
     _variablesList = _list;
 }
Member Data Documentation
QString SalomePythonFileUtil::_fileName private
Definition at line 29 of file salomepythonfileutil.h.
Referenced by buildPythonFile(), buildPythonFileForOptimization(), and setFileName().
QString SalomePythonFileUtil::_pathProject private
Definition at line 30 of file salomepythonfileutil.h.
Referenced by buildMainForOptimization(), buildPythonFile(), buildPythonFileForOptimization(), and setPathProject().
SalomeTemplateData SalomePythonFileUtil::_templateData private
Definition at line 31 of file salomepythonfileutil.h.
Referenced by buildMain(), buildMainForOptimization(), getVariablesFromTemplate(), and setTemplateData().
QList<SalomeTemplateData> SalomePythonFileUtil::_templateDataList private
Definition at line 32 of file salomepythonfileutil.h.
Referenced by setTemplateDataList().
QList< QList<SalomeVariableData> > SalomePythonFileUtil::_variablesList private
Definition at line 33 of file salomepythonfileutil.h.
Referenced by getVariables(), and setVariableList().
The documentation for this class was generated from the following files:
Data/SalomeTemplateData/salomepythonfileutil.h
Data/SalomeTemplateData/salomepythonfileutil.cpp