BBIPED Platform: MultizoneProjectDialog Class Reference
MultizoneProjectDialog Class Reference
#include <multizoneprojectdialog.h>
Public Member Functions
MultizoneProjectDialog (QWidget *parent=0)
Constructor.
~MultizoneProjectDialog ()
Desctructor.
MultizoneProjectData getMultizoneProjectData ()
Get the associated information of the multizone project.
bool isMultizoneProjectCreated ()
Returns if the multizone project is created or not.
void setProjectDetails (ProjectDetails _projectDetails)
Set project details.
Private Slots
void on_buttonBox_rejected ()
Action when the user rejects the changes.
void on_configTable_cellClicked (int row, int column)
Action that controls what to do depending on the click (add new, import file, delete file)
void on_multizoneNoSpinBox_valueChanged (const QString &arg1)
Function that controls the Spin Box, increasing create rows, decreasing remove rows.
void on_projectSelectionToolButton_clicked ()
Action that controls the tool button for creation of the project.
Private Member Functions
void accept ()
bool buildFilesInProject ()
Function that actually build the project files into the correspondent project folder.
bool checkConsistency (QString _configFilePath, QString _meshFilePath, SolverConfigManager _solverManager)
This fucntion checks if there are differences among the boundary names read in the mesh file and those read from the configuration file. If there are differences a warning dialog is launched.
void createConfigurationRow (QString _content, int _idRow, int _idZone)
Create the cells of the row according the content and the zone (Configuration file)
void createMeshFileRow (QString _content, int _idRow, int _idZone)
Create the cells of the row according the content and the zone (Mesh file)
void createRowInConfigFileTable (int _noFiles)
Create so many rows as configurationf iles in the table.
void decreaseZoneNumber ()
Action that controls the decreasing number in the spinbox.
void deleteFile (int _row)
Function that launches to delete a file (when a config. file is deleted, the correspondent mesh file is also deleted.
void enableMultizoneParameters ()
Function that enables the different parameters for the multizone.
bool isMeshFileNameValid (QString _file)
Function that checks if the mesh file name exists or not.
void launchCreateNewFile (int _row)
Function that launches to create a new file.
void launchImportNewFile (int _row)
Function that launches to import a file.
void updateZoneNumberInCell ()
Update the number of zones in the correspondent cell.
Private Attributes
QStringList _importedFilesList
bool _isMultizoneProjectCreated
MultizoneProjectData _multizoneProjectData
QStringList _newFilesList
int _noZones
ProjectDetails _projectDetailsData
QString _projectPath
QList< VirtualMrfVO > _virtualMRFData
Ui::MultizoneProjectDialog * ui
Detailed Description
Definition at line 16 of file multizoneprojectdialog.h.
Constructor & Destructor Documentation
MultizoneProjectDialog::MultizoneProjectDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 44 of file multizoneprojectdialog.cpp.
References _isMultizoneProjectCreated, _noZones, _projectPath, and ui.
                                                               :
     QDialog(parent),
     ui(new Ui::MultizoneProjectDialog)
 {
     ui->setupUi(this);
     _projectPath = "";
     _noZones = 0;
     _isMultizoneProjectCreated = false;
 }
MultizoneProjectDialog::~MultizoneProjectDialog ()
Desctructor.
Definition at line 59 of file multizoneprojectdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void MultizoneProjectDialog::accept () private
Definition at line 360 of file multizoneprojectdialog.cpp.
References _isMultizoneProjectCreated, _multizoneProjectData, _projectDetailsData, buildFilesInProject(), MultizoneProjectData::isEmpty(), and UtilFiles::updateMultizoneProjectDataToFile().
 {
     if (!_multizoneProjectData.isEmpty())
      {
          UtilFiles _fileHelper;
          bool _buildSuccess = false;
          _buildSuccess = buildFilesInProject();
          if (_buildSuccess)
          {
              _fileHelper.updateMultizoneProjectDataToFile(_multizoneProjectData,_projectDetailsData);
              _isMultizoneProjectCreated = true;
              close();
          }
      }
 }
bool MultizoneProjectDialog::buildFilesInProject () private
Function that actually build the project files into the correspondent project folder.
Returns
bool
Definition at line 177 of file multizoneprojectdialog.cpp.
References _importedFilesList, _multizoneProjectData, _newFilesList, _projectDetailsData, _projectPath, _virtualMRFData, checkConsistency(), ColumnFileName, UtilFiles::importFile(), SolverConfigManager::initializeManager(), SolverConfigManager::isInitialized(), isMeshFileNameValid(), SolverConfigManager::saveConfigFile(), MultizoneProjectData::setListConfigFiles(), MultizoneProjectData::setListMeshFiles(), ShowMessageHelper::showWarningMessage(), TOOL4, and ui.
Referenced by accept().
 {
     UtilFiles _fileHelper;
     int _rowConfigFile;
     int _rowMeshFile;
     bool _buildSuccess = true;
     QString _fileConfigName;
     QString _fileMeshName;
     SolverConfigManager _solverManager;
     QHash<QString,QString> _userVal;
     QStringList _listConfigFiles;
     QStringList _listMeshFiles;
     if (!_solverManager.isInitialized())
                _solverManager.initializeManager();
     int _lastRow = ui->configTable->rowCount();
     int _processedRow = 0;
     while(_processedRow < _lastRow )
     {
         _rowConfigFile = _processedRow;
         _rowMeshFile = _processedRow+1;
         _fileConfigName = ui->configTable->item(_rowConfigFile, ColumnFileName)->text();
         _fileMeshName = ui->configTable->item(_rowMeshFile, ColumnFileName)->text();
         if (!isMeshFileNameValid(_fileMeshName))
         {
            ShowMessageHelper _messageHelper;
            bool _result =  _messageHelper.showWarningMessage("Mesh File Name not Valid", "Please, choose a valid mesh file to continue");
             return (!_buildSuccess);
         }
         else{
             // Import Mesh File
             QString _newMeshPath = _fileHelper.importFile(_projectPath,_fileMeshName, TOOL4);
             _listMeshFiles.append(_newMeshPath);
             _userVal.insert("MESH_FILENAME",_newMeshPath);
             // Process the Config file
              QString _finalPath = QDir(_projectPath).filePath(TOOL4);
             if (_newFilesList.contains(_fileConfigName))
             {
                 // Saving with all the values by default and the mesh file name associated to it
                 _solverManager.saveConfigFile(QDir(_finalPath).filePath(_fileConfigName),_userVal, _projectDetailsData,_virtualMRFData);
                  _listConfigFiles.append(QDir(_finalPath).filePath(_fileConfigName));
             }else
             {
                 QString _newPath;
                 if (_importedFilesList.contains(_fileConfigName))
                 {
                    _newPath = _fileHelper.importFile(_projectPath,_fileConfigName, TOOL4);
                    bool _canContinue = checkConsistency(_newPath, _newMeshPath, _solverManager);
                    if (!_canContinue)
                    {
                        _buildSuccess = false;
                        return _buildSuccess;
                    }
                 }else // The user has not done anything --> Create a new one with default name
                 {
                     _newPath = QDir(_finalPath).filePath("default_config_"+QString::number(_rowConfigFile)+".cfg");
                     _solverManager.saveConfigFile(_newPath,_userVal,_projectDetailsData,_virtualMRFData);
                 }
                  _listConfigFiles.append(_newPath);
             }
             // Update the counter
             _processedRow = _processedRow+2;
             _userVal.clear();
         }
         _multizoneProjectData.setListConfigFiles(_listConfigFiles);
         _multizoneProjectData.setListMeshFiles(_listMeshFiles);
         }
     return _buildSuccess;
 }
bool MultizoneProjectDialog::checkConsistency (QString _configFilePath, QString _meshFilePath, SolverConfigManager _solverManager) private
This fucntion checks if there are differences among the boundary names read in the mesh file and those read from the configuration file. If there are differences a warning dialog is launched.
Parameters
_configFilePath
_meshFilePath
_solverManager
Definition at line 491 of file multizoneprojectdialog.cpp.
References _projectDetailsData, _virtualMRFData, SolverMarkerMenuHelper::checkMarkerMeshVariables(), WarningMultizoneDialog::getConfigValues(), ParserFiles::getParsedValues(), ConfigurationFileParser::getParsedVirtualMRFData(), WarningMultizoneDialog::initializeFileNames(), WarningMultizoneDialog::isNeedToUpdate(), MeshFileParser::parseFileProcess(), ConfigurationFileParser::parseFileProcess(), SolverConfigManager::saveConfigFile(), WarningMultizoneDialog::setConfigValues(), ParserFiles::setFilePath(), WarningMultizoneDialog::setMeshValueNames(), and WarningMultizoneDialog::userAcceptChanges().
Referenced by buildFilesInProject().
 {
     bool _isConsistent = true;
     // Load Config File
     ConfigurationFileParser _configParser;
    _configParser.setFilePath(_configFilePath);
     _configParser.parseFileProcess();
     QHash<QString,QString>  _userConfigVal = _configParser.getParsedValues();
     _virtualMRFData = _configParser.getParsedVirtualMRFData();
     // Load Mesh File Values
    MeshFileParser _meshParser;
     _meshParser.setFilePath(_meshFilePath);
     _meshParser.parseFileProcess();
     QHash<QString,QString> _meshBoundaryVal = _meshParser.getParsedValues();
     // Check if there are differences
     SolverMarkerMenuHelper _markerHelper;
     if ((!_userConfigVal.isEmpty()) && (! _meshBoundaryVal.isEmpty()) )
     {
         bool _areEqual = _markerHelper.checkMarkerMeshVariables(_userConfigVal,_meshBoundaryVal);
         if (!_areEqual)
         {
             WarningMultizoneDialog  _warningDialog;
             _warningDialog.initializeFileNames(_configFilePath,_meshFilePath);
             _warningDialog.setConfigValues(_userConfigVal);
             _warningDialog.setMeshValueNames(_meshBoundaryVal);
             _warningDialog.exec();
             if (!_warningDialog.userAcceptChanges())
                 _isConsistent = false;
             else{
                 if ( (_warningDialog.userAcceptChanges()) && (_warningDialog.isNeedToUpdate()) )
                 {
                      _userConfigVal = _warningDialog.getConfigValues();
                      _userConfigVal.insert("MESH_FILENAME",_meshFilePath);
                 }
                 // Saving the file
                 _solverManager.saveConfigFile(_configFilePath,_userConfigVal,_projectDetailsData,_virtualMRFData);
             }
         }
     }
     return _isConsistent;
 }
void MultizoneProjectDialog::createConfigurationRow (QString _content, int _idRow, int _idZone) private
Create the cells of the row according the content and the zone (Configuration file)
Parameters
_content
_idRow
_idZone
Definition at line 87 of file multizoneprojectdialog.cpp.
References QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnAddFile, ColumnDeleteFile, ColumnFileName, ColumnImportFile, ColumnZoneNo, IconAdd, IconDelete, IconImport, and ui.
Referenced by on_multizoneNoSpinBox_valueChanged().
 {
     QtableUtil _tableHelper;
     ui->configTable->insertRow(_idRow);
     ui->configTable->setItem(_idRow,ColumnZoneNo,_tableHelper.addNonEditableText(QString::number(_idZone)) );
     ui->configTable->setItem(_idRow,ColumnFileName,_tableHelper.addNonEditableText(_content) );
     ui->configTable->setCellWidget(_idRow,ColumnAddFile,_tableHelper.addIcon(IconAdd) );
     ui->configTable->setCellWidget(_idRow,ColumnImportFile,_tableHelper.addIcon(IconImport) );
     ui->configTable->setCellWidget(_idRow,ColumnDeleteFile,_tableHelper.addIcon(IconDelete) );
 }
void MultizoneProjectDialog::createMeshFileRow (QString _content, int _idRow, int _idZone) private
Create the cells of the row according the content and the zone (Mesh file)
Parameters
_content
_idRow
_idZone
Definition at line 105 of file multizoneprojectdialog.cpp.
References QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnDeleteFile, ColumnFileName, ColumnImportFile, ColumnZoneNo, IconImport, and ui.
Referenced by on_multizoneNoSpinBox_valueChanged().
 {
     QtableUtil _tableHelper;
     ui->configTable->insertRow(_idRow);
     ui->configTable->setItem(_idRow,ColumnZoneNo,_tableHelper.addNonEditableText(""));
     ui->configTable->setItem(_idRow,ColumnFileName,_tableHelper.addNonEditableText(_content) );
     ui->configTable->setCellWidget(_idRow,ColumnImportFile,_tableHelper.addIcon(IconImport) );
     ui->configTable->item(_idRow-1,ColumnZoneNo)->setTextAlignment(Qt::AlignCenter);
     ui->configTable->setSpan(_idRow-1,ColumnZoneNo,2,1);
     ui->configTable->setSpan(_idRow-1,ColumnDeleteFile,2,1);
 }
void MultizoneProjectDialog::createRowInConfigFileTable (int _noFiles) private
Create so many rows as configurationf iles in the table.
Parameters
_noFiles
Definition at line 71 of file multizoneprojectdialog.cpp.
References ui.
 {
     int _totalRows = ui->configTable->rowCount();
     for (int i = 0; i < _noFiles;i++)
         ui->configTable->insertRow(_totalRows+i);
 }
void MultizoneProjectDialog::decreaseZoneNumber () private
Action that controls the decreasing number in the spinbox.
Definition at line 457 of file multizoneprojectdialog.cpp.
References ui.
Referenced by deleteFile().
 {
     int _cvalue = ui->multizoneNoSpinBox->value();
     ui->multizoneNoSpinBox->setValue(_cvalue-1);
 }
void MultizoneProjectDialog::deleteFile (int _row) private
Function that launches to delete a file (when a config. file is deleted, the correspondent mesh file is also deleted.
Parameters
_row
Definition at line 429 of file multizoneprojectdialog.cpp.
References _importedFilesList, ColumnFileName, decreaseZoneNumber(), ui, and updateZoneNumberInCell().
Referenced by on_configTable_cellClicked().
 {
     int _lastRow = ui->configTable->rowCount();
     if (_row < _lastRow)
     {
         QString _meshFileName = ui->configTable->item(_row+1,ColumnFileName)->text();
         if (!_meshFileName.isEmpty())
             if (_importedFilesList.contains(_meshFileName))
                 _importedFilesList.removeOne(_meshFileName);
         QString _configFileName = ui->configTable->item(_row,ColumnFileName)->text();
         if (!_configFileName.isEmpty())
             if (_importedFilesList.contains(_configFileName))
                 _importedFilesList.removeOne(_configFileName);
         ui->configTable->removeRow(_row+1);
         ui->configTable->removeRow(_row);
         decreaseZoneNumber();
         updateZoneNumberInCell();
     }
 }
void MultizoneProjectDialog::enableMultizoneParameters () private
Function that enables the different parameters for the multizone.
Definition at line 383 of file multizoneprojectdialog.cpp.
References ui.
Referenced by on_projectSelectionToolButton_clicked().
 {
     ui->MainTitle->setEnabled(true);
     ui->multizoneNoLabel->setEnabled(true);
     ui->multizoneNoSpinBox->setEnabled(true);
     ui->configFilesTitle->setEnabled(true);
     ui->configTable->setEnabled(true);
 }
MultizoneProjectData MultizoneProjectDialog::getMultizoneProjectData ()
Get the associated information of the multizone project.
Returns
MultizoneProjectData
Definition at line 553 of file multizoneprojectdialog.cpp.
References _multizoneProjectData.
Referenced by MultizoneManager::launchMultizoneDialog().
 {
     return _multizoneProjectData;
 }
bool MultizoneProjectDialog::isMeshFileNameValid (QString _file) private
Function that checks if the mesh file name exists or not.
Parameters
_file
Returns
bool
Definition at line 473 of file multizoneprojectdialog.cpp.
Referenced by buildFilesInProject().
 {
     QFile _fileName(_file);
     if (_fileName.exists())
         return true;
     else
         return false;
 }
bool MultizoneProjectDialog::isMultizoneProjectCreated ()
Returns if the multizone project is created or not.
Returns
bool
Definition at line 543 of file multizoneprojectdialog.cpp.
References _isMultizoneProjectCreated.
Referenced by MultizoneManager::launchMultizoneDialog().
 {
     return _isMultizoneProjectCreated;
 }
void MultizoneProjectDialog::launchCreateNewFile (int _row) private
Function that launches to create a new file.
Parameters
_row
Definition at line 128 of file multizoneprojectdialog.cpp.
References _multizoneProjectData, _newFilesList, ColumnFileName, DEFAULT_CONFIG_FILE_NAME_SUFFIX, MultizoneProjectData::getProjectPath(), TOOL4, and ui.
Referenced by on_configTable_cellClicked().
 {
     QString _newFile = QFileDialog::getSaveFileName(this, tr("Create Configuration File"),
                                QDir(_multizoneProjectData.getProjectPath()).filePath(TOOL4),
                                tr("Solver Configuration File (*.cfg)"));
     if (_newFile.isNull())
         return;
     QFileInfo _fileInfo = QFileInfo(_newFile);
     QString _fileName = _fileInfo.baseName() + DEFAULT_CONFIG_FILE_NAME_SUFFIX;
     ui->configTable->item(_row, ColumnFileName)->setText(_fileName);
     _newFilesList.append(_fileName);
 }
void MultizoneProjectDialog::launchImportNewFile (int _row) private
Function that launches to import a file.
Parameters
_row
Definition at line 147 of file multizoneprojectdialog.cpp.
References _importedFilesList, _multizoneProjectData, ColumnFileName, MultizoneProjectData::getProjectPath(), TOOL4, and ui.
Referenced by on_configTable_cellClicked().
 {
     QString _importedFile;
     bool _isConfigFile = false;
     if (_row%2 == 0)
     {
          _importedFile = QFileDialog::getOpenFileName(this, tr("Import Existing Configuration File"),
                                QDir(_multizoneProjectData.getProjectPath()).filePath(TOOL4),
                                tr("Solver Configuration File (*.cfg)"));
         _isConfigFile = true;
     }
     else
     {
          _importedFile = QFileDialog::getOpenFileName(this, tr("Import Existing Mesh File"),
                                 QDir(_multizoneProjectData.getProjectPath()).filePath(TOOL4),
                                tr("Mesh File (*.su2)"));
         _isConfigFile = false;
     }
     if ( (_importedFile.isNull()) || (_importedFile.isEmpty()))
         return;
     ui->configTable->item(_row, ColumnFileName)->setText(_importedFile);
     _importedFilesList.append(_importedFile);
 }
void MultizoneProjectDialog::on_buttonBox_rejected () private slot
Action when the user rejects the changes.
Definition at line 348 of file multizoneprojectdialog.cpp.
References _isMultizoneProjectCreated.
 {
     _isMultizoneProjectCreated = false;
     close();
 }
void MultizoneProjectDialog::on_configTable_cellClicked (int row, int column) private slot
Action that controls what to do depending on the click (add new, import file, delete file)
Parameters
row
column
Definition at line 327 of file multizoneprojectdialog.cpp.
References ColumnAddFile, ColumnDeleteFile, ColumnImportFile, deleteFile(), launchCreateNewFile(), and launchImportNewFile().
 {
     switch(column)
     {
     case ColumnAddFile:
         launchCreateNewFile(row);
         break;
     case ColumnImportFile:
         launchImportNewFile(row);
         break;
     case ColumnDeleteFile:
         deleteFile(row);
         break;
     }
 }
void MultizoneProjectDialog::on_multizoneNoSpinBox_valueChanged (const QString & arg1) private slot
Function that controls the Spin Box, increasing create rows, decreasing remove rows.
Parameters
arg1
Definition at line 262 of file multizoneprojectdialog.cpp.
References createConfigurationRow(), createMeshFileRow(), DEFAULT_CONFIG_FILE_NAME_PREFIX, DEFAULT_CONFIG_FILE_NAME_SUFFIX, DEFAULT_MESH_FILE_NAME_PREFIX, DEFAULT_MESH_FILE_NAME_SUFFIX, and ui.
 {
     int _totalRows = ui->configTable->rowCount();
     int _newZoneNo = arg1.toInt();
     int _cZoneNo = _totalRows/2;
     if (_newZoneNo > _cZoneNo) // We need to add new rows
     {
         int _noNewRows = _newZoneNo - _cZoneNo;
         int _rowPos = _totalRows;
         for (int i = 0;i < _noNewRows;i++)
         {
             QString _defaultConfig = DEFAULT_CONFIG_FILE_NAME_PREFIX+QString::number(_cZoneNo+i)+DEFAULT_CONFIG_FILE_NAME_SUFFIX;
             QString _defaultMesh = DEFAULT_MESH_FILE_NAME_PREFIX+QString::number(_cZoneNo+i)+DEFAULT_MESH_FILE_NAME_SUFFIX;
             createConfigurationRow(_defaultConfig,_rowPos,_cZoneNo+i);
             createMeshFileRow( _defaultMesh, _rowPos+1,_cZoneNo+i);
             _rowPos = _rowPos+2;
         }
     }else{
         if (_newZoneNo < _cZoneNo) // We need to delete rows
         {
             int _noDeletedRows = ( _cZoneNo -_newZoneNo)*2;
             for (int i = 0; i <= _noDeletedRows;i++)
                   ui->configTable->removeRow(_totalRows - i);
             //updateZoneNumberInCell();
         }
     }
 }
void MultizoneProjectDialog::on_projectSelectionToolButton_clicked () private slot
Action that controls the tool button for creation of the project.
Definition at line 295 of file multizoneprojectdialog.cpp.
References _multizoneProjectData, _projectPath, UtilFiles::createMultizoneProjectStructure(), enableMultizoneParameters(), MultizoneProjectData::setProjectName(), MultizoneProjectData::setProjectPath(), ShowMessageHelper::showMessageWindow(), and ui.
 {
     _projectPath = QFileDialog::getSaveFileName(this, tr("Create Project File"),
                                QCoreApplication::applicationDirPath(),//QDir::currentPath(),
                                tr("Solver Project (*.prj)"));
     if (_projectPath.isNull())
         return;
     ui->projectLineEdit->setText(_projectPath);
     enableMultizoneParameters();
     // Creating the project structure
     UtilFiles _utilFiles;
     // Creating all the project structure
     bool _fileCreated = _utilFiles.createMultizoneProjectStructure(_projectPath); // TODO -- cambiar para incluir los tags the multizone
     if (!_fileCreated)
     {
         QString _title(tr("Error Creating the new project") );
         QString _message(tr("If this project already exists. Please, select a different name. Otherwise, check your writing rights in the folder"));
         ShowMessageHelper _showHelper;
         _showHelper.showMessageWindow(_title,_message,this);
         return;
     }
     _multizoneProjectData.setProjectPath(_projectPath);
     _multizoneProjectData.setProjectName(QFileInfo(_projectPath).baseName());
 }
void MultizoneProjectDialog::setProjectDetails (ProjectDetails _projectDetails)
Set project details.
Parameters
_projectDetails
Definition at line 563 of file multizoneprojectdialog.cpp.
References _projectDetailsData.
 {
     _projectDetailsData = _projectDetails;
 }
void MultizoneProjectDialog::updateZoneNumberInCell () private
Update the number of zones in the correspondent cell.
Definition at line 402 of file multizoneprojectdialog.cpp.
References ColumnZoneNo, and ui.
Referenced by deleteFile().
 {
     int _totalRows = ui->configTable->rowCount();
     for (int _idRow = 0; _idRow < _totalRows;_idRow++)
         if (_idRow%2 == 0)
         {
             QTableWidgetItem * _zoneItem = (QTableWidgetItem  * ) ui->configTable->item(_idRow,ColumnZoneNo);
             if (_zoneItem)
             {
                 int _cPos = _idRow/2;
                 _zoneItem->setText(QString::number(_cPos));
                 ui->configTable->setItem(_idRow,ColumnZoneNo,_zoneItem);
             }
         }
 }
Member Data Documentation
QStringList MultizoneProjectDialog::_importedFilesList private
Definition at line 39 of file multizoneprojectdialog.h.
Referenced by buildFilesInProject(), deleteFile(), and launchImportNewFile().
bool MultizoneProjectDialog::_isMultizoneProjectCreated private
Definition at line 41 of file multizoneprojectdialog.h.
Referenced by accept(), isMultizoneProjectCreated(), MultizoneProjectDialog(), and on_buttonBox_rejected().
MultizoneProjectData MultizoneProjectDialog::_multizoneProjectData private
Definition at line 42 of file multizoneprojectdialog.h.
Referenced by accept(), buildFilesInProject(), getMultizoneProjectData(), launchCreateNewFile(), launchImportNewFile(), and on_projectSelectionToolButton_clicked().
QStringList MultizoneProjectDialog::_newFilesList private
Definition at line 38 of file multizoneprojectdialog.h.
Referenced by buildFilesInProject(), and launchCreateNewFile().
int MultizoneProjectDialog::_noZones private
Definition at line 37 of file multizoneprojectdialog.h.
Referenced by MultizoneProjectDialog().
ProjectDetails MultizoneProjectDialog::_projectDetailsData private
Definition at line 43 of file multizoneprojectdialog.h.
Referenced by accept(), buildFilesInProject(), checkConsistency(), and setProjectDetails().
QString MultizoneProjectDialog::_projectPath private
Definition at line 36 of file multizoneprojectdialog.h.
Referenced by buildFilesInProject(), MultizoneProjectDialog(), and on_projectSelectionToolButton_clicked().
QList<VirtualMrfVO> MultizoneProjectDialog::_virtualMRFData private
Definition at line 44 of file multizoneprojectdialog.h.
Referenced by buildFilesInProject(), and checkConsistency().
Ui::MultizoneProjectDialog* MultizoneProjectDialog::ui private
Definition at line 35 of file multizoneprojectdialog.h.
Referenced by buildFilesInProject(), createConfigurationRow(), createMeshFileRow(), createRowInConfigFileTable(), decreaseZoneNumber(), deleteFile(), enableMultizoneParameters(), launchCreateNewFile(), launchImportNewFile(), MultizoneProjectDialog(), on_multizoneNoSpinBox_valueChanged(), on_projectSelectionToolButton_clicked(), updateZoneNumberInCell(), and ~MultizoneProjectDialog().
The documentation for this class was generated from the following files:
Forms/ProjectDialog/multizoneprojectdialog.h
Forms/ProjectDialog/multizoneprojectdialog.cpp