BBIPED Platform: UtilFiles Class Reference
UtilFiles Class Reference
#include <utilfiles.h>
Public Member Functions
UtilFiles ()
void copyAllFiles (QDir _oldPath, QDir _newPath, QStringList _listFiles)
Copy all the files from one project to other.
void copyAllToolData (ProjectData _oldProjectData, ProjectData _newProjectData)
Copy all the files from one project to other, regarding the content of the tool folders.
void copyAllToolData (MultizoneProjectData _oldProjectData, MultizoneProjectData _newProjectData)
void copyFileToNewName (QString _filetoCopy, QString _newName)
Create a copy of a file with a different name.
bool createLink (QString _filePath, ProjectData _projectVO, QString _toolFolder)
bool createMultizoneProjectFile (QString _baseFileName, QString _finalPath)
Create the multizone project file (.mprj) with the needed information. With the name and in the path passed as arguments. If everything is ok –> returns true, otherwise false.
bool createMultizoneProjectStructure (QString _projectFilePath)
Create the multizoen project Structure, file and paths in the corresponding path If everything goes Ok –> return true, otherwise –> False.
bool createProjectFile (QString _baseFileName, QString _finalPath)
Create the project file (.prj) with the needed information. With the name and in the path passed as arguments. If everything is ok –> returns true, otherwise false.
bool createProjectStructure (QString _projectFilePath)
Create the project Structure, file and paths in the corresponding path If everything goes Ok –> return true, otherwise –> False.
void createProjectSubfolders (QString _basePath)
Create the project subfolders according with the implemented TOOLs in the corresponding path.
QString getFinalPath ()
Gets the final Path of the whole project.
QString getSubfolderName (int _indexTool)
Get the correspondent QString name of the tools subfolders.
bool hasFileExtension (QString _path, QString _extension)
Checks if the file (absolute path + filename) contains the _extension, returning true, otherwise false.
QString importFile (QString _filePath, ProjectData _projectVO, QString _toolFolder)
Functionality to import a file and update the correspondent values in the project data and copying this file into the project folder.
QString importFile (QString _destinationPath, QString _originPath, QString _toolFolder)
Functionality to import a file.
MultizoneProjectData openMultizoneProjectStructure (QString _projectFilePath)
Obtains the data stored in the multizone file project (.mprj) returning the data into the Multizone Project data object.
ProjectDetails openProjectDetails (QString _projectFilePath)
ProjectData openProjectStructure (QString _projectFilePath)
Obtains the data stored in the file project (.prj) returning the data into the Project data object.
void updateMultizoneProjectDataToFile (MultizoneProjectData _multizoneProjectDataToSave, ProjectDetails _projectDetails)
Update the multizone project Data object values into the correspondent file and save it to disk.
MultizoneProjectData updateMultizoneToolPaths (MultizoneProjectData _oldMultizoneProjectData, MultizoneProjectData _newMultizoneProjectData)
Update teh Multizone Tool paths according with the new Project Data.
void updateProjectDataToFile (ProjectData _projectDataToSave, ProjectDetails _projectDetails)
Update the project Data object values into the correspondent file and save it to disk.
ProjectData updateToolPaths (ProjectData _oldProjectData, ProjectData _newProjectData)
Returns a ProjectData object with the updated path values.
Private Attributes
QString _finalAbsoluteFilePath
Detailed Description
Definition at line 14 of file utilfiles.h.
Constructor & Destructor Documentation
UtilFiles::UtilFiles ()
Definition at line 33 of file utilfiles.cpp.
 {
 }
Member Function Documentation
void UtilFiles::copyAllFiles (QDir _oldPath, QDir _newPath, QStringList _listFiles)
Copy all the files from one project to other.
Parameters
_oldPath
_newPath
_listFiles
Definition at line 402 of file utilfiles.cpp.
 {
     for (int i=0;i<_listFiles.count();i++)
     {
         QString _oldFilePath = _oldPath.filePath(_listFiles.at(i));
         QString _newFilePath = _newPath.filePath(_listFiles.at(i));
         QFile::copy(_oldFilePath,_newFilePath);
     }
 }
void UtilFiles::copyAllToolData (ProjectData _oldProjectData, ProjectData _newProjectData)
Copy all the files from one project to other, regarding the content of the tool folders.
Parameters
_oldProjectData
_newProjectData
Definition at line 348 of file utilfiles.cpp.
References ProjectData::getProjectPath(), and TOOL4.
Referenced by MainWindow::on_actionSave_As_triggered().
 {
     QDir _oldPath(_oldProjectData.getProjectPath());
     QDir _newPath (_newProjectData.getProjectPath());
     if (_oldPath.exists())
     {
         QDir _oldTool4Path (_oldPath.filePath(TOOL4));
         QStringList _listFiles;
         if (_oldTool4Path.exists())
         {
             _listFiles = _oldTool4Path.entryList();
             QDir _newTool4Path(_newPath.filePath(TOOL4));
             copyAllFiles(_oldTool4Path,_newTool4Path,_listFiles);
         }
     }
 }
void UtilFiles::copyAllToolData (MultizoneProjectData _oldProjectData, MultizoneProjectData _newProjectData)
all the files from one project to other, regarding the content of the tool folders for Multizone Project
Parameters
_oldProjectData
_newProjectData
Definition at line 375 of file utilfiles.cpp.
References MultizoneProjectData::getProjectPath(), and TOOL4.
 {
     QDir _oldPath(_oldProjectData.getProjectPath());
     QDir _newPath (_newProjectData.getProjectPath());
     if (_oldPath.exists())
     {
         QDir _oldTool4Path (_oldPath.filePath(TOOL4));
         QStringList _listFiles;
         if (_oldTool4Path.exists())
         {
             _listFiles = _oldTool4Path.entryList();
             QDir _newTool4Path(_newPath.filePath(TOOL4));
             copyAllFiles(_oldTool4Path,_newTool4Path,_listFiles);
         }
     }
 }
void UtilFiles::copyFileToNewName (QString _filetoCopy, QString _newName)
Create a copy of a file with a different name.
Parameters
_filetoCopy
_newName
Definition at line 418 of file utilfiles.cpp.
 {
     QFile _file(_filetoCopy);
     if (_file.exists())
     {
         QFileInfo _fileInfo(_filetoCopy);
         QString _filePath = _fileInfo.absolutePath();
         QString _newFileName = QDir(_filePath).filePath(_newName);
         QFile::copy(_filetoCopy,_newFileName);
     }
 }
bool UtilFiles::createLink (QString _filePath, ProjectData _projectVO, QString _toolFolder)
Definition at line 509 of file utilfiles.cpp.
References ProjectData::getProjectPath(), and StrEqual.
Referenced by SolverUtil::uiImportSolverMeshFile().
 {
     QFileInfo _origPathInfo(_filePath);
     QString _destPath = QDir(_projectVO.getProjectPath()).filePath(_toolFolder);
     QString _fileName = _origPathInfo.fileName();
     QString _destFilePath = QDir(_destPath).filePath(_fileName);
     QFile _destConfigFile(_destFilePath);
      if( (_destConfigFile.exists()) && (QString::compare(_destFilePath,_filePath) != StrEqual))
         _destConfigFile.remove();
     bool _success = QFile::link(_filePath,_destFilePath);
     return _success;
 }
bool UtilFiles::createMultizoneProjectFile (QString _baseFileName, QString _finalPath)
Create the multizone project file (.mprj) with the needed information. With the name and in the path passed as arguments. If everything is ok –> returns true, otherwise false.
Parameters
_baseFileName
_finalPath
Returns
bool
Definition at line 150 of file utilfiles.cpp.
References XmlUtil::createInitialXmlMultizoneProjectFile(), and MULTIZONE_PROJECT_FILE_EXT.
 {
     bool _fileCreated = true;
     QString _suffix = QFileInfo(_baseFileName).suffix();
     if (_suffix.isEmpty())
         _baseFileName = _baseFileName + "."+ MULTIZONE_PROJECT_FILE_EXT;
     QString _finalFilePath = QDir(_finalPath).filePath(_baseFileName);
     XmlUtil _xmlUtil;
     _fileCreated= _xmlUtil.createInitialXmlMultizoneProjectFile(_finalFilePath, _finalPath,_baseFileName);
     this->_finalAbsoluteFilePath = _finalFilePath;
     return _fileCreated;
 }
bool UtilFiles::createMultizoneProjectStructure (QString _projectFilePath)
Create the multizoen project Structure, file and paths in the corresponding path If everything goes Ok –> return true, otherwise –> False.
Parameters
_projectFilePath
Returns
bool
Definition at line 81 of file utilfiles.cpp.
Referenced by MainWindow::on_actionSave_As_triggered(), and MultizoneProjectDialog::on_projectSelectionToolButton_clicked().
 {
     bool _createdProject = true;
     // 1. Get Base path and filename
     QFileInfo pathInfo( _projectFilePath );
     QString _baseFileName( pathInfo.fileName());
     QString _baseProjectName (pathInfo.baseName());
     QString _rootProjectPath ( pathInfo.absolutePath());
     QString _finalPath = QDir(_rootProjectPath).filePath(_baseProjectName);
     QDir _projectDir (_finalPath);
     if (!_projectDir.exists())
         _projectDir.mkpath(".");
     // Creating the project structure
     createProjectSubfolders(_finalPath);
     // Creating the associated file project
     _createdProject = createMultizoneProjectFile(_baseFileName,_finalPath);
     return _createdProject;
 }
bool UtilFiles::createProjectFile (QString _baseFileName, QString _finalPath)
Create the project file (.prj) with the needed information. With the name and in the path passed as arguments. If everything is ok –> returns true, otherwise false.
Parameters
_baseFileName
_finalPath
Returns
bool
Definition at line 126 of file utilfiles.cpp.
References XmlUtil::createInitialXmlProjectFile(), and SOLVER_PROJECT_FILE_EXT.
 {
     bool _fileCreated = true;
     QString _suffix = QFileInfo(_baseFileName).suffix();
     if (_suffix.isEmpty())
         _baseFileName = _baseFileName + "."+ SOLVER_PROJECT_FILE_EXT;
     QString _finalFilePath = QDir(_finalPath).filePath(_baseFileName);
     XmlUtil _xmlUtil;
     _fileCreated= _xmlUtil.createInitialXmlProjectFile(_finalFilePath, _finalPath,_baseFileName);
     this->_finalAbsoluteFilePath = _finalFilePath;
     return _fileCreated;
 }
bool UtilFiles::createProjectStructure (QString _projectFilePath)
Create the project Structure, file and paths in the corresponding path If everything goes Ok –> return true, otherwise –> False.
Parameters
_projectFilePath
Returns
bool
Definition at line 49 of file utilfiles.cpp.
Referenced by MainWindow::on_actionNew_Project_triggered(), and MainWindow::on_actionSave_As_triggered().
 {
     bool _createdProject = true;
     // 1. Get Base path and filename
     QFileInfo pathInfo( _projectFilePath );
     QString _baseFileName( pathInfo.fileName());
     QString _baseProjectName (pathInfo.baseName());
     QString _rootProjectPath ( pathInfo.absolutePath());
     QString _finalPath = QDir(_rootProjectPath).filePath(_baseProjectName);
     QDir _projectDir (_finalPath);
     if (!_projectDir.exists())
         _projectDir.mkpath(".");
     // Creating the project structure
     createProjectSubfolders(_finalPath);
     // Creating the associated file project
     _createdProject = createProjectFile(_baseFileName,_finalPath);
     return _createdProject;
 }
void UtilFiles::createProjectSubfolders (QString _basePath)
Create the project subfolders according with the implemented TOOLs in the corresponding path.
Parameters
_basePath
Definition at line 110 of file utilfiles.cpp.
References Tool4Id.
 {
         QString _newPath = QDir(_basePath).filePath(getSubfolderName(Tool4Id));
         QDir _projectDir (_newPath);
         if (!_projectDir.exists())
             _projectDir.mkpath(".");
 }
QString UtilFiles::getFinalPath ()
Gets the final Path of the whole project.
Returns
QString
Definition at line 456 of file utilfiles.cpp.
Referenced by MainWindow::on_actionNew_Project_triggered(), and MainWindow::on_actionSave_As_triggered().
 {
     return _finalAbsoluteFilePath;
 }
QString UtilFiles::getSubfolderName (int _indexTool)
Get the correspondent QString name of the tools subfolders.
Parameters
_indexTool
Returns
QString
Definition at line 438 of file utilfiles.cpp.
References TOOL4.
 {
     QString _subfolderName = "";
     switch(_indexTool)
     {
          case 4:
             _subfolderName = TOOL4;
             break;
        }
     return _subfolderName;
 }
bool UtilFiles::hasFileExtension (QString _path, QString _extension)
Checks if the file (absolute path + filename) contains the _extension, returning true, otherwise false.
Parameters
_path
_extension
Returns
bool
Definition at line 470 of file utilfiles.cpp.
References StrEqual.
Referenced by MainWindow::on_newActionButton_clicked(), and InputDataTabHelper::saveAsConfigFile().
 {
     QFileInfo _fileInfo = QFileInfo(_path);
     QString _fileExtension = _fileInfo.completeSuffix();
     if (QString::compare(_fileExtension, _extension) != StrEqual)
     {
         return false;
     }else
     {
         return true;
     }
 }
QString UtilFiles::importFile (QString _filePath, ProjectData _projectVO, QString _toolFolder)
Functionality to import a file and update the correspondent values in the project data and copying this file into the project folder.
Parameters
_filePath
_projectVO
_toolFolder
Returns
QString
Definition at line 494 of file utilfiles.cpp.
References ProjectData::getProjectPath(), and StrEqual.
Referenced by MultizoneProjectDialog::buildFilesInProject(), MultizoneIndividualTabForm::on_importMeshFileButton_clicked(), SolverUtil::uiImportSolverConfigFile(), SolverUtil::uiImportSolverMeshInfoFile(), and MainWindow::updateMultizoneUserData().
 {
     QFileInfo _origPathInfo(_filePath);
     QString _destPath = QDir(_projectVO.getProjectPath()).filePath(_toolFolder);
     QString _fileName = _origPathInfo.fileName();
     QString _destFilePath = QDir(_destPath).filePath(_fileName);
     QFile _destConfigFile(_destFilePath);
      if( (_destConfigFile.exists()) && (QString::compare(_destFilePath,_filePath) != StrEqual))
         _destConfigFile.remove();
     QFile::copy(_filePath,_destFilePath);
     return _destFilePath;
 }
QString UtilFiles::importFile (QString _destinationPath, QString _originPath, QString _toolFolder)
Functionality to import a file.
Parameters
_destinationPath
_originPath
_toolFolder
Returns
QString
Definition at line 531 of file utilfiles.cpp.
References StrEqual.
 {
     QFileInfo _origPathInfo(_originPath);
     QString _destPath = QDir(_destinationPath).filePath(_toolFolder);
     QString _fileName = _origPathInfo.fileName();
     QString _destFilePath = QDir(_destPath).filePath(_fileName);
     QFile _destConfigFile(_destFilePath);
      if( (_destConfigFile.exists()) && (QString::compare(_destFilePath,_originPath) != StrEqual))
         _destConfigFile.remove();
     QFile::copy(_originPath,_destFilePath);
     return _destFilePath;
 }
MultizoneProjectData UtilFiles::openMultizoneProjectStructure (QString _projectFilePath)
Obtains the data stored in the multizone file project (.mprj) returning the data into the Multizone Project data object.
Parameters
_projectFilePath
Returns
MultizoneProjectData
Definition at line 204 of file utilfiles.cpp.
References XmlUtil::readXmlMultizoneProjectFile().
Referenced by MultizoneManager::openMultizoneProject().
 {
     XmlUtil _xmlUtil;
     MultizoneProjectData _openedProject = _xmlUtil.readXmlMultizoneProjectFile(_projectFilePath);
     return _openedProject;
 }
ProjectDetails UtilFiles::openProjectDetails (QString _projectFilePath)
Parameters
_projectFilePath
Returns
ProjectDetails
Definition at line 189 of file utilfiles.cpp.
References XmlUtil::getXmlProjectDetails().
Referenced by MultizoneManager::openMultizoneProject(), and MainWindow::openProject().
 {
     XmlUtil _xmlUtil;
     ProjectDetails _projectDetails = _xmlUtil.getXmlProjectDetails(_projectFilePath);
     return _projectDetails;
 }
ProjectData UtilFiles::openProjectStructure (QString _projectFilePath)
Obtains the data stored in the file project (.prj) returning the data into the Project data object.
Parameters
_projectFilePath
Returns
ProjectData
Definition at line 174 of file utilfiles.cpp.
References XmlUtil::readXmlProjectFile().
Referenced by MainWindow::openProject().
 {
     XmlUtil _xmlUtil;
     ProjectData _openedProject = _xmlUtil.readXmlProjectFile(_projectFilePath);
     return _openedProject;
 }
void UtilFiles::updateMultizoneProjectDataToFile (MultizoneProjectData _multizoneProjectDataToSave, ProjectDetails _projectDetails)
Update the multizone project Data object values into the correspondent file and save it to disk.
Parameters
_multizoneProjectDataToSave
Definition at line 237 of file utilfiles.cpp.
References XmlUtil::createXmlMultizoneProjectFile(), MultizoneProjectData::getProjectName(), MultizoneProjectData::getProjectPath(), MULTIZONE_PROJECT_FILE_EXT, and StrEqual.
Referenced by MultizoneProjectDialog::accept(), MainWindow::on_actionSave_As_triggered(), and MainWindow::updateProjectDataToFile().
 {
     XmlUtil _xmlUtil;
     QString _fileNameWithExt = _multizoneProjectDataToSave.getProjectName();// + "."+ MULTIZONE_PROJECT_FILE_EXT;
     QString _fileExt = QFileInfo(_multizoneProjectDataToSave.getProjectName()).completeSuffix();
     if(  (_fileExt.isEmpty()) || (QString::compare(_fileExt,MULTIZONE_PROJECT_FILE_EXT) != StrEqual) )
     {
         // We add the file Extension
         _fileNameWithExt = _fileNameWithExt + "."+ MULTIZONE_PROJECT_FILE_EXT;
     }
     QString _fullPath = QDir(_multizoneProjectDataToSave.getProjectPath()).filePath(_fileNameWithExt);
     _xmlUtil.createXmlMultizoneProjectFile(_fullPath, _multizoneProjectDataToSave,_projectDetails);
 }
MultizoneProjectData UtilFiles::updateMultizoneToolPaths (MultizoneProjectData _oldMultizoneProjectData, MultizoneProjectData _newMultizoneProjectData)
Update teh Multizone Tool paths according with the new Project Data.
Parameters
_oldMultizoneProjectData
_newMultizoneProjectData
Returns
MultizoneProjectData
Definition at line 307 of file utilfiles.cpp.
References MultizoneProjectData::getListConfigFileNames(), MultizoneProjectData::getListMeshFileNames(), MultizoneProjectData::getProjectName(), MultizoneProjectData::getProjectPath(), MultizoneProjectData::setListConfigFiles(), MultizoneProjectData::setListMeshFiles(), MultizoneProjectData::setProjectName(), MultizoneProjectData::setProjectPath(), and TOOL4.
Referenced by MainWindow::on_actionSave_As_triggered().
 {
     MultizoneProjectData  _updatedMultizoneProjectData;
     _updatedMultizoneProjectData.setProjectPath(_newMultizoneProjectData.getProjectPath());
     _updatedMultizoneProjectData.setProjectName(_newMultizoneProjectData.getProjectName());
     QString _projectPath = _newMultizoneProjectData.getProjectPath();
     // Solver updated
     QString _tool4Path = QDir(_projectPath).filePath(TOOL4);
     QStringList _listConfigNames = _oldMultizoneProjectData.getListConfigFileNames();
     QStringList _newConfigList;
     if (!_listConfigNames.isEmpty())
         for (int i = 0; i < _listConfigNames.size();i++)
         {
             QString _fileName = _listConfigNames.at(i);
             _newConfigList.append(QDir(_tool4Path).filePath(_fileName));
         }
     QStringList _listMeshNames = _oldMultizoneProjectData.getListMeshFileNames();
     QStringList _newMeshList;
     if (!_listMeshNames.isEmpty())
         for (int i = 0; i < _listMeshNames.size();i++)
         {
             QString _fileMeshName = _listMeshNames.at(i);
             _newMeshList.append(QDir(_tool4Path).filePath(_fileMeshName));
         }
     _updatedMultizoneProjectData.setListConfigFiles(_newConfigList);
     _updatedMultizoneProjectData.setListMeshFiles(_newMeshList);
     return _updatedMultizoneProjectData;
 }
void UtilFiles::updateProjectDataToFile (ProjectData _projectDataToSave, ProjectDetails _projectDetails)
Update the project Data object values into the correspondent file and save it to disk.
Parameters
_projectDataToSave
Definition at line 219 of file utilfiles.cpp.
References XmlUtil::createXmlProjectFile(), ProjectData::getProjectFileName(), ProjectData::getProjectPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), and SolverVO::getSolverFilePath().
Referenced by MainWindow::on_actionSave_As_triggered(), and MainWindow::updateProjectDataToFile().
 {
     XmlUtil _xmlUtil;
     QString _fullPath = QDir( _projectDataToSave.getProjectPath()).filePath(_projectDataToSave.getProjectFileName());
     _xmlUtil.createXmlProjectFile(_fullPath, _projectDataToSave.getProjectPath(),
                                   _projectDataToSave.getProjectFileName(),
                                   _projectDataToSave.getSolverDataInformation().getSolverFilePath(),
                                   _projectDataToSave.getSolverDataInformation().getSolverConfigFilePath(),
                                   _projectDetails);
 }
ProjectData UtilFiles::updateToolPaths (ProjectData _oldProjectData, ProjectData _newProjectData)
Returns a ProjectData object with the updated path values.
Parameters
_oldProjectData
_newProjectData
Returns
ProjectData
Definition at line 260 of file utilfiles.cpp.
References ProjectData::getProjectFileName(), ProjectData::getProjectPath(), SolverVO::getSolverConfigFilePath(), ProjectData::getSolverDataInformation(), SolverVO::getSolverFilePath(), SolverVO::isConfigFileEmpty(), ProjectData::isEmpty(), SolverVO::isMeshFileEmpty(), ProjectData::setProjectFileName(), ProjectData::setProjectPath(), SolverVO::setSolverConfigFilePath(), ProjectData::setSolverDataInformation(), SolverVO::setSolverFilePath(), and TOOL4.
Referenced by MainWindow::on_actionSave_As_triggered().
 {
     ProjectData  _updatedProjectData;
     if (_oldProjectData.isEmpty())
         return _updatedProjectData;
     _updatedProjectData.setProjectPath(_newProjectData.getProjectPath());
     _updatedProjectData.setProjectFileName(_newProjectData.getProjectFileName());
     QString _projectPath = _newProjectData.getProjectPath();
     // Solver updated
     QString _tool4Path = QDir(_projectPath).filePath(TOOL4);
     //Setting the mesh file name
     QString _oldMeshFileName;
     QString _meshFileName;
     if (!_oldProjectData.getSolverDataInformation().isMeshFileEmpty())
     {
         _oldMeshFileName  = QFileInfo(_oldProjectData.getSolverDataInformation().getSolverFilePath()).fileName();
        _meshFileName = QDir(_tool4Path).filePath(_oldMeshFileName);
     }
     QString _oldConfigFileName;
     QString _configFileName;
     if (!_oldProjectData.getSolverDataInformation().isConfigFileEmpty())
     {
        _oldConfigFileName = QFileInfo(_oldProjectData.getSolverDataInformation().getSolverConfigFilePath()).fileName();
       _configFileName = QDir(_tool4Path).filePath(_oldConfigFileName);
     }
     // Setting up the new values in the solver data
     SolverVO _newSolverVO;
     _newSolverVO.setSolverFilePath(_meshFileName);
     _newSolverVO.setSolverConfigFilePath(_configFileName);
     _updatedProjectData.setSolverDataInformation(_newSolverVO);
     return _updatedProjectData;
 }
Member Data Documentation
QString UtilFiles::_finalAbsoluteFilePath private
Definition at line 66 of file utilfiles.h.
The documentation for this class was generated from the following files:
Utility/utilfiles.h
Utility/utilfiles.cpp