BBIPED Platform: SalomeToolCreateMeshDialog Class Reference
SalomeToolCreateMeshDialog Class Reference
#include <salometoolcreatemeshdialog.h>
Signals
void outlogtext (QString ver)
Public Member Functions
SalomeToolCreateMeshDialog (QWidget *parent=0)
~SalomeToolCreateMeshDialog ()
void setBBIPEDPath (QString _path)
void setProjectName (QString _name)
void setProjectPath (QString _path)
void setSalomeMeshViewerPath (QString _path)
void setTemplateData (SalomeTemplateData _template)
Private Slots
void errorConsole ()
void meshCreationFinished ()
void on_createMeshButton_clicked ()
void on_finishButton_clicked ()
void outputConsole ()
void slotProcessError (QProcess::ProcessError error)
Private Member Functions
void closeSalomeTool ()
void runPythonFile ()
Private Attributes
QString _bbipedPath
QProcess * _meshCreationProcess
QString _projectName
QString _projectPath
QTextEdit * _regEditor
QString _salomeMeshPath
SalomeTemplateData _templateData
Ui::SalomeToolCreateMeshDialog * ui
Detailed Description
Definition at line 14 of file salometoolcreatemeshdialog.h.
Constructor & Destructor Documentation
SalomeToolCreateMeshDialog::SalomeToolCreateMeshDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 31 of file salometoolcreatemeshdialog.cpp.
References _regEditor, and ui.
                                                                       :
     QDialog(parent),
     ui(new Ui::SalomeToolCreateMeshDialog)
 {
     ui->setupUi(this);
     _regEditor = ui->consoleTextEdit;
 }
SalomeToolCreateMeshDialog::~SalomeToolCreateMeshDialog ()
Definition at line 43 of file salometoolcreatemeshdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void SalomeToolCreateMeshDialog::closeSalomeTool () private
void SalomeToolCreateMeshDialog::errorConsole () private slot
Definition at line 157 of file salometoolcreatemeshdialog.cpp.
References _meshCreationProcess, and _regEditor.
Referenced by runPythonFile().
 {
     QString _output =_meshCreationProcess->readAllStandardError();
      //emit outlogtext(_output);
     _output = "[ERROR] -->" + _output;
     _regEditor->append(_output);
 }
void SalomeToolCreateMeshDialog::meshCreationFinished () private slot
Definition at line 168 of file salometoolcreatemeshdialog.cpp.
References _meshCreationProcess, _projectPath, _regEditor, and ui.
Referenced by runPythonFile().
 {
     ui->finishButton->setEnabled(true);
     if (_meshCreationProcess->exitStatus() < 0)
      {
          _regEditor->append("[ERROR] --> Mesh cannot be created. Check your files");
          _regEditor->append(_meshCreationProcess->errorString());
      }else
     {
         _regEditor->append("[OUTPUT] --> Mesh created. Check your folder");
         // Change the name of the file to the user selection
         QString _userFileNameSelection = ui->meshFileNameLineEdit->text();
         if (!_userFileNameSelection.isEmpty())
         {
             QString _pythonPath=QDir(_projectPath).filePath("Python");
             QString _finalOldFile = QDir(_pythonPath).filePath("AutomaticMesh.su2");
             QString _finalNewFile = QDir(_pythonPath).filePath(_userFileNameSelection+".su2");
             QFile::rename(_finalOldFile,_finalNewFile);
         }
     }
 }
void SalomeToolCreateMeshDialog::on_createMeshButton_clicked () private slot
Definition at line 217 of file salometoolcreatemeshdialog.cpp.
References _projectName, _projectPath, _templateData, SalomePythonFileUtil::buildPythonFile(), SalomeTemplateData::isEmpty(), runPythonFile(), SalomePythonFileUtil::setFileName(), SalomePythonFileUtil::setPathProject(), and SalomePythonFileUtil::setTemplateData().
 {
     if (_templateData.isEmpty())
         return;
     SalomePythonFileUtil _pythonUtil;
     _pythonUtil.setFileName(_projectName);
     _pythonUtil.setPathProject(_projectPath);
     _pythonUtil.setTemplateData(_templateData);
     _pythonUtil.buildPythonFile();
      // Running the python file
     runPythonFile();
 }
void SalomeToolCreateMeshDialog::on_finishButton_clicked () private slot
Definition at line 238 of file salometoolcreatemeshdialog.cpp.
 {
     close();
 }
void SalomeToolCreateMeshDialog::outlogtext (QString ver) signal
Referenced by outputConsole().
void SalomeToolCreateMeshDialog::outputConsole () private slot
Definition at line 146 of file salometoolcreatemeshdialog.cpp.
References _meshCreationProcess, _regEditor, and outlogtext().
Referenced by runPythonFile().
 {
     QString _output =_meshCreationProcess->readAllStandardOutput() ;
     _output = "[OUTPUT] --> " + _output;
     emit outlogtext(_output);
     _regEditor->append(_output);
 }
void SalomeToolCreateMeshDialog::runPythonFile () private
Definition at line 83 of file salometoolcreatemeshdialog.cpp.
References _meshCreationProcess, _projectName, _projectPath, _regEditor, _salomeMeshPath, errorConsole(), meshCreationFinished(), outputConsole(), slotProcessError(), and ui.
Referenced by on_createMeshButton_clicked().
 {
     QFileInfo _salomeFilePath(_salomeMeshPath);
     QString _salomeToolPath = _salomeFilePath.absolutePath();
     if (_salomeToolPath.isEmpty())
         return;
     _regEditor->append("Starting Python JobManager Execution ....");
     _meshCreationProcess = new QProcess(this);
     _meshCreationProcess->setWorkingDirectory(QDir(_projectPath).filePath("Python"));
     QString _meshCommand("") ;
     _meshCommand = _salomeToolPath + "/runSession runSalome -t -u" + _projectName +".py";
     connect(_meshCreationProcess, SIGNAL(error(QProcess::ProcessError)),
             this, SLOT(slotProcessError(QProcess::ProcessError)));
     connect(_meshCreationProcess, SIGNAL(readyReadStandardOutput()), this, SLOT(outputConsole()));
     connect(_meshCreationProcess, SIGNAL(readyReadStandardError()), this, SLOT(errorConsole()));
     connect(_meshCreationProcess, SIGNAL(finished(int)), this, SLOT(meshCreationFinished()));
     _regEditor->append("[START MESH CREATION] --> Running " + _meshCommand);
     _meshCreationProcess->start(_meshCommand);
     // Updating the Text of the Create Mesh Button
     ui->createMeshButton->setDisabled(true);
 }
void SalomeToolCreateMeshDialog::setBBIPEDPath (QString _path)
Parameters
_path
Definition at line 207 of file salometoolcreatemeshdialog.cpp.
References _bbipedPath.
Referenced by SalomeTemplateDialog::on_createMeshButton_clicked().
 {
     _bbipedPath = _path;
 }
void SalomeToolCreateMeshDialog::setProjectName (QString _name)
Parameters
_name
Definition at line 61 of file salometoolcreatemeshdialog.cpp.
References _projectName.
Referenced by SalomeTemplateDialog::on_createMeshButton_clicked().
 {
     _projectName = _name;
 }
void SalomeToolCreateMeshDialog::setProjectPath (QString _path)
Parameters
_path
Definition at line 71 of file salometoolcreatemeshdialog.cpp.
References _projectPath.
Referenced by SalomeTemplateDialog::on_createMeshButton_clicked().
 {
     _projectPath = _path;
 }
void SalomeToolCreateMeshDialog::setSalomeMeshViewerPath (QString _path)
Parameters
_path
Definition at line 197 of file salometoolcreatemeshdialog.cpp.
References _salomeMeshPath.
Referenced by SalomeTemplateDialog::on_createMeshButton_clicked().
 {
     _salomeMeshPath = _path;
 }
void SalomeToolCreateMeshDialog::setTemplateData (SalomeTemplateData _template)
Parameters
_template
Definition at line 52 of file salometoolcreatemeshdialog.cpp.
References _templateData.
Referenced by SalomeTemplateDialog::on_createMeshButton_clicked().
 {
     _templateData = _template;
 }
void SalomeToolCreateMeshDialog::slotProcessError (QProcess::ProcessError error) private slot
Parameters
error
Definition at line 113 of file salometoolcreatemeshdialog.cpp.
References _regEditor.
Referenced by runPythonFile().
 {
     switch (error) {
         case QProcess::FailedToStart :
         _regEditor->append("FAILED to start the application: Check the executable configuration in the Preferences Menu");
             break;
     case QProcess::Crashed:
        _regEditor->append( "STOP Running simulation" );
         break;
        case QProcess::Timedout:
        _regEditor->append("TimedOut process: Contact Support");
         break;
     case QProcess::WriteError:
        _regEditor->append("Write Error: Check the permissions of the folder");
         break;
     case QProcess::ReadError:
        _regEditor->append( "Read Error: Check the permissions of the files ");
         break;
     case QProcess::UnknownError:
       _regEditor->append("Unknown Error: Contact Support ");
         break;
     }
  //stopSolverProcess();
 }
Member Data Documentation
QString SalomeToolCreateMeshDialog::_bbipedPath private
Definition at line 47 of file salometoolcreatemeshdialog.h.
Referenced by setBBIPEDPath().
QProcess* SalomeToolCreateMeshDialog::_meshCreationProcess private
Definition at line 50 of file salometoolcreatemeshdialog.h.
Referenced by errorConsole(), meshCreationFinished(), outputConsole(), and runPythonFile().
QString SalomeToolCreateMeshDialog::_projectName private
Definition at line 44 of file salometoolcreatemeshdialog.h.
Referenced by on_createMeshButton_clicked(), runPythonFile(), and setProjectName().
QString SalomeToolCreateMeshDialog::_projectPath private
Definition at line 45 of file salometoolcreatemeshdialog.h.
Referenced by meshCreationFinished(), on_createMeshButton_clicked(), runPythonFile(), and setProjectPath().
QTextEdit* SalomeToolCreateMeshDialog::_regEditor private
Definition at line 51 of file salometoolcreatemeshdialog.h.
Referenced by errorConsole(), meshCreationFinished(), outputConsole(), runPythonFile(), SalomeToolCreateMeshDialog(), and slotProcessError().
QString SalomeToolCreateMeshDialog::_salomeMeshPath private
Definition at line 46 of file salometoolcreatemeshdialog.h.
Referenced by runPythonFile(), and setSalomeMeshViewerPath().
SalomeTemplateData SalomeToolCreateMeshDialog::_templateData private
Definition at line 43 of file salometoolcreatemeshdialog.h.
Referenced by on_createMeshButton_clicked(), and setTemplateData().
Ui::SalomeToolCreateMeshDialog* SalomeToolCreateMeshDialog::ui private
Definition at line 42 of file salometoolcreatemeshdialog.h.
Referenced by meshCreationFinished(), runPythonFile(), SalomeToolCreateMeshDialog(), and ~SalomeToolCreateMeshDialog().
The documentation for this class was generated from the following files:
Forms/ToolsDialog/salometoolcreatemeshdialog.h
Forms/ToolsDialog/salometoolcreatemeshdialog.cpp