BBIPED Platform: SolverConfigReader Class Reference
SolverConfigReader Class Reference
#include <solverconfigreader.h>
Classes
struct childIds
Public Member Functions
SolverConfigReader ()
Constructor.
QList< SolverSectionVO > getAllSectionVariableMenus (QDomDocument *_tree)
Function that returns the list of SolverSection elements from the XML DOM template.
QStringList getComboValues (QDomElement _element)
Function that get the list of Combo values from the XML Tree.
void updateAllDomTree (QHash< QString, QString > _newMapValues, QDomDocument *_domTree)
Function taht updates all the values of the DOM tree.
void updateValueElement (QString _valueName, QString _newValue, QDomDocument *_domTree)
Function tha update the value elements in the Dom TREE.
Private Member Functions
void changeValueElement (QString _varName, QString _newValue, QDomDocument *_domTree)
Function that changels the values of the elements in the DOM tree.
void createComboValues (QDomElement _element, SolverVariableVO *_solverVO)
This function create the SolverVAriable value object with the content for the combo values to be shown in the view.
SolverVarHelpVO * createHelpElement (QDomElement _element)
This fucntion allows to create the help element from the xml file.
QList< SolverSectionVO > createSectionNode (QDomElement _element)
Function that creates the SolverSection list from a Section element of the XML template.
QList< SolverVariableVO > createVariableSection (QDomElement _element)
Function that creates the SolverSection list from a Variable element of the XML template.
childIds findSectionChildId (QString _varName, QDomNodeList _sectionNodeList)
Function that finds a Section node in the XML Tree.
Detailed Description
Definition at line 13 of file solverconfigreader.h.
Constructor & Destructor Documentation
SolverConfigReader::SolverConfigReader ()
Constructor.
Definition at line 32 of file solverconfigreader.cpp.
 {
 }
Member Function Documentation
void SolverConfigReader::changeValueElement (QString _varName, QString _newValue, QDomDocument * _domTree) private
Function that changels the values of the elements in the DOM tree.
Parameters
_varName
_newValue
_domTree
Definition at line 337 of file solverconfigreader.cpp.
References SolverConfigReader::childIds::_sectionId, and SolverConfigReader::childIds::_variableId.
 {
     QDomElement  _rootElement = _domTree->documentElement();
     QDomNodeList _sectionNodeList = _rootElement.childNodes();
     childIds _foundVarIds = findSectionChildId(_varName,_sectionNodeList);
     _domTree->documentElement().childNodes().at(_foundVarIds._sectionId).childNodes().
             at(_foundVarIds._variableId).childNodes().at(2).firstChild().setNodeValue(_newValue);
 }
void SolverConfigReader::createComboValues (QDomElement _element, SolverVariableVO * _solverVO) private
This function create the SolverVAriable value object with the content for the combo values to be shown in the view.
Parameters
_element
_solverVO
Definition at line 184 of file solverconfigreader.cpp.
References SolverVariableVO::setComboValueNamesList(), SolverVariableVO::setComboValuesList(), SolverVariableVO::setSelectableComboValues(), StrEqual, XML_VARIABLE_COMBOVALUE_ELEMENT_NAME, XML_VARIABLE_COMBOVALUE_NAME_ATT, and XML_VARIABLE_COMBOVALUE_SELECTABLE_ATT.
 {
     QDomNodeList _comboValList = _element.elementsByTagName(XML_VARIABLE_COMBOVALUE_ELEMENT_NAME);
     if (!_comboValList.isEmpty())
     {
         QStringList _listVal;
         QStringList _listNames;
         QList<bool> _selectableValList;
         for (int i = 0;i < _comboValList.count();i++)
         {
             QDomElement _valueEl = _comboValList.at(i).toElement();
             _listVal.append(_valueEl.text() );
             if (_valueEl.hasAttribute(XML_VARIABLE_COMBOVALUE_NAME_ATT))
                 _listNames.append(_valueEl.attribute(XML_VARIABLE_COMBOVALUE_NAME_ATT));
             if (_valueEl.hasAttribute(XML_VARIABLE_COMBOVALUE_SELECTABLE_ATT))
             {
                 QString _selVal= _valueEl.attribute(XML_VARIABLE_COMBOVALUE_SELECTABLE_ATT);
                 if (QString::compare(_valueEl.attribute(XML_VARIABLE_COMBOVALUE_SELECTABLE_ATT),"YES") == StrEqual)
                     _selectableValList.append(true);
                 else
                     _selectableValList.append(false);
             }
         }
         if (!_listNames.isEmpty())
             _solverVO->setComboValueNamesList(_listNames);
         if (!_listVal.isEmpty())
             _solverVO->setComboValuesList(_listVal);
         if (!_selectableValList.isEmpty())
             _solverVO->setSelectableComboValues(_selectableValList);
     }
 }
SolverVarHelpVO * SolverConfigReader::createHelpElement (QDomElement _element) private
This fucntion allows to create the help element from the xml file.
Parameters
_element
Returns
SolverVarHelpVO
Definition at line 228 of file solverconfigreader.cpp.
References SolverVarHelpVO::setDefinitionText(), SolverVarHelpVO::setDetailsText(), and SolverVarHelpVO::setValuesText().
 {
     SolverVarHelpVO * _helpObj = new SolverVarHelpVO();
     QDomNodeList _definition = _element.elementsByTagName("definition");
     QDomNodeList _values = _element.elementsByTagName("values");
     QDomNodeList _details =_element.elementsByTagName("otherdetails");
     if( (!_definition.isEmpty()) && (_definition.size() >= 1))
             _helpObj->setDefinitionText(_definition.at(0).toElement().text());
     if( (!_values.isEmpty()) && (_values.size() >= 1))
         _helpObj->setValuesText(_values.at(0).toElement().text());
     if( (!_details.isEmpty()) && (_details.size() >= 1))
         _helpObj->setDetailsText(_details.at(0).toElement().text());
     return _helpObj;
 }
QList< SolverSectionVO > SolverConfigReader::createSectionNode (QDomElement _element) private
Function that creates the SolverSection list from a Section element of the XML template.
Parameters
_element
Returns
QList<SolverSectionVO>
Definition at line 44 of file solverconfigreader.cpp.
References SolverSectionVO::setSectionName(), SolverSectionVO::setSubsectionName(), SolverSectionVO::setSubsectionVarList(), XML_SUBSECTION_NAME, XML_SUBSECTION_TITLE_NAME, and XML_TITLE_SECTION_NAME.
 {
     QList<SolverSectionVO> _resultList;
     QString _sectionTitle;
     QDomNodeList _titleList = _element.elementsByTagName(XML_TITLE_SECTION_NAME);
     if (!_titleList.isEmpty())
     {
         _sectionTitle = _titleList.at(0).toElement().text();
     }
     QDomNodeList _sectionList = _element.elementsByTagName(XML_SUBSECTION_NAME);
     if (!_sectionList.isEmpty())
     {
         for (int i = 0; i <_sectionList.count();i++)
         {
             QDomElement _child = _sectionList.at(i).toElement();
             SolverSectionVO _createdObjVO;
             _createdObjVO.setSectionName(_sectionTitle);
             QDomNodeList _titleSubsecList = _child.elementsByTagName(XML_SUBSECTION_TITLE_NAME);
             if (!_titleSubsecList.isEmpty())
                  _createdObjVO.setSubsectionName(_titleSubsecList.at(0).toElement().text());
             QList<SolverVariableVO> _variableList = createVariableSection(_child);
             _createdObjVO.setSubsectionVarList(_variableList);
             _resultList.append(_createdObjVO);
         }
     }
     return _resultList;
 }
QList< SolverVariableVO > SolverConfigReader::createVariableSection (QDomElement _element) private
Function that creates the SolverSection list from a Variable element of the XML template.
Parameters
_element
Returns
QList<SolverVariableVO>
Definition at line 80 of file solverconfigreader.cpp.
References SolverVariableVO::setAssociatedVariables(), SolverVariableVO::setCurrentValue(), SolverVariableVO::setDefaultValue(), SolverVariableVO::setHelpContents(), SolverVariableVO::setOptional(), SolverVariableVO::setRepeatable(), SolverVariableVO::setSubVariableNames(), SolverVariableVO::setUniqueSelection(), SolverVariableVO::setUnitValue(), SolverVariableVO::setVariableFileName(), SolverVariableVO::setVariableName(), SolverVariableVO::setVariableSelectable(), SolverVariableVO::setVisibleInMenu(), StrEqual, XML_VARIABLE_ASSOCIATED_VAR_ATT, XML_VARIABLE_COMBOVALUE_UNIQUESEL_ATT, XML_VARIABLE_COMBOVALUES_LIST_NAME, XML_VARIABLE_HELP_NAME, XML_VARIABLE_ISOPTIONAL_ATT, XML_VARIABLE_ISREPEATABLE_ATT, XML_VARIABLE_ISVISIBLEINMENU_ATT, XML_VARIABLE_NAME, XML_VARIABLE_NAME_NAME, XML_VARIABLE_SELECTABLE_ATT, XML_VARIABLE_VALUE_DEFAULT_VALUE_ATT, XML_VARIABLE_VALUE_NAME, XML_VARIABLE_VALUE_NAME_ATT, XML_VARIABLE_VALUE_SUBVAR_NAME_ATT, XML_VARIABLE_VALUE_UNIT_ATT, and YES_VALUE.
 {
     QList<SolverVariableVO> _resultList;
     QDomNodeList _variableList = _element.elementsByTagName(XML_VARIABLE_NAME);
     if (!_variableList.isEmpty())
     {
         for (int i = 0;i < _variableList.count();i++)
         {
             SolverVariableVO _createdObj;
             QDomElement _child = _variableList.at(i).toElement();
             // Check if it is repeatable
             if (_child.hasAttribute(XML_VARIABLE_ISREPEATABLE_ATT))
                 if (QString::compare(_child.attribute(XML_VARIABLE_ISREPEATABLE_ATT),YES_VALUE) == StrEqual)
                         _createdObj.setRepeatable(true);
             // Check if it is optional
             if (_child.hasAttribute(XML_VARIABLE_ISOPTIONAL_ATT))
                 if (QString::compare(_child.attribute(XML_VARIABLE_ISOPTIONAL_ATT),YES_VALUE) == StrEqual)
                         _createdObj.setOptional(true);
             // Check if it is selectable by the users
              if (_child.hasAttribute(XML_VARIABLE_SELECTABLE_ATT))
                  if (QString::compare(_child.attribute(XML_VARIABLE_SELECTABLE_ATT),"YES") == StrEqual)
                          _createdObj.setVariableSelectable(true);
                  else
                      _createdObj.setVariableSelectable(false);
             QDomNodeList _nameList = _child.elementsByTagName(XML_VARIABLE_NAME_NAME);
             // Variable Name
             if (!_nameList.isEmpty())
                  _createdObj.setVariableName(_nameList.at(0).toElement().text());
             QDomNodeList _helpList = _child.elementsByTagName(XML_VARIABLE_HELP_NAME);
             // Help Value
             if (!_helpList.isEmpty())
                  _createdObj.setHelpContents(createHelpElement(_helpList.at(0).toElement()));
             QDomNodeList _valueList = _child.elementsByTagName(XML_VARIABLE_VALUE_NAME);
             if (!_valueList.isEmpty())
             {
                 QDomElement _valueEl = _valueList.at(0).toElement();
                 // Variable File Name
                 if (_valueEl.hasAttribute(XML_VARIABLE_VALUE_NAME_ATT))
                     _createdObj.setVariableFileName(_valueEl.attribute(XML_VARIABLE_VALUE_NAME_ATT));
                 // Default Value
                 if (_valueEl.hasAttribute(XML_VARIABLE_VALUE_DEFAULT_VALUE_ATT))
                 {
                     _createdObj.setDefaultValue(_valueEl.attribute(XML_VARIABLE_VALUE_DEFAULT_VALUE_ATT));
                     _createdObj.setCurrentValue(_valueEl.text());
                 }
                 // Unit Value
                 if (_valueEl.hasAttribute(XML_VARIABLE_VALUE_UNIT_ATT))
                 {
                     QString _unitValue = _valueEl.attribute(XML_VARIABLE_VALUE_UNIT_ATT);
                     if (QString::compare(_unitValue,"NONE") == StrEqual) // If there is no unit applicable, we don't shown anything
                         _unitValue = "";
                     _createdObj.setUnitValue(_unitValue);
                 }
                 // In case it has Other Variable Names inside
                 if (_valueEl.hasAttribute(XML_VARIABLE_VALUE_SUBVAR_NAME_ATT))
                 {
                     QString _subVariableNameList = _valueEl.attribute(XML_VARIABLE_VALUE_SUBVAR_NAME_ATT);
                     _createdObj.setSubVariableNames(_subVariableNameList.split(","));
                 }
                 // Check if it is Visible
                 if (_valueEl.hasAttribute(XML_VARIABLE_ISVISIBLEINMENU_ATT))
                     if (QString::compare(_valueEl.attribute(XML_VARIABLE_ISVISIBLEINMENU_ATT),"NO") == StrEqual)
                             _createdObj.setVisibleInMenu(false);
                 // Check if it contains associated variables
                 if (_valueEl.hasAttribute(XML_VARIABLE_ASSOCIATED_VAR_ATT))
                 {
                     QString _associatedVarList = _valueEl.attribute(XML_VARIABLE_ASSOCIATED_VAR_ATT);
                     _createdObj.setAssociatedVariables(_associatedVarList.split(","));
                 }
             }
             // Combo Values
             QDomNodeList _comboValuesParent = _child.elementsByTagName(XML_VARIABLE_COMBOVALUES_LIST_NAME);
             if (! _comboValuesParent.isEmpty())
             {
                 QDomElement _comboAttElement = _comboValuesParent.at(0).toElement();
                 QString _uniqueValue;
                 if (_comboAttElement.hasAttribute(XML_VARIABLE_COMBOVALUE_UNIQUESEL_ATT))
                     _uniqueValue = _comboAttElement.attribute(XML_VARIABLE_COMBOVALUE_UNIQUESEL_ATT);
                 // If the combo values has selected no unique option, this implies that it allows multiple
                 // selection (similar to checkbox
                 if ((!_uniqueValue.isEmpty()) && (QString::compare(_uniqueValue,"YES") != StrEqual))
                     _createdObj.setUniqueSelection(false);
             }
             createComboValues(_child, &_createdObj);
             _resultList.append(_createdObj);
         }
     }
     return _resultList;
 }
SolverConfigReader::childIds SolverConfigReader::findSectionChildId (QString _varName, QDomNodeList _sectionNodeList) private
Function that finds a Section node in the XML Tree.
Parameters
_varName
_sectionNodeList
Returns
SolverConfigReader::childIds
Definition at line 355 of file solverconfigreader.cpp.
References SolverConfigReader::childIds::_sectionId, SolverConfigReader::childIds::_variableId, StrEqual, XML_VARIABLE_NAME, XML_VARIABLE_VALUE_NAME, and XML_VARIABLE_VALUE_NAME_ATT.
 {
     int _varIndex = 0;
     childIds _foundId;
     _foundId._sectionId = -1;
     _foundId._variableId = -1;
     for (int i = 0 ; i < _sectionNodeList.count(); i++)
     {
         QDomElement _sectionEl = _sectionNodeList.at(i).toElement();
         cout << _sectionEl.tagName().toStdString() << endl;
         QDomNode _childNode = _sectionEl.firstChild();
         while  (!_childNode.isNull())
         {
             QDomElement _nodeElement = _childNode.toElement();
             if (!_nodeElement.isNull())
             {
                 if (QString::compare(_nodeElement.tagName(),XML_VARIABLE_NAME) == StrEqual)
                 {
                       QDomNodeList _valueNode = _nodeElement.elementsByTagName(XML_VARIABLE_VALUE_NAME);
                       if ((!_valueNode.isEmpty()) && (_valueNode.size() == 1))
                       {
                           QString _nameAtt = _valueNode.at(0).toElement().attribute(XML_VARIABLE_VALUE_NAME_ATT);
                           if (QString::compare(_nameAtt,_varName) == StrEqual)
{
                                 _foundId._sectionId = i;
                                 _foundId._variableId = _varIndex;
                                 return _foundId;
                           }
                       }
                 }
             }
             _childNode = _childNode.nextSibling();
             _varIndex ++;
         }
     }
     return _foundId;
 }
QList< SolverSectionVO > SolverConfigReader::getAllSectionVariableMenus (QDomDocument * _tree)
Function that returns the list of SolverSection elements from the XML DOM template.
Parameters
_tree
Returns
QList<SolverSectionVO>
Definition at line 253 of file solverconfigreader.cpp.
References XML_SECTION_NODE_NAME.
Referenced by SolverConfigManager::buildMenuVariablesList(), and SolverConfigManager::buildPersonalizedMenuVariablesList().
 {
     QList<SolverSectionVO> _list;
     QDomElement _root = _tree->documentElement();
     QDomNodeList _sectionNodeList = _root.elementsByTagName(XML_SECTION_NODE_NAME);
     if (!_sectionNodeList.isEmpty())
     {
         for (int i = 0; i < _sectionNodeList.count();i++)
         {
             QList<SolverSectionVO> _resultList = createSectionNode(_sectionNodeList.at(i).toElement());
             _list.append(_resultList);
         }
     }
     return _list;
 }
QStringList SolverConfigReader::getComboValues (QDomElement _element)
Function that get the list of Combo values from the XML Tree.
Parameters
_element
Returns
QStringList
Definition at line 277 of file solverconfigreader.cpp.
References XML_VARIABLE_COMBOVALUE_ELEMENT_NAME.
 {
     QStringList _resultList;
     QDomNodeList _comboList = _element.elementsByTagName(XML_VARIABLE_COMBOVALUE_ELEMENT_NAME);
     if (_comboList.isEmpty())
         return _resultList;
     for (int i = 0;i < _comboList.count();i++)
         _resultList.append(_comboList.at(i).toElement().text() );
     return _resultList;
 }
void SolverConfigReader::updateAllDomTree (QHash< QString, QString > _newMapValues, QDomDocument * _domTree)
Function taht updates all the values of the DOM tree.
Parameters
QHash<QString
_newMapValues
_domTree
Definition at line 312 of file solverconfigreader.cpp.
Referenced by SolverConfigManager::updateDOMTree().
 {
     QHash<QString, QString>::iterator _iter;
     if( (!_newMapValues.empty()) && (!_domTree->isNull()))
     {
         for (_iter = _newMapValues.begin(); _iter != _newMapValues.end();++_iter)
         {
             // Get the root element
             QString _varName = _iter.key();
             QString _newValue = _iter.value();
             changeValueElement(_varName, _newValue,_domTree);
         }
     }
 }
void SolverConfigReader::updateValueElement (QString _valueName, QString _newValue, QDomDocument * _domTree)
Function tha update the value elements in the Dom TREE.
Parameters
_valueName
_newValue
_domTree
Definition at line 298 of file solverconfigreader.cpp.
 {
     changeValueElement(_valueName,_newValue,_domTree);
 }
The documentation for this class was generated from the following files:
Solver/solverconfigreader.h
Solver/solverconfigreader.cpp