BBIPED Platform: VirtualCurveDialog Class Reference
VirtualCurveDialog Class Reference
#include <virtualcurvedialog.h>
Public Member Functions
VirtualCurveDialog (QWidget *parent=0)
~VirtualCurveDialog ()
QStringList getInnerValues ()
QStringList getOuterValues ()
bool hasUserModifiedValues ()
void initializeDialog ()
bool is3DCoordinates ()
void set3DCoordinates (bool _val)
void setInnerValues (QStringList _list)
void setOuterValues (QStringList _list)
void setSolverSection (SolverSectionVO _var)
Private Types
enum ColumnValues
enum UpdateOption
Private Slots
void on_acceptButton_clicked ()
void on_cancelButton_clicked ()
void on_innerButtonHelp_clicked ()
void on_innerCurveSpinBox_valueChanged (int arg1)
void on_outerButtonHelp_clicked ()
void on_outerCurvespinBox_valueChanged (int arg1)
void on_selectedDimension_currentIndexChanged (const QString &arg1)
void textChangedSlot2D (QString _tableName)
Private Member Functions
QString addItemToTable (QTableWidget *_table, int _row, int _col)
void addRow (int _rowPos, QTableWidget *_table, QString _valueX, QString _valueY)
void addSignals2D (int _column, QString _tableName)
void deleteRow (int _rowPos, QTableWidget *_table)
void fillTable (QTableWidget *_table, QStringList _listVal)
void generateHelpDialog (int _helpPos)
void rowAddRemoveSpinBox (int _noZones, QTableWidget *_table)
void updateUserValues (int _option)
Private Attributes
QStringList _innerValues
bool _is3DCoordinates
QStringList _outerValues
QSignalMapper * _signalMapperTxtEdit
SolverSectionVO _solverSection
bool _userAcceptChanges
Ui::VirtualCurveDialog * ui
Detailed Description
Definition at line 15 of file virtualcurvedialog.h.
Member Enumeration Documentation
enum VirtualCurveDialog::ColumnValues private
Enumerator
Column_X_Value
Column_Y_Value
Column_Z_Value
Definition at line 62 of file virtualcurvedialog.h.
                      {
         Column_X_Value=0,
         Column_Y_Value = 1,
         Column_Z_Value = 2
     };
enum VirtualCurveDialog::UpdateOption private
Enumerator
UpdateInnerCurveVal
UpdateOuterCurveVal
Definition at line 69 of file virtualcurvedialog.h.
                      {
         UpdateInnerCurveVal=0,
         UpdateOuterCurveVal = 1
     };
Constructor & Destructor Documentation
VirtualCurveDialog::VirtualCurveDialog (QWidget * parent = 0) explicit
Parameters
parent
Definition at line 34 of file virtualcurvedialog.cpp.
References _is3DCoordinates, _signalMapperTxtEdit, _userAcceptChanges, and ui.
                                                       :
     QDialog(parent),
     ui(new Ui::VirtualCurveDialog)
 {
     ui->setupUi(this);
     _userAcceptChanges = false;
     _is3DCoordinates = false;
     _signalMapperTxtEdit = new QSignalMapper(this);
 }
VirtualCurveDialog::~VirtualCurveDialog ()
Definition at line 48 of file virtualcurvedialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
QString VirtualCurveDialog::addItemToTable (QTableWidget * _table, int _row, int _col) private
Parameters
_table
_row
_col
Returns
QString
Definition at line 189 of file virtualcurvedialog.cpp.
Referenced by updateUserValues().
 {
     QString _value("");
     QLineEdit * _item = qobject_cast<QLineEdit *> ( _table->cellWidget(_row,_col));
     if (_item)
         _value = _item->text();
     else
     {
         QTableWidgetItem * _item = _table->item(_row,_col);
         if (_item)
             _value = _item->text();
     }
     return _value;
 }
void VirtualCurveDialog::addRow (int _rowPos, QTableWidget * _table, QString _valueX, QString _valueY) private
Parameters
_rowPos
_table
_valueX
_valueY
_valueZ
Definition at line 313 of file virtualcurvedialog.cpp.
References _is3DCoordinates, QtableUtil::addEditText(), QtableUtil::addNonEditableText(), Column_X_Value, and Column_Y_Value.
Referenced by fillTable(), and rowAddRemoveSpinBox().
 {
     QtableUtil _tableHelper;
     _table->blockSignals(true);
     _table->insertRow(_rowPos);
     if (!_is3DCoordinates)
         _table->setItem(_rowPos,Column_X_Value,_tableHelper.addNonEditableText(_valueX));
     else
         _table->setCellWidget(_rowPos,Column_X_Value,_tableHelper.addEditText(_valueX));
     if ((!_is3DCoordinates) && (_rowPos==1))
         _table->setItem(_rowPos,Column_Y_Value,_tableHelper.addNonEditableText(_valueY));
     else
         _table->setCellWidget(_rowPos,Column_Y_Value,_tableHelper.addEditText(_valueY));
     _table->blockSignals(false);
  /*   if (_is3DCoordinates)
         _table->setCellWidget(_rowPos,Column_Z_Value,_tableHelper.addEditText(_valueZ));
     else
         _table->setItem(_rowPos,Column_Z_Value,_tableHelper.addNonEditableText(""));
         */
 }
void VirtualCurveDialog::addSignals2D (int _column, QString _tableName) private
Definition at line 119 of file virtualcurvedialog.cpp.
References _signalMapperTxtEdit, INNER_TABLE, OUTER_TABLE, StrEqual, textChangedSlot2D(), and ui.
Referenced by initializeDialog().
 {
     bool _foundLineEdit = false;
     QTableWidget * _table;
     if (QString::compare(_tableName,INNER_TABLE) == StrEqual)
         _table = ui->innerTable;
     if (QString::compare(_tableName,OUTER_TABLE) == StrEqual)
         _table = ui->outerTable;
     if (_table->rowCount() == 0)
         return;
     int _initialRow = 0;
     QWidget * _item;
     _item = _table->cellWidget(_initialRow,_column);
     QLineEdit * _lineEdit = qobject_cast<QLineEdit *> (_item);
     if (_lineEdit)
     {
         connect(_lineEdit,SIGNAL(editingFinished()),_signalMapperTxtEdit,SLOT(map()),Qt::UniqueConnection);
         _signalMapperTxtEdit->setMapping(_lineEdit,_tableName);
         _foundLineEdit = true;
     }
     if (_foundLineEdit)
         connect(_signalMapperTxtEdit, SIGNAL(mapped(const QString &)),this, SLOT(textChangedSlot2D(const QString &)),Qt::UniqueConnection);
 }
void VirtualCurveDialog::deleteRow (int _rowPos, QTableWidget * _table) private
Parameters
_rowPos
_table
Definition at line 379 of file virtualcurvedialog.cpp.
Referenced by rowAddRemoveSpinBox().
 {
     _table->removeRow(_rowPos);
 }
void VirtualCurveDialog::fillTable (QTableWidget * _table, QStringList _listVal) private
Parameters
_table
_listVal
Definition at line 105 of file virtualcurvedialog.cpp.
References addRow().
Referenced by initializeDialog().
 {
     int _dimension = 2;
     int _totalRows = 0;
     _totalRows = _listVal.size()/_dimension;
     for (int i = 0; i < _totalRows; i++)
     {
         int _cPos=i*_dimension;
         addRow(i,_table,_listVal.at(_cPos),_listVal.at(_cPos+1)); // TODO --- Hay que pasarle los valores X e Y
     }
 }
void VirtualCurveDialog::generateHelpDialog (int _helpPos) private
Parameters
_helpPos
Definition at line 422 of file virtualcurvedialog.cpp.
References _solverSection, SolverVariableVO::getHelpContents(), SolverSectionVO::getSubsectionVarList(), HTML_FORMAT_ON, HelpDialog::loadHelpText(), and HelpDialog::setHelpText().
Referenced by on_innerButtonHelp_clicked(), and on_outerButtonHelp_clicked().
 {
     QList<SolverVariableVO> _infoVarVO = _solverSection.getSubsectionVarList();
     if (_infoVarVO.isEmpty())
         return;
     if (_helpPos >= _infoVarVO.size())
         return;
     SolverVariableVO _varGeneralInfo =  _infoVarVO.at(_helpPos);
     QString _helpText = _varGeneralInfo.getHelpContents(HTML_FORMAT_ON);
     HelpDialog *  _helpDialog = new HelpDialog();
      _helpDialog->setHelpText(_helpText);
      _helpDialog->loadHelpText();
      _helpDialog->exec();
 }
QStringList VirtualCurveDialog::getInnerValues ()
Returns
QStringList
Definition at line 481 of file virtualcurvedialog.cpp.
References _innerValues.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     return _innerValues;
 }
QStringList VirtualCurveDialog::getOuterValues ()
Returns
QStringList
Definition at line 501 of file virtualcurvedialog.cpp.
References _outerValues.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     return _outerValues;
 }
bool VirtualCurveDialog::hasUserModifiedValues ()
Returns
bool
Definition at line 510 of file virtualcurvedialog.cpp.
References _userAcceptChanges.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     return _userAcceptChanges;
 }
void VirtualCurveDialog::initializeDialog ()
Definition at line 58 of file virtualcurvedialog.cpp.
References _innerValues, _is3DCoordinates, _outerValues, addSignals2D(), Column_Y_Value, fillTable(), INNER_TABLE, OUTER_TABLE, and ui.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     if (!_innerValues.isEmpty())
     {
         fillTable(ui->innerTable,_innerValues);
         if (!_is3DCoordinates)
           addSignals2D(Column_Y_Value,INNER_TABLE);
         // Updating the counters
         ui->innerCurveSpinBox->blockSignals(true);
         ui->innerCurveSpinBox->setValue(ui->innerTable->rowCount());
         ui->innerCurveSpinBox->blockSignals(false);
     }
     if (!_outerValues.isEmpty())
     {
       fillTable(ui->outerTable,_outerValues);
       if (!_is3DCoordinates)
         addSignals2D(Column_Y_Value,OUTER_TABLE);
       // Updating the counters
       ui->outerCurvespinBox->blockSignals(true);
       ui->outerCurvespinBox->setValue(ui->outerTable->rowCount());
       ui->outerCurvespinBox->blockSignals(false);
     }
     if (_is3DCoordinates)
     {
         ui->selectedDimension->blockSignals(true);
         ui->selectedDimension->setCurrentIndex(1);
         ui->selectedDimension->blockSignals(false);
     }else
     {
         ui->innerCurveSpinBox->setEnabled(false);
         ui->outerCurvespinBox->setEnabled(false);
     }
 }
bool VirtualCurveDialog::is3DCoordinates ()
Returns
bool
Definition at line 461 of file virtualcurvedialog.cpp.
References _is3DCoordinates.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     return _is3DCoordinates;
 }
void VirtualCurveDialog::on_acceptButton_clicked () private slot
Definition at line 167 of file virtualcurvedialog.cpp.
References _userAcceptChanges, UpdateInnerCurveVal, UpdateOuterCurveVal, and updateUserValues().
 {
     _userAcceptChanges = true;
     // Update the values of INNER curve
     updateUserValues(UpdateInnerCurveVal);
     // Update the values of OUTER curve
     updateUserValues(UpdateOuterCurveVal);
     close();
 }
void VirtualCurveDialog::on_cancelButton_clicked () private slot
Definition at line 255 of file virtualcurvedialog.cpp.
References _innerValues, _outerValues, and _userAcceptChanges.
 {
     _userAcceptChanges = false;
     _innerValues.clear();
     _outerValues.clear();
     close();
 }
void VirtualCurveDialog::on_innerButtonHelp_clicked () private slot
Definition at line 402 of file virtualcurvedialog.cpp.
References generateHelpDialog().
 {
     generateHelpDialog(1);
 }
void VirtualCurveDialog::on_innerCurveSpinBox_valueChanged (int arg1) private slot
Parameters
arg1
Definition at line 268 of file virtualcurvedialog.cpp.
References rowAddRemoveSpinBox(), and ui.
 {
     rowAddRemoveSpinBox(arg1,ui->innerTable);
 }
void VirtualCurveDialog::on_outerButtonHelp_clicked () private slot
Definition at line 412 of file virtualcurvedialog.cpp.
References generateHelpDialog().
 {
    generateHelpDialog(2);
 }
void VirtualCurveDialog::on_outerCurvespinBox_valueChanged (int arg1) private slot
Parameters
arg1
Definition at line 300 of file virtualcurvedialog.cpp.
References rowAddRemoveSpinBox(), and ui.
 {
     rowAddRemoveSpinBox(arg1,ui->outerTable);
 }
void VirtualCurveDialog::on_selectedDimension_currentIndexChanged (const QString & arg1) private slot
Parameters
arg1
Definition at line 389 of file virtualcurvedialog.cpp.
References _is3DCoordinates, and StrEqual.
 {
     if (QString::compare(arg1,"3D") == StrEqual)
         _is3DCoordinates = true;
     else
         _is3DCoordinates = false;
     //updateUserDataInTable();
 }
void VirtualCurveDialog::rowAddRemoveSpinBox (int _noZones, QTableWidget * _table) private
Definition at line 273 of file virtualcurvedialog.cpp.
References addRow(), and deleteRow().
Referenced by on_innerCurveSpinBox_valueChanged(), and on_outerCurvespinBox_valueChanged().
 {
     int _totalRows = _table->rowCount();
     int _newZoneNo = _noZones;
     int _cZoneNo = _totalRows;
     if (_newZoneNo > _cZoneNo) // We need to add new rows
     {
         int _noNewRows = _newZoneNo - _cZoneNo;
         for (int i = 0;i < _noNewRows;i++)
             addRow(_cZoneNo+i,_table,"","");
     }
     else{
         if (_newZoneNo < _cZoneNo) // We need to delete rows
         {
             int _noDeletedRows = _cZoneNo -_newZoneNo;
             for (int i = 0; i <= _noDeletedRows;i++)
                 deleteRow(_totalRows - i,_table);
         }
     }
 }
void VirtualCurveDialog::set3DCoordinates (bool _val)
Parameters
_val
Definition at line 452 of file virtualcurvedialog.cpp.
References _is3DCoordinates.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     _is3DCoordinates = _val;
 }
void VirtualCurveDialog::setInnerValues (QStringList _list)
Parameters
_list
Definition at line 471 of file virtualcurvedialog.cpp.
References _innerValues.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     _innerValues = _list;
 }
void VirtualCurveDialog::setOuterValues (QStringList _list)
Parameters
_list
Definition at line 491 of file virtualcurvedialog.cpp.
References _outerValues.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     _outerValues = _list;
 }
void VirtualCurveDialog::setSolverSection (SolverSectionVO _var)
Parameters
_var
Definition at line 441 of file virtualcurvedialog.cpp.
References _solverSection.
Referenced by VirtualRotatingDialog::launchCurveDialog().
 {
     _solverSection = _var;
 }
void VirtualCurveDialog::textChangedSlot2D (QString _tableName) private slot
Definition at line 146 of file virtualcurvedialog.cpp.
References Column_Y_Value, INNER_TABLE, OUTER_TABLE, StrEqual, and ui.
Referenced by addSignals2D().
 {
     QTableWidget * _table;
     if (QString::compare(_tableName,INNER_TABLE) == StrEqual)
         _table = ui->innerTable;
     if (QString::compare(_tableName,OUTER_TABLE) == StrEqual)
         _table = ui->outerTable;
     int _totalRows = _table->rowCount();
     if (_totalRows != 2)
         return;
     int _rowToCopy = 0;
     QLineEdit * _firstElement = (QLineEdit *) _table->cellWidget(_rowToCopy,Column_Y_Value);
     QString _value = _firstElement->text();
     // Copy the value to the second row
     _table->item(_rowToCopy+1,Column_Y_Value)->setText(_value);
 }
void VirtualCurveDialog::updateUserValues (int _option) private
Parameters
_option
Definition at line 209 of file virtualcurvedialog.cpp.
References _innerValues, _outerValues, addItemToTable(), Column_X_Value, Column_Y_Value, ui, UpdateInnerCurveVal, and UpdateOuterCurveVal.
Referenced by on_acceptButton_clicked().
 {
     int _totalRows = 0;
     QTableWidget * _table;
     if (_option == UpdateInnerCurveVal)
     {
         _innerValues.clear();
         _totalRows = ui->innerTable->rowCount();
         _table = ui->innerTable;
     }else{
         if (_option == UpdateOuterCurveVal)
         {
             _outerValues.clear();
             _totalRows = ui->outerTable->rowCount();
             _table = ui->outerTable;
         }
     }
     for (int i = 0; i < _totalRows; i++)
     {
         QString _valueX = addItemToTable(_table,i,Column_X_Value);
         QString _valueY = addItemToTable(_table,i,Column_Y_Value);
         if ( (!_valueX.isNull()) && (!_valueX.isEmpty()) && (!_valueY.isNull()) && (!_valueY.isEmpty()))
         {
             if (_option == UpdateInnerCurveVal)
             {
                 _innerValues.append(_valueX);
                 _innerValues.append(_valueY);
             }else
                 if (_option == UpdateOuterCurveVal)
                 {
                     _outerValues.append(_valueX);
                     _outerValues.append(_valueY);
                 }
         }
     }
 }
Member Data Documentation
QStringList VirtualCurveDialog::_innerValues private
Definition at line 55 of file virtualcurvedialog.h.
Referenced by getInnerValues(), initializeDialog(), on_cancelButton_clicked(), setInnerValues(), and updateUserValues().
bool VirtualCurveDialog::_is3DCoordinates private
Definition at line 58 of file virtualcurvedialog.h.
Referenced by addRow(), initializeDialog(), is3DCoordinates(), on_selectedDimension_currentIndexChanged(), set3DCoordinates(), and VirtualCurveDialog().
QStringList VirtualCurveDialog::_outerValues private
Definition at line 56 of file virtualcurvedialog.h.
Referenced by getOuterValues(), initializeDialog(), on_cancelButton_clicked(), setOuterValues(), and updateUserValues().
QSignalMapper* VirtualCurveDialog::_signalMapperTxtEdit private
Definition at line 60 of file virtualcurvedialog.h.
Referenced by addSignals2D(), and VirtualCurveDialog().
SolverSectionVO VirtualCurveDialog::_solverSection private
Definition at line 59 of file virtualcurvedialog.h.
Referenced by generateHelpDialog(), and setSolverSection().
bool VirtualCurveDialog::_userAcceptChanges private
Definition at line 57 of file virtualcurvedialog.h.
Referenced by hasUserModifiedValues(), on_acceptButton_clicked(), on_cancelButton_clicked(), and VirtualCurveDialog().
Ui::VirtualCurveDialog* VirtualCurveDialog::ui private
Definition at line 54 of file virtualcurvedialog.h.
Referenced by addSignals2D(), initializeDialog(), on_innerCurveSpinBox_valueChanged(), on_outerCurvespinBox_valueChanged(), textChangedSlot2D(), updateUserValues(), VirtualCurveDialog(), and ~VirtualCurveDialog().
The documentation for this class was generated from the following files:
Forms/VirtualRotatingDialog/virtualcurvedialog.h
Forms/VirtualRotatingDialog/virtualcurvedialog.cpp