BBIPED Platform: SolverResidualVO Class Reference
SolverResidualVO Class Reference
#include <solverresidualvo.h>
Public Member Functions
SolverResidualVO ()
Constructor.
void clearAllData ()
Clear all the data.
void enableAllValues ()
Restore all values visibility to true.
void fillValues (QStringList _list)
This function allows to fill in the Residual object according to the values stored in _list and their visibility.
double getCDragTotal ()
Return CDrag Total.
double getCliftTotal ()
Return Clift Total.
bool getCliftTotalEnabled ()
Returns if the Clift Total will appear in the graphic (true, false otherwise)
bool getDragTotalEnabled ()
Returns if the Drag Total will appear in the graphic (true, false otherwise)
int getIteration ()
return Number of iteration
bool getIterationEnabled ()
Returns if the Iteration will appear in the graphic (true, false otherwise)
double getResRho ()
Return ResRho.
double getResRhoe ()
Return ResRhoe.
bool getResRhoeEnabled ()
Returns if the ResRhoe will appear in the graphic (true, false otherwise)
bool getResRhoEnabled ()
Returns if the ResRho will appear in the graphic (true, false otherwise)
bool getTimeEnabled ()
Returns if the Time will appear in the graphic (true, false otherwise)
double getTimeValue ()
Return time Value.
void setCDragTotal (double _newVal)
Set CDrag Total.
void setCliftTotal (double _newVal)
Set Clift Total.
void setCliftTotalEnabled (bool _val)
Set if the CliftTotal will appear in the graphic (true, false otherwise)
void setDragTotalEnabled (bool _val)
Set if the Drag Total will appear in the graphic (true, false otherwise)
void setIteration (int _newIteration)
Set number of iteration.
void setIterationEnabled (bool _val)
Set if the iteration no. will appear in the graphic (true, false otherwise)
void setResRho (double _newVal)
Set ResRho.
void setResRhoe (double _newVal)
Set ResRhoe.
void setResRhoeEnabled (bool _val)
Set if the ResRhoe will appear in the graphic (true, false otherwise)
void setResRhoEnabled (bool _val)
Set if the ResRho will appear in the graphic (true, false otherwise)
void setTimeEnabled (bool _val)
Set if the time will appear in the graphic (true, false otherwise)
void setTimeValue (double _newVal)
set Time Val
Private Attributes
double _cDragTotal
bool _cDragTotalEnabled
double _cliftTotal
bool _cliftTotalEnabled
int _iteration
bool _iterationEnabled
double _resRho
double _resRhoe
bool _resRhoeEnabled
bool _resRhoEnabled
double _time
bool _timeEnabled
Detailed Description
Definition at line 6 of file solverresidualvo.h.
Constructor & Destructor Documentation
SolverResidualVO::SolverResidualVO ()
Constructor.
Definition at line 24 of file solverresidualvo.cpp.
References _cDragTotal, _cDragTotalEnabled, _cliftTotal, _cliftTotalEnabled, _iteration, _iterationEnabled, _resRho, _resRhoe, _resRhoeEnabled, _resRhoEnabled, _time, and _timeEnabled.
 {
     _iteration = 0;
     _time = 0;
     _resRho = 0;
     _resRhoe = 0;
     _cDragTotal = 0;
     _cliftTotal = 0;
     _iterationEnabled = true;
     _timeEnabled = true;
     _resRhoEnabled = true;
     _resRhoeEnabled = true;
     _cliftTotalEnabled = true;
     _cDragTotalEnabled = true;
 }
Member Function Documentation
void SolverResidualVO::clearAllData ()
Clear all the data.
Definition at line 369 of file solverresidualvo.cpp.
References _cDragTotalEnabled, _cliftTotalEnabled, _iterationEnabled, _resRhoeEnabled, _resRhoEnabled, _timeEnabled, setCDragTotal(), setCliftTotal(), setIteration(), setResRho(), setResRhoe(), and setTimeValue().
Referenced by MainWindow::closeProject(), MainWindow::on_restartButton_clicked(), and MainWindow::runSolverProject().
 {
     this->setIteration(0);
     this->setTimeValue(0);
     this->setResRho(0);
     this->setResRhoe(0);
     this->setCliftTotal(0);
     this->setCDragTotal(0);
     this->_iterationEnabled  = true;
     this->_timeEnabled = true;
     this->_resRhoEnabled = true;
     this->_resRhoeEnabled = true;
     this->_cliftTotalEnabled = true;
     this->_cDragTotalEnabled = true;
 }
void SolverResidualVO::enableAllValues ()
Restore all values visibility to true.
Definition at line 354 of file solverresidualvo.cpp.
References setCliftTotalEnabled(), setDragTotalEnabled(), setIterationEnabled(), setResRhoeEnabled(), setResRhoEnabled(), and setTimeEnabled().
Referenced by OutputSolverParser::identifyNoElementsToPlot().
 {
     setIterationEnabled(true);
     setTimeEnabled(true);
     setResRhoEnabled(true);
     setResRhoeEnabled(true);
     setCliftTotalEnabled(true);
     setDragTotalEnabled(true);
 }
void SolverResidualVO::fillValues (QStringList _list)
This function allows to fill in the Residual object according to the values stored in _list and their visibility.
Parameters
_list
Definition at line 306 of file solverresidualvo.cpp.
References _cDragTotalEnabled, _cliftTotalEnabled, _iterationEnabled, _resRhoeEnabled, _resRhoEnabled, _timeEnabled, setCDragTotal(), setCliftTotal(), setIteration(), setResRho(), setResRhoe(), and setTimeValue().
Referenced by OutputSolverParser::fillResidualObject().
 {
     if (!_list.isEmpty())
     {
         int _posList = 0;
         if (!_list.contains("Negative"))
            {
                 if  (_iterationEnabled)
                 {
                    this->setIteration(_list.at(_posList).toInt());
                     _posList++;
                 }
                 if  (_timeEnabled)
                 {
                    this->setTimeValue(_list.at(_posList).toDouble());
                     _posList++;
                 }
                 if  (_resRhoEnabled)
                 {
                    this->setResRho(_list.at(_posList).toDouble());
                     _posList++;
                 }
                 if  (_resRhoeEnabled)
                 {
                    this->setResRhoe(_list.at(_posList).toDouble());
                     _posList++;
                 }
                 if  (_cliftTotalEnabled)
                 {
                    this->setCliftTotal(_list.at(_posList).toDouble());
                     _posList++;
                 }
                 if  (_cDragTotalEnabled)
                 {
                    this->setCDragTotal(_list.at(_posList).toDouble());
                     _posList++;
                 }
            }
     }
 }
double SolverResidualVO::getCDragTotal ()
Return CDrag Total.
Returns
double
Definition at line 88 of file solverresidualvo.cpp.
References _cDragTotal.
 {
     return _cDragTotal;
 }
double SolverResidualVO::getCliftTotal ()
Return Clift Total.
Returns
double
Definition at line 78 of file solverresidualvo.cpp.
References _cliftTotal.
 {
     return _cliftTotal;
 }
bool SolverResidualVO::getCliftTotalEnabled ()
Returns if the Clift Total will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 283 of file solverresidualvo.cpp.
References _cliftTotalEnabled.
Referenced by OutputSolverParser::checkNanValues(), and OutputSolverParser::getValidElementsToPrint().
 {
     return _cliftTotalEnabled;
 }
bool SolverResidualVO::getDragTotalEnabled ()
Returns if the Drag Total will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 294 of file solverresidualvo.cpp.
References _cDragTotalEnabled.
Referenced by OutputSolverParser::checkNanValues(), and OutputSolverParser::getValidElementsToPrint().
 {
     return _cDragTotalEnabled;
 }
int SolverResidualVO::getIteration ()
return Number of iteration
Returns
int
Definition at line 152 of file solverresidualvo.cpp.
References _iteration.
Referenced by ResidualTabHelper::showPlot(), and SolverPlotter::showPoints().
 {
     return _iteration;
 }
bool SolverResidualVO::getIterationEnabled ()
Returns if the Iteration will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 237 of file solverresidualvo.cpp.
References _iterationEnabled.
Referenced by OutputSolverParser::checkNanValues(), and OutputSolverParser::getValidElementsToPrint().
 {
     return _iterationEnabled;
 }
double SolverResidualVO::getResRho ()
Return ResRho.
Returns
double
Definition at line 58 of file solverresidualvo.cpp.
References _resRho.
Referenced by SolverPlotter::showPoints().
 {
     return _resRho;
 }
double SolverResidualVO::getResRhoe ()
Return ResRhoe.
Returns
double
Definition at line 68 of file solverresidualvo.cpp.
References _resRhoe.
Referenced by SolverPlotter::showPoints().
 {
    return _resRhoe;
 }
bool SolverResidualVO::getResRhoeEnabled ()
Returns if the ResRhoe will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 271 of file solverresidualvo.cpp.
References _resRhoeEnabled.
Referenced by OutputSolverParser::checkNanValues(), OutputSolverParser::getValidElementsToPrint(), SolverPlotter::resetLegend(), SolverPlotter::showPoints(), and SolverPlotter::updateLegendItemsInGraphic().
 {
     return _resRhoeEnabled;
 }
bool SolverResidualVO::getResRhoEnabled ()
Returns if the ResRho will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 260 of file solverresidualvo.cpp.
References _resRhoEnabled.
Referenced by OutputSolverParser::checkNanValues(), OutputSolverParser::getValidElementsToPrint(), SolverPlotter::resetLegend(), SolverPlotter::showPoints(), and SolverPlotter::updateLegendItemsInGraphic().
 {
     return _resRhoEnabled;
 }
bool SolverResidualVO::getTimeEnabled ()
Returns if the Time will appear in the graphic (true, false otherwise)
Returns
bool
Definition at line 249 of file solverresidualvo.cpp.
References _timeEnabled.
Referenced by OutputSolverParser::checkNanValues(), and OutputSolverParser::getValidElementsToPrint().
 {
     return _timeEnabled;
 }
double SolverResidualVO::getTimeValue ()
Return time Value.
Returns
double
Definition at line 48 of file solverresidualvo.cpp.
References _time.
 {
     return _time;
 }
void SolverResidualVO::setCDragTotal (double _newVal)
Set CDrag Total.
Parameters
_newVal
Definition at line 141 of file solverresidualvo.cpp.
References _cDragTotal.
Referenced by clearAllData(), and fillValues().
 {
     _cDragTotal = _newVal;
 }
void SolverResidualVO::setCliftTotal (double _newVal)
Set Clift Total.
Parameters
_newVal
Definition at line 130 of file solverresidualvo.cpp.
References _cliftTotal.
Referenced by clearAllData(), and fillValues().
 {
     _cliftTotal = _newVal;
 }
void SolverResidualVO::setCliftTotalEnabled (bool _val)
Set if the CliftTotal will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 215 of file solverresidualvo.cpp.
References _cliftTotalEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
     _cliftTotalEnabled = _val;
 }
void SolverResidualVO::setDragTotalEnabled (bool _val)
Set if the Drag Total will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 225 of file solverresidualvo.cpp.
References _cDragTotalEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
    _cDragTotalEnabled = _val;
 }
void SolverResidualVO::setIteration (int _newIteration)
Set number of iteration.
Parameters
_newIteration
Definition at line 162 of file solverresidualvo.cpp.
References _iteration.
Referenced by clearAllData(), and fillValues().
 {
     _iteration = _newIteration;
 }
void SolverResidualVO::setIterationEnabled (bool _val)
Set if the iteration no. will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 173 of file solverresidualvo.cpp.
References _iterationEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
     _iterationEnabled = _val;
 }
void SolverResidualVO::setResRho (double _newVal)
Set ResRho.
Parameters
_newVal
Definition at line 108 of file solverresidualvo.cpp.
References _resRho.
Referenced by clearAllData(), and fillValues().
 {
     _resRho = _newVal;
 }
void SolverResidualVO::setResRhoe (double _newVal)
Set ResRhoe.
Parameters
_newVal
Definition at line 119 of file solverresidualvo.cpp.
References _resRhoe.
Referenced by clearAllData(), and fillValues().
 {
     _resRhoe = _newVal;
 }
void SolverResidualVO::setResRhoeEnabled (bool _val)
Set if the ResRhoe will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 205 of file solverresidualvo.cpp.
References _resRhoeEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
     _resRhoeEnabled = _val;
 }
void SolverResidualVO::setResRhoEnabled (bool _val)
Set if the ResRho will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 195 of file solverresidualvo.cpp.
References _resRhoEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
     _resRhoEnabled = _val;
 }
void SolverResidualVO::setTimeEnabled (bool _val)
Set if the time will appear in the graphic (true, false otherwise)
Parameters
_val
Definition at line 184 of file solverresidualvo.cpp.
References _timeEnabled.
Referenced by OutputSolverParser::checkNanValues(), enableAllValues(), and OutputSolverParser::identifyNoElementsToPlot().
 {
     _timeEnabled = _val;
 }
void SolverResidualVO::setTimeValue (double _newVal)
set Time Val
Parameters
_newVal
Definition at line 98 of file solverresidualvo.cpp.
References _time.
Referenced by clearAllData(), and fillValues().
 {
     _time = _newVal;
 }
Member Data Documentation
double SolverResidualVO::_cDragTotal private
Definition at line 49 of file solverresidualvo.h.
Referenced by getCDragTotal(), setCDragTotal(), and SolverResidualVO().
bool SolverResidualVO::_cDragTotalEnabled private
Definition at line 55 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getDragTotalEnabled(), setDragTotalEnabled(), and SolverResidualVO().
double SolverResidualVO::_cliftTotal private
Definition at line 48 of file solverresidualvo.h.
Referenced by getCliftTotal(), setCliftTotal(), and SolverResidualVO().
bool SolverResidualVO::_cliftTotalEnabled private
Definition at line 54 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getCliftTotalEnabled(), setCliftTotalEnabled(), and SolverResidualVO().
int SolverResidualVO::_iteration private
Definition at line 44 of file solverresidualvo.h.
Referenced by getIteration(), setIteration(), and SolverResidualVO().
bool SolverResidualVO::_iterationEnabled private
Definition at line 50 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getIterationEnabled(), setIterationEnabled(), and SolverResidualVO().
double SolverResidualVO::_resRho private
Definition at line 46 of file solverresidualvo.h.
Referenced by getResRho(), setResRho(), and SolverResidualVO().
double SolverResidualVO::_resRhoe private
Definition at line 47 of file solverresidualvo.h.
Referenced by getResRhoe(), setResRhoe(), and SolverResidualVO().
bool SolverResidualVO::_resRhoeEnabled private
Definition at line 53 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getResRhoeEnabled(), setResRhoeEnabled(), and SolverResidualVO().
bool SolverResidualVO::_resRhoEnabled private
Definition at line 52 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getResRhoEnabled(), setResRhoEnabled(), and SolverResidualVO().
double SolverResidualVO::_time private
Definition at line 45 of file solverresidualvo.h.
Referenced by getTimeValue(), setTimeValue(), and SolverResidualVO().
bool SolverResidualVO::_timeEnabled private
Definition at line 51 of file solverresidualvo.h.
Referenced by clearAllData(), fillValues(), getTimeEnabled(), setTimeEnabled(), and SolverResidualVO().
The documentation for this class was generated from the following files:
Data/Solver/VO/solverresidualvo.h
Data/Solver/VO/solverresidualvo.cpp