BBIPED Platform: TemplateDialog Class Reference
TemplateDialog Class Reference
#include <templatedialog.h>
Public Member Functions
TemplateDialog (QWidget *parent=0)
Constructor.
~TemplateDialog ()
Destructor.
void loadTemplate ()
Load all teh values of the template.
void setSolverConfigManager (SolverConfigManager *_solverManagerData)
Function that sets the Solver Config manager to set the Menu List to be used.
Private Types
enum ColumnNo
enum ColumnSelectedVar
Private Slots
void keyPressEvent (QKeyEvent *evt)
This function controls the events of the key pressed.
void on_buttonBox_accepted ()
This function controls the acceptance by the user.
void on_clearSearchButton_clicked ()
This function controls the clear search functionality.
void on_searchButton_clicked ()
This function controls the search functionality.
void on_searchLineEdit_returnPressed ()
This function controls the search functionality on key pressed.
void on_selectedVariablesTableWidget_cellClicked (int row, int column)
This function controls the behaviour over clicking in the cells of the selected var table.
void on_variablesToSelectTableWidget_cellChanged (int row, int column)
Slot function that controls those variables that have been selected.
void on_variablesToSelectTableWidget_cellClicked (int row, int column)
void on_variablesToSelectTree_clicked (const QModelIndex &index)
This function controls when a menu item is clicked on the tree to show teh associated variables.
Private Member Functions
void addVariable (SolverSectionVO _section)
Adds a variable to the table.
void addVariableToTable (SolverVariableVO _variable, int _row)
Function that adds the variable elements to each row in the table.
void addVariableToTable (QString _name, QString _subsectionName)
This function adds to the selected var table, the variable of the selection table.
void disableVariableInTableToSelect (QString _varName)
This function unchecks teh variable status in the selection table.
void fillMenuTable (QString _parentName, QList< SolverVariableVO > _list)
This function fills the menu table.
void fillTableVarToSelect (QString _parentSelected, QString _childSelected)
This function loads the table for a specific menu item.
void initializeHelpers ()
This function initialize the helpers.
void initializeTableHeaders ()
This function initialize the table headers.
void initializeVariables ()
This function initialize the variables.
void loadHelp (QString _helpText)
This function loads the help dialog.
void loadMenu ()
This function loads teh menu list.
void refreshSelectVarTable (bool _addVar, QString _variableName)
This function refresh the table of selected variables.
void removeVariableFromTable (QString _name)
This function remove a variaable from the selected var table.
void resetTable (QTableWidget *_table)
This function resets the table.
void setMenuList (QDomDocument *_menu)
This function sets the menu list.
void updateSelectedVariableCheckBox (SolverSectionVO _sectionVO)
This funtion updates the values of a selected variable.
Private Attributes
bool _isLoadingTable
SearchPairHelper _searcherHelper
QString _selectedMenu
QHash< QString, QString > _selectedVariables
SolverConfigManager * _solverManager
bool _userHasMadeChanges
QDomDocument * _variablesMenuToShow
Ui::TemplateDialog * ui
Detailed Description
Definition at line 21 of file templatedialog.h.
Member Enumeration Documentation
enum TemplateDialog::ColumnNo private
Enumerator
ColNoVarToSelect
ColNoVarSelected
Definition at line 59 of file templatedialog.h.
                  {
         ColNoVarToSelect = 3,
         ColNoVarSelected = 4
     };
enum TemplateDialog::ColumnSelectedVar private
Enumerator
SelectedColSectionName
SelectedColVariableName
SelectedColHelp
SelectedColDelete
Definition at line 63 of file templatedialog.h.
{
         SelectedColSectionName = 0,
         SelectedColVariableName = 1,
         SelectedColHelp = 2,
         SelectedColDelete = 3
     };
Constructor & Destructor Documentation
TemplateDialog::TemplateDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 38 of file templatedialog.cpp.
References initializeHelpers(), initializeTableHeaders(), initializeVariables(), and ui.
                                               :
     QDialog(parent),
     ui(new Ui::TemplateDialog)
 {
     ui->setupUi(this);
     initializeTableHeaders();
     initializeVariables();
     initializeHelpers();
 }
TemplateDialog::~TemplateDialog ()
Destructor.
Definition at line 52 of file templatedialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void TemplateDialog::addVariable (SolverSectionVO _section) private
Adds a variable to the table.
Parameters
_section
Definition at line 77 of file templatedialog.cpp.
References _selectedVariables, addVariableToTable(), SolverSectionVO::getSubsectionName(), SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableName(), and ui.
Referenced by loadTemplate().
 {
     QString _subsectionName = _section.getSubsectionName();
     QList<SolverVariableVO> _varList = _section.getSubsectionVarList();
     int _row = ui->selectedVariablesTableWidget->rowCount();
     for (int i = 0; i < _varList.size();i++)
     {
         SolverVariableVO _variableVO = _varList.at(i);
         QString _varName = _variableVO.getVariableName();
         _selectedVariables.insert(_varName,_subsectionName);
         addVariableToTable(_varName,_subsectionName);
         _row++;
     }
 }
void TemplateDialog::addVariableToTable (SolverVariableVO _variable, int _row) private
Function that adds the variable elements to each row in the table.
Parameters
_variable
_row
Definition at line 284 of file templatedialog.cpp.
References QtableUtil::addIcon(), QtableUtil::addSelectableCheckColumn(), QtableUtil::addVariable(), ColumnCheck, ColumnTemplateHelp, ColumnVarName, SolverVariableVO::getVariableName(), and ui.
Referenced by addVariable(), fillMenuTable(), and refreshSelectVarTable().
 {
     QtableUtil _tableHelper;
     ui->variablesToSelectTableWidget->insertRow(_row);
     ui->variablesToSelectTableWidget->setItem(_row,ColumnVarName,_tableHelper.addVariable(_variable.getVariableName()));
     ui->variablesToSelectTableWidget->setItem(_row, ColumnTemplateHelp, _tableHelper.addIcon());
     ui->variablesToSelectTableWidget->setItem(_row,ColumnCheck,_tableHelper.addSelectableCheckColumn());
 }
void TemplateDialog::addVariableToTable (QString _name, QString _subsectionName) private
This function adds to the selected var table, the variable of the selection table.
Parameters
_name
_subsectionName
Definition at line 389 of file templatedialog.cpp.
References _userHasMadeChanges, QtableUtil::addIcon(), QtableUtil::addVariable(), IconDelete, SelectedColDelete, SelectedColHelp, SelectedColSectionName, SelectedColVariableName, and ui.
 {
     int _row = ui->selectedVariablesTableWidget->rowCount();
     ui->selectedVariablesTableWidget->insertRow(_row);
     QtableUtil _tableHelper;
     ui->selectedVariablesTableWidget->setItem(_row,SelectedColVariableName,_tableHelper.addVariable(_name));
     ui->selectedVariablesTableWidget->setItem(_row,SelectedColSectionName,_tableHelper.addVariable(_subsectionName));
     ui->selectedVariablesTableWidget->setItem(_row,SelectedColHelp, _tableHelper.addIcon());
     ui->selectedVariablesTableWidget->setCellWidget(_row,SelectedColDelete, _tableHelper.addIcon(IconDelete));
     _userHasMadeChanges = true;
 }
void TemplateDialog::disableVariableInTableToSelect (QString _varName) private
This function unchecks teh variable status in the selection table.
Parameters
_varName
Definition at line 370 of file templatedialog.cpp.
References ColumnCheck, ColumnVarName, StrEqual, and ui.
Referenced by on_selectedVariablesTableWidget_cellClicked().
 {
     int _totalRows = ui->variablesToSelectTableWidget->rowCount();
     for (int i = 0; i <_totalRows ;i++)
     {
         QString _nameTable = ui->variablesToSelectTableWidget->item(i,ColumnVarName)->text();
         if (QString::compare(_varName, _nameTable) == StrEqual)
             ui->variablesToSelectTableWidget->item(i,ColumnCheck)->setCheckState(Qt::Unchecked);
     }
 }
void TemplateDialog::fillMenuTable (QString _parentName, QList< SolverVariableVO > _list) private
This function fills the menu table.
Parameters
_parentName
_list
Definition at line 264 of file templatedialog.cpp.
References addVariableToTable(), and StrEqual.
Referenced by fillTableVarToSelect().
 {
     if ( (_parentName.isEmpty()) || (QString::compare(_parentName,"") == StrEqual) )
         return;
     for (int i= 0; i < _list.count();i++)
     {
         SolverVariableVO _vo = _list.at(i);
         addVariableToTable(_vo,i);
      }
 }
void TemplateDialog::fillTableVarToSelect (QString _parentSelected, QString _childSelected) private
This function loads the table for a specific menu item.
Parameters
_parentSelected
_childSelected
Definition at line 210 of file templatedialog.cpp.
References _solverManager, fillMenuTable(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), StrEqual, and updateSelectedVariableCheckBox().
Referenced by on_variablesToSelectTree_clicked().
 {
     if (QString::compare(_parentSelected,"") != StrEqual)
     {
         SolverSectionVO _sectionVO;
         _sectionVO =  _solverManager->getVariableListofSubsections(_childSelected);
         fillMenuTable(_childSelected,_sectionVO.getSubsectionVarList());
         updateSelectedVariableCheckBox(_sectionVO);
     }
 }
void TemplateDialog::initializeHelpers () private
This function initialize the helpers.
Definition at line 154 of file templatedialog.cpp.
References _searcherHelper, SearchPairHelper::registerUIElements(), and ui.
Referenced by TemplateDialog().
 {
     _searcherHelper.registerUIElements(ui->variablesToSelectTree,ui->searchLineEdit,ui->resultFoundNoLabel,
                                        ui->variablesToSelectTableWidget);
 }
void TemplateDialog::initializeTableHeaders () private
This function initialize the table headers.
Definition at line 165 of file templatedialog.cpp.
References ColNoVarSelected, ColNoVarToSelect, and ui.
Referenced by TemplateDialog().
 {
     // Setting up the columns for the variables to be selected
     ui->variablesToSelectTableWidget->setColumnCount(ColNoVarToSelect);
     ui->variablesToSelectTableWidget->setHorizontalHeaderLabels(QString("Selected;Name of the variable;Help").split(";"));
     ui->variablesToSelectTableWidget->horizontalHeader()->setVisible(true);
     ui->variablesToSelectTableWidget->resizeColumnsToContents();
     ui->variablesToSelectTableWidget->show();
     // Setting up the columns for the selected variables
     ui->selectedVariablesTableWidget->setColumnCount(ColNoVarSelected);
     ui->selectedVariablesTableWidget->setHorizontalHeaderLabels(QString("Section;Name of the variable;Help;Remove").split(";"));
     ui->selectedVariablesTableWidget->horizontalHeader()->setVisible(true);
     ui->selectedVariablesTableWidget->resizeColumnsToContents();
     ui->selectedVariablesTableWidget->show();
 }
void TemplateDialog::initializeVariables () private
This function initialize the variables.
Definition at line 143 of file templatedialog.cpp.
References _isLoadingTable, _selectedMenu, and _userHasMadeChanges.
Referenced by TemplateDialog().
 {
     _selectedMenu ="";
     _isLoadingTable = false;
     _userHasMadeChanges = false;
 }
void TemplateDialog::keyPressEvent (QKeyEvent * evt) private slot
This function controls the events of the key pressed.
Parameters
evt
Definition at line 516 of file templatedialog.cpp.
 {
     if(evt->key() == Qt::Key_Enter || evt->key() == Qt::Key_Return)
         return;
     QDialog::keyPressEvent(evt);
 }
void TemplateDialog::loadHelp (QString _helpText) private
This function loads the help dialog.
Parameters
_helpText
Definition at line 318 of file templatedialog.cpp.
References HelpDialog::loadHelpText(), and HelpDialog::setHelpText().
Referenced by on_selectedVariablesTableWidget_cellClicked(), and on_variablesToSelectTableWidget_cellClicked().
 {
     HelpDialog * _helpDialog = new HelpDialog(this);
     _helpDialog->setHelpText(_helpText);
     _helpDialog->loadHelpText();
     _helpDialog->exec();
 }
void TemplateDialog::loadMenu () private
This function loads teh menu list.
Definition at line 124 of file templatedialog.cpp.
References _variablesMenuToShow, and ui.
Referenced by setMenuList().
 {
     DomModel * _model;
    _model = new DomModel((* _variablesMenuToShow), this);
     // Setting and showing the model tree
     ui->variablesToSelectTree->setModel(_model);
     ui->variablesToSelectTree->hideColumn(1);
     ui->variablesToSelectTree->hideColumn(2);
     ui->variablesToSelectTree->show();
 }
void TemplateDialog::loadTemplate ()
Load all teh values of the template.
Definition at line 61 of file templatedialog.cpp.
References _solverManager, _userHasMadeChanges, addVariable(), SolverConfigManager::getAllPersonalizedSectionMenuList(), and ui.
Referenced by SolverHelper::editConfigurationTemplateByUser().
 {
     QList<SolverSectionVO> _list = _solverManager->getAllPersonalizedSectionMenuList();
     for (int i = 0; i <_list.size(); i++)
         addVariable(_list.at(i));
     ui->selectedVariablesTableWidget->resizeColumnsToContents();
     _userHasMadeChanges = false;
 }
void TemplateDialog::on_buttonBox_accepted () private slot
This function controls the acceptance by the user.
Definition at line 473 of file templatedialog.cpp.
References _selectedVariables, _solverManager, _userHasMadeChanges, SolverConfigManager::getAllSectionMenuList(), TemplateManager::saveTemplate(), and TemplateManager::setSectionTreeList().
 {
     if (!_userHasMadeChanges)
     {
         close();
         return;
     }
     QString _workingPath = QDir(QCoreApplication::applicationDirPath()).filePath(".templates");
                                 //QDir::currentPath()).filePath(".templates");
     if (!QDir(_workingPath).exists())
         QDir(QCoreApplication::applicationDirPath()).mkdir(".templates");
                     //QDir::currentPath()).mkdir(".templates");
     QString _binPath = QFileDialog::getSaveFileName(this, tr("Select a name for saving your template"),
                                                             _workingPath,
                                                             tr("Template Config File Type(*.xml)"));
     if (!_binPath.isNull())
     {
         TemplateManager _templateManager;
         _templateManager.setSectionTreeList(_solverManager->getAllSectionMenuList());
         _templateManager.saveTemplate(_binPath,_selectedVariables);
     }
     else
         return;
 }
void TemplateDialog::on_clearSearchButton_clicked () private slot
This function controls the clear search functionality.
Definition at line 463 of file templatedialog.cpp.
References _searcherHelper, SearchPairHelper::clearSearchStatus(), resetTable(), and ui.
 {
     resetTable(ui->variablesToSelectTableWidget);
     _searcherHelper.clearSearchStatus();
 }
void TemplateDialog::on_searchButton_clicked () private slot
This function controls the search functionality.
Definition at line 453 of file templatedialog.cpp.
References _searcherHelper, resetTable(), SearchPairHelper::searchItems(), and ui.
 {
     resetTable(ui->variablesToSelectTableWidget);
     _searcherHelper.searchItems();
 }
void TemplateDialog::on_searchLineEdit_returnPressed () private slot
This function controls the search functionality on key pressed.
Definition at line 505 of file templatedialog.cpp.
References _searcherHelper, resetTable(), SearchPairHelper::searchItems(), and ui.
 {
     ui->searchButton->setFocus();
      resetTable(ui->variablesToSelectTableWidget);
     _searcherHelper.searchItems();
 }
void TemplateDialog::on_selectedVariablesTableWidget_cellClicked (int row, int column) private slot
This function controls the behaviour over clicking in the cells of the selected var table.
Parameters
row
column
Definition at line 424 of file templatedialog.cpp.
References _selectedMenu, _selectedVariables, _solverManager, disableVariableInTableToSelect(), SolverConfigMenuHelper::getAssociatedHelpText(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), HTML_FORMAT_ON, loadHelp(), removeVariableFromTable(), SelectedColDelete, SelectedColHelp, SelectedColSectionName, SelectedColVariableName, StrEqual, and ui.
 {
     if (column == SelectedColHelp)
     {
         SolverConfigMenuHelper _uiHelper;
         QString _menu = ui->selectedVariablesTableWidget->item(row,SelectedColSectionName)->text();
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_menu);
         QString _nodeName = ui->selectedVariablesTableWidget->item(row,SelectedColVariableName)->text();
         QString _helpText = _uiHelper.getAssociatedHelpText(_nodeName,_sectionVO.getSubsectionVarList(),HTML_FORMAT_ON);
         loadHelp(_helpText);
         ui->selectedVariablesTableWidget->clearSelection();
     }else{
         if (column == SelectedColDelete)
         {
            QString _varName = ui->selectedVariablesTableWidget->item(row,SelectedColVariableName)->text();
            QString _sectionName = ui->selectedVariablesTableWidget->item(row,SelectedColSectionName)->text();
            removeVariableFromTable(_varName);
            _selectedVariables.remove(_varName);
            if (QString::compare(_selectedMenu, _sectionName) == StrEqual)
                disableVariableInTableToSelect(_varName);
         }
     }
 }
void TemplateDialog::on_variablesToSelectTableWidget_cellChanged (int row, int column) private slot
Slot function that controls those variables that have been selected.
Parameters
row
column
Definition at line 332 of file templatedialog.cpp.
References _isLoadingTable, _selectedMenu, _selectedVariables, ColumnCheck, ColumnVarName, refreshSelectVarTable(), and ui.
 {
     if ((!_isLoadingTable) && (column == ColumnCheck) )
     {
        QTableWidgetItem *item = ui->variablesToSelectTableWidget->item(row,ColumnCheck);
        QString _varName = ui->variablesToSelectTableWidget->item(row,ColumnVarName)->text();
        if (item->checkState() == Qt::Checked)
            _selectedVariables.insert(_varName,_selectedMenu);
        else
            if (item->checkState() == Qt::Unchecked)
                  _selectedVariables.remove(_varName);
        refreshSelectVarTable(item->checkState(), _varName);
     }
 }
void TemplateDialog::on_variablesToSelectTableWidget_cellClicked (int row, int column) private slot
This function launches the help menu
Parameters
row
column
Definition at line 299 of file templatedialog.cpp.
References _selectedMenu, _solverManager, ColumnTemplateHelp, ColumnVarName, SolverConfigMenuHelper::getAssociatedHelpText(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), HTML_FORMAT_ON, loadHelp(), and ui.
 {
     if(column == ColumnTemplateHelp)
     {
         SolverConfigMenuHelper _uiHelper;
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedMenu);
         QString _nodeName = ui->variablesToSelectTableWidget->item(row,ColumnVarName)->text();
         QString _helpText = _uiHelper.getAssociatedHelpText(_nodeName,_sectionVO.getSubsectionVarList(),HTML_FORMAT_ON);
         loadHelp(_helpText);
         ui->variablesToSelectTableWidget->clearSelection();
     }
 }
void TemplateDialog::on_variablesToSelectTree_clicked (const QModelIndex & index) private slot
This function controls when a menu item is clicked on the tree to show teh associated variables.
Parameters
index
Definition at line 188 of file templatedialog.cpp.
References _isLoadingTable, _searcherHelper, _selectedMenu, fillTableVarToSelect(), SearchPairHelper::refreshSearchInTree(), resetTable(), and ui.
 {
        QVariant _data = index.data(Qt::DisplayRole);
        QString _parent = index.parent().data(Qt::DisplayRole).toString();
        _selectedMenu = _data.toString();
        // Filling the table
        _isLoadingTable = true;
        resetTable(ui->variablesToSelectTableWidget);
        fillTableVarToSelect(_parent,_selectedMenu);
        _isLoadingTable = false;
        ui->variablesToSelectTableWidget->resizeColumnsToContents();
        ui->variablesToSelectTableWidget->show();
        _searcherHelper.refreshSearchInTree(index);
 }
void TemplateDialog::refreshSelectVarTable (bool _addVar, QString _variableName) private
This function refresh the table of selected variables.
Parameters
_addVar
_variableName
Definition at line 354 of file templatedialog.cpp.
References _selectedMenu, addVariableToTable(), removeVariableFromTable(), and ui.
Referenced by on_variablesToSelectTableWidget_cellChanged().
 {
     if (_addVar)
         addVariableToTable(_variableName,_selectedMenu);
     else
         removeVariableFromTable(_variableName);
     ui->selectedVariablesTableWidget->resizeColumnsToContents();
     ui->selectedVariablesTableWidget->show();
 }
void TemplateDialog::removeVariableFromTable (QString _name) private
This function remove a variaable from the selected var table.
Parameters
_name
Definition at line 407 of file templatedialog.cpp.
References SelectedColVariableName, StrEqual, and ui.
Referenced by on_selectedVariablesTableWidget_cellClicked(), and refreshSelectVarTable().
 {
     for (int _row = 0; _row < ui->selectedVariablesTableWidget->rowCount();_row++)
     {
         QString _varName = ui->selectedVariablesTableWidget->item(_row,SelectedColVariableName)->text();
         if (QString::compare(_varName,_name) == StrEqual)
             ui->selectedVariablesTableWidget->removeRow(_row);
     }
 }
void TemplateDialog::resetTable (QTableWidget * _table) private
This function resets the table.
Parameters
_table
Definition at line 247 of file templatedialog.cpp.
Referenced by on_clearSearchButton_clicked(), on_searchButton_clicked(), on_searchLineEdit_returnPressed(), and on_variablesToSelectTree_clicked().
 {
     if (_table->rowCount() > 0)
     {
         //  Delete all rows
         int _totalRows = _table->rowCount();
         for (int i = _totalRows; i >= 0; i--)
             _table->removeRow(i);
     }
 }
void TemplateDialog::setMenuList (QDomDocument * _menu) private
This function sets the menu list.
Parameters
_menu
Definition at line 113 of file templatedialog.cpp.
References _variablesMenuToShow, and loadMenu().
Referenced by setSolverConfigManager().
 {
     _variablesMenuToShow = _menu;
     loadMenu();
 }
void TemplateDialog::setSolverConfigManager (SolverConfigManager * _solverManagerData)
Function that sets the Solver Config manager to set the Menu List to be used.
Parameters
_solverManagerData
Definition at line 97 of file templatedialog.cpp.
References _searcherHelper, _solverManager, SolverConfigManager::getAllMenuList(), SolverConfigManager::initializeManager(), SolverConfigManager::isInitialized(), setMenuList(), and SearchPairHelper::setSolverManager().
Referenced by SolverHelper::createConfigurationTemplateByUser(), and SolverHelper::editConfigurationTemplateByUser().
 {
     _solverManager = _solverManagerData;
     if (!_solverManager->isInitialized())
         _solverManager->initializeManager();
     setMenuList(_solverManager->getAllMenuList());
     _searcherHelper.setSolverManager(_solverManager);
 }
void TemplateDialog::updateSelectedVariableCheckBox (SolverSectionVO _sectionVO) private
This funtion updates the values of a selected variable.
Parameters
_sectionVO
Definition at line 227 of file templatedialog.cpp.
References _selectedVariables, ColumnCheck, SolverSectionVO::getSubsectionVarList(), SolverVariableVO::getVariableName(), and ui.
Referenced by fillTableVarToSelect().
 {
     if (!_selectedVariables.isEmpty())
     {
        QList<SolverVariableVO> _list = _sectionVO.getSubsectionVarList();
        for (int i = 0; i < _list.size();i++)
        {
            SolverVariableVO _variable = _list.at(i);
            QString _varName = _variable.getVariableName();
            if (_selectedVariables.contains(_varName))
                ui->variablesToSelectTableWidget->item(i,ColumnCheck)->setCheckState(Qt::Checked);
        }
     }
 }
Member Data Documentation
bool TemplateDialog::_isLoadingTable private
Definition at line 52 of file templatedialog.h.
Referenced by initializeVariables(), on_variablesToSelectTableWidget_cellChanged(), and on_variablesToSelectTree_clicked().
SearchPairHelper TemplateDialog::_searcherHelper private
Definition at line 55 of file templatedialog.h.
Referenced by initializeHelpers(), on_clearSearchButton_clicked(), on_searchButton_clicked(), on_searchLineEdit_returnPressed(), on_variablesToSelectTree_clicked(), and setSolverConfigManager().
QString TemplateDialog::_selectedMenu private
Definition at line 51 of file templatedialog.h.
Referenced by initializeVariables(), on_selectedVariablesTableWidget_cellClicked(), on_variablesToSelectTableWidget_cellChanged(), on_variablesToSelectTableWidget_cellClicked(), on_variablesToSelectTree_clicked(), and refreshSelectVarTable().
QHash<QString,QString> TemplateDialog::_selectedVariables private
Definition at line 54 of file templatedialog.h.
Referenced by addVariable(), on_buttonBox_accepted(), on_selectedVariablesTableWidget_cellClicked(), on_variablesToSelectTableWidget_cellChanged(), and updateSelectedVariableCheckBox().
SolverConfigManager* TemplateDialog::_solverManager private
Definition at line 53 of file templatedialog.h.
Referenced by fillTableVarToSelect(), loadTemplate(), on_buttonBox_accepted(), on_selectedVariablesTableWidget_cellClicked(), on_variablesToSelectTableWidget_cellClicked(), and setSolverConfigManager().
bool TemplateDialog::_userHasMadeChanges private
Definition at line 56 of file templatedialog.h.
Referenced by addVariableToTable(), initializeVariables(), loadTemplate(), and on_buttonBox_accepted().
QDomDocument* TemplateDialog::_variablesMenuToShow private
Definition at line 50 of file templatedialog.h.
Referenced by loadMenu(), and setMenuList().
Ui::TemplateDialog* TemplateDialog::ui private
Definition at line 49 of file templatedialog.h.
Referenced by addVariable(), addVariableToTable(), disableVariableInTableToSelect(), initializeHelpers(), initializeTableHeaders(), loadMenu(), loadTemplate(), on_clearSearchButton_clicked(), on_searchButton_clicked(), on_searchLineEdit_returnPressed(), on_selectedVariablesTableWidget_cellClicked(), on_variablesToSelectTableWidget_cellChanged(), on_variablesToSelectTableWidget_cellClicked(), on_variablesToSelectTree_clicked(), refreshSelectVarTable(), removeVariableFromTable(), TemplateDialog(), updateSelectedVariableCheckBox(), and ~TemplateDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/templatedialog.h
Forms/SolverMenuDialog/templatedialog.cpp