BBIPED Platform: SolverBasicDialog Class Reference
SolverBasicDialog Class Reference
#include <solverbasicdialog.h>
Public Member Functions
SolverBasicDialog (QWidget *parent=0)
Constructor.
~SolverBasicDialog ()
Destructor.
void enablePersonalizedView ()
Enables the personalized view.
QHash< QString, QString > getConfigurationValues ()
Function to return the map with the config values.
QList< VirtualMrfVO > getVirtualMRFData ()
bool hasUserMadeChanges ()
Function that returns if the user has made changes.
bool isReseted ()
Check if the dialog is reseted to default.
void loadMenu ()
Load the corresponding Tree menu according with the user selection (basic view or advanced view)
void resetDialog ()
Function to reset the dialog variables.
void set3DMeshType (bool _val)
void setBasicView (bool _value)
Function to enable basic view.
void setConfigurationValues (QHash< QString, QString > _values)
Function to set the new values.
void setData (SolverConfigManager *_solverManagerData)
Functio to set the config manager.
void setVirtualMRFData (QList< VirtualMrfVO > _list)
Private Slots
void changedComboValueByUser (QString position)
Slot to control the change of the combo value by the user.
void handleItem (QString position)
This function handles the selection of the checkitems to be saved.
void keyPressEvent (QKeyEvent *evt)
This function controls the press event,.
void on_basicViewRadioButton_clicked ()
Function that restore the elements for the BASIC VIEW.
void on_clearSearchButton_clicked ()
This function resets all the views to their status before the search.
void on_customizedViewRadioButton_clicked ()
Function that restore the elements for the CUSTOMIZED VIEW.
void on_expertViewRadioButton_clicked ()
Function that restore the elements for the ADVANCED VIEW.
void on_resetDefaultButton_clicked ()
Function that controls the functionality when the user click the reset to default button.
void on_searchButton_clicked ()
This method provides the functionality of the search button.
void on_searchVariableNameLabelLineEdit_returnPressed ()
This function controls the return to search function.
void on_solverGroupButton_accepted ()
Function that controls the functionality when the user click the accept button.
void on_solverGroupButton_rejected ()
Function that controls the functionality when the user click the cancel button.
void on_solverMenuTree_clicked (const QModelIndex &index)
Fills in the table according the selected value by the user.
void on_solverVariablesTable_cellClicked (int row, int column)
This function help to manage the behaviour when clicking on the help column to launch the help dialog.
void on_summarySolverButton_clicked ()
Slot to control when the user check/uncheck the rotating frame menu element.
void textChangedSlot (QString _position)
Slot to control when the text is changed.
Private Member Functions
void addSignals ()
Function to add the signals.
void addSignalsSpecificWindows (QList< int > _rowIndexList)
void buildAllToolTips ()
Function to build all the tooltips.
void changeStatusChecked ()
bool checkIsDefaultValue (QString _cValue, int _row)
This function checks if the value stored in a row is a default value, returning a true, otherwise, returns false.
void expandParentChild (int _idParent)
void fillTable (QString _parentSelected, QString _childSelected)
This fucntion fills the table widget according user selection.
QString getAssociatedFileNameValue (QString _val, int _itemRow)
This function returns teh associated value name of a variable in the correspondent row.
QHash< QString, QString > getUserInput ()
Function to return the map with the user input.
void initializeHelpers ()
void insertRowSpecific (int _row)
void insertRowSpecificWithoutIcons (int _row)
void intializeVariables ()
Initialize all the main internal variables.
void launchSpecificWindow (QString position)
void launchVirtualRotatingDialog (SolverSectionVO _sectionVO)
void loadTableHeader ()
Loads the common table header values.
void loadTableHeaderSpecific (QStringList _labelList)
void resetAllConfigurationValues ()
Function to reset all.
void resetTable ()
Function to reset the table.
void resetToDefaultValue (int _itemRow)
void saveUserChanges (QString _value, int _itemRow)
Function to save the user changes made in the session.
void saveUserChangesSpecificWindow (QString _value, int _itemRow)
void setEnableCheckBoxes (bool _value)
void updatePersonalizedMenu ()
Function that restore the elements for the PERSONALIZED VIEW.
void updateRadioButtonCheckStatus (bool _val)
Function that updates the radio button status.
void updateTableHeaderSpecific ()
void updateUserValues (SolverSectionVO _solverSecvo)
Function to update with the user values.
void updateUserValuesSpecific ()
Private Attributes
QHash< QString, QString > _configValues
HelpDialog * _helpDialog
bool _is3DMesh
bool _isLoadingTable
bool _isVirtualSubMenuSelected
bool _resetedToDefault
RuleEngine _ruleEngine
SearchPairHelper _searchHelper
QString _selectedSubMenu
bool _showBasicView
QSignalMapper * _signalMapper
QSignalMapper * _signalMapperCheckList
QSignalMapper * _signalMapperNonEditText
QSignalMapper * _signalMapperTxtEdit
SolverConfigManager * _solverManager
SummaryDialog * _summaryDialog
bool _userHasModifiedValues
QList< VirtualMrfVO > _virtualUserValues
Ui::SolverBasicDialog * ui
Detailed Description
Definition at line 27 of file solverbasicdialog.h.
Constructor & Destructor Documentation
SolverBasicDialog::SolverBasicDialog (QWidget * parent = 0) explicit
Constructor.
Parameters
parent
Definition at line 51 of file solverbasicdialog.cpp.
References initializeHelpers(), intializeVariables(), loadTableHeader(), and ui.
                                                     :
     QDialog(parent),
     ui(new Ui::SolverBasicDialog)
 {
     ui->setupUi(this);
     intializeVariables();
     loadTableHeader();
     initializeHelpers();
 }
SolverBasicDialog::~SolverBasicDialog ()
Destructor.
Definition at line 69 of file solverbasicdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
void SolverBasicDialog::addSignals () private
Function to add the signals.
Definition at line 956 of file solverbasicdialog.cpp.
References _signalMapper, _signalMapperCheckList, _signalMapperTxtEdit, changedComboValueByUser(), ColumnSelVal, handleItem(), textChangedSlot(), and ui.
Referenced by fillTable().
 {
     bool _foundCombos = false;
     bool _foundLineEdit = false;
     bool _foundCheckList = false;
     if (ui->solverVariablesTable->rowCount() > 0)
     {
         for (int i = 0; i< ui->solverVariablesTable->rowCount();i++)
         {
                 QWidget * _item;
                 _item = ui->solverVariablesTable->cellWidget(i,ColumnSelVal);
                 if (_item)
                 {
                     QComboBox *_comboItem = qobject_cast<QComboBox *> (_item);
                     if (_comboItem)
                     {
                         if (_comboItem->isEditable())
{
                             connect(_comboItem,SIGNAL(editTextChanged(QString)),_signalMapper,SLOT(map()),Qt::UniqueConnection);
                             _signalMapper->setMapping(_comboItem,QString("%1-%2").arg(i).arg(ColumnSelVal));
                         }
                         connect(_comboItem, SIGNAL(currentIndexChanged(int)), _signalMapper, SLOT(map()),Qt::UniqueConnection);
                        _signalMapper->setMapping(_comboItem, QString("%1-%2").arg(i).arg(ColumnSelVal));
                         _foundCombos = true;
                     }else
                     {
                         QLineEdit * _lineEdit = qobject_cast<QLineEdit *> (_item);
                         if (_lineEdit)
{
                             connect(_lineEdit,SIGNAL(editingFinished()),_signalMapperTxtEdit,SLOT(map()),Qt::UniqueConnection);
                             _signalMapperTxtEdit->setMapping(_lineEdit,QString("%1").arg(i));
                             _foundLineEdit = true;
                         }
                         else
{
                             QListWidget * _checkList = qobject_cast<QListWidget *> (_item);
                             if (_checkList)
{
                                 connect(_checkList,SIGNAL(itemClicked(QListWidgetItem*)),_signalMapperCheckList,SLOT(map()),Qt::UniqueConnection);
                                _signalMapperCheckList->setMapping(_checkList,QString("%1").arg(i));
                                _foundCheckList = true;
                             }
                         }
                     }
                 }
         }
     }
     if (_foundCombos)
         connect(_signalMapper, SIGNAL(mapped(const QString &)),this, SLOT(changedComboValueByUser(const QString &)),Qt::UniqueConnection);
     if (_foundLineEdit)
         connect(_signalMapperTxtEdit, SIGNAL(mapped(const QString &)),this, SLOT(textChangedSlot(const QString &)),Qt::UniqueConnection);
     if (_foundCheckList)
         connect(_signalMapperCheckList, SIGNAL(mapped(const QString &)),this, SLOT(handleItem(const QString &)),Qt::UniqueConnection);
 }
void SolverBasicDialog::addSignalsSpecificWindows (QList< int > _rowIndexList) private
Definition at line 925 of file solverbasicdialog.cpp.
 {
  /*   int _totalRows = ui->solverVariablesTable->rowCount();
     bool _foundSpecificWindowNeeds = false;
     for (int _cIndex=0;_cIndex<_rowIndexList.size();_cIndex++)
     {
         int _cRow = _rowIndexList.at(_cIndex);
         if (_cRow < _totalRows)
         {
             QLineEdit *_lineEdit = qobject_cast<QLineEdit *> (ui->solverVariablesTable->cellWidget(_cRow,ColumnSelVal));
             if (_lineEdit)
             {
                 connect(_lineEdit,SIGNAL(textEdited(QString)),_signalMapperNonEditText,SLOT(map()),Qt::UniqueConnection);
                 _signalMapperNonEditText->setMapping(_lineEdit,QString("%1").arg(_cRow));
                 _foundSpecificWindowNeeds = true;
             }
         }
     }
     if (_foundSpecificWindowNeeds)
         connect(_signalMapperNonEditText, SIGNAL(mapped(const QString &)),this, SLOT(launchSpecificWindowSlot(const QString &)),Qt::UniqueConnection);*/
 }
void SolverBasicDialog::buildAllToolTips () private
Function to build all the tooltips.
Definition at line 361 of file solverbasicdialog.cpp.
References _selectedSubMenu, _solverManager, ColumnSelVal, ColumnVarName, SolverConfigMenuHelper::getAssociatedHelpText(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), HTML_FORMAT_OFF, and ui.
Referenced by on_solverMenuTree_clicked().
 {
     SolverConfigMenuHelper _uiHelper;
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
         int _totalRows = ui->solverVariablesTable->rowCount();
         for (int _row = 0; _row < _totalRows ; _row++)
         {
             QString _nodeName = ui->solverVariablesTable->item(_row,ColumnVarName)->text();
             QString _helpText = _uiHelper.getAssociatedHelpText(_nodeName,_sectionVO.getSubsectionVarList(),HTML_FORMAT_OFF);
             ui->solverVariablesTable->item(_row,ColumnVarName)->setToolTip(_helpText);
             ui->solverVariablesTable->item(_row,ColumnSelVal)->setToolTip(_helpText);
         }
 }
void SolverBasicDialog::changedComboValueByUser (QString position) private slot
Slot to control the change of the combo value by the user.
Parameters
position
Definition at line 437 of file solverbasicdialog.cpp.
References _isLoadingTable, ColumnCheck, getAssociatedFileNameValue(), saveUserChanges(), and ui.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
         QStringList coordinates = position.split("-");
         int row = coordinates[0].toInt();
         int col = coordinates[1].toInt();
         QComboBox* combo = (QComboBox*) ui->solverVariablesTable->cellWidget(row, col);
         ui->solverVariablesTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
         QString _value = combo->currentText();
         _value = getAssociatedFileNameValue(_value,row);
         saveUserChanges(_value,row);
     }
 }
void SolverBasicDialog::changeStatusChecked () private
bool SolverBasicDialog::checkIsDefaultValue (QString _cValue, int _row) private
This function checks if the value stored in a row is a default value, returning a true, otherwise, returns false.
Parameters
_cValue
_row
Returns
bool
Definition at line 416 of file solverbasicdialog.cpp.
References _selectedSubMenu, _solverManager, ColumnVarName, SolverSectionDAO::findValueNameByVariableName(), SolverConfigManager::getVariableListofSubsections(), SolverSectionDAO::isDefaultValueByFileName(), and ui.
Referenced by textChangedSlot().
 {
     bool _result = true;
     SolverSectionDAO _dao;
     QString _cVariable = ui->solverVariablesTable->item(_row,ColumnVarName)->text();
     SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
     QString _cVariableFileName = _dao.findValueNameByVariableName(_sectionVO,_cVariable);
     QList<SolverSectionVO> _list ;
     _list.append(_sectionVO);
     _result =_dao.isDefaultValueByFileName(_list,_cVariableFileName,_cValue);
     return _result;
 }
void SolverBasicDialog::enablePersonalizedView ()
Enables the personalized view.
Definition at line 895 of file solverbasicdialog.cpp.
References ui.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     ui->customizedViewRadioButton->setEnabled(true);
 }
void SolverBasicDialog::expandParentChild (int _idParent) private
void SolverBasicDialog::fillTable (QString _parentSelected, QString _childSelected) private
This fucntion fills the table widget according user selection.
Parameters
_parentSelected
_childSelected
Definition at line 236 of file solverbasicdialog.cpp.
References _solverManager, addSignals(), SolverConfigMenuHelper::fillMenuTable(), SolverConfigManager::getPersonalizedVariableListofSubsections(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), StrEqual, ui, and updateUserValues().
Referenced by on_solverMenuTree_clicked().
 {
     SolverSectionVO _sectionVO;
     SolverConfigMenuHelper _uiHelper;
     bool _isPersonalizedViewSelected = ui->customizedViewRadioButton->isChecked();
     if (QString::compare(_parentSelected,"") != StrEqual)
     {
         if (_isPersonalizedViewSelected)
             _sectionVO =  _solverManager->getPersonalizedVariableListofSubsections(_childSelected);
         else
             _sectionVO =  _solverManager->getVariableListofSubsections(_childSelected);
         QList<SolverVariableVO> _list = _sectionVO.getSubsectionVarList();
         _uiHelper.fillMenuTable(_childSelected,_parentSelected, ui->solverVariablesTable,_list);
         updateUserValues(_sectionVO);
         addSignals();
     }
 }
QString SolverBasicDialog::getAssociatedFileNameValue (QString _val, int _itemRow) private
This function returns teh associated value name of a variable in the correspondent row.
Parameters
_val
_itemRow
Returns
QString
Definition at line 555 of file solverbasicdialog.cpp.
References _selectedSubMenu, _solverManager, ColumnVarName, SolverSectionDAO::findValueNameByVariableName(), SolverSectionDAO::findVariableByFileName(), SolverVariableVO::getComboValueNamesList(), SolverVariableVO::getComboValuesList(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), and ui.
Referenced by changedComboValueByUser().
 {
     QString _result;
     SolverSectionDAO _solverDAO;
     QString _variableName =  ui->solverVariablesTable->item(_itemRow,ColumnVarName)->text();
     SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
     QString _keyName = _solverDAO.findValueNameByVariableName(_sectionVO,_variableName);
     SolverVariableVO _variable = _solverDAO.findVariableByFileName(_sectionVO.getSubsectionVarList(),_keyName);
     if (_variable.getComboValueNamesList().contains(_val))
     {
         QStringList _valList = _variable.getComboValuesList();
         int _pos = _variable.getComboValueNamesList().indexOf(_val);
         _result = _valList.at(_pos);
     }else
         _result = _val; // This is when the combo allows user entry values
    return _result;
 }
QHash< QString, QString > SolverBasicDialog::getConfigurationValues ()
Function to return the map with the config values.
Returns
QHash<QString, QString>
Definition at line 854 of file solverbasicdialog.cpp.
References _configValues.
Referenced by InputDataTabHelper::launchSolverConfigDialog().
 {
     return _configValues;
 }
QHash< QString, QString > SolverBasicDialog::getUserInput () private
Function to return the map with the user input.
Returns
QHash<QString, QString>
Definition at line 863 of file solverbasicdialog.cpp.
References _configValues.
 {
     return _configValues;
 }
QList< VirtualMrfVO > SolverBasicDialog::getVirtualMRFData ()
Definition at line 1150 of file solverbasicdialog.cpp.
References _virtualUserValues.
Referenced by InputDataTabHelper::launchSolverConfigDialog().
 {
     return _virtualUserValues;
 }
void SolverBasicDialog::handleItem (QString position) private slot
This function handles the selection of the checkitems to be saved.
Parameters
position
Definition at line 462 of file solverbasicdialog.cpp.
References _isLoadingTable, ColumnCheck, ColumnSelVal, ColumnVarName, saveUserChanges(), and ui.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
         int row = position.toInt();
          QListWidget * _checkList = qobject_cast<QListWidget *> (ui->solverVariablesTable->cellWidget(row,ColumnSelVal));
          if (!_checkList)
              return;
          // Recovering the previous value of the user
          QString _rowVariableName = ui->solverVariablesTable->item(row,ColumnVarName)->text();
          QStringList _valueList;
          for (int i = 0; i < _checkList->count();i++)
          {
              QListWidgetItem * _item = _checkList->item(i);
              if (_item->checkState() == Qt::Checked)
                  _valueList.append(_item->text());
          }
          QString _value = _valueList.join(",");
          ui->solverVariablesTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
          saveUserChanges(_value,row);
     }
 }
bool SolverBasicDialog::hasUserMadeChanges ()
Function that returns if the user has made changes.
Returns
bool
Definition at line 1025 of file solverbasicdialog.cpp.
References _userHasModifiedValues.
Referenced by InputDataTabHelper::launchSolverConfigDialog().
 {
     return _userHasModifiedValues;
 }
void SolverBasicDialog::initializeHelpers () private
Definition at line 78 of file solverbasicdialog.cpp.
References _searchHelper, _solverManager, SearchPairHelper::registerUIElements(), SearchPairHelper::setSolverManager(), and ui.
Referenced by SolverBasicDialog().
 {
     _searchHelper.registerUIElements(ui->solverMenuTree,ui->searchVariableNameLabelLineEdit,
                                      ui->resultsLabelToUpdate,ui->solverVariablesTable);
     _searchHelper.setSolverManager(_solverManager);
 }
void SolverBasicDialog::insertRowSpecific (int _row) private
Definition at line 275 of file solverbasicdialog.cpp.
References QtableUtil::addChangedColumn(), QtableUtil::addIcon(), QtableUtil::addNonEditableText(), ColumnCheck, ColumnHelp, ColumnSelVal, ColumnUnit, ColumnVarName, IconDelete, IconHelp, and ui.
Referenced by updateUserValuesSpecific().
  {
      QtableUtil _tableHelper;
      ui->solverVariablesTable->insertRow(_row);
      ui->solverVariablesTable->setItem(_row,ColumnCheck,_tableHelper.addChangedColumn());
      ui->solverVariablesTable->setItem(_row,ColumnVarName,_tableHelper.addNonEditableText("Click here to add a new Box"));
      ui->solverVariablesTable->setItem(_row,ColumnSelVal,_tableHelper.addNonEditableText(""));
      ui->solverVariablesTable->setCellWidget(_row,ColumnUnit,_tableHelper.addIcon(IconDelete));
      ui->solverVariablesTable->setCellWidget(_row,ColumnHelp,_tableHelper.addIcon(IconHelp));
  }
void SolverBasicDialog::insertRowSpecificWithoutIcons (int _row) private
Definition at line 287 of file solverbasicdialog.cpp.
References QtableUtil::addChangedColumn(), QtableUtil::addNonEditableText(), ColumnCheck, ColumnHelp, ColumnSelVal, ColumnUnit, ColumnVarName, and ui.
Referenced by launchSpecificWindow(), and updateTableHeaderSpecific().
  {
      QtableUtil _tableHelper;
      ui->solverVariablesTable->insertRow(_row);
      ui->solverVariablesTable->setItem(_row,ColumnCheck,_tableHelper.addChangedColumn());
      ui->solverVariablesTable->setItem(_row,ColumnVarName,_tableHelper.addNonEditableText("Click here to add a new Box"));
      ui->solverVariablesTable->setItem(_row,ColumnSelVal,_tableHelper.addNonEditableText(""));
      ui->solverVariablesTable->setItem(_row,ColumnUnit,_tableHelper.addNonEditableText(""));
      ui->solverVariablesTable->setItem(_row,ColumnHelp,_tableHelper.addNonEditableText(""));
   }
void SolverBasicDialog::intializeVariables () private
Initialize all the main internal variables.
Definition at line 89 of file solverbasicdialog.cpp.
References _is3DMesh, _isLoadingTable, _resetedToDefault, _signalMapper, _signalMapperCheckList, _signalMapperNonEditText, _signalMapperTxtEdit, _solverManager, and _userHasModifiedValues.
Referenced by SolverBasicDialog().
 {
     _solverManager = new SolverConfigManager();
     _isLoadingTable = false;
     _signalMapper = new QSignalMapper(this);
     _signalMapperTxtEdit = new QSignalMapper(this);
     _signalMapperCheckList = new QSignalMapper(this);
     _signalMapperNonEditText = new QSignalMapper(this);
     _resetedToDefault = false;
     _userHasModifiedValues = false;
     _is3DMesh = false;
 }
bool SolverBasicDialog::isReseted ()
Check if the dialog is reseted to default.
Returns
bool
Definition at line 875 of file solverbasicdialog.cpp.
References _resetedToDefault.
Referenced by InputDataTabHelper::launchSolverConfigDialog().
 {
     return _resetedToDefault;
 }
void SolverBasicDialog::keyPressEvent (QKeyEvent * evt) private slot
This function controls the press event,.
Parameters
evt
Definition at line 1138 of file solverbasicdialog.cpp.
 {
     if(evt->key() == Qt::Key_Enter || evt->key() == Qt::Key_Return)
         return;
     QDialog::keyPressEvent(evt);
 }
void SolverBasicDialog::launchSpecificWindow (QString position) private
Definition at line 489 of file solverbasicdialog.cpp.
References _isLoadingTable, _selectedSubMenu, _solverManager, QtableUtil::addIcon(), ColumnCheck, ColumnHelp, ColumnSelVal, ColumnUnit, ColumnVarName, DOMAIN_CLIPPING_MENU_NAME, DOMAIN_CLIPPING_VARIABLE_NAME, SolverSectionDAO::findValueNameByVariableName(), SolverSectionDAO::findVariableByFileName(), SolverVariableVO::getDefaultValue(), SolverSectionVO::getSubsectionVarList(), ClipDomainDialog::getValues(), SolverConfigManager::getVariableListofSubsections(), SolverVariableVO::getVariableName(), IconDelete, IconHelp, ClipDomainDialog::initializeDialog(), insertRowSpecificWithoutIcons(), saveUserChangesSpecificWindow(), ClipDomainDialog::setSolverVariable(), ClipDomainDialog::setUserValues(), StrEqual, and ui.
Referenced by on_solverVariablesTable_cellClicked().
 {
     if (!_isLoadingTable)
     {
         QString _variableName;
         int row = position.toInt();
         bool _isNewVariable = false;
         if (row == ui->solverVariablesTable->rowCount() -1)
             _isNewVariable = true;
         if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
             _variableName=DOMAIN_CLIPPING_VARIABLE_NAME;
         // Recovering the previous value of the user
         SolverSectionDAO _solverDAO;
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
         QString _keyName = _solverDAO.findValueNameByVariableName(_sectionVO,_variableName);
         SolverVariableVO _variable = _solverDAO.findVariableByFileName(_sectionVO.getSubsectionVarList(),_keyName);
         QTableWidgetItem * _item = ui->solverVariablesTable->item(row,ColumnSelVal);
         if (!_item)
              return;
         QString _value = _item->text();
         if ((_value.isEmpty()) || (_value.isNull()))
                 _value = _variable.getDefaultValue();
         // Launching the Dialog
         if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
         {
             ClipDomainDialog _clipDialog;
             _clipDialog.setUserValues(_value);
             _clipDialog.setSolverVariable(_variable);
             _clipDialog.initializeDialog();
             _clipDialog.exec();
             _value = _clipDialog.getValues();
         }
         else
             return;
         // Update the cell
         QtableUtil _tableHelper;
         ui->solverVariablesTable->item(row,ColumnVarName)->setText(_variable.getVariableName());
         ui->solverVariablesTable->item(row,ColumnSelVal)->setText(_value);
         ui->solverVariablesTable->item(row,ColumnCheck)->setCheckState(Qt::Checked);
         ui->solverVariablesTable->setCellWidget(row,ColumnUnit,_tableHelper.addIcon(IconDelete));
         ui->solverVariablesTable->setCellWidget(row,ColumnHelp,_tableHelper.addIcon(IconHelp));
          // Add a new row
         if (_isNewVariable)
             insertRowSpecificWithoutIcons(ui->solverVariablesTable->rowCount());
          // Save the changes
         saveUserChangesSpecificWindow(_value,row);
     }
 }
void SolverBasicDialog::launchVirtualRotatingDialog (SolverSectionVO _sectionVO) private
Definition at line 210 of file solverbasicdialog.cpp.
References _is3DMesh, _selectedSubMenu, _userHasModifiedValues, _virtualUserValues, VirtualRotatingDialog::getUserDefinedVirtualMRFValues(), VirtualRotatingDialog::hasUserAcceptModifiedValues(), VirtualRotatingDialog::initializeDialog(), VirtualRotatingDialog::set2DMeshCase(), VirtualRotatingDialog::setSelectedSubmenu(), VirtualRotatingDialog::setSolverSection(), and VirtualRotatingDialog::setUserDefinedVirtualMRFValues().
Referenced by on_solverMenuTree_clicked().
 {
     VirtualRotatingDialog _virtualDialog;
     _virtualDialog.setSelectedSubmenu(_selectedSubMenu);
     _virtualDialog.set2DMeshCase(_is3DMesh);
     _virtualDialog.setSolverSection(_sectionVO);
     _virtualDialog.setUserDefinedVirtualMRFValues(_virtualUserValues);
     _virtualDialog.initializeDialog();
     _virtualDialog.exec();
     if (_virtualDialog.hasUserAcceptModifiedValues())
     {
        _virtualUserValues = _virtualDialog.getUserDefinedVirtualMRFValues();
        _userHasModifiedValues = true;
     }
 }
void SolverBasicDialog::loadMenu ()
Load the corresponding Tree menu according with the user selection (basic view or advanced view)
Definition at line 124 of file solverbasicdialog.cpp.
References _searchHelper, _showBasicView, _solverManager, SolverConfigManager::getAdvancedMenuList(), SolverConfigManager::getBasicMenuList(), SolverConfigManager::initializeManager(), SolverConfigManager::isInitialized(), SearchPairHelper::setSolverManager(), and ui.
Referenced by InputDataTabHelper::initializeSolverBasicDialog(), on_basicViewRadioButton_clicked(), on_expertViewRadioButton_clicked(), and on_resetDefaultButton_clicked().
 {
     DomModel * _model;
     if (!_solverManager->isInitialized())
         _solverManager->initializeManager();
     if (_showBasicView)
        _model = new DomModel(*_solverManager->getBasicMenuList(), this);
     else
        _model = new DomModel(*_solverManager->getAdvancedMenuList(), this);
     // Setting and showing the model tree
     ui->solverMenuTree->setModel(_model);
     ui->solverMenuTree->hideColumn(1);
     ui->solverMenuTree->hideColumn(2);
     ui->solverMenuTree->show();
     _searchHelper.setSolverManager(_solverManager);
 }
void SolverBasicDialog::loadTableHeader () private
Loads the common table header values.
Definition at line 149 of file solverbasicdialog.cpp.
References ui.
Referenced by resetTable(), and SolverBasicDialog().
 {
     ui->solverVariablesTable->setColumnCount(5);
     ui->solverVariablesTable->setHorizontalHeaderLabels( QString("Changed;Variable;Value;Unit;Help").split(";"));
     ui->solverVariablesTable->horizontalHeader()->setVisible(true);
 }
void SolverBasicDialog::loadTableHeaderSpecific (QStringList _labelList) private
Definition at line 156 of file solverbasicdialog.cpp.
References ui.
Referenced by updateTableHeaderSpecific().
 {
     ui->solverVariablesTable->setColumnCount(5);
     ui->solverVariablesTable->setHorizontalHeaderLabels(_labelList);
     ui->solverVariablesTable->horizontalHeader()->setVisible(true);
 }
void SolverBasicDialog::on_basicViewRadioButton_clicked () private slot
Function that restore the elements for the BASIC VIEW.
Definition at line 1057 of file solverbasicdialog.cpp.
References _showBasicView, loadMenu(), resetTable(), and updateRadioButtonCheckStatus().
 {
     resetTable();
     updateRadioButtonCheckStatus(true);
     _showBasicView = true;
     loadMenu();
 }
void SolverBasicDialog::on_clearSearchButton_clicked () private slot
This function resets all the views to their status before the search.
Definition at line 1046 of file solverbasicdialog.cpp.
References _searchHelper, SearchPairHelper::clearSearchStatus(), and resetTable().
 {
     resetTable();
     _searchHelper.clearSearchStatus();
 }
void SolverBasicDialog::on_customizedViewRadioButton_clicked () private slot
Function that restore the elements for the CUSTOMIZED VIEW.
Definition at line 1112 of file solverbasicdialog.cpp.
References resetTable(), ui, and updatePersonalizedMenu().
 {
     resetTable();
     bool _val= true;
     ui->basicViewRadioButton->setChecked(!_val);
     ui->expertViewRadioButton->setChecked(!_val);
     ui->customizedViewRadioButton->setChecked(_val);
     updatePersonalizedMenu();
 }
void SolverBasicDialog::on_expertViewRadioButton_clicked () private slot
Function that restore the elements for the ADVANCED VIEW.
Definition at line 1099 of file solverbasicdialog.cpp.
References _showBasicView, loadMenu(), resetTable(), and updateRadioButtonCheckStatus().
 {
     resetTable();
     updateRadioButtonCheckStatus(false);
     _showBasicView = false;
     loadMenu();
 }
void SolverBasicDialog::on_resetDefaultButton_clicked () private slot
Function that controls the functionality when the user click the reset to default button.
Definition at line 689 of file solverbasicdialog.cpp.
References _resetedToDefault, _userHasModifiedValues, loadMenu(), resetAllConfigurationValues(), resetTable(), ShowMessageHelper::showMessageReset(), and ui.
 {
     ShowMessageHelper _showHelper;
     bool _doReset = _showHelper.showMessageReset();
    if (_doReset)
    {
         resetAllConfigurationValues();
         resetTable();
         if (!ui->customizedViewRadioButton->isChecked())
           loadMenu();
         _resetedToDefault = true;
         _userHasModifiedValues = true;
    }
 }
void SolverBasicDialog::on_searchButton_clicked () private slot
This method provides the functionality of the search button.
Definition at line 1034 of file solverbasicdialog.cpp.
References _searchHelper, resetTable(), and SearchPairHelper::searchItems().
 {
     resetTable();
    _searchHelper.searchItems();
 }
void SolverBasicDialog::on_searchVariableNameLabelLineEdit_returnPressed () private slot
This function controls the return to search function.
Definition at line 1126 of file solverbasicdialog.cpp.
References _searchHelper, resetTable(), SearchPairHelper::searchItems(), and ui.
 {
     ui->searchButton->setFocus();
     resetTable();
     _searchHelper.searchItems();
 }
void SolverBasicDialog::on_solverGroupButton_accepted () private slot
Function that controls the functionality when the user click the accept button.
Definition at line 664 of file solverbasicdialog.cpp.
 {
     close();
 }
void SolverBasicDialog::on_solverGroupButton_rejected () private slot
Function that controls the functionality when the user click the cancel button.
Definition at line 674 of file solverbasicdialog.cpp.
References _configValues, _resetedToDefault, and _userHasModifiedValues.
 {
     _configValues.clear();
     _resetedToDefault = false;
     _userHasModifiedValues = false;
     close();
 }
void SolverBasicDialog::on_solverMenuTree_clicked (const QModelIndex & index) private slot
Fills in the table according the selected value by the user.
Parameters
index
Definition at line 172 of file solverbasicdialog.cpp.
References _isLoadingTable, _searchHelper, _selectedSubMenu, _solverManager, buildAllToolTips(), DOMAIN_CLIPPING_MENU_NAME, fillTable(), SolverConfigManager::getVariableListofSubsections(), launchVirtualRotatingDialog(), SearchPairHelper::refreshSearchInTree(), resetTable(), StrEqual, ui, updateTableHeaderSpecific(), updateUserValuesSpecific(), and VIRTUAL_SUBSECTION_NAME.
 {
         QVariant _data = index.data(Qt::DisplayRole);
         _selectedSubMenu = _data.toString();
         _isLoadingTable = true;
         QString _parent = index.parent().data(Qt::DisplayRole).toString();
        resetTable();
        if (QString::compare(_selectedSubMenu,VIRTUAL_SUBSECTION_NAME) == StrEqual)
        {
            // Find the associated SolverVariableVO
            SolverSectionVO _sectionVO;
             _sectionVO=  _solverManager->getVariableListofSubsections(_selectedSubMenu);
             launchVirtualRotatingDialog(_sectionVO);
        }else
        {
            if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
            {
                updateUserValuesSpecific();
                updateTableHeaderSpecific();
            }else
                fillTable(_parent,_selectedSubMenu);
            _isLoadingTable = false;
            ui->solverVariablesTable->resizeColumnsToContents();
            ui->solverVariablesTable->show();
            buildAllToolTips();
         // In case a search has been done
            _searchHelper.refreshSearchInTree(index);
        }
 }
void SolverBasicDialog::on_solverVariablesTable_cellClicked (int row, int column) private slot
This function help to manage the behaviour when clicking on the help column to launch the help dialog.
Parameters
row
column
Definition at line 306 of file solverbasicdialog.cpp.
References _configValues, _helpDialog, _selectedSubMenu, _solverManager, _userHasModifiedValues, ColumnHelp, ColumnUnit, ColumnVarName, DOMAIN_CLIPPING_MENU_NAME, DOMAIN_CLIPPING_VARIABLE_FILENAME, SolverSectionDAO::findVariableByValueName(), SolverConfigMenuHelper::getAssociatedHelpText(), SolverSectionVO::getSubsectionVarList(), SolverConfigManager::getVariableListofSubsections(), HTML_FORMAT_ON, SolverVariableVO::isEmpty(), SolverVariableVO::isVariableSelectable(), launchSpecificWindow(), HelpDialog::loadHelpText(), HelpDialog::setHelpText(), StrEqual, and ui.
 {
     if (column == ColumnHelp)
     {
         // In the last row of the Domain clipping, there is no help Icon, so no help shall be displayed
         if  ((QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual) && (row == ( ui->solverVariablesTable->rowCount()-1)))
             return;
         // Normal help
         _helpDialog = new HelpDialog(this);
         SolverConfigMenuHelper _uiHelper;
         SolverSectionVO _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
         QString _nodeName = ui->solverVariablesTable->item(row,ColumnVarName)->text();
         SolverSectionDAO _sectionDao;
         SolverVariableVO _var =_sectionDao.findVariableByValueName(_sectionVO,_nodeName);
         bool _isSelectable = true;
         if (!_var.isEmpty())
             _isSelectable = _var.isVariableSelectable();
         if (!_isSelectable)
             return;
         QString _helpText = _uiHelper.getAssociatedHelpText(_nodeName,_sectionVO.getSubsectionVarList(),HTML_FORMAT_ON);
         // Launch the help dialog
         _helpDialog->setHelpText(_helpText);
         _helpDialog->loadHelpText();
         _helpDialog->exec();
         ui->solverVariablesTable->clearSelection();
     }else
         if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
             if (column == ColumnUnit)
             {
                 // Delete the row
                 int _lastRow = ui->solverVariablesTable->rowCount() -1; // The last row cannot be deleted
                 if (row < _lastRow)
                 {
                     QString _cValues = _configValues.value(DOMAIN_CLIPPING_VARIABLE_FILENAME);
                     QStringList _valuesList =_cValues.split(";");
                     _valuesList.removeAt(row);
                     _configValues.insert(DOMAIN_CLIPPING_VARIABLE_FILENAME,_valuesList.join(";"));
                     ui->solverVariablesTable->removeRow(row);
                     _userHasModifiedValues = true;
                 }
             }else
                launchSpecificWindow(QString::number(row));
 }
void SolverBasicDialog::on_summarySolverButton_clicked () private slot
Slot to control when the user check/uncheck the rotating frame menu element.
Parameters
arg1 Slot to control when the user check/uncheck the unsteady menu element
arg1 Function that controls the functionality when the user click the summary button
Definition at line 641 of file solverbasicdialog.cpp.
References _configValues, _solverManager, _summaryDialog, _userHasModifiedValues, SummaryDialog::buildSummaryTable(), SolverConfigManager::getAllSectionMenuList(), SummaryDialog::resetDialog(), resetTable(), SummaryDialog::setSectionMenuList(), SummaryDialog::setValuesToShow(), and SummaryDialog::userHasMadeChanges().
 {
     resetTable();
     _summaryDialog = new SummaryDialog(this);
     _summaryDialog->setValuesToShow(&_configValues);
     _summaryDialog->setSectionMenuList(_solverManager->getAllSectionMenuList());
     _summaryDialog->buildSummaryTable();
     _summaryDialog->exec();
     if (_summaryDialog->userHasMadeChanges())
     {
         _userHasModifiedValues = true;
         _summaryDialog->resetDialog();
     }
 }
void SolverBasicDialog::resetAllConfigurationValues () private
Function to reset all.
Definition at line 822 of file solverbasicdialog.cpp.
References _configValues, _solverManager, _virtualUserValues, and SolverConfigManager::initializeManager().
Referenced by on_resetDefaultButton_clicked().
 {
     _solverManager->initializeManager();
     _configValues.clear();
     _virtualUserValues.clear();
 }
void SolverBasicDialog::resetDialog ()
Function to reset the dialog variables.
Definition at line 108 of file solverbasicdialog.cpp.
References _isLoadingTable, _resetedToDefault, _searchHelper, _userHasModifiedValues, and SearchPairHelper::setTotalFoundElements().
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     _resetedToDefault = false;
     _userHasModifiedValues = false;
      _isLoadingTable = false;
     _searchHelper.setTotalFoundElements(0);
 }
void SolverBasicDialog::resetTable () private
Function to reset the table.
Definition at line 834 of file solverbasicdialog.cpp.
References loadTableHeader(), and ui.
Referenced by on_basicViewRadioButton_clicked(), on_clearSearchButton_clicked(), on_customizedViewRadioButton_clicked(), on_expertViewRadioButton_clicked(), on_resetDefaultButton_clicked(), on_searchButton_clicked(), on_searchVariableNameLabelLineEdit_returnPressed(), on_solverMenuTree_clicked(), and on_summarySolverButton_clicked().
 {
     if (ui->solverVariablesTable->rowCount() > 0)
     {
         //  Delete all rows
         int _totalRows = ui->solverVariablesTable->rowCount();
         for (int i = _totalRows; i >= 0; i--)
             ui->solverVariablesTable->removeRow(i);
     }
     loadTableHeader();
     //_specificWindowIndexList.clear();
 }
void SolverBasicDialog::resetToDefaultValue (int _itemRow) private
Definition at line 759 of file solverbasicdialog.cpp.
References _configValues, _selectedSubMenu, _solverManager, _userHasModifiedValues, ColumnVarName, SolverSectionDAO::findValueNameByVariableName(), SolverConfigManager::getVariableListofSubsections(), and ui.
Referenced by textChangedSlot().
 {
     SolverSectionDAO _solverDAO;
     SolverSectionVO _sectionVO;
     QString _keyName;
     _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
     _keyName = _solverDAO.findValueNameByVariableName(_sectionVO,
                 ui->solverVariablesTable->item(_itemRow,ColumnVarName)->text());
     _configValues.remove(_keyName);
     _userHasModifiedValues = true;
  }
void SolverBasicDialog::saveUserChanges (QString _value, int _itemRow) private
Function to save the user changes made in the session.
Parameters
_value
_itemRow
Definition at line 714 of file solverbasicdialog.cpp.
References _configValues, _selectedSubMenu, _solverManager, _userHasModifiedValues, ColumnVarName, SolverSectionDAO::findValueNameByVariableName(), SolverConfigManager::getVariableListofSubsections(), and ui.
Referenced by changedComboValueByUser(), handleItem(), and textChangedSlot().
 {
     SolverSectionDAO _solverDAO;
     SolverSectionVO _sectionVO;
     QString _variableName =  ui->solverVariablesTable->item(_itemRow,ColumnVarName)->text();
     QString _keyName;
     _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
     _keyName = _solverDAO.findValueNameByVariableName(_sectionVO,_variableName);
     _configValues.insert(_keyName,_value);
     _userHasModifiedValues = true;
  }
void SolverBasicDialog::saveUserChangesSpecificWindow (QString _value, int _itemRow) private
Definition at line 729 of file solverbasicdialog.cpp.
References _configValues, _selectedSubMenu, _solverManager, _userHasModifiedValues, ColumnVarName, DOMAIN_CLIPPING_MENU_NAME, SolverSectionDAO::findValueNameByVariableName(), SolverConfigManager::getVariableListofSubsections(), StrEqual, and ui.
Referenced by launchSpecificWindow().
 {
     if ((_value.isEmpty()) || (_value.isNull()))
         return;
     SolverSectionDAO _solverDAO;
     SolverSectionVO _sectionVO;
     QString _variableName =  ui->solverVariablesTable->item(_itemRow,ColumnVarName)->text();
     QString _keyName;
     _sectionVO =  _solverManager->getVariableListofSubsections(_selectedSubMenu);
     _keyName = _solverDAO.findValueNameByVariableName(_sectionVO,_variableName);
     if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
     {
         QString _oldValue = _configValues.value(_keyName);
         QStringList _oldValueList;
         if ((!_oldValue.isNull()) && (!_oldValue.isEmpty()) )
             _oldValueList = _configValues.value(_keyName).split(";");
         if ( (!_oldValue.isEmpty()) && (_itemRow < _oldValueList.size()-1))
             _oldValueList.replace(_itemRow,_value);
         else
             _oldValueList.append(_value);
         _configValues.insert(_keyName,_oldValueList.join(";"));
         _userHasModifiedValues = true;
     }
 }
void SolverBasicDialog::set3DMeshType (bool _val)
Definition at line 1154 of file solverbasicdialog.cpp.
References _is3DMesh.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     _is3DMesh = _val;
 }
void SolverBasicDialog::setBasicView (bool _value)
Function to enable basic view.
Parameters
_value
Definition at line 905 of file solverbasicdialog.cpp.
References _showBasicView.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
      _showBasicView = _value;
 }
void SolverBasicDialog::setConfigurationValues (QHash< QString, QString > _values)
Function to set the new values.
Parameters
QHash<QString,QString>
_values
Definition at line 886 of file solverbasicdialog.cpp.
References _configValues.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     _configValues = _values;
 }
void SolverBasicDialog::setData (SolverConfigManager * _solverManagerData)
Functio to set the config manager.
Parameters
_solverManagerData
Definition at line 916 of file solverbasicdialog.cpp.
References _solverManager.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     this->_solverManager = _solverManagerData;
 }
void SolverBasicDialog::setEnableCheckBoxes (bool _value) private
void SolverBasicDialog::setVirtualMRFData (QList< VirtualMrfVO > _list)
Definition at line 1145 of file solverbasicdialog.cpp.
References _virtualUserValues.
Referenced by InputDataTabHelper::initializeSolverBasicDialog().
 {
     _virtualUserValues =_list;
 }
void SolverBasicDialog::textChangedSlot (QString _position) private slot
Slot to control when the text is changed.
Parameters
_position
Definition at line 384 of file solverbasicdialog.cpp.
References _isLoadingTable, checkIsDefaultValue(), ColumnCheck, ColumnSelVal, resetToDefaultValue(), saveUserChanges(), and ui.
Referenced by addSignals().
 {
     if (!_isLoadingTable)
     {
        int _row = _position.toInt();
        QLineEdit * _lineEdit = (QLineEdit *) ui->solverVariablesTable->cellWidget(_row,ColumnSelVal);
        QString _value = _lineEdit->text();
        // Check if the value is different to the default value
        if (!checkIsDefaultValue(_value,_row))
        {
            ui->solverVariablesTable->item(_row,ColumnCheck)->setCheckState(Qt::Checked);
            saveUserChanges(_value,_row);
        }else
        {
            ui->solverVariablesTable->item(_row,ColumnCheck)->setCheckState(Qt::Unchecked);
            resetToDefaultValue(_row);
        }
     }
 }
void SolverBasicDialog::updatePersonalizedMenu () private
Function that restore the elements for the PERSONALIZED VIEW.
Definition at line 1082 of file solverbasicdialog.cpp.
References _searchHelper, _solverManager, SolverConfigManager::getPersonalizedTemplateMenuList(), SearchPairHelper::setSolverManager(), and ui.
Referenced by on_customizedViewRadioButton_clicked().
 {
     DomModel * _model;
    _model = new DomModel(*_solverManager->getPersonalizedTemplateMenuList(), this);
     // Setting and showing the model tree
     ui->solverMenuTree->setModel(_model);
     ui->solverMenuTree->hideColumn(1);
     ui->solverMenuTree->hideColumn(2);
     ui->solverMenuTree->show();
     _searchHelper.setSolverManager(_solverManager);
 }
void SolverBasicDialog::updateRadioButtonCheckStatus (bool _val) private
Function that updates the radio button status.
Parameters
_val
Definition at line 1071 of file solverbasicdialog.cpp.
References ui.
Referenced by on_basicViewRadioButton_clicked(), and on_expertViewRadioButton_clicked().
 {
     ui->basicViewRadioButton->setChecked(_val);
     ui->expertViewRadioButton->setChecked(!_val);
     ui->customizedViewRadioButton->setChecked(false);
 }
void SolverBasicDialog::updateTableHeaderSpecific () private
Definition at line 258 of file solverbasicdialog.cpp.
References QtableUtil::addIcon(), ColumnUnit, IconDelete, insertRowSpecificWithoutIcons(), loadTableHeaderSpecific(), and ui.
Referenced by on_solverMenuTree_clicked().
   {
         // Change Unit Column Name as Delete
         QStringList _newTableHeaders = QString("Changed;Variable;Value;Delete;Help").split(";");
         loadTableHeaderSpecific(_newTableHeaders);
         // Create first row with no-values and a delete icon
         int _lastRow = ui->solverVariablesTable->rowCount();
         // Add a delete icon in the rest of the table
         QtableUtil _tableHelper;
         for (int _row=0; _row < ui->solverVariablesTable->rowCount()-1;_row++)
             ui->solverVariablesTable->setCellWidget(_row, ColumnUnit,_tableHelper.addIcon(IconDelete));
         // Add extra row with no values to create a new clipping
         insertRowSpecificWithoutIcons(_lastRow);
   }
void SolverBasicDialog::updateUserValues (SolverSectionVO _solverSecvo) private
Function to update with the user values.
Parameters
_solverSecvo
Definition at line 781 of file solverbasicdialog.cpp.
References _configValues, ui, and SolverConfigMenuHelper::updateTableWithUserValues().
Referenced by fillTable().
 {
     SolverConfigMenuHelper _uiHelper;
     _uiHelper.updateTableWithUserValues(_solverSecvo,ui->solverVariablesTable, _configValues);
 }
void SolverBasicDialog::updateUserValuesSpecific () private
Definition at line 788 of file solverbasicdialog.cpp.
References _configValues, _selectedSubMenu, ColumnCheck, ColumnSelVal, ColumnVarName, DOMAIN_CLIPPING_MENU_NAME, DOMAIN_CLIPPING_VARIABLE_FILENAME, DOMAIN_CLIPPING_VARIABLE_NAME, insertRowSpecific(), StrEqual, and ui.
Referenced by on_solverMenuTree_clicked().
 {
     if (QString::compare(_selectedSubMenu,DOMAIN_CLIPPING_MENU_NAME) == StrEqual)
     {
         QString _aux = _configValues.value(DOMAIN_CLIPPING_VARIABLE_FILENAME);
         if (_aux.isEmpty())
             return;
         QStringList _userVal =_configValues.value(DOMAIN_CLIPPING_VARIABLE_FILENAME).split(";");
         if ((_userVal.isEmpty()) || (_userVal.size() == 0))
             insertRowSpecific(ui->solverVariablesTable->rowCount());
         else
         {
             int _noValues = _userVal.size();
             for (int _row=0; _row <_noValues;_row++)
             {
                 insertRowSpecific(_row);
                 ui->solverVariablesTable->item(_row,ColumnVarName)->setText(DOMAIN_CLIPPING_VARIABLE_NAME);
                 ui->solverVariablesTable->item(_row,ColumnSelVal)->setText(_userVal.at(_row));
                 ui->solverVariablesTable->item(_row,ColumnCheck)->setCheckState(Qt::Checked);
             }
         }
     }
 }
Member Data Documentation
QHash<QString, QString> SolverBasicDialog::_configValues private
Definition at line 89 of file solverbasicdialog.h.
Referenced by getConfigurationValues(), getUserInput(), on_solverGroupButton_rejected(), on_solverVariablesTable_cellClicked(), on_summarySolverButton_clicked(), resetAllConfigurationValues(), resetToDefaultValue(), saveUserChanges(), saveUserChangesSpecificWindow(), setConfigurationValues(), updateUserValues(), and updateUserValuesSpecific().
HelpDialog* SolverBasicDialog::_helpDialog private
Definition at line 84 of file solverbasicdialog.h.
Referenced by on_solverVariablesTable_cellClicked().
bool SolverBasicDialog::_is3DMesh private
Definition at line 120 of file solverbasicdialog.h.
Referenced by intializeVariables(), launchVirtualRotatingDialog(), and set3DMeshType().
bool SolverBasicDialog::_isLoadingTable private
Definition at line 99 of file solverbasicdialog.h.
Referenced by changedComboValueByUser(), handleItem(), intializeVariables(), launchSpecificWindow(), on_solverMenuTree_clicked(), resetDialog(), and textChangedSlot().
bool SolverBasicDialog::_isVirtualSubMenuSelected private
Definition at line 104 of file solverbasicdialog.h.
bool SolverBasicDialog::_resetedToDefault private
Definition at line 100 of file solverbasicdialog.h.
Referenced by intializeVariables(), isReseted(), on_resetDefaultButton_clicked(), on_solverGroupButton_rejected(), and resetDialog().
RuleEngine SolverBasicDialog::_ruleEngine private
Definition at line 111 of file solverbasicdialog.h.
SearchPairHelper SolverBasicDialog::_searchHelper private
Definition at line 107 of file solverbasicdialog.h.
Referenced by initializeHelpers(), loadMenu(), on_clearSearchButton_clicked(), on_searchButton_clicked(), on_searchVariableNameLabelLineEdit_returnPressed(), on_solverMenuTree_clicked(), resetDialog(), and updatePersonalizedMenu().
QString SolverBasicDialog::_selectedSubMenu private
Definition at line 90 of file solverbasicdialog.h.
Referenced by buildAllToolTips(), checkIsDefaultValue(), getAssociatedFileNameValue(), launchSpecificWindow(), launchVirtualRotatingDialog(), on_solverMenuTree_clicked(), on_solverVariablesTable_cellClicked(), resetToDefaultValue(), saveUserChanges(), saveUserChangesSpecificWindow(), and updateUserValuesSpecific().
bool SolverBasicDialog::_showBasicView private
Definition at line 101 of file solverbasicdialog.h.
Referenced by loadMenu(), on_basicViewRadioButton_clicked(), on_expertViewRadioButton_clicked(), and setBasicView().
QSignalMapper* SolverBasicDialog::_signalMapper private
Definition at line 93 of file solverbasicdialog.h.
Referenced by addSignals(), and intializeVariables().
QSignalMapper* SolverBasicDialog::_signalMapperCheckList private
Definition at line 95 of file solverbasicdialog.h.
Referenced by addSignals(), and intializeVariables().
QSignalMapper* SolverBasicDialog::_signalMapperNonEditText private
Definition at line 96 of file solverbasicdialog.h.
Referenced by intializeVariables().
QSignalMapper* SolverBasicDialog::_signalMapperTxtEdit private
Definition at line 94 of file solverbasicdialog.h.
Referenced by addSignals(), and intializeVariables().
SolverConfigManager* SolverBasicDialog::_solverManager private
Definition at line 88 of file solverbasicdialog.h.
Referenced by buildAllToolTips(), checkIsDefaultValue(), fillTable(), getAssociatedFileNameValue(), initializeHelpers(), intializeVariables(), launchSpecificWindow(), loadMenu(), on_solverMenuTree_clicked(), on_solverVariablesTable_cellClicked(), on_summarySolverButton_clicked(), resetAllConfigurationValues(), resetToDefaultValue(), saveUserChanges(), saveUserChangesSpecificWindow(), setData(), and updatePersonalizedMenu().
SummaryDialog* SolverBasicDialog::_summaryDialog private
Definition at line 85 of file solverbasicdialog.h.
Referenced by on_summarySolverButton_clicked().
bool SolverBasicDialog::_userHasModifiedValues private
Definition at line 103 of file solverbasicdialog.h.
Referenced by hasUserMadeChanges(), intializeVariables(), launchVirtualRotatingDialog(), on_resetDefaultButton_clicked(), on_solverGroupButton_rejected(), on_solverVariablesTable_cellClicked(), on_summarySolverButton_clicked(), resetDialog(), resetToDefaultValue(), saveUserChanges(), and saveUserChangesSpecificWindow().
QList<VirtualMrfVO> SolverBasicDialog::_virtualUserValues private
Definition at line 117 of file solverbasicdialog.h.
Referenced by getVirtualMRFData(), launchVirtualRotatingDialog(), resetAllConfigurationValues(), and setVirtualMRFData().
Ui::SolverBasicDialog* SolverBasicDialog::ui private
Definition at line 83 of file solverbasicdialog.h.
Referenced by addSignals(), buildAllToolTips(), changedComboValueByUser(), checkIsDefaultValue(), enablePersonalizedView(), fillTable(), getAssociatedFileNameValue(), handleItem(), initializeHelpers(), insertRowSpecific(), insertRowSpecificWithoutIcons(), launchSpecificWindow(), loadMenu(), loadTableHeader(), loadTableHeaderSpecific(), on_customizedViewRadioButton_clicked(), on_resetDefaultButton_clicked(), on_searchVariableNameLabelLineEdit_returnPressed(), on_solverMenuTree_clicked(), on_solverVariablesTable_cellClicked(), resetTable(), resetToDefaultValue(), saveUserChanges(), saveUserChangesSpecificWindow(), SolverBasicDialog(), textChangedSlot(), updatePersonalizedMenu(), updateRadioButtonCheckStatus(), updateTableHeaderSpecific(), updateUserValues(), updateUserValuesSpecific(), and ~SolverBasicDialog().
The documentation for this class was generated from the following files:
Forms/SolverMenuDialog/solverbasicdialog.h
Forms/SolverMenuDialog/solverbasicdialog.cpp